### ISSUE TITLE
[Suggestion] Ender-farmer's Lead config options

### ISSUE THREAD

**Issue by Partonetrain** [Shadows-of-Fire/Apotheosis#100]
The Ender-farmer's Lead lacks any options in garden.cfg. I suggest a config for its durability, a mob blacklist, and possibly a whitelist.

**Comment by Partonetrain** [comment]
Also, the recipe for the Ender-Farmer's Lead isn't in JSON and can't be overwritten as it is defined in code. I might make a quick PR to change that

**Comment by Shadows-of-Fire** [comment]
The underlying system attributes the ability for json recipes to override mine, but uh, its a bit of a problem while the names are still dynamically generated.  Placebo needs to be updated to use output specific names instead of r1...rn

**Comment by Partonetrain** [comment]
![image](https://user-images.githubusercontent.com/19861808/67508847-6b0b4880-f657-11e9-83fe-082ec314515a.png)

The name of the recipe is just apotheosis:0; I have a (valid) file in my datapack data\apotheosis\recipes\0.json but it doesn't replace it as I'd expect.

I assume it's defined in code so the recipe can be disabled with the module, but if the garden module is disabled the JSON will error with no output item, which is not a big deal if it means making the recipe customizable (IMO)

**Comment by Shadows-of-Fire** [comment]
Huh.  It *should* replace it, given that https://github.com/Shadows-of-Fire/Placebo/blob/1.14/src/main/java/shadows/placebo/recipe/RecipeHelper.java#L117 checks for existance before creating the recipe, unless that check needs to be different.

**Comment by Partonetrain** [comment]
When does that check happen? datapacks are read on world load or /reload. 

Here's a datapack that only overwrites your recipe: 
[farmersleashrecipe.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/3768759/farmersleashrecipe.zip)

Putting it in saves/<savename>/datapacks doesn't change the recipe

**Comment by Shadows-of-Fire** [comment]
That recipe adding code is called every reload, and my reload handler runs immediately after the recipe reload handler, so I'll probably need to debug this later

**Comment by Shadows-of-Fire** [comment]
Ah, figured it out.  Turns out the recipe loader *is* finding the old recipe, but it's still placing it in because it thinks it's doing a shapeless recipe replacement on the existing recipe instead of yielding to a different one.  I need to make these apply in different steps.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Placebo/commit/75598a325aeac9ca7e38eb89d2dd12e12f1757f2

**Comment by Partonetrain** [comment]
Sorry it took me a week to test it, but seems I still can't replace the recipe. I have the same datapack, just renamed the file to farmers_leash.json as per the Placebo update. Renaming the file to anything other than "farmers_leash" has both my recipe and the mod's recipe show up, so it's definitely loaded, just not overriding the default one. :/

**Comment by Shadows-of-Fire** [comment]
Welp, back to the testing department...

**Comment by Partonetrain** [comment]
It works! Thanks a bunch

**Comment by k1r0s** [comment]
any changes to backport this to 1.12 ?

**Comment by superon** [comment]
from what i understand here this issue should not have been close as completed, the original issue still stands.
only the "also" appended in a later post about the recipe was fixed.
the original post was "The Ender-farmer's Lead lacks any options in garden.cfg. I suggest a config for its durability, a mob blacklist, and possibly a whitelist."  if this was added pls forgive me i'm unable to find where or how to access the whitelist for the ender lead (1.20.1)
