### ISSUE TITLE
Mob Spawner Config

### ISSUE THREAD

**Issue by RenRants** [Shadows-of-Fire/Apotheosis#1000]
The 1.20 version of the game appears to have no deadly module, it's been included in the adventure module instead. In the adventure module, there seems to be no way to adjust the frequency of rogue spawners generating in each chunk. I've been playing the game and it's impossible to go mining because there is literally 2-3 spawners in each chunk and I have to fight entire hoards of enemies just to travel a few blocks. am I missing something?
![apo generation](https://github.com/Shadows-of-Fire/Apotheosis/assets/143908552/fc431f99-4cd8-4381-9cbe-2aac6d08e9fc)

**Comment by Shadows-of-Fire** [comment]
All configuration to worldgen must be done through a datapack now. See https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/worldgen/placed_feature for the existing files. The thing you'll probably want to turn down is the `count` field.
