### ISSUE TITLE
Structure Generation for Apotheosis towers generating in random locations.

### ISSUE THREAD

**Issue by Zelioth** [Shadows-of-Fire/Apotheosis#1001]
Minecraft 1.20.1
Forge 47.1.47
Apothosis 7.0.5

Seems to be some sort of issue with structure generation based on location. It varies but can be random. Reason I bring this up is because the structures are generating in strange places and just look out of place with floating islands under them. 

Can be recreated on any MC world with the Apotheosis mod included 

![2023-09-03_17 04 08](https://github.com/Shadows-of-Fire/Apotheosis/assets/77481431/15345a7f-6060-47b4-bcd3-6f70bce1a05c)
![2023-09-03_17 06 39](https://github.com/Shadows-of-Fire/Apotheosis/assets/77481431/51458ec5-f724-40bf-aec6-e419e8888f0e)
![2023-09-03_17 07 02](https://github.com/Shadows-of-Fire/Apotheosis/assets/77481431/659ce13b-e39c-4c70-be97-6fde361dbf90)
![2023-09-03_15 26 55](https://github.com/Shadows-of-Fire/Apotheosis/assets/77481431/f307cb8a-6dc2-408d-a385-d469e343be81)

**Comment by Shadows-of-Fire** [comment]
Think the biome tags need to be made more granular.
