### ISSUE TITLE
[Bug]Unable to work on Arclight server in 1.19.2

### ISSUE THREAD

**Issue by LrbsX** [Shadows-of-Fire/Apotheosis#1002]
Unable to work on arclight server,Server startup was stopped。
see the log
[lastest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/12512064/lastest.log)

version:Apotheosis-1.19.2-6.4.0
forge:1.19.2-Forge_43.2.14
Arclight:Arclight-1.19.2-1.0.2
https://github.com/IzzelAliz/Arclight

**Comment by Shadows-of-Fire** [comment]
Arclight is not a supported platform.
