### ISSUE TITLE
Gem cutter misuse Crash to Desktop

### ISSUE THREAD

**Issue by wraithhawit** [Shadows-of-Fire/Apotheosis#1003]
I was trying to figure out how to operate the gem cutter and I put crushed gems in the slot where the gem is supposed to go and the game crashed. 

1.20.1 - 7.0.5 
ATM9 - 0.63
[crash-2023-09-05_04.12.02-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12521335/crash-2023-09-05_04.12.02-client.txt)

**Comment by LuckyDog322** [comment]
I also encountered the same problem

**Comment by Tolgajk3** [comment]
yess

**Comment by xVeNoMZz** [comment]
So, no solution until now?
