### ISSUE TITLE
In curseforge app, required libraries are not added when adding apotheosis

### ISSUE THREAD

**Issue by Warimano** [Shadows-of-Fire/Apotheosis#1005]
I wanted to include some of your mods(namely Apotheosis and Hostile Neural Networks) into a private pack but it simply crashed on startup. It didn't even reach the image in-game that tells you what is missing for a certain mod to work. Only way for me to reach that page was to disable/remove Apotheosis.

Suggested solution: Make it so that when adding one of your mods to a pack in curseforge, have it automatically add required libraries, or at the very least make sure that if you miss adding a library, that the in-game page stating what libraries are missing is reached.

**Comment by Shadows-of-Fire** [comment]
CF automatically downloads projects marked as required dependencies on download, of which all of apoth's are declared appropriately.  You may have encountered a CF bug, but everything I can do is done correctly.
