### ISSUE TITLE
1.20.1 crash when disable adventure mode

### ISSUE THREAD

**Issue by CubeTwo** [Shadows-of-Fire/Apotheosis#1006]
if you disable adventure mode in config and try create game world game crashes

Apotheosis-1.20.1-7.0.5
ApothicAttributes-1.20.1-1.1.4
forge 47.1.47

[crash-2023-09-06_22.25.21-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12541731/crash-2023-09-06_22.25.21-client.txt)

**Comment by Shadows-of-Fire** [comment]
The adventure module can only be disabled when using NeoForge, as the issue was a Forge bug that has only been fixed in neo.

See #989

**Comment by lockf** [comment]
Forge  47.2.23, that no longer happens
