### ISSUE TITLE
Nature's Blessing doesn't work on certain plants that can be bonemealed

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#1007]
Demon's Dream from Occultism, Magebloom from Ars Nouveau, and Sage from Hexerei cannot be grown using a hoe with Nature's Blessing. 

All of these plants accept Bone Meal applied by hand.

Version: Apotheosis-1.19.2-6.3.5

Tested with an Ironwood Hoe from Twilight Forest.

Oddly, when using a Diamond Hoe, Demon's Dream works fine, but only if directly clicked. The rest do not, either from AoE or from direct interaction.

**Comment by MuteTiefling** [comment]
Seems to interact poorly with quark's Hoe Harvesting feature.

**Comment by Shadows-of-Fire** [comment]
Closing since it seems to be a quark interaction thing.
