### ISSUE TITLE
[Suggestion] Socket gem slot blacklist

### ISSUE THREAD

**Issue by foklan** [Shadows-of-Fire/Apotheosis#1008]
Is there any option to blacklist specific items that will not be equipped with gem slot after crafting the item?

I'm asking because in some mods (e.g. MineColonies https://github.com/ldtteam/minecolonies/issues/9100) there are quests which are requesting wearable items and it is impossible to complete them. 
I believe it's caused by adding NBT data to the item by adding socket slot.

So if there isn't this feature I think it would be nice to have it in the future.

**Comment by Shadows-of-Fire** [comment]
I'm not sure what you are referring to.  Apotheosis does not apply gem slots to freshly crafted items, only those generated from loot or those reforged using the Reforging table.

**Comment by foklan** [comment]
That's strange because when I craft something it has gem slot by default. Even when I'm looking at it in JEI.
![2023-09-08_14-58](https://github.com/Shadows-of-Fire/Apotheosis/assets/34000783/d6c7613e-fcff-4e25-9a4b-deb64f97504b)

**Comment by SiverDX** [comment]
Isn't that socket from https://www.curseforge.com/minecraft/mc-mods/passive-skill-tree?

Apotheosis should be grey
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/85c76510-fd2a-4d77-bb92-c1240120d1ab)

**Comment by foklan** [comment]
Interesting, that could be it. I don't have that much knowledge about other mods so I thought this mod adds sockets for its gems.
I might check that mod you mentioned instead.
Thanks for clarification.
