### ISSUE TITLE
Gem cutting table collapse

### ISSUE THREAD

**Issue by LuckyDog322** [Shadows-of-Fire/Apotheosis#1009]
When using the gemstone cutting table to insert items, it instantly crashes

Versions: 1.20.1

Versions: 7.0.5
/
[crash-2023-09-08_15.44.28-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12557077/crash-2023-09-08_15.44.28-client.txt)

**Comment by Shadows-of-Fire** [comment]
Why did you open another issue after already seeing #1003

**Comment by LuckyDog322** [comment]
I'm not sure if the two of us are the same source of collapse
