### ISSUE TITLE
Client-side crash anvil combination Tome of the Miners + enchanted book

### ISSUE THREAD

**Issue by SkippyMitch** [Shadows-of-Fire/Apotheosis#101]
I put these two items together in an anvil and crashed my client. I didn't expect to be able to combine the two really, but of course crashing sucks, so here is the report.
Crash report:
https://pastebin.com/FNa20ASv

Screenshot showing the two items, and their enchantments. 
![tome crash10 41](https://user-images.githubusercontent.com/27940256/67152956-448b8d00-f2a6-11e9-8195-4711dc0c4833.png)

**Comment by Shadows-of-Fire** [comment]
Somehow there's a null enchantment on the tome, which is... interesting.  Not sure exactly what to do about that.

**Comment by Shadows-of-Fire** [comment]
I don't entirely know how you got a null enchantment on the tome, but the vanilla code paths aren't really within my reach to edit.
