### ISSUE TITLE
Rogue Spawner Crash

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#1010]
Minecraft v1.20.1
Forge v47.1.47
Apotheosis v7.0.5

When entering my world, I get this crash
[Crash Report](https://gist.github.com/WenXin20/12d1baf40e34422caf0faf5ee5977a24)

**Comment by Shadows-of-Fire** [comment]
Did you disable all the rogue spawners via datapack but not disable the feature?

**Comment by WenXin20** [comment]
No, I don't have any datapacks disabling them, unless the Repurpose Structures datapacks do that.

**Comment by Shadows-of-Fire** [comment]
Not sure then.  I would need to see a full log from such a run, because this crash can only occur if there are no rogue spawners loaded.

**Comment by WenXin20** [comment]
if I have it happen again, I'll send the report here
