### ISSUE TITLE
What are the parameters called after the item name (e.g. "of Distant battles") and can I disable several of them?

### ISSUE THREAD

**Issue by Arsik654** [Shadows-of-Fire/Apotheosis#1011]

**Comment by Shadows-of-Fire** [comment]
These are suffixes, part of the name component of affixes.  An affix may provide either a prefix or a suffix, chosen at random when the item is created.  The only way to disable strictly suffixes would be to override all the translations for suffixes to `""` (empty string).  If you just wish to remove the name from a generated loot item, you can use a Vial of Unnaming.
