### ISSUE TITLE
feature request: expose Apotheosis boss spawn sounds in the Extreme Sound Muffler interface

### ISSUE THREAD

**Issue by adeilt** [Shadows-of-Fire/Apotheosis#1012]
Exposing the boss spawn sounds in the Extreme Sound Muffler interface would allow dynamic configuration of the sounds during gameplay rather than requiring editing of a config file.

**Comment by Shadows-of-Fire** [comment]
The boss spawn sound is not a special sound that can be exposed in such a manner, it is just the vanilla sound `block.end_portal.spawn`
