### ISSUE TITLE
[BUG] Reforging does not accept rarity settings

### ISSUE THREAD

**Issue by N-thing** [Shadows-of-Fire/Apotheosis#1013]
When changing rarity settings in a datapack, they are not applied during reforging. Specifically the durability setting. When they work on replaced affixes (from bosses or loot)

MC: 1.19.2
Forge: 43.2.21
Apot: 6.4.0

Example Uncommon:
 - config: 
![изображение](https://github.com/Shadows-of-Fire/Apotheosis/assets/44474704/4274a74e-888d-4b9c-8b3a-4d932fa95a3e)
 - from loot: 
![изображение](https://github.com/Shadows-of-Fire/Apotheosis/assets/44474704/1a8b48d1-592f-4d48-b373-98fa28399c66)
 - when reforging:
![изображение](https://github.com/Shadows-of-Fire/Apotheosis/assets/44474704/0c04db49-9475-45ba-baae-4cf68242c39a)

**Comment by N-thing** [comment]
Let me clarify that this is a visual bug. When directly reforging, durability is applied

**Comment by Shadows-of-Fire** [comment]
Guessing the client isn't receiving the changed loot rules.
