### ISSUE TITLE
[Feature Request] Add a tag to items with affixes on them

### ISSUE THREAD

**Issue by CanvasofSpores** [Shadows-of-Fire/Apotheosis#1014]
Pretty self-explanatory, it would be nice if affixed items had something like #forge:ores on items for easier pulling from storage systems for automation and all that. Obviously we'd want something like apotheosis:affixed as the tag or something similar, but it could be useful.

**Comment by Shadows-of-Fire** [comment]
Tags are not nbt-based, so this is impossible.
