### ISSUE TITLE
[1.20.1] Wither Skeleton boss json has incorrect AABB height

### ISSUE THREAD

**Issue by SkyzerFlyzer** [Shadows-of-Fire/Apotheosis#1015]
MC: 1.20.1
Apotheosis: 7.0.5
Forge: 47.1.3

Boss entities have been spawning inside of blocks making them suffocate constantly as shown in the image below.

<img width="1916" alt="image" src="https://github.com/Shadows-of-Fire/Apotheosis/assets/43912613/78b0fb67-fe48-44b6-b79b-ca13f2509612">

**Comment by Shadows-of-Fire** [comment]
This is actually just a bug in the boss json for the wither skeleton, it's declaring a height of 2 instead of 3, so it thinks it can fit there.  Not a general boss problem.
