### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by kurtramone** [Shadows-of-Fire/Apotheosis#1018]
Missing some attributes text, not sure if it's you guys or Ars:

MC 1.19.2 Eng
Apotheosis: 6.4.0
![Captura de tela 2023-09-12 220231](https://github.com/Shadows-of-Fire/Apotheosis/assets/55619656/1267cd1f-ab43-48bd-a1dd-3defba27876b)

**Comment by Shadows-of-Fire** [comment]
That would be on ars to provide.  I believe they have added it for 1.20, they may not update it for 1.19

**Comment by kurtramone** [comment]
Thanks, will let them now
