### ISSUE TITLE
[1.20.1] enchanting table GUI.

### ISSUE THREAD

**Issue by Bass2style** [Shadows-of-Fire/Apotheosis#1019]
Hello,

i have a little bug with my enchanting table, i can't open it when Apotheosis is installed. removing apotheosis bring back my interface.
i tryed with apotheosis alone (alongside few mods that should not interact like JEI, jmap etc), and it's working, so it's maybe a conflict with another mod, but i don't know wich one could be.
are there known conflicting mods ?

here is my modlist : https://gist.github.com/Bass2style/eb8c5ad64e920bf46239b26de3dfb8f1
idk what i can provide as revelant informations, more if i can provide more informations that can be useful, just ask. :D

Forge : 47.1.47
Apotheosis : 7.0.5
LIB : 1.1.4

have a nice day.

**Comment by RoyalReject** [comment]
Remove lapis reserve, apotheosis already does this anyway

**Comment by Bass2style** [comment]
damn, i forgot this one. i removed nearby all the "until apotheosis come out" mods, but i forgot this one. thanks. xD

it's fixed, thanks for that quickness, like always. <3
