### ISSUE TITLE
1 Hit kill/death

### ISSUE THREAD

**Issue by da-degenerate** [Shadows-of-Fire/Apotheosis#1020]
I'm having issues with killing and being killed with 1 hit regardless of armor/weapons/ETC. I noticed I have "green" attributes on my adventure tab (that was introduced by Apotheosis 6.3.0). I've diagnosed the issue, and the culprit seems to be a default setting of some sort. I've done multiple New Worlds, and config resets with no change. I have 100% Crit Chance, 100% Life Steal, and 100% Current HP Damage. (I'm assuming this effect applies to mobs too, as they kill me in 1 hit) I've attempted to remove and change the versions of my added mods, with no defining results. I'm planning on starting an LP soon, and I really want to show off the most recent update of this mod specifically. Thanks in advance!

**If you'd like a video of this issue, I can provide one on request.

Issue at hand:
![Screenshot 2023-09-14 010320](https://github.com/Shadows-of-Fire/Apotheosis/assets/144997018/8dada892-3239-4030-928d-f6cc613e1a6c)

Modlist:
![Screenshot 2023-09-14 010532](https://github.com/Shadows-of-Fire/Apotheosis/assets/144997018/762a243c-d514-4c42-92af-c6e2f3572dd5)

**Comment by Shadows-of-Fire** [comment]
Try resetting your config files to see if you have some erroneous entry that is changing the default value from 0% to 100%.
Specifically at least the Apotheosis configs and the `attributefix.json` file (which can mess with the attribute default values).

**Comment by da-degenerate** [comment]
Guess it was simply a random error from my configs. I scoured them too, I couldn't find anything that could pose an issue. Thanks for the quick reply, everything seems to be in order now.
