### ISSUE TITLE
[request] configurable spawn rate of towers & ability to disable them - 1.19.2

### ISSUE THREAD

**Issue by 3lkram** [Shadows-of-Fire/Apotheosis#1021]
the way that the Apotheosis towers spawn is far too frequent and sporadic. I love the rest of the mod but for my specific use-case, I need to be able to disable the towers entirely for how my modpack works. I've made a datapack that can reduce the spawn-rate of the towers, but they still spawn in inappropriate locations and I need to be able to disable them entirely.

![2023-09-15_10 41 41](https://github.com/Shadows-of-Fire/Apotheosis/assets/78918971/df71337c-6acc-4ce5-8aa1-fdcbd5fd1cee)
![Screenshot 2023-09-14 at 12 11 57](https://github.com/Shadows-of-Fire/Apotheosis/assets/78918971/c81f6aaa-b11f-4c2d-bc17-44bde5a33664)

**Comment by RoyalReject** [comment]
They can be disabled and configured with datapacks which you already have stated. Newer versions of minecraft worldgen can really only be modified with datapacks this is a change brought by mojang

**Comment by 3lkram** [comment]
I've tried disabling them using a datapack and it doesn't work

[apotheosis_remove_towers.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/12623154/apotheosis_remove_towers.zip)

**Comment by RoyalReject** [comment]
For one that is not how you disable features... I would recommend learning more about datapacks and structures https://misode.github.io/guides/adding-custom-structures/.

As you can see they have conditions so all you need to do is make the condition for them to generate to always be false. Forge provides a false condition for this.

[Apotheosis_Remove_Towers.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/12623338/Apotheosis_Remove_Towers.zip)

**Comment by 3lkram** [comment]
you are the poggiest internet person and I thank you with immense gratitude
