### ISSUE TITLE
[Feature Request] Allow Spawner Upgrades to be Configured for Min/Max

### ISSUE THREAD

**Issue by alfredggttv** [Shadows-of-Fire/Apotheosis#1023]
Currently, the biggest issue with spawners is how fast they can get on a server. This can cause a lot of lag, especially when players build a mob farm.

If we could adjust the values for the min/max of each modifier in the configs, that could allow servers and pack mackers to limit the speeds of these spawners. If we could also change what items are needed for each modifier, that would also add more control to create a better sense of balance.

Thanks for the awesome mod btw!

**Comment by Shadows-of-Fire** [comment]
This already exists, each stat change in a modifier recipe encodes the value it changes, as well as the min and max value that modifier recipe may apply to that stat: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/recipes/spawner/min_delay.json#L12-L14

You can have different recipes with different min/max values as well.
