### ISSUE TITLE
[1.19.2 and 1.20.1 Forge] Apotheosis causes Slow Falling application to launch player up

### ISSUE THREAD

**Issue by TelepathicGrunt** [Shadows-of-Fire/Apotheosis#1024]
On 1.19.2 and 1.20.1, any application of a strong leveled slow falling effect will launch player upward when Apotheosis is on. When disabled, the launching no longer happens. Here are videos demonstrating the issue. I am using latest versions of apoth and its deps as chosen by Curseforge launcher.

https://github.com/Shadows-of-Fire/Apotheosis/assets/40846040/18a9c17d-98a5-459b-adfb-5f7fc1795696

https://github.com/Shadows-of-Fire/Apotheosis/assets/40846040/f1a798be-8d14-49e9-95c5-cfcae590ef9f

1.20.1 versions I was using that reproduced the issue there too:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/40846040/7f5235e2-fe0a-4d32-b38c-5f960c1494f6)

Disabling Apotheosis's modules by config makes the launching bug stop happening. So the issue lies within Apotheosis's module code I guess

**Comment by Shadows-of-Fire** [comment]
Root cause is due to the gravity modifier on the slow fall effect combined with bumblezone applying a very high level of slow falling, which yields very high negative gravity.
