### ISSUE TITLE
[Support] How do I modify the enchantment configs?

### ISSUE THREAD

**Issue by TheoCGaming** [Shadows-of-Fire/Apotheosis#1027]
I'm looking to modify the enchantability, enchantment_module, and enchantments config files but I don't know how to add/remove specific things. Do you have any documentation?
(and mods should have good docs anyway :p)

**Comment by ZaneyHD** [comment]
I am also having this issue

**Comment by RoyalReject** [comment]
Enchantment config is located at config/apotheosis/enchantments.cfg

**Comment by ZaneyHD** [comment]
> Enchantment config is located at config/apotheosis/enchantments.cfg

Thank you so much! :)

**Comment by TheoCGaming** [comment]
Not where, but *how?* There aren't any specifics on how to add or remove specific items from the configs.

**Comment by Shadows-of-Fire** [comment]
What are you talking about?  You do not add entries to a config file, you modify the existing entries.  Entries are present for all registered enchantments.

**Comment by TheoCGaming** [comment]
From what I've seen, enchantability.cfg does *not* have every registered item. You can enchant books, I can change the enchantability of ***everything in the config to the maximum possible value***, but the enchantability of books will ***never change.***

**Comment by Shadows-of-Fire** [comment]
The only config file for the enchantment module is `enchantments.cfg`, `enchantability.cfg` is a long dead relic of the past.

**Comment by TheoCGaming** [comment]
then how do I change the enchantability of books? is it hard coded?
