### ISSUE TITLE
Conflict with Allurement

### ISSUE THREAD

**Issue by CupOJo1** [Shadows-of-Fire/Apotheosis#1030]
It seems like apotheosis and allurement are conflicting with each other involving a change to anvils with allurement. 

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/12777790/latest.log)

**Comment by Shadows-of-Fire** [comment]
You can ask Allurement to mark their mixin as optional.  I will not make any changes for compatibility with ARR mods.

**Comment by SiverDX** [comment]
they actually already did
