### ISSUE TITLE
[1.19.2] Legacy Reforging config entries are still generated

### ISSUE THREAD

**Issue by Cerbion** [Shadows-of-Fire/Apotheosis#1031]
Minecraft: 1.19.2
Server: Forge 43.3.0
Apotheosis: 6.4.0

I tried changing the adventure.cfg contents, specifically the XP amount it takes to reforge, but it has no effect. I am able to change the Gem Dust amount though, just not the XP level base, I even let Apotheosis regenerate the .cfg file and tried changing just that, but to no avail.
Is there a fix/workaround for this, or am I stuck with these settings until it's fixed (if ever?) - The patchnotes for 7.0+ suggest, that the files are obsolete in newer versions, has some of these changes accidentally made it into 1.19.2/Apo 6.x?

**Comment by xIcePower** [comment]
Same problem here

**Comment by Shadows-of-Fire** [comment]
The reforging controls are now json recipes, the defaults are here, and they must be modified via datapack: <https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/recipes/reforging>
It seems like the config line didn't get removed for 1.19.  I might remove it at some point, but that's unlikely at this point
