### ISSUE TITLE
Wandering Trader ignores Enchantment restrictions

### ISSUE THREAD

**Issue by twothe** [Shadows-of-Fire/Apotheosis#1033]
When enabling the village module the wandering trader ignores most enchantment limitations set in the Enchanting module. I.E. I have set all enchantment limits to vanilla standards, yet the trader offers items with Fortune 7, or Boon of the Earth 4.

**Comment by Shadows-of-Fire** [comment]
This is not a bug. The items sold by the trader have statically-encoded levels (ex: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/wanderer_trades/arachnids_fear.json#L22).  They can be changed with a datapack, but otherwise adhere to no limits.
