### ISSUE TITLE
1.19.2 Apotheosis Incompatible with DMC loot

### ISSUE THREAD

**Issue by cranberriez** [Shadows-of-Fire/Apotheosis#1034]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/24465331/307fa33a-364d-4cb4-96d7-1f2c13895b7b)

Combining Apotheosis with DMC loot on 1.19.2 causes double prefixes and suffixes.

I most likely will be removing DMC loot to solve this issue. However I wanted to bring it up as I couldn't find a proper issue about it.

**Comment by Shadows-of-Fire** [comment]
Don't think I can do anything about this. DMC is pulling the full item name into their prefixed name, and then the affix name is added back onto the items name since it is still in NBT.
