### ISSUE TITLE
1.20.1: Rendering screen crash

### ISSUE THREAD

**Issue by Daltaxy** [Shadows-of-Fire/Apotheosis#1035]
hey,
My friend and I play using Essential, and every time he opens his inventory he crashes.
120.1, latest forge version 47.2.1, Apotheosis-1.20.1-7.0.5.jar
https://mclo.gs/6W5oEw0
something about a prismatic web not existing?
edit: replaced crash report file to mclo website uploaded crash report

**Comment by Daltaxy** [comment]
also please check this as a mod owner also reports a bug that could be linked to this
https://github.com/Stardust-Labs-MC/Terralith/issues/49

**Comment by RoyalReject** [comment]
Does the same issue occur when using forge 47.1.3? With the forge/neoforge split Apotheosis is going with neoforge. For 1.20.1 I believe that Apotheosis will only support up to 47.1.3 on forge and should work on any version of neoforge.

**Comment by Shadows-of-Fire** [comment]
I think this is a case of the enchanting module being disabled on the server but enabled on the client

**Comment by Shadows-of-Fire** [comment]
Please ensure the configs are matched on both the client and the server and try to reproduce. This seems like it is a config mismatch issue.

**Comment by AzureShark** [comment]
Can confirm, this is a config mismatch issue. I was experiencing the same issue, making sure both the configs were the same fixed this immediately.

**Comment by Daltaxy** [comment]
indeed, fixed by sending him my config. sorry for the delay.
