### ISSUE TITLE
Server crashing in a specific and strange way 

### ISSUE THREAD

**Issue by TioNickZeus** [Shadows-of-Fire/Apotheosis#1036]
Basically, when an ejector shoots an arrow and a player is using equipment that, for example, gives an effect to the attacker. 
EX: The player is wearing a helmet that causes blindness to whoever attacks him, but he was attacked by a piston, so the server simply crashes.

**Comment by Shadows-of-Fire** [comment]
Crash issues must provide a crash report

**Comment by TioNickZeus** [comment]
[crash-2023-10-07_00.34.49-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12836706/crash-2023-10-07_00.34.49-server.txt)

**Comment by TioNickZeus** [comment]
i think this one might be better 
[crash-2023-10-07_00.33.48-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12836710/crash-2023-10-07_00.33.48-server.txt)

**Comment by Shadows-of-Fire** [comment]
This crash is coming out of a mixin: `at net.minecraft.world.entity.LivingEntity.handler$cpe000$d(LivingEntity.java:23550)` I do not know what mod the mixin is from, so you'll have to root-cause it on your own.
