### ISSUE TITLE
Crashing when disabling the adventure module

### ISSUE THREAD

**Issue by NottDAG-Gsimus** [Shadows-of-Fire/Apotheosis#1038]
---------------------------------------------------------------------------------------------------------------------------------------------------
**Description:**
When you disable the adventure module in the config, the game crashes when you create a new world
---------------------------------------------------------------------------------------------------------------------------------------------------
**Forge Version:**
1.20.1, Forge 47.2.1
---------------------------------------------------------------------------------------------------------------------------------------------------
**Mods:**
_Apotheosis_
Apotheosis-1.20.1-7.0.5.jar

_Apothic Attributes (AttributesLib)_
ApothicAttributes-1.20.1-1.1.4.jar

_Patchouli_
Patchouli-1.20.1-81-FORGE.jar

_Placebo_
Placebo-1.20.1-8.3.7.jar
---------------------------------------------------------------------------------------------------------------------------------------------------
**Crash report:**
[crash-2023-10-13_19.33.51-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12897574/crash-2023-10-13_19.33.51-client.txt)

**Comment by Shadows-of-Fire** [comment]
The adventure module can only be disabled when using NeoForge, as the issue was a Forge bug that has only been fixed in neo.

See https://github.com/Shadows-of-Fire/Apotheosis/issues/989

**Comment by NottDAG-Gsimus** [comment]
So, is there any way to fix it on normal forge?

**Comment by SiverDX** [comment]
why, yes
you just have to

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/ee715a9c-cc86-4b71-a195-9889ec11825a)

**Comment by NottDAG-Gsimus** [comment]
What do you mean by that?

**Comment by NottDAG-Gsimus** [comment]
Good news! I found a solution to this problem! When you disable the adventure module in the configure file, put the default setting as false as well, that then fixes the issue and the adventure module is disabled without any problems
