### ISSUE TITLE
Advancements relating to disabled modules

### ISSUE THREAD

**Issue by Partonetrain** [Shadows-of-Fire/Apotheosis#104]
Advancements aren't dynamically disabled based on what modules are loaded. Is that even possible, given how advancements work (entirely data-driven)? End users can always overwrite advancements with datapacks, so maybe a wontfix

**Comment by Shadows-of-Fire** [comment]
As far as I'm aware it's not possible to disable them like that.  That said, I think I recall seeing a forge PR for advancement conditions, not sure if that went anywhere

**Comment by Shadows-of-Fire** [comment]
Added conditions to all json objects that can use them https://github.com/Shadows-of-Fire/Apotheosis/commit/e5cdf3f89d37f272b0d4a3adaa2c389941458ff7
