### ISSUE TITLE
[bug] When installed together with easy magic, the enchantment table will become a static block! 

### ISSUE THREAD

**Issue by Qee1y** [Shadows-of-Fire/Apotheosis#1041]
mc 1.19.2
forge 43.3.2
mod 6.4.0

**Comment by RoyalReject** [comment]
Easy Magic modifies the enchanting table making it incompatible with apotheosis, this is the case with most mods that modify the enchanting table

**Comment by Qee1y** [comment]
Can they be compatible? Just make easy maigc mod rendering animations and items stay。

**Comment by Shadows-of-Fire** [comment]
Ah yes, "just make it compatible 4head"

No, Apoth and Easy Magic make fundamentally incompatible overrides of the enchanting menu, and cannot be made compatible without writing a third layer that incorporates both features.
