### ISSUE TITLE
Percentage Attribute increase helmet gem multiplies attack damage by 20

### ISSUE THREAD

**Issue by ArmouredDrood** [Shadows-of-Fire/Apotheosis#1045]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/18104964/c6d2767d-40f5-4ea4-b771-c37186782439)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/18104964/8454350b-9e09-44b7-b465-7b6fa6f4a434)
without gem of %attribute increase:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/18104964/7e948f6f-53e5-4a73-be5b-01479debc220)
with
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/18104964/01336fab-030f-4bd2-8c37-66039e84557e)

**Comment by ArmouredDrood** [comment]
mobs that spawn with affix helmets with this gem do this as well

**Comment by Shadows-of-Fire** [comment]
This is caused by a cross-mod interaction with (I think) passive skill tree. The gem increases all stats, and they have a fuckton of stats (and they are not zero-indexed), so the gem increases all of them, leading to this.

**Comment by ArmouredDrood** [comment]
I will report it to them. Thanks.
Apologies for bugging you with it.
And yes, I have passive skill tree.

**Comment by muon-rw** [comment]
Maybe a config whitelist or blacklist for whether or not an attribute should be affected by all attribute increases would be good catch-all solution?

**Comment by Shadows-of-Fire** [comment]
If desired one can datapack the gem to use a very long `multi_attribute` bonus, but I don't plan on changing the default implementation.

Passive skill tree should ideally be using zero-indexed attributes.

**Comment by muon-rw** [comment]
I did already implement the same workaround, minus the large tooltip it works pretty well. Thanks for the tip.

In that case hopefully the skill tree report goes somewhere.

**Comment by ArmouredDrood** [comment]
@muon-rw Would you kindly be willing to share your datapack workaround with me?
I am not as familiar with custom datapacks as i should be :/
