### ISSUE TITLE
Сompatible TreeChop

### ISSUE THREAD

**Issue by Willem07** [Shadows-of-Fire/Apotheosis#1046]
Is it possible that Chainsaw enchantment is compatible with the TreeChop mod?

[Apotheosis-1.20.1-7.0.5](https://legacy.curseforge.com/minecraft/mc-mods/apotheosis/files/4724390)
[TreeChop-1.20.1-forge-0.18.3](https://legacy.curseforge.com/minecraft/mc-mods/treechop/files/4685647)

_or is the compatibility problem on the side of the developers of the TreeChop mod?_

**Comment by Shadows-of-Fire** [comment]
The chainsaw enchantment is fundamentally incompatible with how that mod works. Chainsaw attempts to walk the tree and break the entire log structure on block break, but that mod prevents the block from actually being broken.
If TreeChop wanted to add compat they could potentially make it so having a chainsaw-enchanted axe would immediately break the tree, but this is not functionality I can add.
