### ISSUE TITLE
Mage Slayer gem bonus's math is off

### ISSUE THREAD

**Issue by TheWinABagel** [Shadows-of-Fire/Apotheosis#1047]
https://github.com/Shadows-of-Fire/Apotheosis/blob/1176c37bc8cb98f395788a097427ba9164c31e85/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/bonus/special/MageSlayerBonus.java#L42-L43

Should just return `amount` as the player is currently getting healed for the same amount as they take damage

**Comment by Shadows-of-Fire** [comment]
Correct that the math was off, but not the correct fix - the return value is correct, but the heal amount should be `amount * value`.
