### ISSUE TITLE
[BUG] Crash on Startup (Possible Conflict with immediatelyFast)

### ISSUE THREAD

**Issue by Camawama** [Shadows-of-Fire/Apotheosis#1048]
FORGE: 1.20.1-47.2.1

Attempting to add Apotheosis to my modpack (in development) causes a crash on startup. No crash report.

Logs: 
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13049703/latest.log)

Debug Logs:
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13049704/debug.log)

**Comment by Shadows-of-Fire** [comment]
```
[19Oct2023 22:38:22.206] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'attributeslib', Requested by: 'apotheosis', Expected range: '[1.1.3,)', Actual version: '[MISSING]'
```

**Comment by Camawama** [comment]
Well this is embarrassing. 

I always catch those dependencies, guess this was the first time I was defeated.
