### ISSUE TITLE
Enchanted Anvils drops improperly

### ISSUE THREAD

**Issue by LordXerus** [Shadows-of-Fire/Apotheosis#105]
Overview
---
When an anvil(that is overwritten by Apotheosis, regardless of enchantments) is broken by a Integrated Dynamics/Tunnels World Block Importer, the anvil doesn't drop itself(it doesn't go into the Integrated* network). An existing workaround is to break it with an Integrated * User Simulator set to break blocks instead, then pick it up with a World Item Importer.

This might be caused by non-standard drop handling.

Another issue is when the anvil lands on an incomplete block(Project Red framed wires, Integrated* logic pipes), it drops without the enchantments.

I suspect the issue is here, so I haven't submitted an issue on the Integrated* side yet.
Game Version: 1.12.2

Test
---
ID network used:
(Chest)(f)---(i)(A)

(Chest) Acts as the inventory of the network.
(f) Item Interface that connects the chest to the network
\- A Logic Pipe from Integrated Dynamics
(i) World Block Importer
(A) Apotheosis Enchanted Anvil

Mods
---
_**Relevant Mods:**_
- Apotheosis-1.12.2-1.10.5
- IntegratedTunnels-1.12.2-1.6.10
- IntegratedDynamics-1.12.2-1.1.0
- CommonCapabilities-1.12.2-2.4.4

_**Relevant Mod Dependencies:**_
- CyclopsCore-1.12.2-1.5.1
- Placebo-1.12.2-1.6.0

_**All Other Installed Mods:**_
- jei_1.12.2-4.15.0.291
- Hwyla-1.8.26-B41_1.12.2
- _Other Integrated* mods_
    - IntegratedCrafting-1.12.2-1.0.8
    - IntegratedTerminals-1.12.2-1.0.12
    - refinedstorage-1.6.15
- _Majority of the Thermal Series by CoFH_
    - CoFHCore-1.12.2-4.6.3.27-universal
    - CoFHWorld-1.12.2-1.3.1.7-universal
    - RedstoneFlux-1.12-2.1.0.6-universal
    - ThermalCultivation-1.12.2-0.3.3.12-universal
    - ThermalExpansion-1.12.2-5.5.4.43-universal
    - ThermalFoundation-1.12.2-2.6.3.27-universal
    - ThermalInnovation-1.12.2-0.3.3.12-universal
    - CodeChickenLib-1.12.2-3.2.2.353-universal
- TConstruct-1.12.2-2.12.0.157
- Mantle-1.12-1.3.3.55
- AppleSkin-mc1.12-1.0.9

[Mods.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/3775127/Mods.zip)

**Comment by Shadows-of-Fire** [comment]
This is likely caused by the non-standard drop handling, but it is necessary as the drop is dependent on the tile entity.  The breaker would probably experience the same issue with shulker boxes (The same issue the AA breaker (currently) and the Mek digital miner (previously) had).

Not really anything that can be done about it from my end tho.
