### ISSUE TITLE
Mythic loot affixes not generating, console log errors

### ISSUE THREAD

**Issue by DarkSolus** [Shadows-of-Fire/Apotheosis#1051]
Issue #682 popped up again in my server, reopening for solutions

Apotheosis version 7.0.5, MC 1.20.1

`[23Oct2023 18:52:09.315] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:52:54.188] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:53:44.054] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:54:08.901] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:55:35.036] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:golden_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:55:55.001] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:iron_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:02.458] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:05.156] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:leather_helmet/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:13.191] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:diamond_boots/apotheosis:mythic/ABILITY/0.3!`
`[23Oct2023 18:56:30.903] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:chainmail_boots/apotheosis:mythic/ABILITY/0.3!`

This happened in the End, all loot as a result rolled without any affixes, just vanilla enchants.

During server startup these messages also show up, but I haven't been able to figure out how to fix them.

`[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2`
`[23Oct2023 14:02:06.681] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2`
`[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.685] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.686] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.687] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4`
`[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2`
`[23Oct2023 14:02:06.688] [main/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2`

_Originally posted by @DarkSolus in https://github.com/Shadows-of-Fire/Apotheosis/issues/682#issuecomment-1775771697_

P.S. Rare, Uncommon and Common affixes generate as normal, only Mythic affixes are affected.

**Comment by Shadows-of-Fire** [comment]
Have you modified anything via datapack or is this a stock installation?

**Comment by DarkSolus** [comment]
> Have you modified anything via datapack or is this a stock installation?

No datapacks modifying Apotheosis, no. I also reset the adventure.cfg config file just in case, however, that did not resolve the loot errors.

Update:
I have tested purely Apotheosis (w/Placebo and Apothic Attributes, as they are dependencies) in a singleplayer world. All other mods were disabled, Forge shows only these mods as loaded. No datapacks loaded, fresh singleplayer world.
Configs were reset to default.
Console output as follows:

`[11:48:18] [Render thread/INFO] [placebo/]: Registered 31 additional loot tables.`
`[11:48:18] [Render thread/INFO] [minecraft/RecipeManager]: Loaded 12 recipes`
`[11:48:18] [Render thread/INFO] [minecraft/AdvancementList]: Loaded 1324 advancements`
`[11:48:18] [Render thread/INFO] [placebo/]: Registered 27 additional recipes.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Enchantment/]: Registered 29 enchanting_stats.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 6 rarities.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 82 affixes.`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2`
`[11:48:18] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 19 gems.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 16 gear_sets.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 75 affix_loot_entries.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 17 bosses.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 8 rogue_spawners.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 5 minibosses.`
`[11:48:18] [Render thread/INFO] [Apotheosis : Village/]: Registered 28 wanderer_trades.`

Strangely enough, I do not get the "Failed to execute LootRule" errors.
Will test mods further, see if some of them prevent mythic items from spawning.

UPD2: On clean Apotheosis install w/o other mods, errors "Failed to execute LootRule" still appear, but much more rarely. With only Apotheosis, I get these errors maybe once every 10 mins, and there is no visible indicator of any failure. Mythic bosses still drop Mythic loot, however, they never drop helmets or boots. When trying to enchant helmets or boots, the "Failed to execute LootRule" pops up, the item gets enchanted with Mythic affixes as normal. Further testing reveals that trying to add affixes to any helmet or boots immediately triggers the error, despite the successful affixing.

**Comment by Shadows-of-Fire** [comment]
I think a few more affixes need to be added to certain pools, but this isn't a fatal error.

**Comment by Louie365** [comment]
This issue seems to be causing people to crash in my server. We get logged out when getting close to a spell scroll from Iron's spellbooks.
This appears shortly after in the server console:

[INFO] .... [minecraft/MinecraftServer]: Louie365 left the game

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[INFO] .... [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@2c03d69c[id=<null>,name=Louie365,properties={},legacy=false] (/94.155.24.41:58890) lost connection: Disconnected

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:uncommon/STAT/0.45!

[INFO] .... [minecraft/ServerLoginPacketListenerImpl]: UUID of player Machi1503 is 50e21463-60d9-4c51-a0be-b6fc6c5aacc2

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/STAT/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/1.0!

[ERROR] .... [Apotheosis : Adventure/]: Failed to execute LootRule irons_spellbooks:blaze_spell_book/apotheosis:rare/ABILITY/0.33!

**Comment by Krimatoria** [comment]
I have such a mistake. The server crashes often, I don't know if it's related to this or not.
I have attached a file there are a lot of these errors. Here is an example. There are about 234 errors in the logs with this problem. 
[Insufficient number of affixes to satisfy the loot rules (ignoring backup rules)]
[Log 6.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14319206/Log.6.txt)

**Comment by SiverDX** [comment]
> I have such a mistake. The server crashes often, I don't know if it's related to this or not. I have attached a file there are a lot of these errors. Here is an example. There are about 234 errors in the logs with this problem. [Insufficient number of affixes to satisfy the loot rules (ignoring backup rules)] [Log 6.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14319206/Log.6.txt)

Your server crashing is likely due to https://www.curseforge.com/minecraft/mc-mods/apothic-curios
(This might have been resolved in the latest release a couple days ago)

If you want this message to go away, add more affixes to the entries logged

**Comment by Krimatoria** [comment]
> > У меня такая ошибка. Сервер часто вылетает, не знаю связано это с этим или нет. Прикрепил файл, там много таких ошибок. Вот пример. В логах с этой проблемой около 234 ошибок. [Недостаточное количество аффиксов для удовлетворения правил добычи (игнорирование правил резервного копирования)] [Журнал 6.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14319206/Log.6.txt)
> 
> Сбой вашего сервера, вероятно, вызван https://www.curseforge.com/minecraft/mc-mods/apothic-curios (возможно, это было решено в последней версии пару дней назад)
> 
> Если вы хотите, чтобы это сообщение исчезло, добавьте дополнительные аффиксы к зарегистрированным записям.

Yes, it was I who contacted the developer at Discord. Yes, there was some kind of problem with the air tags. He released an updated version. But it's flying out now anyway. Of course I'll send it to him, maybe it's interconnected again.

Should I add? Ahahaha. I'm not a developer, just a player.. I don't understand anything about it)

**Comment by Krimatoria** [comment]
1.19.2 Forge 
Apotheosis-1.19.2-6.4.1.jar

This leads to a crash from the server every time. It seems like when a mob with certain affixes is generated, then you are thrown out of the world.

[17Feb2024 16:27:21.981] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
[17Feb2024 16:27:21.981] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2

**Comment by Krimatoria** [comment]
1.20.1

> [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:ringRequired: 4; Provided: 3
> --
> 5519 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:an_focusRequired: 4; Provided: 3
> 5520 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:necklaceRequired: 4; Provided: 3
> 5521 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:charmRequired: 4; Provided: 3
> 5522 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:beltRequired: 4; Provided: 3
> 5523 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:spellstoneRequired: 4; Provided: 3
> 5524 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:scrollRequired: 4; Provided: 3
> 5525 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:braceletRequired: 4; Provided: 3
> 5526 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:talismanRequired: 4; Provided: 3
> 5527 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:ringRequired: 4; Provided: 3
> 5528 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:an_focusRequired: 4; Provided: 3
> 5529 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:necklaceRequired: 4; Provided: 3
> 5530 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:charmRequired: 4; Provided: 3
> 5531 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:beltRequired: 4; Provided: 3
> 5532 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:spellstoneRequired: 4; Provided: 3
> 5533 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:scrollRequired: 4; Provided: 3
> 5534 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:braceletRequired: 4; Provided: 3
> 5535 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:talismanRequired: 4; Provided: 3
> 5536 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category helmetRequired: 5; Provided: 4
> 5537 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category chestplateRequired: 5; Provided: 4
> 5538 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category leggingsRequired: 5; Provided: 4
> 5539 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category bootsRequired: 5; Provided: 4
> 5540 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category shieldRequired: 5; Provided: 4
> 5541 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:ringRequired: 5; Provided: 3
> 5542 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:an_focusRequired: 5; Provided: 3
> 5543 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:necklaceRequired: 5; Provided: 3
> 5544 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:charmRequired: 5; Provided: 3
> 5545 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:beltRequired: 5; Provided: 3
> 5546 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:spellstoneRequired: 5; Provided: 3
> 5547 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:scrollRequired: 5; Provided: 3
> 5548 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:braceletRequired: 5; Provided: 3
> 5549 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category curios:talismanRequired: 5; Provided: 3
> 5550 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category pickaxeRequired: 5; Provided: 4
> 5551 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:esoteric for category shovelRequired: 5; Provided: 4
> 5552 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shieldRequired: 5; Provided: 4
> 5553 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:ringRequired: 5; Provided: 3
> 5554 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:an_focusRequired: 5; Provided: 3
> 5555 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:necklaceRequired: 5; Provided: 3
> 5556 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:charmRequired: 5; Provided: 3
> 5557 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:beltRequired: 5; Provided: 3
> 5558 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:spellstoneRequired: 5; Provided: 3
> 5559 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:scrollRequired: 5; Provided: 3
> 5560 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:braceletRequired: 5; Provided: 3
> 5561 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:talismanRequired: 5; Provided: 3
> 5562 | [00:21:42] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 3

**Comment by meeprdib** [comment]
Looks like you need to provide more affixes for curios to get it to stop posting that in the log, base apotheosis doesn't do that.
Also, please don't just post server logs without actually defining an issue or providing any other information, there's not much to go off of from there.

**Comment by Krimatoria** [comment]
> Похоже, вам нужно предоставить больше аффиксов для curios, чтобы он перестал публиковать это в журнале, base apotheosis этого не делает. Также, пожалуйста, не публикуйте просто логи сервера без фактического определения проблемы или предоставления какой-либо другой информации, из этого не так много информации.

ok

**Comment by Krimatoria** [comment]
> Похоже, вам нужно предоставить больше аффиксов для curios, чтобы он перестал публиковать это в журнале, base apotheosis этого не делает. Также, пожалуйста, не публикуйте просто логи сервера без фактического определения проблемы или предоставления какой-либо другой информации, из этого не так много информации.

You probably think I know how to do this in terms of adding to curious. But I don't understand anything about it, I'm just a player)))))
