### ISSUE TITLE
[Bug] [1.19.2 Forge] Glitched gem causing game to crash

### ISSUE THREAD

**Issue by TobbyPopz** [Shadows-of-Fire/Apotheosis#1052]
I got a glitched gem that has no bonuses or anything so I was going to turn it into Gem dust, but when I dropped it on the ground the game crashed and I can't get back into my world because it keeps on crashing 

[crash-2023-10-24_21.34.45-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13113688/crash-2023-10-24_21.34.45-client.txt)

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/neruina to get back into the world
(Not entirely sure if this works on render ticks, might not)

The crash itself is caused by https://www.curseforge.com/minecraft/mc-mods/loot-beams

**Comment by TobbyPopz** [comment]
Neruina didn't work but removing loot beams did, Thanks!
