### ISSUE TITLE
Incompatible with vanillaicecreamfix

### ISSUE THREAD

**Issue by CatAndPaste** [Shadows-of-Fire/Apotheosis#1053]
Might be incompatibility with some other mod. 1.20.1 (NeoForge 47.1.79), apoth 7.0.5.

Crash log: https://pastebin.com/wLfDxBg2

EDIT: replaced with pastebin link.

**Comment by CatAndPaste** [comment]
Removing vanillafix-1.0.0-forge-beta.jar fixed the problem. Seems like Apotheosis is not compatible with https://www.curseforge.com/minecraft/mc-mods/vanillaicecreamfix by @repletsin5 
(https://github.com/repletsin5/VanillaIcecreamFix).

**Comment by Shadows-of-Fire** [comment]
Yeah they're shipping a cursed `@Overwrite` of the entire anvil update method.
https://github.com/repletsin5/VanillaIcecreamFix/blob/forge/forge/src/main/java/me/replet/client/other/AnvilScreenHandlerMixin.java#L42

Closing as mod conflict.
