### ISSUE TITLE
(1.16.5) Crash upon being hit by entity spawned through spawner + affix boss

### ISSUE THREAD

**Issue by ReeCodes** [Shadows-of-Fire/Apotheosis#1054]
This resulted in the server crashing, kicking me in the process.
First entity encounter crash:
[crash-2023-10-25_21.24.42-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13170020/crash-2023-10-25_21.24.42-server.txt)
2nd entity encounter crash:
[crash-2023-10-25_21.40.50-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13170024/crash-2023-10-25_21.40.50-server.txt)

**Comment by Shadows-of-Fire** [comment]
1.16.5 is not supported
