### ISSUE TITLE
[Suggestion] Ability to reroll single effect or attribute of an item

### ISSUE THREAD

**Issue by s185948** [Shadows-of-Fire/Apotheosis#1057]
Since reforging an item rerolls all the effect and attribute of an item, it is difficult to get the best stats out of an item. I suggest that there should be a way to reroll one single effect or attribute of an item. This can be:
- A gem/rarity material that allows selective rerolling of one effect or attribute.
- A gem/rarity material that prevents rerolling of desireable effects or attributes (more gems requried overall).

I hope this gets added into the mod! Thanks.

**Comment by Shadows-of-Fire** [comment]
This has been on the todo list for a while, just need to spin up a new table type for it...

**Comment by s185948** [comment]
Thanks for following up on this, look forward to see this feature in game.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/commit/7588c8868ad30f770225a04a1def87005b9ab0e3
