### ISSUE TITLE
Crash viewing Wave 3 of Gateway to Eternity

### ISSUE THREAD

**Issue by Hanoverfist** [Shadows-of-Fire/Apotheosis#1058]
Pack: Enigmatica 9: Expert (MC 1.20.1)
Version: Apotheosis-1.19.2-6.4.0

Looking up the Gateway to Eternity in EMI and scrolling to Wave 3 causes a client crash.

Explaination
- Crash to desktop on EMI lookup.
- Lookup @Gateway to search the mod Gateways to Eternity.
- Hover over "Small Apothic Boss Gate Pearl"
- Hold shift and use the mouse wheel to attempt to look at 'Wave 3' information.

Crash Report: https://pastebin.com/RfNizLqR

**Comment by Shadows-of-Fire** [comment]
The boss gateway depends on the presence of the `apotheosis:the_end/enderman` boss, if it isn't registered the gateway is invalid and may crash in this manner.  If the boss was removed by the modpack the gateway should be removed as well.

**Comment by Fnige** [comment]
This happens for us too in a custom modpack with basically no config changes too. But only on a server, not in a singleplayer world

Crash log: https://gist.github.com/Fnige/8b83ae3ec5d5cb3b4358681a985bd4b0

**Comment by Fnige** [comment]
Aha, EMI crashes with the tooltip error but JEI gives
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/35159947/f017a762-b37f-4219-8adc-88f13b87efb6)

**Comment by Shadows-of-Fire** [comment]
Gateways support is being redone for Gateways 4.2.0 - this will vanish with that.
