### ISSUE TITLE
[1.14.4] [2.4.2]Language file name listed in Enchantment books description

### ISSUE THREAD

**Issue by raziel23x** [Shadows-of-Fire/Apotheosis#106]
![image](https://user-images.githubusercontent.com/441966/67826886-753ca500-faa4-11e9-86c8-da6e35f1cfe5.png)

**Comment by Shadows-of-Fire** [comment]
That's rather peculiar.  Another mod might be causing that, but it's rather interesting as the language files are not even called en_US.lang anymore, as of 1.14 all language files are xx_xx.json (so en_us.json)

**Comment by Shadows-of-Fire** [comment]
![image](https://user-images.githubusercontent.com/3682588/67830341-a58a4080-fab0-11e9-8b6d-31d81e7813b7.png)
Cannot reproduce, must be another mod in your instance.
