### ISSUE TITLE
[1.20.1] Glitched spawned entities

### ISSUE THREAD

**Issue by moonarts** [Shadows-of-Fire/Apotheosis#1060]
- Some baby mobs spawned from Apotheosis spawners are stuck in the air, without gravity, without AI, you can hit and kill them, but they stay as corpse in the air and still count in the mob cap, which turn off the spawner over time.

- I have this issue on the Direwolf20 1.20 modpack (version 1.3.1).

- Other people reported the exact same issue on the Discord server.

![1](https://github.com/Shadows-of-Fire/Apotheosis/assets/65072318/27e4a582-f144-40df-97a6-e2820d72c140)
![2](https://github.com/Shadows-of-Fire/Apotheosis/assets/65072318/af58e1e1-a7e5-4443-b107-6fd7d1e85da9)
![3](https://github.com/Shadows-of-Fire/Apotheosis/assets/65072318/6bd71fd6-1864-462a-bf6f-d42246cabd5f)

**Comment by DarkDanny** [comment]
EDIT: I THINK I located the source of the problem. I had Redstone Control, Ignore Lighting, & Silent on the spawner. I removed both Ignore Lighting & Silent & it seems to have fixed the ghost entities issue. I'll test in both single player & multiplayer when I get the chance to see if I can replicate the problem & figure out which one specifically is causing the problem if it's not the combination of the two.


I'm also having this problem, but its happening with baby Zombie Piglins.

Direwolf20 (modpack version 1.4.1) (Apotheosis version 7.0.5)

Playing on Multiplayer.

![84EGjKC](https://github.com/Shadows-of-Fire/Apotheosis/assets/28662899/8d588da6-ef74-4f51-b743-a90233838da6)

Apotheosis modifiers
![hHck2O3](https://github.com/Shadows-of-Fire/Apotheosis/assets/28662899/1684c583-4b10-42f1-b293-59dd99aed98e)


Restarting the server removes the floating dead mob entities, but restarting the server when others are playing isn't optimal.

**Comment by moonarts** [comment]
Edit : Yes, server restarts remove the floating dead mob entities. Also, my spawner only has Redstone Control.

**Comment by Shadows-of-Fire** [comment]
@DarkDanny any progress on an isolated reproduction? This usually only happens if entities are being added on the client side, but the entire spawner code is serverside only, so that can't be happening here.

**Comment by Shadows-of-Fire** [comment]
I can't get this to reproduce with or without specific modifiers.  Usually when you see a stuck entity like that it's one that is added only on the clientside, but none of the spawner code even runs on the clientside, so I'm skeptical that the spawner is truly the root cause of the issue here.

**Comment by moonarts** [comment]
I tried to replicate it in singleplayer for hours and it didn't work. If the glitched entities were clientside only, it wouldn't stop the spawner after too much glitched entities had spawn. The glitched baby entities exist on the server because other players can see them and they count in the mob cap (F3 debug menu). I'll try to record a video about the bug, you usually see the spawner spawns few mobs and one of the mob is a baby variant being stuck in the air with no AI.

**Comment by DarkDanny** [comment]
> I tried to replicate it in singleplayer for hours and it didn't work. If the glitched entities were clientside only, it wouldn't stop the spawner after too much glitched entities had spawn. The glitched baby entities exist on the server because other players can see them and they count in the mob cap (F3 debug menu). I'll try to record a video about the bug, you usually see the spawner spawns few mobs and one of the mob is a baby variant being stuck in the air with no AI.

Firstly, let me say the workaround solution is to use Inverted Stirrups from Cyclic on the floating AI mobs & then put them back down once you've picked them up, & they'll spring back to life & can be killed as normal, but the stirrups only work on them if they have HP & are considered alive.

I just tested on single player & was able to replicate it in singleplayer. The problem comes from adding a soul lantern to the spawner which is the Ignores Light modifier.

**Comment by moonarts** [comment]
I tried adding the "Ignores Light" modifier, you're right, it's the one breaking everything.
![1](https://github.com/Shadows-of-Fire/Apotheosis/assets/65072318/da61b45c-3f4a-4616-8078-c38fbb7727e5)
![2](https://github.com/Shadows-of-Fire/Apotheosis/assets/65072318/d73192ee-fda5-48a5-b16a-5b8d803dbb17)
