### ISSUE TITLE
MC 1.18.2 - Modpack Dev - Crash at Init

### ISSUE THREAD

**Issue by Pel00** [Shadows-of-Fire/Apotheosis#1061]
So many times when I wnated to add Forbidden and Arcanus to modpack - alwas crash. I have a crash log and can show list of the mods. Is there some mods which they have always conflict with F&A ? Or there is something else?

Crash log in txt (my website): 
[https://pel00.net/assets/text/minecraft/1.18.2/crashes/crash-2023-11-02_16.32.56-client.txt](https://pel00.net/assets/text/minecraft/1.18.2/crashes/crash-2023-11-02_16.32.56-client.txt)

List of the mods:
[https://pel00.net/assets/text/minecraft/1.18.2/crashes/modlist.txt](https://pel00.net/assets/text/minecraft/1.18.2/crashes/modlist.txt)

**Comment by RoyalReject** [comment]
This is not an apotheosis issue. Looking at your crash you are missing the mod valhelsia core

**Comment by Pel00** [comment]
Yeah you are right, I didn't looked at that. Thanks a lot.
