### ISSUE TITLE
[Java - 1.20.1] Underlying exceptions / Insufficient number of affixes

### ISSUE THREAD

**Issue by RRiiverr** [Shadows-of-Fire/Apotheosis#1062]
Hello! So everytime i launch/restart my server i keep getting these errors and i'm not sure if i may have misplaced or maybe something related to the mod config is causing these errors.

I haven't modified anything. Everything is on default. For reference i'm using the ATM9 Mod pack.

[Error Log.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13250261/Error.Log.txt)

**Comment by SiverDX** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/1028
