### ISSUE TITLE
Spawn range Bug

### ISSUE THREAD

**Issue by AbaDAAM** [Shadows-of-Fire/Apotheosis#1064]
have an issue with the Spawn range. after using the blaze rod to set it to 3 and then activate the level for it to start spawn mobs and then flick the lever again to turn it off, the Spawn range resets and goes down to 0 and no mobs spawns anymore,

**Comment by Shadows-of-Fire** [comment]
No mechanism in apoth provides for any way to reset the spawn range the way you're describing.  You probably have another mod messing with spawners.
