### ISSUE TITLE
Vein Mining Mod enchantment incompatability

### ISSUE THREAD

**Issue by N00b14nL00z3r** [Shadows-of-Fire/Apotheosis#1065]
With Apotheosis installed the enchantment level is capped at 1.
Existing enchantments function as expected except for trying to increase enchantment level.
If I try to level up the enchantment from 2 to 3 it sets the level to 1.

**Comment by maxiboy211** [comment]
Reported this on the Vein Mining github [here](https://github.com/illusivesoulworks/veinmining/issues/112).

**Comment by Shadows-of-Fire** [comment]
Looks to be a non-issue, just a bad config.
