### ISSUE TITLE
1.19.2 Deep Strider + Swim Speed enchant = breakneck speed

### ISSUE THREAD

**Issue by BlackAures1** [Shadows-of-Fire/Apotheosis#1066]
Apotheosis-1.19.2-6.4.0

If you combine the two enchantments (Deep Strider + Swim Speed), this will happen when you try to swim in lava:
https://github.com/Shadows-of-Fire/Apotheosis/assets/43911230/67a2bc18-8e8c-411c-81ea-917ee3a60103

This can crash or disconnect from the server, and makes it impossible to swim. Same for water.

**Comment by Shadows-of-Fire** [comment]
This looks to be moreso a problem with the Hell Strider enchantment applying unlimited acceleration - but that enchantment is not from apoth.
