### ISSUE TITLE
[BUG] Vial of Arcane Extraction

### ISSUE THREAD

**Issue by ryennce** [Shadows-of-Fire/Apotheosis#1067]
Vial of arcane Extraction not working. 

Version: Apotheosis-1.20.1-7.0.5, playing ATM9

Vial of arcane extraction does not extract anything in the smithing table

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/102876250/5818f201-bf29-419e-a8af-063e11285108)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/102876250/5e400666-7ea8-48a6-a468-2254456d4d1b)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/102876250/5630cce4-9924-4bb6-a807-b299a786a26f)

**Comment by ultrablazed** [comment]
This one is driving me crazy I just wanna unsocket my gems

**Comment by ryennce** [comment]
Since this problem has already been reported, im closing this issue. 

https://github.com/Shadows-of-Fire/Apotheosis/issues/1016
