### ISSUE TITLE
On hit effect from enchantments or affixes affect other players even with PVP false.

### ISSUE THREAD

**Issue by Ernesto-Velasco-Aguilar** [Shadows-of-Fire/Apotheosis#1068]
Enchantments like rebounding or on hit effects like blindness affect other players that hit you. 
Blindness is specially concerning as while the vision effect its temporary, the other players become unable to sprint until rejoining.

**Comment by Shadows-of-Fire** [comment]
I can add a guard for this in `PotionAffix` to prevent the issue you're seeing (which is blindness being applied on the client only, and then never being cleared), but I don't think I can stop rebounding from working that way.

See, for rebounding to work, it has to apply motion to the player on the client side. The way that MC has implemented its "no-pvp" flag is that it only prevents damage from occuring on the server side (for some reason), which means there is no method for me to check if pvp is enabled on the client.
