### ISSUE TITLE
protection IX not available despite config setting

### ISSUE THREAD

**Issue by jlp1528** [Shadows-of-Fire/Apotheosis#1070]
In the Direwolf20 1.20 pack, protection is set to 9 in the config, but only 8 is reachable.

**Comment by Shadows-of-Fire** [comment]
Reachable by what means?

**Comment by jlp1528** [comment]
I cannot get protection 9 by any means. I've tried max enchanting (yes I checked the setup), anvil, and the Library of Alexandria. The config says 9 but I can't get over 8. Also I've noticed the library acting funky, saying I have higher max levels available than I actually get when shift-clicking out books.

**Comment by Shadows-of-Fire** [comment]
You should triage this further with the modpack, I don't believe this is a mod issue. Potentially sounds like a config mismatch if playing on a dedicated server.
