### ISSUE TITLE
There doesn't seem to be a way to change the spawn rate of towers 

### ISSUE THREAD

**Issue by MattBanak** [Shadows-of-Fire/Apotheosis#1074]
Towers spawn far too often for my liking, I wish there was something in the adventure config file to let me change the chance they spawn!

I really wish there was more control in the config about gems. I really wish I could make them much more rare and shape the distribution of chance by rarity! I know I can change what rarities can spawn, but I wish I could prod at the odds by rarity. Same with affixes!

**Comment by Shadows-of-Fire** [comment]
The towers are managed by datapack: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/worldgen/structure_set/
The flags that mostly control placement frequency are `"spacing"` and `"separation"`.
