### ISSUE TITLE
datapack error when changing anything in the apotheosis config

### ISSUE THREAD

**Issue by ozne1** [Shadows-of-Fire/Apotheosis#1075]
having the same issue as an old closed issue #688 but in 1.20.1 
tried to disable adventure module, gets me a datapack error at entering any world, and doesn't let me create any new ones. did some testing, happens if I turn off any of the modules, even setting the "book on join" to false is causing this 

forge 47.2.0

**Comment by SiverDX** [comment]
what do you expect people to do without any logs

also check if it can be replicated with neoforge
https://github.com/Shadows-of-Fire/Apotheosis/issues/1006

**Comment by Shadows-of-Fire** [comment]
duplicate of #989
