### ISSUE TITLE
Apotheosis-1.20.1-7.0.5 Crashes with Placebo-1.20.1-8.5.6

### ISSUE THREAD

**Issue by Mattsingen** [Shadows-of-Fire/Apotheosis#1076]
[crash-2023-11-16_19.33.14-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13382328/crash-2023-11-16_19.33.14-client.txt)

Reverting Placebo to 8.3.7 is a short term fix for me, but it also forces Apothic Attributes to 1.1.4

**Comment by keathunsar** [comment]
I had the same issue, but i also had to revert Apothic Attributes(AttributesLib)[1.1.4] and Gateways to Eternity[4.1.1] because of reverting Placebo[8.3.7].

**Comment by Shadows-of-Fire** [comment]
These versions are only compatible with Apotheosis 7.1.0+
