### ISSUE TITLE
Apothic Attributes 1.20.1-1.2.0 & Placebo 1.20.1-8.5.6 Crashes Server

### ISSUE THREAD

**Issue by Kangy1103** [Shadows-of-Fire/Apotheosis#1077]
Hi, 
With the latest 2 versions of the mods in the title installed my dedicated server refuses to boot. My single player client does though. If I downgrade both mods the server then boots again

Here are the logs:
[2023-11-16-6.log.gz](https://github.com/Shadows-of-Fire/Apotheosis/files/13382538/2023-11-16-6.log.gz)
[2023-11-16-7.log.gz](https://github.com/Shadows-of-Fire/Apotheosis/files/13382539/2023-11-16-7.log.gz)

**Comment by Shadows-of-Fire** [comment]
These versions are only compatible with Apotheosis 7.1.0+

**Comment by Kangy1103** [comment]
Ahhh my mistake, I didn't see the update for Apotheosis as well. Curseforge didn't automagically offer the update
