### ISSUE TITLE
Apotheosis in Technic Modpack not Launching Forge

### ISSUE THREAD

**Issue by MichaelS608** [Shadows-of-Fire/Apotheosis#1080]
This is using the new Apotheosis 7.1.0, as well as ApothicAttributes 1.2.0, Placebo 8.5.6, and Patchouli 1.20.1-81-FORGE, and no other mods. When launching the pack, forge will not launch and vanilla 1.20.1 launches instead.

Link to the modpack: https://www.technicpack.net/modpack/shannypackv2.1979640

**Comment by SiverDX** [comment]
link to log would be nice

**Comment by MichaelS608** [comment]
Still relatively new to this. Since it’s not crashing when launching, how should I get the log for that? Thanks!

**Comment by SiverDX** [comment]
didn't read that right 
sounds like a launcher thing / your setup being wrong / you being in a fabric instance 

no mod can cause that issue

**Comment by MichaelS608** [comment]
Here is a log from the pack working before adding Apotheosis and it's dependencies:
[techniclauncher_2023-11-17-NoApo.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13397198/techniclauncher_2023-11-17-NoApo.log)
And here is a log from the pack not working with just Apotheosis and it's dependencies:
[techniclauncher_2023-11-17.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13397277/techniclauncher_2023-11-17.log)
Still not really sure why the inclusion of Apotheosis and its dependencies results in the pack not launching, it launches fine until I add them. I have double triple and quadruple checked that I am downloading forge versions for the mods as well as compatible versions; I tried 7.0.5 Apotheosis and the older versions of the dependencies that are compatible with it, as well as 7.1.0 Apotheosis with the newer versions of the dependencies and neither will launch with forge when included in the mods folder.

**Comment by SiverDX** [comment]
i dont get it
does it crash or does it not crash?

if it does crash / exit without launching you may need the game output / launcher log
dont know where you get that from the launcher you use

**Comment by MichaelS608** [comment]
Okay I seem to have figured it out or found a workaround. Technic Launcher just gets rid of the forge instance, as well as all apotheosis-related mods for reasons beyond my comprehension, but once I add them back into the mods folder manually it works. Apologize for the trouble and appreciate the responses.
