### ISSUE TITLE
[Crash] Apotheosis Boss Drops cause my game to crash on modpack

### ISSUE THREAD

**Issue by doemty** [Shadows-of-Fire/Apotheosis#1085]
Just as title says
I play minecraft on my own modpack and tried to update apotheosis and dependence mods
[crash-2023-11-21_19.32.41-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13428828/crash-2023-11-21_19.32.41-server.txt)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/13428830/latest.log)

**Comment by SiverDX** [comment]
disable https://www.curseforge.com/minecraft/mc-mods/loot-beams (maybe you can disable some apotheosis related config entry in its config)

it needs to update its compatibility

**Comment by SiverDX** [comment]
actually it already has an update
https://www.curseforge.com/minecraft/mc-mods/loot-beams/files/4882144
so just use that i guess

**Comment by doemty** [comment]
> actually it already has an update https://www.curseforge.com/minecraft/mc-mods/loot-beams/files/4882144 so just use that i guess

it has worked! thank you very much!!
