### ISSUE TITLE
[1.20.1] Flight charm doesn't like dimension change with commands /home or /back from ftb essentials

### ISSUE THREAD

**Issue by jinkhya** [Shadows-of-Fire/Apotheosis#1086]
Hello ! 
I like that the flight charm now works well without the drop, good job on that :) , however when the effect is renewed there's a weird issue going on when you travel to/from another dimension with /home or /back from FTB essentials you're no longer flying and you can't double jump to activate it again. Only way to fix it is by putting the charm in another inventory or disabling it for a few seconds and then putting it back in inventory. 

Best regards,
Jin

**Comment by jinkhya** [comment]
Also seems to happen when you go through a portal with a create train if that helps.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apothic-Attributes/commit/d53840bf99ec6f4eae770daba884faf933ee4757
