### ISSUE TITLE
Step Assist issue for Cyclic - Apotheosis compatibility (Bug)

### ISSUE THREAD

**Issue by OmniNova** [Shadows-of-Fire/Apotheosis#1087]
I heard from this thread (https://github.com/Lothrazar/Cyclic/issues/2346) that Apotheosis is probably responsible for this. In my situation I have Cyclic version (Cyclic-1.16.5-1.5.21.jar) and Apotheosis version (Apotheosis-1.16.5-4.8.99F.jar). When playing in a singleplayer, the Apple of Loft Stature from Cyclic works fine (it's function gives you step assist of a horse's for instant step). In a server and LAN world (I used LAN), me as a hoster and using the apple also works fine, but other joining players who use the apple doesn't work (step assist failure). Now I don't know how much work it might take to fix this bug but it's a bug.

**Comment by Shadows-of-Fire** [comment]
No, the linked issue does not apply to 1.16 (apoth does not mandate usage of the step height attribute until 1.19.2+), so whatever issue you are seeing is unrelated, and probably purely on Cyclic's side.
