### ISSUE TITLE
Please add a keybind to turn step height on/off

### ISSUE THREAD

**Issue by Dragnier** [Shadows-of-Fire/Apotheosis#1089]
While I love this capability of the mod, it can sometimes get annoying when you're trying to enter certain builds as you'll end up on the roof rather than through the door. Having a keybind to turn step height on and off would be extremely useful.

**Comment by Shadows-of-Fire** [comment]
Step height is from forge, so while I might be able to add a keybind that prevents you from stepping up higher than normal, it might not interact properly with other mods.
