### ISSUE TITLE
Apotheosis gems completely reset the weapon

### ISSUE THREAD

**Issue by CYM-GS** [Shadows-of-Fire/Apotheosis#1090]
If you apply gems onto the hammer, the affixing slots of apotheosis will reset the weapon completely.

Video of the Issue: https://streamable.com/o3zhgm

**Comment by Shadows-of-Fire** [comment]
This has always been an issue with the infinity hammer. There is nothing I can do to fix it, it is the only item in any mod that experiences such behavior.
