### ISSUE TITLE
1.20.1 gems not working

### ISSUE THREAD

**Issue by Flame1211** [Shadows-of-Fire/Apotheosis#1092]
None of the gems seem to work. 

I've tried over 20 gems I've collected with items with slots open, and none of them work.
![image_2023-11-24_182028701](https://github.com/Shadows-of-Fire/Apotheosis/assets/112832703/ba3d91bd-363a-4bbf-8d2f-cb97abd97da9)

The photo below is of gems given from the passive skill tree mod, which is compatible with apotheosis. These gems work just fine.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/112832703/da23caa3-5feb-4e06-9cfb-68a998ae61b3)

**Comment by Shadows-of-Fire** [comment]
As far as I'm aware PST in 1.20+ is not compatible with apoth, and as such sockets from them will not slot an apoth gem.  It is unfortunate that they have elected to make their empty sockets look identical to mine despite the incompatibility.

The apoth gems work as intended when an item has an apoth socket present.

**Comment by Flame1211** [comment]
got it, thanks for the quick reply!
