### ISSUE TITLE
can only get gem dust and no rarity item

### ISSUE THREAD

**Issue by Daniellevi12** [Shadows-of-Fire/Apotheosis#1095]
for some reason, I
![image_2023-11-27_041813738](https://github.com/Shadows-of-Fire/Apotheosis/assets/133147223/8e2590a0-575a-4f73-9778-f1cdbd9b2bf9)
 can only get gem dust

**Comment by Shadows-of-Fire** [comment]
You are only showing gems in the salvaging table, those only give gem dust.  Are you unable to place affix items in the table?

**Comment by Daniellevi12** [comment]
yaa i found out i was doing it wrong thanks anyway
