### ISSUE TITLE
Sugarcane should only be 6-8 blocks by default

### ISSUE THREAD

**Issue by Aceplante** [Shadows-of-Fire/Apotheosis#1096]
The current lack of a limit is absolutely ridiculous and OP as heck. I genuinely thought this was a feature of serene seasons, since it would make sense for them to grow taller during the summer only, but from sugarcane to just always do that is just OP.

so at least make it only 6-8 blocks by default, but can be increased via config if you want.

**Comment by Shadows-of-Fire** [comment]
Eh, probably.  They'll be reworked for 1.21 due to replacement finally not being a thing which forces me to deal with them.  For now I won't bother changing it.

**Comment by Aceplante** [comment]
replacement?
