### ISSUE TITLE
Upgraded enchanting tables?

### ISSUE THREAD

**Issue by Aceplante** [Shadows-of-Fire/Apotheosis#1097]
Cant believe this isn't a thing already, but how about upgraded enchanting tables; Nether, crystalline, end etc

**Comment by Shadows-of-Fire** [comment]
So the thing is, given the current system, what would a "better" table even do?  There is nothing remaining to augment at that level.

**Comment by Aceplante** [comment]
some built in eterna/arcana? or unlocks higher level enchants? For example, regardless of eterna, enchants are capped at 5 for the vanilla enchanting table, but sea/nether ones go to 7, endstone one goes to 9, and some sort of endgame one that finally goes to 10?

**Comment by SiverDX** [comment]
the bookshelfs already work as a cap though
need to go to different places / dimensions to get the resources to craft them

they are also the ones powering up the enchantment table itself

- interactions could be things like only being able to enchant netherite or above stuff (controlled by a tag) at a higher enchantment table
- or being able to enchant already enchanted items one additional time

both dont sound that great though

**Comment by Aceplante** [comment]
Hm, I suppose you're right and other than the idea I already mentioned, didn't have any other ideas of how to integrate it, but still feel like it would be a cool idea. Perhaps its cosmetic? Just to be in theme with the bookshelves? But I'm sure a small boost would be appreciated
