### ISSUE TITLE
[Suggestion] Backport piping into the salvaging table to 1.18.2

### ISSUE THREAD

**Issue by jinkhya** [Shadows-of-Fire/Apotheosis#1098]
Hello ! 

I dunno how much work it would involved but would it be possible to get the piping ability into the salvaging table in 1.18.2 please? Any kind of mob farm provides a large amount of affixed items and it's quite the work to salvage them by hand or deal with them in general :')

Thanks in advance, 
Best regards
Jin

**Comment by Shadows-of-Fire** [comment]
No, 1.18 is not receiving updates for any reason.
