### ISSUE TITLE
Reforging table giving a different reforge than expected

### ISSUE THREAD

**Issue by giulgu17** [Shadows-of-Fire/Apotheosis#1099]
Hello, for some reason when I use the reforging table I get a different (sometimes similar) reforge than anticipated

![2023-12-06_21 32 46](https://github.com/Shadows-of-Fire/Apotheosis/assets/66566897/7c60fc6a-e215-4046-ad8c-5c21e985d8a2)
![2023-12-06_21 32 52](https://github.com/Shadows-of-Fire/Apotheosis/assets/66566897/b264c207-c4a1-4881-bd64-7ee30ad07b68)

**Comment by Shadows-of-Fire** [comment]
What version are you using

**Comment by Shadows-of-Fire** [comment]
Closing for lack of information.
