### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by BrisingrAerowing** [Shadows-of-Fire/Apotheosis#11]
[Crash Log](https://paste.dimdev.org/ofiwedacug.mccrash)

Apotheosis Version: 1.6.1
Placebo Version: 1.5.1

Crash occurs on startup.

**Comment by Shadows-of-Fire** [comment]
I appear to have forgotten to comment out all the altar stuff before the release.

**Comment by Shadows-of-Fire** [comment]
Fixed in 1.6.2

**Comment by BrisingrAerowing** [comment]
Thanks! This is an awesome mod.
