### ISSUE TITLE
[Question] How do you enable/disable modules?

### ISSUE THREAD

**Issue by Monkeyatgunpoint** [Shadows-of-Fire/Apotheosis#1101]
I know the mod page says you can disable different modules, but I found nothing on how you do that?
If you could point me in the right direction, I would be very thankful.

Currently I am using the latest release for version 1.20.1 on forge.
I have the Placebo and Patchouli dependencies installed.

**Comment by ZOMBIEOFDE4TH** [comment]
go to your config file, then Apotheosis, then Apotheosis.cfg, then change whichever module you want off from true to false

**Comment by Monkeyatgunpoint** [comment]
Thanks, this was a great help!
