### ISSUE TITLE
Gemming IF Hammer will reset it's level

### ISSUE THREAD

**Issue by Rithenar** [Shadows-of-Fire/Apotheosis#1102]
Playing FTB Genesis with Apotheosis 6.4.1.
I was able to add some affixes to a level 4 Infinity Hammer by upgrading with some godforged pearls and it gave me 2 gem slots. When I tried to slot a light weapon gem, the hammer reset its level to 0 and lost all the affixes.  I tried the same process 4 times with the same results

**Comment by SiverDX** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/1090
