### ISSUE TITLE
Royal gem Increases gravity without any gravity modifiers.

### ISSUE THREAD

**Issue by Catlord-3** [Shadows-of-Fire/Apotheosis#1103]
If you use a slotted royal gem in your helmet slot, your gravity will increase even if you have no gravity altering items or gems equipped. While this is not a huge issue (even with max gem you can still jump up blocks) it is kind of annoying as it makes jumping more frustrating, and I don't want to have to slot in a lunar gem to counteract this effect. A simple solution could be to check if player gravity is the default gravity, and leave it unchanged if it is, and otherwise provide the multiplier.

**Comment by OxiiGiin1** [comment]
Royal gem (any %bonus) also gives unlimited feathers when you also have the [https://www.curseforge.com/minecraft/mc-mods/feathers](url) Mod also installed. 

To recreate add any Royal gem into any slot on any piece of armor what a couple seconds and your feather bar will turn "energized" (meaning it will turn orange and youll have unlimited feather regeneration.)

![2023-12-12_20 51 22](https://github.com/Shadows-of-Fire/Apotheosis/assets/102929976/939e991c-5b29-4fda-a43d-3051c1db6762)
