### ISSUE TITLE
[bug] Client is getting kicked from a server when using the library of alexandria.  invalid distance too far back

### ISSUE THREAD

**Issue by CKY-** [Shadows-of-Fire/Apotheosis#1105]
getting kicked from a server when when using the library of alexandria. invalid distance too
CKY  has disconnected, reasonInternal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: invalid distance too far back

is all that shows in the log odd part is im only 3.5 blocks from the library

**Comment by Shadows-of-Fire** [comment]
That's a DateFormatException, so "too far back" is referring to in time, not in distance.

This is coming from netty internals so it isn't something I can fix, your system time is probably out of sync with the range the server deems valid or something.
