### ISSUE TITLE
[1.20.1] Random crash when exploring world, starting up modpack, etc.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apotheosis#1107]
### **Versions**:
- Apotheosis: 7.2.0
- Apothic Attributes: 1.2.1
- Patchouli: v84
- Placebo: 8.6.0
- Forge: 47.2.17

**Crash-report 1**: https://gist.githubusercontent.com/Gbergz/4dd7b77c8281e6ae24b8fd7cee161a8a/raw/cbf25f9773b03dd751f14c41082ffa2ff6083e71/gistfile1.txt

**Crash-report 2**: https://gist.githubusercontent.com/Gbergz/4806f2132d66a357ad67a8cd9affd79f/raw/5bfaf2e8cb66608dbe3c92ae5acf30abb02271eb/gistfile1.txt

**Crash-report launcher message**: 
`Error: java.lang.NullPointerException: Cannot read field "next" because "this.next" is null`

**-** Gbergz

**Comment by Shadows-of-Fire** [comment]
Someone's applying a mixin to that method, so this is out of my hands to do anything about.  There is no way for a null entry to be present in the linked list under normal circumstances.
