### ISSUE TITLE
2 bugs about "/apoth" commands

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Shadows-of-Fire/Apotheosis#1109]
I found 2 bugs about `/apoth` command in 1.20.1-7.1.0 version.
Bug 1: `/apoth` commands don't have their own run success and fail message;
Bug 2: Try to run `/apoth set_sockets <minus number>`, such as `/apoth set_sockets -1`, means set an item's socket amount to minus, the game will crash, then the world cannot be opened no longer. Too many sockets(such as 1000) will cause the tooltip to overflow the screen, this command needs a max value.
The crash report about bug 2: [link](https://gist.github.com/mc-kaishixiaxue/4531d5c607d979f16e41bb1d5f9245ba)

**Comment by Shadows-of-Fire** [comment]
The commands aren't an officially supported public API, they're mostly for internal debug purposes.  The crash has been resolved though.
