### ISSUE TITLE
Request: Configurable Roque Spawner and Tower Rates

### ISSUE THREAD

**Issue by tslindsay** [Shadows-of-Fire/Apotheosis#1111]
The Rogue Spawners and Apotheosis Towers are great additions to the game, but at times seem to be generated too frequently (especially at lower levels, in the case of Rogue Spawners). It would be nice to be able to customize their spawn rate in a config.

**Comment by RoyalReject** [comment]
This has to be done with datapacks. Mojang changed how worldgen works and that is just how it is now.

**Comment by RoyalReject** [comment]
Default Files: https://github.com/Shadows-of-Fire/Apotheosis/tree/1.20/src/main/resources/data/apotheosis/worldgen/placed_feature
Wiki that explains placed features:  https://minecraft.wiki/w/Placed_feature
