### ISSUE TITLE
[Bug] Combining two same enchantments with one of them exceed max level cause the result level being trimmed down to the max level

### ISSUE THREAD

**Issue by AlisonHuang777** [Shadows-of-Fire/Apotheosis#1114]
For example: Sharpness IX + Sharpness X -> Sharpness IX
(w/ the max level of Sharpness set to 9)

**Comment by Shadows-of-Fire** [comment]
working as intended

**Comment by AlisonHuang777** [comment]
So that means it's a bug that directly applying an enchantment which exceeds max level to a tool/weapon/armor that doesn't have the same enchantment, the level will not get trimmed down?
