### ISSUE TITLE
Server crash randomly at TRANSFORMER/apotheosis@6.4.1/shadows.apotheosis.adventure.loot.LootRarity.random(LootRarity.java:272)

### ISSUE THREAD

**Issue by SneakyDevil** [Shadows-of-Fire/Apotheosis#1115]
Not sure what was causing it, according to my players they were all afking so I have to assume its likely the default spawn mechanics.
[crash-2023-12-27_21.01.10-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13787522/crash-2023-12-27_21.01.10-server.txt)

**Comment by Shadows-of-Fire** [comment]
This is generally caused by having a boss file with invalid rarity bounds. Nothing more I can do here, 1.19 is no longer being developed.
