### ISSUE TITLE
Seashelf of Aquatic Filtration not blacklisting modded enchants.

### ISSUE THREAD

**Issue by Aryxon** [Shadows-of-Fire/Apotheosis#1116]
I am having a issue with the Seashelf of Aquatic Filtration and that is that it's not actually working in blocking the enchants Rebounding and Repellant, I am playing in the latest All the mod 9 pack and I'm enchanting their vibranium armor. I have all sorts of different levels of the enchants in the shelf yet it's not actually blacklisting any of them! It's very annoying, I don't know if they're enchants from Apotheosis or some other mod....

![2023-12-30_00 16 27](https://github.com/Shadows-of-Fire/Apotheosis/assets/14962917/4ae42ca4-bc89-456f-b349-95c2ae9db667)
![2023-12-30_00 16 18](https://github.com/Shadows-of-Fire/Apotheosis/assets/14962917/150afe2a-63a3-49c5-ae89-35cdf6378a9c)
![2023-12-30_00 20 18](https://github.com/Shadows-of-Fire/Apotheosis/assets/14962917/dfbf820e-04fa-4845-8421-f92e5cbf9a45)

**Comment by Shadows-of-Fire** [comment]
Do the enchantments show as crossed out in the enchanting info window (the `?` tab)

**Comment by Aryxon** [comment]
No they do not, but I did learn that it seemingly worked when I moved the shelf down a block. Which is weird cause technically it WAS in a valid shelf space.

**Comment by Shadows-of-Fire** [comment]
If it worked after moving it it means it wasn't being picked up for some reason.  Sometimes certain blocks can prevent the block from being detected, but I don't think there's a bug here.
