### ISSUE TITLE
[Question] How to increase max enchant level + How to increase sockets on items.

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#1117]
Hi! 

**### _Question 1:_** 
So I'm playing ATM9 at the moment and I edited the ATM9\config\apotheosis/enchantments.cfg to increase max lv of enchants to 127 (max)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47760399/90ebd39d-8327-4c67-a38d-08b4ff74341d)

but the max level that shows me on the enchanting table on Minecraft don't go over VIII, what am I doing wrong?
I believe that is something related with power range? Some items on JEI appears on the new level but other's don't.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47760399/0b44be2f-9c96-4e6b-9a6d-c3a43383257e)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47760399/ae9337db-8a1f-49c9-a419-329281a5efc7)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47760399/5664c9fb-a846-4277-b1b0-a65200db20e7)

UPDATE: 

I tried to give me 2 fortune 127 books by command and tried to mix them in a anvil, it won't pass 127, so I supossed this is the way it works? Can't I get super High levels enchants on the enchanting table?

**### _Question 2:_** 

How do I increase the number of sockets that is available on items? 

I found this issue related to my question: https://github.com/Shadows-of-Fire/Apotheosis/issues/723
However, I couldn't find the path that you posted in the comments.
Path: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/recipes/superior_add_sockets.json#L11

Where do I find this path to change the config?

**Comment by RoyalReject** [comment]
Not sure on question 1, but for question 2 you would have to create a datapack to override that recipe or add a recipe that allows another item to apply more sockets.  Just change the max sockets entry

**Comment by Shadows-of-Fire** [comment]
You will only see extremely high level enchantments in the enchanting table if you either (A) raise the level cap of the table _significantly_ by increasing the max available eterna or (B) change the `Max Power Function` of the enchantments you want to increase the level of so that they are available in the existing power range.
