### ISSUE TITLE
[1.18.2] Potion charms assume potion effect from ID, ignoring NBT effects

### ISSUE THREAD

**Issue by eternaleye** [Shadows-of-Fire/Apotheosis#1118]
(I realize I'm reporting against an old version, but it's what the SMP I encountered it on was running and I examined the relevant code, which seems unchanged since then).

When creating a charm from potions which have additional effects not implied by their ID, these effects are not present in the resulting charm. I encountered this with potions derived from another mod:

The mod Ars Nouveau adds a "potion melder". This draws from two "potion jars" from that mod, emitting into a third, consuming three doses each of two potions to produce a single dose of a combined potion. This has the ID of one of the potions, but the second's effects are added via NBT. Crafting charms from these produces a charm with only the effects implied by the base ID of the mixed potion.

I suspect other mods are reliant on NBT potion effects ("When Dungeons Arise" does this with splash potions, using uncraftable splash potions with Wither 4, or multiple effects, but I've not seen non-splash potions like this from that mod to test charm creation with), and the results of ignoring or stripping them may be unpredictable.

**Comment by Shadows-of-Fire** [comment]
Charms are intentionally designed to work only with registered potion types and not custom ones.
