### ISSUE TITLE
Conflict with Everlasting Abilities

### ISSUE THREAD

**Issue by ravendm5** [Shadows-of-Fire/Apotheosis#1119]
Hello,

I've found that using Apotheosis with Everlasting Abilities causes the step assist ability from that mod to not work. This was on MC 1.20.1 and the most recent versions of Forge and both mods.  I have also reported this issue on the Everlasting Abilities site as I am not sure what is causing the conflict.

Any help with this issue would be appreciated.

**Comment by Shadows-of-Fire** [comment]
Apothic Attributes enforces the use of the forge step height attribute.  There are no workarounds and other mods will need to use the attribute.

This will be enforced by vanilla in 1.21

**Comment by ravendm5** [comment]
Gotcha, thanks for the info!
