### ISSUE TITLE
per-category loot rules

### ISSUE THREAD

**Issue by ZoeyPageOfSpace** [Shadows-of-Fire/Apotheosis#1121]
Trying to make a data pack that limits certain categories of items to a different number of sockets, perks, or abilities fails because rarities can't be separated by item category.

**Comment by Shadows-of-Fire** [comment]
This feature managed to sneak in in this commit https://github.com/Shadows-of-Fire/Apotheosis/commit/dedd7f9a49026794880f892c2375ea0996f0849b
