### ISSUE TITLE
Feature Placement Issues

### ISSUE THREAD

**Issue by GreatKingKeenan** [Shadows-of-Fire/Apotheosis#1122]
Feature placement issues of Rogue Spawner causing crash on world load
[crash-2024-01-05_21.19.59-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/13848242/crash-2024-01-05_21.19.59-client.txt)

**Comment by RoyalReject** [comment]
Looks like you have the connector mod, its not a guarantee to work well I would try without it and any fabric mods and see if this is still an issue.

**Comment by baegol** [comment]
Got the same issue without the connector mod, here's my crash report:
https://pastebin.com/d3XmUfmK 

Looks quite similar to the OP's crash report, just without the connector mixin

**Comment by Shadows-of-Fire** [comment]
Weird, these crash reports would imply that either there are zero rogue spawners loaded (which is an error condition for the feature still being loaded) or somehow worldgen is being invoked before data load (which should be impossible).  I can nullcheck this here, but it implies something else is _quite_ broken.
