### ISSUE TITLE
[Suggestion] 1.20.1 config option to change rogue spawner generation

### ISSUE THREAD

**Issue by Visual-Anxiety** [Shadows-of-Fire/Apotheosis#1123]
I enjoy the adventure module quite a lot, however, the rogue spawners are incredibly annoying and I dislike the fact that they spawn rare blocks and loot chests, especially when they spawn so frequently. I have seen people talk about a config option in the adventure config file that disables their generation, however in 1.20.1 versions it seems this option has been removed. I suggest adding this option back in: the ability to configure out frequently rogue spawners generate if at all. Personally, I want an option to prevent them from generating entirely.

**Comment by Shadows-of-Fire** [comment]
Rogue spawners (and other worldgen) must be controlled via datapack in 1.20+, the existing files are here https://github.com/Shadows-of-Fire/Apotheosis/tree/1.20/src/main/resources/data/apotheosis/worldgen/placed_feature
