### ISSUE TITLE
Warlord gem socketing bug

### ISSUE THREAD

**Issue by Sultia** [Shadows-of-Fire/Apotheosis#1124]
When player sockets Warlord gems into their gear they are unable to move.

MC ver: 1.20.1
mod ver: 7.2.0
forge ver: 47.2.19
Modpack: Orbit Cycle

They have socketed multiple warlord gems and have had this issue happen consistently.

Both items they socketed were from L_enders Cataclysm

Cataclysm ver :1.86

**Comment by Shadows-of-Fire** [comment]
Cross-mod issues with closed source mods are not supported.
