### ISSUE TITLE
1.20.1-7.1.0 Spawner attributes reset when unloaded.

### ISSUE THREAD

**Issue by UberAffe** [Shadows-of-Fire/Apotheosis#1128]
The bonus attributes of the spawner such as No-AI and Redstone controlled are retained, but attributes like min/max spawn delay and spawn range reset to their original values every time the spawner is unloaded and reloaded.

To reproduce:
Pick up and place any spawner
Modify any of Min/Max Spawn Delay, Spawn Count, Max Entities, Activation Range, or Spawn Range.
Unload the chunk containing the spawner.
Reload the chunk containing the spawner.
Observe that these attributes have all reset to their original value.

I observed this behavior in a server. I have not tested in other environments.

**Comment by Konin-Sensei** [comment]
I'm noticing the same issue but I don't even need to reload the spawner. After the first time spawning a batch of mobs, all the stats reset. I'm playing in 1.19.2, mod version 6.2.1. No pertinent logs appearing on my server when it happens. I'm using blaze spawners in the nether.

**Comment by UberAffe** [comment]
I noticed that using Ignore-Spawning-Conditions will reset stats as well.

**Comment by Konin-Sensei** [comment]
@UberAffe Are you playing with any other mods? 
EDIT: I just noticed the pack I'm in has the 'harder spawners' mod which has its own config file for spawners. It looks like every time the spawner tried to spawn, it would replace it's stats with the ones defined in the harder spawners config file.

**Comment by UberAffe** [comment]
I don't think there are others that would affect it. But in this modpack (Occultcraft) I can modify the spawners and they work fine. The exception has only been when I use "ignore spawn conditions" or when the spawner unloads/reloads.

**Comment by Konin-Sensei** [comment]
occultcraft has the same mod I mentioned. When I removed it from my pack, the spawner modifiers started working correctly. I would look at the config for that mod or anything the modpack developer did for compatibility as its probably a problem with that since it seems like apotheosis spawners and harder spawners are basically incompatible
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/38869772/7dcb50b8-6e26-45a2-9eb0-9039ec9ea4c4)

**Comment by Shadows-of-Fire** [comment]
Not sure what Harder Spawners is doing but it sounds like a typical incompatibility.  Closing as external/wontfix.
