### ISSUE TITLE
[1.20.1] Mana Pylons and Bookshelves not adding up

### ISSUE THREAD

**Issue by QueenDiancieTTV** [Shadows-of-Fire/Apotheosis#1130]
Previously in older versions I could add 15 bookshelves and 2 mana pylons from botania and it would bring me up to enchanting power / eterna 30, like they would stack. This is not the case in this version, I’m still capped at 15. 

Apotheosis version is 7.2.0 and I’m using it with Enchanting Infuser (which I’ve had no issues with up until now) and It’s not an issue with Enchaning infuser because the issue still happens with regular enchanting table.

I was wondering if this was a bug or an intended feature.

**Comment by Shadows-of-Fire** [comment]
Apoth dows not provide enchanting stats for pylons, so their max eterna is the default of 15.  Whatever modpack you were previously playing may have changed this, but this is working as intended.
