### ISSUE TITLE
unable to join server running save version

### ISSUE THREAD

**Issue by vampirejuicebox** [Shadows-of-Fire/Apotheosis#1132]
![image_2024-01-12_145627831](https://github.com/Shadows-of-Fire/Apotheosis/assets/156473856/90a811ec-c2d7-494c-9ab4-0e2ea74f5eca)
I'm trying to set up a server that uses Apotheosis, but every time I try to join it gives me this error. The file the server uses is a direct copy of the use I'm using for my game. Is anyone else experiencing this or knows how to fix it? I'm on game version 1.19.2

**Comment by Shadows-of-Fire** [comment]
This means your config is mismatched from the server.
