### ISSUE TITLE
1.19.2 Minecraft with 6.4.1 apotheosis causes invalid datapack issue

### ISSUE THREAD

**Issue by Nobi6617** [Shadows-of-Fire/Apotheosis#1134]
Im making my modpack just for fun
and im having trouble with those, really want to put apoth in this pack please help me!!!

Its pretty long though, silly me..

log
 [page 1 of 3](https://pastebin.com/SHaD83H0)
 [page 2 of 3](https://pastebin.com/4vF9Pk8W)
 [page 3 of 3](https://pastebin.com/BDaJHPbL)

crash report
[crash report](https://pastebin.com/24EF6eur)

**Comment by SiverDX** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/issues/883

**Comment by Nobi6617** [comment]
> #883
Ahhhh its caused by Unique Enchantments
solved thx!!
