### ISSUE TITLE
Failed to execute LootRule minecraft:air/apotheosis:uncommon/STAT/1.0!

### ISSUE THREAD

**Issue by AfroSpartan** [Shadows-of-Fire/Apotheosis#1137]
This seems very strange, should it even be affecting air?
I'm working on a mod pack with a ridiculous amount of mods so this is probably a mod conflict but I'm getting the error "Failed to execute LootRule minecraft:air/apotheosis:uncommon/STAT/1.0!" shortly after spawning in a new world.
Is there a list of known incompatible mods, or any pointers as to what could cause this?

Versions 
- Apotheosis-1.20.1-7.2.2.jar
- ApothicAttributes-1.20.1-1.2.1.jar
- ApothicCurios-1.20.1-1.0.3.jar
- ec_apotheosis_plugin-1.20.1-1.1.0-all.jar
- curios-forge-5.4.7+1.20.1.jar
- expanded_combat-1.20.1-3.0.5-all.jar

**Comment by SiverDX** [comment]
mcreator mods tend to add `minecraft:air` to the `curios` tag
either clean them up or ask the dev of `ApothicCurios` to ignore `minecraft:air`

**Comment by AfroSpartan** [comment]
I'll take a look, cheers

**Comment by AfroSpartan** [comment]
I'm pretty new to creating modpacks. Any pointers as to where to look to clean the tags up or and documentation?

**Comment by SiverDX** [comment]
I'm using kubejs 
craft tweaker should also be able to do it 

with datapacks you can only completely overwrite it 

meaning you'd need to clear it completely and add everything back except air

possible if you use the ingame /forge command to list out tag entries and check periodically to make sure you add any new tags

**Comment by AfroSpartan** [comment]
Much appreciated, I'll try that.
I'm guessing it's a case of creating a datapack that contains copies for any items that have the minecraft:air tag but with that tag removed?
