### ISSUE TITLE
[suggestion] PLEASE add a config option to disable sculkshelf noises

### ISSUE THREAD

**Issue by Nicodemus111** [Shadows-of-Fire/Apotheosis#1138]
Sculkshelves making noise is cool conceptually but they annoy me so much it makes me want to use endshelves instead. Having them make noise means that any base that has an enchanting setup will be unnecessarily noisy, it feels dissonant with how much nicer using a mob farm is with the wool spawner upgrade is too.

**Comment by SonyStinks** [comment]
Hear, Hear!

The cool, novel feature put in has worn thin. I'd love to turn it off in config, 'cause I don't think there's another mod out there post-flattening (and CERTAINLY not for 1.20+) that lets you selectively filter out noises.  If a config option is too hard, I'd settle for right-clicking the shelves with some wool.

**Comment by RoyalReject** [comment]
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler

**Comment by Nicodemus111** [comment]
Actually extreme sound muffler cannot select just the sculkshelf sounds. It will only mute the vanilla sculk sounds that sculkshelves also use.
