### ISSUE TITLE
Altar of the Sea crashes world, will no longer load. 

### ISSUE THREAD

**Issue by Survivor1019** [Shadows-of-Fire/Apotheosis#114]
I used the Altar of the Sea in Version 1.11.6 and upon placing all four items the world shut down. I updated to the latest version of Apotheosis (1.12.2 as of right now) but the world continues to shut down immediately after it seems to finish loading. I also tried switching Forge Versions from the one I had been using to the latest version for 12.2. I have played with Apotheosis for a while and used the Altar of the Sea before, the client also loads fine so I don't believe it was a compatibility problem. [Here](https://paste.dimdev.org/qunimomapo.mccrash) is a crash report I got from VanillaFix, let me know if additional information is needed. This mod is pretty cool and I thank you for updating it constantly, which is why I'm not worried about the crash.

**Comment by Shadows-of-Fire** [comment]
Well, thats weird, whatever item you've put on the altar had a null enchantment on it, should be a quick fix to check for that.
Anyway, in the meantime, you can enable removeErroringTileEntities in forge.cfg so your world is usable (this will delete that altar, socjust note that)

**Comment by Survivor1019** [comment]
Thank you, enabling it removed the items in the Altar but the block itself remained.  Is there a way to know within the game whether an enchantment would be null? I don't think any of the enchantments were something out of the ordinary or from a different mod.  Should I close the report since the issue was technically fixed?

**Comment by Shadows-of-Fire** [comment]
What items had you put on the altar?

**Comment by Survivor1019** [comment]
Two Enchantment books (Fire Aspect 1 and Power 1) , a golden sword (Sweeping Edge 2), and an iron sword (Smite 1).
