### ISSUE TITLE
Blacklist some modded boss mobs from Apotheosis boss spawning or add a blacklist config

### ISSUE THREAD

**Issue by Traehgniw** [Shadows-of-Fire/Apotheosis#1141]
It spawned the Aquamirae end boss fight as a random Overworld encounter with bonus Apotheosis affixes, completely outside the context of the Aquarmirae questline and without doing any of the steps for summoning her.

I don't think it should be able to do that, it's a lot like if it randomly spawned a Wither with all the same kind of affixes it'd use to make a skeleton into a bossfight.

**Comment by SiverDX** [comment]
if you dont want that to happen dont install https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions which explicitly adds those things

this does not happen if you just use apotheosis
