### ISSUE TITLE
Gem time lost doesn't bind

### ISSUE THREAD

**Issue by ClementM0512** [Shadows-of-Fire/Apotheosis#1143]
Version of Apotheosis 7.1.0

I upgraded a gem to time lost level with the cutting gem table.
But in can't bind the gem on my item.

Is that a bug or this is not implemented yet ?
![Capture](https://github.com/Shadows-of-Fire/Apotheosis/assets/34575889/c6af9d08-af6d-4b9a-86b2-6f95fef83fbe)

**Comment by Shadows-of-Fire** [comment]
Time-Lost is not a feature of base apoth, so you have a broken addon messing with things.
