### ISSUE TITLE
neruina & apoth 1.19.2 forge "Failed to locate any affixes for air{null} with category LootCategory[curios:charm] and rarity LootRarity{uncommon}."

### ISSUE THREAD

**Issue by loti1234** [Shadows-of-Fire/Apotheosis#1144]
[crash-2024-01-30_15.17.27-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14099691/crash-2024-01-30_15.17.27-server.txt)

**Comment by SiverDX** [comment]
see https://github.com/Shadows-of-Fire/Apotheosis/issues/1137
