### ISSUE TITLE
apotheosis Affixes not matched up

### ISSUE THREAD

**Issue by huntzilla360c** [Shadows-of-Fire/Apotheosis#1145]
when enhancing an item with the Reforging table, the preview affix is not what appears on the item being enhanced
![1](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/dabd8bca-e0a6-4541-af4d-e09f6666ecf8)
![1-1](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/4290b7f7-1613-4ba7-b37a-9a0c86a15111)
![2](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/889aa1fa-af86-46c6-a4c5-d0a4e73b99d4)
![2-1](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/c251a48f-890a-4a26-82de-783080ec873f)
![3](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/92d00c7d-57c5-4fd9-9936-730de6ce9642)
![3-1](https://github.com/Shadows-of-Fire/Apotheosis/assets/61102631/72cda944-77ce-42e5-bd47-c851d5d6a25a)

this is in survival/creative/adventure, any rarity, any applicable item.

**Comment by huntzilla360c** [comment]
This is on TNP Limitless 7, version 0.37.1

**Comment by Shadows-of-Fire** [comment]
Does the issue persist without `Apotheotic Additions` installed?  It doesn't reproduce in isolation, and I don't see anything else that would be obviously messing with the process.

**Comment by SiverDX** [comment]
i think i encountered sth. similar when i had a performance mod which switched out the random objects with a more performant / thread safe variant (that mod was not officially released though)

**Comment by IdrisQe** [comment]
So, to add to this, this appears to only be happening in our server. In singleplayer, it works as it should.
The server has no mods that the client doesn't, but the client has the following mods that the server doesn't:

AmbientEnvironment-forge-1.20.1-11.0.0.1.jar
BetterThirdPerson-Forge-1.20-1.9.0.jar
embeddium-0.2.18+mc1.20.1.jar (Sodium Forge Port)
emoji-type-2.2.3+1.20.4-forge.jar
entity_model_features_forge_1.20.1-1.2.3.jar
entity_texture_features_forge_1.20.1-5.2.1.jar
fabric-api-0.91.0+1.10.5+1.20.1.jar (Forgeified Fabric API)
figura-0.1.3-pre.4+1.20.1-forge-mc.jar
firstperson-forge-2.2.4-mc1.20.1.jar
guiclock-1.20.1-4.4.jar
guicompass-1.20.1-4.4.jar
healthindicatortxf-1.20.1-1.2.2-forge.jar
Jade-1.20.1-forge-11.7.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
lazurite-1.0.1+mc1.20.1.jar (Indium Forge Port)
MouseTweaks-forge-mc1.20-2.25.jar
notenoughanimations-forge-1.7.0-mc1.20.1.jar
notenoughcrashes-4.4.7+1.20.1-forge.jar
OverflowingBars-v8.0.0-1.20.1-Forge.jar
Rrls-3.2.0-1.20.1-forge.jar (Remove Reloading Screen)
sound-physics-remastered-forge-1.20.1-1.3.1.jar
tia-1.20-1.1-forge.jar (Tiny Item Animations)
ToolStats-Forge-1.20.1-16.0.7.jar
visuality-forge-2.0.2.jar

**Comment by IdrisQe** [comment]
> i think i encountered sth. similar when i had a performance mod which switched out the random objects with a more performant / thread safe variant (that mod was not officially released though)

Do you know which mod that was? I'm curious if one we're running may have a similar tweak causing this.

**Comment by Shadows-of-Fire** [comment]
Actually managed to get it to trigger in isolation.  I think something else was making it more common, but the fix should prevent it entirely.
