### ISSUE TITLE
Render thread/ERROR / Analysis Errors

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1152]
Apotheosis-1.19.2-6.4.1.jar
apotheotic_additions1.0.2_v1.19.2.jar
ApothicCurios-1.19.2-1.0.3.jar
Placebo-1.19.2-7.3.5.jar

[placebo/]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
[Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/crude_scythe.
[Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception:
19564 | java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:crude_scythe
19565 | at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%2393!/:?]
19566 | at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%2393!/:?]
19567 | at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%2393!/:?]
19568 | at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19569 | at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19570 | at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19571 | at java.util.HashMap.forEach(Unknown Source) ~[?:?]
19572 | at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19573 | at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19574 | at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19575 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
19576 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
19577 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19578 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19579 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19580 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19581 | at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19582 | at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19583 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19584 | at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19585 | at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19586 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19587 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19588 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19589 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19590 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23122!/:?]
19591 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?]
19592 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?]
19593 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?]
19594 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?]
19595 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?]
19596 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?]
19597 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?]
19598 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
19599 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19600 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19601 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19602 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19603 | at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc4.jar:mmc4]
19604 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19605 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19606 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19607 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19608 | at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
19609 | at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
19610 | at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
19611 | at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
19612 | [08Feb2024 02:54:02.312] [Render thread/ERROR] [placebo/]: Codec failure for type Affix Loot Entry, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
19613 | [08Feb2024 02:54:02.312] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/soul_stained_steel_scythe.
19614 | [08Feb2024 02:54:02.312] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception:
19615 | java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
19616 | at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%2393!/:?]
19617 | at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%2393!/:?]
19618 | at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%2393!/:?]
19619 | at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19620 | at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19621 | at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19622 | at java.util.HashMap.forEach(Unknown Source) ~[?:?]
19623 | at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19624 | at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23563!/:7.3.5]
19625 | at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19626 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
19627 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
19628 | at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19629 | at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19630 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19631 | at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19632 | at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19633 | at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19634 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19635 | at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19636 | at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23639!/:?]
19637 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19638 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19639 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19640 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19641 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23122!/:?]
19642 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?]
19643 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?]
19644 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?]
19645 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?]
19646 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?]
19647 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?]
19648 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?]
19649 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
19650 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19651 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19652 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19653 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19654 | at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc4.jar:mmc4]
19655 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
19656 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19657 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
19658 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
19659 | at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
19660 | at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
19661 | at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
19662 | at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
19668 | [08Feb2024 02:54:02.353] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
19669 | [08Feb2024 02:54:02.353] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2

**Comment by Shadows-of-Fire** [comment]
That's an invalid file from apotheotic additions.

**Comment by Krimatoria** [comment]
And what does it mean? Do I need to remove some kind of mod?

> That's an invalid file from apotheotic additions.
