### ISSUE TITLE
Suggestion! 1.19.2. 

### ISSUE THREAD

**Issue by DigitalWendigo** [Shadows-of-Fire/Apotheosis#1153]
Hey there! 
Awesome mod, first time trying it out. 

Would it be possible to make spawned bosses not despawn like regular mobs? 
Sometimes a rare boss spawns, and it despawns before I can even get to it, since it's, for example; across a lava lake. 
I figured since they're named, they wouldn't despawn by default, yet they still do. 
Checked the config files, but I don't see an option related to boss despawning, so I figured I'd post a suggestion here! 

Cheers!

**Comment by Shadows-of-Fire** [comment]
I can't make them never despawn as they would eventually start piling up too heavily.  You could install https://www.curseforge.com/minecraft/mc-mods/mob-despawn-timers to ensure that all mobs stick around for a certain duration before being removed by the spawn process.

**Comment by DigitalWendigo** [comment]
> I can't make them never despawn as they would eventually start piling up too heavily. You could install https://www.curseforge.com/minecraft/mc-mods/mob-despawn-timers to ensure that all mobs stick around for a certain duration before being removed by the spawn process.

Ah, that does make sense. 
But what if the game (in this case your mod) would check for existing bosses in loaded chunks before spawning new ones, in which case it won't if there are; let's say, 5 Apotheosis bosses, ? 
I'm no mod developer, so I'm likely unaware of what I'm actually even asking in terms of difficulty and hassle, in which case I do apologize. - But, what are your thoughts? 
But I'm definitely going to try out the mod you just suggested and make do with that. 
Cheers!
