### ISSUE TITLE
Neruina Caught Exception: Apotheosis + Super Bosses + Neruina (Loot Apotheosis Crash Item)

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1155]
I have described the whole problem here. But I'm duplicating it for Apotheosis.
https://github.com/Bawnorton/Neruina/issues/43 

What Super Duper looks like - they don't have a visual change, you need [1.19.2][Forge] RPG-HUD-3.10.1.jar to see them, hover over them with the mouse and there will be a signature.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/a37eb24b-14f0-49e6-acf2-cfab03c7e091)

I found the relationship of the problem and what causes it. The SuperBoss mod that I added to the build where creepers are enhanced with the Enhanced AI mod (their explosion force is greater than usual) strengthens them even more by generating colossal explosions, but this does not cause problems or crashes of the game until the Apotheosis mod is added, it adds its loot to mobs.

The Neruina mod was already installed when SuperBoss was added and I tested it on superplanes, I never had the creeper essence removed before the explosion.

I added the problem code from the log file below. The problem arises when charged creepers explode, both ordinary ones and from the Super Bass mod (Super Bass - the mod itself does not add mob eggs, this is important)

How to check it. You need a Super Boss mod, it needs 4 library mods: Pehkui-3.7.11+1.19.2- forge.jar, MobsPropertiesRandomness-4.2.3-mc1.19.2.jar, lootjs-forge-1.19.2-2.9.1.jar, kubejs-forge-1902.6.2-build.59.jar

There are no SuperBoss eggs, so you just take the egg of an ordinary creeper and spawn it until you have a SuperDuper creeper or its lightning-charged version.

You need a Charged or regular SuperDuper - precisely because their power is huge.

Yes, sometimes you need to wake him up a lot of times for him to appear. You set it on fire with a flint and in the event of an explosion, which will not happen, it will be prevented by Neruina with a message about the removal of the ticking entity. When playing on a server of 3 people, this caused a crash from the server. Although Neruina was created so as not to break the game, apparently departure is the best option.

I do not know which item adds Apotheosis to creepers, but the Log says about these categories of items:
LootCategory[curios:back] and rarity LootRarity{common}.

I added the problem code from the log file below. The problem arises when charged creepers explode, both ordinary ones and from the SuperBoss mod (SuperBoss - the mod itself does not add mob eggs, this is important)

How to check it. You need a SuperBoss mod, it needs 4 library mods, Enhanced AI 1 library [InsaneLib](https://www.curseforge.com/minecraft/mc-mods/insanelib):

1. Pehkui-3.7.11+1.19.2- forge.jar,
2. MobsPropertiesRandomness-4.2.3-mc1.19.2.jar,
3. lootjs-forge-1.19.2-2.9.1.jar,
4. kubejs-forge-1902.6.2-build.59.jar

There are no SuperBoss eggs, so you just take the egg of an ordinary creeper and spawn it until you have a SuperDuper creeper or its lightning-charged version.

You need a Charged SuperDuper or regular SuperDuper - precisely because their power is huge.

Yes, sometimes you need to wake him up a lot of times for him to appear. You set it on fire with a flint and in the event of an explosion, which will not happen, it will be prevented by Neruina with a message about the removal of the ticking entity. When playing on a server of 3 people, this caused a crash from the server. Although Neruina was created so as not to break the game, apparently departure is the best option.

Related to Common and Uncommon items.
I do not know which item adds Apotheosis to creepers, but the Log says about these categories of items:

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6676 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{common}.
6677 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6678 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6679 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6713 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{uncommon}.
6714 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6715 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6716 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]

![2024-02-08_23 37 35](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/4b3fdfc0-20c5-4c48-a2e2-e741eb7bbbd9)
![2024-02-08_23 07 27](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/d5043f2d-4fee-4eac-a7be-e81efeac5a9c)
![2024-02-08_23 07 51](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/cc09855e-5962-4c7e-9d20-c71dbee2a2ff)
![2024-02-08_23 08 35](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/6da6efe5-d01c-402b-a308-47b1a71b390a)
![2024-02-08_23 08 38](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/c30ac1d7-2f7c-4a0f-837a-79df35a171ef)
![2024-02-08_23 18 12](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/ec9a56b4-b15c-4006-ace9-019c65425e91)
![2024-02-08_23 18 14](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/a08ddcb5-b339-4c64-a91d-578daad846e4)
![2024-02-08_23 33 18](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/201241c2-6d06-4624-919a-7d4e68d159cf)
![2024-02-08_23 33 44](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/e0911361-9969-4c3e-89e6-fb8429b250ea)
![2024-02-08_23 34 09](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/d8db7d52-b552-43b2-8ad7-ce7a07e24532)
![2024-02-08_23 34 16](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/d8634342-e536-447a-88da-be37d8cc6bed)
![2024-02-08_23 34 17](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/e8fe76b2-246e-40dd-9643-75ed90d29bb3)
![2024-02-08_23 34 23](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/e0536722-d014-4901-be37-efc5ba23c732)
![2024-02-08_23 35 59](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/a193051f-f56e-4f58-9d05-c72348e874cf)
![2024-02-08_23 36 06](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/39f8ebd2-044e-4bea-8391-2cc2f5607b4c)

[08Feb2024 23:04:06.861] [Server thread/WARN] [neruina/]: Neruina Caught Exception
6713 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{uncommon}.
6714 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6715 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6716 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6717 | at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6718 | at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6719 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6720 | at net.minecraft.world.entity.LivingEntity.m_7625_(LivingEntity.java:1374) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6721 | at net.minecraft.world.entity.Mob.m_7625_(Mob.java:483) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6722 | at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1339) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6723 | at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1298) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6724 | at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6725 | at net.minecraft.world.level.Explosion.m_46061_(Explosion.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6726 | at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:996) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6727 | at net.minecraft.world.level.Level.m_46511_(Level.java:485) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6728 | at net.minecraft.world.entity.monster.Creeper.m_32315_(Creeper.java:225) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6729 | at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6730 | at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6731 | at net.minecraft.world.level.Level.mixinextras$bridge$accept$138(Level.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6732 | at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23572!/:?]
6733 | at net.minecraft.world.level.Level.wrapOperation$ckf000$catchTickingEntities(Level.java:3038) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6734 | at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6735 | at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6736 | at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6737 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6738 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6739 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6740 | at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6741 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6742 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6743 | at java.lang.Thread.run(Unknown Source) [?:?]

[Server thread/WARN] [neruina/]: Neruina Caught Exception
6676 | java.lang.RuntimeException: Failed to locate any affixes for air{null} with category LootCategory[curios:back] and rarity LootRarity{common}.
6677 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:71) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6678 | at shadows.apotheosis.adventure.loot.LootController.createLootItem(LootController.java:40) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6679 | at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:37) ~[Apotheosis-1.19.2-6.4.1.jar%23406!/:6.4.1]
6680 | at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6681 | at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1320) ~[forge-1.19.2-43.3.5-universal.jar%23674!/:?]
6682 | at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:90) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6683 | at net.minecraft.world.entity.LivingEntity.m_7625_(LivingEntity.java:1374) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6684 | at net.minecraft.world.entity.Mob.m_7625_(Mob.java:483) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6685 | at net.minecraft.world.entity.LivingEntity.m_6668_(LivingEntity.java:1339) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6686 | at net.minecraft.world.entity.LivingEntity.m_6667_(LivingEntity.java:1298) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6687 | at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1155) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6688 | at net.minecraft.world.level.Explosion.m_46061_(Explosion.java:203) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6689 | at net.minecraft.server.level.ServerLevel.m_7703_(ServerLevel.java:996) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6690 | at net.minecraft.world.level.Level.m_46511_(Level.java:485) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6691 | at net.minecraft.world.entity.monster.Creeper.m_32315_(Creeper.java:225) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6692 | at net.minecraft.world.entity.monster.Creeper.m_8119_(Creeper.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6693 | at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6694 | at net.minecraft.world.level.Level.mixinextras$bridge$accept$138(Level.java) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6695 | at com.bawnorton.neruina.handler.NeruinaTickHandler.safelyTickEntities$notTheCauseOfTickLag(NeruinaTickHandler.java:115) ~[neruina-1.3.0-forge+1.18.2-1.20.1.jar%23572!/:?]
6696 | at net.minecraft.world.level.Level.wrapOperation$ckf000$catchTickingEntities(Level.java:3038) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6697 | at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6698 | at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6699 | at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6700 | at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6701 | at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6702 | at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6703 | at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6704 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6705 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23669!/:?]
6706 | at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by Shadows-of-Fire** [comment]
The issue you are seeing is caused by Apothic Curios.

**Comment by Krimatoria** [comment]
> The issue you are seeing is caused by Apothic Curios.

I wrote to the developer. The problem is solved with the released updated mod Apothic Curios
