### ISSUE TITLE
Impossible to modify recipes for Hellshelf and Seashelf using datapacks or KubeJS mod.

### ISSUE THREAD

**Issue by LMongoose** [Shadows-of-Fire/Apotheosis#1158]
I am developing a custom modpack and I want to edit some recipes, however when I tried removing the recipes for hellshelf and seashelf nothing happens, I searched on this repo and didn't found JSONs for their recipes, I tried with all other shelfs and they can be edited except the hellshelf and seashelf.

**Comment by Shadows-of-Fire** [comment]
Those use a slightly weird™ code recipe subsystem which hasn't been phased out yet.  You can change their recipes by adding a new recipe with the same recipe ID.

**Comment by LMongoose** [comment]
Oh thanks, I never though it was possible.
