### ISSUE TITLE
[Feature Request] Multishot scales with level

### ISSUE THREAD

**Issue by muon-rw** [Shadows-of-Fire/Apotheosis#1159]
I think the title sums this up nicely, but I always thought it was very disappointing that higher levels of Multishot change nothing in vanilla. I think this sort of thing fits perfectly into the rest of Apotheosis. 

It would probably best to scale additively (1>3>5>7 arrows), and have the default level cap at around 3.

**Comment by Arceus-77** [comment]
use commands to make multishot 999 and shoot a trillion arrows

**Comment by Shadows-of-Fire** [comment]
I think vanilla has added this in 1.21? The new implementation _looks_ like it should support level scaling.
