### ISSUE TITLE
The server can't connect to the server because the item registries don't match.

### ISSUE THREAD

**Issue by loboazul0103** [Shadows-of-Fire/Apotheosis#1166]
I installed the same version of Apotheosis on both server and client, and when I tried to connect, I couldn't because the item registries didn't match.
 When I opened the server with my personal PC, I had no problems, but when I opened it through the hosting site, or at certain times, this happened.
 The item in the registry that doesn't match is an item called ender_lead.
I don't know what the exact cause of this problem is.
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/14279540/latest.log)

**Comment by SiverDX** [comment]
make sure client and server have the same configs

**Comment by loboazul0103** [comment]
Ah, That's a really simple issue! I thought it was a problem with the modes themselves when I saw "modes don't match". I have no idea what is causing this and have been at a loss all day. thanks so much for letting me know.
