### ISSUE TITLE
Crashes when installing Apotheosis in my modpack

### ISSUE THREAD

**Issue by doemty** [Shadows-of-Fire/Apotheosis#1168]
Basically, everything in the title.
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/14288510/debug.log)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/14288511/latest.log)

**Comment by Shadows-of-Fire** [comment]
Whatever mod is indicated by `me.replet.client.other.AnvilScreenHandlerMixin` is incompatible with apoth.
