### ISSUE TITLE
[Question] Blacklisting Spawn Egg from Spawner

### ISSUE THREAD

**Issue by NillerMedDild** [Shadows-of-Fire/Apotheosis#117]
Hey, I'm having trouble using the blacklist config `Banned Mobs` in the `spawner.cfg`.
I've tried with the following values:

`quark:stoneling`
`stoneling`
`"quark:stoneling"`
`"stoneling"`

At this point I'm a bit sick of /reloading, could you tell me what the correct syntax is please? :)

**Comment by Shadows-of-Fire** [comment]
`quark:stoneling` should be the proper syntax assuming thats the registry name.
Also those configs don't support /reload, unfortunately.

**Comment by NillerMedDild** [comment]
That did the trick, thanks - I thought /reload worked so I hadn't actually tried quark:stoneling
Sidenote, I was given the advancement `Spawner Modifier` when I clicked a spawner with the blacklisted spawn egg for `quark:stoneling`
