### ISSUE TITLE
apotheosis structure overriding cracker's wither storm mod

### ISSUE THREAD

**Issue by shade1822226911** [Shadows-of-Fire/Apotheosis#1170]
whenever this mod is played with cracker's wither storm mod on the latest version, apotheosis has a high chance to spawn a tower on the generated structure cracker's wither storm mod generated at x=0, z=0, effectively making said mod unprogressable.
is there a way to make apotheosis structures generate around x=0 z=0 but not actually on it [50 blocks away from 0, 0 is good enough]

**Comment by shade1822226911** [comment]
a config to change the spawn rate of the tower would be nice if implemented aswell

**Comment by Shadows-of-Fire** [comment]
The spawn frequency of the towers are controllable via datapack: https://github.com/Shadows-of-Fire/Apotheosis/tree/1.20/src/main/resources/data/apotheosis/worldgen/structure_set
