### ISSUE TITLE
Incompatibility with Tetra - Affixes Removed

### ISSUE THREAD

**Issue by Lokilotus** [Shadows-of-Fire/Apotheosis#1173]
**Summary of Bug**
Affixes on tools are removed when Tetra is used to swap parts.

**Observed behaviour**
Pick up an affixed Apotheosis item:
![Affix Item Screenshot](https://github.com/Shadows-of-Fire/Apotheosis/assets/2342253/963c5eec-8798-4bdf-ad8b-0d9567d90fa0)

Place it in the Tetra table and prepare to swap the head (or indeed, any part):
![Affix Item Preswap](https://github.com/Shadows-of-Fire/Apotheosis/assets/2342253/968f595b-c6e1-47b0-87b1-2253958dcf36)

Replace the tool part and note that the affixing has disappeared.
![Affix Item After Swap](https://github.com/Shadows-of-Fire/Apotheosis/assets/2342253/390be8a3-e81a-488c-99a8-f36099d31092)

**Expected behaviour**
Affix remains on Tetra tool, i.e. in the example above, the result should be a Diorite-headed Murderous Axe of the Butcher, with Speed on hit, a 30% chance to sweep, 11% durability resistance, 27% Armor Shred, 24% Crit Chance, and one socket.

**Steps to reproduce**
1. Pick up an affixed Apotheosis item:
2. Place it in the Tetra table and prepare to swap the head (or indeed, any part):
3. Replace the tool part and note that the affixing has disappeared.

**Crashlog**
No crash occurs, but logs from Server and Client can be procured on request.

**Apotheosis version**
4.10.1

**Tetra Version**
4.5.0

**NeoForge version**
1.20.1 - 40.1.84

**Other mods**
A full modlist for our server can be provided on request.

**Other Information**
Previously reported to the Tetra developers on October 24th 2022 by another user of Tetra and Apotheosis (unknown to our server), but issue disappeared in future versions of both mods before reappearing now. The issue on the Tetra bugtracker is https://github.com/mickelus/tetra/issues/673#issue-1420755486 and I have commented on it that the issue has reappeared. I shall reference this issue in that thread also.

**Comment by Shadows-of-Fire** [comment]
There is nothing I can do about this - tetra must maintain the item's NBT data while performing such manipulations.
