### ISSUE TITLE
Ignoring backup rules 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1174]
Forge 43.3.5
Minecraft 1.19.2
Apotheosis-1.19.2-6.4.1.jar
[I understand the same problem. ](https://github.com/Shadows-of-Fire/Apotheosis/issues/1051)

Does this apply to them again Apotheotic Additions or to your mod?

> [16:34:50] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
> [16:34:50] [Render thread/ERROR]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
> 
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:ringRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:an_focusRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:necklaceRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:charmRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:beltRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:spellstoneRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:scrollRequired: 4; Provided: 3
> [22Feb2024 03:47:57.858] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:braceletRequired: 4; Provided: 3
> [22Feb2024 03:47:57.859] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:talismanRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:ringRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:an_focusRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:necklaceRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:beltRequired: 4; Provided: 3
> [22Feb2024 03:47:57.860] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:spellstoneRequired: 4; Provided: 3
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:scrollRequired: 4; Provided: 3
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:braceletRequired: 4; Provided: 3
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:talismanRequired: 4; Provided: 3
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:ringRequired: 3; Provided: 2
> [22Feb2024 03:47:57.861] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:necklaceRequired: 3; Provided: 2
> [22Feb2024 03:47:57.862] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category curios:charmRequired: 3; Provided: 2
>

**Comment by Shadows-of-Fire** [comment]
The only one relevant to base are those first two lines (the mythic ones for helm/boots) - the backup rules handle them appropriately.  The rest are apothic curios (which typically falls under user error, as apothic curios does not ship any affixes by default, so the user/packdev is liable to provide them).

**Comment by Krimatoria** [comment]
> The only one relevant to base are those first two lines (the mythic ones for helm/boots) - the backup rules handle them appropriately. The rest are apothic curios (which typically falls under user error, as apothic curios does not ship any affixes by default, so the user/packdev is liable to provide them).

So is this an apothic curios problem?

**Comment by Shadows-of-Fire** [comment]
No, because apothic curios does not provide affixes.  It is a modpack problem.

**Comment by Krimatoria** [comment]
> Нет, потому что апотические сувениры не содержат аффиксов. Это проблема модпака.

And that is, the problem is in some mods? I'm trying to understand what affixes are. Are these some kind of drop-down items from mobs or what is it? 

Google shows pictures with a description in a frame for this))) I want to understand at least which way to look to look for this mod. I have 280 of them in the assembly+

**Comment by Shadows-of-Fire** [comment]
Affixes are the bonuses applied to items.  Granted, the addons mod is supplying curios affixes, so it may be their fault for not supplying a sufficient amount: https://github.com/Bryce792/ApotheoticAdditions/tree/main/data/apotheotic_additions/affixes

**Comment by Krimatoria** [comment]
> Аффиксы — это бонусы, применяемые к предметам. Конечно, мод дополнений предоставляет аффиксы любопытных предметов, поэтому это может быть их вина, что они не предоставили достаточного количества: https://github.com/Bryce792/ApotheoticAdditions/tree/main/data/apotheotic_additions/affixes

And how does this affect the game? I mean, this error is higher.
 [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity epic for category curios:ringRequired: 4; Provided: 3

 I'm sorry for asking a lot of questions, it's just that this has been a bug for quite some time and I haven't reported it on ApotheoticAdditions yet. I'm just going to make a branch on this topic there.

**Comment by Shadows-of-Fire** [comment]
If you see this error it means that items of the specified category of rarity may not generate with the desired number of affixes.

**Comment by Krimatoria** [comment]
> If you see this error it means that items of the specified category of rarity may not generate with the desired number of affixes.

Well, yes, it's not very good))) Thanks for the answers) It became clearer) This is how many items do not appear) considering that there are 23 such errors, and sometimes more)

**Comment by Krimatoria** [comment]
> Если вы видите эту ошибку, это означает, что предметы указанной категории редкости не могут генерироваться с желаемым количеством аффиксов.

Is this error critical? It's just different, do I need to open a new post with this error?

[25Feb2024 01:53:00.513] [Server thread/ERROR] [Apotheosis : Adventure/]: Failed to locate any gear sets matching the following predicates: 
[25Feb2024 01:53:00.513] [Server thread/ERROR] [Apotheosis : Adventure/]: SetPredicate[#terrible]

**Comment by Mjolinir** [comment]
I see this on my server as well, and I'm trying to understand the issue.  What exactly needs done here to make it behave as it should? Is there any documentation on how to correct this?
