### ISSUE TITLE
Stackable items can't be enchanted

### ISSUE THREAD

**Issue by RedBlockCreator** [Shadows-of-Fire/Apotheosis#1178]
What the title says. 

I have tested this by making items stackable with bigger stacks and kubejs, both do not allow items to be enchanted.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3914603/44941150-0159-4b44-8729-4b1e69f663c7)

**Comment by Shadows-of-Fire** [comment]
This issue will present in vanilla as well and is not something I am willing to change (due to potential introduction of side effects).

The vanilla code for `Item#isEnchantable` is 
```java
   public boolean isEnchantable(ItemStack pStack) {
      return this.getMaxStackSize(pStack) == 1 && this.isDamageable(pStack);
   }
```
which means changing the stack size will make the items non-enchantable.
