### ISSUE TITLE
Null pointer exception: Ticking entity 1.14

### ISSUE THREAD

**Issue by ValueTown1** [Shadows-of-Fire/Apotheosis#118]
I've been having issues in my modpack for quite a while now with null pointer crashes on ticking entities. We've looked into it and we believe it's your mod that is causing the issue. If i'm wrong I apologize.

Here's a couple example crash logs:
https://pastebin.com/ipuxM5nf
https://paste.ee/p/rlYdy

Here's the modpack for reference:
https://www.curseforge.com/minecraft/modpacks/valuepack-2/files

**Comment by Shadows-of-Fire** [comment]
Not sure why you think apoth has anything to do with that, damage indicatiors is the only mod in the call stack, which means its on them
