### ISSUE TITLE
[Suggestion] Allow Feather/Pointed Dripstone usage on Mob Spawners

### ISSUE THREAD

**Issue by Delfite** [Shadows-of-Fire/Apotheosis#1180]
### **The Suggestion**
Allow the player to use Feathers or Pointed Dripstone to tweak mobs spawned from a Mob Spawner to have increased susceptibility to fall damage.

### **An Example**
I right click a spawner with Pointed Dripstone and the mobs spawned from that spawner will now take 2x fall damage. Inversely, they will take no fall damage if I applied it while Quartz was in my offhand.

### **My reasoning behind the addition of this feature**
Currently, mob farms that use pointed dripstone to increase the fall damage that mobs take have an issue where items will get stuck on top of the dripstone and remain there until they despawn naturally or the player picks them up. This can not only cause additional server lag but can also put a damper on a mob farm's efficiency when it comes to automation. Sure, you could use Create to push the item off of the dripstone using a Mechanical Fan, but not every modpack has Apotheosis AND Create in the same bundle, hence my reasoning for why I made this suggestion. There's also the fact that it would allow for more compact mob farm designs in situations where the player can't really afford to dedicate a ton of space towards a mob farm.

### **Balancing**
I am unsure as to how you would balance this feature, but I hope it gets added regardless of what you come up with!

**Comment by Shadows-of-Fire** [comment]
Staged as part of the 1.21 update

**Comment by Delfite** [comment]
> Staged as part of the 1.21 update

Sweet! Can't wait to design new farms around this!
