### ISSUE TITLE
Boss not Spawn

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1181]
Apotheosis-1.19.2-6.4.1.jar

> This creeper is not the boss)) But he was right in the beam) Maybe it's a coincidence. I saw the appearance of a new boss, but when I arrived in creative mode, I only saw a ray. There is usually a long glow. He was gone, as was the boss himself. I've already seen this a few times. Especially in hell. Maybe it's some kind of mistake when he was spawning.

![2024-02-27_15 19 27](https://github.com/Shadows-of-Fire/Apotheosis/assets/106809386/bd1d9438-5444-4b7e-8092-5e144015ee8c)

**Comment by Shadows-of-Fire** [comment]
That would mean that apotheosis attempted to spawn the boss, and it was reported as successful, but the boss was either removed by another mod or despawned.  For the latter issue, you can attempt using the mod Mob Despawn Timers.  For the former issue, there isn't much that can be done, as mods are allowed a lot of control over entity spawns.
