### ISSUE TITLE
Client crashes whenever I try to open a container (Chest, barrel, etc)

### ISSUE THREAD

**Issue by Mrwerebear** [Shadows-of-Fire/Apotheosis#1184]
The issue happens on a server, but I am the only one who's having crashes. It seems that I can't replicate it in singleplayer worlds.
[crash-2024-03-02_21.43.33-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14470478/crash-2024-03-02_21.43.33-client.txt)

**Comment by Shadows-of-Fire** [comment]
Duplicate of #1165 
This was fixed in 7.3.1
