### ISSUE TITLE
AttributeFix 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1185]
https://github.com/Darkhax-Minecraft/AttributeFix/issues/51
I removed the configs, the problem remained, but they haven't answered me there yet what to do about it.

> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:mining_speed' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:arrow_velocity' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:healing_received' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:draw_speed' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:ghost_health' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:prot_pierce' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:armor_pierce' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.569] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:prot_shred' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:arrow_damage' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:fire_damage' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:current_hp_damage' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:overheal' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:crit_chance' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:dodge_chance' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:cold_damage' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:crit_damage' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:life_steal' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:experience_gained' does not belong to a known attribute. This entry will be ignored.
> [03Mar2024 02:18:33.570] [Worker-ResourceReload-5/ERROR] [AttributeFix/]: Attribute ID 'apotheosis:armor_shred' does not belong to a known attribute. This entry will be ignored.
>

**Comment by Shadows-of-Fire** [comment]
You have to delete / reset the AttributeFix config.  According to your messages in the other issue, all you did was reset your Apotheosis config (which is irrelevant here).
