### ISSUE TITLE
Diamond Loot 1.20.1

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1186]
Apotheosis-1.20.1-7.3.1.jar
Maybe it's related to this mod:

- ancient_manuscripts-1.1.4-1.20.1.jar
- ancient_aether-0.8.8.jar

https://gist.github.com/Krimatoria/1a29ca102322372839685d01cdb0d993 - Log

**Comment by Shadows-of-Fire** [comment]
Ancient items are not implemented, generating them is unsupported.
