### ISSUE TITLE
[bug?] Problem with "radial" affix

### ISSUE THREAD

**Issue by DankestO** [Shadows-of-Fire/Apotheosis#1190]
I've been using apotheosis version 1.20.1-7.2.2, the "radial" affix for pickaxes worked with other mods, such as Create and CC: Tweaked.

But, since version 1.20.1-7.3.1 (which is the one I'm using now) it no longer works in these mods, is this intentional?

**Comment by SiverDX** [comment]
Did you try the different modes?

https://github.com/Shadows-of-Fire/Apotheosis/blob/c487e1fef537b5a187420864db2f281d296f8db2/changelog.md?plain=1#L17-L20

Maybe it's disabled or only enabled while sneaking for you

**Comment by DankestO** [comment]
I tried that with each of the modes before giving the tools to the Create contraptions and the CC: Tweaked turtles, but I didn't notice any changes, it could be that those entities work differently with the new keys added in the last update ?

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/126206944/2aab52fe-c9f6-499b-8b01-0e05e6005bab)


I also went to check it in the version that 7.2.2 used before, and in this case it does dig 5x5
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/126206944/4d5c09b9-bef4-4b76-988b-22389bf63c66)

**Comment by SiverDX** [comment]
oh you meant create things using the tool

i think the default mode is actually "requires sneaking" 
https://github.com/Shadows-of-Fire/Apotheosis/blob/c487e1fef537b5a187420864db2f281d296f8db2/src/main/java/dev/shadowsoffire/apotheosis/adventure/affix/effect/RadialAffix.java#L222
(would have to set and get the ordinal for the default to be not-sneaking or return a different value here)

and those things probably use a fake player, so you changing the configuration won't have any effect

**Comment by DankestO** [comment]
aah, now I understand why it didn't work xD
Yup, I mean that, I usually make trains that dig for me with Create, the same with the CC tortures, it makes my life much easier (?
I would appreciate then if there was some way to set it to "not-sneaking" by default.

**Comment by Shadows-of-Fire** [comment]
Looks like the default mode got incorrectly set to `REQUIRE_SNEAKING` instead of `REQUIRE_NOT_SNEAKING`.  Will be fixed next update.

**Comment by DankestO** [comment]
Thank you! :D
