### ISSUE TITLE
CTD with Ring of ascension

### ISSUE THREAD

**Issue by glea94** [Shadows-of-Fire/Apotheosis#1196]
Hi, i have the mod Ring of Ascension+curios api.
I actually have 2 rings in 2 slots, both with sockets to put gems.
One actually do not have any gem in, i can see the info about the ring.
The second do have a gem socketed and it CTD when the mouse cursor go on to see info about the ring.
I went to the dat file to see what's going on with the ring and see this :
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/89050166/6aff4b04-1f5d-4dcb-9cc1-d8a69c59589a)
I didn't have this bug before, it seems to happen with the last 7.3.3 update. On 7.3.1 the ring was already socketed with this gem and didn't ctd.
Thank you.

**Comment by glea94** [comment]
I alos have ApothicCurios (i can socket gem in jewelry etc..), but I didn't get any ctd before, the last ApothicCurios uodate is about a month ago. So i do not report this but to daripher cause the last update i got was from apotheosis.

**Comment by Shadows-of-Fire** [comment]
Crash issues must provide a crash report at the bare minimum.

**Comment by glea94** [comment]
Ok but i have 215 mods... the crash log is very long. Do you want just the part where it crash or all the log?

**Comment by glea94** [comment]
https://mclo.gs/aPNysQk
The log start when i enter the map and then put the cursor on the ring
thank you

**Comment by Shadows-of-Fire** [comment]
Apothic Curios is not compatible with the most recent apoth release.  You will need to report an issue to them and wait for them to fix it.

**Comment by glea94** [comment]
Ok thank you😊
