### ISSUE TITLE
[Question] 1.20.1 -1.19.2 wrong mod :P

### ISSUE THREAD

**Issue by SGZ-Creations** [Shadows-of-Fire/Apotheosis#1197]
Is there any chance that the new Hephaestus Forge system gets backported to 1.19.2 as I'm hoping to use it in my 1.19.2 modpack?

**Comment by Shadows-of-Fire** [comment]
The what now

**Comment by SGZ-Creations** [comment]
The 4 tiers Hephaestus Forge has?

**Comment by Shadows-of-Fire** [comment]
I have no idea what a Hephaestus Forge is.  I think you might have the wrong repo.

**Comment by SGZ-Creations** [comment]
OOPS i was thinking of the wrong mod My bad Forbidden arcanus has that not you sorry for the confusion
