### ISSUE TITLE
Windows defender detects trojan in latest version

### ISSUE THREAD

**Issue by Tulepeeker** [Shadows-of-Fire/Apotheosis#1198]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/38054549/af324a28-b567-40f0-be40-5b00e278d98c)

**Comment by Shadows-of-Fire** [comment]
That's just defender being false positive. VirusTotal report: https://www.virustotal.com/gui/file/70afbd19adb071a8840b5fc977ca72224e89c1ef4dd1b3680f7b06508dab89ec

Your defender database _might_ be outdated?  Since the VT report even shows Microsoft as reporting it clean.
