### ISSUE TITLE
Falling Anvils Cause Server to Crash

### ISSUE THREAD

**Issue by darkphan** [Shadows-of-Fire/Apotheosis#12]
Causing an anvil to fall crashes servers.

Version: 1.6.0

Crash log: https://pste.me/#/rlzio

**Comment by darkphan** [comment]
This appears to still happen with version 1.6.2

Crash log: https://pste.me/#/Fcz8V

**Comment by Shadows-of-Fire** [comment]
Well, i fixed the other crash only to be hit with another
