### ISSUE TITLE
Showing armor stats twice (somewhat missleading people to think they're getting twice the stats)

### ISSUE THREAD

**Issue by OlaPessoa** [Shadows-of-Fire/Apotheosis#1200]
i don't understand why this happens but... here's a comparison betwheen a item that has been reforged to ancient (therefore with actual extra stats) and a item that has no extra stats yet both are showing these "+armor, +armor toughness and + knockback resistance" [the mentioned helmet in the screenshots are from majrus difficulty, this is still ocurring to vanilla items as well tho]
![2024-03-14_12 21 41](https://github.com/Shadows-of-Fire/Apotheosis/assets/119851799/e9e34b4f-7165-454d-952d-4420249e9095)
![2024-03-14_12 21 43](https://github.com/Shadows-of-Fire/Apotheosis/assets/119851799/dd6235d3-42b0-4b1e-8b7c-79ed2c285469)

**Comment by OlaPessoa** [comment]
it's more of a minor incovenience rather than a bug i think, but still, it is a incovenience lol

**Comment by Shadows-of-Fire** [comment]
You will need to remove or disable whatever mod is showing the green tooltips, as that is not me and they are not using my API to do it.

**Comment by OlaPessoa** [comment]
that's the thing, from some other screenshots i've seen troughtout the gameplay... this is a thing from vanilla
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/119851799/9c6aea2c-d95a-4ed2-a79d-ab7dd51145e0)
so your api is actually the one responsable for this extra thingy , - , as far as i'm concerned it's the only mod that actually messes up with tooltips aside of legendary tooltips in the entire modpack and legendary tooltips do not add these

**Comment by Shadows-of-Fire** [comment]
Vanilla only does this for attack damage and attack speed, not armor - as shown in this screenshot from vanilla 1.20.4
 ![](https://i.imgur.com/tOBfkS4.png)
 
 You have another mod applying this behavior.  You will need to disable it.

**Comment by OlaPessoa** [comment]
welp... there's apotheosis... legendary tooltips... even removed resorcepacks given the fact there are some that change tooltips... and i thought i may have added some texture pack that did that... and still no... WHAT IS CAUSING IT??? there's like no other mod that messes up with tooltips AT ALL

**Comment by OlaPessoa** [comment]
anyway i'll close the thing here, i'm sorry for wasting your time... given i have nothing else that messes with the tooltip at all i thought it would be either legendary tooltips or apotheosis... turns out it ain't both (i guess i will try removing apotheosis yet)

**Comment by OlaPessoa** [comment]
no actually, the problem ain't the green things, they're actually the ones i wanted to stay, the thing is the blue ones that are from your mod showing up when there's no necessity

**Comment by Shadows-of-Fire** [comment]
The green ones are from an external mod which has not been identified.  Apothic Attributes performs a full takeover of the tooltip system to effectively display information, and whatever is adding them is incompatible with AA.

**Comment by muon-rw** [comment]
Possibly Combat Nouveau
