### ISSUE TITLE
Tyrannical Gem weaker than Guardian Gem

### ISSUE THREAD

**Issue by fewfre** [Shadows-of-Fire/Apotheosis#1202]
## Issue
So when used on "Core Armor" the Perfect Tyrannical Gem (which is "unique") gives +6 Armor Toughness, whereas the Perfect Guardian Gem (which is not unique) give +9. It feels weird to me that the unique gem you can only put into a socket once is weaker than then not unique one.

## What I'd expect
I'd expect Tyrannical Gem to either give more armor toughness / be a %, or for the bonus to be something completely different

**Comment by Shadows-of-Fire** [comment]
Ah, no, the bug here is that the guardian gem is actually supposed to give `Armor` and not `Armor Toughness`.  Wonder how long that's been broken.
