### ISSUE TITLE
Heavy Weapons being Heavy Weapon

### ISSUE THREAD

**Issue by Tatsuu22** [Shadows-of-Fire/Apotheosis#1204]
cant get %hp dmg on any axe or something else nothing counts towards heavy weapons. curently playing atm9 if that matters

**Comment by SiverDX** [comment]
Had something like this happen just now as well (on a dedicated server)
re-joining the server fixed the issue and the affixes were shown again

Is your weapon affixed but isn't showing any? If yes did you check the NBT of the item?

**Comment by Shadows-of-Fire** [comment]
Not sure what could cause such an issue.  The selection logic is deterministic.

The only thing I could think of is maybe [this change](https://github.com/Shadows-of-Fire/Apotheosis/commit/cf0e2e82baa0103d420e1f843d76f75c0dc5bfb3), but if relogging fixes it then nothing about this change would be relevant.

I do realize that `ShieldBreakerTest` can leak the level however, so I'll have to address that.

**Comment by SiverDX** [comment]
might just be some weird server sync issue (potentially only if certain mods are present? unsure)

i also had 1 gem not being recognized (it was shown as errored gem)
re-logging fixed that as well (i don't use the passive skill tree mod or apotheotic additions)

another player also had problems (i think some non-heavy-weapon didn't show the affixes)
same fix

**Comment by Shadows-of-Fire** [comment]
The loot category selection is deterministic and unsynced, though if the `adventure.cfg` type overrides become disjoint between sides issues may occur, but that would also not be fixed by a relog.
