### ISSUE TITLE
Feedback on enchanting curses

### ISSUE THREAD

**Issue by Wicked1667** [Shadows-of-Fire/Apotheosis#1205]
I didn't know where else to put this but in issues. 

I would like to give a bit of feedback on the enchanting system. Can you instead add a special type of bookcase or block that when put under the enchanting table removes the chance to get curses or (what I would prefer) added with the bookshelves to lower the chance to get curses and make it stackable enough to say for example 4 curse nullifying bookcases removes chances of getting a curse (25% each). Obviously with this being a fairly powerful/beneficial addition it would be a late/end game type of item that's hard to make. I feel like for such a diverse enchanting system something like this would be a great addition and would make a lot of people happy.

**Comment by Shadows-of-Fire** [comment]
This functionality is addressed by the Seashelf of Aquatic Filtration.
