### ISSUE TITLE
conflict with Balanced Enchanting causing crash on startup [1.19.2]

### ISSUE THREAD

**Issue by MoonMoonShark** [Shadows-of-Fire/Apotheosis#1207]
Minecraft: 1.19.2
Forge: 43.3.0
Apotheosis: Apotheosis-1.19.2-6.5.0
Patchouli: Patchouli-1.19.2-77
Placebo: Placebo-1.19.2-7.4.0
Balanced Enchanting: balancedenchanting-1.18.2-2 (i know the filename says 1.18.2 but it's the 1.19.2 version)

hey there! the latest update to apotheosis is conflicting with balanced enchanting. i've been using them alongside each other in my modpack for months, but with the latest apotheosis update, minecraft crashes during startup. i removed all of the other mods until i tracked down exactly where the conflict was. there is no crash report, but i've included the debug log.

thank you so much for all of your hard work on this! please let me know if there is anything i can do to help with this. i have a private server, if you need a place to test out updates, and i'd be honored to share it with you.

[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/14707049/debug.log)

**Comment by Shadows-of-Fire** [comment]
Apotheosis 6.5.0 was a backport of new features from 1.20.1, one of them was the following:
> * Made all experience costs (enchanting table, anvil, reforging table) use the optimal XP cost (as if you were spending the exact level).
>    * A book entry was added to cover this, and a tooltip was added to the anvil to show the actual XP amount being used.

Thus Balanced Enchanting is no longer necessary when using Apotheosis, since the feature is included natively.

**Comment by MoonMoonShark** [comment]
you are a rockstar! thank you so much! one less mod in the pack without losing functionality is always a win.
