### ISSUE TITLE
Crash upon opening the inventory (1.20.1)

### ISSUE THREAD

**Issue by Voidshelf** [Shadows-of-Fire/Apotheosis#1208]
Greetings,
I happen to have started a server with Apotheosis 7.3.3 for 1.20.1.
Everything went fine for a while, but then, I mysteriously started crashing; at first upon joining the server, which stopped after the first crash. But then, my game crashes every time I try to open my inventory. Here's the crash report:

[crash-2024-03-22_05.08.09-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14717232/crash-2024-03-22_05.08.09-client.txt)

I've tried making sure I had the latest version of both Apotheosis and Placebo, re-install the involved mods, using a different launcher (Curseforge/ATlauncher, this report is from ATlauncher), but nothing I've tried so far works. The problem keeps persisting.

The crash is only clientside, by the way, as the server itself is perfectly fine and doesn't crash or anything when this happens. I'd like to specify just in case, the modpack has Sinytra, but it doesn't seem to be part of the problem.

Thank you in advance for your help

**Comment by Shadows-of-Fire** [comment]
Your main module config `/config/apotheosis/apotheosis.cfg` is mismatched between the client and the server.  This means that potentially other configs are out of sync as well.  You'll need to copy them from the server.

**Comment by Voidshelf** [comment]
I downloaded the entire apoth config folder from the server just to be sure, deleted my own and replaced it.
It worked. Thank you very much for the help :D
