### ISSUE TITLE
Axe Affixes Broken

### ISSUE THREAD

**Issue by AmpedNormal** [Shadows-of-Fire/Apotheosis#1209]
I'm playing on ATM9 modpack. As of version 0.2.52 of the pack, my axes all lost their blue affixes, only the yellow ones at the top of the tooltip remained. All new axes dropped as loot also have no blue affixes.

If I go to reforge an axe, the affixes shown are actually the light weapon affixes rather than the heavy weapon one's, but then when I complete the craft the blue one's are hidden again and the yellow affixes that were shown in the tooltip are different:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/87498102/293ba7e0-d5f9-4233-ac9e-1c2b99bf0324)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/87498102/8e18d443-a535-46c3-a213-2355e6ed4912)

**Comment by AmpedNormal** [comment]
Weirdly, the NBT data still shows heavy affixes, so this seems to be an issue with the tooltip identifying it as a light weapon instead of heavy maybe?
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/87498102/07f25752-a878-48f0-a142-e4bcfc063920)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/87498102/dadc2654-207a-4e07-9a52-860d06033bc5)

**Comment by Shadows-of-Fire** [comment]
A local instance of ATM9 is showing axes properly as heavy weapons.  Can you hold an axe and run `/apoth loot_category`?  This will print out what the game thinks the category is.

**Comment by AmpedNormal** [comment]
So it is recognized as a heavy weapon so the bug seems to be purely visual
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/87498102/391ecf2e-6675-4dc3-b310-606638a344ea)

**Comment by valeredev** [comment]
Hello,
Actually i had an axe that had  % hp damage, but now it shows knockback like it was a light weapons.

![2024-03-23_19 34 30](https://github.com/Shadows-of-Fire/Apotheosis/assets/42415928/056fd9cd-406a-4508-abcb-b2b90b5f5126)

There are some people that say some gems not working anymore on ATM9 last version (2.0.54)

https://www.reddit.com/r/allthemods/comments/1bkpa0m/atm_9_how_to_do_damage/
