### ISSUE TITLE
Altar of the Sea does not function with very high level enchantments

### ISSUE THREAD

**Issue by killslash** [Shadows-of-Fire/Apotheosis#121]
For example, with a maxed out Hell Infusion Hellshelf enchanting table I have level 120 as max enchant.

Four golden swords enchanted @ 120 and the altar of the sea does nothing.

For golden swords four level 60 enchants didn't do anything the one time I tried. Seems like the cap is somewhere around that range.

If the altar is intended to have a cap, perhaps give some visual feedback when the altar is overloaded? Perhaps lightning bolts and the books get thrown out.

**Comment by Shadows-of-Fire** [comment]
It's supposed to play an abnormal sound when it's overloaded, is it not doing that?
Also that cap is there as to not void items when their collective enchanting power sum would yield no enchantments.

**Comment by killslash** [comment]
It's not playing any sound for me, no. The items just sit there.

Perhaps have an option/config to set the enchanting power to the absolute maximum that would yield enchantments if it exceeds it?
