### ISSUE TITLE
(minor) Using reforger causing attribute.modifier.apotheosisplus.1

### ISSUE THREAD

**Issue by Greennyy7504** [Shadows-of-Fire/Apotheosis#1210]
If you reforge an item that doesn't yet have any affix/suffix, yet already has a modifier to your base speed, and it would give speed from the reforging, then instead the speed line is replaced with 

Attribute.modifier.apotheosisplus.1
Attribute.modifier.apotheosisplus.2
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/31377178/5c0e3431-0b3b-4bf4-9251-5dbcef08bb7d)
(For reference, Silent Gear mod  leggings with phantom membrane give  +2% base move speed. That is what seems to have caused this picture. This seems to be the only one that causes this, as other effects such as knock back resistance just stack numerically as normal.)

**Comment by Shadows-of-Fire** [comment]
1.18 is no longer supported
