### ISSUE TITLE
Preview affixes not staying/working on applying reforge

### ISSUE THREAD

**Issue by Xynrati** [Shadows-of-Fire/Apotheosis#1212]
I don't have screenshot proof, but I'll lay out my experiences thusfar.

First off, this has been the same on ATM9 and ATM9 no frills, both running a dedicated server (which seems to be a key point, based on similar questions/reports on the ATM discord).

When attempting to reforge an item, the "to be applied" affixes never fully show up (or function). For example, a pickaxe adding 5x3 mining *never* gets it afterwards, regardless of affix rarity or item tier. This looks similar to the issue with the axes everyone has been reporting, but thusfar I've seen it with swords and pickaxes as well.

I hadn't played in a month or so, and started a fresh brand new server on the current latest version of ATM9/ATM9NF as of this posting. I thought the bug was just in no frills so i swapped back to regular ATM9 only to run into the same issue. Again, it seems to be related to running it as a server, as people who have reported it noted it's on servers and testing locally works fine (I haven't tested locally).

**Comment by Xynrati** [comment]
Went to get screenshots, and now it's behaving as expected... I swear I'm not crazy. I had done a 5x3 that didn't work, but a 3x3 just worked fine...
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/84252507/5e03edb2-6e36-4eef-bf39-22154092ad80)

**Comment by Xynrati** [comment]
Welp, missed the pre-affix screenshot, but I chose this reforge because it came with a 1.25 step height. Lo and behold, it didn't keep it.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/84252507/47d32b6d-af7b-4c8e-91f5-edb8de672a34)
Edit: It also had Speed on hit (I think Speed 2, can't recall) but that's also missing.

**Comment by Shadows-of-Fire** [comment]
I can confirm the reproduction in ATM9 on a dedicated server, but cannot reproduce in isolation.  This probably means there is some mod attempting to interface with apoth and doing so poorly. This will need to be reported to the modpack for further investigation.
