### ISSUE TITLE
Suggestion  add attributeslib:armor_pierce and attributeslib:armor_shred to some mobs

### ISSUE THREAD

**Issue by jpaulo-rb** [Shadows-of-Fire/Apotheosis#1213]
armor toughness is useless against mobs, with the new calc for armor and armor toughness. So, if some mobs had this attribute, it would bring more value to armor toughness

**Comment by Shadows-of-Fire** [comment]
This is staged for 1.21, but not earlier.

**Comment by Shadows-of-Fire** [comment]
Achieved via Tier Modifiers in 8.0.0+
