### ISSUE TITLE
Crash when Gateways summon Affix loot in a dimension with none specified. 

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#1215]
Apotheosis: 1.19.2-6.5.0
Gateways: 1.19.2-3.2.2

More Details: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/911

If a gateway is set to drop Affix loot and it is executed in a dimension where no loot has been configured, it will crash the game. Logs in the link above.

I am pushing a fix to the pack that resolves this for Compact Machines by simply assigning the same loot as another dimension to CMs. However, I'm a bit stuck with Nomadic Tents, which registers a new dimension for each tent. 

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/9543430/c3a879a1-ec25-4619-aab7-8f0ee5e18dda)

It appears I'm unable to specify a blank dimension to apply to any dimension, and I cannot supply the dimension name as it always changes. So I think some error handling would have to be implemented in Apotheosis directly.

**Comment by andr9528** [comment]
Just a suggestion, but maybe Apotheosis should have a default (configurable) tier for affix loot drops in a dimention?
That should prevent a similar crash from happening.

If that list of dimentions is also used to determin if mobs are allowed to drop the loot, then perhabs only dimentions that are explicitely defined should allow drops from mobs, while still having the default in place should something force a drop, like the Gateways.
