### ISSUE TITLE
what the..

### ISSUE THREAD

**Issue by HeyKiezq** [Shadows-of-Fire/Apotheosis#1216]
I calmly played on my build and after I prescribed the command '/kill', I did not die and this continues many times and I cannot die, as well as the screen is shaking violently and I cannot use chests, inventory and much more. If this is a bug, then you can fix it somehow, is it in the logs? I need help. 

![2024-03-26_23-13-13](https://github.com/Shadows-of-Fire/Apotheosis/assets/163204344/384d994e-c443-40f2-9ac1-56afba585ddf)

https://imgur.com/a/RQGXLMy

**Comment by Shadows-of-Fire** [comment]
What makes you think this was caused by Apotheosis?
