### ISSUE TITLE
Reforging not giving the stats showing

### ISSUE THREAD

**Issue by Ombiax** [Shadows-of-Fire/Apotheosis#1218]
I am currently on Version 7.3.3 playing ATM9 on my server with friends and the Reforging Table is showing me stats, but whenever I try putting them on my gear I get something different and not the one I selected. I tried it several times, switching between the 50/100/150 of god pearls or trying one multiple times and it didn't work.

**Comment by Shadows-of-Fire** [comment]
This is caused by the old version of Iron's spells used by the latest ATM9 update.  You can either update it manually or wait for atm to update.
