### ISSUE TITLE
[1.19.2] Changelog is Incorrect

### ISSUE THREAD

**Issue by 2ndkirbyever** [Shadows-of-Fire/Apotheosis#1219]
According to the changelog for version 6.5.0, "Backported all changes from Apotheosis 7.1.0 through Apotheosis 7.3.3."
One change, the pufferfish recipe, is present.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/16438720/3e2c8992-fc02-4546-bec4-eb9e9c1baf3a)

However, the two new shelves, the Seashelf of Aquatic Filtration and the Deepshelf of Arcane Treasures, are not present.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/16438720/e237aa4f-6314-4a0a-b32e-c27a0fac963c)

Were these two shelves supposed to appear, or is it intended that they were not ported?

**Comment by SiverDX** [comment]
aren't those based on chiseled bookshelves

**Comment by Shadows-of-Fire** [comment]
Only the filtering shelf is, the treasure shelf is just a static shelf that flips on treasure enchantments

**Comment by Shadows-of-Fire** [comment]
The pufferfish recipe was added as to make crafting seashelves not so annoying in modpacks that add other fish to the fishing pool (since obtaining one can become virtually impossible when this happens)

**Comment by 2ndkirbyever** [comment]
Interesting. I just looked at the repo, and there is no recipe in the 1.19 branch for the filtering shelf. Also, when I searched JEI for the filtering shelf earlier, it didn't pop up.

**Comment by Shadows-of-Fire** [comment]
Well, no, the filtering shelf cannot be backported as it relies on vanilla code which is not present in 1.19 (the Chiseled Bookshelf).  The other two pieces that you mention are missing (the pufferfish recipe and the treasure shelf) should have been added (but based on @SiverDX's comment they were omitted)

**Comment by 2ndkirbyever** [comment]
Well, the pufferfish recipe was added, hence the first screenshot in the issue, so you don't need to worry about that.
