### ISSUE TITLE
[1.14.4] Pigman crashes the server/game. (Ticking Entity)

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apotheosis#122]
----------------------------

MC-Version: **1.14.4**
Mod-Version: **2.4.4**
Forge-Version: **28.1.107**
Modlist of the [Pack](https://www.curseforge.com/minecraft/modpacks/tnp-limitless) i'm playing: [Github Paste](https://gist.github.com/Gbergz/7252666765f7028165b2cf903440aec7)

Crash-Report: [https://gist.github.com/Gbergz/90a7b80d238596c639f4679013396a98](https://gist.github.com/Gbergz/90a7b80d238596c639f4679013396a98) (Ticking Entity)

----------------------------

**Comment by Shadows-of-Fire** [comment]
does not appear to be an apotheosis issue, nothing from my code is in that trace
