### ISSUE TITLE
Dodge Chance not registered

### ISSUE THREAD

**Issue by ToddyGoat** [Shadows-of-Fire/Apotheosis#1220]
[crash-2024-03-30_17.16.16-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14813369/crash-2024-03-30_17.16.16-client.txt)
Not sure what to say really, an arrow is registering with dodge_chance after shooting a multishot crossbow, and its crashing on world load. I was in the nether with a blue-rarity crossbow (Forgot all the attributes attached)

**Comment by Shadows-of-Fire** [comment]
This is caused by another mod not using forge's attribute registration infrastructure, but given the following:
```
// Hi. I'm Connector, and I'm a crashaholic
=========================
SINYTRA CONNECTOR IS PRESENT!
Please verify issues are not caused by Connector before reporting them to mod authors.
If you're unsure, file a report on Connector's issue tracker found at https://github.com/Sinytra/Connector/issues.
=========================
```
this is due to the existence of a fabric mod.  You'll have to take it up with them.
