### ISSUE TITLE
Unable to put enchantments past vanilla max level on items through an anvil.

### ISSUE THREAD

**Issue by AsianMcRasin** [Shadows-of-Fire/Apotheosis#1221]
Me and my friend are playing on an atm9 server and we cant put a sharpness 9 book on a sword through a anvil.
![Screenshot 2024-03-30 212254](https://github.com/Shadows-of-Fire/Apotheosis/assets/163957418/58ba9ec6-e139-4b24-9999-30e55c7fc655)
![Screenshot 2024-03-30 212353](https://github.com/Shadows-of-Fire/Apotheosis/assets/163957418/7963d18f-d69d-4fa2-9c23-af897fcb812b)

**Comment by Shadows-of-Fire** [comment]
This issue tends to be caused by other mods that fiddle with the anvil. I can fix it if the offending mod can be sourced, but I will not lint an entire modpack to do so.

Please report this issue to the modpack and have them get back to me with more details.

**Comment by XipherGaming** [comment]
Yeah I tend to have this issue with Quark and Apotheosis combo, not sure how to fix it yet lol
