### ISSUE TITLE
Status changes and bonuses removed after enchanting

### ISSUE THREAD

**Issue by EthanHand** [Shadows-of-Fire/Apotheosis#1223]
Apotheosis-1.19.2-6.5.0.jar
In the Enigmatica 9 Expert Mod Pack 
Enigmatica9Expert-1.20.1.zip

I had just re-forged this axe and it had the correct stats but was removed after I enchanted it.
I then re-forged it again and this time it didn't give the stat bonuses indicated but also didn't change the top bonuses.
(The reforge had loot pinata and the finished product doesn't and I am pretty sure it didn't change)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/109968104/9ded08a4-7888-48c3-9c2e-b501df993281)

Appears to still give stats even if it doesn't show when hovering over weapon.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/109968104/307349a9-9bb8-410f-8399-22a3158bed84)

**Comment by trynity121** [comment]
try to remove inventory sorter or remove plugins

**Comment by RoyalReject** [comment]
This is typically seen with a specific version of irons spells try updating it to the latest

**Comment by Shadows-of-Fire** [comment]
Likely related to https://github.com/Shadows-of-Fire/Apotheosis/issues/1234
