### ISSUE TITLE
Server crash when wearing specific equipment and hit by wither skeleton

### ISSUE THREAD

**Issue by MaxQi233** [Shadows-of-Fire/Apotheosis#1225]
Minecraft Version : 1.20.1

Forge Version : 47.2.20

Modpack : All The Mods 9 - 0.2.56

Operating System : Windows 10 22H2

Crash Report : In attachment

World Seed: 7935564070466375662

Description of issue :

When a player wearing the  equipment in the following screenshot  is hit by a withered skull , the server crashes (occurs 100%).

The Wither Skeleton Spawner is in (921, 13, -2494).

Additionally, after simple testing, single player games do not have this issue.

If you need more information, please let me know.

![helmetNBT](https://github.com/Shadows-of-Fire/Apotheosis/assets/59874619/be8504e3-7077-4c2a-b823-bcffce5ad0d8)

[crash-2024-04-06_21.09.35-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14896806/crash-2024-04-06_21.09.35-server.txt)

**Comment by Shadows-of-Fire** [comment]
Not sure what caused this crash but it isn't apoth, nor is it related to the equipment you're wearing.  The issue you're seeing here is concurrent modification of the Entity AI for the wither skeleton in question, which is likely a reaction to the attack.  However, Apoth performs no such modification to entity AI.
