### ISSUE TITLE
1.19.2 bug

### ISSUE THREAD

**Issue by AinSpoh** [Shadows-of-Fire/Apotheosis#1226]
Minecraft Version:1.19.2
Forge Version:43.3.0
Mods:Apotheosis6.5.0,  Tetra:5.6.0,   L2 Complements 1.4.10 (and front mods)
Description of issue :when put apotheosis weapon in tetra workbench,FPS will drop sharply(almost crash)
i asked l2's developer,they said the problem is 1.19.2 apotheosis.(in 1.20.1these mod are running normally)
Hope you can fix this issue as soon as possible
![p1](https://github.com/Shadows-of-Fire/Apotheosis/assets/166686568/09c49ef3-25d5-44b1-bdb1-7e61c0840c1c)

![p2](https://github.com/Shadows-of-Fire/Apotheosis/assets/166686568/32d41f5d-9321-46e3-bd61-0ffa0882013e)

**Comment by Shadows-of-Fire** [comment]
You would need to provide a client render spark profile to triage what is happening.  I suspect the issue does not lie with apotheosis.

**Comment by AinSpoh** [comment]
https://spark.lucko.me/eFXHVd2w1a

**Comment by SiverDX** [comment]
that's server 
you need to provide a client one using /sparkc

**Comment by AinSpoh** [comment]
sorry, this is my first time using Spark
https://spark.lucko.me/uZAWpHBDBz

**Comment by SiverDX** [comment]
in case the report dies
not sure who is at fault here

tetra is constantly checking if the item is broken which leads to this being called:
https://github.com/Minecraft-LightLand/L2Complements/blob/9ecad71d6d93e5e2cf62ee98d6d418ccb58f4bb7/src/main/java/dev/xkmc/l2complements/mixin/ItemStackMixin.java#L51

which leads to the whole enchantment (and therefor gem) stuff being checked

which leads to tool actions being checked which are not very performant for tetra items

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/86e380ab-326c-450a-abd7-543131826d9e)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/c05112e6-98c2-44c6-846f-a9c74d089a77)

**Comment by AinSpoh** [comment]
Okay, thank you for answering my question
