### ISSUE TITLE
randomly ticking mob problem with lootbeams.

### ISSUE THREAD

**Issue by KaziiTheAvali** [Shadows-of-Fire/Apotheosis#1228]
There seems to be a mod incompatibility with lootbeams. 
it seems that some part of lootbeams try to call java.lang.NoSuchMethodError: 'dev.shadowsoffire.placebo.reload.TypeKeyed dev.shadowsoffire.placebo.reload.DynamicHolder.get()' if you wish for me to go put this in placebo or lootbeams feel free to tell me.

files
[crash-2024-04-14_07.10.59-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/14970751/crash-2024-04-14_07.10.59-server.txt) 
logs: https://mclo.gs/J7gGRFN.

**Comment by Shadows-of-Fire** [comment]
Looks like loot beams is compiled against an older version of Placebo - they'll need to rebuild against latest.
