### ISSUE TITLE
Limited Enchantability on books

### ISSUE THREAD

**Issue by abby-cadabra** [Shadows-of-Fire/Apotheosis#1230]
Hi there,

Having a weird bug (?) on Forge 1.20.1. About half the time when I go to enchant a Book, it will return "Limited Enchantability" or else be completely blank.

![2024-04-17_11 41 44](https://github.com/Shadows-of-Fire/Apotheosis/assets/132413818/28b6896f-fb3b-42c9-bb73-2aba9a3b7a28)
![2024-04-17_11 41 59](https://github.com/Shadows-of-Fire/Apotheosis/assets/132413818/5fe9395a-114b-43bc-8588-18e530afd5eb)

When I look at the latest.log, I do see something happening around the time of the bug:

[11:42:09] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket@1a75d869, suppressing error
java.lang.NullPointerException: Cannot invoke "chronosacaria.mcdw.bases.McdwDagger.m_7968_()" because the return value of "chronosacaria.mcdw.enums.DaggersID.getItem()" is null

Wondering if this might point to an incompatibility with MC Dungeons Weapons? Otherwise I have no clue.

**Comment by Shadows-of-Fire** [comment]
From what I can tell something is modifying the enchantment table, since the Enchanting Info popup (the `?` button on the top-left of the menu) is absent.  What version of the mod are you using?

**Comment by abby-cadabra** [comment]
I seem to have fixed this one through advice from MCDW devs! The latest MCDW seems to break things unless you delete the configs. Regenerating the MCDW configs fixes this issue.

Hopefully this will be helpful for anyone else who runs into the same problem.
