### ISSUE TITLE
Crash when opening inventory & chest

### ISSUE THREAD

**Issue by cal1407** [Shadows-of-Fire/Apotheosis#1231]
Pretty straightforward. The game would crash when I tried opening the inventory or any storage (i.e. chests), with the logs mentioning this mod here.

Crash Report: 
[crash-2024-04-17_20.47.34-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/15008618/crash-2024-04-17_20.47.34-server.txt)

Log: 
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/15008612/latest.log)

**Comment by Shadows-of-Fire** [comment]
The linked crash is coming out of the vanilla worldgen function `StructurePiece#reorient`, which is responsible for aligning chests to be facing away from the nearest wall.  It is not capable of selecting the `UP` direction as your crash report would imply, so I'm pretty sure this is the fault of some other mod's mixin.  Unfortunately there isn't much I can do about it, this is the same code that vanilla uses for dungeon placement.
