### ISSUE TITLE
Create interaction issue

### ISSUE THREAD

**Issue by DerRoboMeister** [Shadows-of-Fire/Apotheosis#1232]
Whenever an affixed backtank of any kind from Create is placed on the ground, it immediately loses all affixes and gem sockets. Not sure if this issue exists on either Create's end or Apotheosis' end.

I'm running this on Minecraft 1.20.1 on NeoForge 47.1.104, with Apotheosis on version 7.3.4 and Create on 1.20.1-0.5.1f.

**Comment by Shadows-of-Fire** [comment]
Nothing much can be done about this from my end, this will happen with any sort of data that is stored on the `ItemStack` when placed into block form.  Create would need to retain the original `ItemStack` and restore it when the tank block is broken to retain the additional data.
