### ISSUE TITLE
Trident with Piercing and Loyalty crashes when using Embeddium

### ISSUE THREAD

**Issue by RoyalReject** [Shadows-of-Fire/Apotheosis#1233]
Someone brought this up in the discord and after some testing was able to reproduce with just apotheosis and dependencies with Embeddium.

When a trident has both piercing and loyalty enchantments and used on a mob, it can cause the game to freeze and exit without a crash report and the log was not helpful. They found it mainly occurred when attacking an enderman with the trident. 

Creating an issue here as apotheosis had a mixin to allow piercing on the trident.
Curseforge profile export:
[Trident crash with Embeddium.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/15081969/Trident.crash.with.Embeddium.zip)

**Comment by RedAngel121** [comment]
Its not Embeddium, the issue persists without it.
