### ISSUE TITLE
[BUG] The affix of heavy_weapon is not show when you enter the server

### ISSUE THREAD

**Issue by Kiuju79** [Shadows-of-Fire/Apotheosis#1234]
Minecraft 1.19.2
Forge-1.19.2-1.0.6
Apotheosis-1.19.2-6.5.0
Placebo-1.19.2-7.4.0

TestServer: Arclight

The affix of heavy_weapon is not show when you enter the server,
And the reforging_table, AXE will show the affix of sword instead of heavy_weapon
![1](https://github.com/Shadows-of-Fire/Apotheosis/assets/122474664/0c49c23e-5fb2-45aa-bb04-7fc67e33c891)

Enter single player mode, Reentry server, Return to normal.
but, the problem will be repeated after restarting the game.

(Sorry, my English is not very good)

**Comment by Kiuju79** [comment]
Not only affix but also gem is affected by this.

**Comment by Shadows-of-Fire** [comment]
Seems like https://github.com/Shadows-of-Fire/Apotheosis/commit/39467d5b96279a5a797e294802a689c048f637b0 (and the follow-up commits) need to be backported to 1.19
