### ISSUE TITLE
Reforging affixe isn't the final affixe

### ISSUE THREAD

**Issue by Keynoost** [Shadows-of-Fire/Apotheosis#1235]
(Sorry for my medium English). I saw a lot of post talking about this issue where the pre reforge affixe isn't the affixe on the item after reforging but not on the server I'm using so I re opened a post. So this problem only happen on Aternos server and not in solo. So do you have any idea of what trigger this problem? I'm not very familiar with logs and all so maybe it's really easy to repair ..

**Comment by RoyalReject** [comment]
Typically we have seen this with an outdated version of Iron's spells or when using apothic additions

**Comment by Keynoost** [comment]
I do use apothic additions but it still work on solo and not on Aternos server

**Comment by Shadows-of-Fire** [comment]
This appears to be an additions issue, Apoth on its own does not produce desynced results for reforging, even on dedicated servers.
