### ISSUE TITLE
Crash while loading mod(1.20.1)

### ISSUE THREAD

**Issue by assomed00011** [Shadows-of-Fire/Apotheosis#1236]
It's strange that it didn't provide me with a crash report, so I can only export the crash log from the console log (not the crash report)

I ensure that Apotheosis mod is the latest version (7.3.4), Placebo mod is the latest version (8.6.1), and Apotheosis pre mod is the latest version (1.3.4),Perhaps there is a serious conflict between it and a certain mod, and I am currently unable to locate it

Here is the log:
[latest.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/15206607/latest.txt)

Furthermore, it is amazing that in 1.19.2, if Apotheosis mods above 6.4.1 (excluding 6.4.1) were used, the final result would be the same as in 1.20.1

**Comment by RoyalReject** [comment]
You have a conflict anvil mod. Remove AnvilNeverTooExpensive. Also 1.20.1 apotheosis is built on neoforge that only guarantees compatability with forge 47.1.3 IIRC.
