### ISSUE TITLE
[BUG] potion 'sundering' is not valid in the server

### ISSUE THREAD

**Issue by Kiuju79** [Shadows-of-Fire/Apotheosis#1237]
Minecraft 1.19.2
Forge-1.19.2-43.3.13
Apotheosis-1.19.2-6.5.0
Placebo-1.19.2-7.4.0

TestServer: Arclight

Normal in single player,
However, it does not take effect on the server.

**Comment by Shadows-of-Fire** [comment]
Probably a conflict with Arclight, not something I can fix from my end.
