### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by gjmhmm8** [Shadows-of-Fire/Apotheosis#1238]
[apotheosis.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/15213714/apotheosis.zip)
[crash-2024-05-06_00.30.37-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/15213715/crash-2024-05-06_00.30.37-client.txt)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/15213716/latest.log)

**Comment by Shadows-of-Fire** [comment]
Disabling the adventure module requires using NeoForge or upgrading MinecraftForge to `47.2.5` or above.
