### ISSUE TITLE
Issue on connection to Multiplayer server after a server restart

### ISSUE THREAD

**Issue by ACrazyD** [Shadows-of-Fire/Apotheosis#1239]
Im not 1000% sold that its your mod, but i did catch an error on attempting to connect to a multiplayer server

Heres the error and related info
 - [Error](https://paste.mcstellarum.com/dunonariqo.md)
 - Mod Version: 1.20.1-7.3.5
 - MC Version: 1.20.1 Forge
 - Forge Version: 47.2.30
 
 Not sold the issues im running into are yours, just saw the error and it may help with something else idk

**Comment by Shadows-of-Fire** [comment]
This isn't actually an error (just a caught exception printed to the log message), but it doesn't really need to be printed, so I can shut it up.
