### ISSUE TITLE
1.20.1, bug, compatibility of mods

### ISSUE THREAD

**Issue by vlad0-0** [Shadows-of-Fire/Apotheosis#1240]
It is not possible to open the upgrade menu for some weapons (swords and bows) in the tetra mod with this installed mod (Apotheosis)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/54848408/c75be7bb-1955-411c-8eab-f7436720f0a9)
To reproduce this bug, you can click on any part of the weapon and it will not open its menu

**Comment by Shadows-of-Fire** [comment]
Per policy, I do not provide support for closed-source mods.
