### ISSUE TITLE
Conflict with Palladium 1.20.1

### ISSUE THREAD

**Issue by snixton** [Shadows-of-Fire/Apotheosis#1241]
There is a conflict with the mod Palladium where gems and vails can't be placed into smithing table but sigils are able to.

To replicate the problem, install Palladium and run it together with Apotheosis

**Comment by Shadows-of-Fire** [comment]
Not sure what fiddling they are doing to the smithing table.  Since they're the only mod in existence that is breaking it, I'm going to say they should fix it.  It looks like there's already a bug open for it over there. https://github.com/ThreeTAG/Palladium/issues/115
