### ISSUE TITLE
Gems dropped from Item Frames return item.apotheosis.gem 1.20.1

### ISSUE THREAD

**Issue by LunarHackett003** [Shadows-of-Fire/Apotheosis#1242]
Gems obtained from the towers in Apotheosis, regardless of the name when looking at them in the item frames on the walls, always drop a non-functional gem

**Comment by LunarHackett003** [comment]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/61294652/15b8044a-bedf-474e-b1fd-bd7398ede62e)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/61294652/ea1ed3b5-286e-4420-9c56-5730f66899fd)
images attached  - the gem still appears to be the correct gem when its on the ground, but changes once its picked up

**Comment by LunarHackett003** [comment]
Update: its *every* gem that's picked up that is broken

**Comment by Shadows-of-Fire** [comment]
This seems like another mod in your instance is breaking item NBT data.  Gems are working fine in isolation, other instances and in other large modpacks

**Comment by Shadows-of-Fire** [comment]
`Mo' Enchantments` was identified to be causing this kind of NBT loss.
