### ISSUE TITLE
Missing crafting recipes 1.20.1

### ISSUE THREAD

**Issue by Sylvestre289** [Shadows-of-Fire/Apotheosis#1243]
I play apotheosis in a modpack I made on 1.20.1 and nearly all the shelves has no crafting recipes, especially hellshelves or seashelves which makes me unable to go further in the mod

My mod version is currently: Apotheosis-1.20.1-7.3.5.jar

I don't know id the recipes are supposed to be shown in the book as well, but if so they aren't

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/89229239/e35b5a2f-36f8-4ebd-a041-4c3e39c24d30)

**Comment by Shadows-of-Fire** [comment]
Modpacks may change or adjust recipes.  I suggest you consult with them to figure out what the recipes are, or view the items in JEI.

**Comment by meeprdib** [comment]
The mod "palladium" has also been reported to break recipes, check if you have it installed and remove it
