### ISSUE TITLE
Crash upon pressing new world

### ISSUE THREAD

**Issue by CuchilloMucho** [Shadows-of-Fire/Apotheosis#1245]
I attempted to add Apotheosis to a modpack and I only want the enchanting module but when I disable the adventure module I can no longer make worlds
[crash-2024-05-14_20.18.30-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/15307295/crash-2024-05-14_20.18.30-client.txt)

**Comment by Shadows-of-Fire** [comment]
Disabling thr adventure module requires using NeoForge or a very recent version of MinecraftForge.
