### ISSUE TITLE
How do I disable towers? 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Shadows-of-Fire/Apotheosis#1246]
How do I disable towers? 🙏🙏🙏

**Comment by meeprdib** [comment]
There's a datapack that does this in Shadow's discord
https://discord.com/invite/shadows-mods-613010559532531713

**Comment by FilipKompaniets3** [comment]
> Є пакет даних, який робить це в Shadow's Discord https://discord.com/invite/shadows-mods-613010559532531713

Where exactly should I look for it?

**Comment by FilipKompaniets3** [comment]
I already found it. thank you

**Comment by meeprdib** [comment]
try this
https://discord.com/channels/613010559532531713/1152354830828970084/1205544169074987038
