### ISSUE TITLE
[Feature Request] Add an item/way to remove affixes

### ISSUE THREAD

**Issue by ArcTrooper210** [Shadows-of-Fire/Apotheosis#1247]
Sorry if this has been requested before but I didn't find anything while searching through the issues page. Could you add a way to remove all affixes from an item. i.e returning an item to it's freshly crafted state.

**Comment by Shadows-of-Fire** [comment]
Similar question to #948 - what is the use case for this functionality?

**Comment by Shadows-of-Fire** [comment]
Closing due to lack of response.
