### ISSUE TITLE
Maxed enchanting table capping at 39 all of a sudden

### ISSUE THREAD

**Issue by Secrets17x** [Shadows-of-Fire/Apotheosis#1251]
I've had my table maxed out on everything for a while. Quanta, Arcana, Eterna, and Rectification. It's been 100 for the 3rd option the whole time. Now, all of a sudden, my enchants are capping out at level 39 xp. Not sure what to do about it.

**Comment by Shadows-of-Fire** [comment]
I suspect you have some block preventing the line-of-sight rules from the table to the bookshelves.  It could potentially be an invisible meta-block from another mod, making it hard to debug.  There's not a ton I can do about this without knowing the exact setup.

**Comment by Secrets17x** [comment]
Well, I even picked up the enchanting table and moved it elsewhere and the
39 remained the same. It's 15 pearlescents, 1 draconic, 4 rectifications,
and 3 masterful sights. No matter where I place it, it stays 39. Everything
on it is maxed out. Quanta, Eterna, Arcana, etc.
