### ISSUE TITLE
Apotheosis boss drops crash game, seemingly from incompatibility when the Lootbeams mod attempts to pull their rarity

### ISSUE THREAD

**Issue by dia-b0lical** [Shadows-of-Fire/Apotheosis#1252]
log -> [latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/15396944/latest.log)

**Comment by Shadows-of-Fire** [comment]
This just means LootBeams needs to update to be compatible with the latest version of Apoth (which they may have done already).
