### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by The-Quaint-One** [Shadows-of-Fire/Apotheosis#1254]
If you put any gem on any tool, then use multiple vials of extraction in the table, and Shift Click to quick move the removed gem into your inventory. The gem is duplicated in a 1-1 ratio of how many vials you put in the table. Apologies about the video being a Zip File. 10mb video limit.
[Base Profile 2024.05.25 - 04.56.19.02.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/15443318/Base.Profile.2024.05.25.-.04.56.19.02.zip)

**Comment by Shadows-of-Fire** [comment]
what version of Apotheosis are you using

**Comment by The-Quaint-One** [comment]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/170804999/081a60d0-ffd1-4606-a960-5903d677289b)

**Comment by The-Quaint-One** [comment]
Heres the version of Apotheosis in Ciscos.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/170804999/6a8991e0-2de9-49dc-bd46-7ad5bfaaa97a)
