### ISSUE TITLE
Creating a torch through a fire 

### ISSUE THREAD

**Issue by FilipKompaniets3** [Shadows-of-Fire/Apotheosis#1255]
How can I disable torch creation via bonfire? I could find this in the configuration myself, but I don’t know English and it’s difficult for me to do this.

**Comment by RoyalReject** [comment]
You would need to create a datapack to remove this recipe https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/recipes/torch.json or you could use something like kubejs or craft tweaker that also had the ability to remove recipes.

**Comment by FilipKompaniets3** [comment]
Could you briefly explain how to create this data package? I don't know how to use hithub(

**Comment by Shadows-of-Fire** [comment]
Resources on how to create and use datapacks are out-of-scope for this issue tracker, there are plenty of examples on the internet.
