### ISSUE TITLE
[Feature Request] Enchantment Library Level Config

### ISSUE THREAD

**Issue by dieflemm** [Shadows-of-Fire/Apotheosis#1258]
It might be useful for some modpack authors to be able to configure the maximum output level of the Enchantment Library.
Theres is no reason to upgrade the library if you have no enchantments above level 16.

**Comment by Shadows-of-Fire** [comment]
The enchantment library max storage level is bound by the physical limitations of the storage medium (16-bit shorts vs 32-bit integers).  The 32-bit version is mostly fluff, it doesn't serve a real purpose in a sensible modpack, nor do I want to incentivize it being something people feel obligated to create.
