### ISSUE TITLE
[1.15.x] Sugar cane, cactus and bamboo not transparent

### ISSUE THREAD

**Issue by JayJay1989** [Shadows-of-Fire/Apotheosis#126]
**Describe the bug**
Sugar cane, cactus and bamboo not transparent. and not rendering correctly

**To Reproduce**

**Logs/crashlogs/etc**
--

**Expected behavior**
--

**Screenshots**
[cactus](http://prntscr.com/qpl09m)
[sugar cane](http://prntscr.com/qpl0hr)
[bamboo](http://prntscr.com/qpl0sq)

**Minecraft enviroment (please complete the following information):**
 - OS: Server: linux / Desktop:  Windows
 - Ram allocated [e.g. 8G] Server: 8G / Desktop: 8G
 - Minecraft & Forge version [e.g. 1.12.2 - 14.23.5.2772] 1.15.1-30.0.41
 - Mod Version [e.g. 1.12.6] 3.0.2
 - Mod List: [Mod List](https://pastebin.com/zpP3SLBy)

**Additional context**
--

**Comment by Shadows-of-Fire** [comment]
This is a forge bug, there is a PR pending to fix it: https://github.com/MinecraftForge/MinecraftForge/pull/6452
