### ISSUE TITLE
Loot Rules

### ISSUE THREAD

**Issue by LilithASMP** [Shadows-of-Fire/Apotheosis#1261]
[16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:rare for category curios:spellbookRequired: 2; Provided: 0
--
2063 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:epic for category curios:spellbookRequired: 2; Provided: 0
2064 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category helmetRequired: 3; Provided: 2
2065 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category bootsRequired: 3; Provided: 2
2066 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:mythic for category curios:spellbookRequired: 3; Provided: 0
2067 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bowRequired: 5; Provided: 4
2068 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category crossbowRequired: 5; Provided: 4
2069 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category pickaxeRequired: 5; Provided: 4
2070 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category shovelRequired: 5; Provided: 4
2071 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category helmetRequired: 4; Provided: 2
2072 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category bootsRequired: 4; Provided: 2
2073 | [16:29:29] [main/ERROR] [Apotheosis : Adventure]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheosis:ancient for category curios:spellbookRequired: 4; Provided: 0

**Comment by LilithASMP** [comment]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/170349783/07f4720b-79c9-43ec-bb1e-a4f682a9cc5c)
everytime a player connect i have these problems, i also have multiples gems who doesn't work but appear in the JEI

**Comment by Shadows-of-Fire** [comment]
These are warnings emitted when certain conditions are not met to make the rarities valid.  Given those messages are talking about ancient rarity (which is not implemented), this is the fault of another mod attempting to provide it.  There are a couple known warnings that happen for mythics, tracked by #1051
