### ISSUE TITLE
[1.20.1] Default Step Height at 0 and unable to be changed

### ISSUE THREAD

**Issue by HockeyZman2000** [Shadows-of-Fire/Apotheosis#1262]
I'm not sure if this is an Apotheosis problem or a Forge problem but currently when starting a new world according to Apothic Attributes my step height stat is 0 when default behavior in vanilla should be 0.5 if I'm not mistaken. I'm currently unable to walk up stairs, slabs, or even snow layers and carpets. The only way around this is getting affixed boots to increase my step height back above 0.5 in order to get back to vanilla behavior. I believe that without affixes you should still be able to walk up these blocks unless I'm missing something here?

I also tried manually setting my step height in-game using the /attribute command to return myself to 0.5 but the command appeared not to actually change anything. Thanks in advance for any help you can provide.

Forge 47.3.1
Apotheosis 7.3.5
Apothic Attributes 1.3.5

**Comment by Shadows-of-Fire** [comment]
If the `/attribute` command is unable to change it, then you have another mod forcing the value to zero.  That's out of my control, and you'll have to isolate whatever it is in your modpack instance and remove it.

**Comment by HockeyZman2000** [comment]
Thank you. I found the culprit mod and will be taking it up with them.
