### ISSUE TITLE
Crash at the start of the loading of a world [1.18.2] [custom modpack]

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#1265]
I am creating somewhat of a kitchen sink with just mashing things together. Minecraft opens fine, but when creating and loading a world (during the world creation progress, i guess) during 3-4% mark, the game crashes with "Description: Feature placement"

java.lang.IllegalArgumentException: Cannot set property null as it does not exist in Block{minecraft:vine}

I put the crash file here:
[crash-2024-06-12_18.11.10-server.txt](https://github.com/user-attachments/files/15807502/crash-2024-06-12_18.11.10-server.txt)

apotheosis is fine by itself, but i couldn't find the culprit mod that does the vine thing even with the google gemini AI. installed mods should be in the crash file.

**Comment by Shadows-of-Fire** [comment]
1.18 is no longer supported.  If you can't identify the cause of this problem, you could try disabling placement of rogue spawners.

**Comment by ghost** [comment]
yes, after looking into it more, a different mod causes similar feature placement problems. I am not sure which mod does at the moment. opened a reddit post about it and currently trying to understand the problem. my primary suspect is yungs better mineshaft, but i am not sure about that. because the crash report sometimes blame apotheosis, sometimes waystones, sometimes other mods. the crash also happens without any optimization mods either.

**Comment by ghost** [comment]
a person on reddit found the issue, a mod called "redirector" did it. appearently it is a mod about changing enum values and other constants to optimize the game.

Edit: I have now opened another issue on redirector mod's issue tracker.
