### ISSUE TITLE
Environmental Controller with peace module doesn't stop bosses from spawning

### ISSUE THREAD

**Issue by ShadwDrgn** [Shadows-of-Fire/Apotheosis#1266]
Not sure how they prioritize their event hook but hopefully this can somehow be fixed. Maybe I need to file the bug with them instead? Let me know.

The code in rftools that should handle this seem to be here. It's definitely working on normal world spawns, and as long as you're creating that boss arrival event using w/e would trigger this hook it SHOULD work i imagine :(.

https://github.com/McJtyMods/RFTools/blob/030a495c8530183bdfe47475ed41d45386e56f6c/src/main/java/mcjty/rftools/ForgeEventHandlers.java#L228

**Comment by Shadows-of-Fire** [comment]
The linked code looks like its for a very very old version of MC (~1.12).  I'm not sure where the equivalent code for modern versions is.  It would appear to be https://github.com/McJtyMods/RFToolsUtility/blob/1.20/src/main/java/mcjty/rftoolsutility/setup/ForgeEventHandlers.java#L245 but this doesn't look like it gets called anywhere.

**Comment by Shadows-of-Fire** [comment]
I don't believe there are any changes I can make to assist in this process.  Apoth listens to the `FinalizeSpawn` event for triggering these spawns, which should be cancelled by the controlled.
