### ISSUE TITLE
Rogue Spawner chance - Please make it a config option

### ISSUE THREAD

**Issue by kragnoth** [Shadows-of-Fire/Apotheosis#1267]
Please change it so that the if(rand()%100==0) check is dependant on a variable that can be configured in the adventure config file.  I've not seen a rogue spawner since I think version 7.2.2 (when I believe this change was made)

**Comment by RoyalReject** [comment]
All world gen can be configurable via datapack. This is a change mojang has made and modders had to adapt. I am not sure where you got your example from to see what it is doing. But yeah datapack is how you would modify the chances now.

**Comment by Shadows-of-Fire** [comment]
The rogue spawner specifically does have a hardcoded 1/100 success chance in the feature code, though it can be kinda counteracted by increasing the `count` in the placed feature.

I could probably move the definition of the `100` to the feature config instead of it being hardcoded.

**Comment by kragnoth** [comment]
thanks shadows-of-fire, I'll check the datapack side for now until that's a feature config.

**Comment by kragnoth** [comment]
> All world gen can be configurable via datapack. This is a change mojang has made and modders had to adapt. I am not sure where you got your example from to see what it is doing. But yeah datapack is how you would modify the chances now.

I looked at the source code while trying to figure out if I broke something.

**Comment by kragnoth** [comment]
just tested with a count of 256, and ... well out of a gigantic cave system I had at least one spawner.  So maybe if you could add a config option that would be great, because 256 is the hard cap on placed feature
