### ISSUE TITLE
Royalty Gems appear as item.apotheosis.item

### ISSUE THREAD

**Issue by colin094** [Shadows-of-Fire/Apotheosis#1268]
All royalty gems that spawn in the world, dropped by mobs, and spawned in with commands appear as item.apotheosis.item gems with errored stats. It also does not appear in jei and the creative menu. When the /placebo hand command is ran, it shows the correct nbt data of the royalty gem.
![IMG_6244](https://github.com/Shadows-of-Fire/Apotheosis/assets/143117405/8699b099-1bda-4b12-bca4-2c8a930192e2)

**Comment by Shadows-of-Fire** [comment]
If the correctly-encoded gem appears as an error, the gem was removed by the modpack (or invalidated).  The gem works correctly under the default settings.  I'm not really sure how these gems could be generating if they were unloaded (though they could have been generated beforehand).
