### ISSUE TITLE
[1.18.2]Bug caused by spectral affix resulting in StackOverflowError and crash.

### ISSUE THREAD

**Issue by Windrinn** [Shadows-of-Fire/Apotheosis#1269]
[crash.zip](https://github.com/user-attachments/files/15858882/crash.zip)

**Comment by SettingDust** [comment]
Apotheosis is avoiding that with https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/AdventureEvents.java#L129

But I can't find where is the flag assign to the entity.

**Comment by SettingDust** [comment]
I guess the flag need to mark as true at https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/affix/effect/SpectralShotAffix.java#L58

Looks like noop in 1.20+ as well

**Comment by Shadows-of-Fire** [comment]
1.18 is no longer supported, though it does (from code analysis) appear to be a problem in 1.20

However, for some reason, it doesn't actually _occur_ in 1.20, despite the flag not being set.

**Comment by Shadows-of-Fire** [comment]
Ah, actually, that's probably why.  It just fizzles out, unless the random chance approaches 100%, and then it recurs infinitely.  I guess technically it could infinitely recur at any chance, but it would be unlikely.

**Comment by SettingDust** [comment]
For anyone need the fix on 1.18.2. https://legacy.curseforge.com/minecraft/mc-mods/mod-compat-fixes/files/5436687 fixed
