### ISSUE TITLE
Reforging table giving a different reforge than expected [1.20.1]

### ISSUE THREAD

**Issue by MrBenoit** [Shadows-of-Fire/Apotheosis#1270]
![2024-06-17_22 16 32](https://github.com/Shadows-of-Fire/Apotheosis/assets/111755919/c4e4a9a2-8bf2-4a73-8cc6-e128bc817f55)
![2024-06-17_22 16 40](https://github.com/Shadows-of-Fire/Apotheosis/assets/111755919/5bbfe17a-f1c1-43b2-aa96-e5fab4b27707)

**Comment by meeprdib** [comment]
The mod Apothetic Additions is known to cause this issue, do you have that installed?

**Comment by MrBenoit** [comment]
not installed

**Comment by meeprdib** [comment]
Huh, could you send a modlist then?

**Comment by MrBenoit** [comment]
ohh.. installed. but i dont wanna delete this mod. can i use any interpreter?

**Comment by meeprdib** [comment]
You can make your own mod compatibilities with a datapack, apoth additions is not required for that

**Comment by MrBenoit** [comment]
what Apothetic Additions do?

**Comment by meeprdib** [comment]
Additions adds apotheosis compatibility for other mods by making some modded mobs spawn as bosses, enabling their loot to spawn with affixes, and making affixes, among other things. It also messes with the reforging table for some reason.

**Comment by MrBenoit** [comment]
hmmmm.. ok. i need try

**Comment by MrBenoit** [comment]
ok. Can i use this mod without this bug?

**Comment by MrBenoit** [comment]
i fix it))))

**Comment by MrBenoit** [comment]
this bug work only in multiplayer (hamachi or Radmin) 
any player enchant thing - bug
host enchantthing - work)
