### ISSUE TITLE
Extraction vial

### ISSUE THREAD

**Issue by death587** [Shadows-of-Fire/Apotheosis#1271]
the extraction vial is not working again I'm playing with 7.3.5
![image_2024-06-19_193056208](https://github.com/Shadows-of-Fire/Apotheosis/assets/37222445/14b5da66-bbe4-4466-ba6a-e1e980e85c7b)
![Screenshot (132)](https://github.com/Shadows-of-Fire/Apotheosis/assets/37222445/9093acd4-4d87-44df-a342-47e6c4374a17)

**Comment by Shadows-of-Fire** [comment]
Is Palladium installed?  It completely bricks the smithing table

**Comment by death587** [comment]
It is not I'm playing atm9 to the sky

**Comment by Shadows-of-Fire** [comment]
The two gem vials have been replaced with the Sigil of Withdrawal in 7.4.0, which resolves this problem.
