### ISSUE TITLE
[1.20.1] Can't socket gems into items

### ISSUE THREAD

**Issue by luluhcifer** [Shadows-of-Fire/Apotheosis#1273]
As the title says, I can't put gems into my items because the smithing table doesn't accept gems. I don't know what I can do about it, please help! (The items have empty sockets)

ModList:
KumaAPI                       
FTB Essentials                
Tempad With Shaders           
GeckoLib 4                    
Player Animator               
PalladiumCore                 
Heroes                        
Sophisticated Core            
Palladium                     
Placebo                       
ModernFix                     
Citadel                       
Alex's Mobs                   
YUNG's API                    
MixinExtras                   
Bookshelf                     
Sophisticated Backpacks       
Create: Dragon Lib            
Apotheosis                    
Balm                          
YUNG's Better Nether Fortresse
Cloth Config v10 API          
MmmMmmMmmmmm                  
Supplementaries               
Mob Grinding Utils            
Embeddium                     
Farmer's Delight              
Tempad                        
AmbientSounds                 
PantheonSent                  
Epic Knights : Japanese Armory
Colorful Hearts               
Resourcefulconfig             
LionfishAPI                   
Cataclysm Mod                 
Curios API                    
Patchouli                     
Oculus                        
Xaero's Minimap               
SimpleHats                    
Apothic Attributes            
Better Third Person           
FTB Ultimine                  
Resourceful Lib               
WorldEdit                     
Construction Wand             
Architectury                  
YUNG's Better Mineshafts      
Rhino                         
FTB Library                   
FTB Teams                     
Amendments                    
Just Enough Items             
KubeJS                        
AttributeFix                  
Pehkui                        
Waystones                     
Clumps                        
Artifacts                     
Epic Knights Mod              
Ars Nouveau                   
What Are They Up To           
MythicMounts                  
FTB Chunks                    
Forge                         
Iron Chests                   
Infernal Mobs                 
Minecraft                     
Simple Voice Chat             
Sound Physics Remastered      
Create: Steam 'n' Rails       
Simply Swords                 
EnchantmentDescriptions       
Moonlight Library             
Mouse Tweaks                  
Better Combat                 
Night Lights                  
MixinSquared                  
Jade                          
CreativeCore                  
Flywheel                      
Create                        
Create: Central Kitchen       
Ars Creo                      
Storage Drawers               
EntityCulling                 
Sherds API                    
CoroUtil                      
AppleSkin                     
Alex's Delight                
Lootr                         
Ferrite Core                  
Packet Fixer                  
CosmeticArmorReworked         
ExpandAbility                 
Create Enchantment Industry   
Create Crafts & Additions     

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/109778015/c5e906a1-1021-4ae2-a44a-cc7dba815a6b)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/109778015/53ba678d-5d20-4957-add0-82f881f6413d)

**Comment by Shadows-of-Fire** [comment]
Palladium bricks the smithing table.  You'll have to remove it.
