### ISSUE TITLE
[1.20.1] Crash in the Reforging Table

### ISSUE THREAD

**Issue by BazZziliuS** [Shadows-of-Fire/Apotheosis#1274]
If you put a mjolnir from the MysticBotany mod in the Reforging Table and visit the enchantment selection, it causes a crash

Crash-log: https://paste.fuix.net/bXMqKwo
Suspected Mods: MythicBotany-1.20.1-4.0.3, Minecraft (minecraft), Placebo (placebo), Apotheosis-1.20.1-7.3.5

**Comment by Shadows-of-Fire** [comment]
Please provide the full game's debug.log file.  MythicBotany provides an IMC override for Mjolnir which means it should never enter this infinite loop: https://github.com/noeppi-noeppi/MythicBotany/blob/master/src/main/java/mythicbotany/MythicBotany.java#L192

The game log will contain a line if this is actually being received or not.

**Comment by BazZziliuS** [comment]
> Please provide the full game's debug.log file. MythicBotany provides an IMC override for Mjolnir which means it should never enter this infinite loop: https://github.com/noeppi-noeppi/MythicBotany/blob/master/src/main/java/mythicbotany/MythicBotany.java#L192
> 
> The game log will contain a line if this is actually being received or not.

debug.log: https://paste.fuix.net/iyVqeBk

**Comment by Shadows-of-Fire** [comment]
I see the log message from the successful IMC message
>  [26Jun2024 14:26:54.322] [Worker-Main-15/DEBUG] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Transforming renderHUDBox with desc (Lnet/minecraft/client/gui/GuiGraphics;IIII)V

But the crash report you have implies that it isn't being used at runtime.  I'm not really sure how that would be possible, since the IMC message will be received well before the config is loaded (and especially before it is re-loaded upon entry into the world).

Does entering the world, running `/reload`, and then attempting to place Mjolnir in the table work?

**Comment by BazZziliuS** [comment]
> I see the log message from the successful IMC message
> 
> > [26Jun2024 14:26:54.322] [Worker-Main-15/DEBUG] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Transforming renderHUDBox with desc (Lnet/minecraft/client/gui/GuiGraphics;IIII)V
> 
> But the crash report you have implies that it isn't being used at runtime. I'm not really sure how that would be possible, since the IMC message will be received well before the config is loaded (and especially before it is re-loaded upon entry into the world).
> 
> Does entering the world, running `/reload`, and then attempting to place Mjolnir in the table work?

Reloading does not help, and /reload players cannot write on the server

**Comment by Shadows-of-Fire** [comment]
I'm unable to reproduce this in ATM9 with an alpha build of 7.4.0, so I'll consider this resolved for now.  After removing ATM9's config override of Mjolnir, it properly shows as a sword-type item via the IMC override.
