### ISSUE TITLE
Newest Update 7.4.0 Crashest the game on startup.

### ISSUE THREAD

**Issue by Maxi90909** [Shadows-of-Fire/Apotheosis#1279]
![Screenshot (44)](https://github.com/Shadows-of-Fire/Apotheosis/assets/76815835/9d7dc5fe-2cec-4573-bde7-9e6c8c9fe777)
[crash-2024-06-30_10.03.08-fml.txt](https://github.com/user-attachments/files/16043654/crash-2024-06-30_10.03.08-fml.txt)
[latest.log](https://github.com/user-attachments/files/16043686/latest.log)

I can only say that I updated the mod. I didn't do more and I don't know why it is crashing now.

**Comment by Maxi90909** [comment]
I think this is caused by passive skill tree. Let me check if it loads normal without it.

**Comment by Maxi90909** [comment]
Nevermind. It is also Eidolon.

**Comment by ElardHuaraca** [comment]
Okay here's another mod that dies with the new version of apotheosis: "Loot Beams, Apothic-Curios"

**Comment by meeprdib** [comment]
Those mods need to update their compatibility with Apotheosis, file an issue on those mods (if none exist already) and wait until they update.
