### ISSUE TITLE
Apotheosis causing crash on startup

### ISSUE THREAD

**Issue by Lynxiie071** [Shadows-of-Fire/Apotheosis#1280]
Right as minecraft says "joining world" it crashed to desktop and leaves this error code and nothing more:

Error: java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/affix/socket/SocketHelper

Crash report:
[crash-2024-06-30_15.01.24-client.txt](https://github.com/user-attachments/files/16045795/crash-2024-06-30_15.01.24-client.txt)

**Comment by Shadows-of-Fire** [comment]
Apothic curios needs to update their compat.
