### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by goldrichman9Modded** [Shadows-of-Fire/Apotheosis#1283]
https://mclo.gs/YgFnDE2

I was making sever and than, it crashed i've single out all mods and it seem to be this one casing the crash

**Comment by meeprdib** [comment]
Either downgrade apotheosis or uninstall whatever  "ec_apotheosis_plugin" is, as it's most likely made for an older version of apotheosis.

**Comment by Shadows-of-Fire** [comment]
That appears to be this mod https://www.curseforge.com/minecraft/mc-mods/ec-apotheosis-compat

But yeah, same advice, you have to use 7.3.5 or remove this mod until it updates.
