### ISSUE TITLE
Errored gems

### ISSUE THREAD

**Issue by BrolliD** [Shadows-of-Fire/Apotheosis#1292]
Hello! I am working on a forge 1.20.1 modpack with Apotheosis and every gem I get is coming back as an _errored gem_
![2024-07-11_11 20 17](https://github.com/Shadows-of-Fire/Apotheosis/assets/117849813/179dbd8f-a63c-4e2c-81db-8c1aa6899441)

I have all apotheosis correlated mods (Apotheosis, Apotheotic additions and attributes) updated to their latest versions for 1.20.1

What else will you need from me to help solve this issue?

**Comment by RoyalReject** [comment]
Its probably Apotheotic additions, errored gems usually happened when the NBT gets broken and Apotheotic additions has done this in the past, try with it disabled and see if that helps any and if so report it to Apotheotic additions.

**Comment by BrolliD** [comment]
> Its probably Apotheotic additions, errored gems usually happened when the NBT gets broken and Apotheotic additions has done this in the past, try with it disabled and see if that helps any and if so report it to Apotheotic additions.

Alright I tried a new world, got a gem drop and it still shows an error. I tried with Apotheotic additions turned off.

**Comment by RoyalReject** [comment]
Are you using something like curseforge where you can export your pack, If so you can upload it here and I can take a look on my pc https://support.curseforge.com/en/support/solutions/articles/9000197908-exporting-a-modpack-for-curseforge-project-submission

**Comment by BrolliD** [comment]
> Are you using something like curseforge where you can export your pack, If so you can upload it here and I can take a look on my pc https://support.curseforge.com/en/support/solutions/articles/9000197908-exporting-a-modpack-for-curseforge-project-submission

I am using curseforge and are currently exporting my modpack. Where can I send it?

**Comment by RoyalReject** [comment]
You should be able to upload the zip or you can DM it to me on discord (royalreject) if you use that.

**Comment by BrolliD** [comment]
> You should be able to upload the zip or you can DM it to me on discord (royalreject) if you use that.

I'll create a mediafire link because my pack is too big.

**Comment by BrolliD** [comment]
> You should be able to upload the zip or you can DM it to me on discord (royalreject) if you use that.

https://www.mediafire.com/file/mme9wvpazag1zbh/Brollicraft.zip/file

You should be able to download it from here!

**Comment by RoyalReject** [comment]
If you have to do this in the future, you really only need to select mods, config, defaultconfigs to export and maybe resourcepacks and kubejs or crafttweaker scripts. Makes it 39MB compared to 146MB

**Comment by BrolliD** [comment]
> If you have to do this in the future, you really only need to select mods, config, defaultconfigs to export and maybe resourcepacks and kubejs or crafttweaker scripts. Makes it 39MB compared to 146MB

Noted. I just thought to do everything as a precaution.

**Comment by RoyalReject** [comment]
Mo Enchantments is a mccreator mod and they are doing some weird things that breaks the gems NBT, for now it wont be compatible with apotheosis

**Comment by BrolliD** [comment]
> Mo Enchantments is a mccreator mod and they are doing some weird things that breaks the gems NBT, for now it wont be compatible with apotheosis

Alright, I'll check that out on my end!

**Comment by BrolliD** [comment]
> Mo Enchantments is a mccreator mod and they are doing some weird things that breaks the gems NBT, for now it wont be compatible with apotheosis

Yep! New world, saw a gem in a chest and it had stuff on it! I Was also able to keep the other Apoth mod on.
