### ISSUE TITLE
shadows of fire

### ISSUE THREAD

**Issue by KrysisUchiha** [Shadows-of-Fire/Apotheosis#1299]
java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/affix/socket/gem/GemItem
i keep getting this error when i try to join single player

**Comment by meeprdib** [comment]
I'm assuming you're running the latest Apotheosis on 1.20.1 with one or more of the following mods:

* Passive Skill Tree
* Loot Beams
* Extended Combat Apotheosis Plugin

In the future though, be sure to share more information such as a full latest.log or crash report when reporting issues, it makes it a lot easier for people to figure out what went wrong.
