### ISSUE TITLE
Duplicate Key 7 Crash

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#130]
`Minecraft v1.14.4`
`Forge v28.1.116`
`Apotheosis v2.4.4`

While exploring the world, my game stopped getting game update ticks. I could move around, but I could not interact with anything. 
Upon checking the logs, it looks like a Duplicate Key 7 crash occurred, even though it didn't crash to desktop or form a crash report. 
But here is what was printed in the [logs](https://gist.github.com/WenXin20/e889d68e0a2dedf9b3355ee417ea91b9)

Similar to what was reported at #108, but for 1.14.4.

**Comment by Shadows-of-Fire** [comment]
This should be fixed as of 1.15
