### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Raresheky2227** [Shadows-of-Fire/Apotheosis#1300]
On version 1.20.1 apotheosis and passive skill tree mod on their latest versions crash together. Crash points out something wrong with gems in this mod. Will post on the other's mod github too.

Crash log:
[crash-2024-07-20_23.46.52-fml.txt](https://github.com/user-attachments/files/16322304/crash-2024-07-20_23.46.52-fml.txt)

Debug log:
[debug.log](https://github.com/user-attachments/files/16322319/debug.log)

Latest log:
[latest.log](https://github.com/user-attachments/files/16322320/latest.log)

**Comment by RoyalReject** [comment]
Apotheosis was updated, you will either need to downgrade to 7.3.5 or disable passive skills until they update to account for the new changes.
