### ISSUE TITLE
[Crsah - Incompatible] Mixin apply fails on startup

### ISSUE THREAD

**Issue by ShinryuAspect** [Shadows-of-Fire/Apotheosis#1301]
It seems the EnchantmentHelper mixin fails to inject/collides or whatever is it called with Upgraded Trims' one.

**Upgraded trims**: https://www.curseforge.com/minecraft/mc-mods/upgraded-trims

*Debug.log*: https://gist.github.com/ShinryuAspect/bfaafcb1fccf17240c9366cb48463ec6

If it's on their end, let me know so I can report it to them.

**Comment by Padpadangz** [comment]
> It seems the EnchantmentHelper mixin fails to inject/collides or whatever is it called with Upgraded Trims' one.
> 
> **Upgraded trims**: https://www.curseforge.com/minecraft/mc-mods/upgraded-trims
> 
> _Debug.log_: https://gist.github.com/ShinryuAspect/bfaafcb1fccf17240c9366cb48463ec6
> 
> If it's on their end, let me know so I can report it to them.

Are you trying to run quark as well?

**Comment by ShinryuAspect** [comment]
Oh, may it also be due to Quark? Cuz, yes, I've Quark installed

**Comment by SiverDX** [comment]
It's unrelated to Quark

this overwrite 

https://github.com/Shadows-of-Fire/Apotheosis/blob/9aea273079340d8237ecccfa7a6d736563f8136a/src/main/java/dev/shadowsoffire/apotheosis/mixin/EnchantmentHelperMixin.java#L54-L57

is incompatible with this mixin from upgraded trims

```java
    @ModifyVariable(method = {"selectEnchantment"}, at = @At(value = "INVOKE", target = "Lnet/minecraft/world/item/ItemStack;getEnchantmentValue()I"))
    private static int trimEnchantability(int enchantability, RandomSource p_220298_, ItemStack p_220299_, int p_220300_, boolean p_220301_) {
        return TrimsUtil.hasLapisTrim(p_220299_) ? (int)((double)enchantability + Math.min(Math.floor((double)(enchantability / 2)), 10.0)) : enchantability;
    }
```

**Comment by Shadows-of-Fire** [comment]
No compat support is provided for closed source ARR mods
