### ISSUE TITLE
Ingredient crashed(Charm)

### ISSUE THREAD

**Issue by ashi0-a** [Shadows-of-Fire/Apotheosis#1305]
When hovering over any charm from the mod in jei, it pops up “This ingredient crashed when getting its tooltip. Please see the client logs for detailed information”.

Latest log:
[latest.log](https://github.com/user-attachments/files/16365622/latest.log)

**Comment by ashi0-a** [comment]
When you disable the ars nouveau mod, nothing changes
[latest.log](https://github.com/user-attachments/files/16365719/latest.log)

**Comment by SiverDX** [comment]
try removing apothic curios it's still not compatible with latest version to my knowledge and it's throwing a lot of exceptions in your log

**Comment by RoyalReject** [comment]
I think it's the opposite here they are using apotheosis 7.3.5. I have not tested but Apothic Curios had a version stating they updated to support 7.4.0 so in this case they need to either downgrade apothic curios or upgrade apotheosis

**Comment by ashi0-a** [comment]
> I think it's the opposite here they are using apotheosis 7.3.5. I have not tested but Apothic Curios had a version stating they updated to support 7.4.0 so in this case they need to either downgrade apothic curios or upgrade apotheosis

It worked! Thank you
