### ISSUE TITLE
Game crashes when looking at weapons/tools

### ISSUE THREAD

**Issue by mark0master** [Shadows-of-Fire/Apotheosis#1306]
Error: java.lang.NoClassDefFoundError: dev/shadowsoffire/apotheosis/adventure/socket/SocketHelper

[latest.log](https://github.com/user-attachments/files/16392068/latest.log)
[crash-2024-07-26_08.52.16-client.txt](https://github.com/user-attachments/files/16392078/crash-2024-07-26_08.52.16-client.txt)

I've tried the latest 4 versions of Apotheosis and this happens with all of them.

**Comment by RoyalReject** [comment]
Latest version of apothic curios requires 7.4.0. Apotheosis recently had a change that requires addons to possibly update

**Comment by Boggyghost** [comment]
I'm also having this issue and everything is updated.

**Comment by RoyalReject** [comment]
Some mods are not updated to latest apotheosis. Would need your logs/crash report to see the issue

**Comment by Boggyghost** [comment]
[crash-2024-07-29_08.54.53-client.txt](https://github.com/user-attachments/files/16413413/crash-2024-07-29_08.54.53-client.txt)
i believe this is it

**Comment by RoyalReject** [comment]
Your apotheosis is not on latest. Also easy anvils will cause issues

**Comment by Boggyghost** [comment]
[crash-2024-07-29_08.58.52-fml.txt](https://github.com/user-attachments/files/16413587/crash-2024-07-29_08.58.52-fml.txt)
Sorry, I forgot to update it. I had it 1 version before so I could at least load the game. Also, I'm wondering if passive skill tree mod is conflicting. I have to go back 1 version for that also to at least load game. When everything is updated, this is the crash report.
And thank you for taking your time to look into this!!

**Comment by RoyalReject** [comment]
Passive trees will also have to update to the latest changes in 7.4.0

**Comment by Boggyghost** [comment]
Everything in last crash was updated to newest version out. I just tried deleting Easy Anvils and it still crashed.

**Comment by RoyalReject** [comment]
Is that the same crash log as your previous post. If so passive skill trees had not updated yet. Again with the changes mods need to update to support it if they were using it. Apothic Curios happened to update. You will need to either wait for passive skills, remove it, or figure out what version all work with each other when using 7.3.5 vs 7.4.0

**Comment by Boggyghost** [comment]
ok. Thank you again for all your help.
