### ISSUE TITLE
[Bug] Seashelf of Aquatic Filtration has missing sprite

### ISSUE THREAD

**Issue by Phoupraw** [Shadows-of-Fire/Apotheosis#1308]
![image](https://github.com/user-attachments/assets/a08f3eee-275b-4370-878c-67c4bd331a16)
Mods List: [latest.log](https://github.com/user-attachments/files/16409127/latest.log)
This bug has existed since last year.

**Comment by Shadows-of-Fire** [comment]
This issue does not reproduce in isolation, which means you have another mod that is messing with the model. You will need to source the offending mod and report it to them.
![](https://i.imgur.com/IbPD8y1.png)
