### ISSUE TITLE
Disabling certain potion charms

### ISSUE THREAD

**Issue by DaytonaBlep** [Shadows-of-Fire/Apotheosis#1311]
I'm trying to make the flying charm uncraftable with kubejs, but the crafting recipes for all charms are removed too.

**Comment by meeprdib** [comment]
Can't help without seeing your script

**Comment by DaytonaBlep** [comment]
```
ServerEvents.recipes(event => {
    [
     Item.of('minecraft:potion', '{Potion:"apotheosis:extra_long_flying"}').strongNBT(),
    ].forEach((ingredientID) => event.remove({input: ingredientID}));
})
```

```
ServerEvents.recipes(event => {
    [
     Item.of('minecraft:potion', '{Potion:"apotheosis:extra_long_flying"}')
    ].forEach((ingredientID) => event.remove({input: ingredientID}));
})
```

```
ServerEvents.recipes(event => {
    event.remove({ input: 'minecraft:potion', '{Potion:"apotheosis:extra_long_flying"}' })
})
```
Same result for all variants, all charms are uncraftable. And not only charms, everything in the modpack that uses potions in the recipe, it's about 60~ items

**Comment by Shadows-of-Fire** [comment]
Charm crafting is controlled by a single dynamic recipe; removing it will remove charm crafting entirely, and it does not have a blacklist.

Whatever issue you are seeing that removes everything using potions is just a result of the script being bad, but the functionality you want to accomplish is impossible.

**Comment by SiverDX** [comment]
@Shadows-of-Fire you could add a mobeffect blacklist tag and check it when you're also checking `.isInstantenous()`
