### ISSUE TITLE
Apotheosis Reforging Glitch

### ISSUE THREAD

**Issue by DarkSammich** [Shadows-of-Fire/Apotheosis#1312]
When you don't equip the armor first then enchant it the stats won't apply whatsoever even if reforging it again after equipping it. 1.20.1

**Comment by Shadows-of-Fire** [comment]
I am unable to reproduce this issue in any capacity.  Items do not experience any change when being equipped, so there is no difference when reforging a previously-equipped item as compared to a fresh item. You might have an additional mod in your instance causing the attribute system to go haywire, but it isn't apoth.
