### ISSUE TITLE
Minecraft crashes when spawning a specific miniboss

### ISSUE THREAD

**Issue by amazing-maze** [Shadows-of-Fire/Apotheosis#1317]
https://pastebin.com/MQ1pdUqR

No issues with the overworld or end, only the miniboss "wither_Archer" in the nether.

**Comment by meeprdib** [comment]
Do you have any Apotheosis addons installed? Or have any apotheosis related datapacks loaded in game?

**Comment by amazing-maze** [comment]
I have now tried to remove the addons, but the same problem shows up. No datapacks at all!

**Comment by Shadows-of-Fire** [comment]
I am not able to reproduce this issue.  Withering archers under normal conditions are able to spawn as expected.  Apoth provides three unique gear sets for the `#the_nether_bow` tag - <https://github.com/Shadows-of-Fire/Apotheosis/tree/1.20/src/main/resources/data/apotheosis/gear_sets/the_nether>

**Comment by Omni-Mads-Jensen** [comment]
Odd 🤔 Is there a way of disabling the miniboss spawning?

**Comment by Shadows-of-Fire** [comment]
You can use a datapack to override that specific miniboss with the false condition, which will remove it.

**Comment by amazing-maze** [comment]
I don't have any experience with making datapacks. Do you have a link or guide to disable that miniboss? or perhaps a way to disable the spawns in the nether specifically? I really enjoy the mod, and would hate to remove it :c

**Comment by Shadows-of-Fire** [comment]
You can base off of this export of the base apotheosis data files from 7.4.0
[stock_1.20.1_7.4.0.zip](https://github.com/user-attachments/files/16643005/stock_1.20.1_7.4.0.zip)

You would then erase every data file you don't care about (those in `data/`), leaving only the withering archer file (`data/apotheosis/minibosses/the_nether/withering_archer.json`)

Then replace the contents of the withering archer with the false-condition:
```json
{
    "conditions": [
        { "type": "forge:false" }
    ]
}
```
You will then have a datapack that, when loaded, will disable the withering archer, which should resolve your issue.
