### ISSUE TITLE
looting prevents ancient knowledge from working

### ISSUE THREAD

**Issue by fakegamingnerd** [Shadows-of-Fire/Apotheosis#1318]
for whatever reason whenever looting is on a weapon in my modpack, it prevents the effect from ancient knowledge from working. I have tested with a fresh pack that only has apotheosis and its dependencies and ancient knowledge worked fine. i even added apothic attributes and better than mending since they were the only mods in the main modpack that i thought might affect experience drops and ancient knowledge still worked. it is quite likely this isnt caused by apotheosis but i couldnt find any other mods that affect experience drops in the main modpack so putting here. i have included the modlist. If anyone knows any of the other mods that could be causing this issue lmk and ill move this to that mods issue tracker.

AdditionalBanners-Forge-1.20.1-14.0.4.jar
--
alexscaves-1.1.4.jar
alexsmobs-1.22.8.jar
amendments-1.20-1.2.8.jar
Apotheosis-1.20.1-7.4.0.jar
ApothicAttributes-1.20.1-1.3.6.jar
appleskin-forge-mc1.20.1-2.5.1.jar
ArcaneLanterns-v8.0.0-1.20.1-Forge.jar
architectury-9.2.14-forge.jar
ArmorStatues-v8.0.6-1.20.1-Forge.jar
artifacts-forge-9.5.11.jar
athena-forge-1.20.1-3.1.2.jar
BagOfHolding-v8.0.2-1.20.1-Forge.jar
balm-forge-1.20.1-7.3.6-all.jar
BarteringStation-v8.0.0-1.20.1-Forge.jar
bedspreads-forge-6.2.0+1.20.1.jar
beekeeperhut-forge-mc1.20.1-2.0.1.jar
BetterThanMending-1.7.2.jar
BetterTridents-v8.0.1-1.20.1-Forge.jar
blastingraw-1.20.1-2-forge.jar
BlockRunner-v8.0.4-1.20.1-Forge.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
BorderlessWindow-1.20-1.6.0.jar
Bountiful-6.0.3+1.20.1-forge.jar
BuildingWands-mc1.20.1-2.6.9-release.jar
caelus-forge-3.2.0+1.20.1.jar
chalk-1.20.1-1.6.4.jar
charmofundying-forge-6.5.0+1.20.1.jar
chat_heads-0.12.9-forge-1.20.jar
Chipped-forge-1.20.1-3.0.6.jar
citadel-2.5.6-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar.disabled
collective-1.20.1-7.80.jar
comforts-forge-6.4.0+1.20.1.jar
Companion-1.20.1-forge-5.0.1.jar
configured-forge-1.20.1-2.2.3.jar
Controlling-forge-1.20.1-12.0.2.jar
corpse-forge-1.20.1-1.0.12.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.f.jar
createaddition-1.20.1-1.2.4d.jar
CreateCasing-1.20.1-1.6.1-fix1.jar
create_salt   1.20.1-1.1.0.jar
cristellib-1.1.5-forge.jar
curios-forge-5.9.1+1.20.1.jar
curious_armor_stands-1.20-5.1.0.jar
customizableelytra-forge-2.1.2+1.20.jar
CutThrough-v8.0.2-1.20.1-Forge.jar
DarkUtilities-Forge-1.20.1-17.0.3.jar
dcintegration-forge-3.0.7.1-1.20.1.jar
deathbackup-1.20.1-3.4.jar
DiagonalFences-v8.1.4-1.20.1-Forge.jar
DiagonalWalls-v8.0.3-1.20.1-Forge.jar
DiagonalWindows-v8.1.4-1.20.1-Forge.jar
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
duckling-3.0.0-forge.jar
dummmmmmy-1.20-1.8.17b.jar
dynamiclights-1.20.1.2.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar
easy-piglins-forge-1.20.1-1.0.9.jar
easy-villagers-forge-1.20.1-1.1.15.jar
EasyAnvils-v8.0.2-1.20.1-Forge.jar
EasyMagic-v8.0.1-1.20.1-Forge.jar
EasyShulkerBoxes-v8.0.2-1.20.1-Forge.jar
easy_mob_farm_1.20.1-7.1.0.jar
EchoChest-v8.0.0-1.20.1-Forge.jar
elytraslot-forge-6.4.3+1.20.1.jar
embeddium-0.3.28+mc1.20.1.jar
embeddiumplus-1.20.1-v1.2.13.jar
EnchantingInfuser-v8.0.3-1.20.1-Forge.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.16.jar
EnderZoology-v8.0.2-1.20.1-Forge.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
exposure-1.20.1-1.7.5-forge.jar
FarmersDelight-1.20.1-1.2.4.jar
Female-Gender-Mod-forge-1.20.1-3.0.1.jar
ferritecore-6.0.1-forge.jar
files_and_folders.txt
flowerymooblooms-forge-mc1.20.1-2.0.2.jar
framework-forge-1.20.1-0.7.6.jar
friendsandfoes-forge-mc1.20.1-2.0.15.jar
ftb-chunks-forge-2001.3.1.jar
ftb-library-forge-2001.2.4.jar
ftb-teams-forge-2001.3.0.jar
ftb-ultimine-forge-2001.1.5.jar
geckolib-forge-1.20.1-4.4.7.jar
GeckoLibOculusCompat-Forge-1.0.1.jar
geode_plus-forge-1.2.5-1.20.1.jar
giacomos_map_merging-1.20.1-1.3.6.jar
globalxp-forge-1.20.1-1.11.jar
goblintraders-forge-1.20.1-1.9.3.jar
guardvillagers-1.20.1-1.6.6.jar
handcrafted-forge-1.20.1-3.0.6.jar
HorseExpert-v8.1.1-1.20.1-Forge.jar
Iceberg-1.20.1-forge-1.1.21.jar
idas_forge-1.10.1+1.20.1.jar
IllagerInvasion-v8.0.5-1.20.1-Forge.jar
integrated_api-1.5.1+1.20.1-forge.jar
integrated_stronghold-1.1.1+1.20.1-forge.jar
integrated_villages-1.0.1+1.20.1-forge.jar
ItemBorders-1.20.1-forge-1.2.1.jar
Jade-1.20.1-forge-11.9.2.jar
JadeAddons-1.20.1-forge-5.2.2.jar
jagmkiwis-1.20.1-1.1.1.jar
jeed-1.20-2.2.2.jar
jei-1.20.1-forge-15.8.2.25.jar
JRFTL-1.20.1-1.6.0.jar
JustEnoughAdvancements-1.20.1-5.0.1.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
Kambrik-6.1.1+1.20.1-forge.jar
kotlinforforge-4.11.0-all.jar
LeavesBeGone-v8.0.0-1.20.1-Forge.jar
letsdo-API-forge-1.2.15-forge.jar
letsdo-bakery-forge-1.1.15.jar
letsdo-beachparty-forge-1.1.5.jar
letsdo-bloomingnature-forge-1.0.7.jar
letsdo-brewery-forge-1.1.9.jar
letsdo-candlelight-forge-1.2.13.jar
letsdo-herbalbrews-forge-1.0.8.jar
letsdo-meadow-forge-1.3.19.jar
letsdo-nethervinery-forge-1.2.14.jar
letsdo-vinery-forge-1.4.27.jar
LibX-1.20.1-5.0.12.jar
light-overlay-8.0.0-forge.jar
lootr-forge-1.20-0.7.34.86.jar
material_elements_1.20.1-7.1.1.jar
mavapi-1.1.4-mc1.20.1.jar
mavm-1.2.6-mc1.20.1.jar
MetalBundles-v8.0.2-1.20.1-Forge.jar
modernfix-forge-5.19.0+mc1.20.1.jar
modonomicon-1.20.1-forge-1.74.0.jar
monobank-1.20.1-1.1.4.jar
moonlight-1.20-2.12.9-forge.jar
MouseTweaks-forge-mc1.20.1-2.25.1.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Neruina-2.1.1-forge+1.20.1.jar
nethersdelight-1.20.1-4.0.jar
occultism-1.20.1-1.132.2.jar
oceansdelight-1.0.2-1.20.jar
oculus-flywheel-compat-forge1.20.1+1.1.1.jar
oculus-mc1.20.1-1.7.0.jar
pamhc2crops-1.20-1.0.3.jar
pamhc2foodcore-1.20.4-1.0.5.jar
pamhc2foodextended-1.20.4-1.0.1.jar
pamhc2trees-1.20-1.0.2.jar
Patchouli-1.20.1-84-FORGE.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
PigPen-Forge-1.20.1-15.0.2.jar
Placebo-1.20.1-8.6.2.jar
polymorph-forge-0.49.5+1.20.1.jar
potionbundles-1.20-1.8.jar
Prism-1.20.1-forge-1.0.5.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
Quark-4.0-460.jar
QuarkOddities-1.20.1.jar
quark_delight_1.0.0_forge_1.20.1.jar
repurposed_structures-7.1.15+1.20.1-forge.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.28.jar
rubidium-extra-0.5.4.3+mc1.20.1-build.121.jar
Runelic-Forge-1.20.1-18.0.2.jar
salt-1.20.1-1.2.6.jar
Searchables-forge-1.20.1-1.0.3.jar
SkyVillages-1.0.4-1.19.2-1.20.1-forge-release.jar
SmartBrainLib-forge-1.20.1-1.14.2.jar
sootychimneys-1.20.1-1.2.1.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
sophisticatedstorage-1.20.1-0.10.25.804.jar
spark-1.10.53-forge.jar
Stoneworks-v8.0.0-1.20.1-Forge.jar
supplementaries-1.20-2.8.17.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
TinyCoal-forge-1.20.1-1.1.5.jar
TinySkeletons-v8.0.1-1.20.1-Forge.jar
TradingPost-v8.0.2-1.20.1-Forge.jar
trimeffects-forge-1.20.X-1.3.1.jar
UniversalBoneMeal-v8.0.1-1.20.1-Forge.jar
UniversalEnchants-v8.0.0-1.20.1-Forge.jar
unlockschematics-1.20.1-1.0.1.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
wares-1.20.1-1.2.8.jar
waystones-forge-1.20-14.1.4.jar
XaerosWorldMap_1.38.8_Forge_1.20.jar
Xaeros_Minimap_24.2.0_Forge_1.20.jar
xaeros_waystones_compability-1.0.jar
Zeta-1.0-24.jar
[1.20.1]MoreCraftingTables-5.1.3.jar

**Comment by meeprdib** [comment]
Do a binary search to find the culprit of this issue.

>Disable half of the mods in the modpack
>If issue is resolved, enable half of the mods back
>If issue is not resolved, disable half of the mods again
>Rinse and repeat until you find the culprit(s)
