### ISSUE TITLE
[Compatibility][Crash] Mod is not compatible with passive skill trees as of newest update

### ISSUE THREAD

**Issue by AndrinoC** [Shadows-of-Fire/Apotheosis#1320]
![image](https://github.com/user-attachments/assets/dc78e753-133e-4147-8b2c-bc53159ffe74)

Forge 47.3.0
Minecraft Java 1.20.1
Apotheosis 1.20.1-7.3.5
Passive Skill Tree 1.20.1-BETA-0.6.13a-all

In case of any more info needed please comment, I am willing to help!

**Comment by Shadows-of-Fire** [comment]
This can only be resolved by PST.
