### ISSUE TITLE
It crashes when the adventure module is disabled in the mod.

### ISSUE THREAD

**Issue by applelike2** [Shadows-of-Fire/Apotheosis#1322]
[crash_report.txt](https://github.com/user-attachments/files/16636229/crash_report.txt)

It crashes when the adventure module is disabled in the mod.
The same thing happens even though I only enabled Apotheosis mode and the modes required for Apotheosis mode.
(I used a translator, so the sentences may be strange.)

**Comment by Tullemania** [comment]
I also experience this issue on the latest Apotheosis version on 1.20.1

**Comment by GoldenDarius** [comment]
for all its worth I am experiencing the same issue, i don't know if this happened to you people as well, but I'd also get this when i'd crash
![image](https://github.com/user-attachments/assets/f44e8e50-2617-4f2a-a6b9-e9c9f0bf1a66)
I have disabled all my mods and yeah it was definitely apotheosis, just didn't expect it to be tied to the adventure module

**Comment by RoyalReject** [comment]
There was a forge bug that causes issues with disabling modules on 1.20.1. Some have had luck with latest forge version. But 1.20.1 is built against neoforge and disabling does work properly on neoforge

**Comment by Tullemania** [comment]
> for all its worth I am experiencing the same issue, i don't know if this happened to you people as well, but I'd also get this when i'd crash ![image](https://private-user-images.githubusercontent.com/75396163/358660576-f44e8e50-2617-4f2a-a6b9-e9c9f0bf1a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4Mjk2NDgsIm5iZiI6MTcyMzgyOTM0OCwicGF0aCI6Ii83NTM5NjE2My8zNTg2NjA1NzYtZjQ0ZThlNTAtMjYxNy00ZjJhLWE2YjktZTljOWYwYmYxYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDE3MjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NmNiMjQyNmY3YjkzODg0ZTYzMmY1ZTgyNGFmMDQ1NjA5YWIyMGUzYmM3NWI3ZTQ4YmZiMjNmZjdmNmE1N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ajdJCZcN7iSI62CHiPNhDlZmi0Tb4qlA1mO-voaI2fA) I have disabled all my mods and yeah it was definitely apotheosis, just didn't expect it to be tied to the adventure module

I haven't had any issues with the text like that.

**Comment by Shadows-of-Fire** [comment]
Someone made a Forge PR at some point to add the same fix, so this must be a new version of the same issue with a different root cause (assuming the used forge version is new enough)
