### ISSUE TITLE
Enchanting level

### ISSUE THREAD

**Issue by jmoney184** [Shadows-of-Fire/Apotheosis#1325]
So I am playing Cisco's Fantasy Medieval RPG and for some reason our enchants are completely different he can enchant at level 30 due to the bookshelves while I'm capped at 3 and I have my fully enchantment tree maxed out so it's a bit confusing ![image](https://github.com/user-attachments/assets/fae26475-0259-4ceb-8702-a3584170bd25)

**Comment by Shadows-of-Fire** [comment]
If your highest enchantment level selection does not match your current eterna value times two, then you have another mod messing with the enchantment levels, which is out of my control.  You should communicate with the modpack author to see what's going on.
