### ISSUE TITLE
Bleeding effect is bugged 

### ISSUE THREAD

**Issue by KiraKayn** [Shadows-of-Fire/Apotheosis#1326]
On 1.20.1 Forge latest apotheosis version (has been like this before aswell) the Bleeding effect is bugged, it doesnt go off like normal effects do, it says on mobs forever when applied, heres a video: 

https://github.com/user-attachments/assets/de318f42-e83c-43f9-9757-0d0dda148a1c

**Comment by Shadows-of-Fire** [comment]
How are you applying the effect to the creeper?  Usually this is caused by erroneously adding the effect on the client or something of the sort.
Bleeding, like most mob effects, does not manage its own timing / removal.

**Comment by KiraKayn** [comment]
I used an origins power, but when i changed that power to inflict poison instead, it worked like I wanted it to.

**Comment by Shadows-of-Fire** [comment]
Don't think there's anything I can do here, bleeding does not manage its own ticking.  Not sure why origins would be causing it to last forever, but that's out of my control.
