### ISSUE TITLE
[Idea] Elytra Fall Enchantment

### ISSUE THREAD

**Issue by CrimsonFluff** [Shadows-of-Fire/Apotheosis#133]
Could you please add an Enchantment, Maybe called SkyFall, that when attached to an Elytra does not make you die if you dive into a wall or the floor too fast.

I just cant get used to landing while wearing an Elytra and not killing myself

I think this is in-keeping with your mod

**Comment by mettlephaontoms** [comment]
I think of it like a subtle version of feather falling that is multiplied by the feather falling enchantment level.

**Comment by ghost** [comment]
Maybe feather falling can dampen the Elytra damage as well as fall damage
