### ISSUE TITLE
Wither Skeletons not spawning in overworld (with No Conditions upgrade)

### ISSUE THREAD

**Issue by dragonkid828** [Shadows-of-Fire/Apotheosis#1331]
Minecraft Version: 1.19.2 
Apotheosis Version: 6.4.1 - current

Added a dragon egg to my wither skeleton spawner and it still doesn't spawn wither skeletons. When tested in creative, they would spawn in and instantly despawn. Updated to the most recent version manually and they still weren't spawning as far as I could tell. Can't tell if it's a me problem or what because in ATM8 prior to the most recent version (1.0.28?) it WAS working.

**Comment by Shadows-of-Fire** [comment]
Are you on peaceful?

**Comment by dragonkid828** [comment]
The creative world may have been on peaceful I think, but the survival world with the mob grinder definitely isn't.
![javaw_ZEfYrC3qBW](https://github.com/user-attachments/assets/bdd07a3b-d114-4026-aafb-c7a637e7cf08)
Top one is the wither skeleton spawner, it has a dragon egg and redstone control.

**Comment by Shadows-of-Fire** [comment]
Can you swap it with the bottom one?  It looks like you have a roof on the building, and depending on the spawn range, there might not be any available positions for wither skeletons (3-block tall) to spawn without colliding with the roof.  The no conditions augment does not remove collision checks (it did in like... 1.16, but it just led to mobs spawning in walls).

**Comment by dragonkid828** [comment]
You were right, it was too small. I extended the roof one and they're spawning now. Thank you for your help, and sorry about that!
