### ISSUE TITLE
Log Spam Shield Breaker Test

### ISSUE THREAD

**Issue by JurkoDev** [Shadows-of-Fire/Apotheosis#1336]
am on 1.20.1 i updated all the mod via the prism update tool and now apotheosis spams about a shield breaker test every time i join a server am on apotheosis 7.4.2

console log (trimmed it was 700mb of the same thing)
https://gist.github.com/JurkoDev/643c9f83ec8c189b500b71310fa030d2

**Comment by Shadows-of-Fire** [comment]
You have some mod using a mixin or similar which is breaking the SynchedEntityData system.  This error will populate any time a Zombie (and likely other mobs) is constructed.

This is not an apoth issue, you'll need to remove mods until you can source the offending mod.
