### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [Shadows-of-Fire/Apotheosis#1337]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack?

**Comment by Shadows-of-Fire** [comment]
I have no plans to upload artifacts to Modrinth for the foreseeable future.  You may distribute the jars sourced from CurseForge within a Modrinth pack.

**Comment by mzxiethemuse** [comment]
sorry for necropost - why not?

**Comment by meeprdib** [comment]
<img width="523" height="875" alt="Image" src="https://github.com/user-attachments/assets/93273fac-cb9a-484d-9299-66bb79f72943" />

**Comment by lonevox** [comment]
I'd remind any dev with this attitude towards modrinth that it has one third of mod searches and is only gaining on curseforge (curseforge also has mods for many other games besides mc).

<img width="1162" height="611" alt="Image" src="https://github.com/user-attachments/assets/93b477db-4c92-4079-aca8-9828c9335266" />

**Comment by mzxiethemuse** [comment]
<img alt="Image" width="523" height="875" src="https://private-user-images.githubusercontent.com/149535160/471287381-93273fac-cb9a-484d-9299-66bb79f72943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM5MTY2MzEsIm5iZiI6MTc1MzkxNjMzMSwicGF0aCI6Ii8xNDk1MzUxNjAvNDcxMjg3MzgxLTkzMjczZmFjLWNiOWEtNDg0ZC05Mjk5LTY2YmI3OWY3Mjk0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDczMFQyMjU4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmQyNmJmODllZWFjYTBjMzA3NmU4OTdlYTRhZWMwNzcxMWJhOWI1ZjljMTUzYjY1NjM5OTQxMjhlNTIwMGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZENbquSTdbc0ZGi6Djiy5X_bzZ06UxmzRfyxyKLkqXM">

lmfao
is it seriously that hard to just bite the bullet and spend an afternoon setting up a mod page there? this feels like they're refusing to do something that would be good for everyone just bcuz of some weird hate boner

**Comment by meeprdib** [comment]
Sounds pretty ungrateful and whiny asking people to spend their free time doing something they have no interest in, especially given that everyone has *explicit permission* to redistribute Shadow's mods in Modrinth modpacks to avoid CurseForge exclusivity. I doubt your attitude is helping him sway his stance though, and if you really cared about this you'd PR a publishing script to his mods or something to make his life easier instead of bitching and moaning on an issue tracker.

**Comment by mzxiethemuse** [comment]
oh cool, being slightly critical is 'bitching and moaning' now. maybe *he* could spend his free time setting up the page instead of bitching and moaning about it, then?

**Comment by Shadows-of-Fire** [comment]
> is it seriously that hard to just bite the bullet and spend an afternoon setting up a mod page there?

I have 15 actively maintained projects. That is far more than "an afternoon". Each project also needs infrastructure changes to be able to publish to modrinth.

It also requires a commitment to maintaining the modrinth pages, which is not free either.

The cost/benefit analysis of what I get out of supporting Modrinth is simply not there. Modrinth's creator revenue recently cratered by about 80-85% this month.
