### ISSUE TITLE
crash with OpenJDK.

### ISSUE THREAD

**Issue by MadWomen** [Shadows-of-Fire/Apotheosis#134]
crash with OpenJDK 11.0.6 with apotheosis 1.15.2 3.0.4
exception in server tick loop running ATM5 modpack.

works fine with oracle java.

crashlog:
https://pastebin.com/X3cvrmUZ

**Comment by GilloDaby** [comment]
How fix this...!

**Comment by Shadows-of-Fire** [comment]
Ah, right, this is a thing.  One minute...

**Comment by GilloDaby** [comment]
How download the fix?
