### ISSUE TITLE
Crash when reforging

### ISSUE THREAD

**Issue by ethvor** [Shadows-of-Fire/Apotheosis#1341]
1.20.1 ATM 9 repack, Forge 47.1.3

The server instantly crashes when I generate the 3 reforges in the reforging table. I tried both the godforged pearl and the arcane sands to reforge armor, weapons, enchanted and non-enchanted. Each time, I did not see the 3 reforges before the game crashed. I have added 3 crash reports from seperate crashes that I repeated. The order in which I placed the items did not matter, it crashed either way (item first, then the godforged pearl VS the godforged pearl then the item)

[crash-2024-09-03_02.18.32-client.txt](https://github.com/user-attachments/files/16844446/crash-2024-09-03_02.18.32-client.txt)
[crash-2024-09-03_02.20.57-client.txt](https://github.com/user-attachments/files/16844447/crash-2024-09-03_02.20.57-client.txt)
[crash-2024-09-03_02.26.50-client.txt](https://github.com/user-attachments/files/16844448/crash-2024-09-03_02.26.50-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is a rubidium issue.  Use embeddium.

**Comment by ethvor** [comment]
thanks man! such a cool mod, glad i can continue playing :)
