### ISSUE TITLE
version 1.12.2 naming bug of fortune picks/axes

### ISSUE THREAD

**Issue by Wolfram96** [Shadows-of-Fire/Apotheosis#1342]
Hi, i enjoy the hunt for rare Items and it took me quite a while to assemble an almost complete set of Ancient (unbreakable) gear, but for some reason all the ancient or epic picks and axes that carry the Fortune enchantment have a bugged out name. basically "affix.apotheosis:fortunate.double" or "affix.apotheosis:fortunate" and renaming them in an anvil will remove the special colour from the name, thats just not satisfying. 

I know that version is hopelessly outdated, but could you perhaps fix it? The one epic axe i found that had an unbreaking enchantment instead, had a properly spelled-out name even if it was basically useless. 

or alternatively perhaps there is a way to rename the items and keep the colour?

thx for the awesome mod, any further updates to the 1.12.2 version would be appreciated.

**Comment by Shadows-of-Fire** [comment]
1.12 will not receive any changes.  You can probably fix this with a resource pack that defines the relevant lang keys you see here using the same pattern as similar ones from the 1.12 era, but you're on your own to figure that out.
