### ISSUE TITLE
Item.Apotheosis.Gem with the Royal Family Gem

### ISSUE THREAD

**Issue by colin094** [Shadows-of-Fire/Apotheosis#1348]
Basically in the server im in (ATM-9) the royal family gem has been bugged so that it is only a Item.Apotheosis.Gem item with no stats, this is persistent across all version of atm-9 and all versions of apotheosis that atm-9 uses. Similarly, resetting the world file, reinstalling the mod and modpack, and using a default apotheosis config has not been effective in fixing this issue. The only thing I can think of is that the server runs on mohist if there's any known mod or plugin incompatibilities between apoth and that.
![2024-09-09_21 04 36](https://github.com/user-attachments/assets/0a53f94e-beb9-4e65-a108-559c876d2cad)
![2024-09-09_21 04 20](https://github.com/user-attachments/assets/f85f74b5-0e20-49d5-83d6-295adeeed198)

**Comment by Shadows-of-Fire** [comment]
That would imply the gem failed to load, hence a gem with that NBT being invalid.  You can check your game log for loading errors, but there isn't any more specific support I'm able to offer.
