### ISSUE TITLE
Enchanting table doesn't exceed level 54

### ISSUE THREAD

**Issue by RazvanFlorea7** [Shadows-of-Fire/Apotheosis#1353]
i've made a 16 x infused hellshelf setup, and the enchanting level of the table is still 54. is this a bug or intended? what am i doing wrong?

**Comment by RazvanFlorea7** [comment]
To add here: this is on forge 1.20.1

**Comment by Shadows-of-Fire** [comment]
You need the upgraded form of an infused hellshelf (glowing or blazing) to hit 60.
