### ISSUE TITLE
Out of bounds crash extracting gem from an item

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#1354]
Details here: https://github.com/EnigmaticaModpacks/Enigmatica9/issues/1012

apotheosis version: 1.19.2-6.5.1

**Comment by SiverDX** [comment]
This seems to happen when:
- You have https://www.curseforge.com/minecraft/mc-mods/polymorph installed
- You extract a gem, place in another item and try to extract another gem

At least from my testing

**Comment by Shadows-of-Fire** [comment]
[d98f459](https://github.com/Shadows-of-Fire/Apotheosis/commit/d98f459a9945a740deab0b7a39e528f4648d3628)
