### ISSUE TITLE
Crash while attempting to reforge Mythic Botany Mjoellnir

### ISSUE THREAD

**Issue by StAlexandre** [Shadows-of-Fire/Apotheosis#1358]
Attempted affix reforging with Mythic Botany's Mjoellnir, and it caused the client to crash. The Apotheosis version being used is 7.4.2, which last I checked, was the latest offered.

Crash log:
[crash-2024-09-23_21.31.08-client.txt](https://github.com/user-attachments/files/17106672/crash-2024-09-23_21.31.08-client.txt)

**Comment by Shadows-of-Fire** [comment]
Use the adventure module config to force a type override for Mjoellnir.  They have an IMC message to force the type but it seems to not be working sometimes.
