### ISSUE TITLE
Wither Skeleton Spawner doesn't work in overworld

### ISSUE THREAD

**Issue by DJToxica** [Shadows-of-Fire/Apotheosis#136]
Hello Shadows-of-Fire

I think that this is probably a basegame issue, but maybe you can fix it.
I converted a spawner to a wither skeleton spawner and put it in my mobfarm in the overworld.
But it looks like it doesn't work in the overworld. It's emitting flames and the wither model is spinning but even after waiting half an hour no skeletons spawned. I even put Netherbrick Blocks under it to simulate a nether fortress (which would be an interesting condition)

I havn't put it in the nether yet but i will test it this evening.

**Comment by Shadows-of-Fire** [comment]
Wither skeletons wont spawn outside the nether, you'll need an ignore conditions modifier for that, or some way to convert the area to the hell biome.
