### ISSUE TITLE
MC crashes on startup with an Exit code 1

### ISSUE THREAD

**Issue by Delet05** [Shadows-of-Fire/Apotheosis#1360]
Apotheosis seems to not be working with my modpack. It looks like everything is fine but when i launch the minecraft launcher it crashes with a Code 1 Error. I left the debug and crashlog attached as well to see if you could help me fix this.

[debug.log](https://github.com/user-attachments/files/17181171/debug.log)
 
[2024-09-29-3.log](https://github.com/user-attachments/files/17181174/2024-09-29-3.log)

**Comment by Shadows-of-Fire** [comment]
Remove "Anvil Never Too Expensive"
