### ISSUE TITLE
Please add incompat with Anvils Never Too Expensive, or fix mixin

### ISSUE THREAD

**Issue by purejosh** [Shadows-of-Fire/Apotheosis#1361]
Hey, noticed that if I have Apotheosis and [Anvils Never Too Expensive](https://modrinth.com/mod/ante) installed, the client hard crashes with no crash log or warnings. It seems Apotheosis and ANTE are fighting for a mixin, and one of the mods is causing hard crashing. 

```
[13:10:50] [pool-4-thread-1/WARN]: @ModifyConstant conflict. Skipping ante.mixins.json:AnvilMenuMixin->@ModifyConstant::mixinLimitInt(I)I with priority 1000, already redirected by apotheosis.mixins.json:AnvilMenuMixin->@ModifyConstant::apoth_removeLevelCap(I)I with priority 1000
```

I asked ANTE's dev to add incompat on Apotheosis, so at least the client will get a warning if they're both present. Is it Apotheosis crashing?

**Comment by meeprdib** [comment]
They are incompatible because Apotheosis and ANTE have the same anvil mixin. You do not need ANTE when using Apotheosis.

**Comment by SiverDX** [comment]
> They are incompatible because Apotheosis and ANTE have the same anvil mixin. You do not need ANTE when using Apotheosis.

i think thats the point
in fabric you can name mods which your mod is incompatible with and you'll get a proper error message on startup that way
don't know if (neo)forge has sth. like that as well

**Comment by purejosh** [comment]
> They are incompatible because Apotheosis and ANTE have the same anvil mixin. You do not need ANTE when using Apotheosis.

That's what I said. 

My request was to either add incompatibility to the mod, meaning a message will show up in the game saying that Minecraft won't load due to a mod conflict, or to add graceful handling of the exception when attempting to mixin, to prevent the client from simply hard crashing with no error messages whatsoever.

It might not be obvious to all end users that using both mods is pointless. And it's incredibly less obvious why their client is crashing. I spent some time fixing this for one of my members, and I definitely see room for improvement on handling this.

**Comment by Shadows-of-Fire** [comment]
> Is it Apotheosis crashing?

No, Apoth's mixin is marked as non-required.  ANTE's is not, hence the crash.  I probably won't be making any more 1.20 releases unless a critical bug is discovered, so I'll close this as not planned.
