### ISSUE TITLE
[Question] Weapon with right click ability and apotheosis affixes 

### ISSUE THREAD

**Issue by baseb01** [Shadows-of-Fire/Apotheosis#1364]
Is there a way to make a modded weapon (cataclysm:meat_shredder in this case) with a right click ability trigger the apoth affixes on the weapon such as overheal?

Kind regards

**Comment by Shadows-of-Fire** [comment]
Lifesteal and Overheal trigger off of any direct physical damage dealt by any source (which would include right click abilities, as long as they are direct damage). If it isn't triggering for that particular effect, there's no easy way to make it apply, short of adding a new event handler in an addon.
