### ISSUE TITLE
Negative base armor value

### ISSUE THREAD

**Issue by PapaDimitri** [Shadows-of-Fire/Apotheosis#1365]
So i have downloaded apotheosis and noticed that after sometime when i take damage (i think ) my base armor value goes negative. Also all armor stats are wierd too - they can go negative or lower number. The only fix i found is dying.
![2024-10-06_13 29 12](https://github.com/user-attachments/assets/913faf49-3c03-458d-8b66-8c52f15accf8)

**Comment by I-Nocturne-I** [comment]
what mods are you using?

**Comment by PapaDimitri** [comment]
Well... Better question is what mod i m not using lmao. 350 mods is quite a lot. There are few mods that i suspect could cause this:

- Sintraya connector (i dont think its causing it, never had problems with it but will write about it otherwise)

- Born in chaos (Almost everytime i fought with mobs from this mod and took hefty amount of damage resulted in this wierd armor value)

I forgot to add this is 1.20.1 forge

**Comment by PapaDimitri** [comment]
I m also using AttributeFix and tried deleting config file after installing apotheosis

**Comment by I-Nocturne-I** [comment]
> Well... Better question is what mod i m not using lmao. 350 mods is quite a lot. There are few mods that i suspect could cause this:
> 
>     * Sintraya connector (i dont think its causing it, never had problems with it but will write about it otherwise)
> 
>     * Born in chaos (Almost everytime i fought with mobs from this mod and took hefty amount of damage resulted in this wierd armor value)
> 
> 
> I forgot to add this is 1.20.1 forge

Are you getting negative armour values fighting other mobs? if not disable born in chaos and see if that fixes it

**Comment by PapaDimitri** [comment]
The problem is that its very hard for me to get this again. I think it might be this lifestealer mob because i fought him twice and i got these values  after fighting him. I ll try again later tho

**Comment by Shadows-of-Fire** [comment]
Nothing in apoth modifies the base values of attributes, whatever is fiddling with your base values is something external.
