### ISSUE TITLE
Tetra modified bows can't be reforged

### ISSUE THREAD

**Issue by I-Nocturne-I** [Shadows-of-Fire/Apotheosis#1366]
If you modify a bow with tetra it won't allow you to insert it into the reforging table, if you reforge a regular bow and then modify it through tetra it'll remove any speed and other bonuses gained through reforging, it also removes any descriptions for bonuses on the bow like if it gives a speed boost on hit.

**Comment by Shadows-of-Fire** [comment]
That's because bows rely on doing `instanceof BowItem` for the default check, which tetra does not extend.  You can try using the adventure module config to set an override for the tetra item.
