### ISSUE TITLE
did the new update remove apotheosis' ability to work with create? if so, was it on purpose?

### ISSUE THREAD

**Issue by gabepikamole** [Shadows-of-Fire/Apotheosis#1368]
it suddenly doesn't interact with any create block whatsoever, whereas it did before. an example would be using the crushing wheel to crush the gear or gem i wouldn't use. no bug report or anything like that, it seems to be working just fine if not for that

**Comment by gabepikamole** [comment]
actually nevermind, sorry for posting =/. it basically doesn't work anymore for no reason or change i made, as i did not tinker with anything like that at all, so i don't know what happened and will look into it. again, sorry for bothering, last 1.20.1 update was quite some time ago and it did work on this version before. i don't know what could've happened.

**Comment by gabepikamole** [comment]
i'm so sorry. i did not have the mod i needed. i'm sorry

**Comment by Moses24713** [comment]
Sorry to ask this on a closed thread, but what was the name of the mod that adds compat?
