### ISSUE TITLE
Crash in Forge-28.2.1

### ISSUE THREAD

**Issue by Rensik** [Shadows-of-Fire/Apotheosis#137]
On load.
https://paste.gg/p/anonymous/08deb5411fd349a58f6be6bc3defba88

**Comment by Shadows-of-Fire** [comment]
Do you have any modules disabled?  It looks like the hell infusion enchantment doesnt exist, but the hellshelf still does.

**Comment by Rensik** [comment]
Only what's default. Haven't touched configs yet. Looking.

**Comment by Rensik** [comment]
All modules are enabled.

**Comment by Shadows-of-Fire** [comment]
Thats rather interesting.  I imagine something else is causing the error to happen, as it launches fine on it's own, and is in ATM4 with no known issues

**Comment by Rensik** [comment]
Possible. Leaving disabled for the moment. Will re-enable if updated before error found and test again.

**Comment by Rensik** [comment]
found the conflicting mod: betterTotem1.0-1.14.4

**Comment by Shadows-of-Fire** [comment]
Then it would be a bug in that mod, likely for invoking getSubItems before registry phase has ended.
