### ISSUE TITLE
Royal family gem pickaxe function bug

### ISSUE THREAD

**Issue by Rb5x** [Shadows-of-Fire/Apotheosis#1370]
Tooltip of royal family gem states copper ore can produce gold chunks 
This behavior does not happen instead iron ore produces gold chunks.
Playing on divnectar server in dimension of twilight first apotheosis version 1.20.1-7.4.0

**Comment by SiverDX** [comment]
sounds like a modpack issue

they changed the tag:
https://github.com/Shadows-of-Fire/Apotheosis/blob/fd032772692339e136d247daa6301c5657065bfe/src/main/resources/data/apotheosis/gems/overworld/royalty.json#L65-L68

but didn't update the description:
https://github.com/Shadows-of-Fire/Apotheosis/blob/fd032772692339e136d247daa6301c5657065bfe/src/main/resources/assets/apotheosis/lang/en_us.json#L345

**Comment by Rb5x** [comment]
Thank you.
