### ISSUE TITLE
[Suggestion] Attribute that scales life steal/overheal

### ISSUE THREAD

**Issue by Zortexxx619** [Shadows-of-Fire/Apotheosis#1371]
A new attribute (for Apothic Attributes) that scales the amount of HP an attacker gains via life steal/overheal when a target is attacked. The attack target's attribute value is used in the calculation.

For example, (calling it Healscale as a placeholder), Mob A has a Healscale attribute of 50%, and Mob B has a Life Steal attribute of 40%. Mob B attacks Mob A, dealing 10 HP worth of damage, then Mob B gains 10 * 0.4 * 0.5 = 2 HP due to Life Steal. Same deal with Overheal.

The idea is to allow different mobs to grant different amounts of HP when struck with a life stealing/overhealing weapon.

**Comment by Shadows-of-Fire** [comment]
I'm not really interested in adding such an attribute, it overcomplicates the logic of lifesteal (beyond where it already is now, being post-mitigation damage modified by healing received).
