### ISSUE TITLE
equipment name bug

### ISSUE THREAD

**Issue by NeoStarWonV** [Shadows-of-Fire/Apotheosis#1372]
I used the mod "Grindstone sharper tools" that the mod will sharpen the tools and gives it an additional name like『已打磨◆剩余』.But the Apotheosis's special equipment name will infinitely repeatedly extend.I don't know why.
before sharpen
![image](https://github.com/user-attachments/assets/dc75ff7e-c7da-4f95-bc7c-cae4ccba1467)
after sharpen
![image](https://github.com/user-attachments/assets/aa55959b-0ac0-4cc3-a148-fc52b5e46072)

**Comment by Shadows-of-Fire** [comment]
To effectively preserve the underlying item name, the apoth affix name additions are injected unusually. This mod is making a copy of the name with the additions, which then means the apoth name is re-appended to the NBT-encoded name.

In general, copying the item's current name and encoding it as NBT with some kind of addition is prone to all manner of faults (especially for dynamic items), the other mod should find a less fragile approach.
