### ISSUE TITLE
Life Leech balancing

### ISSUE THREAD

**Issue by NinthDesertDude** [Shadows-of-Fire/Apotheosis#1376]
1. Life leech + damaging/igniting nearby mobs is a little broken because you get a piece of _all_ the mobs damaged, instead of just the one that caused the others to get damaged.

2. Life leech is powerful enough on its own to punch out wardens without much care. If there's a way to target this in a datapack, I would be really happy to disable it or make it only appear with end-game loot.

Proposals:
- Make life leech mutually exclusive to attributes that harm by proximity, during affix generation
- Add config options to enable/disable specific affixes (easiest), or limit their intensity by dimension/structure/item

**Comment by meeprdib** [comment]
All affixes can be changed via datapack.

**Comment by meeprdib** [comment]
Filepath for Life Leech in particular:
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/resources/data/apotheosis/affixes/sword/attribute/vampiric.json

**Comment by NinthDesertDude** [comment]
Got it, I didn't expect it already to be in a datapack format. That makes it easy enough, tysm!

**Comment by meeprdib** [comment]
np ^_^
