### ISSUE TITLE
[Bug/Incompatible] Apotheosis interaction with mod called "spellblades and such" 

### ISSUE THREAD

**Issue by R4llik** [Shadows-of-Fire/Apotheosis#1377]
I recently played apotheosis on 1.20.1 without any problems, but when I added “spellblades and such” with the help of sinytra connector the game started crashing when trying to join any world. From what I've seen, the problems are related to LivingEntity and TickingEntity in this case player and armor rack. Normally I would report the problem on the sinytra connector site on github, but they recently switched to minecraft version 1.21.x, and 1.20.1 has been put under long-term support, which means they won't be fixing compatibility issues for that version from now on. There are 3 crash logs all are in some way diffrent from eachother.

https://mclo.gs/3V3wKKH

https://mclo.gs/XQnioes

https://mclo.gs/zYLVmGv

**Comment by R4llik** [comment]
Also a little update crash occurs only on apotheosis 7.4.0+. On apotheosis 7.3.5 everything works fine

**Comment by Shadows-of-Fire** [comment]
Compatibility is not offered for fabric-native mods loaded through connector.
