### ISSUE TITLE
HT's TreeChop Compatibility

### ISSUE THREAD

**Issue by komdreupau** [Shadows-of-Fire/Apotheosis#1378]
Hi absolutely love your mod, it has inspired me in my own datapack and modpack making adventure, but I can't play without this (much smaller, but still essential) one as well: [hammertater/treechop](https://github.com/hammertater/treechop). Your mod seems to disable this mods most vanilla enhanced way of chopping trees that don't just float around or fall awkwardly.

**Comment by Shadows-of-Fire** [comment]
Apoth doesn't have any interactions with trees or arbitrary block breaks in a way that I think would break this. Were you testing in an isolated instance?

Regardless, closing, this is better tracked on treechop's issue tracker.
