### ISSUE TITLE
[CRASH] Apotheosis/Placebo crashes the game when opening creative menu

### ISSUE THREAD

**Issue by BENZOOgataga** [Shadows-of-Fire/Apotheosis#1380]
Hi, I asked for support on the Discord regarding my crash report and I got no answers so I'm putting it here so that maybe it gets fixed one day...

Server runs on Forge, though I tested with NeoForge and it does the same crash report : 
```
net.minecraftforge.fml.ModLoadingException: Placebo (placebo) encountered an error during the done event phase
§7java.lang.NullPointerException: Registry Object not present: apotheosis:ender_lead
```

With some searching, there is no item named "Ender Lead" in the Apotheosis mod.

Crash report for neoforge:
[crash-2024-10-26_18.03.25-client.txt](https://github.com/user-attachments/files/17531436/crash-2024-10-26_18.03.25-client.txt)
Crash report for forge :
[crash-2024-10-26_16.20.14-client.txt](https://github.com/user-attachments/files/17531470/crash-2024-10-26_16.20.14-client.txt)

Edit : 
Forgot to mention that the server is under 1.20.1 with Forge 47.3.0 (I tested with NeoForge after getting the crash report, which is why I also added another crash report using NeoForge, in case something changes between forge and neoforge)
Here are my client mods : 
[client_mods.txt](https://github.com/user-attachments/files/17531455/client_mods.txt)
Here are my server mods : 
[server_mods.txt](https://github.com/user-attachments/files/17531461/server_mods.txt)

It is really sad because I really wanted to add Apotheosis to my server, it's a heckin' good mod but I can't open creative menu from time to time when I need to just because of Placebo, thanks for considering my bug report!

**Comment by BENZOOgataga** [comment]
After doing a bit more research and thanks to a friend of mine, the issue is apprently coming to deactivating the garden module from Apotheosis, which actually removes an item called Ender Lead. With this done, when you restart the server, Placebo doesn't find the item called ender lead because Apotheosis Garden Module is deactivated.

Suggestion: Maybe adding a check within Placebo, that checks if the item's module is deactivated before going to search it when opening creative menu, would fix this issue.

**Comment by meeprdib** [comment]
Apotheosis configs must match between client and server, that's just how it is

**Comment by BENZOOgataga** [comment]
> Apotheosis configs must match between client and server, that's just how it is

Didn't know that at first, would be great to mention this on the CurseForge page and such for modpack makers. Thanks for the reply though!

**Comment by SiverDX** [comment]
> > Apotheosis configs must match between client and server, that's just how it is
> 
> Didn't know that at first, would be great to mention this on the CurseForge page and such for modpack makers. Thanks for the reply though!

just to be clear that is the case for all common configs (i.e. for all mods which use it) since it's a (neo)forge feature

**Comment by Shadows-of-Fire** [comment]
Apoth doesn't actually use the forge config system, since it isn't available at startup when the module loading needs to be decided.
