### ISSUE TITLE
[Custom DataPack] Crash when loading loot

### ISSUE THREAD

**Issue by SojaIntegral** [Shadows-of-Fire/Apotheosis#1381]
**Explanation:** 
- I have changed gems, affixes and rarities;
- Individually, none of the changed bonuses or numbers cause any issues, as I have tested them individually many many times;
- Mobs wearing Apotheosis gear is disabled in the DataPack;
- When walking around, apotheosis will randomly cause a crash (assumed it is when trying to generate loot with affixes).

**Crash logs:**
- [crash-2024-10-27_03.50.12-server.txt](https://github.com/user-attachments/files/17533048/crash-2024-10-27_03.50.12-server.txt)
- [crash-2024-10-27_03.55.31-server.txt](https://github.com/user-attachments/files/17533049/crash-2024-10-27_03.55.31-server.txt)

**There are absolutely no issues when not using the datapack and I have played for hours without it**
**This is a custom modpack**

**Comment by SojaIntegral** [comment]
**DataPack:**
- [apoth.zip](https://github.com/user-attachments/files/17533057/apoth.zip)

(I don't know how useful this might be)

**Comment by Shadows-of-Fire** [comment]
You've replaced the festive affix with an affix of a different type (executing), even though you've kept the same name. Thus, the crash. Don't do that.

**Comment by SojaIntegral** [comment]
Lmao sorry XD
That was very dumb from me :3

**Comment by meeprdib** [comment]
It's better to remove affixes you don't like and then create new ones in another namespace other than the Apotheosis one instead of replacing ones
