### ISSUE TITLE
Stargate/ Apotheosis/ JEI compat issue?

### ISSUE THREAD

**Issue by border999** [Shadows-of-Fire/Apotheosis#1383]
https://github.com/Povstalec/StargateJourney/issues/149
posting in both main mods githubs so it can be looked at from both sides.

**Comment by Shadows-of-Fire** [comment]
This appears to be purely a stargate issue. Not sure how they're missing the implementation of a default interface from one of the forge extension interfaces, but it's certainly a them problem.
