### ISSUE TITLE
How to get more dragon eggs for spawner modifier?

### ISSUE THREAD

**Issue by adamk33n3r** [Shadows-of-Fire/Apotheosis#1384]
Is it intended that you are only able to make one of these spawners? You can only get 1 egg from the first time you kill the ender dragon.

**Comment by MegaHakkero** [comment]
https://minecraft.wiki/w/Ender_Dragon#Re-summoning

**Comment by meeprdib** [comment]
In vanilla Minecraft / Apotheosis, you can only get one spawn egg per world. However, you can make a datapack to change the modifier to need a different material. There's also mods/datapacks out there that make it to the ender dragon spawns an egg each time it is killed.

**Comment by adamk33n3r** [comment]
Thanks for the info, I'll look into it!
