### ISSUE TITLE
[Custom datapack] [Question] I tried to add a new boss, but it didn't work out =(

### ISSUE THREAD

**Issue by Dalarin1** [Shadows-of-Fire/Apotheosis#1386]
I tried to add a new boss (Fire dragon from _Ice and Fire_), but he doesn't want to spawn at all. What am I doing wrong?
[fire_dragon.json](https://github.com/user-attachments/files/17690845/fire_dragon.json)

**Comment by Shadows-of-Fire** [comment]
This question is more appropriately suited for the [discord server](https://discord.shadowsoffire.dev)
