### ISSUE TITLE
[1.20.1] Apotheosis Spawner Modifiers Do Not Show Up In EMI (JEI alternative)

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [Shadows-of-Fire/Apotheosis#1387]
Pressing "U" while hovering over a Spawner dose not show Modifiers either.
Apotheosis-1.20.1-7.4.3
Emi-1.1.18+1.20.1+forge

**Comment by Shadows-of-Fire** [comment]
EMI is not a supported platform.  You can install JEI alongside EMI to have EMI use JEI's data as a backend.
