### ISSUE TITLE
[Crash][1.12.2]Splitting enchantments problem maybe

### ISSUE THREAD

**Issue by xANoyU** [Shadows-of-Fire/Apotheosis#1388]
look like this issues? (https://github.com/Shadows-of-Fire/Apotheosis/issues/276)

Server Version: 1.12.2
Mod Version: Apotheosis-1.12.2-1.12.5
Crash Log: https://paste.ubuntu.com/p/qQV3yPynBJ/

can you fix it, please😫

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported
