### ISSUE TITLE
Re-equipping armor multiple times causes the effects to stack

### ISSUE THREAD

**Issue by Coolstuf1** [Shadows-of-Fire/Apotheosis#1390]
I found a bug that only works on servers for some reason (I am using ketting server 1.20.1) 
I have tested this in singleplayer and it does not work, but I also tested multiplayer with no plugins but it still happens

It seems to only work when you apply gems to an item, then spam re equip it.

Video of what happens:
https://github.com/user-attachments/assets/f3e49a44-5cec-4b68-9173-b6386bf5fce2

**Comment by Shadows-of-Fire** [comment]
This is probably an issue with the forge/spigot hybrid server you're using. You can see if they would like to investigate it, but I will not.
