### ISSUE TITLE
(1.20.1) Other mobs have critical hit chances.

### ISSUE THREAD

**Issue by SuperTiru** [Shadows-of-Fire/Apotheosis#1391]
I tested this in version 1.20.1 with only the Apotheosis mod installed and confirmed that critical hits are still triggered by other mobs. To verify this, I created a simple mod that outputs the damage I take to the chat whenever I'm attacked. When I was attacked by silverfish, I observed abnormal damage values like 1.6 and 1.4, accompanied by the Apotheosis critical hit effect.

![image](https://github.com/user-attachments/assets/96aed0dd-d2c2-4bb3-8dbe-067621d6ce7e)

**Comment by Shadows-of-Fire** [comment]
That's not a bug, the default critical hit chance is 5% for all entities.

**Comment by SuperTiru** [comment]
Can I Disabled it?
