### ISSUE TITLE
Changes to Cyclic spells not reflected in enchantments.cfg

### ISSUE THREAD

**Issue by OldGamerBroad** [Shadows-of-Fire/Apotheosis#1393]
FROM Cyclic release Cyclic-1.20.1-1.12.13.jar - Oct. 2, 2024

"Block Reach enchantment now has max level 5 to give players more control of how far the reach boost is increased; so levels I through V are now available. Since players normally have 5 blocks of reach distance: level I reaches 8, II reaches 10, III reaches 12, IV reaches 14, and V reaches 16 blocks (+4 for anything beyond with something like apotheosis)"

enchantments.cfg currently freezes the Max Level at 1 which causes the changes to be unavailable to the user.  The original Block Reach had a range of 16 blocks at level 1, so this is a huge nerf to the spell if it's not corrected.

Below is the change I made to the "cyclic:reach" section enchantments.cfg which allows the changes Cyclic made to work:

"cyclic:reach" {
    # If this enchantment is obtainable via enchanting and enchanted loot items.
    # Default: true
    B:Discoverable=true

    # If enchanted books of this enchantment are available via loot sources.
    # Default: true
    B:Lootable=true

    # The max level of this enchantment - originally 5.
    # Default: 1; Range: [1 ~ 127]
    I:"Max Level"=5

    # The max level of this enchantment available from loot sources.
    # Default: 1; Range: [1 ~ 127]
    I:"Max Loot Level"=5
    
    *********************************
    Thanks so much for a great mod!

**Comment by Shadows-of-Fire** [comment]
The config is fixed at the time of generation, it can't determine when a mod changes the underlying default level and re-adjust itself on the fly.  You editing your existing config manually is the correct fix here.
