### ISSUE TITLE
disable shift showing enchantment id with advance tooltips

### ISSUE THREAD

**Issue by Aceplante** [Shadows-of-Fire/Apotheosis#1394]
I am trying to hide enchantments forge 1.20.1
![image](https://github.com/user-attachments/assets/f5c7e54b-4954-4dd2-8f23-832516af9c3e)
unfortunately, pressing shift shows the exact id. I have a feeling it is your mod
![image](https://github.com/user-attachments/assets/2817f24b-026f-42d2-87ab-61cc1156f8d8)

I found a mod to disable the advance tooltip info keybind, but that is only a bandaid fix

**Comment by Shadows-of-Fire** [comment]
This is not an apotheosis feature.
