### ISSUE TITLE
[Bug] AnvilCraft and Apotheosis cannot run together.

### ISSUE THREAD

**Issue by Lintern** [Shadows-of-Fire/Apotheosis#1395]
### OS Version
Windows
### Minecraft Version Details
1.20.1, Forge47.3.0
### Mod version
- [AnvilCraft](https://github.com/Anvil-Dev/AnvilCraft/issues/1178) version：1.4.1+pre-release.2+build.767
- Apotheosis version：7.4.3
#### Both mods modify the same method:

- The Mixin from [AnvilCraft](https://github.com/Anvil-Dev/AnvilCraft/issues/1178) fails when injecting into the getAvailableEnchantmentResults method of EnchantmentHelper. The reason is that the Mixin from Apotheosis modifies this method with a higher priority ("merged"), causing changes to the bytecode structure of the method.
 
#### Injection point failure:

- The injection in [AnvilCraft](https://github.com/Anvil-Dev/AnvilCraft/issues/1178) expects the original Minecraft EnchantmentHelper method signature, not the modified version altered by Apotheosis. When Apotheosis modifies this method first, AnvilCraft's injection logic may become incompatible with the altered bytecode.

### Crash reports:
[crash-2024-11-17_12.35.08-server.txt](https://github.com/user-attachments/files/17788873/crash-2024-11-17_12.35.08-server.txt)

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Shadows-of-Fire** [comment]
Based on the linked issue, this was fixed on their end.
