### ISSUE TITLE
[Request] Un-Hardcode Rarity Color

### ISSUE THREAD

**Issue by NimbusIzayoi** [Shadows-of-Fire/Apotheosis#1396]
Currently we cannot recolor an Apoth enchanted item as the rarity color overrides it.
I would like to be able to do this.
Ty.

**Comment by meeprdib** [comment]
What are you trying to use to recolor the item?

**Comment by NimbusIzayoi** [comment]
/data merge entity @e[type=item,limit=1,sort=nearest] {Item:{tag:{display:{Name:'{"text":"The Morgan","italic":false,"color":"#C11101"}'}}}}

**Comment by NimbusIzayoi** [comment]
It wasn't working before but it did now... I'll see if we can figure out what was going on.

**Comment by NimbusIzayoi** [comment]
Might be because of the NBT mod we installed "In-game NBTEdit Reborn"
