### ISSUE TITLE
How to Remove Spezific Entchant ? 

### ISSUE THREAD

**Issue by HeederaHelix** [Shadows-of-Fire/Apotheosis#1398]
HEy, i wanna remove "knowledge of Ages" entirely from the mod for a server. its way to powerfull, kill one mob be level 20+ is there a way or is it hopeless and i need to take it like it is ?

**Comment by meeprdib** [comment]
Check the enchantment.cfg file in the config folder for Apotheosis, you can remove methods of obtaining enchants there.
