### ISSUE TITLE
Crashed in the Erebus with this mod installed

### ISSUE THREAD

**Issue by Cazadorsniper** [Shadows-of-Fire/Apotheosis#14]
https://pastebin.com/2TrrMdTZ

I removed the mod and was able to move freely in the Erebus.

**Comment by Shadows-of-Fire** [comment]
This is similar to the issue that was happening with AoA (direct mob spawner tile creation)
@vadis365 Could you change [this line](https://github.com/vadis365/TheErebus/blob/mc1.12/src/main/java/erebus/blocks/BlockSpawner.java#L23) to 
`TileEntityMobSpawner tile = 
(TileEntityMobSpawner) Blocks.MOB_SPAWNER.createTileEntity(world, getDefaultState());`

**Comment by Shadows-of-Fire** [comment]
Vadis mentioned he would be able to put the fix in, so hopefully that gets resolved quickly.

**Comment by Shadows-of-Fire** [comment]
Closed as of https://github.com/vadis365/TheErebus/commit/3b43aa404e8930954b585098d569463d70d3d007

**Comment by vadis365** [comment]
Nearly. One of the other custom spawners was missed, so this is still an issue with the Fly Spawner specifically. I'll get it patched to work with Apotheosis later as a sort of 'luke warm fix' later.
