### ISSUE TITLE
Hellshelf Bookshelf Tags

### ISSUE THREAD

**Issue by MeinKraft** [Shadows-of-Fire/Apotheosis#140]
Apotheosis 1.14.4/1.15.2

Could you make the Hellshelf recipe use forge:bookshelves tag?  this would allow compatibility with the bookshelves from the ILikeWood mod

ILikeWood tags them as ILikeWood:Bookshelves, but I change this using a datapack, but I cant change the Hellshelf recipe

Thank you

**Comment by Shadows-of-Fire** [comment]
1.14 is not under development, and 1.15 already uses the tags.  Additionally, you can change the recipe, a json will override the inbuilt one.
