### ISSUE TITLE
[Suggestion] Any plans to add a mod to Modrinth?

### ISSUE THREAD

**Issue by Alter73** [Shadows-of-Fire/Apotheosis#1401]
Hi! I just make quite a lot of modpacks in the Modrinth launcher and a lot of mods have moved there. It is also possible because the service is developed only for Minecraft. It would be much more convenient if Apotheosis was also in Modrinth, otherwise I have to download it separately for each modpack and check for its updates, but this is very inconvenient when creating modpacks.

**Comment by meeprdib** [comment]
No.
From last I've heard from Shadows, Modrinth is both too unstable and the setup would be too much work for what it'd give in return. 
Personally, I'd recommend Prism launcher as it has both CF and MR support for making modpacks, though 99.9% of mods can be found on CF anyway.

**Comment by Alter73** [comment]
It's a pity. I don't know what instability you're talking about, all my modpacks work fine. Especially in the launcher, I like the user-friendly design, ease of use and a good mod update system. After all, I make modpacks not only for myself, but also put them on Modrinth, because it is much more convenient to make modpacks on it, for this reason, Prism is not quite suitable for me. But CurseForge lacks a lot of this, plus it's very bulky compared to Modrinth. Anyway, thanks for the reply.

**Comment by RoyalReject** [comment]
If anything lack of mods on modrinth is an issue no? Majority of users still use curseforge so it's not worth the headache of dealing with 2 pages. I am not sure what you think is lacking from curseforge as it's app is not perfect but has gotten better over the last few years. Not sure what you consider bulky but the apps probably have the same system footprint I will test that later to verify.

**Comment by meeprdib** [comment]
No problem! The instability I was referring to was referencing the site itself, I feel like it's too financially unstable to sustain itself long term. The launcher itself is lovely though.

**Comment by DavidSiuA** [comment]
i also want to move to modrith and also neoforge. A lot of new mods have been only publishing on modrith and also a lot of forge mods have been migrating to neo forge and thanks to that i can now play with some forge mods with distant horizons + shaders with forge mods, now the last piece left is the best minecraft mod: apotheosis

**Comment by meeprdib** [comment]
What mods have only been publishing to Modrinth?
