### ISSUE TITLE
1.20.1 C2ME + Apotheosis Mixin (owner: Render thread, current: Thread-13)

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1402]
When adding Apotheosis, errors occur with threads.

Minecraft 1.20.1 Forge 47.3.12

1. Zeta-1.0-24.jar
2. Apotheosis-1.20.1-7.4.3.jar
3. ApothicAttributes-1.20.1-1.3.7.jar
4. c2me-fabric-mc1.20.1-0.2.0+alpha.11.13.jar
5. Connector-1.0.0-beta.46+1.20.1.jar
6. emi-1.1.18+1.20.1+forge.jar
7. fabric-api-0.92.2+1.11.8+1.20.1.jar
8. Patchouli-1.20.1-84-FORGE.jar
9. Placebo-1.20.1-8.6.2.jar
10. Quark-4.0-460.jar

Error Log:
https://gist.github.com/Krimatoria/edc8b55646c32fb46a18e652000e679e

**Comment by meeprdib** [comment]
Connector is not supported

**Comment by meeprdib** [comment]
I'd tell you to report the issue to connector, but they're focusing on 1.21 afaik, so you're probably SoL.
Multithreading worldgen is highly invasive anyway, so I suspect it'd be on their end to resolve issues.

**Comment by coco875** [comment]
the issue you have look like related to https://github.com/Shadows-of-Fire/Apothic-Enchanting/issues/6#issuecomment-2377397419 so I think it's more emi who need to change then connector of apotheosis

**Comment by Krimatoria** [comment]
They wrote that the problem is on the side of Apotheosis
https://github.com/emilyploszaj/emi/issues/837#issuecomment-2614698167
