### ISSUE TITLE
FORGE Apotheosis-1.20.1-7.4.3 CAUSING GAME TO CRASH. MISSING REGISTRY ITEM APOTHEOSIS:VIAL_OF_DESTRUCTION

### ISSUE THREAD

**Issue by Minebrah** [Shadows-of-Fire/Apotheosis#1403]
[Worker-Main-6/ERROR] [net.minecraftforge.common.ForgeHooks/]: Couldn't parse element loot_tables:apotheotic_additions:chests/born_in_chaos_spawner
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: apotheosis:vial_of_expulsion

THE GAME HARD CRSHES TO HOME SCREEN AND NO CRASH REPORT IS GIVEN SO I PROVIDED MY LATEST.LOG INSTEAD.

LINK TO LATEST LOG SHOWING WHAT HAPPENED BEFORE CRASH:

https://gist.github.com/Minebrah/d7f5e2ec1b53f228d56454d791a8bc48

[https://gist.github.com/Minebrah/d7f5e2ec1b53f228d56454d791a8bc48](url)

SOME MOD DEVELOPERS HELPED ME IDENTIFY THE PROBLEM:

 [https://github.com/iron431/irons-spells-n-spellbooks/issues/684](url)

THANKS AGAIN FOR LOOKING INTO IT

**Comment by meeprdib** [comment]
Apotheotic Additions is referencing an item in a loot table which does not exist. Report this issue to them.

**Comment by Minebrah** [comment]
Thank you so much for the quick response. I looked into it and it looks like the mod developer is not very reliable when it comes to fixing bugs. So I will just uninstall that mod then. Other than that I have had some weird stuff pop up in chat concerning this mod. But it might just be due to addons as well like:

[02Dec2024 10:21:43.632] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affixes file apotheosis_ascended:gun/attribute/kick_reduction.
[02Dec2024 10:21:43.632] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception: 

[02Dec2024 10:21:43.683] [Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affixes file apotheosis_modern_ragnarok:magnum.
[02Dec2024 10:21:43.683] [Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception: 
java.lang.RuntimeException: Failure when parsing a affixes. Unrecognized type: apotheosis_modern_ragnarok:damage_bonus

[02Dec2024 10:21:43.689] [Render thread/INFO] [Apotheosis : Adventure/]: Registered 247 affixes.
[02Dec2024 10:21:43.697] [Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity apotheotic_additions:artifact for category apotheosis_modern_ragnarok:bolt_actionRequired: 2; Provided: 0

Other than that there are no errors being shown to be directly caused by this mod? They are all because of the addons? If so then I will redirect the bug reports to the appropriate mod authors.

**Comment by meeprdib** [comment]
You're talking to the Apotheosis Ascended dev rn lol
Those logs are just errors because you don't have Scorched Guns installed, you can safely ignore them.
Don't know about the "modern ragnorok" mod though.

**Comment by Minebrah** [comment]
Hey Dev thank you for lending me a hand with this. Okay so Apotheosis and Ascended are okay I just need to uninstall Additions and possibly make a new bug report for the Ragnarok ones. Is that it? The errors thrown by your mod don't affect performance then, its just shows it supports a mod I don't have installed?

**Comment by meeprdib** [comment]
Yeah, the errors thrown by ragnorok don't seem bad either, but can't hurt to ask, I guess.

**Comment by Minebrah** [comment]
Awesome thank you. Also thanks for the cool mod appreciate that.

**Comment by meeprdib** [comment]
thanks for the compliments ^_^
