### ISSUE TITLE
Questions, new to mod configuring 

### ISSUE THREAD

**Issue by Mobuid** [Shadows-of-Fire/Apotheosis#1404]
Hi, apologies if you get these questions a lot, I absolutely adore your adventure module for apotheosis, I wanna know if there is a way to both, remove the current health % damage affix from the pool and lowering towers spawn rates. Currently making a modpack for a Christmas break playthrough with friends, but i just wanna make it harder to get as strong with your mod, if there's no way i completely understand, also i don't know whats the proper place to ask this question, so apologies if this is the wrong place

**Comment by meeprdib** [comment]
You can make a datapack to configure / remove certain affixes. An example datapack can be found in Shadow's discord, if you're interested.

**Comment by Mobuid** [comment]
I am very much so, i have zero knowledge on how to make data packs or anything, where may i find the discord?

**Comment by meeprdib** [comment]
https://discord.gg/shadows-mods-613010559532531713
