### ISSUE TITLE
texture bug

### ISSUE THREAD

**Issue by ksaodied** [Shadows-of-Fire/Apotheosis#1406]
hello, after connecting a gem and a weapon (no matter what), the texture of the weapon in the hand becomes the texture of a gem, please help
![2024-12-11_14 51 37](https://github.com/user-attachments/assets/b241a289-604f-4a65-a763-59c9d6d8e369)

**Comment by ksaodied** [comment]
> hello, after connecting a gem and a weapon (no matter what), the texture of the weapon in the hand becomes the texture of a gem, please help ![2024-12-11_14 51 37](https://private-user-images.githubusercontent.com/162157083/394727928-b241a289-604f-4a65-a763-59c9d6d8e369.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTgzNDQsIm5iZiI6MTczMzkxODA0NCwicGF0aCI6Ii8xNjIxNTcwODMvMzk0NzI3OTI4LWIyNDFhMjg5LTYwNGYtNGE2NS1hNzYzLTU5YzlkNmQ4ZTM2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxMTU0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTE0YzgyYjU3MDg1OGY4MWE5NWJlOTczZjc0ZWE2MzQ0M2FmNWEzMGQ2MTU5NmJmMTI0ZDg4YmI4MzFmNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y-74W-b1r6RrqNhzyC2wcuN_E2pKQBOytCh_eVgvOg8)


I forgot to say that I connect this on the table from the Transmog mod

**Comment by RoyalReject** [comment]
That seems to be the whole point of the Transmog mod. Don't use their table, socket gems in the smiting table. If that still causes issues report it to Transmog

**Comment by ksaodied** [comment]
> That seems to be the whole point of the Transmog mod. Don't use their table, socket gems in the smiting table. If that still causes issues report it to Transmog

i cant do it on smiting table D:
![Uploading 2024-12-11_15.15.43.png…]()

**Comment by RoyalReject** [comment]
That image is not loading for me but does your item have an available socket?

**Comment by ksaodied** [comment]
> That image is not loading for me but does your item have an available socket?

yea, but i just need to write to Transmog github, thanks for help bro!!
