### ISSUE TITLE
enchantment bug

### ISSUE THREAD

**Issue by THEBEARDKID** [Shadows-of-Fire/Apotheosis#1408]
when i create any tool it comes with unbreaking 3 and fortune 3 im new to modding and cannot find a the culprit

**Comment by RoyalReject** [comment]
If you could please share your logs or if using curseforge an export of your pack tutorial [here](https://support.curseforge.com/en/support/solutions/articles/9000198501-exporting-and-importing-modpacks)

**Comment by Shadows-of-Fire** [comment]
Apotheosis does not contain any functionality to modify freshly crafted items in that manner.
