### ISSUE TITLE
Prism shaped spider web error

### ISSUE THREAD

**Issue by vhdx** [Shadows-of-Fire/Apotheosis#1409]
One or more Prismatic Cobwebs will collapse when removing negative enchantments on an anvil minecraft

**Comment by Shadows-of-Fire** [comment]
If you have a crash you will need to provide a crash report. You can reopen this issue if/when you provide one.

**Comment by vhdx** [comment]
Anvils: 64 or more Prismatic Cobweb: When removing an enchantment book negative enchantment, it crashes, does not respond, and cannot provide a crash report
![PixPin_2025-01-10_22-11-57](https://github.com/user-attachments/assets/7a38a7bf-ea09-44e2-bb3e-73b5d1f1fed6)
![PixPin_2025-01-10_22-31-54](https://github.com/user-attachments/assets/4039514b-8ac0-4326-ac8e-a3a65a7f9949)

**Comment by vhdx** [comment]
Anvils: 64 or more Prismatic Cobweb: When removing an enchantment book negative enchantment, it crashes, does not respond, and cannot provide a crash report
![PixPin_2025-01-10_22-31-54](https://github.com/user-attachments/assets/07abbc95-0c3f-4a42-a097-1b40f0089cf0)
![PixPin_2025-01-10_22-11-57](https://github.com/user-attachments/assets/411d2920-6e1a-455a-95a9-fcf83eda4830)

**Comment by Shadows-of-Fire** [comment]
I think you have another mod causing this bug. The prismatic cobweb does not even offer any behavior when in the left slot. It only works in the right slot (ref: [here](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.20/src/main/java/dev/shadowsoffire/apotheosis/ench/EnchModuleEvents.java#L45))

**Comment by vhdx** [comment]
3 mods
![PixPin_2025-01-11_22-09-40](https://github.com/user-attachments/assets/15f17c4e-4a4d-49f7-85b8-0fde58761a24)

**Comment by vhdx** [comment]
Even 3 mods can't handle this bug
