### ISSUE TITLE
Incompatibility between Apotheosis and Quark's "Right Click to Add to Shulker Box" feature.

### ISSUE THREAD

**Issue by ridjack** [Shadows-of-Fire/Apotheosis#141]
As title; when using Apotheosis and Quark, Quark's feature stops functioning.

Full details over on Quark's issue: Vazkii/Quark#1663

**Comment by Shadows-of-Fire** [comment]
Apotheosis does not do anything relating to any code paths regarding this issue, no modifications to shulker boxes nor guis, so I don't think this issue is being caused by me.
