### ISSUE TITLE
how do u apply gems (i forgot)

### ISSUE THREAD

**Issue by VaporeonScripts** [Shadows-of-Fire/Apotheosis#1411]
I'd like to know how you applied gems, as I've completely forgotten.

**Comment by meeprdib** [comment]
Make sure the piece of gear has sockets available (you can get sockets through reforging), and then use a Smithing Table to apply gems to the gear.

**Comment by meeprdib** [comment]
There's also the Chronicles of Shadows which you can get if you have Patchouli installed, which details every part of this mod.

**Comment by VaporeonScripts** [comment]
oh yeah, that was why it wasnt working, i remember i needed smithing table , ty
