### ISSUE TITLE
The nether and end use the bed will not explode properly

### ISSUE THREAD

**Issue by 19300000** [Shadows-of-Fire/Apotheosis#1412]
minecraft version:1.12.2
mod version:1.12.5
forge version:14.23.5.2860
Running this mod alone found that the bed doesn't explode in the above two worlds, and the config file doesn't see the switch about this event?
It's so strange that no one has ever found out about the problem

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported

**Comment by 19300000** [comment]
> 1.12 is not supported

Ha, the classic answer

**Comment by VincyChannel** [comment]
I've found a fix for this, but the question is, why you change the blockBed Class and add to it a fakeExplosion? @Shadows-of-Fire

**Comment by VincyChannel** [comment]
Exactly this ASM Transformer class for the vanilla bed: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.12/src/main/java/shadows/util/BedTransformer.java
