### ISSUE TITLE
[1.15.2] Server crash on load - Exception in server tick loop

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Apotheosis#142]
Crash log-
java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that does not map to a registry. Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : shadows.apotheosis.deadly.loot.affix.Affix at shadows.apotheosis.deadly.loot.affix.Affixes.FIRE_DAMAGE

https://gist.github.com/ProsperCraft/e42aa695e325d00853139e8ef25b6f36
Apotheosis-1.15.2-3.0.6.jar

**Comment by Shadows-of-Fire** [comment]
Must be caused by another mod causing classloading issues
