### ISSUE TITLE
Tier augments still not applied in some vanilla methods which spawn mobs

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Apotheosis#1420]
The augments from the current world tier are not applied when mobs are spawned by the following vanilla methods:
* Generating chunks
* Generating structures containing mobs
* Breeding
* Throwing eggs
* Building iron or snow golems

In all five cases, `apotheosis:tier_augments_applied` is `1b` in the entity's NBT data, but no tier augments are applied.

However, the same mobs spawned naturally, from a spawner, or from the `/summon` command do get the tier augments applied.

Mod list:
```
Apotheosis-1.21.1-8.0.1
ApothicAttributes-1.21.1-2.5.0
ApothicEnchanting-1.21.1-1.2.5
ApothicSpawners-1.21.1-1.1.1
cloth-config-15.0.140-neoforge
emi_enchanting-0.1.2+1.21+neoforge
emi-1.1.18+1.21.1+neoforge
NoChatReports-NEOFORGE-1.21.1-v2.9.1
Patchouli-1.21-87-NEOFORGE
Placebo-1.21.1-9.6.1
```

**Comment by Shadows-of-Fire** [comment]
Looks like the check is ignoring creative players when considering options for applying the tier augments, and it still marks the entity when the augments cannot be applied due to no available players.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/commit/d48d65cc6fb932eb05f9b7c2fba27b8755692f80
