### ISSUE TITLE
New NBT data

### ISSUE THREAD

**Issue by Malty44** [Shadows-of-Fire/Apotheosis#1422]
Hi, I would like to know what the new NBT data for the apotheosis armor/tool drops are for ATM 10, cuz the tags from ATM 9 do not work when I try to filter items. Thank you

**Comment by undeci16** [comment]
{"apotheosis:rarity":"apotheosis:common"}
{"apotheosis:rarity":"apotheosis:uncommon"}
{"apotheosis:rarity":"apotheosis:rare"}
{"apotheosis:rarity":"apotheosis:epic"}
{"apotheosis:rarity":"apotheosis:mythic"}

Gems are 
{"apotheosis:purity":"cracked"}
{"apotheosis:purity":"chipped"}
{"apotheosis:purity":"normal"}
{"apotheosis:purity":"flawed"}
{"apotheosis:purity":"flawless"}
{"apotheosis:purity":"perfect"}

**Comment by Malty44** [comment]
Thank you very much. It worked like a charm.
