### ISSUE TITLE
Affixs not spawning (All The Mods 10)

### ISSUE THREAD

**Issue by StillAlive1804** [Shadows-of-Fire/Apotheosis#1429]
I just started a server using All the mods 10 modpack on Akliz Game server hosting

I have played with the Apotheosis mod before on All the mods 9 and it worked great, 
However, this time, 
-The only bosses that are spawning are specifically the uncommon ones (Green), 
-The only gems I am finding are either cracked or chipped
-The only affix items I get from mob drops and chest are common, uncommon, and rare (Gray, Green, and blue)
-I have not once seen a epic or mythic affix

On the server hosting platform
![ERROR](https://github.com/user-attachments/assets/438e45d9-0af3-4b4e-a8fd-d3df739b7558)

We have quite a bit of progress already in the modpack, I am hoping to be able to find a way to fix it without affecting the current playthrough

I really like this mod and I want to get it to work, I've tried finding fixes, but, a lot of the forums I check out make no sense to me, I'm just a player so I don't understand a lot of this stuff so all the help is much appreciated

**Comment by YocyCraft** [comment]
Apotheosis added World Tier system in 1.21.  [World Tier](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.21/changelog.md#features)
You need to unlock higher World Tier to get items with higher rarity.

**Comment by number65259** [comment]
The log spam is a separate issue from everything else you reported.

ATM 10 issue open to remedy minecraft:air being considered for affixes: https://github.com/AllTheMods/ATM-10/issues/1597

**Comment by StillAlive1804** [comment]
> Apotheosis added World Tier system in 1.21. [World Tier](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.21/changelog.md#features) You need to unlock higher World Tier to get items with higher rarity.

Yeah, that's my bad, I figured since I'd been everywhere (Overworld, nether, end) that it must have been an issue: thats on me. Thank you ur the best
