### ISSUE TITLE
Crash Error: java.lang.NullPointerException: null key in entry: null=10

### ISSUE THREAD

**Issue by emanuele246gi** [Shadows-of-Fire/Apotheosis#143]
Hi I have this problem while starting the game:
https://pastebin.com/DLVJAKze

**Comment by SDUBZ** [comment]
same problem here 
Forge: 1.15.2-31.1.18
apth: Apotheosis-1.15.2-3.0.6
placebo: Placebo-1.15.2-3.0.2

Seems to be your item
ItemHellBookshelf.func_150895_a(ItemHellBookshelf.java:47)

**Comment by emanuele246gi** [comment]
Yeah but I would like to know a way to solve this issue, I mean I know that item is the cause but I don't know what to do

**Comment by Shadows-of-Fire** [comment]
This is being caused by another mod invoking getSubItems earlier than it should be, but the trace doesn't provide what mod.  The debug.log file might

**Comment by SDUBZ** [comment]
im thinking it could be flux

**Comment by emanuele246gi** [comment]
But I always had these two mods since the beginning of this modpack! How could that be possible?

**Comment by Shadows-of-Fire** [comment]
Loading is multithreaded, when it's happening (and it may not be that mod) could be a result of load order weirdness

**Comment by emanuele246gi** [comment]
Are you kidding me, mr mod? Shadow of Fire, I were right... It was because of Flux, that's ridiculous... Anyway, good for me now :D

**Comment by emanuele246gi** [comment]
At least the mod still works but only if I downgrade to the previous version of Flux, because I saw that I'm not the only who have this issue
