### ISSUE TITLE
[Feature Request] [1.15.2] Curios compatibility

### ISSUE THREAD

**Issue by Dragnier** [Shadows-of-Fire/Apotheosis#144]
In 1.15.2, things like the Charm of Invisibility would be nice to have Curios compatibility so it could be equipped in a charm slot if both mods are loaded together but still work like normal if they aren't.

**Comment by mjlmjl888** [comment]
There is also baubles now too! So that would be nice to be compatible with too.

**Comment by Shadows-of-Fire** [comment]
Oh, yeah, this is a thing now.
