### ISSUE TITLE
Hell Shelf causes crash on latest version at start up

### ISSUE THREAD

**Issue by PineapplePunk** [Shadows-of-Fire/Apotheosis#146]
java.lang.NullPointerException: null key in entry: null=10
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:73) ~[guava-21.0.jar:?] {}
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:120) ~[guava-21.0.jar:?] {}
	at shadows.apotheosis.ench.objects.ItemHellBookshelf.func_150895_a(ItemHellBookshelf.java:47) ~[?:3.0.7] {re:classloading}
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:597) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:shouldersurfing:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:435) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:shouldersurfing:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.25.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1063823352.call(Unknown Source) [forge-1.15.2-31.1.25.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
	at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42)
	at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:73)
	at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:120)
	at shadows.apotheosis.ench.objects.ItemHellBookshelf.func_150895_a(ItemHellBookshelf.java:47)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:597)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:435)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$464/1063823352.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4358268640 bytes (4156 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2%20(2).jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2%20(2).jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2%20(2).jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.25
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
	Mod List: 
		followingvillagers-1.15.2-1.4.0.jar Following Villagers {followingvillagers@1.15.2-1.4.0 LOAD_REGISTRIES}
		SlimyBoyos-2.0.0.jar SlimyBoyos {slimyboyos@2.0.0 LOAD_REGISTRIES}
		dotHack-Weapons-1.15.2-1.3.0.jar dotHack Weapons {dothack@1.0.0 ERROR}
		zombiehs_1.15.2-2.1.2.jar Zombie Horse Spawn {zombiehs@2.1.2 LOAD_REGISTRIES}
		prefab-1.5.0.1.jar Prefab {prefab@1.5.0.1 LOAD_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 LOAD_REGISTRIES}
		timber-1.15.2-1.5.jar Timber Mod {timber@1.5 LOAD_REGISTRIES}
		softerhayb_1.15.2-1.0.jar Softer Hay Bales {softerhayb@1.0 LOAD_REGISTRIES}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 LOAD_REGISTRIES}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 LOAD_REGISTRIES}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 LOAD_REGISTRIES}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 LOAD_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 LOAD_REGISTRIES}
		sneakthroughberries-1.15.2-20w06a-1.0.1.jar Sneak Through Berries {sneakthroughberries@1.15.2-20w06a-1.0.1 LOAD_REGISTRIES}
		edibleglowst_1.15.2-1.0.jar Edible Glowstone {edibleglowst@1.0 LOAD_REGISTRIES}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 LOAD_REGISTRIES}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 LOAD_REGISTRIES}
		cryingghasts_1.15.2-1.0.jar Crying Ghasts {cryingghasts@1.0 LOAD_REGISTRIES}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 LOAD_REGISTRIES}
		Waddles-1.15.2-0.8.5.jar Waddles {waddles@1.15.2-0.8.5 LOAD_REGISTRIES}
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 LOAD_REGISTRIES}
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 LOAD_REGISTRIES}
		EE+-+2.0.jar Extra Enrichments {extraenrichments@2.0 LOAD_REGISTRIES}
		w2w-1.15.2-0.0.0.1.jar w2w {w2w@NONE LOAD_REGISTRIES}
		anviltweaks-2.2a.jar Anvil Tweaks {anviltweaks@2.2a LOAD_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 LOAD_REGISTRIES}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 LOAD_REGISTRIES}
		repurposedstructures-1.15.2-1.1.0.jar Repurposed Structures {repurposed_structures@1.15.2-1.1.0 LOAD_REGISTRIES}
		AmbientSounds_v3.0.18_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 LOAD_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.352-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.349 LOAD_REGISTRIES}
		phosphor-mc1.15.2-forge-0.4.2-rc2.jar Phosphor {phosphor@0.4.2-rc2 LOAD_REGISTRIES}
		MekanismAdditions-1.15.2-9.9.16.408.jar Mekanism: Additions {mekanismadditions@9.9.16 LOAD_REGISTRIES}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 LOAD_REGISTRIES}
		valhelsia_structures-15.0.2.jar Valhelsia Structures {valhelsia_structures@15.0.2 LOAD_REGISTRIES}
		invtotem_1.15.2-1.0.jar Inventory Totem {invtotem@1.0 LOAD_REGISTRIES}
		mining_dimension-1.15.2-1.0.1.jar Mining World {mining_dimension@1.15.2-1.0.1 LOAD_REGISTRIES}
		AzureRPGItems+1.15.2-1.3.2.jar Azure RPG Items {azurerpgitems@1.1.0 LOAD_REGISTRIES}
		lycanitesmobs-1.15.2-2.2.2.1.jar Lycanites Mobs {lycanitesmobs@1.0 LOAD_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.jar Curios API {curios@FORGE-1.15.2-2.0.2 LOAD_REGISTRIES}
		carrotslib-mc1.15.2-2.5b1.jar Carrots Lib {carrots@2.5.0b1 LOAD_REGISTRIES}
		vanillafoodpantry-mc1.15.2-5.5b1.jar Vanilla Food Pantry {vanillafoodpantry@5.5.0b1 LOAD_REGISTRIES}
		rndbmflowers_1.15-1.1.jar Random Bone Meal Flowers {rndbmflowers@1.1 LOAD_REGISTRIES}
		Clay+WorldGen-1.1.0-1.15.1.jar Clay WorldGen {clayworldgen@version LOAD_REGISTRIES}
		extlights-2.0.jar Extended Lights {extlights@2.0 LOAD_REGISTRIES}
		lostcities-1.15-3.0.1-alpha.jar LostCities {lostcities@1.15-3.0.1-alpha LOAD_REGISTRIES}
		tombstone-4.3.0-1.15.2.jar Corail Tombstone {tombstone@4.3.0 LOAD_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 LOAD_REGISTRIES}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 LOAD_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 LOAD_REGISTRIES}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 LOAD_REGISTRIES}
		doubledoors_1.15.2-1.2.jar Double Doors {doubledoors@1.2 LOAD_REGISTRIES}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 LOAD_REGISTRIES}
		mining-helmet-1.15.2-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 LOAD_REGISTRIES}
		Mine+and+Slash-1.15.2-3.4.0.jar Mine and Slash {mmorpg@3.4.0 LOAD_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 LOAD_REGISTRIES}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 LOAD_REGISTRIES}
		buzzierbees-1.3.jar Buzzier Bees {buzzierbees@1.3 LOAD_REGISTRIES}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 LOAD_REGISTRIES}
		Realistic+Ulities+4.1.1.jar Realistic Ulities {realistic@4.1.1 LOAD_REGISTRIES}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 LOAD_REGISTRIES}
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 LOAD_REGISTRIES}
		bloomful-1.15.2-1.3.1.jar Bloomful {bloomful@NONE LOAD_REGISTRIES}
		skeletonhs_1.15.2-1.1.2.jar Skeleton Horse Spawn {skeletonhs@1.1.2 LOAD_REGISTRIES}
		extraboats-1.3.0-1.15.2.jar Extra Boats {extraboats@1.3.0 LOAD_REGISTRIES}
		MS+Auto-Compat-1.15.2-1.2.0.jar M&S Auto-Compat 1.15.1 {azurecompat@1.2.0 LOAD_REGISTRIES}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 LOAD_REGISTRIES}
		MoreOresInONE-1.1_1.15.2.jar More Ores in ONE {moreoresinone@1.1 LOAD_REGISTRIES}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 LOAD_REGISTRIES}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 LOAD_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 LOAD_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 LOAD_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 LOAD_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 LOAD_REGISTRIES}
		nhacampfire_1.15.2-1.5.jar No Hostiles Around Campfire {nhacampfire@1.5 LOAD_REGISTRIES}
		permasomnia_v1.1.1_formc1.15.2.jar Permasomnia {permasomnia@1.1.1 LOAD_REGISTRIES}
		mapperbase-1.15.2-1.0.0.0.jar Mapper Base {mapperbase@1.15.2-1.0.0.0 LOAD_REGISTRIES}
		bedspreads-FORGE-1.15.2-3.0.jar Bedspreads {bedspreads@FORGE-1.15.2-3.0 LOAD_REGISTRIES}
		edibmagmac_1.15.2-1.0.jar Edible Magma Cream {edibmagmac@1.0 LOAD_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 LOAD_REGISTRIES}
		dismounte_1.15-1.1.jar Dismount Entity {dismountentity@1.1 LOAD_REGISTRIES}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 LOAD_REGISTRIES}
		swampexpansion-1.15.2-1.5.jar Swamp Expansion {swampexpansion@NONE LOAD_REGISTRIES}
		forge-1.15.2-31.1.25-universal.jar Forge {forge@31.1.25 LOAD_REGISTRIES}
		Bountiful-3.0.0-1.15.2.jar Bountiful {bountiful@3.0.0-1.15.2 LOAD_REGISTRIES}
		goprone-1.15.x-1.1.1.jar GoProne {goprone@1.15.x-1.1.1 LOAD_REGISTRIES}
		[Forge]+[1.15.2]+GamemodeOverhaul-1.15.2-1.4.2.2.jar GamemodeOverhaul {gamemodeoverhaul@1.15.2-1.4.2.2 LOAD_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 LOAD_REGISTRIES}
		forge-1.15.2-31.1.25-client.jar Minecraft {minecraft@1.15.2 LOAD_REGISTRIES}
		turtlemod-1.15.1-1.2.0-6.jar Turtle Mod {turtlemod@1.15.1-1.2.0-6 LOAD_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.4.jar EnchantmentDescriptions {enchdesc@2.0.4 LOAD_REGISTRIES}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 LOAD_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 LOAD_REGISTRIES}
		bspawncontrol_1.15.2-1.0.jar Better Spawner Control {bspawncontrol@1.0 LOAD_REGISTRIES}
		behgameon-1.15.2-1.3.0.jar Behgameon {behgameon@1.3.0 LOAD_REGISTRIES}
		edibsgr_1.15.2-2.0.jar Edible Sugar {edibsgr@2.0 LOAD_REGISTRIES}
		ShoulderSurfing-1.15.2-1.22.jar Shoulder Surfing {shouldersurfing@1.15.2-1.22 LOAD_REGISTRIES}
		fallthroughsl_1.15.2-1.0.jar Fall Through Slime {fallthroughsl@1.0 LOAD_REGISTRIES}
		BerryBushes-1.1.1.jar Berry Bushes {berrybushes@1.1.1 LOAD_REGISTRIES}
		flux-4.11.1.jar Flux {flux@4.11.1 LOAD_REGISTRIES}
		fl-3.1.3.jar Flux Library {fl@3.1.3 LOAD_REGISTRIES}
		betconduitpl_1.15-1.0.jar Better Conduit Placement {betconduitpl@1.0 LOAD_REGISTRIES}
		JAOPCA-1.15.2-3.0.0.21.jar JAOPCA {jaopca@3.0.0.21 LOAD_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 LOAD_REGISTRIES}
		performant-1.15-1.7.jar Performant {performant@1.7 LOAD_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 LOAD_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 LOAD_REGISTRIES}
		lightningtweaks-1.15.2-0.0.1.0.jar Lightning Tweaks {lightningtweaks@NONE LOAD_REGISTRIES}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 LOAD_REGISTRIES}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 LOAD_REGISTRIES}
		parachutemod-1.15.2-3.0.2-479.jar Parachute Mod NG {parachutemod@1.15.2-3.0.2-479 LOAD_REGISTRIES}
		healingcf_1.15.2-1.7.jar Healing Campfire {healingcf@1.7 LOAD_REGISTRIES}
		lootbagmod-1.15.1-1.5.jar Loot Bag Mod {lootbagmod@1.15.1-1.5 LOAD_REGISTRIES}
		farlanders-1.15.2-1.1.2.jar The Farlanders {farlanders@1.1.2 LOAD_REGISTRIES}
	Launched Version: 1.15.2-forge-31.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics

**Comment by Shadows-of-Fire** [comment]
This was determined to be a bug in the mod Flux, see #143
