### ISSUE TITLE
Apotheosis Doesnt Work on Dedicated MC Server

### ISSUE THREAD

**Issue by Frederick404** [Shadows-of-Fire/Apotheosis#147]
it causes a crash on server start.
i did single apotheosis out. it also doesnt work when it is the only mod except for placebo.
https://pastebin.pl/view/9a920889

**Comment by TheOddPanda** [comment]
Same issue here. A freshly setup server crashes a lot. Pls hotfix asap

**Comment by Shadows-of-Fire** [comment]
Not sure what makes you think thats an apoth problem, that crash is caused by `gravityworld1144`
Which is an mcreator mod, so it will never work on a server.
