### ISSUE TITLE
Never finishes loading world

### ISSUE THREAD

**Issue by LittleExxGames** [Shadows-of-Fire/Apotheosis#148]
Something about apotheosis makes it so when I create a new world, it loads to 100% and is stuck at that forever. It does not crash and Minecraft is responsive, it just does not finish loading. It loads when I remove the mod.
Mod List:
AmbientEnvironment-3.0.0.jar
AmbientSounds_v3.0.19_mc1.15.2.jar
BonsaiTrees-2.1.2.6.jar
Bountiful-3.0.0-1.15.2.jar
classicbar-3.0.2.jar
giantspawn_1.15.2-1.0.2.jar
goblintraders-1.2.0-1.15.2.jar
HunterMod-1.15.2-1.0.3.jar
hunterillager-1.15.2-0.5.0.jar
huskspawn_1.15.2-1.0.jar
immersive-portals-0.8(forMc1.15withForge).jar
Kottle-1.5.0.jar
libnonymous-1.15.2-1.1.1.5.jar
lycanitesmobs-1.15.2-2.2.2.1.jar
MixinBootstrap-1.0.2.jar
MutantBeasts-1.15.2-1.0.4.jar
Placebo-1.15.2-3.0.2.jar
reap-1.12.2.jar
repurposedstructures-1.15.2-1.2.1.jar
RiddleChests-1.1.0.1.jar
ruins-1.15.1.3 (1).jar
skeletonhs_1.15.2-1.1.2.jar
strayspawn_1.15.2-1.0.jar
valhelsia_structures-15.0.2a.jar
zombiehs_1.15.2-2.1.2.jar

**Comment by Shadows-of-Fire** [comment]
You'll have to provide a debug.log file, as I've created quite a few worlds with no issues.

**Comment by LittleExxGames** [comment]
Not sure how to get a debug.log. Hopefully, this is what you need. Only 10% of the time can I start a world and it would work, but when it does not, this is the log:
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/4372449/latest.log)

**Comment by Shadows-of-Fire** [comment]
Well, there's two errors in there, one is something else breaking my anvil transforming coremod (couldn't tell you what mod)
And the other is what appears to be a bug in lycanites, but I believe the former is causing the stalling.

Anyway, you'd have to remove mods until you find out what mod is breaking my transformer, and if you do that, tell me, so I can mark said mod as incompatible.
