### ISSUE TITLE
Miner's Fevor impractical at high levels or when mixed with Efficiency.

### ISSUE THREAD

**Issue by avalonv** [Shadows-of-Fire/Apotheosis#149]
It like, just breaks mining. Actually makes it harder to mine because you end up creating 4x1 holes in a few milliseconds. I lost diamonds to lava because of it at level 4, at higher levels it becomes virtually impossible to mine a single block at depths 20 and below. Level 11 just seems impractical 99% of the time, it acts more like a curse.
I have lowered the max level in the config, but would it be possible to also lower the default for the mod, or perhaps add an option to make it incompatible with items that also have efficiency?

By the way excellent mod, thank you for you work.

**Comment by Shadows-of-Fire** [comment]
Yeah, fervor (and quite a few enchantments) need a retune.  They're next on the list after the Affix rework which is in-progress.

**Comment by Shadows-of-Fire** [comment]
The formula for how Miner's Fervor is calculated has been reworked, it should hopefully be less annoying now.
