### ISSUE TITLE
Altar of the Sea can't be crafted in 1.5.2

### ISSUE THREAD

**Issue by avalonv** [Shadows-of-Fire/Apotheosis#150]
I can acquire it in creative mode but I can't interact with it.

**Comment by 016Nojr** [comment]
Have you tried clicking the "pillars" on it? It's specific about where you click enchanted items on it.
Working for me with version 3.0.6

**Comment by avalonv** [comment]
@016Nojr you are right, I wasn't interacting with it correctly. However I still cannot craft it, having checked the recipe is correct.

**Comment by Shadows-of-Fire** [comment]
The altar recipe works just fine, are you using the right recipe?
