### ISSUE TITLE
[1.14.4] Possible to disable specific enchantments entirely?

### ISSUE THREAD

**Issue by ridjack** [Shadows-of-Fire/Apotheosis#151]
From my looking through the config, I didn't see any way to completely disable specific enchantments; I can prevent them from appearing on the enchanting table by setting their minimum enchanting power to some arbitrarily high number, but they can still appear in loot tables and villager trades.

**Comment by Shadows-of-Fire** [comment]
There is no way to perform such an action, and there probably will never be, as per the forge guidelines on registry objects (stating that all objects should always be registered).
