### ISSUE TITLE
[1.15.2] Many things seem to be missing

### ISSUE THREAD

**Issue by Peerius1701** [Shadows-of-Fire/Apotheosis#152]
Hello,

I'm currently playing the ATM 5 - All the mods 5 modpack where Apotheosis is installed. I added all mods that are given as dependencies on the curseforge site, but it seems like many things are missing. It's easier to count what is there:
- The potions
- The Endless Quiver enchantment
- The arrows

That's all... everything else just isn't there.

What can I do? :(

**Comment by Shadows-of-Fire** [comment]
Unfortunately that modpack has disabled most of the content of apotheosis.  You'll have to take it up with them, or re-enable the content in ./config/apotheosis/apotheosis.cfg
