### ISSUE TITLE
Roguelike Dungeons Custom Potion issue

### ISSUE THREAD

**Issue by Wolfram96** [Shadows-of-Fire/Apotheosis#153]
i'm using the 1.12.2 version of this mod.

the roguelike dungeons mod adds some custom potions with hidden effects but sadly this mod overlays the actual effects as with the special item enchants that don't correlate with the actual enchantments. there are to ways this could be fixed but since i think your mod makes certain hidden values visible and both mods using the same mechanic causes the overlap the first one should be easier. 
1. make it so the overly doesn't cut through the flavor text by adding a separate line/tab. this would fix the ugly overlapping of text and symbols but it would still spoil the surprise of the potion effect.
2. second, make it not show up on RD potions altogether, not sure how that would work though.

i would appreciate if u look into it but its not game-breaking and i will continue to use both mods for the foreseeable future.

**Comment by Shadows-of-Fire** [comment]
I'm not even really sure what you're asking, but versions other than 1.15.2 are not under development

**Comment by Wolfram96** [comment]
oh ups
