### ISSUE TITLE
ignore spawn cap

### ISSUE THREAD

**Issue by TheUntamed** [Shadows-of-Fire/Apotheosis#154]
In the config the value change for this spawner modification is set to 0 by default:

> The amount each item changes this stat. [range: -2147483648 ~ 2147483647, default: 0]
> I:value=0

Does this mean adding a chorus fruit has no effect?

**Comment by Shadows-of-Fire** [comment]
That modifier does not have an integer value associated with it, as it is a boolean, this config is autogenerated and has a few side effects, such as that, where the config is misleading/useless

**Comment by TheUntamed** [comment]
And how can I disable this modification?
Removing the spawn cap sounds dangerous to me. Especially for a server.

**Comment by Shadows-of-Fire** [comment]
change the item for the modifier to smth unobtainable
