### ISSUE TITLE
Problems with the splitting enchantment in 1.15.2

### ISSUE THREAD

**Issue by andreas-k-beckman** [Shadows-of-Fire/Apotheosis#155]
Apotheosis-1.15.2-3.0.7.jar

Tested within the context of the Valhelsia 2 modpack.

Trying to enchant an anvil with splitting gives Splitting I, both when you use Splitting I or Splitting V books.

Trying to use the anvil on a book with multiple enchants either does nothing (My guess is this is where the enchant doesnt trigger) or makes the book vanish, without giving any new books from it.

Best Regards
Andreas

**Comment by Shadows-of-Fire** [comment]
Valhelsia has the max level of splitting set to 1, so, you'll have to take it up with them.  I've got no clue why anyone would limit the level to below 5.
As for the making the book vanish part, I can't reproduce that, even with just Splitting 1.

**Comment by andreas-k-beckman** [comment]
I see!

Thank you for looking into it :)
