### ISSUE TITLE
1.14.4 Mobs from spawners regenerate health

### ISSUE THREAD

**Issue by BigFriendlyJakey** [Shadows-of-Fire/Apotheosis#156]
Just set up a XP farm with 2 swarm spawners I found covered in vines close to each other. They fall 21 blocks and are left with half a heart, but then they regen slowly back to full. I've been searching through my mods and configs, and I'm sure this is the only mod of my 40-mod 'pack' that changes spawners. I've tried spawning mobs in creative with spawn eggs and they don't regenerate. Any ideas?

**Comment by Shadows-of-Fire** [comment]
You probably picked up a brutal spawner, which by default applies a couple potions to the mob contained in said spawner.  Regeneration happens to be one of them.
