### ISSUE TITLE
Bug w/tome of boots recipe.

### ISSUE THREAD

**Issue by Maxwelllondon92** [Shadows-of-Fire/Apotheosis#16]
Found a bug while crafting a tome of boots. Actually recognized as shapeless recipe: result is tome of others.
Tested on Bibliocraft fancy crafting table.

**Comment by Maxwelllondon92** [comment]
Was this actually a bug? Or was it my fault? (E.g. Mod incompatibility)

**Comment by Shadows-of-Fire** [comment]
This was an actual bug.  The recipe was registered early, and needed to be registered later
