### ISSUE TITLE
Mod Compatibility Issue (1.12.2):  Mekanism Cardboard boxes

### ISSUE THREAD

**Issue by hyperjoe** [Shadows-of-Fire/Apotheosis#160]
When using Mekanism Cardboard boxes to move spawners that have been customized via Apotheosis,  customizations such as Spawn delay (max and min) are maintained.

However,  if you pick up a spawner that has "Requires Redstone" or "Ignores Spawn conditions"   enabled (via a redstone comparator or dragon egg), that trait is stripped from the spawner either upon applying the cardboard box or removing it.  

I've not tested with "ignores player"  or "ignores spawn cap"  but I suspect that the same will happen in those situations as well.    

This may be an issue with Mekanism so I reported this issue on their github as well.

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported
