### ISSUE TITLE
[1.15.2] Possible Mixin Related Crash

### ISSUE THREAD

**Issue by Dragnier** [Shadows-of-Fire/Apotheosis#162]
MC version: 1.15.2
Forge version: 31.1.77
Apotheosis version: 3.0.7

Crashlog changes depending on whether other Mixin using mods are loaded or not. Turning off all other Mixin mods results in the following crashlog: [Crash without other Mixin mods](https://gist.github.com/Dragnier/417779c4653f014d2b1e87df6721b2c2)

Turning on any other Mixin using mod, whether it loads the Mixin itself or through MixinBootstrap, causes the crash log to point at that mod rather than Apotheosis or MixinBootstrap.

Loading without any Mixin mods other than MixinBootstrap is fine. Loading with all other Mixin mods besides Apotheosis is fine.

**Comment by Shadows-of-Fire** [comment]
That's probably an issue caused by whatever mixin is messing with that code, as nothing in apoth touches render code.

**Comment by Irritumerus** [comment]
I know this says it's closed, but one of the known issues is between apotheosis and quark oddities since they both change the enchanting table in some way

**Comment by rtxyd** [comment]
@Irritumerus you can disable the matrix enchanting in quark.
