### ISSUE TITLE
[1.15.2] Advancement not functioning?

### ISSUE THREAD

**Issue by Dasawkem** [Shadows-of-Fire/Apotheosis#163]
Apologies if this has been addressed before, but I have killed many apotheotic bosses over and over, yet my game never seems to trigger the "Slay an apotheotic boss" advancement? I've beaten them many times over, confirmed by the characteristic "square" of red sandstone, so I do know it's the specific boss mob I've defeated. Is this possibly just a glitch or a goof on my end? Or is this entirely intentional?

**Comment by Shadows-of-Fire** [comment]
That one is essentially some forge issue.  The bosses have an nbt tag that's getting lost during their spawn cycle.
