### ISSUE TITLE
Chest Inventory Crash

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#165]
`Minecraft v1.15.2`
`Forge v31.1.87`
`Apotheosis v3.1.0`

I recieved a crash client side while on my server after opening a chest and presumably mousing over an item. I don't know which item it was, but no items contained enchantments on it in the chest or player inventory.

[Crash Report](https://gist.github.com/WenXin20/fdaf6e87b8d023c483e73065a3b5656d)

**Comment by DrakusorU** [comment]
I get the same when hovering over an enchanted bow. 3.0.7 works fine.. https://prnt.sc/shko95 might conflict with strange as this is a legendary bow dropped from a named mob added by strange I think :-?
