### ISSUE TITLE
Boss Mob crash issue

### ISSUE THREAD

**Issue by Keppto** [Shadows-of-Fire/Apotheosis#166]
My server and game kept crashing once I tried to interact with the boss mobs. He was a blueish skeleton with full gear, and I couldn't hit him. He was invulnerable even to commands, and would crash the game and server. Here's the crash report:
https://hastebin.com/gudirovati.pl 
Was using the ATM5 modpack, and the modpack author suggested I removed the EnvironmentalCreepers mod as it was conflicting. I tried that, as well as resetting the world to peaceful and I kept crashing.

**Comment by Shadows-of-Fire** [comment]
That hastebin link is blank

**Comment by Keppto** [comment]
Okay I've tried to put it on pastebin instead.
https://pastebin.com/zkDMCTnH

**Comment by Shadows-of-Fire** [comment]
Resolved with the old-affix protections added in 3.1.1
