### ISSUE TITLE
Ticking player & ticking Entities crashes 

### ISSUE THREAD

**Issue by ArabJew** [Shadows-of-Fire/Apotheosis#168]
https://pastebin.com/E0gAdgcq
https://pastebin.com/WbDwMtqX

I was playing survival and i went through lava in the nether with my jet pack on and crashed a few seconds later. trying to replicate the issue in creative world making the nether portal my game crashed as well.

**Comment by Shadows-of-Fire** [comment]
update to 3.1.1
