### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#169]
`Minecraft v1.15.2`
`Forge v31.1.87`
`Apotheosis v3.1.1`

After updating, the game now crashes on luanch.

[Crash Report](https://gist.github.com/WenXin20/0e76dd4925d52f104c29ad0227d16f95)

**Comment by Shadows-of-Fire** [comment]
That's caused by something invoking getSubItems before the registry phase ends, nothing on apoth's side
