### ISSUE TITLE
Mini achievment bug

### ISSUE THREAD

**Issue by Gayanfalor** [Shadows-of-Fire/Apotheosis#171]
Hi there just seen a mini bug in activement about slaying apo boss while in fact i had not killed him but naked him and stole all his stuff with the pilfeting enchant on fishing rod. Just getting the equipment unlocked the achievment.

I play on atm5 1.24 with app 3.1.2

**Comment by Shadows-of-Fire** [comment]
working as intended

**Comment by Gayanfalor** [comment]
Oh ok if its intented thats ok. Even if getting the achievment "slay an apotheosis boss" without actually killing it seemed for me as a Glitch or bug 😉
