### ISSUE TITLE
[Feature Request] Configurable Surface Boss Spawns

### ISSUE THREAD

**Issue by ShockPuppet** [Shadows-of-Fire/Apotheosis#176]
**Configurable Surface Boss Spawns**

Hi Shadows of Fire,

We are suggesting to allow control of frequency for increase or decrease the amount of boss spawns on the surface of the world.

The players on my server absolutely love the bosses, and although i have set the frequency to 1.0 in deadly config for boss spawning, i believe that increases the chance for one of those underground red sandstone pads to be generated in a chunk.

We would like to see more bosses appearing on the surface of the world, we would be extremely impressed and grateful if this was possible. We wouldn't mind if it was purely by making the lightning happen more often with a boss spawn, or if they could be naturally spawned with the other hostile mobs.

Thank you.

**Comment by Shadows-of-Fire** [comment]
Coming in next update, isn't there yet as I was trying to find a suitable default level
