### ISSUE TITLE
[1.12.2] Enchantability on tinkers tools

### ISSUE THREAD

**Issue by Invidious** [Shadows-of-Fire/Apotheosis#177]
With the addition of this mod it adds the ability to enchant tinkers' construct tools which isn't possible without it. I tried browsing through the enchantability config and couldn't find anything that referenced tinkers tools to disable it. Alternatively there's a tinkers armor addon mod that I have that does have a section that appears in the config that stops all the armor from being enchanted. Is there a work around for this? I've tried things like "tconstruct:pickaxe" which is the generic item name without the tags but that doesn't work because it wasn't a material I guess..

Ex:
```
The enchantability of this armor material. [range: 0 ~ 2147483647, default: 0]
    I:armory=0
```

**Comment by Shadows-of-Fire** [comment]
1.12 is not supported, and TiC stuff being enchantable is something that they would need to prevent on their end (by overriding Item#isEnchantable to false).
