### ISSUE TITLE
Trouble blacklisting spawn eggs in config file

### ISSUE THREAD

**Issue by koimp** [Shadows-of-Fire/Apotheosis#178]
Hey, whenever I try to blacklist a mob and start up the game, the config file undoes the change and generates an ERRORED file. I'm assuming I'm getting something wrong with syntax. I've tried using the `quark:stoneling` example from #117 and it's still happening. Is 
```
spawn_eggs {
    # A list of entity registry names that cannot be applied to spawners via egg. [default: ]
    S:"Banned Mobs" <quark:stoneling
     >
```
not correct? Some help would be much appreciated, thanks.

**Comment by Shadows-of-Fire** [comment]
each entry should be on a new line, and it should be the only thing on that line
