### ISSUE TITLE
Spawner Configs and tweaks

### ISSUE THREAD

**Issue by Fortist** [Shadows-of-Fire/Apotheosis#18]
It's nice we can change what items are needed to edit spawners, but we cant change how many ticks/amount each item does.
Would It be possible to add that for at least some of the options?

also, it seems that there is no "Stop" to how many items you put in when you "max it"
Like, if I were to drop the minimum spawn rate to 0, it would still accept items despite it being at 0.

**Comment by Shadows-of-Fire** [comment]
There's a rewrite of this system in-progress, it should address those concerns.

**Comment by Shadows-of-Fire** [comment]
As of 1.8.0:

Spawner modifiers will no longer over-consume.
The amount each modifier changes it's respective value is configurable.
More complex modifier ingredients can be applied via ZS.
