### ISSUE TITLE
Exception Ticking World

### ISSUE THREAD

**Issue by dankfrog** [Shadows-of-Fire/Apotheosis#180]
Was just walking around the world and froze then crashed.

heres the crash log - https://pastebin.com/5d5ksAAR

It's happened once before, not sure exactly what causes it. 

It could be an interaction with the Extended Animals mod. 
I reported this to the dev of Genetic Animals (aka Extended Animals on Github) as well. 

Thank you.

**Comment by Shadows-of-Fire** [comment]
Doesn't look like this has anything to do with apoth
