### ISSUE TITLE
crash on Guardian beam "defect" with shield. 

### ISSUE THREAD

**Issue by AlienXtream** [Shadows-of-Fire/Apotheosis#181]
im assuming this "projectile" (its actually just direct damage yeh?) or whatever was missed in testing but "deflecting" a guardian beam with the reflective defences enchant crashes the game. here's the crash report.
[crash-2020-06-13_16.43.18-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/4774376/crash-2020-06-13_16.43.18-server.txt)

edit: 1.12.2 btw.
additional info just in case it is needed. i was swimming. was using the "summoning pendant", an entity capture tool from the "cyclic" mod.  (may be important for simultaneous events where the hit and the capture happened within the same tick).

**Comment by AlienXtream** [comment]
so yeh. word of warning to others. dont do that for now...

**Comment by Shadows-of-Fire** [comment]
That is... strange, but 1.12.2 isn't supported anymore unfortunately.

**Comment by AlienXtream** [comment]
thats fair enough. as long as it does not happen on the latest version :)
