### ISSUE TITLE
Thorns Enchantment not going above 3

### ISSUE THREAD

**Issue by blarghhh** [Shadows-of-Fire/Apotheosis#182]
im not getting the enchantment for thorns to exceed thorns 3 even though the config shows a higher level. i have hell infusion enchanted hellshelves and able to get level 150 enchantment power.

"minecraft:thorns" {
    # The max level of this enchantment. [range: 1 ~ 127, default: 14]
    I:"Max Level"=14

    # A function to determine the max enchanting power.  The variable "x" is level.  See: https://github.com/uklimaschewski/EvalEx#usage-examples [default: ]
    S:"Max Power Function"=

    # The min level of this enchantment. [range: 1 ~ 127, default: 1]
    I:"Min Level"=1

    # A function to determine the min enchanting power. [default: ]
    S:"Min Power Function"=
}

please advise

**Comment by Shadows-of-Fire** [comment]
I assume some other mod is breaking it, or the module is disabled, or something.

The enchantment system has currently been entirely redone, so hopefully it prevents mods from breaking it a bit better.
