### ISSUE TITLE
Random Lightning Bolt Spawning

### ISSUE THREAD

**Issue by Leirday** [Shadows-of-Fire/Apotheosis#184]
The Apotheosis Mod seems to be causing lightning bolts to "spawn" at random times. The lightning bolts themselves are not visible to the player (as far as I know) and they can occur even if the weather is set to clear and in the Nether and End dimensions respectively. 

Mod Version: Apotheosis-1.15.2-3.1.2, Placebo-1.15.2-3.0.2

Here are a few screenshots:

Note: I turned on Subtitles so I could screenshot whenever the bolt spawns. (Check bottom left corner.)

![2020-06-20_15 32 39](https://user-images.githubusercontent.com/63563648/85212359-e4ab2180-b31f-11ea-9da8-3abcf53b14d6.png)

![2020-06-20_01 58 11](https://user-images.githubusercontent.com/63563648/85212373-12906600-b320-11ea-8a32-ac290d12bd30.png)

**Comment by lamoyrl90** [comment]
Same issue here, same MC version, same mod version.

It's annoying to the point where I have to disable the mod even though I love its content.

**Comment by Shadows-of-Fire** [comment]
the lightning bolts signal a boss spawn, if you dont want random boss spawns, disable them in the configs.  The fact that its happening in other dimensions is a bug that is fixed in dev but not yet released

**Comment by lamoyrl90** [comment]
Oh thank the lord!

Could you maybe add a config option to just disable the thunder?

**Comment by Shadows-of-Fire** [comment]
yeah, thats probably a reasonable idea

**Comment by Leirday** [comment]
> yeah, thats probably a reasonable idea

Thanks for responding :D
