### ISSUE TITLE
Capturing Enchantment

### ISSUE THREAD

**Issue by jermacalocas** [Shadows-of-Fire/Apotheosis#185]
Can we get a better understanding of the coded mechanics of capture enchantment? Are there entities it doesnt cause an egg to drop for? Im Mostly curious if they spawn villager eggs? I am working on a villager farm to build custom villages with as an easier form of transportation and containment.

**Comment by Shadows-of-Fire** [comment]
The capturing enchantment will only drop spawn eggs for mobs that "have" a spawn egg (not all mobs do).  Additionally, certain mobs can be blacklisted in the config, so if you're on a modpack, you may need to check if some egg types are being prevented from dropping.
