### ISSUE TITLE
Beheading not working with players

### ISSUE THREAD

**Issue by grandogarndo** [Shadows-of-Fire/Apotheosis#188]
So, when i kill a player with beheading, it gives me their head, but not the skins head.  below is an image of my friends head, who does not have the alex skin.
![2020-07-07_19 33 59](https://user-images.githubusercontent.com/56941237/86855688-dc294980-c088-11ea-9778-b58097b86fc2.png)

**Comment by Shadows-of-Fire** [comment]
There is no beheading in this mod

**Comment by grandogarndo** [comment]
oof, sorry. Since Apotheosis adds so many enchants I thought that beheading was part of it.
