### ISSUE TITLE
ItemColors PotionCore Client Crash

### ISSUE THREAD

**Issue by ClockworkFountain** [Shadows-of-Fire/Apotheosis#189]
Getting a weird crash on launch
[https://pastebin.com/p1SVrEkX](url)

**Comment by Shadows-of-Fire** [comment]
That is real weird, reading the code behind that, a final field is null... so something extra sketchy is going on.

**Comment by ClockworkFountain** [comment]
Is there any way to find out what's causing this, besides removing mods one by one?

**Comment by Shadows-of-Fire** [comment]
No, because whatever is messing with it has no accountability in that log (so it's probably a mixin or smth).
I've never seen this in either Valhelsia or ATM5, so you could cross-check with those modlists and try removing things that are unique to this pack.

**Comment by ClockworkFountain** [comment]
Would posting the debug log help?

**Comment by ClockworkFountain** [comment]
Thanks to MoreCrashInfo, I found out it was from Silent's Gems
