### ISSUE TITLE
Crash because of shadows? 1.15.2 Error: java.lang.NullPointerException: null key in entry: null=10

### ISSUE THREAD

**Issue by IEatRoombas** [Shadows-of-Fire/Apotheosis#190]
The Error i get is Error: java.lang.NullPointerException: null key in entry: null=10 when i try to launch the game
[crash-2020-07-11_11.57.06-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/4907481/crash-2020-07-11_11.57.06-client.txt)
^ this is the crash report. thanks for the help

**Comment by Shadows-of-Fire** [comment]
long been fixed, you're using a vastly outdated version

**Comment by IEatRoombas** [comment]
oh, well thanks. i always forget to update my mods, oops
