### ISSUE TITLE
[1.15] Crash on Startup in modpack

### ISSUE THREAD

**Issue by katubug** [Shadows-of-Fire/Apotheosis#191]
Hi! I'm having an issue where my game crashes on startup when Apotheosis is added to my existing modlist. This does not occur in an instance with only Apotheosis, so it's gotta be a mod conflict, but I haven't had much luck figuring out what the issue is. The problem goes away when I remove Apotheosis. Placebo has been in the pack the whole time, without issue.

I am using 1.0.1 of this modpack: https://www.curseforge.com/minecraft/modpacks/rustic-wanderings

Apotheosis: 3.2.2
Forge: 31.2.30 and 31.2.31
Placebo: 3.1.0

Here's one of the crash reports I received: https://pastebin.com/cJaYamEL

The mods indicated in the lower half of the report (RandomPatches, Improved Stations) do not appear to actually be the issue. Removing them implicates random other mods, including shedaniel's other mod, Rare Ice. It also takes issue with Savage and Ravage's version of the Pillager Outpost, although it doesn't mention the mod by name, just the structure while that mod is loaded.

Let me know if I can provide any other information! Thanks for your time.

**Comment by Shadows-of-Fire** [comment]
Welp, pastebin is dead, so hopefully I remember to check this later

**Comment by katubug** [comment]
I got you, boo: https://hastebin.com/nogepejono.makefile

**Comment by Shadows-of-Fire** [comment]
Since that happens to be a caught FML loading exception, I'll need the entire debug.log to properly look into it.

**Comment by katubug** [comment]
I seem not to have debug.log enabled. Here's the latest.log in the meantime: https://paste.ee/p/fQMKE

Can I just enable it in fml.toml?

Edit: looks like nope, neither there nor forge-client.toml

Edit 2: Google not helping. How do I enable that?

**Comment by Shadows-of-Fire** [comment]
As far as I know it should just *be* there, so, uh, good question...

**Comment by katubug** [comment]
I just checked, and not only do I not have a debug.log for this modpack, I don't have it for ANY of the packs on this computer, some of which are 1.12.2. o-o I'm wondering if this is some Twitch launcher nonsense somehow...

**Comment by Shadows-of-Fire** [comment]
Hm, might be, my MMC packs all have the debug logs present.

**Comment by katubug** [comment]
Ye that was the problem. I guess I missed the part where MultiMC decided to support forge past 1.13 after all, or I'd have been using that the whole time, lol. Anyway, that worked, and here's the debug.log for ya - https://paste.ee/p/fwPMQ

**Comment by Shadows-of-Fire** [comment]
Well, that doesn't appear to contain the actual source either.  Which means it's probably a coremod conflict, but sourcing what that might be is basically impossible without just identifying the two conflicting mods.

**Comment by katubug** [comment]
Well, heck. Okay, I will get back to isolating the offending mod. I'll keep you posted, thank you!

**Comment by katubug** [comment]
For my reference: In an isolated instance, I gradually added all the mods listed in the "Forge CoreMods" section of the crash report, plus MixinBootstrap. Was unable to replicate the crash. Next step is to test various performance mods to see if it's one of them.

**Comment by Shadows-of-Fire** [comment]
Well I have no idea what it is.  I don't think it's anything fixable on my end.

**Comment by katubug** [comment]
Yeah sorry, I have been meaning to do more testing but I'm dealing with
some health issues that have been limiting my time. I apologize for not
being more helpful. If I find anything useful I will reopen, otherwise I'll
just assume it's a weird mod conflict. Thanks for your help!
