### ISSUE TITLE
Game Crashes when Reloading Resource Packs!

### ISSUE THREAD

**Issue by Leirday** [Shadows-of-Fire/Apotheosis#192]
There is a bug with this mod where if you try to reload texture packs after the game is finished reloading, a loading screen will appear again and after the second loading screen is done loading, the game will end up crashing.

Here is the log: 
[crash-2020-07-12_17.42.12-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/4909608/crash-2020-07-12_17.42.12-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is not reproducible in a development environment, so I might attribute it to the sheer amount of ASM that appears to be going on in that modlist.  

That said, there may be a couple checks that I can put in place to attempt to fix it, but there's no way to tell if they will actually fix it.

**Comment by Leirday** [comment]
> This is not reproducible in a development environment, so I might attribute it to the sheer amount of ASM that appears to be going on in that modlist.
> 
> That said, there may be a couple checks that I can put in place to attempt to fix it, but there's no way to tell if they will actually fix it.

Last Update seems to have fixed the issue :D
