### ISSUE TITLE
Can't enchant higher than level 60

### ISSUE THREAD

**Issue by vincepickle** [Shadows-of-Fire/Apotheosis#195]
I've just installed the Apotheosis mod, and I can't get level enchants higher than 60 showing for use with 3 lapis.

Have I done something worng?

**Comment by Shadows-of-Fire** [comment]
You've used a modpack with the max configured to be at 60, probably valhelsia 2

**Comment by vincepickle** [comment]
Hmmm, not using valhalesia :-(

Mods in use:

Apotheosis-1.15.2-3.2.4.jar
AutoRegLib-1.5-40.jar
BiomesOPlenty-1.15.2-10.0.0.361-universal.jar
EnderMail-1.15.2-1.1.1.jar
MixinBootstrap-1.0.3.jar
NaturesCompass-1.15.2-1.8.5.jar
OptiForge-MC1.15.2-0.1.27.jar
PattysMoreStuff-Mod-1.15.2.jar
Placebo-1.15.2-3.1.0.jar
Quark-r2.1-245.jar
TinyMobFarm-1.15.2-1.0.6.1.jar
Waystones_1.15.2-6.0.2.jar
Xaeros_Minimap_20.11.0_Forge_1.15.2.jar
flower-breeding-1.15.2-1.4.jar
ftb-ultimine-1.0.8.5.jar
inventoryprofiles-forge-1.15.2-0.2.1.jar
jei-1.15.2-6.0.0.4.jar
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar
simplybeans-1.2.jar
storage_overhaul-1.15.2-1.0.4.jar
u_team_core-1.15.2-2.11.0.156.jar
useful_backpacks-1.15.2-1.9.4.63.jar

**Comment by vincepickle** [comment]
Removed all mods apart from Apotheosis and it's still the same 👎 

Is there an Apotheosis config file I can modify?

By the way thanks for the quick response! :-)
