### ISSUE TITLE
Sorry for re-opening issue, just want to check something

### ISSUE THREAD

**Issue by vincepickle** [Shadows-of-Fire/Apotheosis#196]
Saw another strange one...

I increased the Max and Min levels in the enchanting config file, and now the only enchants appearing are the Level 1 enchants like Silk Touch or Mending. I think when other enchants try to appear in the enchanting table GUI they are greyed out and show 'Limited Enchanting Availability' when hovered over. I make sure I have enough enchanting levels... literally 100's of levels, even thousands, but they still don't show. Is this something to do with the new Quanta, Arcana, Eterna mechanics? (which are at the max bars when I enchant)

In general I use the mods below, but I have also tried removing them all and just having Apotheosis installed with Placebo...

Mods in use:

Apotheosis-1.15.2-3.2.4.jar
AutoRegLib-1.5-40.jar
BiomesOPlenty-1.15.2-10.0.0.361-universal.jar
EnderMail-1.15.2-1.1.1.jar
MixinBootstrap-1.0.3.jar
NaturesCompass-1.15.2-1.8.5.jar
OptiForge-MC1.15.2-0.1.27.jar
PattysMoreStuff-Mod-1.15.2.jar
Placebo-1.15.2-3.1.0.jar
Quark-r2.1-245.jar
TinyMobFarm-1.15.2-1.0.6.1.jar
Waystones_1.15.2-6.0.2.jar
Xaeros_Minimap_20.11.0_Forge_1.15.2.jar
flower-breeding-1.15.2-1.4.jar
ftb-ultimine-1.0.8.5.jar
inventoryprofiles-forge-1.15.2-0.2.1.jar
jei-1.15.2-6.0.0.4.jar
preview_OptiFine_1.15.2_HD_U_G1_pre30.jar
simplybeans-1.2.jar
storage_overhaul-1.15.2-1.0.4.jar
u_team_core-1.15.2-2.11.0.156.jar
useful_backpacks-1.15.2-1.9.4.63.jar

_Originally posted by @vincepickle in https://github.com/Shadows-of-Fire/Apotheosis/issues/195#issuecomment-663884929_

**Comment by Shadows-of-Fire** [comment]
I mean, that just means you've created a config setup with the enchantments unobtainable.  That's on you, as the system works perfectly.
