### ISSUE TITLE
enchanting/ anvil other mods wepons ?? 1.14.4

### ISSUE THREAD

**Issue by jigaming** [Shadows-of-Fire/Apotheosis#197]
hi was just curious if it is possible to use the enchants from this mod on other mods and if so how, 
i am using pattysmorestuff alongside this mod and when i tried to combine a knowledge of the ages enchant to a obsidian or redstone sword it wouldn't let me is there away of unblocking this so any enchant can go on any weapon or tool???

**Comment by Shadows-of-Fire** [comment]
thats a bug in that mod

**Comment by jigaming** [comment]
is there a quick fix ???
