### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ThatBenderGuy** [Shadows-of-Fire/Apotheosis#198]
MC Version: 1.15.2
Forge Version:  31.2.30
Mod Version: 3.2.4
Placebo Ver: 3.1.0

I get a crash due to a Null Pointer Exception during the Mod loading process before MC starts

Crash Log
[crash-2020-08-08_23.57.59-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5046832/crash-2020-08-08_23.57.59-client.txt)

Latest.log
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5046834/latest.log)

**Comment by Shadows-of-Fire** [comment]
That's a nonsense crash caused by another mod erroring earlier in the loading process.  The debug.log has the actual information, but its not likely an apoth error
