### ISSUE TITLE
Boss monster crash.

### ISSUE THREAD

**Issue by rfwainug** [Shadows-of-Fire/Apotheosis#2]
net.minecraft.util.ReportedException: Ticking entity at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]Caused by: java.lang.IndexOutOfBoundsException: Index: 4, Size: 4 at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_192] at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_192] at shadows.deadly.gen.BossItem.initBoss(BossItem.java:117) ~[BossItem.class:?] at shadows.deadly.gen.BossItem.place(BossItem.java:94) ~[BossItem.class:?] at shadows.deadly.gen.BossFeature.generate(BossFeature.java:39) ~[BossFeature.class:?] at shadows.deadly.gen.WorldGenerator.run(WorldGenerator.java:38) ~[WorldGenerator.class:?] at shadows.deadly.gen.WorldGenerator.generate(WorldGenerator.java:29) ~[WorldGenerator.class:?] at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?] at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020) ~[axw.class:?] at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?] at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?] at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?] at net.minecraft.world.ChunkCache.(ChunkCache.java:37) ~[and.class:?] at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:113) ~[ze.class:?] at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51) ~[zd.class:?] at com.fantasticsource.dynamicstealth.server.ai.AIDynamicStealth.func_75246_d(AIDynamicStealth.java:658) ~[AIDynamicStealth.class:?] at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) ~[xf.class:?] at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) ~[vq.class:?] at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2356) ~[vp.class:?] at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?] at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?] at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:43) ~[zv.class:?] at net.minecraft.entity.passive.EntitySheep.func_70636_d(EntitySheep.java:111) ~[aag.class:?] at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2176) ~[vp.class:?] at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?] at net.minecraft.world.World.func_72866_a(World.java:1993) ~[amu.class:?] at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?] at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?] at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]

**Comment by Laike-Endaril** [comment]
Possibly related:
[https://github.com/Laike-Endaril/Dynamic-Stealth/issues/28](https://github.com/Laike-Endaril/Dynamic-Stealth/issues/28)

I've included a solution for the issue in that link...in that link (not a typo).  The solution may also solve this issue.

**Comment by Shadows-of-Fire** [comment]
This was fixed in c5504b2 (1.3.0)
