### ISSUE TITLE
1.15.2 Missing Sound

### ISSUE THREAD

**Issue by Yourname942** [Shadows-of-Fire/Apotheosis#201]
`[Render thread/WARN]: Missing sound for event: apotheosis:chain_zap`

Minecraft: 1.15.2
Forge: 31.2.36
Apotheosis: 3.2.4
Placebo: 3.1.0

latest log:
https://gist.github.com/Yourname942/0b9ad3c58aa7cd2be14bd99417be330d

**Comment by Shadows-of-Fire** [comment]
this isn't a real bug, that sound is never used, it just was never removed
