### ISSUE TITLE
[modloading-worker-12/ERROR]

### ISSUE THREAD

**Issue by Yourname942** [Shadows-of-Fire/Apotheosis#203]
`[modloading-worker-12/ERROR]: A mod has attempted to access enchantment information before Apotheosis init, this should not happen.`

**Expected Behaviour**
There should be no errors from your mod when all I did was create a new world and enter it.

**Environment**
- Minecraft: 1.15.2
- Forge version: 31.2.36
- Apotheosis version: 3.2.4
- Placebo: 3.1.0
- Modpack: [Here](https://drive.google.com/file/d/126bE2LKzqLVMNnAcr4jx_lkD2Cm08wpR/view)

**Latest log** [Here](https://gist.github.com/Yourname942/41b2a7d4b9aac14ea7416df2fb18c19a#file-latest-log-6-55pm-8_16_20)

**Highlighted Log Section** [Here](https://gist.github.com/Yourname942/41b2a7d4b9aac14ea7416df2fb18c19a#file-latest-log-6-55pm-8_16_20-L212-L1625)

**Steps to reproduce**
1. Select Play in Twitch App
2. Select Play in Minecraft Launcher
3. Create a new world
4. Enter world
5. Exit Minecraft

**Comment by Shadows-of-Fire** [comment]
This is a bug in whatever mod adds this class `at com.stereowalker.combat.event.AbominationEvents.<clinit>(AbominationEvents`, as they are attempting to access enchantments before they are registered.
You'll have to take it up with them.
