### ISSUE TITLE
Dedicated Server - Fatal Error

### ISSUE THREAD

**Issue by bizfish** [Shadows-of-Fire/Apotheosis#204]
Apotheosis-1.16.1-4.1.0.jar causes fatal error when loading dedicated server. Reverting to Apotheosis-1.16.1-4.0.1.jar resolves the issue. Debug log attached. See line 757:
`[18Aug2020 16:44:27.262] [main/FATAL] [cpw.mods.modlauncher.TransformerClassWriter/]: Class net/minecraft/entity/IRendersAsItem unable to find resource null`
[debug-5.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5093115/debug-5.log)

**Comment by Shadows-of-Fire** [comment]
Well, what I can tell you is that error is right, that's a client-only class.  However, Apoth does not interact with the class noted in this error, and Apoth loads fine on a dedicated server on it's own (with Placebo, JEI, and HWYLA installed).  I suppose this is probably an ASM conflict between a mod with a mixin and Apotheosis, but the only ASM added in 4.1.0 was related to Crescendo of Bolts (Crossbow stuff).  From the looks of it, there is another mod with a mixin into the same location, but you'd have to figure out what mod it is before any fixes can be attempted.

**Comment by vertex101** [comment]
I am having the same issue with the latest version loading on a server i even went and made a test server with nothing but Apotheosis and i still get the same error with no other mods

**Comment by vertex101** [comment]
umm i was looking through the code in the crossbow js file u have this here

`
'apothshieldblock': {
            'target': {
                'type': 'METHOD',
                'class': 'net.minecraft.item.CrossbowItem',
                'methodName': 'func_77659_a',
                'methodDesc': '(Lnet/minecraft/world/World;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Hand;)Lnet/minecraft/util/ActionResult;'
            }
`

i was wondering if it should be like this

`
'apothshieldblock': {
            'target': {
                'type': 'METHOD',
                'class': 'net.minecraft.item.CrossbowItem',
                'methodName': 'func_77659_a',
                'methodDesc': '(Lnet/minecraft/world/World;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/util/Hand;Lnet/minecraft/util/ActionResult;)'
            }
`

**Comment by bizfish** [comment]
I still get the same crash on a dedicated server on it's own (with, and also without Placebo, JEI, and HWYLA installed). 
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5104058/debug.log)

**Comment by Shadows-of-Fire** [comment]
Interesting, and no, that method signature is correct, it's `(<params>)<return type>`.
That method access appears to be attempting to resolve a class and trying to reference that client only class that doesn't exist.  
That's weird because nothing in CrossbowItem even references the class in question at all.

**Comment by Shadows-of-Fire** [comment]
Could anyone that is experiencing the error let me know if this fixes the issue https://github.com/Shadows-of-Fire/Apotheosis/releases/download/4.1.1/Apotheosis-1.16.1-4.1.1.jar

**Comment by bizfish** [comment]
Launches fine for me with that one now, both alone with Placebo, JEI, and HWYLA installed, and also with all the mods I run.

**Comment by Shadows-of-Fire** [comment]
Well, it's a stupid fix, but it tricks the class verifier into working right.
So I suppose it's good enough

**Comment by Darkere** [comment]
This sounds like it's the same problem ? https://gist.github.com/MaxFirestorm/916243949f4c9356db3bd44555eccd2a

**Comment by Shadows-of-Fire** [comment]
Probably a side effect of the trash hack fix, I'm waiting for cpw to let me know whats happening with the asm

**Comment by Shadows-of-Fire** [comment]
This should be actually fixed in 4.1.2, this issue is apparently a modlauncher/FML bug that I have no control over, other than attempting to provide the erroneously loaded class.

**Comment by Shadows-of-Fire** [comment]
The mc copy class can be removed when https://github.com/cpw/modlauncher/issues/57 is resolved

**Comment by ichttt** [comment]
You should be able to remove the workaround now, the issue has been fixes in modlauncher
