### ISSUE TITLE
most of the recipes are missing and hellsheves are not craftable.

### ISSUE THREAD

**Issue by TALchemist5** [Shadows-of-Fire/Apotheosis#206]
I started with the Valhalsia 3 modpack then added the 1.16 version of Apotheosis because I just prefer to have this mod.  but almost nothing is craftable for the mod.  I even went online and found the recipe for hellshelf and I cannot create it.  no errors are being created it just wont craft.  JEI shows all the items, but no recipes exist for it?

Forge: 32.0.106
Minecraft: 1.16.1

if you need anything else just let me know.

edit:  this may be a moot point, I just realized I am using the apotheosis 4.0.0 which was beta.  I will download the latest version once I get home and will update for it that fixes it.

**Comment by TALchemist5** [comment]
Ok after updating to the latest version the recipes are all there and everything is craftable.  The only question is the enchanting of hellshelves different from standard enchanting?  If I put a hellshelf I'm the enchanter it just says limited enchantability.

**Comment by Shadows-of-Fire** [comment]
You'll need to be at least level 45 to enchant a hellshelf, and then its up to luck for hell infusion to appear.  Enchant smth else if all slots say limited, and try again.
