### ISSUE TITLE
[1.16.1] Crash with your modified spawners

### ISSUE THREAD

**Issue by TheSnowyChickens** [Shadows-of-Fire/Apotheosis#207]
Hello,
we have some problems on our server with your spawners, 1 member of the server created a little mod farm and fucked up his area. (aka everytime he enter a specific chunk, the server say "bye bye")

We use the Enigmatica 6 modpack with version 0.2.10. (Apotheosis-4.1.0 - Forge 108, but the same behavior with v4.1.2 with Enigmatica 0.2.11 (I updated the mod manually, 4.1.1 is normally installed in 0.2.11))

Area with disabled spawner module via config (I can't even see this area with activated spawner module)
![2020-08-23_04 26 24](https://user-images.githubusercontent.com/29357962/90969475-6f172980-e4f9-11ea-8f9f-1aa7d89a22ce.png)

I can't tell you, which upgrades he has installed. (I tell him about my issue here so he add the info)

Log -> 
[2020-08-23-1.log.gz](https://github.com/Shadows-of-Fire/Apotheosis/files/5113420/2020-08-23-1.log.gz)

I can't give you a crash log, because the server can't even create one. (I created a fresh new server to test it with only our map) 
(I enter the chunk and 100% freeze (that's all what I can say))

I also tested the Forge options for problematic entities / tile entities, but no better result.

![grafik](https://user-images.githubusercontent.com/29357962/90969727-29a82b80-e4fc-11ea-83d3-6dc65c4ba7cf.png)

I hope you can help us. :)

**Comment by Fuggschen** [comment]
I have more Infos for you.
In total there are 9 blaze spawner. All of them have maximum sugar and clock modifiers and only one has the nether star upgrade and four prisma shards uprades.

It was running fine and the chunk should be chunkloaded so that the Mob Crusher keeps working but the server just stops if I try to login next to the spawner.

I also tried the map in singleplayer and it loads but the game is instantly freezing and crashes.

**Comment by Shadows-of-Fire** [comment]
Well, depending on your configs, that level of upgrade is capable of just grinding your server to a halt.  If your configs predate the defaults on modifier limits, and have all of the limits as [0, +inf), then 9 spawners like that would just actually use up every resource on spawning.

I doubt there's any actual infinite loop hanging being caused (as the spawner code has no while loops or unbounded for loops),  In the case it was that, you could create a stall report with a profiling software like VisualVM.

If it's the first case, I'd advise you set caps in your configs and remove the spawners while the module is off to prevent it occuring again.  The caps exist for a reason.  If it's the second case, generate and send me the stall report and I can take a look into why it's stalling at a given point.

**Comment by TheSnowyChickens** [comment]
Okay, we tested some limit settings and with a low amount we was able to manage it and the area could be loaded again.

Sometimes it is so easy to fix, but we needed first your hint. ^^

I close this issue now and ty for all. :)
