### ISSUE TITLE
Apotheosis Health Glitch? 

### ISSUE THREAD

**Issue by Joshhii** [Shadows-of-Fire/Apotheosis#208]
I have a rare helmet which one of the 'affix/s' give me a health boost of 2.88 hearts when wearing it. But if i die while having it on my head, then it keeps the hearts and gives me even more hearts. So lets say i was on the norm 10 hearts then it goes to 12 then 14 etc. It super annoying as it breaks the game and it fills up my screen way to much, please fix this asap, TY! (btw this is for 1.16.1) if you need the version then i'll send that too :D

**Comment by Shadows-of-Fire** [comment]
The attribute modifiers on items are applied via the same way you could nbt edit them in, in vanilla.  There's no custom systems at work here, so there's no code for me to fix.  If anything, it might be a vanilla bug or even a forge bug, but it's not anything I can fix.
