### ISSUE TITLE
Eterna lv does not seem to be responding to bookshelves

### ISSUE THREAD

**Issue by IOnlyFetchBranches** [Shadows-of-Fire/Apotheosis#209]
Hello, 

Hopefully this is the right place, i've looked all over to make sure i had it setup correctly. I've checked the configs and the logs and I'm not seeing any warnings or anything. I've tried several placement combinations of the bookshelves with the table. I am aware each type of bookshelve can only increase  stats to a certain point. However if you look below I have the following placement of normal bookshelves, it says it should increase Eterna up until 15.0
![image](https://user-images.githubusercontent.com/23384158/90990673-850c0500-e560-11ea-8821-7f846ade27d2.png)

Based on what I've seen online, this should be a proper configuration of the bookshelves. And with each one adding +1, I should also be under the max for normal shelves.
But still:
![image](https://user-images.githubusercontent.com/23384158/90990694-ac62d200-e560-11ea-8d1f-fcaf788696d3.png)

I am using Forge Loader beta, but as mentioned earlier I didn't see any errors or anything in the logs, nor do i have any other mod that would effect enchants. Infact I got Apotheosis FOR the enchant mod :)

Anyways, I couldn't find anything in the curse description about it and I'm not sure if maybe I've just missed anything (is it all or nothing? ie, no +1 it must be +15)  or this is some weird bug. Any help would be appreciated!

Thanks

**Comment by Shadows-of-Fire** [comment]
Levels are only calculated when an item is placed in the table, so this configuration probably does provide 15 Eterna, but it is not calculated due to how the table works.

As long as the stats are present on the item's tooltip, they will be included if in the normal table search space.
