### ISSUE TITLE
[1.16] Can't remove rare enchantments

### ISSUE THREAD

**Issue by hgiabao** [Shadows-of-Fire/Apotheosis#211]
Rare enchantments can no longer be removed by grindstone or any other 3rd party enchantment remover. Is this intended?

**Comment by Shadows-of-Fire** [comment]
what do you mean by rare enchantments?

**Comment by hgiabao** [comment]
Enchantments with colored text, e.g., Berserker's Fury, Life Mending, Scavenger,...
When i put an enchanted item in the grindstone, all enchantments is removed except for these rare enchantments.

**Comment by Shadows-of-Fire** [comment]
Fury and Life Mending are curses, so unless those things handle curses they wont be able to do anything about it.
Scavenger is not a curse, and just has green formatting on the name, I assume its just those two
