### ISSUE TITLE
Affix Shovel is Pickaxe

### ISSUE THREAD

**Issue by GamerXD8991** [Shadows-of-Fire/Apotheosis#212]
MC Version 1.16.1
Mod Version 4.1.2

Apparently a Shovel with the effect/text "This tool has diamond effectiveness against all blocks" is able to work as pickaxe (as in it breaks and drops stone). Is this intended behavior? 
![affixShovel](https://user-images.githubusercontent.com/40356877/91707509-307c1180-eb80-11ea-9ff9-71437052db38.PNG)

**Comment by Shadows-of-Fire** [comment]
ye
