### ISSUE TITLE
Error: Render Overlay Exit Code Error: -1 (1.16.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [Shadows-of-Fire/Apotheosis#214]
Hi there,

It appears that this mod is just causing a crash to desktop while almost getting to the final step in the loading screen. Error is what is in the title

Minecraft: 1.16.2
Forge 33.0.42
Apotheosis: 4.2.1
Crash Report: https://gist.github.com/DatrixTHLK/66f9051a61096925c965659d51c1211d

Taking your mod out causes my game to work just fine.

**Comment by Shadows-of-Fire** [comment]
Apotheosis requires Placebo, which you do not have.  Forge's dependency error screen is broken, so the crash is just from forge.

**Comment by DatrixTHLK** [comment]
Ok, thanks!
