### ISSUE TITLE
[1.16.1] Deadly modules dimension whitelist is ignored

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#217]
This bug was observed on a stream, so I'm unsure as to the exact version of Apotheosis. My best guess is `Apotheosis-1.16.1-4.1.3`

Apotheosis bosses spawn in the end despite config specifying them may only spawn in the overworld.

Dimension whitelist config:
```cfg
    # The dimensions that the deadly module will generate in. [default: [overworld]]
    S:"Generation Dimension Whitelist" <
        overworld
     >
```

**Comment by Shadows-of-Fire** [comment]
Yeah its inoperable in 1.16.1, the way dimensions got rewritten leaves no nice way to check what dim is where.
Its possible in 1.16.2 but the feature needs to be reimplemented

**Comment by NielsPilgaard** [comment]
Alright, thanks for the swift answer.

**Comment by Shadows-of-Fire** [comment]
Reimplemented in 7b7e42b
