### ISSUE TITLE
Latest version crashing on startup

### ISSUE THREAD

**Issue by DeFYzz** [Shadows-of-Fire/Apotheosis#219]
Version: 1.15.2
Apotheosis: 3.3.4

Crashing on startup. Also the 'names.cfg' file is empty. Dont know if thats why. Deleting configs does not help.

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5212840/latest.log)

**Comment by OldePSN00b** [comment]
Same issue here.

**Comment by DeFYzz** [comment]
Also the game starts when disabling the 'Deadly' module.
