### ISSUE TITLE
No netherite

### ISSUE THREAD

**Issue by ShadyThePenN** [Shadows-of-Fire/Apotheosis#222]
No netherite is spawning in my world after removing all mods and resetting my nether my netherite came back I then narrowed 
All my mods down to this one removing my nether ores

**Comment by Shadows-of-Fire** [comment]
mod version / mc version / forge version / debug.log

**Comment by ShadyThePenN** [comment]
Mod version: Apotheosis-1.16.3-4.2.0
Mc version:1.16.3
Forge Version:1.16.3-forge-34.0.1
Debug.log: 
![Capture](https://user-images.githubusercontent.com/71346288/93251783-7b358600-f749-11ea-891a-121a1c9a2601.PNG)

**Comment by Shadows-of-Fire** [comment]
The mod version you have specified "1.16.3-4.2.0" does not exist.  The latest is "1.16.2-4.2.1", use that one.

**Comment by ShadyThePenN** [comment]
omg im so dumb thank you
