### ISSUE TITLE
[Enhancement] Craftweaker / datapack support for enchantment block values

### ISSUE THREAD

**Issue by tlitookilakin** [Shadows-of-Fire/Apotheosis#223]
I think it would be helpful for modpack makers to have the ability to add custom enchanting stats to blocks, either via datapacks (in the form of recipe jsons) or via a craftweaker api. I'd like to use this feature to add custom Eterna, Quanta, and Arcana values to existing blocks from other mods. (If it's exposed as a public API, it could also be useful for other modders wanting to add integration.)

**Comment by Shadows-of-Fire** [comment]
That exists, it's just only supported in 1.15 for the time being.  Development will be resumed on 1.16 after forge is stable.  The format is here: https://github.com/Shadows-of-Fire/Apotheosis/tree/1.15/src/main/resources/data/apotheosis/enchanting_stats

**Comment by tlitookilakin** [comment]
oh, thanks! I'm actually making a pack in 1.15 so this is perfect :) I guess it hadn't occurred to me to check an older version of the source. ;P Thanks a bunch!
