### ISSUE TITLE
[1.16.1] Crash when attempting to rename an item in a Mekanism Robit that's not docked

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#224]
Relayed from: https://github.com/mekanism/Mekanism/issues/6570

#### Issue description:
Crash when attempting to rename an item in a Robit that's not docked.

I use Robit's all the time as anvils, but they're typically docked when doing so. The last two times I've tried renaming something, I had the Robit in follow mode and it resulted in a crash.

#### Steps to reproduce:
1. Make and place Robit
2. Try to rename something using the Robit's built in Anvil
3. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-32.0.108
**Mekanism:** 1.16.1-10.0.9.432 
**Apotheosis:** 1.16.1-4.1.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2020-09-22_11.04.52-client.txt](https://github.com/NillerMedDild/Enigmatica6/files/5262381/crash-2020-09-22_11.04.52-client.txt)

Edit: Please see https://github.com/mekanism/Mekanism/issues/6570#issuecomment-696945231

**Comment by Shadows-of-Fire** [comment]
wot

**Comment by Shadows-of-Fire** [comment]
resolved by mek
