### ISSUE TITLE
[1.15.2] Can't add enchantments from Tomes of Scrapping to items

### ISSUE THREAD

**Issue by DessertOverlord** [Shadows-of-Fire/Apotheosis#225]
Tomes of Scrapping that are enchanted (via combining them with items in an anvil) don't function like normal enchanted books, and thus can't impart their enchantments to items in an anvil.

![image](https://user-images.githubusercontent.com/16036856/94372932-abb8e080-00b6-11eb-976d-17e624e70911.png)
![image](https://user-images.githubusercontent.com/16036856/94372934-b2dfee80-00b6-11eb-9d16-a1572db81785.png)
![image](https://user-images.githubusercontent.com/16036856/94372936-b96e6600-00b6-11eb-8bae-9e46e6398c25.png)
![image](https://user-images.githubusercontent.com/16036856/94372938-be331a00-00b6-11eb-9f5e-c6f2a5a5fdbc.png)

**Comment by Shadows-of-Fire** [comment]
Tomes of scrapping are converted to enchanted books upon use, if they arent, you need to update your apoth version

**Comment by DessertOverlord** [comment]
After trying it again just now, you're correct. Sorry for the unnecessary issue,
