### ISSUE TITLE
[1.16.3] Bosses lose 50% max HP on generation

### ISSUE THREAD

**Issue by TheFantasticLoki** [Shadows-of-Fire/Apotheosis#226]
I wanted to make the bosses a fair bit harder since bosses got VERY easy once we got into the beginning of the mid game stage. All I did was change     S:"Max Health Multiplier"=6.0 to     S:"Max Health Multiplier"=18.0 and the min health to 6 as well as adjust a couple spawner variables to make cave spiders a little less frequent. But now all "BOSS" mobs just have the normal 20HP even after reverting changes.

**Comment by Shadows-of-Fire** [comment]
Bosses are generated at worldgen, so be sure you're only looking in new chunks after changing the values.
Also, you may need AttributeFix to use higher multiplier values since attributes break above a certain threshold

**Comment by TheFantasticLoki** [comment]
I already have attribute fix and yes I was looking in new chunks using the end bug to easily spot the bosses.

**Comment by Shadows-of-Fire** [comment]
I'm not experiencing that behavior ![](https://i.imgur.com/Vvx4yxF.png)
Bosses are retaining their hp modifiers just fine, this one was generated with a range of 9x - 18x

**Comment by Shadows-of-Fire** [comment]
Interestingly enough, upon further inspection, boss hp is being cut in half for some reason after generation.  It's fine when they're added to the world, but once generation finishes and the entity is recreated, it loses half of it's health.

**Comment by TheFantasticLoki** [comment]
Well glad I could help find that bug. also I am on 1.16.1 version of the mod because I am playing the All The Mods 6 Pack.

**Comment by Shadows-of-Fire** [comment]
Upon *even further* inspection, what I'm seeing is a hwyla bug on entity hp values being displayed: https://github.com/TehNut/HWYLA/pull/298
So this isn't a real issue, it seems.
