### ISSUE TITLE
[1.16.3] Crash when loading

### ISSUE THREAD

**Issue by TheonGray** [Shadows-of-Fire/Apotheosis#230]
Hii! I'm getting this Error code when trying to load the game with the mod installed:
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry
Exit Code: -1
I'm using Forge-1.16.3-34.1.0 and Apotheosis-1.16.3-4.3.1

**Comment by Shadows-of-Fire** [comment]
Thats probably an asm conflict with another mod, you'll have to figure out what it is and remove it, there's no way for me to tell you what it is
