### ISSUE TITLE
Arcana question

### ISSUE THREAD

**Issue by NotWu** [Shadows-of-Fire/Apotheosis#231]
Cant seem to find any guides or information on the new enchantment and how to raise arcana and quanta any help would be appreciated

**Comment by NotWu** [comment]
Also the enchanted weapons dont feel like theyre doing the proper damage like sharper 8 and smite 8 arent one shotting zombies

**Comment by Shadows-of-Fire** [comment]
You should read the curseforge page.

**Comment by NotWu** [comment]
I figured out the arcana and quanta issue but still cant figure out the enchantments not having their full damage effect

**Comment by Shadows-of-Fire** [comment]
Enchanting levels past default are supported by vanilla, so you may want to assess if something else is breaking it.  It works fine for me.
