### ISSUE TITLE
Enchanting table won't detect more than 15 bookshelves

### ISSUE THREAD

**Issue by therealepicgamer** [Shadows-of-Fire/Apotheosis#236]
I had about 50 mods. Enchanting table couldn't get above level 60 (with 15 enchanted hellshelves). Took out all the other mods, same thing happened. Tried reinstalling apotheosis + placebo. Still nothing. What else can I try?

**Comment by Shadows-of-Fire** [comment]
Nothing, thats working as intended

**Comment by therealepicgamer** [comment]
I thought max enchantment level with this mod was supposed to be level 150?
