### ISSUE TITLE
Error occurred during loading 1.16.3

### ISSUE THREAD

**Issue by thisoldTH** [Shadows-of-Fire/Apotheosis#238]
Hello, I'm not able to join the game when i put Apotheosis mod inside my mod folder, it says "error during the common_setup event phase". Im on minecraft 1.16.3-forge-34.1.0 and Placebo-1.16.3-4.3.2( i tried with version 4.3.1 but nothing changed)
this is my latest log.
[latestlog.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5358849/latestlog.txt)
tell me if some more files are needed because im new to trying out mods. have a nice day.

**Comment by Shadows-of-Fire** [comment]
bug in morevanillalib
