### ISSUE TITLE
failure to join server with recent apotheosis and quark

### ISSUE THREAD

**Issue by jblosser** [Shadows-of-Fire/Apotheosis#239]
This quark issue: https://github.com/Vazkii/Quark/issues/2556 only occurs when recent versions of Apotheosis are also installed, in both 1.15.x and 1.16.x. The specifics of the error vary based on versions but the essence is that the player cannot join the server with debug errors about the registry and quark:matrix_enchanting. An example debug log is included in that quark report.

I'm running 1.15.2 and the error occurs with Apotheosis-1.15.2-3.3.7.jar, however it does not occur with Apotheosis-1.15.2-3.3.5.jar. I'm not running 1.16.x so I didn't try to find a working combination there.

**Comment by Shadows-of-Fire** [comment]
The enchanting module of apoth is fully incompatible with matrix enchanting.  When the ench module is enabled, it will forcibly deny usage of the matrix enchanting module.

What conditions is this being run under?  This hook has existed for a while with no problems reported
By what conditions I mean what main content modules are active on each end (is matrix active, is ench active, are configs consistent on sides?)

Is this consistently reproducible or a random occurrence?

**Comment by jblosser** [comment]
I can reproduce it 100% of the time on a 1.15.2 server at any recent Quark version with Apotheosis 3.3.7 (but not 3.3.5) with matrix and ench both disabled (matrix disabled either individually or by disabling oddities entirely) and configs consistent on both sides (same file copied via scp).

**Comment by jblosser** [comment]
Ok it worked with 3.3.5 for a while (through multiple quit/reconnects as I test other things) but then I accidentally closed the client without disconnecting first and then I got the same error. And once it started, it was 100% of the time. Removing apoth from server and client mod lists made it work again, putting it back and it failed.

On a whim I put 3.3.7 back in, but that didn't fix anything (added mod to server and client, removed config on server and client, started server, stopped server, disabled ench, started server, copied config to client). I then switched to 3.3.0, and it works. I re-upgraded to 3.3.5, and it still works.

Is it possible vs a specific code change that whatever is being done to disable matrix is getting corrupted on the client side sometimes? And that it has a component that only runs during an initial install or a downgrade, so it can't resolve itself on a server or client restart?

**Comment by Shadows-of-Fire** [comment]
Well, what's most confusing is this appears to be happening with both modules disabled?  If the matrix enchanting module is disabled, there shouldn't be any issues with matrix enchanting stuff missing since it's not enabled in the first place.

It's possible the value of the configs aren't being read before the matrix enchanting file loads, then it may pose a problem.  Since mod loading is threaded, that's technically possible, and only a problem if the enchanting module is disabled.

Could you edit the mods.toml file in the jar to contain this entry
```
[[dependencies.apotheosis]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="BEFORE"
    side="BOTH"
```
and see if this fixes the load issue?  This should be added to the bottom of the file, and if that doesn't fix it, check with `ordering="AFTER"` as well, because I'm not sure of which goes after which in the dependency rules anymore.

Technically forcing apoth to load first should guarantee that this issue stops happening.

**Comment by jblosser** [comment]
Yeah, that makes sense. I'll try the ordering rule next time it happens. I haven't been able to force it when it's not happening (and I'm back on 3.3.7 now without a problem, FWIW).

**Comment by duckman** [comment]
I tried this out and the ordering="AFTER" did the trick. because this is kind of a random issue, can't guarantee this fixed it, but I am able to connect to my server for the first time in a week so I'm pretty stoked.

**Comment by Shadows-of-Fire** [comment]
The only important thing to check is with the ordering rules in place, do all config configurations between matrix and ench module still function properly

**Comment by Londran** [comment]
I can confirm this works in valhelsia 3 (MC 1.16) too and solves the issue with quark, as far as I can tell.

**Comment by Shadows-of-Fire** [comment]
Just to be certain, ordering="AFTER" fixes the issue, and the enchanting module/matrix enchanting both function properly when the other is disabled?

**Comment by Shadows-of-Fire** [comment]
Upon confirmation with some forge things, that ordering thing has nothing to do with the underlying cause of this issue.  Would anyone like to test and see if the issue is no longer present with this file https://github.com/Shadows-of-Fire/Apotheosis/releases/tag/338dev

**Comment by martindanielsson** [comment]
> Upon confirmation with some forge things, that ordering thing has nothing to do with the underlying cause of this issue. Would anyone like to test and see if the issue is no longer present with this file https://github.com/Shadows-of-Fire/Apotheosis/releases/tag/338dev

That's a 1.15 release yeah?

**Comment by Shadows-of-Fire** [comment]
yeah

**Comment by Shadows-of-Fire** [comment]
Was anyone able to successfully test that jar?

**Comment by duckman** [comment]
I'm using 1.16 so sadly no.

**Comment by martindanielsson** [comment]
> I'm using 1.16 so sadly no.

Same, I'm using Valhelsia 3 modpack which is 1.16.1

**Comment by Shadows-of-Fire** [comment]
@jblosser can you see if that 1.15 release works in that environment?

**Comment by jblosser** [comment]
Ironically I haven't had it show up again despite continually swapping around mods and rebuilding a server for days. The original 100% repro isn't working anymore (with nothing changed). Clearly it's some kind of non-deterministic thing. I'll try harder to force it this weekend.

**Comment by Shadows-of-Fire** [comment]
Based on the code paths, I'm gonna assume that this fix works.

**Comment by jblosser** [comment]
It showed up again on a server restart so I upgraded and it went away, hopefully that wasn't just from another restart.

BTW, I am on 1.15.2 (and thanks for fixing it there!) but for 1.16, Quark's only on 1.16.1 vs .3, would you consider backporting so the 1.16 people can benefit from this fix?

Regardless, thanks for the fix.

**Comment by Shadows-of-Fire** [comment]
There are not and never have been plans to support 1.16.1 (the latest 1.16.1 build has a bunch of glaring major issues as-is, and is not on par with either the 1.15.2 or 1.16.3 branches).

**Comment by dinomiteX** [comment]
> I can confirm this works in valhelsia 3 (MC 1.16) too and solves the issue with quark, as far as I can tell.

Hey Londran, we have the same issue with Valhelsia 3. What did you do to solve the issue. We tried to edit the mods.toml with the aboce solutions but that didnt solve the problem for us.
