### ISSUE TITLE
Odd boss platform spawning

### ISSUE THREAD

**Issue by BugmanBugman** [Shadows-of-Fire/Apotheosis#240]
![2020-10-13_21 19 44](https://user-images.githubusercontent.com/40730042/96042054-6b858c00-0e32-11eb-90c9-3962cceadd22.png)
Sometimes the boss platforms spawn in odd places, such as the one above where it intersected with a stronghold tunnel. Is there a way to add checks so the platforms spawn in more open areas?

**Comment by Shadows-of-Fire** [comment]
Boss world gen is being redone next update, so this won't happen anymore.  Red sandstone platforms won't even be a thing anymore, actually.
