### ISSUE TITLE
[BUG] Flying is not Enabled.

### ISSUE THREAD

**Issue by MypowerHD** [Shadows-of-Fire/Apotheosis#242]
If players hit another player with rebound they will be catapulted very far and kicked by the server because flying is not enabled.
Other mods manage to prevent this from happening, is it possible to integrate this into the mod?

**Comment by Shadows-of-Fire** [comment]
Imo the flying check is just broken, I'd suggest you disable it.  You can get kicked for flying if you are jumping when you right click on a bed.  The rebounding enchantment is just a velocity manipulation, so it doesn't retain a player reference to constantly update and change the flying timer.

**Comment by MypowerHD** [comment]
sorry but you are 100% wrong, the check is not broken and your statement is factually wrong under 1.16.3 (other versions not tested).

Other mods also use speed manipulation and you won't get kicked.

> Imo the flying check is just broken, I'd suggest you disable it. You can get kicked for flying if you are jumping when you right click on a bed.
sorry but you are 100% wrong, the check is not broken and your statement is factually wrong under 1.16.3 (other versions not tested).

>The rebounding enchantment is just a velocity manipulation, so it doesn't retain a player reference to constantly update and change the flying timer.
Other mods also use speed manipulation and you won't get kicked.

**Comment by MypowerHD** [comment]
> 
> Imo the flying check is just broken, I'd suggest you disable it. You can get kicked for flying if you are jumping when you right click on a bed. 

sorry but you are 100% wrong, the check is not broken and your statement is factually wrong under 1.16.3 (other versions not tested).


>
> The rebounding enchantment is just a velocity manipulation, so it doesn't retain a player reference to constantly update and change the flying timer.

Other mods also use speed manipulation and you won't get kicked.

**Comment by Shadows-of-Fire** [comment]
Looks like vanilla employed a very nice bandaid of "don't kick if sleeping" to fix that issue in 16.3.
I still don't see why you can't just disable the flying checks to begin with, any employment of fixing it would basically just be disabling it until the player hits the ground again.

**Comment by MypowerHD** [comment]
So you mean to tell me, I should only deactivate it because of a mod? I currently don't have the time to write a fix myself and just don't see it as setting the option to false because it is not a bugfix. It's just a ridiculous way around a problem.

Maybe I am the only one who is so meticulous and not just messing around with any ridiculous settings on the server just because a single mod has not integrated a bypass.
That would be as if I were setting up a vpn but still had all system-relevant services accessible from the outside and my root password would be root.
