### ISSUE TITLE
[1.16.3] V:4.3.1 at ATM6-Pack, Enchanting Stats at the Shelfs not shown

### ISSUE THREAD

**Issue by Sclane1** [Shadows-of-Fire/Apotheosis#243]
Hello,

Vanilla Bookshelfs and ohters at (First Level) all have the "Enchanting Stats: Eterna +1.00"
but only the next tier Item "Hellshelf" and "Seeshelf" has an "Enchanting Stats: Eterna +1.50 and Quanta +1.50"

And i know from Valhelsia, the last tier "Endshelf" has "Enchanting Stats" too.

In addition, the extended Hellshelf, Seeshelf and Endshelf do not have Enchanting Stats too, in ATM6.

Is it the Pack or is the Mod? I dont know.

Thanks
Bye bye

![Enchanting Stats](https://user-images.githubusercontent.com/29591130/96521318-48633e00-1271-11eb-8667-5f07998e87ac.jpg)
![Enchanting Stats2](https://user-images.githubusercontent.com/29591130/96521328-4ef1b580-1271-11eb-8daf-ce01382f410d.jpg)
![Enchanting Stats3](https://user-images.githubusercontent.com/29591130/96521335-531dd300-1271-11eb-84aa-507230fdc0e4.jpg)
![Enchanting Stats4](https://user-images.githubusercontent.com/29591130/96521339-54e79680-1271-11eb-8c05-39a5205963dc.jpg)

**Comment by Shadows-of-Fire** [comment]
This is the issue that 4.3.2 fixes.

**Comment by Shadows-of-Fire** [comment]
Note that while 4.3.2 fixes that issue, searching for stats in jei will not show the items as that is blocked by forge: https://github.com/MinecraftForge/MinecraftForge/pull/7410
