### ISSUE TITLE
possible 1.16.3 bug

### ISSUE THREAD

**Issue by Warbringer12** [Shadows-of-Fire/Apotheosis#244]
don't know if this a bug for your mod or not its popping up first as yours

[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5417488/debug.log)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5417489/latest.log)
[crash-2020-10-21_09.39.09-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5417492/crash-2020-10-21_09.39.09-client.txt)

**Comment by Shadows-of-Fire** [comment]
That's a coremod conflict, not really a mod bug, just means you have something that you can't run with apoth installed.
