### ISSUE TITLE
[1.15.2] Server crash with anvil

### ISSUE THREAD

**Issue by IzzelAliz** [Shadows-of-Fire/Apotheosis#247]
Minecraft 1.15.2
Forge 31.2.45
Apotheosis 3.3.8

Crash report https://paste.ubuntu.com/p/dB7TnWtR92/

**Comment by Shadows-of-Fire** [comment]
MC 1.15.2 is not supported (somehow you have a null enchantment on your anvil, it looks like, so you may need to nuke said item)
