### ISSUE TITLE
Knowledge of the ages on players

### ISSUE THREAD

**Issue by Aphenon** [Shadows-of-Fire/Apotheosis#249]
Can you please disable this mod from turning player's items in to xp? accidental kills is making this enchant into an headache. or the ability to disable single enchants would also be healpful.

**Comment by Shadows-of-Fire** [comment]
KoTA does not execute on players https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/ench/EnchModuleEvents.java#L113
