### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vyraal1** [Shadows-of-Fire/Apotheosis#25]
https://pastebin.com/UChr2QpN

Saw this posted twice now on discord from two different users using MultiMC, any idea or if it's even Apotheosis's fault?

**Comment by Shadows-of-Fire** [comment]
This crash appears to be caused by a JVM implementation spec...

Until I get it fixed, tell users experiencing this crash to switch from OpenJDK to Oracle's JRE.

**Comment by Shadows-of-Fire** [comment]
Closed via 000e1cd
