### ISSUE TITLE
Anvil Tiers

### ISSUE THREAD

**Issue by Gabo6480** [Shadows-of-Fire/Apotheosis#251]
Combining enchantments through the anvil becomes increasingly pricier the greater the level, even though there are ways to grind huge amounts of experience at a time, there is moments where the price is just ridiculous, so any help on lowering that price might be worth considering.

The idea is to add new tiers of anvils to the enchantment module, the new tiers would be as follows:
Gold Anvil: less durability than iron (Greater chance of changing stages), better enchantability, lowers enchanting prices by a % (10% maybe?)
Netherite Anvil: end game oriented, more durability than iron, fire proof, better enchantability (But lower than gold), lowers prices by a grater percentage

The crafting recipes could just be replacing all iron for the corresponding block, but that might make netherite anvils waaaaay too expensive, so maybe the netherite variant would require diamonds and netherite in the recipe (To mimic the fact that for netherite armor you require a set of diamond armor), either that or add a Diamond Anvil that is just equal to an iron anvil but with greater durability and you can upgrade it to netherite using a netherite block in the smithing table idk

**Comment by Shadows-of-Fire** [comment]
The current plan is to change the math on that entirely.  However, it requires changes in forge first, which are pending.

**Comment by James103** [comment]
> The current plan is to change the math on that entirely. However, it requires changes in forge first, which are pending.

Which PRs are you waiting on? My best guess is https://github.com/MinecraftForge/MinecraftForge/pull/7442 (which is already merged).
