### ISSUE TITLE
A way to add custom bookshelves

### ISSUE THREAD

**Issue by TheSpicePhantom** [Shadows-of-Fire/Apotheosis#254]
I might just be blind on this one, but I'd like to add the dragon egg as "bookshelf" - just like Glowstone and the Jack o'Lantern.

Increase Eterna by 50 and set max to 200.
Increase Quanta by 200%.
Increase Arcana by 100%.

This is just an idea to give the dragon egg a decent use. I think of it as a way to increase the stats and not have it sit around on a random pedestal or maybe even have it in a chest.

**Comment by Shadows-of-Fire** [comment]
Any block can be given stats via datapack, this is how most apoth blocks are given their stats: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/resources/data/apotheosis/enchanting_stats/glowstone.json
