### ISSUE TITLE
Server sometimes crashes on startup

### ISSUE THREAD

**Issue by ViRb3** [Shadows-of-Fire/Apotheosis#256]
This is a weird one, it doesn't always happen, usually we keep rebooting until it succeeds. Log: https://mcpaste.io/a72b1daffb01dd95

**Comment by grydian** [comment]
I am getting this error everytime I try to load the server.  Any help would be greatly appreciated.

**Comment by Shadows-of-Fire** [comment]
Duplicate of #255 (bug in psi, must be resolved by them)
