### ISSUE TITLE
Suggestion - ToP support

### ISSUE THREAD

**Issue by Rithenar** [Shadows-of-Fire/Apotheosis#257]
When looking at an upgraded Spawner using The One Probe, I can see the name of the mob and the other vanilla information

![image](https://user-images.githubusercontent.com/9939332/100269589-667d2780-2f1c-11eb-8164-15128c9b48ba.png)

However, when I pick up the spawner I can see all the upgraded information on the tooltip

![image](https://user-images.githubusercontent.com/9939332/100269670-83195f80-2f1c-11eb-8315-44c84cde00d9.png)

Is this interaction something that could be added to Apotheosis or should I reach to the ToP devs?

**Comment by Shadows-of-Fire** [comment]
I would have to add it.  However I currently only support HWYLA as that is my preference in HUD mod and I don't really want to rewrite that compat.

**Comment by Danekjovax** [comment]
I second the motion to add this information via NEI or, alternatively, with a hand-held probe-type tool.

Thanks!

**Comment by Shadows-of-Fire** [comment]
4.8.999 or 5.3.0+
