### ISSUE TITLE
1.16.3 4.4.1 withering min/max power flipped?

### ISSUE THREAD

**Issue by RainnMannx** [Shadows-of-Fire/Apotheosis#258]
[Worker-Main-11/ERROR] [Apotheosis : Enchantment/]: Enchantment netherenhanced:withering has min/max power 220/200 at level 5, making this level unobtainable.

**Comment by Shadows-of-Fire** [comment]
That's just something that happens when scaling enchantments, you can either fix it manually via config or the providing mod would need to change their power formulas to not have different slopes.

**Comment by RoyalReject** [comment]
I hate to comment on this but how would i got about tweaking the scaling of enchants?
