### ISSUE TITLE
Swarm Spawner mobs plus Corail Tombstone Magic Siphon game balance

### ISSUE THREAD

**Issue by incomingnerd** [Shadows-of-Fire/Apotheosis#259]
**Problem**
Swarm Spawner mobs spawn with infinite duration potion effects. The Magic Siphon enchantment has a chance to transfer a positive potion effect from a slain mob to the player. This results in Swarm Spawner-based mob farms effectively granting massively overpowered infinitite duration buffs.

**Suggestion**
Add a (configurable) time limit to the buffs given to spawner spawned mobs. There's no practical reason why they need to be infinite duration.
Adding a similar option for boss mobs too, but with a default duration of several days would also prevent these from being abused too badly.

**Versions**
Minecraft 1.15.2
Apotheosis 1.15.2-3.3.8
Corail Tombstone 4.5.6

**Comment by Shadows-of-Fire** [comment]
That should be resolved by that mod, probably by capping the duration of the effects that are transferred to the player.  Potion effects on bosses are also infinite duration.

**Comment by Danekjovax** [comment]
I am observing this still in a modpack I am playing, Explorico 1.3.  

I originally posted about this here: https://github.com/Shadows-of-Fire/Apotheosis/issues/268

Versions as posted in the link above:
MC 1.16.2
Forge 1.16.4-35.1.4
Apotheosis 1.16.3-4.4.1
Tombstone 6.0.2
