### ISSUE TITLE
Crash upon entering Nether

### ISSUE THREAD

**Issue by viceroy369** [Shadows-of-Fire/Apotheosis#26]
I get this crash whenever I try to enter the nether with Apotheosis:

https://paste.dimdev.org/lezehokuwe.mccrash

Crash report says 'unknown' but I've tested and removing Apotheosis fixes it.

**Comment by Shadows-of-Fire** [comment]
This is a bug in Better Nether: https://github.com/paulevsGitch/BetterNether/issues/9
He appears to still have not fixed it.
