### ISSUE TITLE
Suggestion: Provide a way to disable Ignore Spawn Cap completely

### ISSUE THREAD

**Issue by incomingnerd** [Shadows-of-Fire/Apotheosis#260]
**Problem**
While it is possible to set the item for Ignore Spawn Cap to an unobtainable one, Swarm Spawners still generate with this enabled. Players can therefore still trivially obtain server-breaking spawners.

**Suggestion**
Add boolean config options for disabling the "Ignore X" modifiers completely, even for generated spawners.

**Comment by Shadows-of-Fire** [comment]
Swarm Spawners do not spawn with that modifier, only with the stats as described in https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/deadly/config/DeadlyConstants.java#L27
They do have a default spawn cap of 32, however.
