### ISSUE TITLE
Error occurred applying transform of coremod apothasm/container-repair.js

### ISSUE THREAD

**Issue by draklorx** [Shadows-of-Fire/Apotheosis#262]
Apotheosis mod version:
Apotheosis-1.16.3-4.4.1.jar

Forge version:
forge-1.16.4-35.0.17

[main/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod apothasm/container-repair.js function apothanvilcontainer
java.lang.NullPointerException: null

http://www.wizardbeardgames.com/temp/latest.log

I reported this on the discorrd November 13th, just now got around to reporting it here (sorry for the delay!)

Attached is the entire chat log:

**Kier11/13/2020**
When starting a server I'm getting this error. Anyone run into this before?
[main/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod apothasm/container-repair.js function apothanvilcontainer
java.lang.NullPointerException: null
**Shadows11/13/2020**
sounds like you have an incompatible coremod
probably anvil tweaks or smth
**Kier11/13/2020**
Oooh, ok. I have craft tweaker, and content tweaker, let me try rmoving those!
**Shadows11/13/2020**
no, it's neither of those
**Kier11/13/2020**
Yup. I'm cyling through my mod list.
**Kier11/13/2020**
Looks like it might be the illagers wear armor mod.
More specificall it looks like it's a combination of the illagers wear armor mod and the dungeon gear mod.
One or the other works fine, but when adding both it bugs out with apotheosis. I'll let the mod creator know.
Thanks guys!
**Shadows11/13/2020**
i can't see why a mod about illager armor is coremodding the anvil
**Kier11/13/2020**
It might be the dungeon gear mod. It interacts with the illagers wear armor mod to change the armor they can wear, and maybe they're doing some kinda core modding to interact with the other mod?
They look to be from different creators...
It seems like it might also be throwing the error when I have Valhelsia structures installed.
**Kier11/13/2020**
Looks like it's conflicting with the Storage Overhaul mod as well.
**Kier11/13/2020**
So it looks like it's conflicting with practical tools as well... it's weird. I'm going through and deleting mods one at a time until the error goes away, then I put all the mods back except that one, and go through the process again. The error stillg ets thrown until I remove the next mod that fixes it and put the others back.
I've presently put them all back save for illagers/valhelsia/storage overhaul/practical tools, and it's still throwing errors like another mod is conflicting.
**Shadows11/13/2020**
personally it sounds like your testing process is flawed
bc apoth is in valhelsia
so if you think it's possibly incompatible with v structs, then you're not testing correctly
**Kier11/13/2020**
http://www.wizardbeardgames.com/temp/latest.log
Here's my latest.log
This is ther error in question:

[14Nov2020 04:32:30.718] [main/ERROR] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod apothasm/container-repair.js function apothanvilcontainer
java.lang.NullPointerException: null
It's like if I delete enough other mods this particular error goes away.
**Shadows11/13/2020**
well it's either a mixin mod you're running, or it might be because you're using java 11
**Kier11/13/2020**
Ooooh java 11 sounds likely! Let me try removing that and installing the correct version...
**Kier11/13/2020**
I got this version installed:
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

Still looks like I'm getting the error.
I updted my latest.log
http://www.wizardbeardgames.com/temp/latest.log
**Shadows11/13/2020**
do you have a modlist available?
**Kier11/13/2020**
Apotheosis-1.16.3-4.4.1.jar
AutoRegLib-1.6-46.jar
backpacked-1.7.0-1.16.3.jar
buildersaddition-1.16.3-20201028b.jar
Clumps-6.0.0.12.jar
cobbler-1.6.1.jar
comforts-forge-1.16.4-4.0.0.2.jar
ContentTweaker-1.16-1.0.0.develop.9.jar
corpsecomplex-forge-1.16.3-4.0.0.2.jar
CosmeticArmorReworked-1.16.4-v1.jar
CraftTweaker-1.16.2-7.0.0.27.jar
DungeonCrawl-1.16.3-2.1.1.jar
dungeons_gear-1.16.4-3.0.1.jar
DungeonsMod-1.16.3-1.1.1.jar
extlights-3.1.jar
furniture-7.0.0-pre19-1.16.3.jar
goblintraders-1.2.2-1.16.3.jar
guardvillagers-1.16.3-1.1.5.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
ilikewood-1.16.3-4.0.2.2.jar
illagersweararmor-1.0.2.jar
InitialInventory-5.0.1.11.jar
jei-1.16.4-7.6.0.58.jar
mobcatcher-3.0.jar
mod_pack_2020-11-13.zip
NaturesCompass-1.16.3-1.8.5.jar
pamhc2foodcore-1.16.3-1.0.0.jar
pandoras_creatures-1.16.3-2.0.1.jar
Placebo-1.16.3-4.3.3.jar
practicaltools-1.16.3-1.8.jar
ProgressiveBosses-2.1.8-mc1.16.4.jar
Quark-r2.4-275.jar
repurposed_structures-1.16.3-2.2.11.jar
spiders-2.0-1.16.4-1.0.4.jar
storage_overhaul-1.16.4-1.0.1.jar
towers_of_the_wild-1.16.4-2.0.1.jar
valhelsia_structures-16.0.5.jar
Waystones_1.16.3-7.3.1.jar
Wyrmroost-1.16.3-1.2.7.jar
Xaeros_Minimap_20.27.2.1_Forge_1.16.4.jar
extlights and DungeonsMod are throwing their own errors. if I remove those the error still persists.
**Shadows11/13/2020**
Nothing immediately sticks out
possible vanilla has changed the anvil class in 16.4 - development is still on 16.3
Will have to update dev and check
**Kier11/13/2020**
There's nothing major that happens with apotheosis on world gen right? I can skip it for now, and add it in later?
**Shadows11/13/2020**
yeah
**Kier11/13/2020**
Thanks so much for looking at this with me. I really appreciate you!

**Comment by thepriz** [comment]
I can confirm I am getting this error also I don't have some of the mods that the user is using, but I some of them and others.

**Comment by Shadows-of-Fire** [comment]
this transformer should no longer crash when it fails.  the feature is still incompatible with whatever mod is making the transformer fail, however.
