### ISSUE TITLE
My game keeps crashing

### ISSUE THREAD

**Issue by CaoticDeity** [Shadows-of-Fire/Apotheosis#265]
This is the crash report
[crash-2020-12-05_10.34.53-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5647505/crash-2020-12-05_10.34.53-server.txt)

I can't even create a new world, I get the same error

**Comment by CaoticDeity** [comment]
I can't even create a new world, I get the same error

**Comment by xameryn** [comment]
Yup think I'm getting a similar error as well. Freezes at 0% when creating new world and requires task manager to be closed.

[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5723338/debug.log)

**Comment by GeekJokes** [comment]
similar problem, when i try to create a "caves" worldtype (i forgot what mod is adding that lol) loading gets stuck at 1% and crashes with error 0
[crash-2021-01-10_20.03.07-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5793631/crash-2021-01-10_20.03.07-server.txt)
other worldtypes, except for superflat, get stuck in loading and i have to close the game through the task manager
[crash-2021-01-10_20.54.34-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5793634/crash-2021-01-10_20.54.34-server.txt)

**Comment by GeekJokes** [comment]
turns out the caves worldtype is a vanilla thing, i totally forgot

**Comment by Shadows-of-Fire** [comment]
Deadly module worldgen is being rewritten, so this should vanish with that.
