### ISSUE TITLE
Mod causing server to crash on boot

### ISSUE THREAD

**Issue by purestone9** [Shadows-of-Fire/Apotheosis#267]
Im running an AllTheMods 6 Server and updated the Envirotech Mods and Valkarie Lib
After updating those mods Apothesis keeps causing the server to crash and run in a boot loop

Minecraft Version 1.16.4
Forge Version forge-1.16.4-35.1.4
Crash Log https://pastebin.com/yRtWurmj

**Comment by Shadows-of-Fire** [comment]
Duplicate of #255 (caused by psi, should be fixed on their end already)

**Comment by purestone9** [comment]
How dose Psi have anything to do with this?
