### ISSUE TITLE
I don't think the Eterna, Quanta and Arcana Enchanting will ever be compatible with Quark Oddities Enchanting Matrix?

### ISSUE THREAD

**Issue by Algester** [Shadows-of-Fire/Apotheosis#269]
since the 2 mods has options to overhaul the vanilla enchanting mechanics they will never play nice with each other? I did see Forgecraft does have the 2 mods installed so I'm not sure if there were any feedback when it came to the changes

**Comment by Shadows-of-Fire** [comment]
Apoth's enchanting module forcibly disables matrix enchanting if present, making it compatible would require the creation of a third merged system that supports both.
