### ISSUE TITLE
Crash, probably due to incompatibility with random potion effect chance and potioncore

### ISSUE THREAD

**Issue by edenhack** [Shadows-of-Fire/Apotheosis#27]
[crash-2019-04-03_12.54.49-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/3038745/crash-2019-04-03_12.54.49-server.txt)

**Comment by Shadows-of-Fire** [comment]
This should be considered a bug in thaumic additions, as they appear to be unable to handle any EntityLivingBase, which potions must do.

In the meantime, you could add the registry name (`thaumadditions:sonus`) of that potion to the boss potion blacklist in config/apotheosis/deadly.cfg

**Comment by edenhack** [comment]
Oh I see, thank you I will do that as i enjoyed the large amount of variability that could be achieved my potioncore.Sent from my Sprint Samsung Galaxy Note9.
-------- Original message --------From: Brennan Ward <notifications@github.com> Date: 4/3/19  12:20 PM  (GMT-06:00) To: Shadows-of-Fire/Apotheosis <Apotheosis@noreply.github.com> Cc: Eden Hack <nathancbright@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Shadows-of-Fire/Apotheosis] Crash, probably due to incompatibility with random potion effect chance and potioncore (#27) This should be considered a bug in thaumic additions, as they appear to be unable to handle any EntityLivingBase, which potions must do.
In the meantime, you could add the registry name (thaumadditions:sonus) of that potion to the boss potion blacklist in config/apotheosis/deadly.cfg

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Shadows-of-Fire/Apotheosis","title":"Shadows-of-Fire/Apotheosis","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Shadows-of-Fire/Apotheosis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Shadows-of-Fire in #27: This should be considered a bug in thaumic additions, as they appear to be unable to handle any EntityLivingBase, which potions must do.\r\n\r\nIn the meantime, you could add the registry name (`thaumadditions:sonus`) of that potion to the boss potion blacklist in config/apotheosis/deadly.cfg"}],"action":{"name":"View Issue","url":"https://github.com/Shadows-of-Fire/Apotheosis/issues/27#issuecomment-479581104"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Shadows-of-Fire/Apotheosis/issues/27#issuecomment-479581104",
"url": "https://github.com/Shadows-of-Fire/Apotheosis/issues/27#issuecomment-479581104",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
