### ISSUE TITLE
Question : Mob life spawned

### ISSUE THREAD

**Issue by LeapInSoft** [Shadows-of-Fire/Apotheosis#270]
Hello, I have a little question. I try to make a farm in vanilla + Apotheosis mob.
When I try the design on creatif, with zombie for exemple, look like I need to drop from an height of 38 blocks for kill a mob from the spawner vs 24 blocks from an egg.

What is the rules for numbers of life for mob from the spawner ?

(I mean health not life)

**Comment by Shadows-of-Fire** [comment]
Sounds like you had a brutal spawner, which spawns entities with potions, making them take less damage.  Should be standard resistance math.
