### ISSUE TITLE
Suggestion: enchanting table config (1.16.x)

### ISSUE THREAD

**Issue by dkmk100** [Shadows-of-Fire/Apotheosis#274]
There are configuration settings for the max levels of enchantments, which is helpful when creating modpacks. However, there is no  config options to change how the enchanting itself works. I suggest config settings to change the max level of the enchanting table, and to allow the enchanting table to obtain treasure enchantments.

**Comment by Shadows-of-Fire** [comment]
I don't want to enable treasure enchantments on the table, it kinda defeats the purpose of them being treasure enchantments.  Additionally, the max level of the table is automatically determined from the max available eterna level across all blocks with stats, as loaded by active datapacks.
