### ISSUE TITLE
[Crash] java.lang.NullPointerException: Ticking entity - Caused by Anvil Drop

### ISSUE THREAD

**Issue by Ridanisaurus** [Shadows-of-Fire/Apotheosis#276]
Our server crashed when one of the users tried to use an Anvil with Splitting and Unbreaking to split an enchants on a book.
I told the player to keep the Anvil in case some further testing is required.

Mod Version: Apotheosis-1.16.3-4.4.1
Crash Log: https://gist.github.com/Ridanisaurus/7aff4ee18e022e0af56a0aa8629dc4e1

**Comment by Shadows-of-Fire** [comment]
Looks like you had an item with a null enchantment on it, somehow.  I guess I can null check that.
