### ISSUE TITLE
Enchanting Table Issue

### ISSUE THREAD

**Issue by dwgeek** [Shadows-of-Fire/Apotheosis#279]
While playing All The Mods 6 v1.3.7, the crafting table would not show up in JEI. After crafting it from memory it was named "Air", and when placing it it had a glitched texture before becoming an invisible block that prevented me from walking or jumping on the space where I had attempted to place it.

**Comment by Shadows-of-Fire** [comment]
That would be caused by a mod conflict of something else replacing the table.
