### ISSUE TITLE
Enchanting Table Bug

### ISSUE THREAD

**Issue by Pryemium** [Shadows-of-Fire/Apotheosis#280]
When placing enchanting table, the texture appears to be black and pink checker block with floating book on top. Cannot access the enchanting table either. 

Do note: 
- Placebo version is 1.16.3 (most recent)
- Using forge

**Comment by Pryemium** [comment]
My bad - there is a mod in my pack that is affecting it

**Comment by ProfessorBustanut** [comment]
> My bad - there is a mod in my pack that is affecting it

tell us

**Comment by MelanX** [comment]
Would be nice to know which mod. I have the same issue. And removing Quark Oddities does only help a little bit. 
This is my modlist and idk which mod causes this: https://gist.github.com/MelanX/6eee6a7555cbb338400148744c14e761

**Comment by MelanX** [comment]
Oh.. i think you need to remove Quark completely. That would result in issue #283

**Comment by Shadows-of-Fire** [comment]
quark changed the matrix table to be a new block
