### ISSUE TITLE
Wondering Trader Not Visible During the Day

### ISSUE THREAD

**Issue by Coraline77447** [Shadows-of-Fire/Apotheosis#282]
Hi, Lately I've been seeing the wondering traders not being visible during the day and they're constantly drinking a bucket of milk to try to get rid of their invisibility effect but they can't cause they're permanently invisible. (Also they're driving me insane just hearing a permanently invisible wondering trader constantly trying to get rid of his invisibility effect by drinking a bucket of milk resulting to killing the wondering trader cause of him being annoying as hell and the fact that most of his trades I cant afford yet anyways.)

![Uploading 16091596326263227252555693258536.jpg…]()

**Comment by BugmanBugman** [comment]
Do you have performant

**Comment by Coraline77447** [comment]
Yes? (Sorry for the late reply and I've been checking on here to make sure that you've replied to me but looked like you haven't but I just remembered that I've always left chrome and never refreshed the page by accident...)

**Comment by BugmanBugman** [comment]
Performant is the one causing this bug

**Comment by Shadows-of-Fire** [comment]
Yeah apoth doesnt do anything to traders aside from adding new trade options, so it couldn't be the source of this
