### ISSUE TITLE
Quark conflict

### ISSUE THREAD

**Issue by ProfessorBustanut** [Shadows-of-Fire/Apotheosis#283]
causes the enchantment table to have missing texture and disappear and renames the item to air
disabling matrix enchantments in quark config does nothing to fix this

**Comment by Shadows-of-Fire** [comment]
Well then it sounds like quark has changed their code to not only always register the blocks, but also broken the hook I had in place to forcibly disable it when apoth was present.  Wonderful...

**Comment by ProfessorBustanut** [comment]
i love how quick you got to this i respect dedication to ones work
how soon do you think this is going to be fixed?

**Comment by Shadows-of-Fire** [comment]
No clue, depends how hard it is to fix.  Can't start working on it until I'm back from vacation anyhow

**Comment by ProfessorBustanut** [comment]
found a workaround with createmod make a world back up if you arnt confident with what your doing remove quark and start a new testworld (so not to remove any quark things from your currant playworld) and place an enchant table make a createmod scematic of just the table reinstall quark enter playworld go into creative(if cheats are disabled open to lan with cheats enabled) and use the schematic to print (schematicanon wont work) now you have a working enchantment table be carefull where you put it you cant pick it up or it will revert to the glitched version

**Comment by Chocokakke** [comment]
You can also head into the quark jar and remove any assets related to matrix enchanting. This fixes the issue, as well.

**Comment by WenXin20** [comment]
Quark moved matrix enchanting to a new block, so it should no longer crash.
