### ISSUE TITLE
Request, Spawner Module, accept more items

### ISSUE THREAD

**Issue by Divineaspect** [Shadows-of-Fire/Apotheosis#284]
I'd like to be able to add more items to the spawner.cfg
My use case is wanting to add more expensive higher tech items to the control with redstone_cpntrol, but want to have more then one item work for that function.

**Comment by Shadows-of-Fire** [comment]
Hm, yeah that was previously possible with the crt integration.  I can either rebuild that or make it accept a tag, which would allow you to specify your own set of items.

The only thing a tag would not allow would be nbt.

**Comment by Divineaspect** [comment]
Either would work for my usecase, I suspect a tag would have more useful implications.
