### ISSUE TITLE
[BUG] Deadly module without the spawner module causese the mob spawners in caves to have missing textures.

### ISSUE THREAD

**Issue by BastionNtB** [Shadows-of-Fire/Apotheosis#286]
Disabling the spawner module makes the spawners for the deadly module have no textures, however they still function, seemingly normally.

Here's a picture
![image](https://user-images.githubusercontent.com/15705306/103447590-1a6f8200-4c42-11eb-83ff-075be46f2429.png)

Here's the related mods
Forge 35.1.13
Apotheosis-1.16.3-4.4.1.jar
~ConfigurableCane-1.16.3-2.0.0.jar~ (Removed)
EnchantmentDescriptions-1.16.4-6.0.2.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
jei-1.16.4-7.6.0.62.jar
~branders-spawnermod-1.16.4-1.7.9.jar~ (Removed)

Can we get the deadly module to work without the spawner module enabled?

**Comment by Shadows-of-Fire** [comment]
Disabling the spawner module will do this to all spawners in the world, same with removing any block replacement.  It's a forge bug.

Also, why do you have two mods that are incompatible with apoth installed while making reports?

**Comment by BastionNtB** [comment]
Wow, just close it, without waiting for me to respond. Ok.

Well firstly, these mods you mention that are incompatible are listed in your dependencies. Little did I know that incompatible mods are also listed in the dependencies.  I see now that there's a dependency type selection and you have to select incompatible to see that those are indeed incompatible. My bad.

Secondly, these spawners are spawning WITH THE WORLD. I deleted the world entirely after making these changes. I understand that your spawners are different spawners than vanilla and removing these capabilities would also remove the aforementioned items from the game, causing a glitch like this. But that is NOT THE CASE.

Simply turning off those modules CAUSE THIS ISSUE.
