### ISSUE TITLE
Mob spawner not accepting spawn egg

### ISSUE THREAD

**Issue by Jophan** [Shadows-of-Fire/Apotheosis#288]
When i use a spawn egg on a spawner it doesn't change the spawning mob inside and nothing spawns. I get the achievment but nothing happens, i tried it in creative and same issue there whereas in vanilla it works fine. Maybe I'm doing something wrong I'm not sure, please let me know thank you!

**Comment by Shadows-of-Fire** [comment]
Are you using a modpack?

**Comment by Jophan** [comment]
Yes I am playing on valhelsia III

**Comment by Shadows-of-Fire** [comment]
valhelsia blacklists a significant amount of spawn eggs from spawners.

**Comment by Jophan** [comment]
Ok. Thanks for the quick reply really apreatiate it!
