### ISSUE TITLE
4.4.1 Chipped/Damaged Anvils Lose Enchants

### ISSUE THREAD

**Issue by desagas** [Shadows-of-Fire/Apotheosis#289]
When picking up an enchanted anvil that is damaged or slightly damaged/chipped, it loses all of its enchants. This is true when using both silktouch and fortune or none.

1.16.3.4.4.1 ATM6 1.3.7

I did look briefly, and could not find another issue about this.

**Comment by Danekjovax** [comment]
I am not seeing this in Explorico 1.5b, so can you elaborate what modpack you're using along with this mod?  Thanks.

**Comment by desagas** [comment]
ATM6, 1.3.7, Apoth 4.4.1 as written above. It is not when enchanting chipped or damaged anvils, it is when brand new anvils are enchanted, and placed in world, when using them to add enchants / do what normal anvils do, when they turn from ehchanted full in world anvils to chipped versions, when those ones were broken, they don't keep their glint / enchants. This Also happened in FTB interactions 1.9.1, I believe.

**Comment by Danekjovax** [comment]
Interesting.  I'm playing with Explorico, as I have one vanilla Anvil that was enchanted with Splitting V and I've been happily using it for a few weeks when I need to split enchantments from books with multiple enchants.  I think it's listed as a chipped one now, and last time I think it was still with the enchantment, so when I get on tonight I'll verify if it's still ok.  I'll send screenshots.  Thanks.

**Comment by Shadows-of-Fire** [comment]
fixed in dev
