### ISSUE TITLE
Enchant max not working

### ISSUE THREAD

**Issue by ReportBot9009** [Shadows-of-Fire/Apotheosis#29]
I am running the new Project Ozone 3.0.39 update. I changed all of the vanilla enchants in the config file to a max level of 10. So Sharpness 10, looting 10 etc. and it is not showing up in game. With the new bookshelves that add higher enchanting power, along with enchant specific books, I only get Apotheosis enchants.

The garden module for growing cactus and sugarcane follows the config for what I set it at. I've looked around in the Project Ozone 3 config files and I can't find any blacklisting for higher level enchants. 

Thanks

**Comment by Shadows-of-Fire** [comment]
Using vanilla math, the levels required for things such as looting X and sharpness X aren't remarkably high.  You'd have to change enchantment power formulas or increase the cap further (test it at 127 to see what your table would give you)

**Comment by ReportBot9009** [comment]
I forgot to add, the old Project Ozone 3.0.38 that didn't include your mod, I added it to that version and everything worked perfectly. Enchanting levels up to 10 etc.

**Comment by ReportBot9009** [comment]
This is not working. The first picture is with Hell Infused bookshelf and a Tome of the miner. The second picture was enchanted with a normal bookshelf. Normal bookshelves don't enchant past default and the hell infused only apply enchants from your mod.

I increased the enchanting cap to 400 and the default cap to 60 and nothing changed.

![Apotheosis Not Working 2](https://user-images.githubusercontent.com/4673275/55666306-427e4700-580a-11e9-985f-116968d22f91.jpg)

![Apotheosis Not Working](https://user-images.githubusercontent.com/4673275/55666291-1367d580-580a-11e9-95b9-eb8d3d48956a.jpg)

**Comment by Shadows-of-Fire** [comment]
Uh, what config file are you changing?
