### ISSUE TITLE
[1.16.4] Eidolon Enchantment Table breaks Apotheosis advancements

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#291]
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/756

Using Eidolon progression to enchant items gives every Apotheosis enchanting related advancement at once, as if using a table that is at 100% Arcana, 100% Quanta, and 100% Eterna, while simultaneously being at 0% Quanta.

### Versions
- Apotheosis-1.16.3-4.4.1
- eidolon-0.2.7
- Forge-1.16.4-35.1.29

**Comment by Shadows-of-Fire** [comment]
Is that an open source mod?  I can't say I've ever heard of it

**Comment by NielsPilgaard** [comment]
It is, and very new: https://github.com/elucent/eidolon

**Comment by Shadows-of-Fire** [comment]
@elucent Could you point me in the direction of where you're enchanting things?  I'd look for it myself but I think it's quicker to ask

**Comment by Shadows-of-Fire** [comment]
I think this is the same issue described as in #250 , which if it is, should be fixed next update

**Comment by NielsPilgaard** [comment]
Thank you :)
