### ISSUE TITLE
[Suggestion] Bookshelf Config

### ISSUE THREAD

**Issue by Flabort** [Shadows-of-Fire/Apotheosis#294]
Right now it's cool and kind of puzzly to work out optimal bookshelf arrangements, but what if pack makers could add more kinds of bookshelfs with different stats/limits, such as a shelf that reduces all three stats, or increases Eterna but reduces Arcana.

And make it so if another mod adds something to boost bookshelf levels, then a pack maker can adjust those stats too, such a makimg it so the botania Natura pylon has a max Eterna level of 30 instead of 15.

Default configuration would leave the bookshelves as they are, of course.

**Comment by Shadows-of-Fire** [comment]
They can, as all bookshelf stats are datapack loaded to begin with.
