### ISSUE TITLE
Initialization Exception [1.16.4] [4.4.1]

### ISSUE THREAD

**Issue by Coraline77447** [Shadows-of-Fire/Apotheosis#297]
Hi, It's me again but this time Apotheosis failed to load during common_setup. Here's the crash report and log. 

Crash report: 
[crash-2021-01-11_04.37.55-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5795512/crash-2021-01-11_04.37.55-fml.txt)

Log:
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/5795587/latest.log)

Also can you please take a look at my first report even tho it's totally different than this one? That'll be much appreciated if you do but before that could you fix this issue? Or else I'll have to stop playin with Apotheosis till this issue has been resolved....

**Comment by Shadows-of-Fire** [comment]
This is an issue in MoreVanillaWeapons
