### ISSUE TITLE
Crescendo of Bolts compatibility with Spartan Weaponry's crossbow

### ISSUE THREAD

**Issue by crafting-Aaron** [Shadows-of-Fire/Apotheosis#299]
Cresendo of Bolts works fine on the vanilla Crossbow. It is also able to be added to the Heavy Crossbow from the mod but does not give additional bolts. The heavy crossbow uses modded bolts rather than vanilla arrows. Maybe this could be the problem.

**Comment by Shadows-of-Fire** [comment]
Crescendo of bolts requires quite a bit of hackery to work at all, I'm not surprised it doesn't work on modded crossbows.  Might not be possible to make it work.

**Comment by crafting-Aaron** [comment]
Understandable. The bolts already pack a punch so it would be too overpowered now that I think about it.

**Comment by Shadows-of-Fire** [comment]
SW is closed source / ARR so this is a wontfix

**Comment by AquexTheSeal** [comment]
Spartan Weaponry became open-source and changed their license to  Apache License
