### ISSUE TITLE
Possible compat issues with multiple mods

### ISSUE THREAD

**Issue by Sunconure11** [Shadows-of-Fire/Apotheosis#3]
https://paste.dimdev.org/husikagemo.mccrash <- NightKosh's Gravestones

https://paste.dimdev.org/zepurohecu.mccrash <- The Betweenlands

I'm wondering if there is a connection to Just Enough IDs. However, I will be too inactive over the next few days to test.

**Comment by Shadows-of-Fire** [comment]
Why in the world is the gravestone mod invoking addRandomEnchantment for getSubBlocks...
I can add in something to deal with that but it really shouldn't be doing that.

As for the betweenlands thing, I don't think I'm causing that.

**Comment by Shadows-of-Fire** [comment]
@NightKosh why do you do this here: https://github.com/NightKosh/Gravestone-mod-Graves/blob/master/src/main/java/nightkosh/gravestone/block/BlockGraveStone.java#L510
Surely you could just use a set enchantment like sharpness.

**Comment by Shadows-of-Fire** [comment]
Well, i wish he'd stop doing that, but since there's no reply i'll just add a check for it.  
Doesn't make it less stupid, and i'm going to log an error about it.

**Comment by Shadows-of-Fire** [comment]
The betweenlands thing appears to just be you missing their coremod jar, so i'm gonna close this.
