### ISSUE TITLE
Apotheosis tags causing JEI to not function when connected on a server

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#300]
This is a pretty long and drawn out issue I've been working on most of the day, but the gist is,

with apotheosis mod + jei on client and apotheosis on server, when connecting to a server, JEI will not show any GUI at all.

It is due to some tag problem that I don't understand, but there is extensive details all compiled into this issue on JEI's github here: 
https://github.com/mezz/JustEnoughItems/issues/2213

**Comment by Shorepion** [comment]
add FastWorkbench to your modpack. This fixed it for me.

**Comment by ghost** [comment]
Hi, I already have the mod in my modpack, unfortunately.
FastWorkbench-1.16.4-4.5.0

**Comment by Shadows-of-Fire** [comment]
Provide a client log from a run where the issue occurs.  Don't provide one that is 600k lines long, just open the game, have the issue occur, and retrieve that log.

**Comment by ghost** [comment]
That is literally all that occurred in that log afaik lol

**Comment by ghost** [comment]
This issue has more condensed information related specifically to apotheosis https://github.com/vectorwing/FarmersDelight/issues/106

**Comment by Shadows-of-Fire** [comment]
So then yeah it's just that again, that's fixed in dev (has been for a while) but there's nothing ready to release yet

**Comment by ghost** [comment]
I see, cool. Thanks for the update
