### ISSUE TITLE
[Feature Request] 1.16  Make Wandering Trader trades more configurable

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#301]
Would you consider making the Wandering Villager trades configurable via datapack or other means?

I love the fancy loot he can have, but would like to tone down the enchants on them.

**Comment by Shadows-of-Fire** [comment]
maybe™

**Comment by MuteTiefling** [comment]
I'll take a maybe :D

**Comment by Shadows-of-Fire** [comment]
Trades are json <https://github.com/Shadows-of-Fire/Apotheosis/tree/1.16/src/main/resources/data/apotheosis/wanderer_trades>
(not yet released)
