### ISSUE TITLE
Failed to create mob + spawners do not spawn mobs

### ISSUE THREAD

**Issue by kevinnnm12345** [Shadows-of-Fire/Apotheosis#305]
![image](https://user-images.githubusercontent.com/78066555/105945820-e017bb80-601a-11eb-930f-220e645a8eae.png)

**Comment by Shadows-of-Fire** [comment]
The WorldEntitySpawner is responsible for natural spawning of entities, and has nothing to do with mob spawners.  You probably have a different, but much larger, issue.
