### ISSUE TITLE
Rebounding causes Ender Dragon to vanish

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Shadows-of-Fire/Apotheosis#306]
Using Rebounding (all levels) will cause the Ender Dragon to vanish. The only way to kill it then is with the kill command. It would be nice if the Ender Dragon was immune to Rebounding. I will disable this in my mod packs and serve until it is fixed.

Minecraft: 1.16.5
Forge: 36.0.1
Apotheosis: 1.16.3-4.4.1

**Comment by Shadows-of-Fire** [comment]
Blocking it for all bosses, probably should've done that from the start.
