### ISSUE TITLE
Your inexperience has degraded "Enchantment"

### ISSUE THREAD

**Issue by JosShepherd** [Shadows-of-Fire/Apotheosis#307]
Whenever i add an enchanted book to a piece of armour or a tool, It says "Your inexperience has degraded Leech to level 4" as an example. it only degrades the enchantments that are above what is usually the most you can have in vanilla. I'm only able to add the enchanted books to my tools in creative without it doing this.

![Capture](https://user-images.githubusercontent.com/78119930/106069512-8dadcc00-60fa-11eb-9f7b-bc28714c7961.PNG)

**Comment by Shadows-of-Fire** [comment]
That's not an apoth feature

**Comment by Acru** [comment]
For anyone else that turns up here looking for a solution to this problem, the degradation is caused by the Project MMO mod, Smithing module.  There is an option to disable in pmmo-common.toml
