### ISSUE TITLE
Fletching table arrow recipe overridden

### ISSUE THREAD

**Issue by an0nymz** [Shadows-of-Fire/Apotheosis#310]
Hosting a custom modded server. JEI tells me a recipe from Apotheosis should cause the fletching table to output 6 arrows (for the same ingredient that the basic crafting table outputs 4). However when I try to use it, I see the output show 6 for a split second before changing to 4. It doesn't seem to be just a visual bug as when I take the output it puts 4 arrows in my inventory, and disconnecting and reconnecting still has me at 4 arrows. My only guess is that one of my other mods has a conflicting recipe in the fletching table, but I do have polymorph which I would think should solve that problem. Plus the table itself shows up as an apotheosis item, so again it'd be odd for another mod to be overriding a recipe in it. A few of the bigger mods I also have installed are quark, charm, create, ars nouveau, farmer's delight, mekanism, alex's mobs, and gems and jewels, in case any of these are known to conflict already.

**Comment by an0nymz** [comment]
Another possibly important mod that is installed I should mention is Polymorph, which is "supposed" to be solving any conflicts from having multiple possible outputs for a recipe so I would think that would potentially solve the problem rather than create one but perhaps there's a bug between that mod and this one?

**Comment by Shadows-of-Fire** [comment]
I haven't had any issues with those recipes in a pure apoth environment, and the table is its own crafting type, so I don't see why anything would be interfering with it, but it sounds like it is

**Comment by Shadows-of-Fire** [comment]
Gonna call this as a fault on another mod's end, as the fletching table is separate from normal crafting.  Anything cross-contaminating is doing something wrong.
