### ISSUE TITLE
Adding and Subtracting from Potential Spawns in Spawners

### ISSUE THREAD

**Issue by Divineaspect** [Shadows-of-Fire/Apotheosis#312]
Vanilla spawners can have more then one mob in them as potential spawns.
I would love a change (either in addition to or replacing) allowing for adding and removing potential spawns from spawners, one weight at a time.
This would increase the danger of repurposed spawners to get closer to matching the potential rewards from doing it.
On a map or packmaker level this would allow for some cunning spawner applications.

**Comment by Shadows-of-Fire** [comment]
You should just be able to edit the nbt of either the item or the block in world in order to achieve that.  I'm not sure if there will ever be a clean interface to edit spawner potentials from a user endpoint

**Comment by Divineaspect** [comment]
Using the "subtract" function with the offhand key item to remove a potential felt fairly intuitive.
Using a spawn egg, adding that option or increasing the weight by 1 if it already exists.

**Comment by Shadows-of-Fire** [comment]
After some consideration I think that enabling users to do things such as edit potential spawns is a bit more than what I'd like for the module to have in its toolkit
