### ISSUE TITLE
Add Lootr Compatibility

### ISSUE THREAD

**Issue by ovfudj** [Shadows-of-Fire/Apotheosis#313]
Currently Apotheosis loads chests in a way lootr is unable to generate its chests. I am asking for functionality to give lootr the
appropriate hook in the spawning method.
![image](https://user-images.githubusercontent.com/47165507/106775939-35e6f780-6609-11eb-9ee0-39c8dce4e7bf.png)

Implementation is described in [this](https://gitlab.com/modding-legacy/dungeons-plus/-/merge_requests/3) post.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Placebo/pull/19
