### ISSUE TITLE
[Feature Request] Add chest loot table balance option to deadly module

### ISSUE THREAD

**Issue by plebania** [Shadows-of-Fire/Apotheosis#316]
Hi,
I like your mod very much, but I have small problem with it. The problem is whenever I go mine at the beginning of game and walk out form the caves with diamond or even netherite stuff, in my opinion, breaks the progression of the game. I really like the idea of special properties of tools found in the chests generated under spawners. Would you kindly consider adding a config option to the deadly module? It would determine max tier of the material from, which tools found would be made of? It would interact nicely with mods that allows upgrading tools to higher material tiers, or maybe you could even consider adding such feature.

**Comment by Shadows-of-Fire** [comment]
The items that are valid for affix loot pools are defined in jsons and editable by datapack.  That provides all the configuration that would be needed

**Comment by plebania** [comment]
thanks a lot!!!
