### ISSUE TITLE
Game crashes when trying to load an Apotheosis mob

### ISSUE THREAD

**Issue by SuiguraTaiki** [Shadows-of-Fire/Apotheosis#317]
Hi, I've been running a slightly modified Enigmatica 6 (added a couple mods, not updated anything), and for whatever reason when i travel near a chunk, the game crashes consistently when i approach the same coordinates. Taking a look at the crash reports, the issue is exactly the same, "Caused by: java.lang.IllegalArgumentException: Unsupported mob type for TemptGoal". Not a modder to figure out if its an incompatibility.

Link to the pastebin with the crash report: https://pastebin.com/y7aKeZTF

**Comment by Shadows-of-Fire** [comment]
Nothing in this code comes from apoth, the stacktrace is from simplefarming
