### ISSUE TITLE
enchanting table impossible to use with the mod installed

### ISSUE THREAD

**Issue by doopfish** [Shadows-of-Fire/Apotheosis#318]
when I try to enchant any item in an enchant table, nothing happens, no enchantments show up, there's no compatibility problems because I tried with only apotheosis installed
i tried apotheosis 1.12.4 and 1.12.5, neither of them work
the minecraft version is 1.12.2

**Comment by Shadows-of-Fire** [comment]
mc 1.12 is not supported
