### ISSUE TITLE
Incompatibility with the 'Inspirations' mod's anvil smashing in-world interaction

### ISSUE THREAD

**Issue by MorzanTLD** [Shadows-of-Fire/Apotheosis#32]
When the mod Inspirations is installed alongside Apotheosis, dropping an anvil will not perform any of the in-world interactions added by Inspirations.

**Comment by Shadows-of-Fire** [comment]
@KnightMiner How do you implement your anvil stuff?  Anything I can do to re-enable it under my registry override?

**Comment by KnightMiner** [comment]
All my override does is patch into [onEndFalling](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/recipes/block/BlockSmashingAnvil.java#L22-L27), as there was no easy event I could listen to to modify that behavior. You could possibly call the smashBlock method yourself, but that does feel a bit messy. as its an internal method
