### ISSUE TITLE
Odd message in chat:  death.attack.apoth.execute.player

### ISSUE THREAD

**Issue by xenoflot** [Shadows-of-Fire/Apotheosis#321]
I'm playing on a server and saw this message come up twice in a row.  There are several people online so I have no idea what others are doing although several minutes before, a couple of players got [He Wasn't So Strong] so they may have still been working with bosses (I was AFK in a browser). The players DID get "xyz was slain by Herbert" and "...by Sharon" before they got their achievements. I'm not an admin so I can't check recent logs sorry but I thought I'd mention it. 

We're running Apotheosis-1.16.3-4.4.1

**Comment by Shadows-of-Fire** [comment]
That's rather interesting.  For that to happen something would have to have caused execution damage sourced to a player, which should be impossible.  I can write in the translations for it, but just weird nonetheless.
