### ISSUE TITLE
(1.16.4) Anvil and Enchanting Table missing textures

### ISSUE THREAD

**Issue by allbonus** [Shadows-of-Fire/Apotheosis#324]
After installing Apotheosis and Placebo the anvils and enchantment tables have no textures for some reason.
I don't know what mod could be causing this problem.

These are my mods
-additional_lights-1.16.4-2.1.3
-Apotheosis-1.16.4-4.4.1
-Bookshelf-1.16.4-9.3.23
-comforts-forge-1.16.4-4.0.1.0
-DarkUtilities-1.16.4-7.0.6
-DynamicSurroundings-1.16.4-4.0.3.11
-emojiful-1.16.4-2.1.4
-extended lights 3.3 (for some reason i changed the name by mistake)
-FORGEtimber-1.16.4-1.8.1
-jei-1.16.4-7.6.1.71
-mcw-doors-1.0.2-mc1.16.5
-mcw-furniture-2.0.1-mc1.16.5
-mcw-windows-1.0.3-mc1.16.5 (these macaw's mods works perfect in mc 1.16.4 no crashes at all)
-Neat1.7-27
-Placebo-1.16.4-4.4.1
-Runelic-1.16.4-6.0.3
-TravelersBackpack-1.16.4-5.3.8
-Waystones_1.16.3-7.3.1
-Xaeros_Minimap_20.27.2.1_Forge_1.16.4
-XaerosWorldMap_1.11.7_Forge_1.16.4

**Comment by Shadows-of-Fire** [comment]
Apoth replaces anvils and enchantment tables, and sometimes forge doesn't handle this transition seamlessly within a save.  Breaking and replacing the blocks with missing textures should restore them, unless you have something that is actually breaking it.  I don't see anything that I know of that would do that in that list, though.
