### ISSUE TITLE
[1.16.5] Filling Jerrycan from Immersive Engineering with water causes client crash

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#325]
### Description of the issue:
Holding a Jerrycan and right-clicking while looking at water causes a client crash - The server the client is connected to does not crash. Apotheosis is mentioned in the log so I thought I'd put the issue here in addition to IE's tracker.
Issue on IE's tracker: https://github.com/BluSunrize/ImmersiveEngineering/issues/4672

### Crashlog:
https://gist.github.com/NillerMedDild/3f26127eb12afc0a76133417dc3086a5

### Versions & Modlist
- ImmersiveEngineering-1.16.5-4.2.1-131
- Forge-1.16.5-36.0.40
- Apotheosis-1.16.3-4.4.1 (Also mentioned in crash report)

Modpack is Enigmatica 6 v0.4.0: https://www.curseforge.com/minecraft/modpacks/enigmatica6/files/3214669
Modlist: https://github.com/NillerMedDild/Enigmatica6/blob/master/MODLIST.md

**Comment by Shadows-of-Fire** [comment]
This code has been deleted and made into a safer event implementation in Placebo, so my involvement in this stacktrace is resolved™
