### ISSUE TITLE
0 Eterna, 10 Quanta, 0 Arcana everytime

### ISSUE THREAD

**Issue by GordonHollow** [Shadows-of-Fire/Apotheosis#326]
Play on last ATM6-1.5.2, seems to be enchantment table always get that value, with\without any type of bookshelves (i try end bookshelves to maximize the arcana tho)
Try breaking\replacing ench.table and bookshelves - nothing changes

**Comment by BlueAgent** [comment]
~~The table has a base amount of Quanta IIRC. Melonshelf can reduce it though.~~
Edit: Not relevant.

**Comment by GordonHollow** [comment]
Well, i don't need reduce amount a Quanta, i try to upgrade amount of Arcana for better enchantment - and it's not upgrade with all End Bookshelves i put.

**Comment by BlueAgent** [comment]
Sorry, my bad. I couldn't reproduce it with just Apotheosis or with ATM6-1.5.2. Are you sure you're using the shelves from Apotheosis?

**Failed to reproduce with the following mods only** ([Logs](https://gist.github.com/BlueAgent/e0e6c2fc69f90bd5950e697b148765ec#file-debug-log-L888) see L888):
Forge 1.16.5-36.0.43
Apotheosis 1.16.3-4.4.1.jar
JEI 1.16.4-7.6.1.71
Placebo 1.16.4-4.4.1
![Apothosis, dependencies and JEI only Enchantment Table](https://user-images.githubusercontent.com/630920/109381972-712eca80-7918-11eb-8134-472ba3ca1a8a.png)

**Also failed to reproduce on ATM6-1.5.2** ([Logs](https://gist.github.com/BlueAgent/97b7b849a39f8fc1c8b10935acb81ebf) see L40077):
![ATM6 Apotheosis Enchantment Table](https://user-images.githubusercontent.com/630920/109382222-2a41d480-791a-11eb-9a8c-d3261439f86f.png)

**Comment by GordonHollow** [comment]
Hmm, i can post full log if it needed, cause there is no error or crash, that i can post

**Comment by BlueAgent** [comment]
Yeah you can do that (create super flat world in creative, switch to survival, spawn in items and set it up like I did.) Also can you screenshot your setup too?

**Comment by GordonHollow** [comment]
That's the setup, just temporarly mess of EndBookshelves. And it has 10 basic Quanta and 0 another stats. Now i have 22 lvl, but the same result i have with 106 lvl

![Безымянный](https://user-images.githubusercontent.com/23491996/109383424-3ae94f00-7908-11eb-9740-e1edf1e0aba9.png)

here is latest.log , they all the same, it always has that issue with no crash or erors
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/6054106/latest.log)

**Comment by BlueAgent** [comment]
The table only counts shelves that are on the edge of a 5x5 square centred on the table and the block above each of those.
I guess make sure there's only air blocks around the table as well? Nothing like torches etc in the way.

If you are doing all that then I have no idea what's going on rn.
As you saw I literally downloaded a fresh copy of ATM6-1.15.2 and tested it and it worked just fine.

Can you please test by creating a **new super flat world**, and setting it up like in this picture and see if it's still broken?:
![Example Enchanting Table Setup](https://user-images.githubusercontent.com/630920/109384735-e3f47180-7929-11eb-8b61-d8dc7cca368c.png)

**Comment by GordonHollow** [comment]
Oh, i think it's work vanilla-like with boockshelves. With that exact structure all works fine, thanks!

**Comment by Veritera** [comment]
Got the same error rn. Turned out i had to move 1 chunk away with the setup. Something was broken in there :S
