### ISSUE TITLE
Deadly Feature will replace any block including End Portal Frames which break Strongholds

### ISSUE THREAD

**Issue by TelepathicGrunt** [Shadows-of-Fire/Apotheosis#327]
As the title and picture below shows, the deadly feature from Apotheosis will break structures and features that places hard-to-find or non-replaceable blocks like End Portal Frames. Causing people to have to travel thousands of blocks to find another stronghold and such. Perhaps have the feature not replace blocks in the wither_immune tag? Or blocks that cannot be broken by players in survival? Just some suggestions.
![image](https://user-images.githubusercontent.com/40846040/109366242-e939b980-7860-11eb-9194-3269175a8179.png)

**Comment by Shadows-of-Fire** [comment]
The deadly module features are currently being redone, so I can check that tag (or try to generate before strongholds, though I'm not sure if that's possible).

**Comment by TelepathicGrunt** [comment]
I moved my strongholds to the correct stage (was underground structures and now is in strongholds stage) so this should not be a problem anymore with my mod's strongholds (vanilla's was safe already). Though it's still a good idea in case other mods have unbreakable rare blocks or something.

**Comment by Shadows-of-Fire** [comment]
Sandstone stuff is gone now, and my features follow everything that vanilla features do
