### ISSUE TITLE
What should I keep in mind if I have to use EvalEx for my own mod?

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#328]
I am porting Armor Curve's EvalEx-driven armor reduction formulae to forge. Forgive me if this is the wrong place to ask; how would I go around this, such that the compiled mod wouldn't conflict with Apotheosis?

**Comment by Shadows-of-Fire** [comment]
Provided its the same version of evalex nothing afaik.  If you wanted to be super safe you can change the namespace
