### ISSUE TITLE
Bugs with the Bosses

### ISSUE THREAD

**Issue by wallxnr** [Shadows-of-Fire/Apotheosis#329]
The bosses in my game were summoning invisibility and it's basically impossible to beat someone who kills you with 1hit and is still invisible.
After dying several times, he appeared once and the movement speed is absurd, it is faster than the player himself, even if he is running.
In the link below is a screenshot showing my instant death, a short video of when he appeared in the game and the absurd speed, and lastly, the number of times I died in a short time due to this bug. Please correct this, the mod is great, but these bosses are totally unbalanced.

https://drive.google.com/drive/folders/1CyhU-fnz8s1SaaJt5CZUFdjT7qODFiT6?usp=sharing

**Comment by Shadows-of-Fire** [comment]
Bosses are currently being reworked to have a fixed set of possible potion effects and attributes, so this will be resolved with that.
