### ISSUE TITLE
Enchantment True Infinity & Temptation Can be applied to shields when Betweenlands is installed

### ISSUE THREAD

**Issue by MorzanTLD** [Shadows-of-Fire/Apotheosis#33]
When the mod Betweenlands is installed alongside Apotheosis the enchantments True Infinity and Temptation can be applied to all kinds of shields including ones from separate mods.

**Comment by Shadows-of-Fire** [comment]
Well thats the most oddly specific interaction I've ever seen...  Does bl enable shield enchanting or do anything else enchanting wise?

**Comment by MorzanTLD** [comment]
So upon disabling all mods except the betweenlands and apotheosis this no longer occurs. Though in the previous configuration disabling betweenlands fixes this issue. Further testing is required.

**Comment by MorzanTLD** [comment]
Ok upon further experimentation and you know actually attempting to apply the enchantments in survival, this bug is actually JEI having a fit and displaying enchantments that are not, in fact, able to be applied to the shield.
Furthermore, this bug is not even caused by Betweenlands it just manifested in my test world at the same time that I added it and is actually caused by enchanting tweaks (with the enchanting table modifications disabled) or VanillaTweaks.
![Jei Freaking Out](https://user-images.githubusercontent.com/39711384/56058410-4144a100-5d59-11e9-83c0-8a85fe10ff51.png)
![Proof](https://user-images.githubusercontent.com/39711384/56058411-4144a100-5d59-11e9-88a9-daa01a80d680.png)

**Comment by Shadows-of-Fire** [comment]
I think this has to be on their end, because this can only happen if someone adjusts the rules for what enchantments can go on what or otherwise directly messes with enchantment objects.
