### ISSUE TITLE
enchantment_module.cfg not working 1.16.5

### ISSUE THREAD

**Issue by AdnanuReeves** [Shadows-of-Fire/Apotheosis#330]
I'm trying to make it so I can combine books like experience boost IV together to make experience boost V but none of the changes I make in enchantment_module.cfg works.. the enchantments I try to blacklist doesn't get blacklisted either.

# Configuration file

general {
    # If cobwebs can be used in anvils to remove enchantments. [default: true]
    B:"Enable Cobwebs"=true

    # A list of enchantments that are banned from the enchanting table and other natural sources. [default: ]
    S:"Enchantment Blacklist" <
    minecraft:thorns
    minecraft:infinity
    minecraft:fire_aspect
    minecraft:multishot
    minecraft:flame
    vanillatweaks:siphon
    vanillatweaks:blazing
    vanillatweaks:hops
    vanillatweaks:veteran
    vanillatweaks:vigor
    vanillatweaks:homing
    astralsorcery:scorching_heat
    cyclic:life_leech
    charm:acquisition
    charm:aerial_affinity
     >

    # If any two enchanted items can be combined in an Anvil. [default: false]
    B:"Item Merging"=true

    # The maximum enchantment power a table can receive from normal sources. [range: 0.0 ~ 3.4028235E38, default: 20.0]
    S:"Max Normal Power"=50.0

    # The maximum enchantment power a table can receive. [range: 0.0 ~ 3.4028235E38, default: 75.0]
    S:"Max Power"=150.0
}

**Comment by Shadows-of-Fire** [comment]
MC versions <= 1.16 are not supported
