### ISSUE TITLE
Config for disabling certain enchantments

### ISSUE THREAD

**Issue by Schummel-8** [Shadows-of-Fire/Apotheosis#332]
I think the enchantment module is a really cool way to expand the vanilla system but with the amount of enchantments it's really difficult to get the ones you want. Also with other mods, there are way too many enchantments in the whole game so it would be nice if certain enchantments of this mod could be disabled.

**Comment by Shadows-of-Fire** [comment]
You can block enchantments from the table by setting their max enchanting power function to 0 in enchantments.cfg
