### ISSUE TITLE
No longer able to enchant weapons with multiple damage enchants

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#334]
I know this used to work and nothing has changed in the mod for a while, so I assume this is actually caused by something in Forge itself.

Test:
Launch instance with only the following mods

1. Apotheosis-1.16.3-4.4.1.jar
2. Placebo-1.16.4-4.4.1.jar
3. jei-1.16.4-7.6.1.71.jar
4. forge-36.0.46

In Creative, place an anvil. Grab a diamond sword and apply Sharpness V and Smite V. Now try adding any other damage enchant. It won't allow you to.

**Comment by MuteTiefling** [comment]
https://github.com/Vazkii/Quark/issues/3049

**Comment by Shadows-of-Fire** [comment]
No that was alaays how it worked.  Sharpness + 1 specializationl

**Comment by MuteTiefling** [comment]
Huh, must have been something else removing the limit then. I swear I've made swords with basically everything. Oh well, thanks for setting me straight
