### ISSUE TITLE
Configs Are Not Re-populating

### ISSUE THREAD

**Issue by Yourname942** [Shadows-of-Fire/Apotheosis#335]
Minecraft 1.16.5
Forge 36.0.48
Apotheosis 1.16.3-4.4.1

Issue:
When I update my mods I delete the config folders so that they automatically get re-generated when I launch the server. I do this because when there are 150+ mods I have no idea which ones' config folders may have changed, so I just start clean by letting the server automatically repopulate the config folders/files for me.

Steps to reproduce:
Install Apotheosis 
launch the multiplayer server
close the server
delete the Apotheosis config folder
launch the server

Expected Behavior:
Deleting the config folder and having the server launch should repopulate the configs to their up to date but default settings.

Actual Behavior:
Deleting the config folder and launching the server only populated some config folders/files, and others are empty. The strange part is the files were generated, but they generated empty (ie. 0kb)
this causes the server to crash.

Image: 
https://imgur.com/a/1PAlyr2

**Comment by Shadows-of-Fire** [comment]
and the crash report is where...?
I suspect you have something else crashing when the files are attempting to generate, so they fail.
