### ISSUE TITLE
Spawner config enhancement!

### ISSUE THREAD

**Issue by ShootToKillSTK** [Shadows-of-Fire/Apotheosis#337]
What about a way to change/customize spawners from deadly module.

Like perhaps adding a folder and config file for the 2 default/normal spawners, brutal and swarm. Then people can somehow copy and paste and edit the same file, but give it a different name and each have a set spawn weight for whenever a spawner is allowed to spawn, it picks the one based on the weight of the spawner files.

Ex: Swarm has weight of 10, Brutal of 10, (Personalized file) of 1, (Personalized file 2) of 3. Meaning Brutal and Swarm will spawn about the same amount, but more then the 2 added ones.

A way to set the spawners to spawn per dimension would be really nice too. Like per spawner config setting having a whitelist of allowed dimensions! So you could then make dimension specific spawners, to help keep the danger high even end game dimensions by having harder mobs

Thoughts?

**Comment by Shadows-of-Fire** [comment]
This is now (sort of) a thing.  Per-dimension stuff is not yet possible because that will require even more changes to the subsystems to allow for it, but there are datapack-loaded spawner entries now!
