### ISSUE TITLE
[1.16.4] apotheosis table doesn't get the stats from bookshelfs after adding quark.

### ISSUE THREAD

**Issue by t0naa** [Shadows-of-Fire/Apotheosis#338]
Hello. this happened after I added quark oddities. I've disabled both Matrix Enchanting and the variations of bookshelfs from quark, but they just don't work anymore. I've tried to reinstall both mods and to break and rebuild the enchantment setup.
![Screenshot_10](https://user-images.githubusercontent.com/81068468/111896584-a5c30d00-8a12-11eb-80a9-515a15280717.png)
![Screenshot_11](https://user-images.githubusercontent.com/81068468/111896586-a78cd080-8a12-11eb-9d1f-5af13b561202.png)

>

**Comment by Shadows-of-Fire** [comment]
Stats are not read until an item is placed into the enchanting slot of the table, have you tested with that?
