### ISSUE TITLE
[Compat] Affixed Vampirism's weapons (and probably others) cannot change their attributes

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#339]
Vampirism weapons improve in attack speed and damage by attacking mobs, but this does not happen with affixed ones. I suspect this will happen with other items with dynamic attributes as well.

**Comment by Shadows-of-Fire** [comment]
This was a side effect of the way Item Attribute Modifiers used to work before the addition of the ItemModifierEvent.  The upcoming update has moved affixes to use that event instead of NBT modifiers.

**Comment by Jackiecrazy** [comment]
Just gonna piggyback off this and ask. I made a datapack that allowed bosses to have other sets of gear, but they don't appear to be showing up when I'm just spamming the boss spawner item. Does the current version read data packs?

**Comment by Shadows-of-Fire** [comment]
Current version does, but the format has changed a little bit.  Check the files in the published jar, rather than github, for examples.

**Comment by Jackiecrazy** [comment]
Looking at the published jar, I do not see any boss sets that include bows, yet I observe bow bosses spawning in the world. Why is that? If this is due to my own sets loading, why am I not seeing the rest?

**Comment by Jackiecrazy** [comment]
Yikes. I set the weight too low; never mind then.
