### ISSUE TITLE
OpenJDK crash

### ISSUE THREAD

**Issue by ProspectPyxis** [Shadows-of-Fire/Apotheosis#34]
https://gist.github.com/ProspectPyxis/793bd99f45d7243059c9e6e1ba387dd0

Seems to be another JVM implementation spec related crash. This only happens when using OpenJDK to launch.

**Comment by Shadows-of-Fire** [comment]
This was supposibly resolved in a forge update, unfortunately there's nothing I can really do about it from my end.

You do apppear to be running an older forge, so update that if possible.

**Comment by ProspectPyxis** [comment]
This issue was on ftb interactions, so I suppose I'll have to poke them for a forge update, haha.

**Comment by Saereth** [comment]
what version do you recommend @Shadows-of-Fire we're already running slightly ahead of forge recommended build, beta forge builds worry me on production packs :-/
