### ISSUE TITLE
My own server crash

### ISSUE THREAD

**Issue by Nyxkoh** [Shadows-of-Fire/Apotheosis#340]
When i start my server, he crash and i dont know why. (im playing the All the Mods 6) 
I'll send here my crash log, i tried few restart but doesn't work
[crash-2021-03-26_19.57.01-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6213947/crash-2021-03-26_19.57.01-fml.txt)

**Comment by Shadows-of-Fire** [comment]
This is caused by PSI, but afaik they fixed this issue.  You may just need to update psi/the modpack.
