### ISSUE TITLE
Server crashing on start up when using Apotheosis

### ISSUE THREAD

**Issue by yoshijun95** [Shadows-of-Fire/Apotheosis#341]
I am renting a server off apex hosting. I tried to use the mod but the server wont even start up. It crashes before the server can even go up. Any help with this?

**Comment by Gunner76th** [comment]
> I am renting a server off apex hosting. I tried to use the mod but the server wont even start up. It crashes before the server can even go up. Any help with this?

Well for starters if you want anyone to be above to help you, you need to provide more information other than "it doesn't work, please help". 

What forge are you using, what other mods are you using, where is your latest.log report and where are your crash reports? You've provided zero information it documentation that would be if help to the mod author it anyone else.
