### ISSUE TITLE
Ice & Fire Mob Spawn Eggs Don't Work With Apotheosis Spawners / Nothing Spawns

### ISSUE THREAD

**Issue by DizzyDJW** [Shadows-of-Fire/Apotheosis#343]
Essentially, the mob shows up in the spawner but no matter what block I place beneath it or what light level I make it the mob just spins and spins.

Max Upgraded Spawner, with 5 Min to 10 Max Spawn Delay. On a skyblock, way under mob cap.

Minecraft: 1.16.5
Latest Version

**Comment by brisingraerowing** [comment]
You might need to use the Dragon Egg(?) to disable all spawn conditions. The mob just spinning usually means one of the spawn conditions isn't being met.

**Comment by DizzyDJW** [comment]
We need a tooltip that can show up with The One Probe that shows what the spawn conditions are. 
Just like crouch to see:
Dark: Yes/No
Block: Grass/Any/Etc...
Biome: Any/Etc...

**Comment by Shadows-of-Fire** [comment]
I literally could not provide that if I wanted to.

Anyway, its probably just the spawn conditions of the entity, as thats how the spawner works.
