### ISSUE TITLE
[Feature Request] Let spawners only drop spawner scrap once

### ISSUE THREAD

**Issue by DereC4** [Shadows-of-Fire/Apotheosis#344]
I'm using this on a Valhelsia 3 server and there are certain enchants and mods that make durability really high or even just make an item unbreakable, and combined with silk touch players have been using this to farm spawner scrap by just placing a spawner and breaking and repeating. I was wondering if there was a way to tell if a spawner had been placed by player and add a tag to it so that it cant drop any scrap, but a naturally generated one can

**Comment by Shadows-of-Fire** [comment]
Spawner Scrap is not from apoth, so you'll have to go ask whoever is adding that to change how that works.
