### ISSUE TITLE
Apotheosis not working in Valhelsia 3

### ISSUE THREAD

**Issue by DragonSeason** [Shadows-of-Fire/Apotheosis#345]
It seems like Apotheosis isn't working in Valhelsia 3.
Apotheosis and the respective dependencies are in the specific mod folder of that instance.
Weirdly enough, if I type @apotheosis in the JEI search bar, it finds the spawner and the capturing books of Apotheosis, but nothing else. I noticed it wasn't working, when I tried to mine a spawner with Silk Touch and it didn't drop.
Then I went ahead and wanted to try out the enchantments in a creative world (I thought maybe it just wasn't showing in JEI), but I can't craft the bookshelves. 
Does anyone know what I could do?

**Comment by Shadows-of-Fire** [comment]
certain modules are disabled in that modpack, you would need to re-enable them (in the config file) or use a different modpack.
