### ISSUE TITLE
Enchanted book can't be combined

### ISSUE THREAD

**Issue by DragonSeason** [Shadows-of-Fire/Apotheosis#346]
I tried searching for info, but there seem to be none about it.
I can't seem to combine enchanted books which are at or above the vanilla enchant limit.
E.g.: Sharpness 5 + Sharpness 5 isn't possible.

**Comment by DragonSeason** [comment]
Can't be combined to Sharpness 6.
And Sharpness 6 + Sharpness 6 isn't even possible.

**Comment by Shadows-of-Fire** [comment]
Sounds like either the ench module is off or there's a mod conflict.
