### ISSUE TITLE
Server crash on chunk generation

### ISSUE THREAD

**Issue by StuAhpla** [Shadows-of-Fire/Apotheosis#348]
https://pastebin.com/PaCuqzjF

I'm not sure what exactly is causing it but what I can understand is that any time the game tries to spawn an underground boss it instantly crashes. Disabling the deadly module of course stops the crashing.

**Comment by Shadows-of-Fire** [comment]
That would mean you're somehow attempting world generation without bosses being loaded, which should be impossible, unless some other mod is attempting to force world generation before that load has finished.  Either way, that's invalid behavior.
