### ISSUE TITLE
[Suggestion] Remove Life-Mending from Enchanting Tables

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#349]
Relayed suggestion from: https://github.com/NillerMedDild/Enigmatica6/issues/1968

> 
> 
> **Description**
> Either (a) make Life-Mending not a curse, or (b) remove it from the possible enchantments which an Enchanting Table can bestow.
> 
> **Why would you like this added/changed?**
> The Life-Mending enchantment can be bestowed randomly when enchanting an item at the Enchanting Table. It's also a curse.
> 
> Because it's a curse, it can't be removed at a grindstone; you have to use a prismatic web and 30 levels to remove it from an item. And any item with any enchantment on it, even just a curse, can't be enchanted again.
> 
> No other curses come from an Enchanting Table. Risking a curse when enchanting a nice affixed item really sucks. Having it happen about 25% of the time with a fully-upgraded enchanting station _really_ sucks.
> 
> **Screenshots if applicable.**
> n/a

**Comment by Shadows-of-Fire** [comment]
Hm, well LM will certainly not be leaving the table, but maybe items with _just_ curses should be re-enchantable...

**Comment by Wicked1667** [comment]
I would like to give a bit of feedback on the enchanting system. Can you instead add a special type of bookcase or block that when put under the enchanting table removes the chance to get curses or (what I would prefer) added with the bookshelves to lower the chance to get curses and make it stackable enough to say like 4 curse nullifying bookcases removes chances of getting a curse (25% each)

**Comment by Shadows-of-Fire** [comment]
The Seashelf of Aquatic Filtration achieves this goal already
