### ISSUE TITLE
Crash on using Zombie spawner from dungeon

### ISSUE THREAD

**Issue by Bidgam** [Shadows-of-Fire/Apotheosis#350]
Placed a zombie spawner in my base with a Fiery torch on it and the server crashed after a zombie spawned.

It might not having anything to do with the torch, but I'm including it in here anyway.

I set the config of spawner to 'false', was able to get in the game and remove the torch (block looked like they do without a texture) and then the server crashed again. Tried logging in again and it refused.

Reset to last world. Doing some further testing, but this is what I have at the moment.

**Comment by Shadows-of-Fire** [comment]
crash report?

**Comment by Bidgam** [comment]
Forgot to say it's 1.16.5 and Forge 36.1.3

Crash report: https://pastebin.com/629Te85c

Thanks

**Comment by Bidgam** [comment]
This might actually be more Industrial Foregoing with the mob imprisonment tool actually, but if you can take a look to make sure it's not a cross-mod incompatibility with yours at least.

**Comment by Shadows-of-Fire** [comment]
That crash has nothin to do with apoth whatsoever.  Looks like you need to update Titanium or IF
