### ISSUE TITLE
Commit b6466/v4.5.0 Resolves a serious bug

### ISSUE THREAD

**Issue by gattsuru** [Shadows-of-Fire/Apotheosis#351]
Would it be possible to get this (and matching Placebo v4.4.2) published to CurseForge?

Specifically, the [update to EnchModuleClient](https://github.com/Shadows-of-Fire/Apotheosis/commit/0c31bcb2912ce471abb2e6615c7bd8c550fb6466).

This came to my attention as a Minecolonies bug in Life In The Village 2, where a block from Farmer's Delight depends on Tag-related information, while the tooltip event is called on remote clients earlier than the Tags are populated.  These two mods (+ Placebo) alone will show the critical exception, included as an attached log: see the line "[shadows.apotheosis.ench.EnchModuleClient:tooltips:48]: java.lang.IllegalStateException: Tag farmersdelight:tray_heat_sources used before it was bound" for the relevant callstack.

[2021-04-13-1.log](https://github.com/Shadows-of-Fire/Apotheosis/files/6301359/2021-04-13-1.log)

On its own, this wouldn't be that big of a deal; another tooltip event will be along shortly. However, Forge appears to allow this to bubble fairly high up the call stack; an unhandled exception here effects not only other mods subscribed to the tooltip event, but also some unrelated event calls, including the initial RecipesUpdatedEvent from a connecting remote client.  For Minecolonies, that prevent the client from loading all furnace recipes until another RecipesUpdatedEvent occurs (which generally doesn't happen), and has significant downstream effects related to item filter GUI selections.

Apotheosis 4.5.0 + Placebo 4.4.2 self-built is tested to resolve the problem.  Sorry for the github issue, but didn't want to ping you out of the blue on the Forge Discord.

**Comment by Shadows-of-Fire** [comment]
The new update will be released when it is finished.  It is not ready yet.
