### ISSUE TITLE
Putting any apotheosis generated item in an anvil renames it to weird numbers.

### ISSUE THREAD

**Issue by Art1xs** [Shadows-of-Fire/Apotheosis#353]
https://user-images.githubusercontent.com/63431899/114982577-40b5d800-9e55-11eb-9fd2-d998fdcd6e5a.mp4

This video shows the bug in all its glory. 

I noticed this bug in a small modpack I made for myself. I am not too sure what provokes this bug, but it seems to break the names (and sometimes attributes) of all the apotheosis generated loot in chests. 

In this video, the only other mods I have installed are placebo (naturally), guard villagers, and advanced x-ray (I needed to look for a chest with apotheosis loot on it. don't hurt me)

**Comment by Shadows-of-Fire** [comment]
This just happens with literally any item over a certain character limit, I'm not sure of a good solution to this issue

**Comment by Shadows-of-Fire** [comment]
Alright I spent a fair amount of time looking into this and have determined that there is no good way to go about solving it.  The anvil translates the name into a String under all cases, so anything with a custom name that uses anything more than just default string characters just fails.  It would require a complete rework of how the anvil handles item names to fix it.

**Comment by Art1xs** [comment]
alright, thank you for responding. Just making sure that you're aware of this!
