### ISSUE TITLE
It will crash in the 1.15.2 server

### ISSUE THREAD

**Issue by YYC2001** [Shadows-of-Fire/Apotheosis#354]
[crash-2021-04-17_20.26.35-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6330296/crash-2021-04-17_20.26.35-server.txt)
[crash-2021-04-17_20.37.27-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6330297/crash-2021-04-17_20.37.27-server.txt)
[crash-2021-04-17_20.24.29-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6330299/crash-2021-04-17_20.24.29-server.txt)
![image](https://user-images.githubusercontent.com/59162403/115130249-9f7b7d00-a020-11eb-9e50-8809d6588ace.png)

**Comment by Shadows-of-Fire** [comment]
1.15 is not supported
