### ISSUE TITLE
Quark Ancient Tomes

### ISSUE THREAD

**Issue by Nitess** [Shadows-of-Fire/Apotheosis#356]
Enchanted books above minecraft level are not combined. I have a fairly large assembly of mods, I spent about an hour trying to figure out what is in conflict. 
The latest version of Apotheosis states: “Changing the maximum level of enchantments is now applied more broadly and can be targeted to other mods. (Quark Ancient Tomes is the only supported mod at the moment.) “Quark has some kind of support, it's not clear what exactly it does.
_______
The bottom line is that it is not possible to combine above the level of vanilla enchantments.
But if "Ancient Tomes" = true, then on an anvil, for example, with Sweeping Edge, I can combine 1 level higher, both with the use of an ancient tome, and without it, with ordinary books.
When "Ancient Tomes" = false, the combo works above the vanilla level. By default, Sweeping Edge can be combined up to level 8.
_______
If this is what is meant by "Quark is supported", then it is worth mentioning about it somewhere, that when you install a quark, you will receive a cap of the level of its ancient tomes.
_______
Ps. I do not know English very well, sorry if something is not clear.
This is not a problem, since I do not use ancient tomes, but there was no need to turn them off. With this message, I report an error, or that it is worth adding somewhere how the quark is supported. I seriously spent about an hour on this.

**Comment by Shadows-of-Fire** [comment]
Quark repackaged their classes, so my coremod wasn't looking in the right spot.  Fixed.

**Comment by The-Arcanian** [comment]
@Shadows-of-Fire This bug seems to have resurfaced in 1.18.1.
![2022-01-25_15 39 51](https://user-images.githubusercontent.com/7005184/151056044-075a49c7-04fd-4250-b213-9b4cd04eaa54.png)

**Comment by Shadows-of-Fire** [comment]
Yeah its already fixed in dev, the coremod needed to be retargeted.

**Comment by The-Arcanian** [comment]
Ok, just making sure you were aware.
