### ISSUE TITLE
1.16.5 Silent's Gems Gravity V & VI do not work

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Shadows-of-Fire/Apotheosis#358]
I had a player of my modpack, Create on a Potato PC report:

>  There's a problem with Gravity enchantment on the pickaxes. I have two with Gravity V and VI but they don't mine underwater at all, as if I have mining fatigue! And the same thing is while flying

Minecraft: 1.16.5
Forge: 36.1.0
Apotheosis: 1.16.3-4.4.1

I tried to replicate this player's setup but was unable to spawn in a Gravity V or VI book. For now, I have limited the level of Gravity to the default level 3

**Comment by Shadows-of-Fire** [comment]
That would be on SG to fix, I cannot make higher levels of another mod's enchantment work.
