### ISSUE TITLE
[1.16.5] Bosses ignore blocks that prevent hostile mob spawn prevention

### ISSUE THREAD

**Issue by KajesLorian** [Shadows-of-Fire/Apotheosis#360]
Minecraft 1.16.5
Forge 36.1.0
Apotheosis-1.16.4-4.5.1

Bosses will still spawn in areas with blocks that are designed to prevent hostile mob spawns, such as the Torchmaster Mega Torch. These bosses specifically spawned above ground at night in an area where no hostile mobs can spawn.

**Comment by Shadows-of-Fire** [comment]
So I don't think there's much I can do with regards to torchmaster, as it's running it's event handler at lowest priority.  I'll change mine to lowest, though I really think TorchMaster should be on a higher priority, as there is literally no way for me to tell if something has been blocked by it.

**Comment by KajesLorian** [comment]
It did not fix it, so I'll submit a bug report to Torchmaster. Thank you for trying!
