### ISSUE TITLE
Suggestion - Charm Belt for holding multiple charms without taking up inventory

### ISSUE THREAD

**Issue by tanyan-tanyan** [Shadows-of-Fire/Apotheosis#361]
Reliquary has mob charms which allow the players to be 'invisible' to mobs, in a sense that mobs will not attack the player on sight and as a result, they become passive to players.
Because of the sheer number of mob charms one can make, it is not ideal to hold the charms in the inventory or baubles, so the mod has introduced a belt which acts like a backpack - you can open it and put mob charms inside it, and then place the belt in a curios slot to save up on inventory space. The mob charms still work as intended while in the belt.

This suggestion would especially be useful for modpacks which introduce numerous potion effects, for example OreSight, which is split into dozens of potion effects for every single ore type in the modpack. 

Here are some screenshots which demonstrate how Reliquary does it:

![javaw_l8P1b8Su98](https://user-images.githubusercontent.com/68793071/116005670-e8729900-a5ff-11eb-827d-4a5cfdf760bc.png)

![javaw_7G8a4g6ZPo](https://user-images.githubusercontent.com/68793071/116005671-ea3c5c80-a5ff-11eb-9daf-bef3f1c2396c.png)

In the above screenshot, there seems to be only 3 slots, however the top slot is for inserting a new charm. The GUI automatically creates new slots on demand.

**Comment by Shadows-of-Fire** [comment]
I don't think the player should have access to an infinite amount of potion charms.  They are already strong as-is.
