### ISSUE TITLE
Make the lootTables configurable with data packs

### ISSUE THREAD

**Issue by Schummel-8** [Shadows-of-Fire/Apotheosis#362]
As of now, there is no way to change the loot tables of the tome towers.
This is unfortunately for my modpack because there seems to be enchanted books which are randomly enchanted and this way ignoring the disabled enchantments from the enchantments module of this mod.
So I get enchanted books with normally disabled enchantments.

**Comment by Shadows-of-Fire** [comment]
They are.  You need to provide a loot table override at the location being used, and it will take control.

**Comment by Schummel-8** [comment]
But I want to edit and expand upon the existing loot table. I can add the affix and enchanting books myself but how do I add affix items to my loot tables?

**Comment by Shadows-of-Fire** [comment]
You would provide a loot pool entry with type `apotheosis:affix_entry`
