### ISSUE TITLE
Spawner Spawn Timer not changing, with mob changes using Mob Eggs.

### ISSUE THREAD

**Issue by Krazyman999** [Shadows-of-Fire/Apotheosis#364]
I don't know if its a feature, but if the timer on a mob spawner is 24,000. Then you change it with a Spawn Egg, it still remains the same.

This means, your starting spawn timer is set, on a mob spawner you find.

Fireworks... 24,000 min, 24,000 max
Fangs.......... 0 min, 0 max
Skeleton.... 200 min, 800 max

After hitting them with a Spawn Egg, the timer remains the same. Which means, the 24,000 spawners are basically worthless. Even with Sugar and Clocks, to change the amounts.

That would mean, you'd have to search for a good spawner, before changing it. The Fangs one above, at 0 min, and 0 max spawn times is what I mean.

======

Possible...

Spawn Eggs contain time details, min and max spawn times, to change spawner times.

======

**Comment by Shadows-of-Fire** [comment]
This is working as intended. 
I don't generate any spawners with spawn times of 24k anyway.

**Comment by Krazyman999** [comment]
> This is working as intended.
> I don't generate any spawners with spawn times of 24k anyway.

It must be another mod, that is altering the times on your mod.

![Spawner info 24000](https://user-images.githubusercontent.com/56986850/116589333-71494780-a914-11eb-8784-827a05a9c407.png)
