### ISSUE TITLE
Tome Towers Terraforged Compatibility

### ISSUE THREAD

**Issue by Yourname942** [Shadows-of-Fire/Apotheosis#366]
Please allow this structure to be compatible with Terraforged. Thank you.

https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

(relating to this ticket)
https://github.com/TerraForged/tracker/issues/105
![2021-04-30_14 40 34](https://user-images.githubusercontent.com/58750222/116835093-f8a1ef80-ab8e-11eb-8c49-8eeb8467f1d7.png)
![2021-05-02_17 54 45](https://user-images.githubusercontent.com/58750222/116835097-fdff3a00-ab8e-11eb-8b3f-7f2cf34aed5d.png)

**Comment by Shadows-of-Fire** [comment]
The towers are generated as Features, not Structures.  The apoth config that lets you turn down the frequency works fine for adjusting how often they generate, even in TF worlds.
