### ISSUE TITLE
Conflict with Forbidden & Arcanus

### ISSUE THREAD

**Issue by Nubidubi23** [Shadows-of-Fire/Apotheosis#367]
If you have both mods installed and break a spawner with silk touch , it always drops a Spawner Scrap from F&A. Doesn't happen without F&A obviously

Minecraft 1.16.5 , Forge 36.1.0 , 
forbidden_arcanus-1.16.4-1.0.0 ,
Apotheosis-1.16.3-4.4.1

**Comment by Nubidubi23** [comment]
Mirror : https://github.com/stal111/Forbidden-Arcanus/issues/162

**Comment by Shadows-of-Fire** [comment]
Previously this was fixed using the harvestdropsevent but it's gone now, I'll see what can be done
