### ISSUE TITLE
Server lockup after Apotheosis WorldGenDungeons

### ISSUE THREAD

**Issue by AndreVallestero** [Shadows-of-Fire/Apotheosis#368]
Background, I've had this issue a few weeks ago and it was resolved by deleting a player's data on my customized Project Ozone 3 server, otherwise, when a specific player would log in, the server would lockup and it would take 60 second to process a tick. The past 2 days I've had the same issue again. Here are the last few lines in console output before the server crashes, this is the same as the last incident:

```
06.05 10:14:40 [Server] Server thread/INFO [neid]: Patching class: "ru.fewizz.neid.asm.Hooks" with Transformer Group: "TransformerGroupChunkPrimer"
06.05 10:14:41 [Server] Server thread/INFO [Apotheosis : Core]: Transforming WorldGenDungeons...
06.05 10:14:41 [Server] Server thread/INFO [Apotheosis : Core]: Successfully transformed WorldGenDungeons
06.05 10:15:40 [Server] Server Watchdog/FATAL [minecraft/ServerHangWatchdog]: A single server tick took 60.01 seconds (should be max 0.05)
```

[crash-2021-05-06_14.15.40-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6435417/crash-2021-05-06_14.15.40-server.txt)

**Comment by Shadows-of-Fire** [comment]
mc 1.12 is not supported
