### ISSUE TITLE
Crash with Various Oddities

### ISSUE THREAD

**Issue by Meshinator69** [Shadows-of-Fire/Apotheosis#37]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ApotheosisCore (Apotheosis-1.12.2-1.9.3.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  LoadingPlugin (Quark-r1.5-146.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  AstralCore (astralsorcery-1.12.2-1.10.17.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2 (1).jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 4/20/19 9:55 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.block.state.IBlockState.func_185895_e()Z
	at com.lying.variousoddities.potion.PotionClimbing.isClimbable(PotionClimbing.java:59)
	at com.lying.variousoddities.potion.PotionClimbing.onLivingUpdateEvent(PotionClimbing.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_PotionClimbing_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(EntityCreeper.java:172)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.lying.variousoddities.potion.PotionClimbing.isClimbable(PotionClimbing.java:59)
	at com.lying.variousoddities.potion.PotionClimbing.onLivingUpdateEvent(PotionClimbing.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_635_PotionClimbing_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:575)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2095)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(EntityCreeper.java:172)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.EntityCreeper)
	Entity ID: 1691694
	Entity Name: Father Sillob the Sneaky
	Entity's Exact location: 134.42, 27.00, -276.92
	Entity's Block location: World: (134,27,-277), Chunk: (at 6,1,11 in 8,-18; contains blocks 128,0,-288 to 143,255,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.01, -0.08, 0.06
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Meshinator'/1018, l='world', x=22.07, y=81.00, z=-295.61]]
	Chunk stats: ServerChunkCache: 617 Drop: 0
	Level seed: 9152932901885413769
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (114,64,228), Chunk: (at 2,4,4 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5579960 game time, 6035520 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 62064 (now: false), thunder time: 164970 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3988917776 bytes (3804 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 10 total; -XX:+UseG1GC -Xmx10G -Xms10G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ParallelGCThreads=4 -XX:+UseStringDeduplication
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 107
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 136 mods loaded, 136 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                  | Source                                             | Signature                                |
	|:------ |:--------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                   | 9.42                     | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2815-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2815             | forge-1.12.2-14.23.5.2815-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit             | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| LCHIJA | foamfixcore           | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCHIJA | dsurroundcore         | 3.5.4.3                  | minecraft.jar                                      | None                                     |
	| LCHIJA | jei                   | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
	| LCHIJA | abyssalcraft          | 1.9.6                    | AbyssalCraft-1.12.2-1.9.6.jar                      | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCHIJA | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                   | None                                     |
	| LCHIJA | acheads               | 2.1.0                    | AbyssalCraft+Heads-1.12.2-2.1.0.jar                | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | chisel                | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                           | None                                     |
	| LCHIJA | twilightforest        | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar        | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| LCHIJA | acintegration         | 1.6.6                    | AbyssalCraft+Integration-1.12.2-1.6.6.jar          | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | aether_legacy         | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                    | None                                     |
	| LCHIJA | animalium             | 0.3.8                    | Animalium-0.3.8.jar                                | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2425               | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar      | None                                     |
	| LCHIJA | botania               | r1.10-361                | Botania+r1.10-361.jar                              | None                                     |
	| LCHIJA | craftstudioapi        | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | natura                | 1.12.2-4.3.2.66          | natura-1.12.2-4.3.2.66.jar                         | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                    | None                                     |
	| LCHIJA | animania              | 1.6.2                    | animania-1.12.2-1.6.2.jar                          | None                                     |
	| LCHIJA | placebo               | 1.5.1                    | Placebo-1.12.2-1.5.1.jar                           | None                                     |
	| LCHIJA | apotheosis            | 1.9.3                    | Apotheosis-1.12.2-1.9.3.jar                        | None                                     |
	| LCHIJA | applecore             | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | appleskin             | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCHIJA | aquaculture           | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LCHIJA | astralsorcery         | 1.10.17                  | astralsorcery-1.12.2-1.10.17.jar                   | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | atum                  | 2.0.4                    | Atum-1.12.2-2.0.4.jar                              | None                                     |
	| LCHIJA | quark                 | r1.5-146                 | Quark-r1.5-146.jar                                 | None                                     |
	| LCHIJA | autoreglib            | 1.3-26                   | AutoRegLib-1.3-26.jar                              | None                                     |
	| LCHIJA | betteranimalsplus     | 5.0.2                    | betteranimalsplus-5.0.2 (1).jar                    | None                                     |
	| LCHIJA | patchouli             | 1.0-18                   | Patchouli-1.0-18.jar                               | None                                     |
	| LCHIJA | llibrary              | 1.7.18                   | llibrary-1.7.18-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | bewitchment           | @VERSION@                | Bewitchment-1.12.2-0.0.19.44-indev.jar             | None                                     |
	| LCHIJA | bibliocraft           | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | bloodmoon             | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf             | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | forgelin              | 1.8.2                    | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHIJA | bountiful             | 2.2.0                    | Bountiful-2.2.0.jar                                | None                                     |
	| LCHIJA | cavern                | 2.1.9                    | Cavern_1.12.2-v2.1.9.jar                           | b78e30ad27c82f3e348f76edf497058678207299 |
	| LCHIJA | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | chancecubes           | 1.12.2-3.2.3.242         | ChanceCubes-1.12.2-3.2.3.242 (1).jar               | None                                     |
	| LCHIJA | coralreef             | 2.0                      | CoralReef-2.5-1.12.2.jar                           | None                                     |
	| LCHIJA | extendedrenderer      | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJA | coroutil              | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJA | configmod             | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
	| LCHIJA | customizeddungeonloot | 1.0.3                    | Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar        | None                                     |
	| LCHIJA | dmonsters             | 1.7                      | Deadly+Monsters+1.71.jar                           | None                                     |
	| LCHIJA | doggytalents          | 1.14.2.396               | DoggyTalents-1.12.2-1.14.2.396-universal.jar       | None                                     |
	| LCHIJA | dldungeonsjbg         | 1.12.3                   | DoomlikeDungeons-1.12.3-MC1.12.2.jar               | None                                     |
	| LCHIJA | mocreatures           | 12.0.5                   | DrZharks Mocreatures Mod-12.0.5.jar                | None                                     |
	| LCHIJA | dc                    | Beta 1.0.0               | DungeonCraft+Beta+1.0.0.jar                        | None                                     |
	| LCHIJA | dungeonmobs           | 5.7.2                    | dungeonmobs-5.7.2-MC1.12.2.jar                     | None                                     |
	| LCHIJA | dungeontactics        | DT-0.15.9                | DungeonTactics-1.12.2-0.15.9.jar                   | None                                     |
	| LCHIJA | embers                | 0.230                    | embers-0.230.jar                                   | None                                     |
	| LCHIJA | erebus                | 1.0.29                   | Erebus-1.0.29.jar                                  | None                                     |
	| LCHIJA | exoticbirds           | 1.0                      | Exotic+Birds+1.12.2-2.2.1.jar                      | None                                     |
	| LCHIJA | familiarfauna         | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                    | None                                     |
	| LCHIJA | fastfurnace           | 1.2.3                    | FastFurnace-1.12.2-1.2.3.jar                       | None                                     |
	| LCHIJA | fastleafdecay         | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCHIJA | foamfix               | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2 (1).jar                      | None                                     |
	| LCHIJA | fossil                | 8.0.0                    | fossilsarcheology-8.0.0.jar                        | None                                     |
	| LCHIJA | gottschcore           | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar      | None                                     |
	| LCHIJA | gravestone            | 1.3.1                    | GraveStone-1.12.2-Graves-1.3.1.jar                 | None                                     |
	| LCHIJA | gravestone-extended   | 1.3.5.1                  | GraveStone-1.12.2-Extended-1.3.5.1.jar             | None                                     |
	| LCHIJA | grimoireofgaia        | 1.6.9.3                  | GrimoireOfGaia3-1.12.2-1.6.9.3.jar                 | None                                     |
	| LCHIJA | overlord              | 2.4.14                   | Overlord-1.12.2-2.4.14.jar                         | None                                     |
	| LCHIJA | guideapi              | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| LCHIJA | heroicarmory          | 1.1.3                    | heroicarmory-1.2.0.jar                             | None                                     |
	| LCHIJA | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCHIJA | iceandfire            | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                        | None                                     |
	| LCHIJA | ic2                   | 2.8.109-ex112            | industrialcraft-2-2.8.109-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | inventorypets         | 2.0.1                    | inventorypets-1.12-2.0.1.jar                       | None                                     |
	| LCHIJA | inventorytweaks       | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jmh                   | 2.0                      | jmh_1.12-2.0.jar                                   | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.5b4           | journeymap-1.12.2-5.5.5b4.jar                      | None                                     |
	| LCHIJA | jaff                  | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12 (1).jar                  | None                                     |
	| LCHIJA | jeid                  | 1.0.2-26                 | JustEnoughIDs-1.0.2-26.jar                         | None                                     |
	| LCHIJA | levelup2              | ${version}               | Level+Up!+2-1.1.22-1.12 (1).jar                    | None                                     |
	| LCHIJA | lex                   | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                             | None                                     |
	| LCHIJA | limitedlives          | 1.12.1-1.0.1             | LimitedLives-1.12.1-1.0.1.jar                      | None                                     |
	| LCHIJA | livingenchantment     | 3.1.9                    | living_enchantment-3.1.9.jar                       | None                                     |
	| LCHIJA | lootbags              | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                        | None                                     |
	| LCHIJA | malisiscore           | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
	| LCHIJA | malisisdoors          | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | millenaire            | Millénaire 7.2.0         | millenaire-1.12.2-7.2.0.jar                        | None                                     |
	| LCHIJA | millenaireextended    | 0.2.1                    | Millénaire+Extended-1.12.2-0.2.1.jar               | None                                     |
	| LCHIJA | mobbanners            | 1.0.5                    | MobBanners-1.12.2-1.0.5.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | morpheus              | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
	| LCHIJA | mowziesmobs           | 1.5.3                    | mowziesmobs-1.5.3.jar                              | None                                     |
	| LCHIJA | naturescompass        | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
	| LCHIJA | nex                   | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                          | None                                     |
	| LCHIJA | recipehandler         | 0.13                     | NoMoreRecipeConflict-0.13(1.12.2).jar              | None                                     |
	| LCHIJA | pirates               | 0.0.2                    | pirates-0.0.4.jar                                  | None                                     |
	| LCHIJA | plants2               | 2.10.7                   | Plants-1.12.2-2.10.7.jar                           | None                                     |
	| LCHIJA | potioncore            | 1.6_for_1.12.2           | PotionCore-1.6_for_1.12.2.jar                      | None                                     |
	| LCHIJA | pvj                   | 1.6.1                    | ProjectVibrantJourneys-1.12.2-1.6.1.jar            | None                                     |
	| LCHIJA | pyramidplunder        | 1.12.2-1.0               | PyramidPlunder-1.12.2-1.2.jar                      | None                                     |
	| LCHIJA | qualitytools          | 1.0.6_for_1.12.2         | QualityTools-1.0.6_for_1.12.2.jar                  | None                                     |
	| LCHIJA | railcraft             | 12.0.0                   | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | randomloot            | 1.3                      | RandomLoot-1.4.1.jar                               | None                                     |
	| LCHIJA | randomthings          | 4.2.7.1                  | RandomThings-MC1.12.2-4.2.7.1.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | reccomplex            | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                       | None                                     |
	| LCHIJA | xreliquary            | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                     | None                                     |
	| LCHIJA | roguelike             | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| LCHIJA | ruins                 | 17.1                     | Ruins-1.12.2.jar                                   | None                                     |
	| LCHIJA | rustic                | 1.1.0                    | rustic-1.1.0.jar                                   | None                                     |
	| LCHIJA | rusticthaumaturgy     | 4.4                      | Rustic+Thaumaturgy-4.4.jar                         | None                                     |
	| LCHIJA | scp                   | 2.1.1                    | SCP+Lockdown-1.12.2-2.1.1-beta.jar                 | None                                     |
	| LCHIJA | solcarrot             | 1.12.2-1.6.2             | solcarrot-1.12.2-1.6.2.jar                         | None                                     |
	| LCHIJA | spawntemple           | 2.1                      | SpawnTemple-v.2.1-mc1.12.jar                       | None                                     |
	| LCHIJA | storagedrawers        | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                    | None                                     |
	| LCHIJA | theeightfabledblades  | 1.0.0                    | TheEightFabledBlades V2.0.01.jar                   | None                                     |
	| LCHIJA | tinkersaether         | 1.3.0                    | tinkersaether-1.3.0.jar                            | None                                     |
	| LCHIJA | toroquest             | 1.12.2-5.3               | toroquest-1.12.2-5.3.jar                           | None                                     |
	| LCHIJA | totemic               | 1.12.2-0.11.6            | Totemic-1.12.2-0.11.6.jar                          | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| LCHIJA | treasure2             | 1.3.0                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar        | None                                     |
	| LCHIJA | tropicraft            | 7.1.8.105                | tropicraft-MC1.12.2-7.1.8.105.jar                  | None                                     |
	| LCHIJA | varodd                | 4.07                     | varodd-1.12.2-4.07.jar                             | None                                     |
	| LCHIJA | wanionlib             | 1.12.2-2.2               | WanionLib-1.12.2-2.2 (1).jar                       | None                                     |
	| LCHIJA | waystones             | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                        | None                                     |
	| LCHIJA | wearablebackpacks     | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                 | None                                     |
	| LCHIJA | zoocraftdiscoveries   | 1.0                      | Zoocraft+Discoveries+1.12.2-1.3.0.jar              | None                                     |
	| LCHIJA | orelib                | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2 (1).jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround             | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | immersiveengineering  | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | ladylib               | 2.1                      | Ladylib-2.1.jar                                    | None                                     |
	| LCHIJA | lumen                 | 0.4.0                    | lumen-Beta+0.4.1.jar                               | None                                     |
	| LCHIJA | structurize           | 1.12.2-0.10.79-ALPHA     | structurize-1.12.2-0.10.79-ALPHA.jar               | None                                     |
	| LCHIJA | minecolonies          | 1.12.2-0.10.269-ALPHA    | minecolonies-1.12.2-0.10.269-ALPHA-universal.jar   | None                                     |
	| LCHIJA | thebetweenlands       | 3.4.6                    | TheBetweenlands-3.4.6-universal.jar                | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | unidict               | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2 (1).jar                       | None                                     |

	Loaded coremods (and transformers): 
ApotheosisCore (Apotheosis-1.12.2-1.9.3.jar)
  shadows.ApotheosisTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.2.7.1.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (Quark-r1.5-146.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.6-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.17.jar)
  
JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  org.dimdev.jeid.JEIDTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
  com.chocohead.biab.BornInABarn
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2 (1).jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['Meshinator'/1018, l='world', x=22.07, y=81.00, z=-295.61]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Shadows-of-Fire** [comment]
This has nothing to do with apotheosis.  This is a bug in the other mod, as they are calling a method that doesn't exist on a dedicated server in common code (IBlockProperties#isTranslucent)

**Comment by Meshinator69** [comment]
I appreciate the fast response! I just added apotheosis today (and had Various oddities for several days), and was generating new terrain, and this crash started happening, I thought it might be from the generation of the dungeon modules in conjunction with this, sorry for the erroneous report, I just like to help if I can! I did remove the other mod and everything is fine now. Thank you
