### ISSUE TITLE
[1.16.5] Endless Quiver Enchant does not apply to Archer's Paradox arrows

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#373]
A bow enchanted with Endless Quiver will still consume arrows from the mod Archer's Paradox. Tested with Diamond Arrows

### Versions
- Forge-1.16.5-36.1.13
- Apotheosis-1.16.4-4.5.2
- archers_paradox-1.16.4-1.2.0

**Comment by Shadows-of-Fire** [comment]
Yeah I think I've heard this issue floated around a couple times.  I'll see if KL can call super.isInfinite or if I need to retarget my coremods at AP classes

**Comment by Shadows-of-Fire** [comment]
KL has agreed to add a super call at https://github.com/KingLemming/1.16/blob/main/CoFHCore/src/main/java/cofh/core/item/ArrowItemCoFH.java#L95
which should resolve this on AP's side
