### ISSUE TITLE
Mod compat issue: Lack of Deadly worldgen in some biome types

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#375]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2103

- Apotheosis-1.16.4-4.5.2

This issue *does not* appear with just Apotheosis, so this is more of a PSA than anything.

> Certain biomes, or perhaps biome groups, wont generate Apotheosis structures.
> 
> For example, in desert-type biomes, it seems to be impossible to locate boss chambers/dungeons and rogue spawners (the ones with blocks above them and vines surrounding them)
> 
> The best way to figure out if a biome is generating them, is to go into spectator mode, and give yourself night vision. When flying around the caves, you should be able to spot them fairly quickly if they generate in the biome your currently in.
> 
> The biomes that I've had issues locating structures in so far are:
> -Jungle type biomes
> -Desert type biomes
> -Ice type biomes
> 
> I'll add more to this list as I find them. I should also mention the world type I have tested this on is the default option. I haven't checked other world types yet, as I usually use default. This doesn't appear to be an issue with Apotheosis directly, as a testing modpack I have with a few other mods, seems to generate structures from Apotheosis just fine.

**Comment by Shadows-of-Fire** [comment]
apoth features are injected into all biomes during the biome load event (which is forge api for feature addition)
If that doesn't work then something else must be messing with stuff

**Comment by NielsPilgaard** [comment]
Could be Structure Gel API, I'll tinker with it when my issue tracker isn't so packed :P

**Comment by Shadows-of-Fire** [comment]
Maybe related to #380 ?  I guess see if it persists with 4.6.0

**Comment by NielsPilgaard** [comment]
It does I'm afraid.

**Comment by Shadows-of-Fire** [comment]
is there perhaps a consistent set of biomes where it occurs?  And anything that they have in common?

**Comment by NielsPilgaard** [comment]
The biometypes where this happens are
-Jungle type biomes
-Desert type biomes
-Ice type biomes

I'm not sure what they have in common though.

**Comment by Shadows-of-Fire** [comment]
This is including vanilla biomes as well?  I swear I've seen stuff in deserts

**Comment by NielsPilgaard** [comment]
It includes vanilla biomes as well, but remember this issue is not present with only Apotheosis and dependencies, so you probably have seen stuff in deserts.

**Comment by Shadows-of-Fire** [comment]
From discussion on discord and CF, this appeared to be caused by YUNG's Better Dungeons   An issue was opened over there, but no response was ever received.
#502
https://github.com/yungnickyoung/YUNGs-Better-Dungeons/issues/25
