### ISSUE TITLE
Crash when mousing over Kikoku from MiniUtilities in JEI

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#377]
Forge: 36.1.16
Apotheosis: Apotheosis-1.16.4-4.5.2
MiniUtilities: miniutilities-1.1.0

Crash when mousing over Kikoku from MiniUtilities in JEI

[crash-2021-05-12_21.33.53-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6469979/crash-2021-05-12_21.33.53-client.txt)

https://github.com/OneLemonyBoi/MiniUtilities/issues/24

**Comment by Shadows-of-Fire** [comment]
From my understanding of that code it would mean that item has a broken attribute modifier on it, I'd need to do some more checking, but almost certain it's their fault

**Comment by Shadows-of-Fire** [comment]
Yeah that line is Attribute#getRegistryName, which means his arent being registered.  Other mod's end.

**Comment by MuteTiefling** [comment]
Alrighty, thanks for looking into it :D
