### ISSUE TITLE
Getting hit by boss crash?

### ISSUE THREAD

**Issue by Frost993** [Shadows-of-Fire/Apotheosis#378]
Someone got hit by a boss and caused the server to crash. Happened twice, only happened with a specific spawner, unsure why. 

Also retested with a different boss mob spawners, didn't cause a crash.

Crash 1
Log
https://pastebin.com/GrAA5PkW
CrashReport
https://pastebin.com/qrfmJhWG

Crash 2
Log
https://pastebin.com/G3iJs43n
CrashReport
https://pastebin.com/6PWzXgik

I have no other info other than the logs. Dunno if they can help or solve the bug.

**Comment by Shadows-of-Fire** [comment]
crash is coming out of dcintegration, looks like nothing to do with apoth
