### ISSUE TITLE
Live Mending + tombstone soulbound not compatible

### ISSUE THREAD

**Issue by Flemmli97** [Shadows-of-Fire/Apotheosis#38]
idk if this is intended or not but live mending and the soulbound enchant from corail tombstone mod it not compatible

Apotheosis-1.12.2-1.9.2
tombstone-3.3.4-1.12

**Comment by Shadows-of-Fire** [comment]
wat

**Comment by Flemmli97** [comment]
Corail tombstone [https://minecraft.curseforge.com/projects/corail-tombstone?gameCategorySlug=mc-mods&projectID=243707](https://minecraft.curseforge.com/projects/corail-tombstone?gameCategorySlug=mc-mods&projectID=243707) adds a soulbound enchant which seems to be incompatible with the live mending enchant from apotheosis. i cant put both enchants on the same item. since i dont see why this would be the case i am posting this as an issue cause i dont know if this is intended or not.

**Comment by Shadows-of-Fire** [comment]
Corail tombstone is not open source, so I don't care about compatibility with it.

Nothing from my end could prevent the two from being applied together (life mending doesn't have a custom `isCompatibleWith` function), so it's likely their fault anyway.
