### ISSUE TITLE
feature request: a way to change tools/weapons used by Apotheosis' bosses

### ISSUE THREAD

**Issue by jecowa** [Shadows-of-Fire/Apotheosis#381]
I want to make the bosses use Silent Gear tools/weapons instead of vanilla tools/weapons in a mod pack that has vanilla tools disabled.

Or I have some commands to create al the Silent Gear tools/weapons with proper NBT tags, if you're interested in adding support for Silent Gear.

**Comment by Shadows-of-Fire** [comment]
The entries for boss items are datapack loaded (see data/boss_gear).  This may be annoying to do with stuff that is dynamic like sgear... but it shouldn't be impossible

**Comment by jecowa** [comment]
here's how to add nbt data to Apotheosis bosses for anyone else wanting this:


        {
          "weight": 4,
          "stack": {
            "item": "silentgear:machete",
            "nbt": "{SGear_UUID: [-1094674196, 871711235, -2088102740, -851605093], SGear_Data: {Construction: {Parts: [{Item: {id: \"silentgear:machete_blade\", Count: 1, tag: {Materials: [{Item: {id: \"silentgear:azure_silver_ingot\", Count: 1}, ID: \"silentgear:azure_silver\"}, {Item: {id: \"silentgear:azure_electrum_ingot\", Count: 1}, ID: \"silentgear:azure_electrum\"}, {Item: {id: \"silentgear:crimson_steel_ingot\", Count: 1}, ID: \"silentgear:crimson_steel\"}]}}, ID: \"silentgear:machete_blade\"}, {Item: {id: \"silentgear:rod\", Count: 1, tag: {CraftedCount: 4, Materials: [{Item: {id: \"silentgear:netherwood_planks\", Count: 1}, ID: \"silentgear:netherwood\", Count: 2}]}}, ID: \"silentgear:rod\"}]}, Properties: {ModVersion: \"2.6.24\", Stats: {\"silentgear:enchantability\": 27.651093, \"silentgear:harvest_speed\": 22.34991, \"silentgear:harvest_level\": 5.0, \"silentgear:durability\": 273.1441, \"silentgear:melee_damage\": 10.864668, \"silentgear:magic_damage\": 8.036673, \"silentgear:rarity\": 53.49571, \"silentgear:attack_speed\": -2.622654, \"silentgear:repair_efficiency\": 1.0}, LockStats: 0, Traits: [{Level: 4, Name: \"silentgear:malleable\"}, {Level: 1, Name: \"silentgear:hard\"}, {Level: 2, Name: \"silentgear:flexible\"}]}, Rendering: {ModelKey: \"machete:machete_blade{azure_silver,azure_electrum,crimson_steel},rod{netherwood,netherwood},\"}}}"
          }

source: https://www.reddit.com/r/ModdedMinecraft/comments/neulr2/could_someone_help_show_me_how_to_add_nbt_data_to/gyip4h4/
