### ISSUE TITLE
Blue particle effects show up below feet.

### ISSUE THREAD

**Issue by MarkFSchneider** [Shadows-of-Fire/Apotheosis#382]
These particles show up at my feet, even after disabling all the other mods in my modpack, after the most recent update of apotheosis. 

Moving back to version Apotheosis-1.16.4-4.5.2.jar fixed the issue

![2021-05-17_21 04 14](https://user-images.githubusercontent.com/43594328/118592709-3f7d1100-b75b-11eb-9eb0-17fdf41a39be.png)

**Comment by Shadows-of-Fire** [comment]
That's coming out of apoth?  I've been trying to track that down all night - I thought it was in placebo

**Comment by MarkFSchneider** [comment]
I used the disable mod feature on curseforge to hunt it down, which may have some influence on how libraries are taken from other .jar files. 

Disabling Apotheosis, but not placebo gets rid of the particle effects. It might be some element of shared code in placebo, but whatever it is its only being accessed by the newer version of Apotheosis in my pack.
