### ISSUE TITLE
[suggestion or bug?] Retrieving 1 less affix on anvil?

### ISSUE THREAD

**Issue by winsrp** [Shadows-of-Fire/Apotheosis#387]
So the following behavior is in place

Rare item on anvil with Rare affix tome, only retrieves 1 affix instead of 2.
Epic item on anvil with Epic affix tome, only retrieves 2 affixes instead of 3.
Mythic item on anvil with Mythic affix tome, only retrieves 2 affixes instead of 3.

Is this what is supposed to be?

Preferred option, to be consistent and have them retrieve their supposed max amount of affixes, 

Second Option: Make a slight modification that using an Epic affix tome with a rare item actually takes the 2 affixes, and using a Mythic tome on an epic item takes 3 affixes, and using an ancient tome takes 3 affixes from mythic. So in short, higher level book takes all affixes from lower level item.

Common and Uncommon does work as expected. Tx

**Comment by Shadows-of-Fire** [comment]
Tomes simply remove half of the affixes rounded up.  2/2 = 1, 3/2 = 1.5 = rounded up to 2

**Comment by winsrp** [comment]
wouldn't it be better if it gets all of them instead of half? if it gets only half and there is no way to create them other than loot then, you stop merging and mixing since they get lost, waiting for that good item to put all of them, so you stop using them for most of the game. just a thought.
