### ISSUE TITLE
Affix loot table entries do not check champion conditions

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#388]
I was trying to get tier 3 [champions](https://www.curseforge.com/minecraft/mc-mods/champions) to drop a random affix item. There is a condition set for the champion, but the entry does not seem to be aware of this, and added an affix drop to every entity instead. Is this a vanilla limitation?

**Comment by Shadows-of-Fire** [comment]
No this is actually just me discarding the conditions too early, oops
