### ISSUE TITLE
Gained permanent buffs

### ISSUE THREAD

**Issue by jaz000** [Shadows-of-Fire/Apotheosis#39]
![Capture](https://user-images.githubusercontent.com/8948636/56695381-d8f2a980-66e0-11e9-98ea-db1f3fb80078.PNG)
A couple of people on our server have, after a particularly energetic fight with mobs, ended up with a bunch of permanent buffs.

Water Breathing
Speed II
Strength
Resistance II
Regeneration
Fire Resistance

All for a time period of **:**  i.e. permanently - we had to remove the buff with an op command to get rid of them.

I think this combination of potion effects is grouped together in this mod (under BRUTAL_POTIONS) but if that is part of the cause of this, I don't know if any other mod is then somehow transferring them to the player.  (We have another ~200 mods in addition to this one in the mix!).

Is anyone able to help piece together how this might have happened?

**Comment by Shadows-of-Fire** [comment]
Those do look exactly like the brutal spawner potions... Not sure how they would be applied or transferred to a player though.

Is there anything you've ever heard of that could move potion effects?  I've never heard of anything doing that.

**Comment by CritFlaw** [comment]
Out of curiosity @jaz000 can you upload your modlist? A player on my pack is reporting an identical issue and I want to see what mods we have in common.

**Comment by jaz000** [comment]
Here's the modlist
https://pastebin.com/n1keDPHS
How are the brutal spawner potions used? Is that a package of buffs applied to a boss mob? If so it does sound like I'm looking for something that steals another entities potion effects ...

**Comment by Shadows-of-Fire** [comment]
It's a set of buffs written as spawn data (in nbt) for brutal spawners that spawn in caves or dungeons.  It will only apply to spawned monsters, and i'm not sure what can transfer potion effects.

**Comment by CritFlaw** [comment]
Can you upload the modlist.html instead? Easier to compare lists.

**Comment by jaz000** [comment]
I'm not sure where modlist.html comes from? (the pack is build in MultiMC).

I have been marking spawner locations in our playthrough so there is a good chance I can find the brutal one again to investigate when I am not running for my life :-)

**Comment by quat1024** [comment]
This is probably a creeper with the brutal effects applied exploding and creating an area effect cloud which transfers the potion effects to anyone who walks inside it

**Comment by Shadows-of-Fire** [comment]
That's a thing?  Why is that a thing?

May need to blacklist creepers from the potion effects.  Honestly they should probably safeguard against infinite length effects themselves, but I guess they aren't doing that.

**Comment by quat1024** [comment]
Yyyyyup Botania had the same problem with the Loonium a while back
