### ISSUE TITLE
According to Heapdump taken with VisualVM, Apotheosis causes some form of Softlock on the server thread

### ISSUE THREAD

**Issue by rinOfTheStars** [Shadows-of-Fire/Apotheosis#395]
Mod version: 4.6.1
Forge version: 35.1.37
Minecraft version: 1.16.4
Other things of note: modpack is [Permafrost](https://www.curseforge.com/minecraft/modpacks/permafrost-eots/files/3335729) which contains Performant version 3.56m

It appears that on occasion, Apotheosis causes some form of softlock when attempting to spawn a boss mob via the deadly module. This softlock **creates no logs** and so had to be caught using the [VirualVM](https://visualvm.github.io/documentation.html) debugging tool. The heapdump pictured and attached to this issue was generated using said tool.

![Screen Shot 2021-06-02 at 11 16 22 PM](https://user-images.githubusercontent.com/24525012/120581341-a99ee280-c3f8-11eb-9c49-f6ff3901d1a4.png)

Zip file containing the full heap is here (google docs):
https://drive.google.com/file/d/1cdppxcJhqtO3ILH3lJ8Qu5SHPHDCKH5B/view?usp=sharing

_Note that the uncompressed version is nearly 3gb large!_

**Comment by rinOfTheStars** [comment]
Replicated by spam-spawning boss mobs with the Boss Spawner item
relevant heap stack data here: 
![Screen Shot 2021-06-02 at 11 35 04 PM](https://user-images.githubusercontent.com/24525012/120583200-c1c43100-c3fb-11eb-8281-de7127af1228.png)
According to another person playing the pack, [Blame](https://www.curseforge.com/minecraft/mc-mods/blame) causes this bug to throw an error instead of softlocking.

**Comment by rinOfTheStars** [comment]
Another update! Blame gets us an actual error to throw, but still locks up the server thread.
https://paste.ee/p/iiL28
Relevant heap thread thingie (again):
![Screen Shot 2021-06-02 at 11 46 39 PM](https://user-images.githubusercontent.com/24525012/120583823-e53bab80-c3fc-11eb-95d5-648e56667da2.png)

Going to see if running a JVM higher than 8 makes any change next.

**Comment by Shadows-of-Fire** [comment]
Do you happen to have custom boss files loaded in via datapack?  That code path from the actual crash points towards this line of code `		entity.getAttribute(this.attribute).applyPersistentModifier(modif);
` which can only NPE if entity is null.  Only way that's null is if the MobEntity returned by the EntityType held in a BossItem creates nothing at this line `MobEntity entity = (MobEntity) this.entity.create(world.getWorld());`

**Comment by rinOfTheStars** [comment]
Sure looks like it.
There's probably something wrong with them, then? Ill post the global datapack folder in a zip real quick if you want to check it over for reference.

**Comment by rinOfTheStars** [comment]
Here it is: 
[apo-permafrost-stuff.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/6588844/apo-permafrost-stuff.zip)

Also, should I make an issue pertaining to having a better failure state for broken .json?

**Comment by Shadows-of-Fire** [comment]
You've probably picked a modded entity that is returning null to EntityType#create, for whatever reason.  No clue why an entity type would do that, but it's not actually a failure in the json, rather in the selected entity type.

**Comment by rinOfTheStars** [comment]
I think I know why: the game gets stuck if it tries to spawn a boss mob with no item slots; as it can't put an item in any of the slots. This seems to be what is happening each time this sort of error occurs so far?

**Comment by Shadows-of-Fire** [comment]
No, that would have nothing to do with it (though that would also be unsupported behavior, you cannot create a boss that is not a MobEntity, which guarantees the slot exists).  You are selecting an entity for boss-creation that is returning null when an attempt to actually "create" that entity occurs.

**Comment by rinOfTheStars** [comment]
alright, time to figure out which one it is ig

**Comment by rinOfTheStars** [comment]
That's not what's causing the softlock in this case?
As shown here, the game is trying to spawn a vindicator and getting stuck, _despite having previously spawned such a mob?_

![Screen Shot 2021-06-03 at 1 17 37 AM](https://user-images.githubusercontent.com/24525012/120591077-8c264480-c409-11eb-8b26-16da08556940.png)

going to dig though the heap stack trace some more for this specific softlock

**Comment by rinOfTheStars** [comment]
I gtg to bed might do some more digging in the morning.
it's for sure some sort of bad json, but idk what since i didnt author the files

**Comment by rinOfTheStars** [comment]
Going to close this for now, suspect its bad json of some sort.
likely culprits are mobs that aren't valid (the error) and bad boss items of some sort (softlock)
