### ISSUE TITLE
[Feature Addition Request] Better, more verbose error handling for Deadly Module functions defined by .json datapack(s)

### ISSUE THREAD

**Issue by rinOfTheStars** [Shadows-of-Fire/Apotheosis#396]
Currently, the Deadly module has a tendency to soft-lock the Server Thread when an error occurs when a call based on .json which the validator considers valid, but still runs into an issue within the methods called in some capacity. I have figured this out though the use of external debug tools such as VirtualVM (see closed issue https://github.com/Shadows-of-Fire/Apotheosis/issues/395)  and I am currently [working on a Fork](https://github.com/cocona20xx/Apotheosis) on which I hope to implement better failure states (either a proper crash of the server thread when throwing an exception if absolutely necessary, or handling the exception without causing a crash, likely by spawning the mob without any Deadly Module functionality and printing the thrown exception to the log) than the current soft-lock behavior.

I'll update with more specific details as I work on said fork, and hope to make some form of pull request in the future.

**Comment by Shadows-of-Fire** [comment]
Based on #395 any errors being thrown would just result in the same jvm state.
The other issue with this is there is no validation to be done, at the time of json parsing there is no world or other context-relevant information required to test if these files are not going to crash.
