### ISSUE TITLE
Mending does not work(enchant)

### ISSUE THREAD

**Issue by Dontas12** [Shadows-of-Fire/Apotheosis#397]
After adding the mod, the Mending on any item stopped working.

**Comment by Shadows-of-Fire** [comment]
what

**Comment by Dontas12** [comment]
In this video I show that only life-mending works. Mending on weapons does not work, but works on Elytra.
https://drive.google.com/file/d/1EB5HmgZpwg713-NZ2JSVLu9qHjDkGATg/view?usp=sharing

**Comment by Shadows-of-Fire** [comment]
Apoth doesnt make any changes to mending, nor does mending even function any differently on different kinds of items (so if it's working on an elytra, it's working)

**Comment by Dontas12** [comment]
Sorry. Indeed, this mod did not affect the repair.
