### ISSUE TITLE
Botania Mana Enchanter Doesn't Use Apotheosis Tomes As Valid Enchanting Book

### ISSUE THREAD

**Issue by Numorphan** [Shadows-of-Fire/Apotheosis#40]
# Version Information
Forge version:  2836
Botania version:  r1.10-361
Apotheosis version: 1.9.3

# Further Information
Steps to reproduce:

1. Place any number of apotheosis tomes (of the right type) in the mana enchanter.
2. Activate the mana enchanter.
3. Nothing happens.
4. Add a regular book.
5. Activate it.
6. The regular book's first enchant will be applied, with all the tome's enchants ignored.

What I expected to happen:

The mana enchanter should treat the tome as a regular enchanted book.

What happened instead:

When using an Apotheosis tome (of Helmets, Weapons, etc) in the Botania mana enchanter, the mana enchanter will ignore the tome and not apply the enchant to the central item.

(https://github.com/Vazkii/Botania/issues/2896)

**Comment by Shadows-of-Fire** [comment]
I'm not sure if there's anything I can do about this actually...
