### ISSUE TITLE
Issue with combining books in anvil 

### ISSUE THREAD

**Issue by toffi3** [Shadows-of-Fire/Apotheosis#400]
The issue is you can't go through max level when combining those enchants in anvil. As you can see in this video https://www.youtube.com/watch?v=zEP-AgBelJc my max level of protection is 5 but you can't combine 2 prot 4 books in anvil. You get prot 4 from it. I don't is it issue in your mod but i'm writing it here since your mod allows to have more enchantments levels. 
Have a nice day!

**Comment by Shadows-of-Fire** [comment]
This is a mod conflict (dunno what with, plenty of mods can break it very easily)
