### ISSUE TITLE
Apotheosis crash when creating a superflat world

### ISSUE THREAD

**Issue by cestofmir** [Shadows-of-Fire/Apotheosis#401]
In my modpack, my game crashes whenever I attempt to create a superflat world. It seems to suspect Apotheosis.

Crashlog: https://paste.dimdev.org/rumihigayu.mccrash
Log: https://drive.google.com/file/d/1DHdpOHT2kX07V6z_RJPK3L3V_GYxkZqe/view?usp=sharing

**Comment by Shadows-of-Fire** [comment]
mc 1.12 is not supported
