### ISSUE TITLE
[Affix system] Getting an armor piece to 6 armor toughness resets it to 3 and no higher

### ISSUE THREAD

**Issue by Tiln1** [Shadows-of-Fire/Apotheosis#403]
![at1](https://user-images.githubusercontent.com/25667497/121926554-503d8a00-ccfb-11eb-9f27-805c1f2756e2.PNG)
![at2](https://user-images.githubusercontent.com/25667497/121926570-53387a80-ccfb-11eb-8618-c74472388941.PNG)
This also happened to a helmet, and a pair of pants I'm improving is having it happen for armor at 12
I think it has something to do with it not liking both +3 Armor Toughness and +3 Armor Toughness on the same item.

Version is 1.16.4-4.6.0

**Comment by Shadows-of-Fire** [comment]
That is more likely an issue with the tooltip mod, as the attribute is working as intended (the max value is 3 for the affix)

**Comment by Tiln1** [comment]
Is the tooltip mod also responsible for the Armor and Armor Toughness bars above the health and food bars? I have a helmet where I went to 6 AT (3 AT + 3 AT) and it says 3 in the tooltip, and only gives me 3(1.5) in the bar. In contrast, I have a helmet with 5.98 AT in the tooltip and it gives me 6(3) in the bar.

**Comment by Shadows-of-Fire** [comment]
Turns out the way I was sorting attribute modifiers to ensure consistent tooltips was voiding modifiers with the same type and magnitude.  Fixed
