### ISSUE TITLE
Limit in Item stats by adding Affixes

### ISSUE THREAD

**Issue by toffi3** [Shadows-of-Fire/Apotheosis#408]
I've seen an issue that +8 Max health is probably a limit because when i tried to add +4,11 max health to my leggings it haven't increased. What's more, Armor Toughness after combining is REDUCED to 3 from 5,42 even if the book says that it will ADD 2,16 I think the best would be just removing the limit or giving players opportunity to set the limit in the config of the mod. Here's footage of the issue.
https://user-images.githubusercontent.com/84127414/123526639-8d315580-d6d9-11eb-81e8-d024be9dd99c.mp4

**Comment by Shadows-of-Fire** [comment]
Max health is capped at 8, working as intended, the armor toughness thing is a separate special issue, see #403
