### ISSUE TITLE
 Suggestion: Crafting low-tier affixes into higher-tier ones

### ISSUE THREAD

**Issue by AedemanZ** [Shadows-of-Fire/Apotheosis#416]
Hello Shadows-of-Fire,

I noticed that there is an option to convert higher rarity affix shards into lower rarity ones. I was wondering if you've ever considered adding a feature to convert lower tier affixes into higher tier ones? It would definitely need to be much more demanding than when downgrading, but I think it could give lower rarity items (or to be more precise, affixes) more use. 

On another note, I am really enjoying your mod! It adds many new and entertaining things to the mix. Although I am using all the modules, I especially love the Deadly one. I have personally made a small modpack based on Apotheosis and other mods like Project MMO and The Gems Project, and it is a blast to play.

**Comment by Darkmega18** [comment]
you could probably achieve that with some crafting recipe editing shenanigans via datapack or crafttweaker I would think? so you can salvage lower shards into higher shards in their empty state. 

but I guess you probably mean combining like shards as if they were enchantments, right? if so, I second this suggestion.

**Comment by AedemanZ** [comment]
> you could probably achieve that with some crafting recipe editing shenanigans via datapack or crafttweaker I would think? so you can salvage lower shards into higher shards in their empty state.
> 
> but I guess you probably mean combining like shards as if they were enchantments, right? if so, I second this suggestion.

Thanks for the comment! I wasn't necessarily referring to combining them like enchantments, but that could definitely be an option. Given the extra features related to spawners and enchantments that boost experience and make it easy to run exp farms, I do think that experience shouldn't be the only requirement to get higher grade shards. 

Also, thanks for the suggestion, I might try creating a crafting recipe for it on my own!

**Comment by Shadows-of-Fire** [comment]
This is not realistically something I want to support by default - the management of affixes is meant to be difficult (and even more so for the higher rarities).

**Comment by Darkmega18** [comment]
WELP, datapack it is... ish.
