### ISSUE TITLE
[Feature Request] allow configuring what affixes can go on which equipment type

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#417]
There are some legitimate use cases for this, such as boots that increase move speed, and some more whimsical configurations like shields that boost draw speed or helmets that increase crit rate (by having an attached scope or something to help with aiming, I presume), but it can help to stir up the armor affix meta a bit, since right now it's just piling on protection.

**Comment by Shadows-of-Fire** [comment]
Technically speaking it would be neat.  Realistically speaking it would need another total rewrite of the affix system for this to be implemented.  I'll stick this here with an enhancement tag, but it likely will not come until the system is redone again.

**Comment by Shadows-of-Fire** [comment]
This is possible as of the rewrite
