### ISSUE TITLE
Cannot apply affixes to Sgear Machete

### ISSUE THREAD

**Issue by TyoAtrosa** [Shadows-of-Fire/Apotheosis#418]
using a Tektite Machete (Sgear+SGems), trying to apply an Affix Tome with the Frostborne and Blazing affixes, will not allow it.

Can Apply to a regular Sgear Sword, just not the Machete or Katana. would it be possible to make the melee weapon affixes work across weapon types?

**Comment by Shadows-of-Fire** [comment]
The classifier for "what is a sword" is already the single most generic check it can possibly be (if the item provides attack damage while in the main hand, and doesn't fall into any other category).  You should probably use the type override config to force the game to recognize them as what you want them to be.
