### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by goopsie** [Shadows-of-Fire/Apotheosis#42]
>
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/3140511/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/3140512/debug.log)

Please tell me if you need anything else

**Comment by Shadows-of-Fire** [comment]
I fail to see how this is an apotheosis problem.  This looks like a corrupted install.

**Comment by goopsie** [comment]
ah sorry man, it was a problem with bewitchment, not this mod. Removed bewitchment and it works fine
