### ISSUE TITLE
Magic Arrow affix causes bows to deal 0.5 damage

### ISSUE THREAD

**Issue by Banananass** [Shadows-of-Fire/Apotheosis#422]
If you have a vanilla bow in version 4.5.3 of apotheosis which has the affix "your arrows deal magic damage" the bow does basically no damage to players (even without armor and/or effects) or mobs. This makes this affix an active downside, even though it is quite rare with a default weight of 1.

**Comment by Shadows-of-Fire** [comment]
I cannot reproduce this with just apotheosis involved.  Arrows deal standard (and increased, due to the magic damage armor pierce) damage to both mobs (skeletons/creepers/zombies) and players (self-inflicted)

**Comment by Banananass** [comment]
Hmm I guess it has to be an incompatibility with another mod then, the only mod in the modpack that changes the vanilla damage system in a way is attributefix but that shouldnt mess with unarmored players. I will try to find out what causes this and reply as soon as I find the mod that messes things up
