### ISSUE TITLE
Suggestion: Add blacklist to Capturing enchant

### ISSUE THREAD

**Issue by landretk** [Shadows-of-Fire/Apotheosis#426]
Some mobs, such as Atum Pharohs, have spawn eggs, but should not be dropped by capturing enchant. Some mods may leave in spawn eggs, but they aren't meant to be obtainable.

**Comment by MuteTiefling** [comment]
Seconding this. It's weird to get a spawn egg for a mob that can't go in a spawner due to the blacklist. Capturing should probably simply respect the spawner blacklist.
