### ISSUE TITLE
Tetra Enchantment Compat not working correctly

### ISSUE THREAD

**Issue by DizzyPrime** [Shadows-of-Fire/Apotheosis#427]
Custom tools from the Tetra mod under the tetra:modular_double tag, such as Pickaxes, Axes, or other double-headed tools are only able to receive Efficiency or Unbreaking for tool related enchantments and can receive offensive enchantments such as sharpness and fire-aspect, but cannot get any enchantments such as silk touch or fortune or other custom enchantments for tools. Before installation of Apotheosis they were able to receive the proper enchantments.

**Comment by Shadows-of-Fire** [comment]
That's something you would need to bring up with tetra, apoth does not change what things can receive what enchantments
