### ISSUE TITLE
[Feature Request] More Datapack support

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#428]
I was just poking around trying to change the crafting recipes for the book shelves and noticed they aren't data pack compatible. Would it be possible to add support for your crafting recipes?

**Comment by Shadows-of-Fire** [comment]
All recipes from apoth/anything that I have is datapack overridable, but the default files are not jsons.

**Comment by MuteTiefling** [comment]
Hrm. Alright then, thanks for the prompt response. I'll take another hack at it, but so far I've been unable to override the hellshelf recipe. I'm just getting another recipe with the same ID.

**Comment by Shadows-of-Fire** [comment]
Well that would be impossible - two recipes cannot share the same ID (they're stored in a Map<ResourceLocation,IRecipe<?>>) - Even if two existed at the same ID, one would kick the other out.

The code recipes don't even attempt to add themselves if a recipe is already present with the same ID https://github.com/Shadows-of-Fire/Placebo/blob/1.16/src/main/java/shadows/placebo/recipe/RecipeHelper.java#L111

**Comment by MuteTiefling** [comment]
Yeah, it's being weird. Probably need a restart. Thanks again!

**Comment by MuteTiefling** [comment]
Well, I've tried just a straight datapack that should result in an ID override and it's not doing anything. Your recipe remains present and registered despite mine being there from startup. 

Not sure what else to do here. I have to say I've modified thousands of recipes to date and this is one of two mods that have given me any difficulty.

**Comment by Shadows-of-Fire** [comment]
Pop open an issue on placebo then - that's the controller for the recipe logic, not entirely sure how both recipes could be there with the same ID but i'll look into it
