### ISSUE TITLE
crash by TileEntityMobSpawner missing

### ISSUE THREAD

**Issue by Byomakuta** [Shadows-of-Fire/Apotheosis#43]
[crash_log.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/3144017/crash_log.txt)

this is happening only when applying apotheosis to the pack

**Comment by Shadows-of-Fire** [comment]
This is caused (I'm fairly certain, but it could be another mod) by an incompatibility with Better Nether.  You have three options to get around it for now:
A) Remove Better Nether
B) Remove Apotheosis
C) Disable Apotheosis' Spawner Module, which will stop the replacement of spawners.

See https://github.com/paulevsGitch/BetterNether/issues/9
