### ISSUE TITLE
Enigmatica 6 Ignore Nearby Players

### ISSUE THREAD

**Issue by kienee** [Shadows-of-Fire/Apotheosis#430]
Hey Guys,

i am playing Enigmatica 6 (Singleplayer) atm, and i tried out the Apotheosis spawner. I pretty much pumped it up with Sugar / Fermented Spider Eye / Clock / Ghast Tears / Nether Star / Dragon Egg. The Dragon Egg should make the Spawner ignore nearby Player. But as soon as i get to far away from the Spawner its stopping completely.

Is there any way to fix it? Or do i have to switch back to the normal Mob Spawners :/

**Comment by Shadows-of-Fire** [comment]
The nether star modifier is the one that applies "Ignores nearby players"
I have personally verified that it works in my currently installed enigmatica 6 instance (V 0.5.6)
