### ISSUE TITLE
Miner's Fervor calculation doesn't include sea level

### ISSUE THREAD

**Issue by DeadBushSanpai** [Shadows-of-Fire/Apotheosis#432]
In [Enchantment Descriptions for Apotheosis](https://gist.github.com/Shadows-of-Fire/adab31e668b4fe71578bae2d5f87ee2b#miners-fervor), you said Miner's Fervor will effect `1 + level * level * ((sea level - y level) / sea level)` for underwater and  `1 + level * level * ((sea level - y level) / (sea level * 3))` for overwater.
But it just [calculate](https://github.com/Shadows-of-Fire/Apotheosis/blob/ec714945d8016a90513b91f2a7c67cddeb63f115/src/main/java/shadows/apotheosis/ench/EnchModuleEvents.java#L164-L169) base on the EnchantmentsLevel(depth) and OriginalSpeed.

**Comment by Shadows-of-Fire** [comment]
That document is not a reliable piece of information anymore (and hasn't been for at least a year, at this point)
