### ISSUE TITLE
Affix harvest error

### ISSUE THREAD

**Issue by RageQuitAmy** [Shadows-of-Fire/Apotheosis#433]
[crash-2021-08-12_23.57.23-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/6979159/crash-2021-08-12_23.57.23-server.txt)
When using a tool from another mod, my single player world crashes and this is the crash report. I tested the other mod by itself and it worked fine.  I am sorry if this is not enough information I have not done anything like this before.

**Comment by Shadows-of-Fire** [comment]
This crash is being caused by `HarvestCheck#getPlayer` returning null, which is invalid behavior (a harvestcheck cannot be done without a player).  The "broken" event is being sent out by the "Pattysmorestuff" mod so you'll have to bring it up with them.

**Comment by RageQuitAmy** [comment]
Okay thank you, sorry for wasting your time.
