### ISSUE TITLE
Deadly boss Datapacking suggestions/requests

### ISSUE THREAD

**Issue by Darkmega18** [Shadows-of-Fire/Apotheosis#434]
1: Have a field that the player can put in a string to put nbt onto the spawning boss when it is spawned like when commands can be run to have nbt on a mob. Override of stack any attributes that happen in the afterwards attributes section.

2: Ability to set potions effects ambient or not when applied.

3: Riding mob with a direct selection of another boss entry name to make a "mounted" boss? Although it could be technically achieved with the above nbt in the riding section I guess?

4: **Ability to set any item to be ignored with a field that defaults to false** when it comes to selecting one of the items from the inslot table to make into the affixed item. So one can use say offhand arrows for skeletons to allow skeleton bosses variable arrows to fire out or have visible trinkets in their hand without accidentally applying affixes to arrows or other types of gear that shouldn't be allowed to and causing either errors or game explosions and also wasting the boss's loot potential on something that didn't work.

5. Datapacking wiki page so (theoretically) less questions from pack devs trying to do their black magic?

**Comment by Shadows-of-Fire** [comment]
1: Added via `custom_nbt` subkey.
2: Implemented via `ambient` and `visible` subkeys.
3: Probably gonna let that one sit for now and deal with it later.
4: That's actually already in there - it's automatic.  If the random selector picks an itemstack that is either empty, or unable to receive affixes, it will be rerolled.

**Comment by Darkmega18** [comment]
Ah, well ok then. :D

**Comment by Shadows-of-Fire** [comment]
I think this satisfies (5) https://gist.github.com/Shadows-of-Fire/937a6f2403928dea773e4de1081e401e
