### ISSUE TITLE
[1.16.5] server crash when opening chest on 4.7.0 - not reproducible

### ISSUE THREAD

**Issue by dskw** [Shadows-of-Fire/Apotheosis#436]
Hello,

I have encountered a crash on a private pack which I have just updated to Aphotheosis 1.16.5-4.7.0
https://pastebin.com/TgxH4dfX

The player reported it happened when opening a chest full of farm items, but I don't see a direct connection to it.
After an automatic restart of the server the issue did not occur again.

The player does not have anything of the mod on himself, so maybe it was caused by a mob in the underground that did not respawn after the reboot.

So no reproduction, sorry :(

**Comment by deftesthawk** [comment]
I'm also crashing on version 4.7.0 when creating a new world, rolling it back to the previous version fixes it
