### ISSUE TITLE
RandomSpawnerManager server crash, using latest version

### ISSUE THREAD

**Issue by ModernGamingWorld** [Shadows-of-Fire/Apotheosis#437]
[crash-2021-08-24_07.24.03-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7040348/crash-2021-08-24_07.24.03-server.txt)

**Comment by luffykick** [comment]
same thing I came to report.
Apotheosis-1.16.5-4.7.0.jar

**Comment by ModernGamingWorld** [comment]
Shadows pretty good at fixing this type of stuff ASAP

**Comment by skulls-dot-codes** [comment]
[crash-2021-08-24_18.02.44-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7042567/crash-2021-08-24_18.02.44-server.txt)

**Comment by ado1928** [comment]
+1
