### ISSUE TITLE
Crash when spawning Deadly Surface boss 

### ISSUE THREAD

**Issue by CLittleLunaC** [Shadows-of-Fire/Apotheosis#440]
[crash-2021-08-25_14.31.57-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7050036/crash-2021-08-25_14.31.57-server.txt)
Hi I keep getting a crash every time a deadly boss tries to spawn, I currently disabled the spawning for the time being so I can play without a random crash after a while of playing. 

I am playin on Forge 1.16.5 with Apotheosis v.4.7.0 and a melody of other mods though none (that I know of) have conflicted with it in the past.

**Comment by Shadows-of-Fire** [comment]
update
