### ISSUE TITLE
Crash with the Fletching Table, because of Apotheosis.

### ISSUE THREAD

**Issue by GreninjaSan** [Shadows-of-Fire/Apotheosis#441]
On the last version, when we open the fletching table, the client suddendly crashes.

Here is the changelog : https://mclogs.minestrator.com/5aBqRcz

**Comment by Shadows-of-Fire** [comment]
Does 1.16.5 even support java 16?

**Comment by GreninjaSan** [comment]
If I remember well, I think it does yea

**Comment by Opity69** [comment]
Have  similar   issue  without potion, clicking on fletching table crashes game
https://pastebin.pl/view/852a5a14

**Comment by ghost** [comment]
Also can confirm, newest version 4.7.1 causes the below crash on client-side every time anyone attempts to use a fletching table. 

Error: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access method net.minecraft.block.CraftingTableBlock.func_220270_a(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;ILnet/minecraft/entity/player/PlayerInventory;Lnet/minecraft/entity/player/PlayerEntity;)Lnet/minecraft/inventory/container/Container; from class shadows.apotheosis.village.fletching.ApothFletchingBlock

Reverting to the previous 4.6.1 version -- where this still functions until a fix is found.
