### ISSUE TITLE
Persistent Crash during loading with Apotheosis-1.16.5-4.7.1

### ISSUE THREAD

**Issue by optmisticnihilist** [Shadows-of-Fire/Apotheosis#443]
Forge 36.2.2
Minecraft 1.16.5
Custom modpack in progress.

Reason for posting here:
Crash report refers to Apotheosis code, and issue was resolved using Apotheosis-1.16.4-4.6.1 instead.

To be fair could be something else interfering with Apotheosis.

Crash log:
[crash-2021-08-25_07.27.29-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7070781/crash-2021-08-25_07.27.29-server.txt)

**Comment by Shadows-of-Fire** [comment]
update

**Comment by optmisticnihilist** [comment]
Updated and working in modpack, thank you.
