### ISSUE TITLE
[Crash] Fletching Table Crashes On Use

### ISSUE THREAD

**Issue by vivvyinks** [Shadows-of-Fire/Apotheosis#444]
[crash-2021-08-28_20.03.56-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7071839/crash-2021-08-28_20.03.56-client.txt)

Tested in both singleplayer and multiplayer, happens no matter what.

**Comment by LordGuppy** [comment]
Seconded

https://pastebin.com/CyzBFWHr

**Comment by Shadows-of-Fire** [comment]
#441
