### ISSUE TITLE
Incompatible with Scaling Health

### ISSUE THREAD

**Issue by Numilani** [Shadows-of-Fire/Apotheosis#447]
This is likely a duplicate of #446 but I have actual details to provide:

## Description

When running Apotheosis (version 1.16.5-4.7.1) and Scaling Health (version 1.16.5-4.1.5+11), connecting to a server gives the following error message:

`Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: Index: 25, Size: 5`

This error does not occur when playing singleplayer. No errors are logged client- or server-side.

**Comment by Shadows-of-Fire** [comment]
I feel like this is something that has to be resolved on scaling health's side - I don't modify the way any attributes work or even touch any netcode.

Hell, the only thing apoth does with attributes is apply modifiers to items and entities (the same way you can do it with vanilla nbt editing).

**Comment by Numilani** [comment]
Understandable. Linking the same open issue on the Scaling health repo for visibility, just in case.

https://github.com/SilentChaos512/ScalingHealth/issues/359

**Comment by Shadows-of-Fire** [comment]
Just going to close this, Scaling Health appears to be dead
