### ISSUE TITLE
Deadly Invis bug?

### ISSUE THREAD

**Issue by Zaldor12** [Shadows-of-Fire/Apotheosis#449]
So I've tried creating a modpack and while testing it i noticed there were invisible mobs that i couldn't hit or see but could hear them, after looking through my mods i found that apotheosis was the only capable of generating mobs so i figured id see what i could do to fix this issue, i do apologize if it something super simple i am very new to mods and what they can and cant do

**Comment by Shadows-of-Fire** [comment]
This request does not have enough information to be addressed (mc ver, apoth ver, forge ver)
