### ISSUE TITLE
Can't merge different items in 1.10.0?

### ISSUE THREAD

**Issue by Xetaxheb** [Shadows-of-Fire/Apotheosis#45]
Don't know if it's intentional or was a patched bug, but in 1.9.3 you could anvil say, diamond helmet+prot 4 with a diamond leggings+unbreaking 3 to get a diamond helmet+prot4+unbreaking 3.

Was this removed?

**Comment by Xetaxheb** [comment]
Addendum: If it was intentionally removed, it would be nice to have this as an optional feature :+1:

**Comment by Shadows-of-Fire** [comment]
Yeah there was a bug in the Tome enchanting handler that allowed for merging of anything.  I suppose I can put something back in it's place, but it will likely be more expensive than it was.

**Comment by Shadows-of-Fire** [comment]
Reimplemented as a config option.
