### ISSUE TITLE
[TODO] Re-evalulate the current state of apotheosis loot tables

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Shadows-of-Fire/Apotheosis#451]
Also see about introducing affix loot pools into standard pools (chests/simple_dungeon, etc)

**Comment by JunArredodno** [comment]
I have a question, How do I put loot from another mods in the aphoteosis chests?. I'd like to add loot from electroblob's wizardry and its addons in the chests under the apothosis spawners but I don't know how to do that

**Comment by Shadows-of-Fire** [comment]
This should be handled on discord or a new issue.
