### ISSUE TITLE
Apotheosis incomptible with Easy Magic. needs a fix

### ISSUE THREAD

**Issue by echofuzzh** [Shadows-of-Fire/Apotheosis#452]
Apotheosis incomptible with Easy Magic. with both mods installed the Easy Magic dosen't work

**Comment by szunakabeats** [comment]
well Easy Magic makes enchantig completely different then Apotheosis. just disable the enchanting module if you want to use easy magic's enchanting style

**Comment by Shadows-of-Fire** [comment]
Easy magic is fundamentally incompatible with apoth, just like quark matrix stuff
