### ISSUE TITLE
Suggestion - increase Enchantment Library max points stored

### ISSUE THREAD

**Issue by Hiranus** [Shadows-of-Fire/Apotheosis#455]
All the Mods 6 pack allows player to make high level enchants that will fill Enchantment Library in one go. It would be really great if you could give us config option to change max Points Stored in Enchantment Library or just set it to MAX_INT. 
Alternatively, lower current max to 256 or something and make it so that Hellshelves that are attached to Enchantment Library increase current max value by ^2. So that to get larger storage space you need more hellshelves.

**Comment by Shadows-of-Fire** [comment]
The library as it stands will not be changed.  It's possible there is another tier of library introduced in the future, but this library will remain at 32767.
