### ISSUE TITLE
Crash when the world is being generated

### ISSUE THREAD

**Issue by ym1025** [Shadows-of-Fire/Apotheosis#457]
I got this crash-report when the world is being generated, but the other world can be loaded.
forge:1.12.2.2855
apotheosis: 1.12.2-1.12.5
[crash-2021-09-10_19.54.02-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7143327/crash-2021-09-10_19.54.02-server.txt)

**Comment by Shadows-of-Fire** [comment]
mc 1.12 is not supported
