### ISSUE TITLE
The Splitting Echantment does not work with modded anvils

### ISSUE THREAD

**Issue by Tfarcenim** [Shadows-of-Fire/Apotheosis#46]
Tested with Apothesis 1.10, Ender IO 5.0.44, and Extra Anvils 0.4

When either the dark steel anvil from ender io or any anvil from extra anvils is enchanted with splitting, it does not split the books.

**Comment by Tfarcenim** [comment]
addendum: the splitting enchantment is kept when placing/breaking the vanilla anvil, but not with modded.

**Comment by Shadows-of-Fire** [comment]
Nothing I can do about it really.  If you want, your anvils can extend my anvil extension class when you detect apoth.  The enchantments being retained requires a TE and splitting working requires an override to onEndFalling.
