### ISSUE TITLE
[Suggestion] Enchantmen Library sorting/searching

### ISSUE THREAD

**Issue by Discomanco** [Shadows-of-Fire/Apotheosis#468]
Enchantment Library is so nice to have, but it is also such a pain to browse through.  
I'll suggest either sorting the Library by name, or by what it can be applied to with a priority list. Or both, to make it a choice. Priority list could be something like `All (fx Mending/Unbreaking) > All Armor (fx Protection) > Helm > Chest > Legs > Boots > All Tools (fx Silk Touch) > Pickaxes > Axes >  Shovels > Hoes > All weapons (fx Sharpness) > Swords > Axes* > Shields > All Ranged (none?) > Bow > Crossbow > Trident`
*Axes are weird, as they can take a bit of both weapon and tool enchants

And/or, introduce a search bar in the Library, so you can easily find exactly what you're looking for.

**Comment by Shadows-of-Fire** [comment]
There's an alphabetical sort implemented in dev, it just hasn't been released yet.

**Comment by Discomanco** [comment]
Wonderful news
