### ISSUE TITLE
Bug of above 100% attack speed on sword

### ISSUE THREAD

**Issue by ABedwarsJoke** [Shadows-of-Fire/Apotheosis#469]
i spawned in alot of ancient sword affix and added to my op sword after adding all it had 150% attack speed but the attack indicator was bugged and wont work it was gray and wouldnt hit when i left click at a entity

**Comment by ABedwarsJoke** [comment]
![2021-10-02_21 59 24](https://user-images.githubusercontent.com/84129699/135725803-fb417130-9b89-44e0-bcd6-5044a8952d27.png)

proof

**Comment by Shadows-of-Fire** [comment]
not reproducible, a sword with +162% attack speed does not cause this issue.
