### ISSUE TITLE
Cant enchant at all unless vinilla level

### ISSUE THREAD

**Issue by AmdDoggo** [Shadows-of-Fire/Apotheosis#47]
Cant enchant at all unless its like 4 xp, i have been messing around with most enchants i use at 150 level and the max enchant recived /recived by normal 150 and it wont work, espically in creative mode, help ;-;

**Comment by Shadows-of-Fire** [comment]
I can't make any sense of this

**Comment by AmdDoggo** [comment]
I try to enchant, i do not get any options
I try to edit  config increasing max recived vaule for enchants in the config file, nothing. 
unles its very small number of bookshelfs it wil just show it as if theres nothing in it.

**Comment by Shadows-of-Fire** [comment]
Update to 1.10.1 and delete your config/apotheosis/enchantments.cfg file, which will reset your maxes to the auto-determined possible max values.

**Comment by AmdDoggo** [comment]
Im on 1.12.2

**Comment by AmdDoggo** [comment]
Oops you mean  mod version.

**Comment by AmdDoggo** [comment]
Didn't work, any incompatible mods or something that may be causing it?

**Comment by Shadows-of-Fire** [comment]
Anything else that modifies enchanting levels or maxes, or the table in general.  The only directly incompatible mod I know of is Enchantments Control

**Comment by AmdDoggo** [comment]
Wont work for me. I think its somethign wrong with my minecraft.

**Comment by AmdDoggo** [comment]
I cant enchant normally now. ;-;
