### ISSUE TITLE
Shield with receive 1 copy of an arrow you block duplicates whatever it blocks  

### ISSUE THREAD

**Issue by quasarea** [Shadows-of-Fire/Apotheosis#471]
![image](https://user-images.githubusercontent.com/10334982/135840404-32051518-bd6c-460d-bcc7-a688bd02de5e.png)

Not only arrows but tridents and anything it can block gets duplicated.

**Comment by Shadows-of-Fire** [comment]
Well it appears to just be tridents, just because the trident entity actually extends the arrow entity class (which is a bit weird).
I guess that needs a higher degree of filtering.
