### ISSUE TITLE
Lighting issue with Enchantment Library

### ISSUE THREAD

**Issue by WenXin20** [Shadows-of-Fire/Apotheosis#472]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Apotheosis v4.8.1`

When the enchantment library is facing east/west, it produces an odd shadow on its side, which is more easily visible if multiple are placed together. It doesn't have this problem when facing north/south.

![2021-10-09_14 41 41](https://user-images.githubusercontent.com/12000593/136672010-62733ca7-6f50-43ed-9431-f31860d62731.png)

**Comment by Shadows-of-Fire** [comment]
what in the world

**Comment by WenXin20** [comment]
¯\\_(ツ)\_/¯
Yeah, I've never seen something like this before either.
Forgot to mention this was on a server, but probably unrelated.

**Comment by Shadows-of-Fire** [comment]
It would appear you have to set `experimentalForgeLightPipelineEnabled = true` in forge-client.toml to get the model to be shaded correctly.
