### ISSUE TITLE
Crash game when applying texture pack.

### ISSUE THREAD

**Issue by ChubbsWasTaken** [Shadows-of-Fire/Apotheosis#474]
Forge: 1.16.5 36.2.8
Apotheosis: 1.16.5 4.8.1

When reloading textures using f3+t or loading ANY kind of resource pack whether in main menu or in game. crashes the game

Crash report:  [crash-2021-10-12_14.44.47-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7330076/crash-2021-10-12_14.44.47-client.txt)

**Comment by Shadows-of-Fire** [comment]
I can put in a fix for this, but it seems like it's more along the lines of some other mod putting a bad value in an itemstack's attribute modifier map, as it doesn't happen in isolation and I haven't seen any other reports of it occuring.
