### ISSUE TITLE
Crash on Worldgen (Feature placement)

### ISSUE THREAD

**Issue by Freebi85** [Shadows-of-Fire/Apotheosis#476]
Hey There :)
Got some crashes with Apotheosis while exploring the world.

Forge 36.2.8
Apotheoisi 4.8.2
[crash-2021-10-16_10.44.26-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7357244/crash-2021-10-16_10.44.26-server.txt)
[crash-2021-10-16_10.27.10-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7357245/crash-2021-10-16_10.27.10-server.txt)

Cheers

**Comment by Shadows-of-Fire** [comment]
Both of these would imply the structure that the second variant of the boss dungeon uses is not loaded, which would be impossible under default configuration.  You likely have something else interfering.
