### ISSUE TITLE
Crashing on loading up server

### ISSUE THREAD

**Issue by ShootToKillSTK** [Shadows-of-Fire/Apotheosis#480]
Something with deadly module it seems is crashing server on startup, removing this mod lets everything load up fine
 Crash log: https://gist.github.com/ShootToKillSTK/34a72ea6bf5be6b874391e82a2a8bfd9

Version of mod: 1.16.5-4.8.2
Tried with default configs too + no datapack (If that matters)

**Comment by Shadows-of-Fire** [comment]
this is a mohist problem.
