### ISSUE TITLE
Can't combine high level enchants with Charm and Apotheosis in 1.16.5

### ISSUE THREAD

**Issue by randomskoolkid** [Shadows-of-Fire/Apotheosis#481]
Versions
    Apotheosis - 1.16.5 4.8.2
    Charm version - 1.16.5 2.3.2 forge version
    Minecraft version - 1.16.5 forge 36.2.4

Description
I was playing the Better Minecraft Plus modpack and noticed I coudn't combine enchantments once they were one level above the vanilla limit. I loaded minecraft with only Charm, Placebo, and Apotheosis, and the problem persisted. I did this again, but this time without Charm, and was able to combine enchantments past their vanilla limit like normal.  I posted this to the Charm Reforged issues tab but I'm a bit skeptical that it will be addressed their since Charm Reforged hasn't been updated since February.

**Comment by Shadows-of-Fire** [comment]
charm's anvil modifications are incompatible with apoth, they can be disabled via their config to my knowledge.

**Comment by randomskoolkid** [comment]
Charm's anvil module is disabled in the config
