### ISSUE TITLE
Potion charms are not marked as non-repairable, just non-enchantable

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#484]
Not sure if this is intended, but it will make sources of repair such as ProjectE's talisman of repair regenerate durability on the charm. May be worth looking into.

**Comment by Rydjinn** [comment]
What if I don't want Project E? Instead I have Forbidden & Arcanus that adds the Eternal Stella(Makes items indestructible.)

**Comment by Shadows-of-Fire** [comment]
Making the charms indestructible was never supported behavior.

**Comment by Rydjinn** [comment]
I was able to enchant them before. Why not now?
