### ISSUE TITLE
I discovered an unkillable mob

### ISSUE THREAD

**Issue by villaxd123** [Shadows-of-Fire/Apotheosis#487]
Im playing a modpack with this mod installed and a mob called Zach (Skeleton) never dies, when he is on 1 of HP and i try to do the last hit this doesn't deal any damage and a sound like a thunder is triggered, then the floor near to this mob spawns a low layer of snow, i tried to hit without any weapon and the lowest amount of HP with wich i manage to leave is 0.25 of HP, this mob is unkillable or i don't know how to kill this if it's a normal tipe of mob.
![Unkillable Mob](https://user-images.githubusercontent.com/29488884/143826837-853bcc07-2913-4433-a0ae-de0f5f3fc995.png)

**Comment by Shadows-of-Fire** [comment]
Likely has some enchantment from some mod making him unkillable, it happens from time to time.  Nothing I can do from my side.
