### ISSUE TITLE
1.16.5 java.lang.RuntimeException: Attempted to apply a random attribute modifier to an entity (minecraft:pig) that does not have that attribute (minecraft:generic.attack_damage)!

### ISSUE THREAD

**Issue by Dante115** [Shadows-of-Fire/Apotheosis#489]
last version of the mod getting this crash ?!
[crash-2021-12-08_17.38.15-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7677408/crash-2021-12-08_17.38.15-server.txt)

**Comment by Shadows-of-Fire** [comment]
pigs are not valid bosses, nor are they default boss types, so you probably have a broken datapack.

**Comment by Dante115** [comment]
> pigs are not valid bosses, nor are they default boss types, so you probably have a broken datapack.

ok i get it.how am i gona fix it ?

**Comment by FelixGrafschmidt** [comment]
@Dante115 Did you ever find a solution to this? I started running into this issue as well.

**Comment by MrDragger** [comment]
Dude I've followed you through 2 different websites @Dante115, did you somehow fix it?

**Comment by Dante115** [comment]
> Dude I've followed you through 2 different websites @Dante115, did you somehow fix it?

it was like 2 years ago, i tihkn i added attribute fix mod after that i just gave up and went to 1.19.2

**Comment by MrDragger** [comment]
NOOOOOOOOO, i'm tryna play Enigmatica 6 (1.16.5) gosh darnit

**Comment by MrDragger** [comment]
I actually fixed it, go to the minecraft file location in the mod file, look for the config file, open the apotheosis file, open "deadly.cfg" (using notepad for me) scroll down till you see the bosses section, change "The 1/n chance that a naturally spawned mob that can see the sky is transformed into a boss.  0 to disable. [range: 0 ~ 500000, default: 85]" to false, 
Now pigs can no longer crash ur got darn game
