### ISSUE TITLE
Attempted to apply a random attribute modifier to an entity (minecraft:pig) that does not have that attribute (minecraft:generic.attack_damage)!

### ISSUE THREAD

**Issue by Dante115** [Shadows-of-Fire/Apotheosis#490]
i have a clean modpack still getting this error
[crash-2021-12-09_18.57.42-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7687062/crash-2021-12-09_18.57.42-server.txt)
please help me

**Comment by Shadows-of-Fire** [comment]
See #491 (very likely external interference)
