### ISSUE TITLE
Enchanting Charms

### ISSUE THREAD

**Issue by Rydjinn** [Shadows-of-Fire/Apotheosis#493]
So, I don't know when this changed but, you used to be able to enchant potion charms with things like Unbreaking and Mending. (As well as the Eternal Stella from Forbidden Arcanus that makes items indestructible). I was wondering if that was going to be added back, because it's very frustrating to have to remake all the potions just to get a new charm.

**Comment by LuciusV** [comment]
Definitely most frustrating nerf in all my modded Minecraft experience. Please make config option to enable them to be enchanted!

**Comment by derrickmehaffy** [comment]
Pretty sure this commit is what changed it: https://github.com/Shadows-of-Fire/Apotheosis/commit/4bdf3779928c6fa763ed05731ef100dfd88596f6

Related to: https://github.com/Shadows-of-Fire/Apotheosis/issues/484

But I 100% agree, annoying as heck, at the minimum set a config option that disables it by default. Modpacks like ATM6 these charms are critical in late game.

**Comment by KrashKourse** [comment]
I updated to a new version of this mod and hated it because of these changes to the enchantment changes to charms and the Stella recipe. 

I am activly going to grab another mod that will allow me to enchant any object. this is pretty bad change. not sure why the author chose phase out the fun of the mod... "need to make it more challenging" yeh but we play with mods because we like fun not because we want to hit our heads against a wall that needs to be recrafted all the time. 

2/10 mod rating for fun. 
1 point for still having enchanting tables that work good
1 point for having mobs that are fun to fight
-8 points for enchantment changes to charms

**Comment by derrickmehaffy** [comment]
> I updated to a new version of this mod and hated it because of these changes to the enchantment changes to charms and the Stella recipe.
> 
> I am activly going to grab another mod that will allow me to enchant any object. this is pretty bad change. not sure why the author chose phase out the fun of the mod... "need to make it more challenging" yeh but we play with mods because we like fun not because we want to hit our heads against a wall that needs to be recrafted all the time.
> 
> 2/10 mod rating for fun. 1 point for still having enchanting tables that work good 1 point for having mobs that are fun to fight -8 points for enchantment changes to charms

Considering the mod is licensed in MIT I'm debating just simply forking it

**Comment by LuciusV** [comment]
@Shadows-of-Fire could you please accept mentioned pull request? Please take our feedback there into account

**Comment by Shadows-of-Fire** [comment]
1.16 will be receiving no changes until 1.18 is stable with all modules available.

**Comment by changhe3** [comment]
> > I updated to a new version of this mod and hated it because of these changes to the enchantment changes to charms and the Stella recipe.
> > I am activly going to grab another mod that will allow me to enchant any object. this is pretty bad change. not sure why the author chose phase out the fun of the mod... "need to make it more challenging" yeh but we play with mods because we like fun not because we want to hit our heads against a wall that needs to be recrafted all the time.
> > 2/10 mod rating for fun. 1 point for still having enchanting tables that work good 1 point for having mobs that are fun to fight -8 points for enchantment changes to charms
> 
> Considering the mod is licensed in MIT I'm debating just simply forking it

I built your fork and it doesn't seem to change anything. 

You need to revert fa641e9 too

**Comment by Jelen941** [comment]
yup its unplayable after u removed infusion enchant... how long they gonna last 5min?....
Hope u gonna fix it :3 or atleast tell us how to fix it
