### ISSUE TITLE
[Feature Request] Allow configuring which block would be placed via Torch Placer affix

### ISSUE THREAD

**Issue by juh9870** [Shadows-of-Fire/Apotheosis#494]
Please allow configuration of which block would be placed by torch placer affix on tools. Aka, in my case, I would like for Torch Placer to instead place Miner's Light from Mining Gadgets mod

**Comment by Shadows-of-Fire** [comment]
I don't _think_ that will work, the torch placement affix functions by actually acting if you had right-clicked a torch item, and afaik the miner's light is not a holdable item.

**Comment by juh9870** [comment]
At least on 1.16, miner's light have item form, and it's even possible to make it craftable
