### ISSUE TITLE
Porting to version 1.12.2 ❓ 

### ISSUE THREAD

**Issue by ElardHuaraca** [Shadows-of-Fire/Apotheosis#495]
I'm trying to port the whole mod 1.16.5 to version 1.12.2 but there are parts in 1.16.5 where I don't understand how you did to change the state of the declarations such as CRITERIA that is in the AdvancementTriggers.class class since this is a private attribute. If you could give me an explanation on how to take it, I would appreciate it

![Screenshot_1](https://user-images.githubusercontent.com/56555556/147209726-9653c4b1-d90d-4a55-867a-b5da84cbf3b9.png)

![Screenshot_2](https://user-images.githubusercontent.com/56555556/147209847-cd34142d-df94-4212-8790-c88ab9d47579.png)

**Comment by Shadows-of-Fire** [comment]
You should not be trying to backport this project.

**Comment by ElardHuaraca** [comment]
Ok, but i want to try, thanks
