### ISSUE TITLE
A clash of Apotheosis

### ISSUE THREAD

**Issue by Theagree** [Shadows-of-Fire/Apotheosis#496]
if i install Apotheosis and endergetic in server at the same time normal mobs will spawn in end, i think it is because of endergetic spawn a normal world biome in end, however if Apotheosis is deleted from server , the problem will be solve ,but i really want to play this mod!!! please help me out ! thank you!

this is a normal world biome↓(mobs will spawn)
![image](https://user-images.githubusercontent.com/84651172/147402921-8acb1b2e-bda7-4565-9f28-5c75cf48c81e.png)

this is a end biome↓(mobs will not spawn)
![image](https://user-images.githubusercontent.com/84651172/147402882-0d313abe-2f85-4117-a847-f0b15924d7e1.png)

**Comment by Theagree** [comment]
abnormals core 3.3.0
endergetic 3.0.0

apotheosis 4.8.4
placebo 4.6.1
 forge 36.2.22

**Comment by Shadows-of-Fire** [comment]
Apotheosis does not intervene in mob spawning rules or biome placements.

**Comment by onyxagata** [comment]
as you can see by looking at the biome, atmospheric mod is the biome mod that is affecting the end. i suggest checking with them instead

**Comment by onyxagata** [comment]
> abnormals core 3.3.0 endergetic 3.0.0
> 
> apotheosis 4.8.4 placebo 4.6.1 forge 36.2.22

this is clearly not your entire modlist. if youre not gonna give an entire modlist, dont expect anyone to help you
