### ISSUE TITLE
Suggestion - Make the Tome Tower a Minecraft Structure

### ISSUE THREAD

**Issue by Tydeed** [Shadows-of-Fire/Apotheosis#498]
It will be possible to use a command /locate apotheosis:tome_tower (for example) or the mod "Explorer's Compass" to find them.

**Comment by ZephyrWindSpirit** [comment]
Terraforged doesn't recognize the tome tower as a structure right now, so I would also like to see this pop up. Please and thank you. 
1.16.5

**Comment by PostEpoch** [comment]
Another benefit would be the ability to use built-in structure checks in FTB Quests. Would love to be able to build out some quests that use "find X number of towers".

**Comment by Shadows-of-Fire** [comment]
6.3.0
