### ISSUE TITLE
AIOT Tool from Botania AIOT can only apply Pickaxe Affixes

### ISSUE THREAD

**Issue by telemenar** [Shadows-of-Fire/Apotheosis#499]
I was playing around Affixes in Enigmatica 6 and I had an Alfsteel Botania AIOT, and I can only apply pickaxe affixes. 

The Botania AIOT mod adds all of the different tool types: 
https://github.com/MelanX/aiotbotania/blob/fd49c000f9533d46c680e0d617c8f6f38c58bdf3/src/main/java/de/melanx/aiotbotania/items/base/ItemAIOTBase.java#L41

But it looks like it is locked to only every a single tool type for Apotheosis:
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/deadly/affix/EquipmentType.java#L42

**Comment by Shadows-of-Fire** [comment]
The current implementation only permits for a single equipment type, as you've figured.  Unfortunately this will not be getting changed on 1.16.

However, the system is being rewritten for 1.18, so this can likely be remidied there

**Comment by Shadows-of-Fire** [comment]
This is...  sort of remedied, but only because affixes are non-movable now, so, bleh.
