### ISSUE TITLE
game crash on load in

### ISSUE THREAD

**Issue by dragonguy215** [Shadows-of-Fire/Apotheosis#50]
[crash-2019-06-05_19.10.23-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/3259482/crash-2019-06-05_19.10.23-client.txt)

**Comment by ProsperCraft** [comment]
Have you tried without dynamic trees installed? did you report to them as well?

**Comment by Shadows-of-Fire** [comment]
https://github.com/ferreusveritas/DynamicTrees/issues/217
