### ISSUE TITLE
Loot from another mods

### ISSUE THREAD

**Issue by JunArredodno** [Shadows-of-Fire/Apotheosis#500]
I'd like to add loot from electroblob's wizardry and its addons in the chests under the apothosis's spawners but I don't know how to do that, so, How do I do that?.

**Comment by Shadows-of-Fire** [comment]
You would need to use a datapack to override the existing loot table, and introduce the new entries that you want within it.

To receive a json-copy of the loot table, use the `/placebo serialize_loot_table` command for the specific table.
