### ISSUE TITLE
Documentation for how to apply effects to bosses (and in general)

### ISSUE THREAD

**Issue by darchitectlp** [Shadows-of-Fire/Apotheosis#501]
Trying to figure out how to prevent fire resistance from being applied to skeleton bosses... it looks like we're supposed to use datapacks to add effects? Is there documentation somewhere that shows how this works?

**Comment by Shadows-of-Fire** [comment]
You would need to use a datapack to override the existing boss entries to ones without fire resistance
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/resources/data/apotheosis/bosses/skeleton.json#L11-L14

**Comment by darchitectlp** [comment]
Thank you!
