### ISSUE TITLE
Mod compatibility with Yung's Better Dungeons

### ISSUE THREAD

**Issue by predundant** [Shadows-of-Fire/Apotheosis#502]
Not sure if this is an Apotheosis thing or a Better Dungeons thing, but Apotheosis boss dungeons and rogue spawners do not generate with better dungeons installed.  By default Better Dungeons disables vanilla dungeon generation.  Changing the Better Dungeons config to allow vanilla dungeons fixes this, but ideally they would be made compatible so that Apotheosis things generate despite this setting in Better Dungeons.

**Comment by Shadows-of-Fire** [comment]
You'd need to bring it up with them, if they're the ones removing my worldgen Feature.  I can't really prevent them from deleting it.
