### ISSUE TITLE
Execute works on players and breaks all player armour.

### ISSUE THREAD

**Issue by Psithief** [Shadows-of-Fire/Apotheosis#506]
Version 1.16.?-4.8.3

I just had a player break all of my armour with a weapon that has the Execute affix. It also crashed the server, though I don't have access to the logs to see what happened there.

I don't see anything in the Execute Affix code that's supposed to prevent this from happening.

The axe in question also had the Piercing, full CritChance and CritDamage affixes.

It occurs to me that the affix is also triggering after the initial damage is dealt, instead of only if the entity had less than the execute % before being damaged.

Can you elaborate on your intended design for this affix? Is it supposed to work on players? Is it supposed to break all armour?

**Comment by Shadows-of-Fire** [comment]
It should work on players, and it should kill them if they would be left at a threshold lower than the %, however it probably shouldn't obliterate armor... That's likely a side effect of the impl

**Comment by Psithief** [comment]
It is intended to bypass totems of undying as well?

**Comment by Psithief** [comment]
Also, dealing float.Max_value really screws up the player's damage taken statistic. 😆

**Comment by Shadows-of-Fire** [comment]
Fixed in 4.9.0.
