### ISSUE TITLE
Trying to get rarity shard not working

### ISSUE THREAD

**Issue by Mechrior** [Shadows-of-Fire/Apotheosis#507]
Have been trying several different attempts to turn a diamond sword into a mythic shard as per the JEI recipe information, but the sword will not place on the campfire at all.
Pack: Direwolf 20 1.16.5: 1.13.
Apotheosis version: 1.16.5-4.8.4

Actions: Placed soul campfire down, treid to right click diamond sword onto it, nothing happens.
Expected: Sword turns into mythic shard as per jei.

**Comment by Shadows-of-Fire** [comment]
Just a random diamond sword?  You need an affix item of the appropriate rarity to make a shard.

**Comment by Mechrior** [comment]
> Just a random diamond sword? You need an affix item of the appropriate rarity to make a shard.

Ah so that is what is not explained well in JEI is that you salvage an item with an affix on it already to obtain the rarity shard.
Ok that was my mistake and also a miscommunication from JEI!
Sorry to have bothered you! Thank you very much for clearing that up.

**Comment by Shadows-of-Fire** [comment]
Yeah it's written on the item tooltip, I'm honestly not sure of a better spot to put it.
I might need to extend the space and draw the text on there.
