### ISSUE TITLE
Eidolon Soul Enchanter breaks spechalized enchantment progression

### ISSUE THREAD

**Issue by Shibva** [Shadows-of-Fire/Apotheosis#508]
The issue is that I found the soul enchanter being a "bipass" to the new echantment system for all 3 new enchantment types and can serve as a progresion skip for creating high quality gear, is their a way to make them only excpusive to this new enchantment system

**Comment by Shadows-of-Fire** [comment]
There is no method of doing that.  It sounds like your best course of action would be to disable the soul enchanter.

**Comment by Shibva** [comment]
I wish I could
