### ISSUE TITLE
Enchanted book dupe with the Enchantment Library

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/Apotheosis#509]
Relayed from: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4060
`Apotheosis-1.16.5-4.8.4`

> ### Describe your issue.
> explanation to the best of my ability: The Enchantment Library from apotheosis, being limited by Java integer, can not subtract the "max enchant value" if the max value of the inputted enchant is over integer 32767, (which, was power 17 and above) henceforth; when a book with 32767> value is inputted, it correctly detects the "new highest level enchant" but it fails to substract the correct value when using "shift + click" and rolls to the closest positive cost, which is zero. costs zero to extract a level 17 book (upon further testing, power 26 was the highest that pedestals can handle, still gets duped on the library.)
> 
>  bug_Trim.mp4 
> due to English not being my native language, I found it easier to explain visually on video rather than on text; sorry for the inconvenience
> 
> ### Did the issue happen in singleplayer or on a server?
> Singleplayer

**Comment by Shadows-of-Fire** [comment]
Well that's fun, bleh signed overflow.
