### ISSUE TITLE
[Request] Mob spawner config

### ISSUE THREAD

**Issue by Roonas** [Shadows-of-Fire/Apotheosis#51]
Please consider adding a configuration option to allow the frequency of rogue spawners to be manipulated so users can change how common they are, as well as a dimensional whitelist/black list for the rogue spawns specifically. 

Side note: It seems the loot tables in chests generated by the rogue spawners cannot be manipulated or don't adhere to loot table changes.

**Comment by crazyirishwrencher** [comment]
+1. Would love to see Apotheosis Spawners generate in other dimensions. I added dimensions to the "Generation Dimension Whitelist" but I can't find them spawning in the dimension I've added to that list (Aroma's Mining Dimension).

**Comment by crazyirishwrencher** [comment]
Perhaps if there's a way to use one of the world gen mods (COFH World, etc) to generate spawners as a block with the features in the deadly module...

**Comment by AttilaPapp** [comment]
+1. Also if you could add biome and biometype restrictions whitelist/backlist for spawner config that would be awesome!!!

Thank you for creating this mod!!!

**Comment by Shadows-of-Fire** [comment]
The chance for a spawner to be created in a chunk can already be manipulated.  See the deadly module configs.

As for different dimensions, there was a bug preventing chunks with the same coordinates in different dimensions from being run through, which has been corrected.

The loot tables should respond to manipulation from LootTweaker, if they don't that should be reported to https://github.com/Shadows-of-Fire/Placebo since the loot system is in the library.

**Comment by AttilaPapp** [comment]
The range of the possibilities in deadly module blown me away it is really nice to have such a vast amount of options.

>The chance for a spawner to be created in a chunk can already be manipulated. See the deadly module configs.
> 
Yes, I am fully aware of this option, I was wondering if you would consider adding a more specific option to create templates or presets to allow for an even more customized experience.

Let say I would like to use an undead swarmer in the cold biome type, a mummy brutal spawner in pyramids.

I really appreciate the work you put in this mod and I appreciate that this is not a "dungeon mob spawner" exclusive mod, yet I would be ecstatic to be able to restrict them to biomes/biometypes.

Thank you in advance

**Comment by Shadows-of-Fire** [comment]
Ah, that level of customization.  I had given some thought to it but it would require a pretty complex deserialization system to read all the data a spawner requires.  I'm currently focusing mostly on 1.14 at the moment, as I've gotten a bit burnt out on 1.12.  Might see that level of complexity in the future.

**Comment by AttilaPapp** [comment]
If not the preset thing, just the restriction to biome/biometype would still be awesome. Sorry if I am asking for too much I don't know how big of a task that is.
