### ISSUE TITLE
Netherwood Sapling CTD

### ISSUE THREAD

**Issue by Varricorn** [Shadows-of-Fire/Apotheosis#512]
I am playing on the latest version for 1.18.1 on a new server with only a handful of simple QoL mods, was trying to plant my Netherwood Saplings to get some Netherwood Sticks, and immediately crashed to the launcher.
Any fixes for this at the moment? If not, oh well. I am patient and can wait for fixes

**Comment by Shadows-of-Fire** [comment]
I think you might be in the wrong place...
