### ISSUE TITLE
There are a lot of such errors in the logs. Failed to load boss item brutalbosses:

### ISSUE THREAD

**Issue by RIZ79** [Shadows-of-Fire/Apotheosis#513]
[2022-01-23-4.log.gz](https://github.com/Shadows-of-Fire/Apotheosis/files/7921632/2022-01-23-4.log.gz)

https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/deadly/reload/BossItemManager.java#L61

**Comment by Shadows-of-Fire** [comment]
This is something that needs to be reported to brutalbosses, since they appear to be providing invalid boss jsons (or they are inadvertently using the sub-namespace I have already claimed for apotheosis bosses).

**Comment by someaddons** [comment]
I'm having my very own custom bosses json, unrelated to apotheosis, which for some reason apotheosis is loading. My bosses are in my own namespace under
data/brutalbosses/bosses so if you're scanning those then likely something is wrong on your side

**Comment by RIZ79** [comment]
He sent me to you
https://github.com/someaddons/dungeonbosses/issues/2

**Comment by Shadows-of-Fire** [comment]
@someaddons Then you misunderstand how JSON data-loading works.
When you declare a JSON reload listener, you declare a sub-path, which loads for all _domains_.  Meaning `/apotheosis/bosses/`, `/minecraft/bosses/`, `/anything/bosses/` (same as recipes, advancements, etc).

Apotheosis already has been using the subkey `bosses` for a very long time.  You'll need to chose another one.

**Comment by someaddons** [comment]
Yes the default implementation is very greedy, and just loads all lowest subfolders with exactly that name, ignoring mod namespace. Which is fine for vanilla, since those folders get shared by mods, but for custom modded folder the proper way would be to exclude reading the wrong namespaces in your reload listener. Instead of kindergarden behaviour of claiming "I was first" on generically named folders.

**Comment by Shadows-of-Fire** [comment]
Bosses are something I expect other mods (or packs) to add under other domains.  This is literally how the system is designed and intended to be used.
