### ISSUE TITLE
Crashing during start

### ISSUE THREAD

**Issue by zezreli** [Shadows-of-Fire/Apotheosis#517]
Latest.log = https://paste.gg/p/anonymous/27bdd6b2beac4b1cb6a2d3588a1f76db
crash log = https://paste.gg/p/anonymous/d9e6828c27a64727bf592e401a5f4c9d

during the start up of the game it crashes and it says its placebo 
minecraft 1.18.1
forge 39.0.47

**Comment by Shadows-of-Fire** [comment]
What version of Placebo do you have installed?  You need 6.0.4

**Comment by zezreli** [comment]
it is 6.0.4 might have found the issue, so i checked the mods folder and there where two copies of placebo one 6.0.3 and one 6.0.4 and when i removed the 6.0.3 verison it now stopped crashing

**Comment by zezreli** [comment]
so it seems that curseforge instead of just updating the mod it installed a second new version of the mod

**Comment by Shadows-of-Fire** [comment]
That's a weird bug with CF that has been happening recently.
