### ISSUE TITLE
weird bug

### ISSUE THREAD

**Issue by zezreli** [Shadows-of-Fire/Apotheosis#518]
so i got in on my world, and started mining, an no items dropped after i mined like the fifth block the game crashed and the crash log file points to apotheosis.ench module

crash log = https://paste.gg/p/anonymous/d70ac3586aac452595010f294910d2e2
latest.log = https://paste.gg/p/anonymous/557b82121c474535a7118e726f6b60da
apotheosis -1.18.1-5.1.0
placebo-1.18.1-6.0.4
forge - 39.0.47
minecraft 1.18.1

**Comment by Shadows-of-Fire** [comment]
Update to 5.1.1

**Comment by zezreli** [comment]
thanks
