### ISSUE TITLE
Crash Related to New Version.

### ISSUE THREAD

**Issue by Elkinsrg** [Shadows-of-Fire/Apotheosis#519]
Unknown crash related to new version of Apotheosis. Not sure where to pull logs to show you as it seems Minecraft doesn't even know what is the problem. Tell me which log you need and I'll provide it. Since updating to 1.18.1-5.1.1 the game crashes. The only update that happened at the time was Apo and Placebo but the game runs fine with just placebo (thought I think no other core reqs are installed so it isn't really doing anything either).

**Comment by Shadows-of-Fire** [comment]
I would need a debug.log located at <root>/logs/debug.log

**Comment by Remingusu** [comment]
I have the same problem. I don't have "debug.log" but I have this. I think you have fixed the problem but you have not put the new version online.
[2022-01-24-2.log](https://github.com/Shadows-of-Fire/Apotheosis/files/7927160/2022-01-24-2.log)

**Comment by Shadows-of-Fire** [comment]
@Remingusu You have two different placebo jars installed, which is a curseforge bug.  You have to remove the old one manually.
@Elkinsrg You may want to see if you have the same issue.

**Comment by Remingusu** [comment]
Thank you very much !

**Comment by Elkinsrg** [comment]
Unfortunately, I don't think this is my issue. I also don't have a debug.log but I do have this latest log following the crash..
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/7928096/latest.log)
.

**Comment by Shadows-of-Fire** [comment]
Ah, you have the mod xpisnoobject installed, which conflicts with apoth.  You'll need to remove it.  Apoth already does what it does.

**Comment by Elkinsrg** [comment]
See, I'm not smart enough to see that. Thank you, I'll try it.

**Comment by Elkinsrg** [comment]
Beautiful! Works like a charm! Thank you for taking the time to figure that out. Great Mod BTW.
