### ISSUE TITLE
Crash on the newest version

### ISSUE THREAD

**Issue by Matschelin** [Shadows-of-Fire/Apotheosis#520]
[crash-2022-01-24_16.59.10-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/7926914/crash-2022-01-24_16.59.10-client.txt)
Hey i just updated the mod and it crashes everytime when i start the modpack i attached the crash report.

**Comment by Shadows-of-Fire** [comment]
You have two copies of apoth installed.

**Comment by Matschelin** [comment]
no there is just that one apotheosis i updated it with the curseforge launcher maybe that makes some problems i try to install the updated version from the internet now

**Comment by Matschelin** [comment]
its actually a problem with curse it just installed the new version too and dont removed the older one so thanks.
