### ISSUE TITLE
[Question] What does Rectification do?

### ISSUE THREAD

**Issue by Khaeops** [Shadows-of-Fire/Apotheosis#523]
Noticed this was a new stat provided by some shelf types, but there is no in-game description for it and nothing on the Curseforge page.

**Comment by Shadows-of-Fire** [comment]
Rectification reduces the lower bound on quanta modifications

Standard quanta modifications work by changing your base power (the level) to a value in the range [-Q, +Q].

Having rectification changes this range to [-Q * (1-R), +Q]

So if you had 100% rectification, the quanta modifier range becomes [0, +Q] meaning all rolls are beneficial.
