### ISSUE TITLE
Soul Campfire - Recipe doesn't exist in 1.12.2 version (for me)

### ISSUE THREAD

**Issue by Halomationdude14** [Shadows-of-Fire/Apotheosis#524]
Hello,

So I enjoy modding my MC worlds and doing various things. There's this MC world that I've had for over 10 years and I've solidified on the 1.12.2 version (because I loooooooove Thaumcraft!). I have the Apotheosis mod and it's one of my favorites... however... I just attempted to migrate the affixes from a legendary wooden sword to the brand new diamond sword I just made. I have all the materials to do so... but my only problem is that the recipe for the soul campfire doesn't exist (not even in creative mode or the Not Enough Items JEI). I've tried to see if anyone else has had this issue and one report did show up on the GitHub, but had no answer. I have the tome of scrapping but no soul campfire. Also, one thing I've noticed is that whenever I look at the "abilities" of said weapon there aren't any shown. I think they only show for Apotheosis bosses (which I've only ever encountered one in my lifetime).

I would appreciate an explanation of why it's not possible to fix any of these or if I'm doing something wrong. Please and thank you!

Signed,
Halo

**Comment by Shadows-of-Fire** [comment]
Hi - 1.12.2 is reallllllly old, and a ton has changed since then.  The content you are trying to access simply didn't exist back then.
Here's the 1.12 CF Page for reference: https://web.archive.org/web/20191108030535/https://www.curseforge.com/minecraft/mc-mods/apotheosis

**Comment by Halomationdude14** [comment]
Thank you for the quick response! I would imagine you're probably busy trying to update the 1.18 version, but the 1.12.x versions are still very popular (and in my opinion the 1.12.x versions have the best selection of mods out there). Would you be able to implement at least this one tiny little feature in the 1.12.2 version sometime in the future?

**Comment by Shadows-of-Fire** [comment]
1.12 is (and has been) declared end-of-life.  It will not be receiving any further updates for any reason.

**Comment by Halomationdude14** [comment]
Well, that's unfortunate to hear. Great job on the mod tho! Really like it overall!
