### ISSUE TITLE
Suggestion: Boss item rarity also affects enchantments

### ISSUE THREAD

**Issue by GrigLog** [Shadows-of-Fire/Apotheosis#525]
Right now a Common item can easily have 4 high-level useful enchantments (like Fortune, Mending, Efficiency and Unbreaking at the same time), and Mythic armor piece can have just one miserable Occult Aversion. Affixes are not as valuable as enchantments, these +20 enchantability or +2 armor toughness are negliable and thus item rarity is pointless. I suppose it should also affect the amount and quality of enchantments provided, for example Common items having only 1 weak enchantment, Uncommon having 1-2, and so on. What do you think?

**Comment by Shadows-of-Fire** [comment]
With the current design of bosses the enchantment levels are designated statically in the JSON, and having it be modified would either required having the jsons specify additional values for higher rarities (which is a breaking change to the schema) or doing it as a percentage (which would not be binary breaking, but would introduce differences in expected vs actual levels).

I'll keep this in mind for the redesign in 1.18 though.
