### ISSUE TITLE
[Suggestion]: Vein Mining enchantment

### ISSUE THREAD

**Issue by JayDo96** [Shadows-of-Fire/Apotheosis#526]
Add a multitiered enchantment that can go on tools. Each level of the enchantment would increase the extra amount of blocks mined by 1-5 depending on how you want to balance it.

**Comment by Weedoof** [comment]
For what it's worth, this already exists in another mod.
https://www.curseforge.com/minecraft/mc-mods/vein-mining

**Comment by Shadows-of-Fire** [comment]
AOE mining is something covered by the affix system (And is also an enchantment in that mod).  So it's not something that will feature as an apoth enchantment.
