### ISSUE TITLE
Right-clicking egg on spawner to change entity, but spawner reverts back to original entity.

### ISSUE THREAD

**Issue by HowardRoark2016** [Shadows-of-Fire/Apotheosis#527]
I'm playing ATM7 1.18.1 v0.2.36 which uses Apotheosis-1.18.1-5.2.2. I silk-touched a skeleton spawner from a DungeonsArise dungeon. I created a Mob Grinding Utils villager egg using a swab. I right-clicked the spawner with the villager egg. I also right-clicked the spawner with a comparator so that I could have redstone control over the spawner. I placed the spawner on the ground with a lever beside it. I could see the villager in the center of the spawner. I activated the lever. Sure enough, several villagers were spawned. However, the spawner reverted back to skeletons and suddenly skeletons were spawning. I repeated the entire process. Villagers spawned in the first spawning cycle but then skeletons spawned after that.

**Comment by Shadows-of-Fire** [comment]
The actual issue for this is that the vanilla code for changing an entity only changes the entity of the current spawn potential - if you find a spawner with multiple potentials, it will only change one of them.

5.3.0 and onward will re-implement a fix to this by clearing all spawn potentials when a spawn egg is applied.
