### ISSUE TITLE
Affixes not displaying client side

### ISSUE THREAD

**Issue by sixpakvb** [Shadows-of-Fire/Apotheosis#528]
Affixes show properly when entering a server for the first time  after starting the client.  If you exit the server and re-enter, however, all affixes will be invisible until restarting the client.

**Comment by Shadows-of-Fire** [comment]
The affixes are just nbt data - if you are having issues with nbt data syncing somehow, then that might happen, but that's out of my scope.  This is not something I've been able to reproduce.
