### ISSUE TITLE
Unbreakable charm 1.18.1

### ISSUE THREAD

**Issue by Remingusu** [Shadows-of-Fire/Apotheosis#529]
Hi!

In JEI we can see that charms can be made unbreakable with the infusion enchantment, at level 100. But when I want to put "infusion" with a command ("/enchant Remingusu apotheosis:infusion") it tells me that the enchantment cannot be put on charms. Is this normal?

**Comment by Shadows-of-Fire** [comment]
Infusion is not an enchantment that can be applied as it doesn't do anything.  If you wanted to make it via nbt editing you would apply the vanilla Unbreakable tag
