### ISSUE TITLE
[1.14.2] Please add a config to disable the grave chest.

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Apotheosis#53]
Please add a config.

Also please add a config option to diable the grave that will allow us to keep your mod in the pack with a more elaborate grave mod in place like Tombstone.

**Comment by Jack-0-Spades** [comment]
Seconded

**Comment by Shadows-of-Fire** [comment]
Added in the 1.14.3 update

**Comment by Corail31** [comment]
For me, it's not enough, the version 1.14.3 of Apotheosis is 25ko of another thing but is not Apotheosis like in 1.12.2, and my mod will reject it automatically it as a grave mod. Playground tests is not for pack.

**Comment by Shadows-of-Fire** [comment]
Crash code is childish.

**Comment by Corail31** [comment]
```
Corail3124/06/2019
hey shad, you should make an api with source for your death chest
as without source and without api i can only consider it as incompatible
```
