### ISSUE TITLE
Spawner issue 

### ISSUE THREAD

**Issue by itsmetzl** [Shadows-of-Fire/Apotheosis#531]
I'm unable to upgrade my spawners using clocks, sugar, etc, it just says ERROR
I'm new to this mod so it may be something I'm doing wrong but wanted to post incase 
![asdasdas](https://user-images.githubusercontent.com/99234245/152916304-3a20c5e9-cfe6-403b-8449-cbd64fe601bc.PNG)

**Comment by Shadows-of-Fire** [comment]
version?

**Comment by itsmetzl** [comment]
> 
I'm on SkyFactory 4 4.2.4 
Apotheosis 1.12.2-1.12.5

**Comment by Shadows-of-Fire** [comment]
Modifiers might be changed - they will be visible in jei
the <ERROR> text is from `The One Probe`, it has nothing to do with apoth, and spawner stats are only available through the `Jade` mod, not ToP (which is not supported until 1.18).
