### ISSUE TITLE
Trying to infuse the enchantment library without success.

### ISSUE THREAD

**Issue by Thunder-Nova** [Shadows-of-Fire/Apotheosis#533]
**Versions**: All the mods 7 v.40b - which has Apotheosis 5.3.2

So I am have wasted a bunch of experience into trying to infuse the enchantment library into the Library of Alexandria, it will actually pull levels from me, but nothing happens.

Did it as said 50/50 Eterna, 45% (and 50% as well) Quanta (tried without rectification as well), and Arcana 99.5%+.5% Enchantability bonus?

I don't know personally, but it feels that it doesn't detect the bonus.
![2022-02-11_23 27 53](https://user-images.githubusercontent.com/31967337/153700116-c2fbb7c3-236e-4a7c-acd1-734931ce68be.png)
![2022-02-11_23 27 49](https://user-images.githubusercontent.com/31967337/153700125-e5a2f8ef-5e5f-494b-9e5a-570ff51c83b3.png)
![2022-02-11_23 27 48](https://user-images.githubusercontent.com/31967337/153700134-05430fcd-8af0-4dd7-8207-8b36b3736d7f.png)
![2022-02-11_23 35 50](https://user-images.githubusercontent.com/31967337/153700174-e2d87153-20c1-4ae4-8dbb-d12f16cf8190.png)
![2022-02-11_23 39 13](https://user-images.githubusercontent.com/31967337/153700285-f79acdc0-002b-40bd-bed3-90dbcdc8826e.png)
![2022-02-11_23 39 38](https://user-images.githubusercontent.com/31967337/153700290-85faf512-0bdc-4987-bdb8-422ac6fb57c2.png)
![2022-02-11_23 39 41](https://user-images.githubusercontent.com/31967337/153700292-2d7c8e93-004f-40ac-ac54-3b8b76cba590.png)

**Comment by Shadows-of-Fire** [comment]
Given that the other two slots are lit up - the infusion enchantment is not even engaged, because the infusion enchantment system disables the top two enchantment slots.  What shows up in those slots?

**Comment by Shadows-of-Fire** [comment]
Well, other weirdness aside, it looks like it is bugged for a different reason.
If you have at least 1 stored enchantment in the library, it'll work.
