### ISSUE TITLE
[Compatibility] Support for the Capturing enchant to drop eggs added by the Wither Eggs mod

### ISSUE THREAD

**Issue by Dutchs** [Shadows-of-Fire/Apotheosis#534]
[Wither Eggs](https://www.curseforge.com/minecraft/mc-mods/wither-eggs) adds eggs for the Wither, Ender_Dragon, Iron_Golem, Snow_Golem, Illusioner and Giant, currently these seem to not be dropped by the Capturing enchant.
This might have something to do with that mod using `ForgeSpawnEggItem` rather than `SpawnEggItem` which Apotheosis uses, as seen here: [WitherEggs.java](https://github.com/IchHabeHunger54/WitherEggs/blob/master/src/main/java/ihh/withereggs/WitherEggs.java)

**Comment by Shadows-of-Fire** [comment]
yeah looks like there's finally a util method to get the egg by the id, i'll move it over.
