### ISSUE TITLE
Chronicle of Shadows - can it be disabled on startup?

### ISSUE THREAD

**Issue by b12arr0** [Shadows-of-Fire/Apotheosis#535]
On 1.18.1, I'd like to disable the guide book until the player crafts it.  Is there a way to disable it on startup?

**Comment by Shadows-of-Fire** [comment]
You have to override the advancement that is granting it.
I'll add a config eventually

**Comment by Jegethy** [comment]
> You have to override the advancement that is granting it. I'll add a config eventually

How can we override it?

**Comment by Shadows-of-Fire** [comment]
3b01eb3
