### ISSUE TITLE
Lot of stuff missing.

### ISSUE THREAD

**Issue by Solverbolt** [Shadows-of-Fire/Apotheosis#537]
According to your wiki, there is supposed to be a number of items or blocks that can be crafted.

Currently on ATM 7 .44 and cannot craft even half of the stuff from your mod.  Altar of the Sea, all the unique arrows, even some of the special bookshelves are uncraftable. There is no recipe in the JEI for it.

**Comment by Shadows-of-Fire** [comment]
A) I do not have a wiki
B) Most if not all of the content of apotheosis can be disabled by the config file
C) See the in-game documentation book "Chronicle of Shadows" for what content is enabled.
