### ISSUE TITLE
Potion of Ancient Knowledge has wrong recipe

### ISSUE THREAD

**Issue by dwentz89** [Shadows-of-Fire/Apotheosis#538]
Reproduced on version 1.18.1-5.3.3.

The brewing recipe for enhancing a Potion of Ancient Knowledge I into a Potion of Ancient Knowledge II requires another Bottle o' Enchanting. It should require a Glowstone Dust like all the other enhancing recipes.

**Comment by Shadows-of-Fire** [comment]
This is not a bug, that is the intended recipe.

**Comment by dwentz89** [comment]
Why is this recipe supposed to be different from all the others? That doesn't make any sense to me.
