### ISSUE TITLE
Boss Names Showing through Terrain

### ISSUE THREAD

**Issue by slave2midna** [Shadows-of-Fire/Apotheosis#539]
Not sure if this is a conflict, or what's happening - but for some reason you can see boss names below the surface of the ground. Is there a way to disable boss names from showing over boss heads?

MC 1.16.5
Forge: 36.2.30
Optifine: HD U G8

**Comment by Shadows-of-Fire** [comment]
No, boss names are just standard vanilla entity names, they are not an apotheosis-specific system.  You'll need to address this issue with whatever is messing up the depth test (probably optifine).

**Comment by slave2midna** [comment]
Thank you for the quick response! Still an amazing mod - and I'll keep testing it and find out the culprit, starting with Optifine as I know that can sometimes being a jerk - I never noticed it or had an issue with it until recently. I just wanted to be sure before I started dismantling things. I have names turned off for some other mods that added them so I figured it was doable. My apologies!
