### ISSUE TITLE
Charms of Ore Sight are not working 90% of the time. 

### ISSUE THREAD

**Issue by Solverbolt** [Shadows-of-Fire/Apotheosis#540]
I have nearly all of them in All the Mods 7.  Even infused them with 100 levels of Experience to make them unbreakable. Shows nothing at all. So far, only ones I have managed to get to work are Copper, Lapis, Vibranium, and Aluminum.  All others fail to do anything all, whether I use the Charm or drink the potion. it shows nothing.

**Comment by Shadows-of-Fire** [comment]
You're gonna need to take that up with the potion, this isnt a bug with the charms

**Comment by Solverbolt** [comment]
Well the Charms are your domain, so if they are not working, then its a combination error between both your codes, not his or yours individually.
