### ISSUE TITLE
Incompatibility with Upgraded Netherite [1.18.1]

### ISSUE THREAD

**Issue by Opalie** [Shadows-of-Fire/Apotheosis#542]
Upon trying to upgrade any enchanted netherite item, Apotheosis breaks EU, see opened issue [HERE](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite/issues/46).

**Comment by Shadows-of-Fire** [comment]
Closed source all rights reserved mods are not supported from a compatibility standpoint, you will need them to either provide a fix or ask them to determine what part of my code is breaking their functionality.
