### ISSUE TITLE
Loot chests occasionally containing blank enchanted books.

### ISSUE THREAD

**Issue by Andraez** [Shadows-of-Fire/Apotheosis#543]
https://youtu.be/bAiNfFI4K7s

Chests occasionally contain blank enchanted books.
Mods folder w/ error in video to show possible conflicting mods.

**Comment by Shadows-of-Fire** [comment]
I don't think this is really something I can fix on my end, the enchanted books in the loot pools are added via the vanilla enchant randomly function, which selects a random enchantment from the registry and places it on a book.
