### ISSUE TITLE
Unbalanced Broadhead Arrow

### ISSUE THREAD

**Issue by k1r0s** [Shadows-of-Fire/Apotheosis#544]
Broadhead Arrow are too easy to craft, too cheap, and compared to damage output it does not make sense to craft obsidian arrow at all.

My recomendation is either to reduce the recipe output from 6 to 1 or maybe entirely disable shot damage from broadhead arrow and only do damage through bleeding debuf which is already broken IMHO. 

I can do a PR if you want

**Comment by Shadows-of-Fire** [comment]
I don't view this as a problem.
