### ISSUE TITLE
Missing Recipes?

### ISSUE THREAD

**Issue by ThisIsNotMe1612** [Shadows-of-Fire/Apotheosis#545]
I am currently checking out the situation of mods in 1.18 and have big respect for you already having updated.

That said, I came across the problem that certain Apotheosis items don't seem to have a recipe. I first suspected a mod conflict, so i verified with a fresh profile and the problem persisted. It is entirely possible i just missed somthing and this is some kind of new progression thing, but i am completely confused for now.

Problem:
Seemingly missing crafting recipes for several items. Not showing up in JEI and manual application of recipes do not produce output. Noticed on:
- Prismatic Cobweb
- All Tomes
- Hellshelve (normal, blazing and glowing)
- Sea Shelf (normal, crystalline and heart-forged)
- Endshelf (normal, draconic and pearlescent)
- Beeshelf
- Melonshelf
- Enchantment Library

Expected Behavior:
Working crafting recipes

Minecraft and Forge Version:
1.18.2 - 40.0.32

Installed Mods:
Apotheosis 5.3.4
Bookshelf 13.0.7
Enchantment Descriptions 10.0.2
JEI 9.5.5.174
Patchouli 1.18.2-66
Placebo 6.2.0

**Comment by Shadows-of-Fire** [comment]
This is actually a Placebo bug, it looks like a coremod silently failed during porting.  Will be fixed shortly.
