### ISSUE TITLE
Loot dropped by Scavenger not converted by Knowledge of the Ages

### ISSUE THREAD

**Issue by ouroborus** [Shadows-of-Fire/Apotheosis#547]
AllTheMods 6-1.8.19
Apotheosis-1.16.5-4.8.4.jar

If you make a kill with a weapon enchanted with both Scavenger and Knowledge of the Ages, the items dropped by Scavenger (or possibly the original items, I can't tell which set) end up on the ground.

I know the code looks good with Scavenger being processed first, but the reality is different. I'm not sure what's causing this but I suspect it has to do with how [`func_213354_a`](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/ench/EnchModuleEvents.java#L110) works.

A possible work around is to apply Knowledge twice, once before Scavenger and once after Scavenger. Since Knowledge clears the drops list, this shouldn't cause double counts.

**Comment by Shadows-of-Fire** [comment]
Resolved in 4.9.0
