### ISSUE TITLE
[Worker-Main-4/ERROR] [Apotheosis : Enchantment/]

### ISSUE THREAD

**Issue by MrLoLf** [Shadows-of-Fire/Apotheosis#548]
Apotheosis 1.18.2-5.3.4
Forge  40.0.41
Modpack https://github.com/AllTheMods/ATM-7/

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/8458581/latest.log)

When starting the server it throws some errors making some enchantments unavailable (Line 308-311 ;Line 524-527)

**Comment by Shadows-of-Fire** [comment]
These are not errors, these are warnings indicating certain levels of enchantments will not be obtainable in an enchantment table.

**Comment by MrLoLf** [comment]
Thanks for your'r fast reply, could you declare them as WARN with the next update to stop confusion instead of this ERROR.
