### ISSUE TITLE
Several problems after installment of Apotheosis 5.3.4

### ISSUE THREAD

**Issue by TNSGJones** [Shadows-of-Fire/Apotheosis#549]
I have a server running several mods, but after adding apotheosis I noticed a couple of problems that I am unable to reproduce in a singleplayer enviroment. I'm making an issue since I didn't see anything about the Major problem that occurs.

Modversion: 5.3.4
Gameversion: Forge 40.0.40 - Minecraft 1.18.2

Minor problems:
- Recipes requiring bookshelves can't be crafted. They simply don't give the expected crafted item. 

Major problems:
- Consuming a potion crashes the server. Potions still crash the server after disabling the PotionModule. Crashreport description always says "Exception in server tick loop". See provided crashlog. 
[crash-2022-04-14_03.33.56-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/8486162/crash-2022-04-14_03.33.56-server.txt)

I hope I have provided enough information

**Comment by Shadows-of-Fire** [comment]
This has nothing to do with apoth, this error is coming from some mod I presume to be called playdate `Illegal classload request for tech.thatgravyboat.playdate.mixin.ItemAccessor. Mixin is defined in playdate-common.mixins.json and cannot be referenced directly`

**Comment by TNSGJones** [comment]
I see, my apologies for the inconvenience
