### ISSUE TITLE
Server crashing after updating to apotheosis 4.8.999

### ISSUE THREAD

**Issue by TheYoloPanda** [Shadows-of-Fire/Apotheosis#550]
1.16.5 Forge 36.2.33

Apotheosis-1.16.5-4.8.999
Placebo-1.16.5-4.7.0

[crash-2022-04-14_10.16.42-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/8487557/crash-2022-04-14_10.16.42-fml.txt)

After updating from 4.8.4 to 4.8.999 my server keeps crashing, disabling the spawner module fixed the issue but even after creating a new world and enabling the spawner module the server keeps crashing with the same error in the crash report.

**Comment by Pilou26021** [comment]
I confirm this

**Comment by SpokenWig620933** [comment]
I confirm this too

**Comment by Shadows-of-Fire** [comment]
Fixed in 4.8.9999
