### ISSUE TITLE
Can't create Chronicle of Shadows

### ISSUE THREAD

**Issue by Yaseishin** [Shadows-of-Fire/Apotheosis#553]
Hi. On 1.18.2 the Chronicle cannot be crafted according to info given (book + golden ingot). Have I missed anything?
![image](https://user-images.githubusercontent.com/103900083/163728319-9b5c0ab9-da77-4aa0-8ffc-b261cfbd5cd0.png)

**Comment by Shadows-of-Fire** [comment]
Do you have Patchouli installed?

**Comment by Yaseishin** [comment]
No I have not. Thanks for a quick answer. Will give it a try.

**Comment by Yaseishin** [comment]
Missed that. Works. Thanks.
