### ISSUE TITLE
Enchantment tables don't benefit from bookshelves underwater

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#556]
They don't in vanilla either, but it would be a nice feature if enchantment tables could be waterlogged and ignored any fluids that obstructed bookshelves.

**Comment by Shadows-of-Fire** [comment]
Hm, yeah.

I don't *think* I can add waterlogging to the block (existing blocks need to retain the same number of states), but I can probably make the table ignore water.

**Comment by brisingraerowing** [comment]
[Underwater Enchanting](https://www.curseforge.com/minecraft/mc-mods/underwater-enchanting) does exactly this, though I don't know if it works with Apotheosis.

**Comment by Shadows-of-Fire** [comment]
No, from the looks of it having that mod installed alongside apoth would lock the table to a max of 30 levels.

**Comment by ghost** [comment]
I'm sad to see this doesn't work with Underwater Enchanting, I wish I could do enchanting in an underwater base, any chance of this feature being implemented?

**Comment by Shadows-of-Fire** [comment]
This was implemented at some point during 1.18's lifespan.

**Comment by ghost** [comment]
way to comment literally a few months later...
I was playing a 1.16 pack, so that does no good for me.
Not even playing minecraft right now anyway.
