### ISSUE TITLE
Anvils with splitting/obliteration lose their enchants and don't effect the books they're dropped on

### ISSUE THREAD

**Issue by GreyMote** [Shadows-of-Fire/Apotheosis#557]
Enchanted an anvil with splitting, dropped it on a book, the book wasn't effected and the anvil lost all enchants. Happened multiple times.

**Comment by Glowing0v3rlord** [comment]
What Apotheosis version and Minecraft version are you using?

**Comment by Shadows-of-Fire** [comment]
Yeah I believe splitting/obliteration/anvils and whatnot are quite broken on 1.18, I just keep forgetting to look into it.
