### ISSUE TITLE
Cannot Translate patchouli book 

### ISSUE THREAD

**Issue by elementsplayer** [Shadows-of-Fire/Apotheosis#560]
Can you set "i18n": true ? 
location : data\apotheosis\patchouli_books\apoth_chronicle\book.json
So that can translate the book to other language

minecraft version :  1.16.5 
mod version :  Apotheosis-1.16.5-4.8.99C

**Comment by Shadows-of-Fire** [comment]
Hm, I didn't realize that was a thing I needed to do.  I'll change that in the next update.
