### ISSUE TITLE
trying to add affixes to another mods weapons and its only applying some of them

### ISSUE THREAD

**Issue by dawnbraker2** [Shadows-of-Fire/Apotheosis#562]
so i have an ultimate full affixed tome for a sword that i want to use on the zweihander from epic knights weapons and armor it only applys the enchantability effect however when i tried to use a fully built shield tome it put all the effects on it that a shield would have i assume this is because you can use the sword to block i have tried using the deadlycfg to classify the sword as a SWORD but it doesnt work and im pretty sure i did it right too if anyone could help it would be appreciated ill add a bunch of screenshots for context best i can give
![Screenshot (128)](https://user-images.githubusercontent.com/54880462/165442587-b59ee9b4-1087-4034-a79f-7ee85bea2160.png)
![Screenshot (129)](https://user-images.githubusercontent.com/54880462/165442590-684b6038-84f4-4684-9034-d1e1ed9c5c06.png)
![Screenshot (130)](https://user-images.githubusercontent.com/54880462/165442592-5b50b71d-8308-4dcd-abd6-3d2f3d09a474.png)
![Screenshot (131)](https://user-images.githubusercontent.com/54880462/165442595-da2aac0d-3765-4cb9-8c20-d19e1326575f.png)
![deadly](https://user-images.githubusercontent.com/54880462/165442636-895fc545-3494-44dd-b0bb-4de3f7c5f5db.PNG)
o

**Comment by Shadows-of-Fire** [comment]
That is not the correct format for the config, the lists are one entry per line, and no entries on the same line as the braces.

**Comment by dawnbraker2** [comment]
> That is not the correct format for the config, the lists are one entry per line, and no entries on the same line as the braces.
thank you for the quick reply it works now again thank you very much ive been struggling with this for the past 2 hours
