### ISSUE TITLE
Diamond Mining Arrow Block Breaking

### ISSUE THREAD

**Issue by Elfinlocks** [Shadows-of-Fire/Apotheosis#563]
Hi there,

I have run into an issue on the 1.16.5 version of the mod, **4.8.99C**. The Mining Arrows are capable of breaking blocks which are not intended to be breakable, such as the Waystone from Waystones, when the configuration with that mod is set to prevent them from being broken. This has worked on all tools except the mining arrows from this mod. I did not see a configuration to disable them, so I am only able to remove the recipe - they still show up as loot. 

Can a configuration be added to allow full removal of mining arrows?

Thank you!

**Comment by Shadows-of-Fire** [comment]
Full removal of content is not a supported configuration feature.

However, these arrows are not added to any loot pools, so I'm not sure where you would be getting them aside from the recipe.

**Comment by Elfinlocks** [comment]
Hmm, something on my side must be adding them as loot - will dig into this further to confirm something on my side isn't messing with it. Thanks for the info!
