### ISSUE TITLE
Patchouli Format Error

### ISSUE THREAD

**Issue by elementsplayer** [Shadows-of-Fire/Apotheosis#565]
![2022-05-04_09 11 32](https://user-images.githubusercontent.com/104289816/166611915-a760e1ae-73e5-4551-9f14-07a54876dae8.png)
other format error:

- enchanting/enchantments/reflective
- enchanting/enchantments/scavenger
- enchanting/enchantments/spearfihing
- potion/effects/sundering
- potion/recipes/fatigue
- potion/recipes/resistance
- potion/recipes/haste
- village/fletching

**Comment by Shadows-of-Fire** [comment]
Ah, that's not good.  Someone asked me to turn on the I18n option, but I think that had some side effects.  I'll probably just flip it back off.
