### ISSUE TITLE
Mob Spawner not spawning mobs.

### ISSUE THREAD

**Issue by darkspyro92** [Shadows-of-Fire/Apotheosis#568]
![image](https://user-images.githubusercontent.com/22324730/168458926-ce1cb6d2-47cc-470f-92e7-aa3317290ee2.png)
![image](https://user-images.githubusercontent.com/22324730/168458942-1084f868-e42e-47b3-be00-b3bb574a097b.png)

I set up a mob spawner in a Void Dimension from Just Another Void Dimension. Waited about 10 minutes and nothing has spawned yet. I put some modifications on it like redstone control, but it still hasn't spawned anything yet.

I'm on TNP Limitless 5.

**Comment by Shadows-of-Fire** [comment]
Is it spinning?  Redstone control requires a signal be applied to the block or it will not tick (indicated by spinning or not).  I'm not sure if that lever is on/off or if a signal from that spot will even be applied to the spawner

**Comment by darkspyro92** [comment]
> Is it spinning? Redstone control requires a signal be applied to the block or it will not tick (indicated by spinning or not). I'm not sure if that lever is on/off or if a signal from that spot will even be applied to the spawner

It is spinning, yes. The redstone signal is on.

**Comment by Shadows-of-Fire** [comment]
Try throwing ignore conditions on it and see if that works.  I think wither skeletons either have a requirement of spawning in a nether biome or on nether brick blocks.

**Comment by darkspyro92** [comment]
> Try throwing ignore conditions on it and see if that works. I think wither skeletons either have a requirement of spawning in a nether biome or on nether brick blocks.

I don't have a dragon egg yet, and I'm worried about using up the dragon egg. Not sure how to get more yet besides the dragon.

**Comment by Nyntex** [comment]
I feel like i had the same issue with 1.18.1 + 2. Try placing the spawner in the air and see if that helps. That fixed it for me.

**Comment by darkspyro92** [comment]
I'm remodeling my base area, so I'll check when I finish that. Thanks for
the tip.
