### ISSUE TITLE
1.12.2 Broken enchants on the boss monsters.

### ISSUE THREAD

**Issue by SpGilbert** [Shadows-of-Fire/Apotheosis#57]
I have noticed that the boss monsters have like 10 enchants for me and 1/2 of them are over there enchant cap such as protection. I have gotten protection 6 at least once now protection 5 several times which are extremely common perhaps because of how many enchants I have in my game from other mods. This is in version 1.12.2 I would appreciate a small fix if possible.

**Comment by LemADEC** [comment]
You can already restrict the max level per enchantment in the configuration file, or did I miss something?

**Comment by SpGilbert** [comment]
you can do but still, you can't stop them from having like 10 enchants on a piece of gear.

**Comment by Shadows-of-Fire** [comment]
not a bug

**Comment by SpGilbert** [comment]
ok
