### ISSUE TITLE
Spawner causes crash

### ISSUE THREAD

**Issue by gxpKyle** [Shadows-of-Fire/Apotheosis#570]
max sugar
48 clocks
a few prismarine
but what made it crash was the chorus fruit. they just star spawning and i guess i can't kill them fast enough

[crash-2022-05-19_16.06.20-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/8734072/crash-2022-05-19_16.06.20-server.txt)

**Comment by Shadows-of-Fire** [comment]
This crash is unrelated to spawners, so you likely have other issues.

**Comment by gxpKyle** [comment]
Sorry if this re-opens the thread, but it only crashed after i put the chorus fruit. I get its not the spawner itself causing the crash, but the zombies are causing the game to crash, do you know what caused it or how i can find it?
