### ISSUE TITLE
Changing the enchantment level: Is it possible?

### ISSUE THREAD

**Issue by DrakeAlbum** [Shadows-of-Fire/Apotheosis#571]
why do the spells disappear by increasing the levels in the configs?
I change their minimum and maximum level in the configs for some enchantments (yes, increasing them at times), and in the game when I try to enchant in the table, these charms simply disappear, or rather the table does not give me these charms. Is this normal or not? By the way, the level I enter is in the range 1-127, (for example, the minimum level of some charms was 10, and the maximum was 30, 40, 50 or 80). I put 0 on some charms, but they are still charmed, although only the 1st level
Version 1.15.2

**Comment by Shadows-of-Fire** [comment]
I don't really know what it is that you're asking, but 1.15 is not supported.
