### ISSUE TITLE
Affix creation

### ISSUE THREAD

**Issue by Cricket1239** [Shadows-of-Fire/Apotheosis#575]
I'm very sorry if this has been asked before and I'll show support on your Patreon to give my thanks for your support if it was. 

But is there a method that would allow affixes to be created via commands or some other process? 
For context, my server crashed due to a memory issue and I lost a few items with good affixes that I quite frankly do not at all remember where I obtained them. 

Thanks for creating such a cool mod!

**Comment by Shadows-of-Fire** [comment]
It's been asked various times, but still no such system exists.

The "best" thing you can do is either write the raw nbt yourself, pull your playerdata from a backup to retrieve the item, or generate a lot of affix items via /affixloot and use tomes to recreate the item.
