### ISSUE TITLE
Spawner stats resseting

### ISSUE THREAD

**Issue by Sonymans** [Shadows-of-Fire/Apotheosis#576]
whenever i put sugar into a spawner and the MIN spawn delay goes lower it resets to 200 after i move far away and come back.
i've tried restarting the server and other items like clocks but neither helped and it still resets all stats

**Comment by Ernb4s** [comment]
for me too... the spawn values are still the same but the no ai always resets

**Comment by Shadows-of-Fire** [comment]
mod version?

**Comment by Sonymans** [comment]
> mod version?

5.3.5

**Comment by Ernb4s** [comment]
Oh im sry im on the wrong github... im playing with the port to fabric...

**Comment by Sonymans** [comment]
Did I do something wrong or is it a bug?
