### ISSUE TITLE
Conflicts with Enchanting Infuser 

### ISSUE THREAD

**Issue by Azzmikaelson** [Shadows-of-Fire/Apotheosis#577]
When I open the enchanting table infuser, It doesn't show all the enchantments and once I put the item closing the menu. It won't let me open the menu again unless I break it.

**Comment by Shadows-of-Fire** [comment]
What is an enchanting infuser

**Comment by Azzmikaelson** [comment]
Another mod.

**Comment by Shadows-of-Fire** [comment]
Then you need to report it to that mod.  They mention they should be compatible with apotheosis, and apotheosis hasn't changed much at all recently.
