### ISSUE TITLE
Suggestion: Item to reduce spawn distance

### ISSUE THREAD

**Issue by darkspyro92** [Shadows-of-Fire/Apotheosis#579]
I think it'd be useful to be able to put an item in a spawner to reduce the distance that enemies spawn. That way you can reduce it to just them spawning on the block itself, so you can reduce the size of your mob farm. Such as doing something like this:

![image](https://user-images.githubusercontent.com/22324730/172068793-17340d11-2826-4aab-96e7-90a9b4bd71fb.png)

By reducing it, you can "sort" your spawns to be specific to that area and kill them in different ways in a much more reduced area, allowing for more area to build other things.

**Comment by Shadows-of-Fire** [comment]
That already exists, its the modifier that reduces spawn range.

**Comment by darkspyro92** [comment]
> That already exists, its the modifier that reduces spawn range.

Which one is that? I didn't see that in the options. I have a quest log and reducing spawn range isn't in the quests. What item do I use?

**Comment by darkspyro92** [comment]
Blaze Rod and Nether Quartz?

**Comment by darkspyro92** [comment]
Holy crap. I had no idea it could be used like that. I thought it was to reverse modifications you made to it.
