### ISSUE TITLE
Request - Config to blacklist & whitelist items and/or enchantments for specified enchantments

### ISSUE THREAD

**Issue by Fireztonez** [Shadows-of-Fire/Apotheosis#58]
Hello,
I frequently fond somes items can by example be enchant with mending or other enchants by example, but I don't want to be enchantable with that enchantments in my modpack. So I want to be able to configure an override for the enchantability of that item with that specified enchantment.

Other thing I can see sometimes, somes modded enchantments is incompatible with other modded enchants, and I want to remove the possibility to get both enchantments in the same item.

Other things I want to be able, is to add, for my modpack is a compatibility for somes enchantments to be on the same item (By example, Protection and Projectile Protection can probably goes on the same pieces of armor without having any real issue...). So I want to be able to override that vanilla limit..

Thank's for your amazing work with that mod, I really like it!!
Fireztonez

**Comment by Shadows-of-Fire** [comment]
I do not want to implement this level of control
