### ISSUE TITLE
[Suggestion] add compatibility with the "Ensorcellation" mod

### ISSUE THREAD

**Issue by Dyshonored** [Shadows-of-Fire/Apotheosis#580]
I installed both Ensorcellation (this mod https://www.curseforge.com/minecraft/mc-mods/ensorcellation) and Apotheosis mods on my modpack and found out that armour items are no longer able to accept both the generic protection and another specialised form of protection at the same time (e.g. say, protection II and projectile protection IV).

I am running minecraft forge 40.1.21 for minecraft version 1.18.2, with the latest version for both mods

In addition, power V enchantments act like power X enchantments on bows if I have both of the mods installed even if I set the maximum enchantment level for power to V in the configuration of Apotheosis.

**Comment by Shadows-of-Fire** [comment]
On policy I do not offer direct support for ARR mods.

Regardless of that, the changes ensorc makes to vanilla enchantments are simply incompatible with the changes apoth makes.  If you want apoth's changes, you may need to see if ensorc's can be disabled, or ask them to add a way to disable them.
