### ISSUE TITLE
`suggestion` denote adding and removing spawner modifiers differently

### ISSUE THREAD

**Issue by Quezler** [Shadows-of-Fire/Apotheosis#581]
It has confused several enigmatica 6 players thus far (https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4952 & https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4980), whilst the `+` feels fairly obvious the `-` could look like a list.

Maybe it would be a good idea to color [them](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.16/src/main/java/shadows/apotheosis/spawn/compat/SpawnerCategory.java#L117-L119) green and red respectively? One of the players confused by it suggested using the text version of both but there might not be enough room, i don't have any concrete ideas but it was worth sharing.

**Comment by atlgeek007** [comment]
Yeah I personally would change + and - to "adds" and "removes" respectively, rather than using plus or minus, but Quezler is right that may not display correctly.

**Comment by Shadows-of-Fire** [comment]
Adds and Removes end up being too long to fit for some cases.  Might be well-to-do with some coloring, but people might get a bit confused (i.e. + spawn delay tends to be bad, but if all "+" are green, confusion).

This UI is quite tricky to get right.

**Comment by Shadows-of-Fire** [comment]
Experimenting with it, I cannot comfortably use a color because it starts to implicitly convey "good vs bad" and some things (like reducing spawner delays) are "good" while moving a number down.

I think I'll just leave it as-is.
