### ISSUE TITLE
Arclight server crash

### ISSUE THREAD

**Issue by skniro** [Shadows-of-Fire/Apotheosis#585]
Apotheosis: 5.3.5
Minecraft: 1.18.2
Forge: 40.1.31
Arclight:1.18.2-1.0.5-SNAPSHOT 
[log.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/8938379/log.txt)
:

**Comment by Shadows-of-Fire** [comment]
dunno what arclight is, but forge is the only supported platform.
