### ISSUE TITLE
Cleave

### ISSUE THREAD

**Issue by INooBTooMuch** [Shadows-of-Fire/Apotheosis#588]
The cleave affix attacks neutral mobs, most importantly villagers.
Minecraft version 1.16.5 and Apotheosis 4.8.99F

(Also in case the updates for 1.16.5 have stopped this could also maybe pass on to the other version when the deadly module gets added)

**Comment by Shadows-of-Fire** [comment]
Fixed in 1.18

**Comment by Shadows-of-Fire** [comment]
(1.18.2) Cleave will no longer hit villagers or animals unless the primary target was one.
