### ISSUE TITLE
Unrecognized recipes unload everyone single time a player loads into the game

### ISSUE THREAD

**Issue by Bidgam** [Shadows-of-Fire/Apotheosis#590]
Minecraft: 1.18.2
Forge: 40.1.27
Apotheosis: 1.18.2-5.3.6

Upon a player loading, the server reports: "Tried to load unrecognized recipe: apotheosis: (recipe here) removed now. for at least a couple of dozens recipes.

The player sees these recipes being recognized upon loading into the game.

Same one, every time they load in.

Thanks for taking a look!

**Comment by Shadows-of-Fire** [comment]
Fixed in more recent versions with the recipe type registration, I think

**Comment by Bidgam** [comment]
Thanks for taking a look! More recent versions? There aren't any more recent, 5.3.6 seems to still be the latest on the Curseforge page.

**Comment by Bidgam** [comment]
I just updated to the latest 1.18.2 Forge version, and unfortunately it still does it :(.

Is there a way to at least turn off the notification for the mod on the client side? Just this mod, since it's not working right.

Thanks

**Comment by Shadows-of-Fire** [comment]
What version of placebo are you using?

**Comment by Bidgam** [comment]
The latest, Placebo-1.18.2-6.4.2.jar

**Comment by Shadows-of-Fire** [comment]
Bizzare.  If that registration didn't fix it I'm not sure what could be causing it - since that log message should only occur if the recipes don't exist, though you mention they still work fine in-game.  

I might just mixin and shut up the error logging if it's being erroneous.

**Comment by Bidgam** [comment]
I did install Toast Control this morning which by default doesn't show on the client side any recipes. Still shows it in the server logs of course, but as long as you don't see a side effect of it continuing, no big deal here then.

**Comment by LunarDev-git** [comment]
Yeah I still have this issue in the console. 

MC Version: 1.18.2 
Forge: 40.1.80

Apotheosis: 5.6.1
Placebo: 6.6.4

![image](https://user-images.githubusercontent.com/105180230/190141993-76671614-e61c-4dca-a88d-6c9a06268691.png)

**Comment by Shadows-of-Fire** [comment]
Fixed in Placebo 6.6.5

**Comment by Maypul** [comment]
Hi there, I also still seem to be having this issue: https://prnt.sc/-Mdv1KsQjJDg
1.19.2, Placebo 7.1.2, Apotheosis 6.0.3.
Interesingly enough, it does not seem to happen when using only Forge + these two mods.

**Comment by Grishord** [comment]
Having same issue, same versions as Maypul
