### ISSUE TITLE
Sword taking increased durability damage when using a Shield Bash enchanted shield in offhand.

### ISSUE THREAD

**Issue by MERCDawn** [Shadows-of-Fire/Apotheosis#591]
Minecraft: 1.18.2
Forge: 40.1.31
Apotheosis: 1.18.2-5.3.6

When using a shield enchanted with "Shield Bash" in your offhand, and using a sword in your mainhand, swinging the sword causes 18 points of durability damage rather than the intended 1 point. This should only happen when attacking with the shield specifically.

No benefit is gained from having a Shield Bash shield in your offhand (as expected, you are not attacking with the shield after all), however you still experience the increased durability usage as if you were using the shield to attack even when you are actively using a sword.

**Comment by Eziogamn** [comment]
Thankyou!!!
I have been trying to find out what has been evaporating my swords!

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.4.0
