### ISSUE TITLE
[Suggestion]Add a config option to let the explosive arrows not explode on blocks

### ISSUE THREAD

**Issue by tankyap** [Shadows-of-Fire/Apotheosis#593]
It would be great if this mod can turn on/off the config on what the title says, because it would be quite annoying fill the holes, it just take some of my spare times to fill it.
(And can you also let this mod compatible with the [ProjectE](https://www.curseforge.com/minecraft/mc-mods/projecte) mod so that all of the items from this mod can transmute from the transmutation table?

**Comment by tankyap** [comment]
> It would be great if this mod can turn on/off the config on what the title says, because it would be quite annoying fill the holes, it just take some of my spare times to fill it.

(And can you also let this mod compatible with the [ProjectE](https://www.curseforge.com/minecraft/mc-mods/projecte) mod so that all of the items from this mod can transmute from the transmutation table?

**Comment by tankyap** [comment]
> It would be great if this mod can turn on/off the config on what the title says, because it would be quite annoying fill the holes, it just take some of my spare times to fill it.

(And can you also let this mod compatible with the [ProjectE](https://www.curseforge.com/minecraft/mc-mods/projecte) mod so that all of the items from this mod can transmute from the transmutation table?)

**Comment by Shadows-of-Fire** [comment]
added in 5.4.2 (not the projecte stuff, not gonna bother with that)
