### ISSUE TITLE
[1.16.5] Blazes aren't spawning.

### ISSUE THREAD

**Issue by SpokenWig620933** [Shadows-of-Fire/Apotheosis#594]
I'm using my own custom modpack.
When I set my blaze spawner to ignore players, it stopped spawning completely(waited several minutes).
Once I added a dragon egg though it was able to spawn again.

The spawner shouldn't require a dragon egg & a nether star just to ignore players.

![2022-07-06_01 28 20](https://user-images.githubusercontent.com/49125888/177475432-04dde60f-f393-44a7-bec8-dfc1620e906e.png)
![2022-07-06_01 28 25](https://user-images.githubusercontent.com/49125888/177475436-9f2617d5-05c3-4dc7-a7c8-c40ae4c34b75.png)

**Comment by SpokenWig620933** [comment]
Any updates on this?

**Comment by Shadows-of-Fire** [comment]
1.16.5 is out of development.

That said, I don't know why it would require a player.  Might be something to do with blaze spawn conditions?

Its possible your spawn range of 1 yields no valid spaces, and thus you need the ignore conditions.

**Comment by SpokenWig620933** [comment]
It worked just fine before I put in the nether star, there is a single location it can spawn, but after I put the star it stopped until I tried a dragon egg to ignore all conditions.

**Comment by SpokenWig620933** [comment]
And since when was 1.16 out of dev? I sent this just a couple days after an update on 1.16...

**Comment by Shadows-of-Fire** [comment]
Since forge declared 1.16.5 to be out of LTS.  You opened this issue more than a month after the last 1.16 release, as well.
