### ISSUE TITLE
crash caused by an Invalid Java Runtime Configuration when Apotheosis is installed

### ISSUE THREAD

**Issue by RandomGuy91** [Shadows-of-Fire/Apotheosis#595]
I am making a modpack and I was gonna add apotheosis to see what it was like, but when I tried to start Minecraft it said that an unexpected issue occurred and it could be caused by an Invalid Java Runtime Configuration. I have both Placebo and Patchouli installed and have not messed with the config files at all. This is with the 1.16.5 version downloaded from the Curseforge app, and does not happen when I uninstall Apotheosis. There is also no crash log. Any help would be appreciated! :)

**Comment by RandomGuy91** [comment]
This is for @Shadows-of-Fire btw

**Comment by RandomGuy91** [comment]
Here is a list of the mods as well  :) I 

https://pastebin.com/wAMu75hV

**Comment by Shadows-of-Fire** [comment]
A debug.log or similar is required

**Comment by RandomGuy91** [comment]
How would I find that? There was no crash report for it...

**Edit:** Wait, here is my latest debug log (too big for pastebin)  https://controlc.com/06a51cc8
