### ISSUE TITLE
[1.18.2] Random Crash shortly after joining World (only with the enchantment module disabled)

### ISSUE THREAD

**Issue by DerCommander323** [Shadows-of-Fire/Apotheosis#596]
After disabling the enchantment module in the config, it seems that after a short amount of time (~30 seconds?) after joining a world the game just crashes. The log seems to mention something about Apotheosis and a bit of Sophisticated Backpacks?

log: https://mclo.gs/4QKj4tg

Versions:
Minecraft 1.18.2
Forge 40.1.59
Apotheosis 1.18.2-5.3.6

**Comment by Shadows-of-Fire** [comment]
Yeah it's currently broken, you can rollback to the previous version of placebo/apoth and it'll stop

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.4.0
