### ISSUE TITLE
[Possible Enhancement Idea] Enchantment Applicable toggle button in Enchantment Libraries

### ISSUE THREAD

**Issue by collosiskdway** [Shadows-of-Fire/Apotheosis#599]
Simply put it would be nice to be able to select what item category of enchantments will display in the Libraries when looking through them. This could be done by having the icons for various items in the top right section of the Library interface which can be clicked to dissable/enable the enchantments displaying for that specific item.

Example: After opening the Library UI, you select the pickaxe icon in the top right section of the interface. This causes all enchantments that specifically would be aplicable to a pickaxe to become hidden within the UI so as to make it easier to sort through the various available enchantments. This example assumes that all enchantment categories are enabled by default.

-I'll try to make a rough visual of this soon and add that here so that my thoughts on the matter can be easier to understand.-

**Comment by Shadows-of-Fire** [comment]
The 1.18 version already has applicable filters, I don't really think additional ones are necessary.

**Comment by collosiskdway** [comment]
I appologize for the delay. The specific menu i am refering to is the one that displays when you open an enchantment library. my suggestion is roughly drawn out on the attached image. 


![example filter menu](https://user-images.githubusercontent.com/46036025/182012351-a5b35644-a43d-4bb2-9670-afd0a9a21ed8.png)

**Comment by Shadows-of-Fire** [comment]
I know, the current iteration of that menu looks like this, with a by-name filter and a by-item filter:  
1.16.5 is not being developed anymore.
 ![](https://i.imgur.com/N2FQz6C.png)

**Comment by collosiskdway** [comment]
ah i see that i must not have gotten my hands on the latest version then. that makes sense. thank you for dealing with my stupidity XD
