### ISSUE TITLE
[Bug] Seashelf crafting recipe not working

### ISSUE THREAD

**Issue by Smittlord** [Shadows-of-Fire/Apotheosis#600]
![image](https://user-images.githubusercontent.com/76596031/179410533-eafd806b-92f4-4741-8045-516527885342.png)
Hi, Me and a friend made a custom modpack using Apotheosis called Eldritch Machinizations 2 and I have just discovered the seashelf crafting recipe is broken. The mod version we use is: apotheosis-0.2.81.jar. We run this on the Fabric API if that makes any difference.

**Comment by Shadows-of-Fire** [comment]
There is no fabric version of apotheosis.
