### ISSUE TITLE
Crash when moving item into library that has infusion enchantment

### ISSUE THREAD

**Issue by kackalack** [Shadows-of-Fire/Apotheosis#601]
A client crash occurs when a player moves an item into a library that contains the infusion enchantment. 
https://crashy.net/oQzYex0BzIxWgYhZUoe4?raw

**Comment by Shadows-of-Fire** [comment]
And how did you obtain the Infusion enchantment?  It is not a "real" enchantment and not supported for any uses whatsoever.

**Comment by kackalack** [comment]
We had it on a book somehow, not entirely sure how we got it to began with.

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.4.0
