### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by BananaSniper** [Shadows-of-Fire/Apotheosis#603]
In the mod 'Upgraded Netherite' the netherite Crossbows are unaffected by the Crescendo Enchantment and they only load one arrow! 

Apotheosis Version 1.18.2-5.3.6

**Comment by Shadows-of-Fire** [comment]
Closed Source / ARR mods are not supported.

All crossbow hooks are implemented using this mixin: https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/mixin/CrossbowItemMixin.java
If this isn't working, it means they aren't using the vanilla crossbow class, and there's not much I can do anyway.

**Comment by BananaSniper** [comment]
Thanks! I made sure to leave a bug report for them so hopefully they will fix it, the crossbow makes the animation but doesn't actually gain any arrows. Anyway I appreciate you responding!
