### ISSUE TITLE
[1.18.2 Issue] Crescendo of Bolts breaks with Enigmatic Legacy's enchantments

### ISSUE THREAD

**Issue by Graxum** [Shadows-of-Fire/Apotheosis#605]
the crescendo of bolts enchantment breaks enigmatic legacy's sharpshooter enchantment. It doesnt break with multishot or piercing though. The sharpshooter enchant is mutually exclusive with piercing and multishot and those two work just fine.

It breaks with Ceaseless as well (basically infinity for crossbows in enigmatic legacy)

**Comment by Shadows-of-Fire** [comment]
What does sharpshooter do?

**Comment by Graxum** [comment]
> What does sharpshooter do?

it increases the damage and accuracy of the crossbow, mutually exclusive with piercing and multishot.

https://user-images.githubusercontent.com/106605348/181918742-47b6b989-edc5-4719-a930-f4a4ac0d58bc.mp4

**Comment by Shadows-of-Fire** [comment]
So... just a quick glance at EL's license and I don't really want to attempt any sort of compatibility with it.  You can ask them to fix it, I guess.  

All I'm doing is replacing the projectile in the crossbow's nbt after it fires until it fires x number of shots, I'm not sure how that could possibly cause issues with enchantments that (should) only be hooking on arrow fire.
