### ISSUE TITLE
Health Boost Potion Charm constantly resets health. 

### ISSUE THREAD

**Issue by 4AC11** [Shadows-of-Fire/Apotheosis#606]
The Health Boost Potion Charm grants the effect for long enough that you will _technically_ always have the extra hearts, but because the effect is applied again an instant after it dissipates, the player takes damage every time it refreshes, resetting the extra hearts and effectively just making what would be a very useful charm into an _active detriment to wear_, as it just drains hunger to regenerate and then remove the same two hearts repeatedly. 

If this is intended / the charm is meant to be useless, why even have the charm as an option at all for someone to craft only to be disappointed?

**Comment by 4AC11** [comment]
A possible solution could be for potion charms to apply their effect for just a second longer than technically necessary, so that, like a Beacon, the effect refreshes before it runs out.

**Comment by Shadows-of-Fire** [comment]
is that even a vanilla effect?  Charms are dynamically generated for everything, I can't magically know what needs special handling

**Comment by 4AC11** [comment]
It seems that the potion was from another mod, I apologize for assuming that apotheosis added it. 

Still, it _is_ a vanilla effect, just not one normally accessible in Survival. I've seen it added as a potion in other mods besides the one I'm currently using as well, so it would make sense for Apotheosis to support a vanilla buff, even if it normally isnt available as a potion.

**Comment by 4AC11** [comment]
(the wiki page for the vanilla buff) https://minecraft.fandom.com/wiki/Health_Boost

**Comment by Shadows-of-Fire** [comment]
`Health Boost is an unused status effect` so it's... not available normally, which means a mod is making it available.  A charm would only be generated for it if a craftable potion exists for it

Anyhow I can just give it the same treatment as night vision, I suppose.

**Comment by 4AC11** [comment]
Sounds good to me.

**Comment by Shadows-of-Fire** [comment]
Will be added in 5.4.0

**Comment by 4AC11** [comment]
Re-opening this a while after the update. Though its not an immediate issue for me anymore, it seems that extending the time for the effect doesn't resolve the problem. It seems that, even if there is extra time left, re-applying the effect still causes the health to reset and take up saturation to refresh.

After messing around with the Effect Give command, it seems like this might just be a vanilla issue with re-applying health boost when a player already has it. :( 

Not sure if it's possible to fix this, but I figured I'd at least reopen this issue in case others have the same problem in their modpacks. 

edit - just realized i dont have the permissions to open the issue again, lol
