### ISSUE TITLE
[1.18.2] I am missing affix tomes / shards and gear in my world

### ISSUE THREAD

**Issue by focusfail** [Shadows-of-Fire/Apotheosis#609]
Hello! Did the affix system get changed or something? In my 1.18,2 world i can't see the affix tomes or shards in JEI.  And when I compared my 1.12.2 config file with the 1.18.2 file there was a few files missing in the latter (files missing: affixes, deadly, names)
If anyone has an idea my those are missing or how the new system works (if there is one), I'd appreciate if you let me know.

**Comment by HockeyZman2000** [comment]
If I recall the Deadly Module that adds all of the stuff having to do with affixes hasn't been added yet in the 1.18.2 version. Hopefully the mod author is still either working on it or planning to! I've personally been waiting on it for a little while

**Comment by Shadows-of-Fire** [comment]
That content is not yet part of 1.18.
