### ISSUE TITLE
Cannot run, the server cannot be turned on

### ISSUE THREAD

**Issue by 1233Ao** [Shadows-of-Fire/Apotheosis#610]
server core is Arclight-forge-1.18.2-1.0.6
Java is jdk-17.0.4_windows-x64
The following is the error log
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9274822/latest.log)
（I'm using Microsoft Translator and there may be some grammatical errors）

**Comment by 1233Ao** [comment]
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9274838/latest.log)
There was a bit of a problem with the previous logs, which are up to date

**Comment by Shadows-of-Fire** [comment]
nonstandard server software is unsupported
