### ISSUE TITLE
[1.18.2] "Apotheosis encountered an error during the common_setup event phase"

### ISSUE THREAD

**Issue by Pokedudeawesome1** [Shadows-of-Fire/Apotheosis#612]
Apotheosis Failed to load during common setup, and I'm not sure what mod is causing this or how to fix it. This is also my first time using this mod.

Crash Report
[crash-2022-08-08_11.08.10-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9282962/crash-2022-08-08_11.08.10-fml.txt)

Log
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9282919/latest.log)

**Comment by Shadows-of-Fire** [comment]
That crash report points to quark, or more specifically it looks like either AutoRegLib is missing or a wrong version, or some other mod is breaking it with a mixin/coremod.

Nothing to do with apoth though.
