### ISSUE TITLE
Slime not spawning

### ISSUE THREAD

**Issue by smilodon79** [Shadows-of-Fire/Apotheosis#614]
I tried spawning Slime, Maze Slime (from Twilight Forest), Skyslime and Enderslime (from Tinker's Construct) and none of them spawn.

Every other entity tested worked properly (tested zombie, skeleton, spiders, cave spiders, creepers, guardian, elder guardian, passive mobs like cows, rabbits, pigs, etc., modded mobs like blitz, blizz, etc.

Spawner is fully maxed out with the following additional flags:
No AI
Ignores Players
Ignores Conditions
Redstone Control (Redstone was on when tested)
Ignores Light
Spawn Range:  6

Game Details:
Version:  Apotheosis-1.16.5-4.8.99F
Minecraft Version:  1.16.5
Tested Biomes:  Plains, Desert, Savanna, **Swamp**
Area available to spawn:  9x9

Appreciate your attention and fix for this issue please.

**Comment by Shadows-of-Fire** [comment]
Once you have ignore conditions applied, it means no checks are being done before the slimes are spawned.  However, external factors can still cause the slime spawn to be blocked, but there's nothing I can do about it.
Slime spawners have been tested and are verified to work, so you do have something external blocking them from working.
Finally, 1.16 is out of support, so no more releases will be published.
