### ISSUE TITLE
crash with "All the Mods 7"

### ISSUE THREAD

**Issue by 5stigma** [Shadows-of-Fire/Apotheosis#617]
crash with "All the Mods 7"

It doesn't open the client at all

**Comment by Shadows-of-Fire** [comment]
crash reports are required for crash issues.

**Comment by 5stigma** [comment]
It didn't provide any crash log, it is just that the launcher tried to open the game but to no avail.

I just can say that I was using the modpack mentioned above along with Rubidium (Sodium) & addons, Radium reforged (Lithium) and  Radon (Phosphor).

**Comment by Shadows-of-Fire** [comment]
Without a crash log such an issue cannot be diagnosed.  You should probably just wait until the ATM7 pack updates to that version manually.

**Comment by 5stigma** [comment]
Cause: Radium reforged
