### ISSUE TITLE
Odd behaviour when toggling enchantment module (and adding/removing mod?)

### ISSUE THREAD

**Issue by CheshireSwift** [Shadows-of-Fire/Apotheosis#62]
Not sure if this is Apotheosis specific or something fundamental in MC/Forge, but when turning the enchantment module on/off in the config, it looks like enchantment IDs get misaligned?

Steps:
1. Have enchantment module disabled.
2. Create a new world.
3. Quit, enable enchantment module, re-run MC.
4. Giggle at bookshelves with Capturing X.

![image](https://user-images.githubusercontent.com/4071936/61584130-a703ae80-ab3a-11e9-8527-5d15d3c82d4c.png)

It's not just the shelves, it also similarly messes up enchanted books, including those from other mods. I first noticed it when searching for Veining enchanted books in JEI returned books with Spartan Weaponry enchants.

Creating a fresh world once the module is toggled is fine, everything is correct in the new save. It's just existing worlds that go wonky.

**Comment by Shadows-of-Fire** [comment]
This is probably due to how vanilla stores enchantments as integers and doesn't remap those integers after the game logs into a world...
Not sure if theres anything I can do about it, as its basically a fundamental flaw in vanilla.

**Comment by CheshireSwift** [comment]
I had a sneaking suspicion that might be the case. It's weird that it's not just existing items, but also JEI and anything created afterwards that's affected, but presumably it stores a mapping of enchantment IDs in the actual world data?

Anyway, no worries and thanks for the quick reply, you can go ahead and close it if you want.

**Comment by Shadows-of-Fire** [comment]
Just as a note if you want the enchantment module functionally disabled you can achiece the same results by adjusting the configs.
