### ISSUE TITLE
Currently Selected Datapacks - Unable to Load/Create Worlds

### ISSUE THREAD

**Issue by dadadadaan** [Shadows-of-Fire/Apotheosis#626]
Currently running on version 1.18.2 - tried multiple combinations of Forge and Apotheosis versions. Getting the below error whenever I load into or attempt to create a world with Apotheosis installed. I have 82 other mods running, but this error only comes up with Apotheosis running.
![image](https://user-images.githubusercontent.com/72238403/185770148-729a5bcc-ef0e-46b4-9edf-ba1f5768769c.png)

Maybe it's an incompatibility issue with another mod? I haven't been able to isolate a single mod to be incompatible with Apotheosis yet, but I've started going down the list and removing some of my mods. No fixes yet.

Full modlist is here, using latest, most stable builds for all.

AI Improvements(QueenOfMissiles)
AppleSkin(squeek502)
Artifacts(ochotonida)
ExpandAbility(florensie)
Curios API (Forge)(TheIllusiveC4)
Oh The Biomes You'll Go(AOCAWOL)
TerraBlender (Forge)(TheAdubbz)
Biomes O' Plenty(Forstride)
Blueprint(TeamAbnormals)
Builder's Delight (Forge)(Tynoxs)
Chicken Chunks 1.8.+(covers1624)
CodeChicken Lib 1.8.+(covers1624)
Configured(MrCrayfish)
Mysterious Mountain Lib(sz0999312)
Farmer's Delight(vectorwing)
Corpse(henkelmax)
Create(simibubi)
Flywheel(jozufozu)
Create Crafts & Additions(MRHminer)
Create Stuff Additions(Furti_Two)
Create Chunkloading(embeddedt)
Cloth Config API (Fabric/Forge)(shedaniel)
Industrialized Create(coppertj)
Architectury API (Fabric/Forge)(shedaniel)
Cultural Delights(NCP_Bails)
Nether's Delight(lumpazl)
Delightful(brdbrn)
Honey Expansion (Add-on for Farmer's Delight)(Spiteful_raccoon)
When Dungeons Arise - Forge!(Aureljz)
Enchantment Descriptions(DarkhaxDev)
Bookshelf(DarkhaxDev)
Neko's Enchanted Books(Nekomaster1000)
Every Compat(MehVahdJukaar)
Moonlight Lib(MehVahdJukaar)
Explorer's Compass(Chaosyr)
Fast Leaf Decay(olafskiii)
FerriteCore (Forge)(malte0811)
Jade Addons (Forge)(Snownee_)
Jade 🔍(Snownee_)
Just Enough Resources (JER)(way2muchnoise)
Just Enough Items (JEI)(mezz)
JourneyMap(techbrew)
Little Logistics(Sveid_)
Little Contraptions(EDToaster)
Magnum Torch(Fuzs_)
Puzzles Lib(Fuzs_)
Macaw's Trapdoors(sketch_macaw)
Macaw's Roofs(sketch_macaw)
Macaw's Fences and Walls(sketch_macaw)
Macaw's Doors(sketch_macaw)
Macaw's Windows(sketch_macaw)
Macaw's Bridges(sketch_macaw)
Nature's Compass(Chaosyr)
Oculus(Asek3)
Rubidium(Asek3)
Iris & Oculus Flywheel Compat(leon_mout)
Patchouli(Vazkii)
Quark(Vazkii)
AutoRegLib(Vazkii)
SuperMartijn642's Config Lib(SuperMartijn642)
SuperMartijn642's Core Lib(SuperMartijn642)
Create Slice & Dice(possible_triangle)
Kotlin for Forge(thedarkcolour)
Snad(TheRoBrit)
Sound Physics Remastered(henkelmax)
Storage Drawers(Texelsaur)
TwitchSpawn(iGoodiex)
Portality(Buuz135)
Titanium(Buuz135)
YUNG's Better Dungeons (Forge)(YUNGNICKYOUNG)
YUNG's API (Forge)(YUNGNICKYOUNG)
YUNG's Better Strongholds (Forge)(YUNGNICKYOUNG)
YUNG's Better Mineshafts (Forge)(YUNGNICKYOUNG)
YUNG's Extras (Forge)(YUNGNICKYOUNG)
YUNG's Bridges (Forge)(YUNGNICKYOUNG)
YUNG's Better Witch Huts (Forge)(YUNGNICKYOUNG)
Placebo(Shadows_of_Fire)
Enhanced Mob Spawners(BR4NDER5)
Just Zoom [Forge](Keksuccino)
Konkrete [Forge](Keksuccino)
Apotheosis(Shadows_of_Fire)

**Comment by Shadows-of-Fire** [comment]
Placebo 6.6.0 is not compatible with the latest apoth,, rollback to 6.5.3

**Comment by dadadadaan** [comment]
That fixed it... Thank you! Is there anywhere that the incompatibilities are for the different Apotheosis versions? My buddies and I love the mod but we play with different versions frequently too

**Comment by Shadows-of-Fire** [comment]
It's really just this version, typically I publish those fixes alongside all corresponding mod updates, but some issues came up blocking release
