### ISSUE TITLE
[1.18.2] Enchanted books don't seem to have any enchantments on them

### ISSUE THREAD

**Issue by tharrmeehan** [Shadows-of-Fire/Apotheosis#627]
Hello, there seems to be an issue with the loot table on my end. My enchanted books all seem to be empty.
I'm only using Apotheosis 5.4.1 and Placebo 6.5.3, no additional mods or datapacks have been added.

Steps to reproduce:
1. Create a new world.
2. Find a chest containing an enchanted book or use the following command till you get one: /loot spawn ~ ~ ~ loot apotheosis:chests/spawner_brutal
3. Enchanted books don't contain any enchantments

Thanks for your help! 👍

**Comment by Shadows-of-Fire** [comment]
Fixed by https://github.com/Shadows-of-Fire/Placebo/commit/86fc1abbcacf97b650869b3cae7444ed2b826fb4
