### ISSUE TITLE
Unable to Start after Updating to 1.18.8-5.5.1 from 1.18.2-5.4.1

### ISSUE THREAD

**Issue by ACrazyD** [Shadows-of-Fire/Apotheosis#628]
I seem to get a mixen related crash that only occurs when I update this mod.

I have tested downgrading the other mods I have and the issue vanished after down porting back to 5.4.1

The issue looks to be with ImmseriveFX - but the issue was gone after downgrading this mod, and ImmersiveFX hadn't updated- so if I need to I can open the report up with them as well.

[crash-2022-08-21_20.36.12-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9391112/crash-2022-08-21_20.36.12-client.txt)
[crash-2022-08-21_20.30.55-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9391113/crash-2022-08-21_20.30.55-client.txt)

**Comment by tharrmeehan** [comment]
Seems to be working perfectly fine for me (newest Apotheosis and ImmersiveFX), have you tried updating Placebo to the newest version aswell?

**Comment by Shadows-of-Fire** [comment]
Those crash reports are coming out of Sound Control, so there doesn't appear to be anything from my end.  The latest builds of everything have been verified to work together many times over.
