### ISSUE TITLE
[1.18.2] Apotheosis and Evlicraft crash, "Can't find attribute apotheosis:current_hp_damage"

### ISSUE THREAD

**Issue by Mitchell5200** [Shadows-of-Fire/Apotheosis#629]
Hi i've got a trio of server crashes from the ATM 7B server, 
pack version 0.4.27
Apotheosis version 1.18.2-5.5.1
Placebo-1.18.2-6.6.1
EvilCraft-1.18.2-1.2.6
Seems to be similar to https://github.com/Shadows-of-Fire/Apotheosis/issues/623

[crash-2022-08-22_10.55.03-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9395758/crash-2022-08-22_10.55.03-server.txt)
[crash-2022-08-22_15.22.37-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9395760/crash-2022-08-22_15.22.37-server.txt)
[crash-2022-08-22_15.39.36-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9395761/crash-2022-08-22_15.39.36-server.txt)

**Comment by Shadows-of-Fire** [comment]
Evilcraft must be doing something weirdly nonstandard with their entity attributes, as I have a handler adding these to all entities.

**Comment by Mitchell5200** [comment]
cross posted to them https://github.com/CyclopsMC/EvilCraft/issues/936

**Comment by rubensworks** [comment]
@Shadows-of-Fire AFAIK EvilCraft is not doing anything special related to attributes (developer here): https://github.com/CyclopsMC/EvilCraft/blob/master-1.19/src/main/java/org/cyclops/evilcraft/entity/monster/EntityVengeanceSpirit.java#L158-L166

Are you sure your handler is considering _all_ entities?

**Comment by Shadows-of-Fire** [comment]
@rubensworks Currently these attributes are applied to all living entities via `EntityAttributeModificationEvent` https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/AdventureModule.java#L179
Previously they were applied via mixin here https://github.com/Shadows-of-Fire/Apotheosis/blob/1e044c2a0937bbd09e187c760e1cc90275aef65c/src/main/java/shadows/apotheosis/mixin/LivingEntityMixin.java#L88

The crash was still present with the mixin, even though the mixin _should_ be more broad, as I figured ALL living entities would be using LivingEntity.createLivingAttributes as their attribute supplier base.

How are your entity attribute suppliers built?

**Comment by rubensworks** [comment]
Your current event handler looks correct to me as well.

I'm using the same event to register attributes: https://github.com/CyclopsMC/EvilCraft/blob/master-1.19/src/main/java/org/cyclops/evilcraft/entity/monster/EntityVengeanceSpiritConfig.java#L81-L99
So the event _does_ work, so the only potential problem I see atm is that my EC's entity types could not present in the [event's `getTypes` result](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/AdventureModule.java#L180) (not sure though).

**Comment by Shadows-of-Fire** [comment]
Potentially.  Since it's a mod bus event - but that wouldn't explain why the mixin variant wouldn't work either.

**Comment by Shadows-of-Fire** [comment]
Oh wait a second!  You aren't supposed to use the modification event for your own entities, You're supposed to use the EntityAttributeCreationEvent, hence why your types aren't showing in this event for me.

**Comment by rubensworks** [comment]
Oohh, I didn't even know about that event. That makes sense, will fix it soon on my end.
Thanks a lot for the help @Shadows-of-Fire ! :-)
