### ISSUE TITLE
[1.18.2] Apotheosis affix weapon not always allowing loot/exp drops

### ISSUE THREAD

**Issue by Ozimundis** [Shadows-of-Fire/Apotheosis#630]
![image](https://user-images.githubusercontent.com/18075273/186021647-60b1431b-b50a-4a15-b58b-3f768febc093.png)

Playing on version 5.5.1, manually added to the DW20 1.18.2 pack, version 1.9.1

Affix sword generated with version 5.4.0 sometimes causes no exp or loot to drop from mob and game does not play death sound. 
Similar to "When an attack deals a fatal amount of damage to a mob, so that it dies while immune, its death sound is not triggered" - from the minecraft wiki.

Is somewhat inconsistant, sometimes allowing loot/exp to drop, othertimes not. 

Easy example of this would be killing magma-slime, no exp is generated and no loot either. 
Video demonstrating this - https://www.youtube.com/watch?v=mFKr4lyg72s

Unsure how to better report or diagnose this issue. 
Non Apotheosis weapons, eg tinkers, allow drops as expected and without issue.

**Comment by Shadows-of-Fire** [comment]
Are you sure you're not just not noticing the teleportation of the drop directly to your inventory?

I can see in your video in the first couple seconds you get a magma cream drop from the slime that you kill.

**Comment by Ozimundis** [comment]
No, that was my thought as well, but I use a different affix sword and have the same result. Only the diamond sword in my video has the "teleport drops to user" ability.

**Comment by Shadows-of-Fire** [comment]
Then I suspect the issue likely lies within the handling for cold damage / fire damage.  I'll have to take a look at those.

**Comment by Ozimundis** [comment]
Just tested with 3 axes and a crossbow, none having an elemental damage - crossbow does "Magic" damage. 
All were allowing mob drops and exp! 
Never occured to me about that.

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.6
