### ISSUE TITLE
[1.18.2] Rendering overlay error since 5.3.6 and newer versions

### ISSUE THREAD

**Issue by Lxazl5770** [Shadows-of-Fire/Apotheosis#631]
The game crashed since I installed Apotheosis 5.3.6 (and newer versions) with a Rendering overlay error. This problem never happens in 5.3.5 and older versions with 1.18.2.

Forge version: 40.1.52 or 40.1.73 (with JDK 17.0.0)
[crash-2022-08-23_17.35.02-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9401416/crash-2022-08-23_17.35.02-client.txt)

**Comment by Shadows-of-Fire** [comment]
This crash report states sound control is the offending mod, apoth is not even in the stacktrace.
