### ISSUE TITLE
[1.18.2] Adventure module: "Announce Boss Spawns"=false doesn't work

### ISSUE THREAD

**Issue by mouseas** [Shadows-of-Fire/Apotheosis#632]
Version: Apotheosis-1.18.2-5.5.1.jar via CurseForge

After updating to the latest version I edited the configuration file for the apotheosis/adventure module to set `Announce Boss Spawns`  to `false`. Even after restarting twice, it still announces nearby boss mobs.

I actually would *like* it to announce boss mobs, but without the deafening sound and while taking y-level into account. Can the sound be a separate setting? Can there be a setting for whether to ignore y level or not?

I also note that the sound is directionless. Previous versions of the Adventure module would use lightning to "announce" a newly-spawned boss, which would give a clue about its location by the sound direction even if you didn't see the lightning flash. Would it be possible to use a sound originating from the spawn location?

**Comment by Faerlinchen** [comment]
Hi I just muted this one here ...  it worked for me :) maybe try this too =)
![grafik](https://user-images.githubusercontent.com/110043019/186456997-a487f49b-a7fb-4014-b9a7-168affa62fbf.png)

**Comment by mouseas** [comment]
Faerlinchen, using a different mod to mute a sound doesn't fix this bug, it just masks it. And since I'm working on creating a modpack, it doesn't help my pack's end users either, because each of them would have to mute the sound themselves.

**Comment by Shadows-of-Fire** [comment]
That specific config option was supposed to have been removed - to kill the announcement you just set the announce distance to zero.

I've added controls (in 5.6.0) to adjust if the sound is played, and if the y-level is accounted for.  The sound being directionless is unfortunately out of my control unless I select a different sound, which I won't be doing for now.
