### ISSUE TITLE
Boss spawn announcements don't stay long enough

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Apotheosis#634]
![image](https://user-images.githubusercontent.com/15698722/186692436-7d6128f3-91cc-4d21-a497-75dc3e3dcc4a.png)

This was on screen for less than three seconds. The config also says it should be a chat message, not here.

~~This is with `Apotheosis-1.18.2-5.5.1`. I crashed when updating.~~ Crash was because Gateways to Eternity was outdated. Now on Apotheosis-1.18.2-5.6.1.

**Comment by Shadows-of-Fire** [comment]
Right, yeah I need to mixin to that field to get it to stay longer.  Forgot to do that before last release.

It _is_ supposed to display there but vanilla hardcodes that slot to only show for 60 ticksm

**Comment by Shadows-of-Fire** [comment]
Increased to 160 ticks in 5.7.0
