### ISSUE TITLE
B:"Announce Boss Spawns"=false does not disable boss spawn announcements

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Apotheosis#635]
[adventure.cfg](https://gist.github.com/f0582bca638b5494aa1dcb094ecd2180)

I disabled it before launching the game, and I'm still getting announcements.

This is on `Apotheosis-1.18.2-5.6.1`

**Comment by Shadows-of-Fire** [comment]
That option has been removed, disabling the announcement requires setting the announce range to zero
