### ISSUE TITLE
Life-Mending regenerating durability on armor stands.

### ISSUE THREAD

**Issue by nrvnzsmbruch** [Shadows-of-Fire/Apotheosis#636]
Hey, I've found a Bug including an armor stand and the Life-Mending enchantment.

If an armor stand has arms, which can be achieved with other mods or commands and you put any Item with durability into it's hands, the Life-Mending enchantment will regenerate durability without any cost whatsoever.

Minecraft Version 1.16.5
Apotheosis Version 4.8.4

**Comment by Shadows-of-Fire** [comment]
MC 1.16.5 is no longer supported.

I'll look into it for 1.18 though.  Weird thing is the enchant triggers off the healing event, and I'm not sure why an armor stand would be healing...

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.7.0
