### ISSUE TITLE
Gems not working in smithing table.

### ISSUE THREAD

**Issue by WillWhym** [Shadows-of-Fire/Apotheosis#637]
I can not get gems to do anything in the smithing table.  It doesn't matter what order I put the item and gem in the table, nothing happens.  I am running a lot of other mods, but is there anything obvious that could cause this issue?

**Comment by Shadows-of-Fire** [comment]
did the item have a socket?

**Comment by Gutieala** [comment]
I too am having this problem aswell as not being able to smelt affixed items on a soul campfire.
