### ISSUE TITLE
[1.18.2] Multi hit affixes also hit Goblin Traders

### ISSUE THREAD

**Issue by INooBTooMuch** [Shadows-of-Fire/Apotheosis#638]
## Versions 

Forge : 40.1.73
Apotheosis : 5.6.1
Placebo : 6.6.3

## Description

Goblin Traders from [Goblin Traders](https://www.curseforge.com/minecraft/mc-mods/goblin-traders) are hit when attacking a mob with a weapon (sword/axe) with a multi hit affix.

**Comment by Shadows-of-Fire** [comment]
fixed in 5.7.0.
