### ISSUE TITLE
[Minor] Chronicle of Shadows should clearly say "Gems will work no matter which socket they're in."

### ISSUE THREAD

**Issue by Xetaxheb** [Shadows-of-Fire/Apotheosis#641]
At the moment it says "a Gem will provide a powerful attribute bonus whenever the item normally would." and that's a little confusing and doesn't clearly let the player know that say, a fire damage gem can be socketed to the chestplate and will give fire damage to attacks.

My alternative suggestions:
"A Gem is a crystal of condensed strength. When socketed into an affix item, the Gem will provide a powerful bonus no matter which item the Gem is socketed into."

"A Gem is a crystal of condensed strength. When socketed into a worn or wielded affix item, the Gem will provide a powerful bonus no matter which socket it is in."

**Comment by Shadows-of-Fire** [comment]
Description updated in 5.7.0
