### ISSUE TITLE
[1.18.2] Boss Dungeons seem to be a bit broken

### ISSUE THREAD

**Issue by brisingraerowing** [Shadows-of-Fire/Apotheosis#644]
In my last playthrough (which was bricked by a bug) the first 4 boss dungeons I found had End related mobs (3 Endermen and 1 Shulker), all of which dropped Netherite gear. My current playthrough, the first boss dungeon spawned a Shulker that dropped Netherite gear. All of this was in the Overworld *before* going to the Nether.

**Comment by Shadows-of-Fire** [comment]
Do you know what version the dungeons were generated on?  They lock in a boss at gen time, so they may have predated the dimensional bosses

**Comment by brisingraerowing** [comment]
5.6.1 for both worlds.

**Comment by Shadows-of-Fire** [comment]
Not seeing this occur anymore, going to mark it as fixed. Update if it continues to occur in new chunks with 5.7.0
