### ISSUE TITLE
(1.18.2) Incompat Between Ex Compressum and Apotheosis

### ISSUE THREAD

**Issue by PhweeDev** [Shadows-of-Fire/Apotheosis#645]
I was playing and then a Compressed boss had spawned.

https://paste.gg/p/anonymous/4e915f3c269e4752a892933374d2fd5d

**Comment by PhweeDev** [comment]
Has this been fixed?

**Comment by Shadows-of-Fire** [comment]
It has been fixed for 5.7.0, but that update is not yet finished.
