### ISSUE TITLE
Are we still not able to move Affixes to different items?

### ISSUE THREAD

**Issue by MewoTM** [Shadows-of-Fire/Apotheosis#646]
Are we still not able to move Affixes to different items? I seen in a post that Deadly Module isnt available yet but that was three weeks ago and i noticed it seems to be in game now but called Adventure Module. I cant seem to find anything on how to take affixes off items and put them into a Tome of Scrapping though.

**Comment by Shadows-of-Fire** [comment]
Moving affixes is not returning as a feature.  Something may eventually take its place, but it will not be the same thing.

**Comment by MewoTM** [comment]
Ahh okay. Thank you for answering!
