### ISSUE TITLE
Recipes for Apotheosis' bookshelves disappeared

### ISSUE THREAD

**Issue by The-Goat-HUN** [Shadows-of-Fire/Apotheosis#647]
I don't know how to replicate, it seems like it randomly happened. I definitely could craft them before.

**Comment by Xorizo** [comment]
Did u fix it? ive got the same problem

**Comment by The-Goat-HUN** [comment]
> Did u fix it? ive got the same problem

Nope
Edit: added them back with CraftTweaker.

**Comment by Xorizo** [comment]
craftTweaker doesnt work for me lol,which mods do u have?server or single player

**Comment by The-Goat-HUN** [comment]
> craftTweaker doesnt work for me lol,which mods do u have?server or single player

I guess you could try KubeJS. But what do you mean it doesn't work? You could join their Discord server and ask for help. I use lots of mods in a custom pack.

**Comment by Xorizo** [comment]
ill try kubeJS,even if i change the recipes with CraftTweaker i cant craft them

**Comment by Shadows-of-Fire** [comment]
Any further information on this?  The shelf recipes exist fine in dev, production, and in modpacks.  I imagine you have something breaking it, but you'll have to figure it out.
