### ISSUE TITLE
[1.18.2] [Bug] Mod Interaction Crash. Twilight Forest Swarm Spider mob vs. Apoth Spawner

### ISSUE THREAD

**Issue by enigmaquip** [Shadows-of-Fire/Apotheosis#648]
Apotheosis 5.6.1
Twilight 4.1.1397
Forge 40.1.74

When the spawner attempts to spawn a swarm spider the server crashes

https://mclo.gs/ZXJ8RkD

relevant locations
<https://github.com/TeamTwilight/twilightforest/blob/1.18.x/src/main/java/twilightforest/entity/monster/SwarmSpider.java#L143>
<https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/spawn/spawner/LyingLevel.java>

Let me know if I should cross post this over to twilight as well

**Comment by Shadows-of-Fire** [comment]
This can only be fixed by TwilightForest, they're making an unsafe cast.

**Comment by Shadows-of-Fire** [comment]
I will add though, they should be using the explicit method `ServerLevelAccessor#getLevel` instead of doing the cast.
