### ISSUE TITLE
Step Height affix not affected by sneaking

### ISSUE THREAD

**Issue by FishOutOfH20** [Shadows-of-Fire/Apotheosis#649]
In 1.18.2 (Enigmatica 8), the Step Height affix does not respect a player sneaking.

If I sneak, I will still go up a block, or down a block.  Step assist should not activate in this situation.

This would be very dangerous in the nether or a skyblock world.  You walk right off the ledge (into lava or the void).

**Comment by Shadows-of-Fire** [comment]
Step height is managed by forge, not apoth, so you'll probably need to file a bug against them for what you believe to be expected behavior.

**Comment by FishOutOfH20** [comment]
I can use a Sojourner's sash from Botania just fine.  It's only when I put on a pair of Apotheosis affixed boots that this behaviour happens.

Still, if you say it's forge related, then I'll believe you since you're the dev.

Cheers.

**Comment by Shadows-of-Fire** [comment]
There's the potential that botania doesn't use the attribute, or it only behaves well with small values (smaller than those seen in apoth).

**Comment by FishOutOfH20** [comment]
Once again, I'll defer to you because you're the dev and you know more than me.

However, having said that, you might want to consider removing this affix until it is fixed by forge.  It breaks a vanilla minecraft staple of sneaking to avoid falling off an edge.  Wearing these boots, you will fall to your death because sneaking no longer prevents you from going over.

Cheers!

**Comment by Shadows-of-Fire** [comment]
This forge PR needs to be backported to 1.18, it seems.  I remembered dealing with it, but I guess I never made it back. https://github.com/MinecraftForge/MinecraftForge/pull/8927

**Comment by Shadows-of-Fire** [comment]
Pending fix by forge https://github.com/MinecraftForge/MinecraftForge/pull/9012
