### ISSUE TITLE
[1.18.2] New mob in spawner drops old mob's loot

### ISSUE THREAD

**Issue by Sinneqs** [Shadows-of-Fire/Apotheosis#650]
I'm playing on All The Mods 7 version 0.4.29 with Apotheosis version 5.5.1.

The issue is as next: I took a wither skeleton (armored) spawner from a Roguelike dungeon*, and when I changed it to spawn ghasts with a ghast spawn egg**, the spawned ghasts drop coal, bones and enchanted armor.

*might be a similar structure from a different mod, looks like the actual Roguelike mod isn't in ATM7
**aquired from the swab -> GM chicken feed -> chicken from Mob Grinding Utils

I played on a previous version of ATM7 already, where I was aware of a weird thing that the dungeon spawners spawned new mobs with the armor from the old mobs when altered, but I didn't run into the issue of it not rolling the correct loot tables, which seems to be the issue here.

Edit: I noticed that the ghasts do not drop wither skeleton skulls nor skull fragments, while the wither skeletons did

Images attached:

Mob spawner, formerly wither skeleton, now ghast
![Minecraft_ 1 18 2 - Multiplayer (3rd-party Server) 5_09_2022 0_07_37](https://user-images.githubusercontent.com/93472090/188335565-019ede76-1c98-4f45-ba7f-1cdaa0c97364.png)

Dropped items when killing multiple ghasts (with Looting V)
![Minecraft_ 1 18 2 - Multiplayer (3rd-party Server) 5_09_2022 0_08_21](https://user-images.githubusercontent.com/93472090/188335562-2efa92c9-b250-4268-9fe4-8989d10637a9.png)

**Comment by Sinneqs** [comment]
I just tried picking up the spawner with silk touch, no effect.
Picking up and replacing the spawner with a cardboard box by Mekanism doesn't help either

**Comment by Sinneqs** [comment]
Just had the same issue happen with a different spawner, which also used to be a wither skeleton spawner, but is now a cow spawner. Using a different sword does not fix the issue.
I also used other spawners today, changing one from vindicator to skeleton, which yielded no loot drop issue, so this seems to be more specifically an issue from either the dungeon spawners* or wither skeleton spawners.
*The vindicator spawner was a spawner found in a boat on the sea, a structure from a different mod than the dungeon mod

**Comment by Shadows-of-Fire** [comment]
Only way I could see that happening is if the prior spawner was encoding a custom loot table, and that nbt data isn't being cleared when the new spawn potential is applied.

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.7.0
