### ISSUE TITLE
[1.18.2] Crescendo of Bolts Enchantment does not work

### ISSUE THREAD

**Issue by whiteknight9547** [Shadows-of-Fire/Apotheosis#651]
Crossbows enchanted with The Crescendo of Bolts do not work as intended.

Crossbows will still use up ammo/arrows and requires the player to recharge the crossbow for every single shot.

What makes it worse is with other clashing enchantment mods like Enigmatic Legacy [Ceaseless] causes the arrows to be unpickable, removes the effects of special arrows (from mods) and still uses up ammunition.

This bug is however persistent even without other enchantments being applied to the crossbow (even when enchanted with just Crescendo of Bolts) the enchantment does nothing.

**Comment by Shadows-of-Fire** [comment]
Enigmatic Legacy is incompatible with apotheosis (and it is the cause of this problem, crescendo works normally, I just tested it).
