### ISSUE TITLE
[1.18.2] Crash - Can't find attribute apotheosis:current_hp_damage

### ISSUE THREAD

**Issue by PhweeDev** [Shadows-of-Fire/Apotheosis#652]
I randomly came back to my world and then I randomly crashed out of nowhere. I'm assuming my Extra Golems' Gold Golem attacked something. 

https://paste.gg/p/anonymous/eb516ab00c9d4abfab00dfda580ab1a0

**Comment by Shadows-of-Fire** [comment]
This is fairly similar to the evilcraft issue, which means extra golems is improperly registering their entity attributes.

They *must* use the EntityAttributeCreationEvent, lest things like this happen.
