### ISSUE TITLE
Missing Recipes and Features

### ISSUE THREAD

**Issue by Hurtequin** [Shadows-of-Fire/Apotheosis#653]
I am using Apotheosis in a custom modpack and when playing my friends and myself can not see some recipes in JEI nor can we create the rarity shards for Affixes. In curse forge it states that you place an affixed item on a soul camp fire (we can't do that), and in the changelog it mentions a new scrapping table (not visible in JEI). I have run Apotheosis in a single player world with no other mods and have run it in single player with just JEI, yet these problems persist.

Also looking at the config files I can't see any settings for the affixes anywhere. Is this normal?

Running Curse Forge 40.1.74
Minecraft 1.18.2

We are playing on a locally hosted server.

**Comment by Shadows-of-Fire** [comment]
sounds like you didn't read the big red notice that says the curseforge page is outdaded.

**Comment by Nicksecreto** [comment]
> 
hello I'm having the same problem as him in version 1.16.5 and I don't see any warning about the curseforge page being out of date I would like help with this if possible

**Comment by Shadows-of-Fire** [comment]
The curseforge page is not valid for old versions.

**Comment by Nicksecreto** [comment]
> A página do curseforge não é válida para versões antigas.

and what would be ?

**Comment by Shadows-of-Fire** [comment]
The Chronicle of Shadows, the in-game guidebook.

**Comment by Nicksecreto** [comment]
> The Chronicle of Shadows, the in-game guidebook.

ok
