### ISSUE TITLE
[1.18.2] [Apotheosis-1.18.2-5.6.1] Startup Crash: java.lang.NoClassDefFoundError: shadows/placebo/network/MessageProvider

### ISSUE THREAD

**Issue by Imoriarty** [Shadows-of-Fire/Apotheosis#654]
Using Forge [40.1.76]

Small Fail Box:

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: shadows/placebo/network/MessageProvider

[crash-2022-09-08_01.31.20-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9524688/crash-2022-09-08_01.31.20-client.txt)

I also attempted to remove Twilight Forest and re-run, still failed, I got something slightly different:

java.lang.NoClassDefFoundError: shadows/placebo/recipe/NBTIngredient

[crash-2022-09-08_01.33.30-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9524716/crash-2022-09-08_01.33.30-client.txt)

So then, I dropped everything but Apotheosis, and got the same thing as the first time:

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: shadows/placebo/network/MessageProvider

Dropped down to zero mods (Just 1.18.2+Forge), game loads.

Upped back to everything but Apotheosis (38 mods, + Optifine), game loads.

Issue persists for (at least) Versions:

Apotheosis-1.18.2-5.6.1
Apotheosis-1.18.2-5.6.0
Apotheosis-1.18.2-5.5.1
... and...
Apotheosis-1.18.2-5.3.4

Rolled back to Forge 40.1.0 (Recommended Build)... no dice.

Sighed heavily, and went back to the Curseforge page to see if anyone else was having issues.

Re-read description. Mod Requires "Placebo."

Placebo Downloaded.

Issue fixed.

/Sigh

Thanks for joining me on this journey. If one could highlight the **Pre-Requisite Mods** a little more boldly (or move the requirement to the top of the description), it'd help tired people like me.

**Comment by Shadows-of-Fire** [comment]
You either have two placebo jars installed (which is usually what I see causing this) or you have a *reallllly* old placebo version.

As for the dependency thing...  It's marked where it needs to be.  I won't go out of my way to put a banner on the main page.
