### ISSUE TITLE
Bug : Legendary tooltips acting strange with item with gems

### ISSUE THREAD

**Issue by Blugori** [Shadows-of-Fire/Apotheosis#655]
I noticed that when an item get a gem, it doesn't have the divider line :
with and without : 

![1](https://user-images.githubusercontent.com/66573974/189503364-4a59fe1c-8acc-46a0-bd00-605a14439dbc.png)
![2](https://user-images.githubusercontent.com/66573974/189503365-0946be7e-9f5f-49f4-a6d4-6632248b0fec.png)

I wouldnt mind if that was the only issue, but as you can see on the 2nd screenshot, everytime I'm putting the mouse over the item with gem, a strange artefact shows up :/

**Comment by Blugori** [comment]
more visible issue : 
![3](https://user-images.githubusercontent.com/66573974/189503510-091dcd6e-1760-4231-a608-0e7b180e1953.png)

**Comment by Shadows-of-Fire** [comment]
Since it's their rendering having a problem you'll need to bring it up to them and they can relay back here if it's something I can fix.

**Comment by AHilyard** [comment]
I've looked into the bug and luckily it is an easy one-liner to fix.  I've made a PR for that here: https://github.com/Shadows-of-Fire/Apotheosis/pull/659
