### ISSUE TITLE
Not able to enchant chestplates or leggings with Rebounding enchantment

### ISSUE THREAD

**Issue by 7thCaliber** [Shadows-of-Fire/Apotheosis#656]
Rebounding can only be added onto chestplates or leggings via enchanted book on an anvil in creative mode, unable to do this in survival mode. Rebounding cannot be found in the enchanting table for chestplates or leggings. Cannot use /enchant command to apply rebounding enchantment to chestplates or leggings, attempting to do so will return the message [armor name] cannot support that enchantment. Hovering over the rebounding enchanted book will not display correct icons (chestplates and leggings) as other apotheosis books do.

_Rebounding book does not display correct icons:_
<img width="627" alt="2022-09-11_00 56 25" src="https://user-images.githubusercontent.com/56764991/189513406-238ecefd-c37d-467d-a33b-8258d721ec57.png">
<img width="627" alt="2022-09-11_00 56 35" src="https://user-images.githubusercontent.com/56764991/189513437-b3d00e1e-f9b2-41bf-b301-975e45305e7b.png">

_Rebounding book can only be combined with compatible armor via anvil in creative mode, but not in survival mode:_
<img width="1920" alt="2022-09-11_01 03 47" src="https://user-images.githubusercontent.com/56764991/189513489-b8551edd-8cbd-4908-b8cd-725b52e554d7.png">
<img width="1920" alt="2022-09-11_01 04 25" src="https://user-images.githubusercontent.com/56764991/189513494-99f097dc-6c3e-4727-86bb-a4972649723d.png">

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.7.0
