### ISSUE TITLE
config bug/ from  #A list of type overrides for the affix loot system.

### ISSUE THREAD

**Issue by linhuan123** [Shadows-of-Fire/Apotheosis#658]
add data in  # A list of type overrides for the affix loot system.
So there is an interesting question.
Entering the World break block causes a lot of affix weapons and gems to spawn
rebound config，It doesn't make the world go back.

**Comment by Shadows-of-Fire** [comment]
What?

**Comment by linhuan123** [comment]
> 什么？

![F1](https://user-images.githubusercontent.com/56089610/190237299-20f38961-4be7-44e5-8023-88c6d9a2a966.png)

**Comment by Shadows-of-Fire** [comment]
No it won't, as that field has no bearing on loot generation.

What you describe would only be the result of a malformed entry in the `"Affix Item Loot Rules"` and `"Gem Loot Rules"` config values.
