### ISSUE TITLE
Death Chest voids items from the Curios API slots

### ISSUE THREAD

**Issue by VT-14** [Shadows-of-Fire/Apotheosis#66]
The Death Chest causes items in the [Curios API](https://www.curseforge.com/minecraft/mc-mods/curios) slots to be voided upon death.  The items are not put into the death chest, nor are they dropped on the ground (which happens as normal if Apotheosis is not installed).

Tested using [Curious Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra).

Minecraft: 1.14.4
Forge: 28.0.32
Apotheosis: Apotheosis-1.14.4-2.1.0.jar
Curios API: curios-FORGE-1.14.4-0.18.jar
Curious Elytra: curiouselytra-FORGE-1.14.4-0.7.jar

Placebo: Placebo-1.14.4-2.1.2.jar
Caelus API: caelus-FORGE-1.14.4-0.10.jar

F3+C Debug Crash: https://gist.github.com/VT-14/8b291af88aec42d2e988d49c375027f5
Forge Log: https://gist.github.com/VT-14/0ac34d4602fc7ef726b8fb4b86cb56e3

**Comment by Shadows-of-Fire** [comment]
Ah, yeah, I need to move my event 1 priority down so curios goes first.  Fixed in next update.
