### ISSUE TITLE
Impossible to infuse stuff like shelves

### ISSUE THREAD

**Issue by antoine-courant** [Shadows-of-Fire/Apotheosis#660]
Minecraft Version: 1.18.2

Forge Version: 40.1.60

Mod Version: 1.18.2-5.3.6

Single Player or Server: Server

Describe problem (what you were doing; what happened; what should have happened):

Hello there ! I was trying to get infused hellshelves
I saw you needed to enable the enchantments for the mod, which was always the case, I have the 45 lvls, all the right stats (that being right the right stats or more of them)
But despites all of this, I still can't infuse anything, even after trying multiple times and enchanting other items, impossible to get them... which is pretty sad because you need to infuse stuff to go further in the mod :/

Video/images/gifs (direct upload or link):
![2022-09-14_22 37 22](https://user-images.githubusercontent.com/11462348/190257513-02de98ad-0ab4-4fed-a9bd-7a86b00b21c1.png)

![2022-09-14_22 37 28](https://user-images.githubusercontent.com/11462348/190257564-2470c0a8-4260-4efc-a242-bed080acc340.png)

**Comment by Shadows-of-Fire** [comment]
That gui isn't an apotheosis enchanting table, so you have another incompatible mod installed.  You'll have to remove it.
