### ISSUE TITLE
1.18.2-5.6.1 "when attacked gain instant health II"

### ISSUE THREAD

**Issue by CuchilloMucho** [Shadows-of-Fire/Apotheosis#661]
This effect is insanely overpowered, it makes you effectively immortal until your armor breaks and if you have mending or another mod that lets you passively repair items it just flat out makes you immortal

**Comment by CuchilloMucho** [comment]
ok after playing with it a bit more it does not seem to trigger on magic attacks, still makes you immortal in melee combat

**Comment by Shadows-of-Fire** [comment]
It will be receiving a cooldown or other nerfs in 5.7

**Comment by Shadows-of-Fire** [comment]
Instant potion affixes will be receiving a 30 tick cooldown between procs in 5.7.0
