### ISSUE TITLE
Bosses spawning in crazy amounts 3+ bosses per night. 

### ISSUE THREAD

**Issue by LunarDev-git** [Shadows-of-Fire/Apotheosis#662]
Is there any way to tamper with the spawn rate for the bosses? I see no way in the config 

I sometimes even have 5+ in one minecraft night. 

MC Version: 1.18.2
Forge: 40.1.80

Apotheosis: 5.6.1
Placebo: 6.6.4

**Comment by Shadows-of-Fire** [comment]
Boss spawns are configurable in the file /config/apotheosis/adventure.cfg

The defaults are constantly being updated, but there's no catch-all value, and the defaults are designed in a vanilla context.
