### ISSUE TITLE
[Feature] Socket Gems as Tetra Sockets

### ISSUE THREAD

**Issue by AngellusMortis** [Shadows-of-Fire/Apotheosis#663]
[Tetra](https://www.curseforge.com/minecraft/mc-mods/tetra) has a similar socketing system as Apotheosis. It would be cool to reuse the Apotheosis socket gems as Tetra socket gems.

**Comment by Shadows-of-Fire** [comment]
No desire to work on this.

**Comment by MadSciSlack** [comment]
C'mon Shadows, this would be coooooool lol

**Comment by meeprdib** [comment]
What would socketed Apotheosis gems provide as Tetra sockets, if this were to be implemented? It just wouldn't make sense to try and combine the two socketing systems imo.
