### ISSUE TITLE
bane of illagers doesn't work for ravager

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadows-of-Fire/Apotheosis#665]
![image](https://user-images.githubusercontent.com/47446553/192544059-d9725a92-8f10-49c6-bf0a-0d5a5f7fa6ba.png)
![image](https://user-images.githubusercontent.com/47446553/192543871-b99ecfac-4fca-4779-8841-93f6f45a404f.png)
I don't know if this is the way it should be or a bug?

**Comment by Shadows-of-Fire** [comment]
The ravager is not really an illager, so this is the correct interaction.
