### ISSUE TITLE
[BUG]1.18.2 Execute entity death bug

### ISSUE THREAD

**Issue by 6371peter** [Shadows-of-Fire/Apotheosis#668]
**Describe the bug**
Entity be excute but it will not dead,but entity will drop loot,but it will still alive;then if kill it there is no drop.

**Mod Version**
Forge-1.18.2-40.1.80
Placebo-1.18.2-6.6.3
Apotheosis-1.18.2-5.6.1

**To Reproduce**
1.Get a weapon has excuting
![2022-10-04_19 56 08](https://user-images.githubusercontent.com/64669376/193813656-6a0f5794-4b3e-41a7-8113-011bae8a6e61.png)
This netherite axe will deal 85 health damage to iron golem[20*(100%+325%)=85],iron golem will alive.
Then when i improve gem effect,make it +330% total attack damage
![2022-10-04_20 05 03](https://user-images.githubusercontent.com/64669376/193815230-29535936-5fec-4e0e-a915-e24ddfc31adf.png)
This time when i attack iron golem,it will deal 86 health damage[20*(100%+330%)=86,iron golem health below 15% max health,it should be excuted;but it still alive and drop loot,it health still 14.
![2022-10-04_20 08 32](https://user-images.githubusercontent.com/64669376/193816429-034d653d-d47f-44c4-8e1b-980b4c789cc0.png)
After it be excuted,kill it again will not drop anything.

**Comment by Shadows-of-Fire** [comment]
Fixed for 5.7.0
