### ISSUE TITLE
Crash with TF Swarm Spider spawners using Ignore Light modifiers

### ISSUE THREAD

**Issue by WickedWeazel** [Shadows-of-Fire/Apotheosis#669]
Sup,

just had a crash (see pastebin for crash-log) while upgrading a spawner (Hedge Spider from Twilight Forest).
Cant remember exactly which upgrade, but I think it was the Soul Lantern one.
I was in the normal overworld while doing, not in the Twilight Forest.

https://pastebin.com/2HXMDPUJ

This was on singleplayer and i cant load my world now, it crashes on joining with the same report everytime.
Is there anyway to get my world back or am i screwed? :(

**Comment by Shadows-of-Fire** [comment]
This is a bug in twilightforest, you'll have to report it to them.  They're making an unsafe cast from ServerLevelAccessor to ServerLevel instead of using ServerLevelAccessor#getLevel

That said, you should be able to use the world by enabling   RemoveErroringTileEntities in the forge config file.

**Comment by WickedWeazel** [comment]
Thanks for the fast reply.

I removed the spawner with a world editor. That let me get back into the world.

Sidenote (for anyone finding this and looking to fix it like @Shadows-of-Fire suggested):
The config file should be **<world>\serverconfig\forge-server.toml**
containing these two settings:

```
removeErroringBlockEntities = false
removeErroringEntities = false
```

**Comment by Shybella** [comment]
> This is a bug in twilightforest, you'll have to report it to them. They're making an unsafe cast from ServerLevelAccessor to ServerLevel instead of using ServerLevelAccessor#getLevel
> 
> That said, you should be able to use the world by enabling RemoveErroringTileEntities in the forge config file.

High quality post, thank you.
