### ISSUE TITLE
[Compatibility] Maximum Enchantment power with Lapis stay in Enchanting Table

### ISSUE THREAD

**Issue by Fireztonez** [Shadows-of-Fire/Apotheosis#67]
Hello,

I have in my the file `enchantment_module.cfg` set: `  S:"Max Normal Power"=20`

So, when I saw enchanting power from Normal source I imagine, what you want to mean is the power enchantment power from normal Bookshelf. So technically with that setting, I should not be able to have an enchanting table with enchant at more than 40 lvl, but when I place bookshelf all around the enchanting table, I can start making enchantments up to lvl 64 (So, power 32...).

I really want to have ability to lock the Power with regular bookshelf for after being able to get higher power from Hellshelf (Maximum of power 128). 

Version: 
Minecraft forge: 1.12.2 - 14.23.5.2838
Apotheosis: 1.10.2

Thank's
Fireztonez

**Comment by Shadows-of-Fire** [comment]
The system that is in place for handling the caps on power is currently functional, however it will fail if something else overrides my container for the enchantment table.  You wouldn't happen to have any other mods that would be doing that, would you?

**Comment by Fireztonez** [comment]
Oki, I have to do somes test and see in that case, I will try to found the mods conflict in that case!

I will let you know

**Comment by Fireztonez** [comment]
I just change the title of the issue, question of clarty, I think this is little more clear like that ;)
