### ISSUE TITLE
attribute crash (again). 1.16.5-4.8.9A0

### ISSUE THREAD

**Issue by AlienXtream** [Shadows-of-Fire/Apotheosis#670]
bit of a nasty one as it totally broke the world (like, gone from the worlds menu alltogether. asn't a minecraft world as far as the game was concerned). *POSSIBLY* related to "AI Improvements" mod. could also be "attribute fix" but i'd have assumed its standard enough to include that it would be considered for compatibility already. im suspecting apotheosis as the catalyst in this case though im honestly not sure and am putting this here more as an FYI than a "OmG pLz FiX". i know mod development is hard and respect that.

 bit hard to test given its based off RNG (unless you can tell me a spawn command that should in throry trigger it. if so will gladly test). as you can see it was allegedly a husk monster so it should have had the attribute. i understand that legacy versions are not a priority and dont even expect you to nesisarrily fix it for this version but for future versions i have a proposed "band-aid" fix. an "attribute safe mode" in the configs. disables all direct attribute effects and instead uses potion effects (if applicable). this would only be needed if specific mod combinations are causing issues, allowing users to use the mod overall but not worry about attributes crashing and as it suggests its a last resort option to enable compatibility. alternatively a hard check for if the attribute is valid for the entity first before trying to apply any attribute modifiers. i know lots of null checks are generally bad but i'll take an extra few ms loss if it means i dont have to constantly be paranoid the game will crash on me XD
 
 anyway, hope this is at least applicable. 

crash report 
 |
\/

[crash-2022-10-04_20.55.30-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9712429/crash-2022-10-04_20.55.30-server.txt)

**Comment by Shadows-of-Fire** [comment]
The provided crash report is coming out of uniquee `uniquee.handler.EntityEvents.onEntityAttack(EntityEvents.java:735) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_126_EntityEvents_onEntityAttack_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}`

There is no apoth code in the stacktrace whatsoever, so this is all on the other mod.

**Comment by AlienXtream** [comment]
ah. i see. apologies. i assumed since it was an apoth boss that triggered it it was inherantly something with your mod. i do not know what mod that is however so some layman's direction would be appreciated

**Comment by AlienXtream** [comment]
sorry to bring this one up again. it happened again and i cant work out what's doing it. only that its thus far been the bosses from the deadly module that are affected. i've disabled their spawning for now but i would be greatful if i could get a summon command for a mob that may trigger the issue consistently it would be a great help in testing, otherwise i have to rely on RNG

**Comment by Shadows-of-Fire** [comment]
You can summon a deadly module boss entity using the Apotheotic Boss Summoner item.

**Comment by AlienXtream** [comment]
... i feel like an idiot... XD
ofc thats a block i can place, ha ha... thanks
