### ISSUE TITLE
5.7.0 items do not show properly

### ISSUE THREAD

**Issue by Tlotro** [Shadows-of-Fire/Apotheosis#671]
Most items and blocks added in 5.7.0 have no texture, and all of them have no name (item's internal name is shown instead). They also have no recipe in JEI. And blocks have no specified tool
![image](https://user-images.githubusercontent.com/50557602/194601523-42c595e7-a7cd-4960-855f-da0be1d7fed3.png)

modpack: FTB Inferno

**Comment by Shadows-of-Fire** [comment]
5.7.0 is not released yet.  Inferno has an alpha build because they needed certain features for their release.
