### ISSUE TITLE
[Bug] Tinkers items dont show affix information

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Apotheosis#674]
The tooltips seem to be cut off in apoth 5.7 on tinkers tools

![image](https://user-images.githubusercontent.com/9200909/195932370-b2a54528-6f0c-4b86-b3f4-98ecd7303af2.png)

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1437

**Comment by Shadows-of-Fire** [comment]
@KnightMiner was adding special support for it but I'm not sure if it made it to live or not.

We have it working in the J2TC development instance, so the code exists somewhere™

**Comment by Saereth** [comment]
tbf we are not on the latest tinkers atm, we're on TConstruct-1.18.2-3.5.1.31, was avoiding updating since its going to be a bunch of work for me lol but if thats the issue we'll update.

**Comment by Saereth** [comment]
confirm works with updated tinkers
![image](https://user-images.githubusercontent.com/9200909/195949637-4cebe16a-0cb4-40fe-83bc-995917794a2a.png)
