### ISSUE TITLE
Affix Shulker Shells?!

### ISSUE THREAD

**Issue by brisingraerowing** [Shadows-of-Fire/Apotheosis#678]
A picture is worth a thousand words, so have four:
![2022-10-15_20 05 56](https://user-images.githubusercontent.com/250409/196011955-55c5542a-9650-4dfc-9a26-4be7da93c82b.png)
![2022-10-15_20 05 57](https://user-images.githubusercontent.com/250409/196011957-e676bd08-688a-4938-be74-9190204a25f4.png)
![2022-10-15_20 05 59](https://user-images.githubusercontent.com/250409/196011958-9debaa8a-7b21-4f39-afa2-93f767d631cb.png)
![2022-10-15_20 06 00](https://user-images.githubusercontent.com/250409/196011959-5b62a922-08d7-4b62-9d5c-ccf40b8d930d.png)

Apotheosis 5.7.0 on 1.18.2

**Comment by Shadows-of-Fire** [comment]
This is not really a bug, moreso a side effect of the new Affix Conversion Loot Modifier combined with something else making helmets a valid equipment item.

Shulker shells do not have an equipment type by default (as is testable by running `/apoth loot_category` while holding one) but I have been informed there is a mod that makes them helmets, which would likely be elevating them to equipment status.

The best bet would be to remove the equipment type from shulker shells via the override in adventure.cfg by setting them to type `NONE`.

**Comment by brisingraerowing** [comment]
Yup. ~~Just found out it's Quark that makes them helmets (of course)~~. I'm turning that 'feature' off now, as I don't see any actual use for it.

Actually it's Supplementaries.
