### ISSUE TITLE
BUG: Base Crit Chance activates effect but no extra damage

### ISSUE THREAD

**Issue by VallenFrostweaver** [Shadows-of-Fire/Apotheosis#679]
Minecraft 1.18.2
Forge 40.1.80
Apotheosis 5.7.0

When using the example sword below it will at times activate a critical hit. The animation and sound happens but the damage does not. Tested using the MmmMmmMmmMmm dummy mod.
![image](https://user-images.githubusercontent.com/13642054/196433822-6204d282-a035-4df3-92b9-f02f894b74ed.png)
Damage numbers on the left are the previous hit. Damage number on the right is the critical taking place.
![image](https://user-images.githubusercontent.com/13642054/196434295-c8ee92d8-6040-4615-9e15-d91269e16042.png)

**Comment by Shadows-of-Fire** [comment]
Fixed via 5.7.1 crit adjustments
