### ISSUE TITLE
Loot pinata equipment dupe

### ISSUE THREAD

**Issue by Tlotro** [Shadows-of-Fire/Apotheosis#684]
mod version 1.0.3.

Loot pinata effect makes a mob drop multiple time it's loot.
Items on mobs do count toward that loot.

steps to reproduce:
1) get an equipment item you want to dupe (mythic item will work fine)
2) find a mob that can equip said item (zombie, skeleton etc.)
3) "give" said mob said item
4) kill said mob
5) repeat steps 2-4 until loot pinata effect triggers
6) get immence amount of select item
7) if you have a spawner of said mob, it can semi-automatically generate infinite items

proposed solutions:
simple: make pinata effect not affect equipment.
complex (if not impossible): mark items when they are picked up by mobs.

P.S. this also tends to clog inventory with items

**Comment by brisingraerowing** [comment]
Does this work with non-equipment items like Nether Stars? If it does, it might be a bit more problematic for servers with economies.

**Comment by Shadows-of-Fire** [comment]
Realistically it probably works on everything.  The best stopgap solution is probably to disable mob griefing, which disables item pickup

**Comment by Tlotro** [comment]
Works on everything thac can be equiped. Imagine this with a backpack mod that uses chestplate slot

**Comment by Tlotro** [comment]
@Shadows-of-Fire If I may ask. Will this be fixed or at least made a config in the future?

**Comment by Shadows-of-Fire** [comment]
Fixed in 5.7.3 (equipment items are omitted from pinata)

**Comment by GeneralHux18** [comment]
does this work for mobs with chests/inventories, such as horse or donkey?
