### ISSUE TITLE
[1.18.2] Latest version dedicated server disconnect on login

### ISSUE THREAD

**Issue by maxhenkes** [Shadows-of-Fire/Apotheosis#687]
Hey,
the latest 1.18.2 version 
Apotheosis-1.18.2-5.7.4.jar

works fine in single player but disconnects the player on my dedicated server immediately on login:
![image](https://user-images.githubusercontent.com/817708/197573516-9f4a2083-72ba-4c24-971b-13f360e4c1cc.png)

I tested this on a fresh forge-1.18.2-40.1.84 server with only your mod and it's dependencies. It was working fine before the update.

https://pastebin.com/qjyyGKjB

**Comment by Shadows-of-Fire** [comment]
Is this the server or client log?

**Comment by maxhenkes** [comment]
Client, the server shows nothing at all. Just disconnects. I'll post it in a sec just in case.

**Comment by maxhenkes** [comment]
https://pastebin.com/kMjd6LzN Server log

**Comment by Shadows-of-Fire** [comment]
Fixed in 6.0.1/5.7.5
