### ISSUE TITLE
Broken installation on forge 28.0.34+

### ISSUE THREAD

**Issue by kemus** [Shadows-of-Fire/Apotheosis#69]
Reproducing from a vanilla install of minecraft 1.14.4:

- install forge `28.0.32`
- place `Apotheosis-1.14.4-2.1.1.jar` into the mods folder
- run the profile forge generates
- game loads up as expected
---------
- install `forge 28.0.34` (or any more recent version up to 28.0.40)
- place `Apotheosis-1.14.4-2.1.1.jar` into the mods folder
- run the profile forge generates
- game crashes on start, providing a launcher log with exceptions that I don't understand:

launcher_log.txt with the errors:
https://gist.github.com/kemus/79d8d8763789a2c53d362e93eab2bcde

**Comment by kemus** [comment]
investigating further, this does not seem to just be an issue with your mod, this forge update also broke
`EnderBags-1.14.4-4.1.0.jar`

**Comment by Shadows-of-Fire** [comment]
Unusual... I'll go poke around at it.

**Comment by kemus** [comment]
Alright, I've tested the 93 mods I've downloaded, and this happens with 5 of them:
`Apotheosis-1.14.4-2.1.1.jar`
`EnderBags-1.14.4-4.1.0.jar`
`morelights-1.3.1.jar`
`RGBStone_1.0.jar`
`ruins-1.14.3.jar`

Seeing as it happens with other mods, I'm betting it's a regression on forge's part, so I'll write up this issue for them too.

If you want to try to fix how it happens with your mod, it might be worth looking at what your mod does similarly to some of the others I listed? Not sure if that'll be useful though.

I'll just stick with using forge 28.0.32, though, since I'm really excited to try apotheosis out :)

**Comment by Shadows-of-Fire** [comment]
If you want to try out apoth you probably shouldn't have any excitement for the 1.14 version, it contains 3 items and nothing more.

**Comment by kemus** [comment]
Oh, welp, I guess I can wait patiently for the update to be out of alpha (I didn't know it wasn't complete) 👍

**Comment by kemus** [comment]
Hey, I don't know if you're still looking into this issue, but it was indeed a forge bug, and one of their devs is working on fixing it now: https://www.minecraftforge.net/forum/topic/74149-crash-on-launch-with-certain-mods-starting-at-forge-28034/

(so I don't think it's worth spending any of your effort trying to fix it on your end)
