### ISSUE TITLE
Data pack errors in 1.19.2

### ISSUE THREAD

**Issue by brasscrest** [Shadows-of-Fire/Apotheosis#691]
Can't open a (single player) world, new or existing, in 1.19.2. Throws a data pack error. Checked with the following and no other mods:

Forge 43.1.47
Apotheosis 1.19.2-6.0.1
Placebo 1.19.2-7.0.1

https://pastebin.com/ruNG0Vuh

**Comment by Shadows-of-Fire** [comment]
Duplicate of #688
