### ISSUE TITLE
Step Height attribute >= 2 causes player to stop moving when crouched.

### ISSUE THREAD

**Issue by GoliathX211** [Shadows-of-Fire/Apotheosis#694]
This only occurs when there is a block gap underneath the player. One vital issue with this is being unable to bridge over chasms.

I apologize for otherwise limited information, I would test further if I knew how to.

**Comment by Shadows-of-Fire** [comment]
Step height is managed by Forge.  Any bugs with it have to be reproduced as a minimal reproduction case (with just forge installed) and reported to them.  I can't manipulate the functionality of it on my end.

**Comment by GoliathX211** [comment]
I suspect that it somehow interferes with how the crouching system determines whether it is safe to walk off the block. It may be related that step height allows you to crouch walk off a block if there is a block below greater than or equal to the step height value.
Edit: Thanks for the fast response.

**Comment by Shadows-of-Fire** [comment]
Step height should no longer permit that behavior as long as your forge version is "new enough"
https://github.com/MinecraftForge/MinecraftForge/pull/8927
https://github.com/MinecraftForge/MinecraftForge/pull/9012

**Comment by GoliathX211** [comment]
Using forge version 40.1.69, do you happen to know what version I should upgrade to? I just realized I never mentioned that I am using 1.18.2.
Edit: I am guessing at least 40.1.78 because it was released on September 8th, the day that the commit was merged.
Edit2: Nevermind, it was patched in 40.1.77 according to the changelog.

**Comment by Shadows-of-Fire** [comment]
Yep, the first release with it is `40.1.77`

**Comment by GoliathX211** [comment]
I know it probably isn't the place to say it, but I absolutely love this mod and I was waiting so excited for the deadly module to come back to 1.18.2. Thank you for all the work you've put into this mod for the community. <3
