### ISSUE TITLE
[Bug] Wandering Traders can Trade Tools with Better Enchanting Levels than Configured

### ISSUE THREAD

**Issue by INooBTooMuch** [Shadows-of-Fire/Apotheosis#695]
So pretty much I have set the Sharpness Enchantment Level to 7 and a trader is giving it for 10.
I set it through apotheosis enchantments.cfg
![image](https://user-images.githubusercontent.com/107572028/198531489-017ebc04-de14-4aab-91bd-b3f58da97fa0.png)

(Here are the in-game photos)
![2022-10-28_10 37 13](https://user-images.githubusercontent.com/107572028/198531606-a74c7ee3-bfd9-41f8-a6ca-f588289d0a72.png)
![2022-10-28_10 37 16](https://user-images.githubusercontent.com/107572028/198531625-b94042c1-2e05-47e6-9718-70e8b1ee0ded.png)

Minecraft : 1.18.2
Forge : 40.1.84
Apotheosis : 5.7.6
Placebo : 6.6.6

**Comment by Shadows-of-Fire** [comment]
Yes, that's expected.  These trades are statically defined via data files https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/wanderer_trades

**Comment by INooBTooMuch** [comment]
So if I make a datapack with the same path but just change the `nbt:` of the item in the output will that work?

For example the bonesplitter.json has this `"nbt": "{Enchantments:[{lvl:10s,id:\"minecraft:sharpness\"},{lvl:1s,id:\"minecraft:mending\"},{lvl:5s,id:\"apotheosis:hell_infusion\"},{lvl:2s,id:\"apotheosis:capturing\"},{lvl:5s,id:\"minecraft:looting\"},{lvl:3s,id:\"minecraft:unbreaking\"}],display:{Name:\u0027{\"translate\":\"name.apotheosis.merch_axe2\"}\u0027},Damage:0}"` 
if I just change the numbers in the lvl is it going to be ok or can it cause problems?

**Comment by Shadows-of-Fire** [comment]
That will work
