### ISSUE TITLE
[1.19] Knight Phantom probably shouldn't be a default Apotheosis boss type

### ISSUE THREAD

**Issue by MuteTiefling** [Shadows-of-Fire/Apotheosis#697]
These are twilight boss mobs, like the lich or ice queen. When they die, they spawn a chest with progression loot under them. Could be considered a break in progress for Twilight Forest if you found one early. 

Version: Apotheosis-1.19.2-6.0.1

**Comment by Shadows-of-Fire** [comment]
hmmmmmmmmmmmmmmm

_perhaps_

**Comment by MuteTiefling** [comment]
There's always the go big or go home approach and just add them all :D
