### ISSUE TITLE
Game crashes after installing Apotheosis and it's dependencies

### ISSUE THREAD

**Issue by KitKatPanda** [Shadows-of-Fire/Apotheosis#699]
As the title says, after installing Apotheosis and it's dependencies, the game crashes. I get this error: https://gyazo.com/409fd68a44b4d3bd39d0b0e1ffadbc8a , but when I go to check the crash report, I don't have anything there.

Made sure all 3 mods were the most updated versions of them, running 1.19.2 on the Medieval MC Pack, with just a few mods I added myself. Here's a quick scroll of them all: https://gyazo.com/e854cc0d87cce34f269b593f2d7733d0

And as a side note, after removing all 3 mods, my game still refuses to start, getting the same error code with no crash report left behind. Odd.

**Comment by Shadows-of-Fire** [comment]
You likely have mods incompatible with apotheosis installed.  In the first frame of your video I see at least one (ConfigurableCane).  Please remove all incompatible mods before installing apoth.

**Comment by KitKatPanda** [comment]
I can't seem to find a list of incompatibilites, would you be able to provide one?

**Comment by Shadows-of-Fire** [comment]
If you open the curseforge page for a specific apoth file they will be listed near the bottom

**Comment by KitKatPanda** [comment]
Oh! I never scrolled down that far, I guess now I know where to look from now on. Thanks. 

Also, I noticed that on the bottom of the Curseforge main page for the mod that it says that Enchantment Descriptions is a recommended, but at the bottom of the 1.19.2 file page, it shows it as a required dependency. 

Might have also cause the crash (other than Conf. Cane) 
(Edit: Already had Enchant. Descripts. Installed.)

**Comment by Shadows-of-Fire** [comment]
Enchantment descriptions missing will not crash, I have it marked as required so it auto installs when using CF.

The only dep that will crash if absent is Placebo
