### ISSUE TITLE
Advent of Ascension spawner crash

### ISSUE THREAD

**Issue by prosbloom225** [Shadows-of-Fire/Apotheosis#7]
Anytime an Advent of Ascension spawner is placed, the game crashes with the belowerror.  Disabling the spawner module in the Apotheosis global config mitigates the issue.  Vanilla spawners are unaffected.

https://paste.ee/p/Zov8U

**Comment by Shadows-of-Fire** [comment]
Should be resolved via the next release of AoA (3.0.2)
