### ISSUE TITLE
[1.14.4] Crash on load when added to The Adventures of Halk pack.

### ISSUE THREAD

**Issue by ProsperCraft** [Shadows-of-Fire/Apotheosis#70]
https://gist.github.com/ProsperCraft/e671e9033c57076f6b667620452979fe

**Comment by ProsperCraft** [comment]
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/3489428/debug.log)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/3489429/latest.log)

**Comment by Shadows-of-Fire** [comment]
Caused by mine and slash https://github.com/RobertSkalko/Mine-and-Slash/issues/63
