### ISSUE TITLE
Can't use Anvil when Apotheosis is installed.

### ISSUE THREAD

**Issue by KitKatPanda** [Shadows-of-Fire/Apotheosis#700]
As mentioned above, when I have Apotheosis installed, I can't use the anvil at all. I can't even open one, regardless if it was placed before the mod was installed, a freshly made one, or a cheated in one after the mod was installed. It's only with this mod installed, as once I remove it the anvil works perfectly fine. 

I don't have any of the incompatible mods, but if I need to make a new list of mods (as I had to completely reinstall the modpack I was using, and it's got a few different mods in it) I can do so.

**Comment by Shadows-of-Fire** [comment]
This issue typically arises when you have a mod incompatibly modifying the anvil.  Your game log should tell you the culprit.
