### ISSUE TITLE
Client crash when I try to track Memory Leaks

### ISSUE THREAD

**Issue by DrSigma4164** [Shadows-of-Fire/Apotheosis#702]
I try to find the memory leaks in minecraft versions 1.16.5 with your Kitit. I have not yet understood how it works, and would be glad if someone would help with that, but the essence of the question is not. As I realized that the program could track down the data, you need to add parameters that will be below.
Everything seems to work, but during the property of the property, in stages everything turns off, I go into the logs, and it contains the next file. Don't tell you what I'm doing wrong? Just without this mod I will not be able to test and do not want to turn it off.

Minecraft: 1.16.5
Apotheosis: 1.16.5-4.8.9A0
Forge: 36.2.39

[crash-2022-10-31_11.57.05-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9900191/crash-2022-10-31_11.57.05-client.txt)
Parameters: -agentpath:C:\ProgramData\YourKit\2022.9.170\windows-x86-64\B99A482A\yjpagent.dll=delay=10000

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported, and I have no clue what is going on in your environment such that the primary mod class is not instantiable.  I imagine your profiler is breaking thing very badly.
