### ISSUE TITLE
Feature request - configurable Rarity Material and Gem Dust cost multipliers when reforging

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Apotheosis#704]
Currently, the cost to reforge an item, in Rarity Materials and Gem Dust, is fixed / hard-coded to be 2, 4, or 6 for Rarity Materials, Gem Dust, and experience levels (based on the selected choice).

I would like this to be configurable so mod packs can tweak the cost to their own liking.
The cost multiplier could be a value which is multiplied by the selected choice (1, 2, or 3) to determine its cost in Rarity Materials and Gem Dust. The default multiplier would be 2 (to preserve old behavior of costing twice the selected choice of both items), with a minimum of 0 (or 1 if required for technical reasons) to 16 (or as high as technically feasible, given the maximum stack size is 64 for most items). Ideally, it should be possible to set different cost multipliers for Rarity Materials and Gem Dust, such that reforging may cost 3 of a rarity material and 1 gem dust (or the opposite).

Example use cases:
* Make reforging less expensive to incentivize players to do it a bit more if they want to.
* Make reforging more expensive for the opposite effect.
* Reduce the quantity of Gems obtained through various sources, while reducing the Gem Dust required to reforge to compensate.
* Make reforging cost more Rarity Materials than gained back to make infinitely reforging to farm rarity materials unviable.

**Comment by Shadows-of-Fire** [comment]
This is possible, and _theoretically_ not complicated, but unfortunately the 2/4/6 numbers on the reforge menu are hardcoded into the texture, and not rendered separately, which means that it will take some time or reworking of that menu to work properly.
