### ISSUE TITLE
[Suggestion] [Adventure] Add way more configuration options

### ISSUE THREAD

**Issue by Lucky-56** [Shadows-of-Fire/Apotheosis#705]
Why? There's armor which gives you Instant Health II on hit, basically making you invincible for the rest of the game.

- configuration for possible effects, boosts

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/affixes
