### ISSUE TITLE
Datapack error when disabling Adventure module

### ISSUE THREAD

**Issue by IchHabeHunger54** [Shadows-of-Fire/Apotheosis#707]
When disabling the Deadly/Adventure module through the config, entering a world yields this error:
`java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / forge:biome_modifier_serializers]: apotheosis:blacklist`
Full log: https://gist.github.com/IchHabeHunger54/9fe13c0c609ea6e3131ff6720d5cf313

**Comment by Shadows-of-Fire** [comment]
duplicate of #688
