### ISSUE TITLE
Feature request - Enchantment Library

### ISSUE THREAD

**Issue by SharkBairRFSR** [Shadows-of-Fire/Apotheosis#709]
I love the interface of the enchantment library and the easy storage of enchanted books and would like the enchanted library seperated form the enchantment module.

**Comment by James103** [comment]
Already implemented in the most recent version of the mod for 1.18 and 1.19.
Update Apotheosis if possible.

**Comment by Shadows-of-Fire** [comment]
I don't plan on ripping out any features and publishing them separately.
