### ISSUE TITLE
[BUG] Weaker Enchantments when using Apotheosis, even when the Enchantment Module is disabled.

### ISSUE THREAD

**Issue by choombdev** [Shadows-of-Fire/Apotheosis#710]
**Issue:** Enchantments are much weaker than Vanilla, even with the Enchantment Module disabled. 
I enchanted 9 Netherite Pickaxes in Creative and wrote down their enchantments here, once with and once without Apotheosis installed:
https://i.ibb.co/KXYwqZY/firefox-19-C3-R4-QJh-D.png

**Apotheosis.cfg and Latest.log:**
https://paste.gg/p/anonymous/08bc86d5c048465ba22751de6fac0df2

**Forge Version** 40.1.84 (Latest)

**Modlist:**
Apotheosis-1.18.2-5.7.6.jar
Bookshelf-Forge-1.18.2-13.2.50
EnchantmentDescriptions-Forge-1.18.2-10.0.9
Patchouli-1.18.2-71.1
Placebo-1.18.2-6.6.6

**Comment by Shadows-of-Fire** [comment]
Issue here was the default vanilla quanta value (15%) wasn't being applied when the ench module was disabled.  This was fixed at some point during 1.19's lifecycle.
