### ISSUE TITLE
Adventure Module causing client crash on Critical Hit Event

### ISSUE THREAD

**Issue by jessejones1031** [Shadows-of-Fire/Apotheosis#713]
When using most weapons to attack, damage wont occur and then son after the game will save world and then crash

[crash-2022-11-08_08.56.17-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9963592/crash-2022-11-08_08.56.17-client.txt)
[debug (1).log](https://github.com/Shadows-of-Fire/Apotheosis/files/9963615/debug.1.log)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9963616/latest.log)
[2022-11-08-1.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9963623/2022-11-08-1.log)

**Comment by Shadows-of-Fire** [comment]
The only mod in that stack trace is UnionLib, nothing about apotheosis.
