### ISSUE TITLE
Major single player and server bug 

### ISSUE THREAD

**Issue by Zelioth** [Shadows-of-Fire/Apotheosis#714]
https://bytebin.lucko.me/IHlPQUT3em

Minecraft Curse forge 43.1.47
1.19.2
Latest version for mod. 

For some reason when people generate new worlds they instantly crash after a few seconds and it gives a entity ticking error.

our server is having this same issue and says apotheosis everytime

**Comment by Shadows-of-Fire** [comment]
nothing in this report says anything about apoth.  The only mod named is corail tombstone.
