### ISSUE TITLE
Auto-pickup affix is incompatible with FTB Ultimine

### ISSUE THREAD

**Issue by James103** [Shadows-of-Fire/Apotheosis#718]
As of Apotheosis 6.0.1 on Minecraft 1.19.2, when a tool that has "Block drops will automatically teleport to you" as one of its effects is used to mine many blocks at once via FTB Ultimine, that effect does not work and the drops are still left near where the blocks originally were. This may lead to loss of items if the player is not careful.

To reproduce:
1. Create a new instance with Minecraft 1.19.2 and Forge 43.1.47.
2. Install Placebo and Apotheosis.
3. Install FTB Ultimine, FTB Library, and Architectury API.
4. Create a new world with cheats enabled.
5. Give yourself a Netherite Pickaxe.
6. Give yourself some GodForged Pearls and a Reforging Table.
7. Repeatedly reforge the tool until one of its effects say "Block drops will teleport to you" (hereafter referred to as the auto-pickup affix).
8. Go into survival mode: `/gamemode survival`
9. Mine a block normally and notice the drop is automatically sent to your inventory.
10. Use FTB Ultimine to mine a bunch a blocks.
11. Notice none of the drops were automatically sent to your inventory.

System information:
[example_crash.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/9995304/example_crash.txt)

The test case uses 1.19.2, but this also happened on the 1.18.2 version of Apotheosis and in the mod pack "All the Mods 7".

Workaround: Install a mod that includes a magnet which teleports nearby items to you (such as [Simple Magnets](https://www.curseforge.com/minecraft/mc-mods/simple-magnets)), allowing easier collection when FTB Ultimine is active.

**Comment by Shadows-of-Fire** [comment]
Detecting block drops is _very_ difficult (even the existing functionality already uses a mixin).  The current system in place hooks into `Block#dropResources` and moves and dropped entities from that method to the player, but if ultimine doesn't utilize that method, it won't get picked up.  I'm not sure what ultimine does, but I think hooking into it would be extremely fragile, so I'll have to opt to allow it to remain as-is.
