### ISSUE TITLE
[1.19.2] Nether bosses in overworld

### ISSUE THREAD

**Issue by brisingraerowing** [Shadows-of-Fire/Apotheosis#719]
The first two boss dungeons I've found in the overworld have spawned a blaze and a Zoglin respectively (and were also within 25 blocks of each other). This seems to be similar to #644.

**Comment by Shadows-of-Fire** [comment]
I still cannot reproduce this issue despite testing. The code responsible for performing the dimensional selection is here https://github.com/Shadows-of-Fire/Placebo/blob/1.19/src/main/java/shadows/placebo/json/WeightedJsonReloadListener.java#L139
This cannot be bypassed by any means unless something was either overriding standard bosses, either removing their dimension restrictions / adding them to the overworld, or somehow lying about the name of the current dimension (or bypassing the check entirely).

If a reliable reproduction can be determined with just apoth, I'm happy to take a look, but the logic on my end is pretty ironclad.  The dimension check is infallible and every nether boss json has the dimension properly set.
