### ISSUE TITLE
No bosses/traps spawning

### ISSUE THREAD

**Issue by Proe24** [Shadows-of-Fire/Apotheosis#72]
I have flown around in spectator mode in attempt to see if there were any locations where bosses/"traps" (or mob spawners with chest) are spawning and have not been able to find any. Unless they are incredibly rare, they don't appear to be generating. There have has been no crashing and I am still able to craft any items from the mod. 

Below is a list of other mods currently running alongside this one:
U Team Core (by HyCraftHD)
Searchable Chests (by ZjuBukkit)
Biomes O' Plenty (by GlitchfiendMods)
Silent Gear (by SilentChaos512)
Placebo (by Shadows_of_Fire)
FastFurnace (by Shadows_of_Fire)
Inventory Sorter (by cpw11)
Useful Backpacks (by HyCraftHD)
Doggy Talents (by percivalalb)
Toast Control (by Shadows_of_Fire)
XL Food Mod (by mariot7)
Morpheus (by Quetzi)
Light Level Overlay Reloaded (by oldjunyi)
EmbellishCraft (by KillerMapper)
FTB Utilities: Backups (by LatvianModder)
FastWorkbench (by Shadows_of_Fire)
Better Title Screen (by Girafi)
Silent Lib (by SilentChaos512)
Tool Belt (by TheRealGigaherz)
Controlling (by Jaredlll08)
Forbidden and Arcanus (by cesar_zorak)
Better Animals Plus (by cybercat5555)
Iron Chests (by progwml6)
Xaero's Minimap (by xaero96)
Equipment Tooltips (by SilentChaos512)
Corpse (by EuhDawson)
Clumps (by Jaredlll08)
Just Enough Items (JEI) (by mezz)
Enchantment Descriptions (by DarkhaxDev)
OpenBlocks Elevator (by VsnGamer)
Progressive Bosses (by InsaneGames_)
AppleSkin (by squeek502)
Hwyla (by TehNut)

**Comment by Shadows-of-Fire** [comment]
Well I know for a fact they were spawning in a vanilla world because I was getting crashes when they were incorrectly implemented.  Might be BoP that is causing it to fail, either due to how the features work or i may not be adding features late enough.

**Comment by Mrtrex525** [comment]
Does Biomes O' Plenty still break it in 1.16.5
