### ISSUE TITLE
"when attacked gain instant health" makes player invulnerable

### ISSUE THREAD

**Issue by iron431** [Shadows-of-Fire/Apotheosis#720]
instant health 1-3 grants players 3-9 hearts every time they get hit... nothing in the game can hit 9+ hearts, especially not through protection 4 on mythic armor. can a configurable cooldown be added or have instant health be switch to regen? this oversight makes progression feel meaningless once you get one piece of armor with the proc on it.

**Comment by Shadows-of-Fire** [comment]
Yes, you can change this affix fully by overriding it with a datapack.  The default file is here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/affixes/armor/mob_effect/revitalizing.json

**Comment by agrzegorzewski** [comment]
@Shadows-of-Fire 
I'm facing the same issue, and it appears there's no option in the config to remove the Affix or at least disable it. I've found the file you linked in this repo, but I have little experience with Java, so I'm not familiar with writing a data pack. 

Can you think of an easy-to-implement hack that would disable or remove this Affix? If not, do you plan on moving Affixes to the config file so they are easily customizable? Looking at how they are stored currently, this looks doable, but not sure how much work that would be.

**Comment by iron431** [comment]
Datapacks use zero java, they're just collections of data files (usually json) that mods can use to automatically generate content, like with the affixes. This is the datapack I made after this post, which switches instant health to regeneration: (!!! this is for 1.18.2 and will not work on 1.19)
[1.18.2 Apotheosis Tweaks.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/10050464/1.18.2.Apotheosis.Tweaks.zip)

Edit: that being said, the cooldown field seems to be ignored through my testing on 1.18.2, is this a bug? @Shadows-of-Fire
