### ISSUE TITLE
Datapack issue

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Shadows-of-Fire/Apotheosis#722]
Not entirely sure what's happening here, but there's a datapack issue somewhere in the files which makes me unable to load a world. dunno if it's another mod getting angry at it or wut, but thought i'd start here since apoth was the first to throw the error
[2022-11-16-1.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10025096/2022-11-16-1.log)

**Comment by Shadows-of-Fire** [comment]
Fixing this issue was dependent on merge of https://github.com/MinecraftForge/MinecraftForge/pull/9113
So this will be automatically fixed in 6.1.0
