### ISSUE TITLE
Is it possible to change max gem sockets on gear?

### ISSUE THREAD

**Issue by iron431** [Shadows-of-Fire/Apotheosis#723]
Through the digging I've done, I haven't found a way to change max sockets per piece through datapacks or config. Is this possible to do, and if so, how?

**Comment by Shadows-of-Fire** [comment]
Naturally rolled?  Not currently, it's this hardcoded thing set in the loot rules of each individual rarity.

*however*, recipes for the addition of sockets define the max number of sockets that item can contribute to, so you can theoretically increase the max this way 
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/recipes/superior_add_sockets.json#L11

**Comment by iron431** [comment]
ill look into it, thanks for the lightning fast response

**Comment by rm302** [comment]
how a do this
