### ISSUE TITLE
Gem Rarities Are Not Accurate

### ISSUE THREAD

**Issue by galactigav** [Shadows-of-Fire/Apotheosis#724]
For whatever reason, gem rarities for me are quite literally backwards. Ancient gems are most common for me and common gems are the rarest for me. I even tried changes the configuration files and that does nothing. I am on Minecraft v1.19.2 and Apotheosis v6.0.1.

**Comment by Shadows-of-Fire** [comment]
Gem rarities are not "real" in the sense that they don't actually do anything (right now)
They're based entirely on the _purity_ (increasing at every 20% threshold value).  Gem rarities will mean something in the upcoming 6.1.0 update.

**Comment by galactigav** [comment]
Thank you for clearing the confusion.
