### ISSUE TITLE
[1.19.2] loot bug?

### ISSUE THREAD

**Issue by CubeTwo** [Shadows-of-Fire/Apotheosis#725]
dont know on which side is this but, if you have all items with + 5-8 luck  and sword with looting 3, you kill raiders from "MineColonies" thay drop like 10-15 items, if you have crown from "Nameless Trinkets" +50% all stats or +120% all stats thay drops like 50 -70 items from 1 mob
edit: all time you kill raiders from "MineColonies"  drops crazy amount of loot, no sound or blast of loot pinata 

https://imgur.com/a/YAjIUtA

Apotheosis-1.19.2-6.0.1
minecolonies-1.19.2-1.0.1124-ALPHA
Nameless Trinkets-1.19.2-1.6.9
forge 43.1.52

**Comment by Shadows-of-Fire** [comment]
Luck is a vanilla stat, so how a mob handles luck is up to it.  That said, you'll need to report it to minecolonies to see what they're doing.  As far as I was aware luck cannot increase the number of dropped items.

**Comment by Diversion98** [comment]
> Luck is a vanilla stat, so how a mob handles luck is up to it. That said, you'll need to report it to minecolonies to see what they're doing. As far as I was aware luck cannot increase the number of dropped items.

I hope you will see this.
I changed my affixes to only 0.01 but when i kill a barbarian, it still drops tons of item, like CubeTwo said, and all of them are affixes

Minecolonies does think its apotheosis doing this: https://github.com/ldtteam/minecolonies/issues/8785

I do want to help giving you and minecolonies more information/testing if needed
It's a very annoying bug, especially when u get late game in minecolonies. (all those barbs dropping tons of loot)

**Comment by Shadows-of-Fire** [comment]
The items become affixed as a result of the conversion modifier (which targets any items dropped from a loot table for addition of affixes) - those are not being "added" by apoth in any sense, so changing the drop chance would not impact it.

The only affix that can increase loot rolls is Loot Pinata (Festive), and the only enchantment that can increase loot rolls is Scavenger.  It should be easily verifiable if this is on minecolonies' side as you should be able to test by changing your luck value via `/attribute` instead of using apoth affixes to boost it.

**Comment by Diversion98** [comment]
> 
I tested this without loot pinata on an axe and still got tons of that loot

**Comment by Diversion98** [comment]
> The items become affixed as a result of the conversion modifier (which targets any items dropped from a loot table for addition of affixes) - those are not being "added" by apoth in any sense, so changing the drop chance would not impact it.
> 
> The only affix that can increase loot rolls is Loot Pinata (Festive), and the only enchantment that can increase loot rolls is Scavenger. It should be easily verifiable if this is on minecolonies' side as you should be able to test by changing your luck value via `/attribute` instead of using apoth affixes to boost it.

I tested this without loot pinata on an axe and still got tons of that loot and it doesnt have scavenger :/
also the axe doesnt have any luck on it, my armor in total does have 21 luck (counted every piece of armor) but no scavanger on the armor

just tested with regular vanilla armor with no enchants and the drops are fine then (didnt change attribute)
Tested with attribute to 100 and got plenty of items again.

Thanks for you advice! :)
