### ISSUE TITLE
Affix tome missing

### ISSUE THREAD

**Issue by Avalonzo** [Shadows-of-Fire/Apotheosis#726]
I'm playing ATM 8 and can't seem to find the affix tome has it been removed or have you changed the affix moving system.

**Comment by Shadows-of-Fire** [comment]
affixes can no longer be moved, the reforging table takes this place instead via rerolling

**Comment by Avalonzo** [comment]
Quick question what do I do with materials gotten from the salvaging table NEI doesn't know and I can't see much about using them in the chronicle of shadows.

Edit: never mind I thought only arcane sand was using in the reforging table.
