### ISSUE TITLE
Strange interaction with Luck - Loot Pinata - Gateways to eternity (witches + reliquary)

### ISSUE THREAD

**Issue by Kevin-Marsh** [Shadows-of-Fire/Apotheosis#729]
I have been playing around with high levels of luck on my gear. This has mad my sword start Loot pinataing on every monster kill. A welcome result to be sure. This has led to a strange interaction with gateways to eternity drops at the end of waves seeming to be significantly multiplied.

Where this becomes an issue is that packs like allthemods which include reliquary give witches a potential drop of a witch hat. This is also multiplied and unstackable. The gateways have been returning an extreme amount of witch hats at the end which resulted in 6700 individual witch hat entities strewn across the floor causing significant slowdowns. It took my system 30 mins to complete the gate yesterday at 1fps.

![2022-12-01_14 17 06](https://user-images.githubusercontent.com/9076964/205265401-e22a6553-b280-43b1-9e35-ca6da0a2467f.png)
![2022-12-01_14 32 23](https://user-images.githubusercontent.com/9076964/205265542-02a776d5-f5b1-4b50-9723-835d5181c542.png)

**Comment by Shadows-of-Fire** [comment]
Ah, well that's terrifying. I will have to implement a flag for preventing pinata from applying on apoth's end, and then raise the flag from gateway's entity loot gen code.
