### ISSUE TITLE
Crash when defeating the ender dragon 

### ISSUE THREAD

**Issue by Raiderax** [Shadows-of-Fire/Apotheosis#73]
The crash happens once you try an go through the portal back to the overworld after defeating the ender dragon it happens everytime for me.

**Comment by Shadows-of-Fire** [comment]
not enough information

**Comment by Raiderax** [comment]
Ok so what exactly do you need because the after the end credits it's like
your stuck in the end void an the game hard freezes Everytime now if their
is a way to log it then I'll do that

**Comment by Shadows-of-Fire** [comment]
A crash report and a debug.log file, anything less cannot be considered.
