### ISSUE TITLE
Error using apotheosis 6.0.1 for 1.19.2 on a 1.19.2 (43.1.65) forge server.

### ISSUE THREAD

**Issue by promitheas-nikou** [Shadows-of-Fire/Apotheosis#730]
I tried installing apotheosis 6.0.1 for 1.19.2 on a 1.19.2 (43.1.65) forge server, and it works on the first launch, but when I try to edit the config file config/apotheosis/apotheosis.cfg and disable every module (set to false) other than spawners and potions, it produces the following WARN (not error, but warning) message:

[blablabla]
[02Dec2022 20:14:39.091] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Error loading registry data: Unknown registry key in ResourceKey[minecraft:root / forge:biome_modifier_serializers]: apotheosis:blacklist
[blablabla]

and then the server crashes.
Tried installing 6.0.0 instead, same thing. Tried resetting the world, didn't even got to load the world, crashed during modloading. Full log can be found here (https://mclo.gs/fVkJRdP).

**Comment by Shadows-of-Fire** [comment]
The adventure module cannot yet be disabled on 1.19.  It's depending on external changes.

**Comment by promitheas-nikou** [comment]
> The adventure module cannot yet be disabled on 1.19. It's depending on external changes.

Is this an intended feature on 1.19, or will it be eventually fixed?

**Comment by Shadows-of-Fire** [comment]
it is a bug
