### ISSUE TITLE
Invalid Charms

### ISSUE THREAD

**Issue by xXHorusXx** [Shadows-of-Fire/Apotheosis#731]
I have a Magma server for 1.16.5.
When I grab a Potion Charm it turns pink and gets invalid. This happens with every single charm.

https://user-images.githubusercontent.com/106632023/205446077-4b517f19-10ff-470d-8fe8-9828c48ca28b.mp4

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported, and magma is _certainly_ not supported.
