### ISSUE TITLE
[1.16] Exception ticking world crash.

### ISSUE THREAD

**Issue by wasdspace** [Shadows-of-Fire/Apotheosis#732]
apotheosis: 1.16.5-4.8.9A0

Random crash, happened after playing about 30 minutes. Although this is random crash, is the third time. Other than that, I didn't find any useful information, sorry :(

[crash-2022-12-03_22.20.21-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10146654/crash-2022-12-03_22.20.21-server.txt)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10146655/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10146656/debug.log)

**Comment by Shadows-of-Fire** [comment]
1.16 is no longer supported.  Based on the crash report you have an invalid boss gear set json loaded, so you may want to remove any datapacks and try to source the cause.
