### ISSUE TITLE
[1.19.2] Infinity tools(industrial foregoing) will reset upon attempting to socket a gem

### ISSUE THREAD

**Issue by PikachuGabe** [Shadows-of-Fire/Apotheosis#733]
(copied from my report on the IF github)
Industrial Foregoing Version:
industrial-foregoing-1.19.2-3.3.2.0-2

Titanium Version:
titanium-1.19.2-3.7.0-23

https://user-images.githubusercontent.com/84477180/205464998-72efb68b-9433-4a20-8863-a3a0912dd6cf.mp4

i reforge it to be an apotheosis item with slots so i have the easiest way to use a smithing table on it,applying a gem. when i apply the gem,the hammer fully resets back to as if it was just crafted.

**Comment by Shadows-of-Fire** [comment]
I don't think there's anything I can do about this, the recipe uses a copy of the itemstack, if it doesn't copy correctly I can't correct it.

**Comment by NielsPilgaard** [comment]
@Buuz135 You may wanna have a look at this, Infinity Tools are reset when upgraded with Apotheosis gems, using a Smithing Table.
