### ISSUE TITLE
Issue with crafting Chronicle of Shadows

### ISSUE THREAD

**Issue by NemesisBreaker** [Shadows-of-Fire/Apotheosis#737]
This is for Apotheosis-1.16.5-4.8.9A0.jar

When trying to craft the Chronicle of Shadows following the screenshot on the Curseforge page, I am not able to craft it. 
![image](https://user-images.githubusercontent.com/2906701/206305993-d5588f1e-9aa3-40f9-bacf-ef91f59c2cb4.png)

 I have the required mods and the recommended mods installed only(see screenshot below)
![image](https://user-images.githubusercontent.com/2906701/206306096-fe360a2e-60b0-4d4c-85b6-b63bb70839d3.png)

**Comment by Shadows-of-Fire** [comment]
Is the book visible in jei?

**Comment by NemesisBreaker** [comment]
The book is visible in JEI but does not display a crafting recipe. I am able to grab one from creative, just not able to craft one.

**Comment by Shadows-of-Fire** [comment]
Ah right now I remember.  The recipe never made it during the backporting process.  You can add it yourself with a datapack, the json file is here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/recipes/book.json

**Comment by BigJMoney** [comment]
Is this issue not going to get fixed? I pulled my hair out trying to figure this out; thank goodness I decided to look in database of closed issues. Most people won't be that thorough.
