### ISSUE TITLE
[Apotheosis-1.18.2-5.7.6] When attacked, gain Instant Health * seems to make player and mobs immortal.

### ISSUE THREAD

**Issue by Damnbugs** [Shadows-of-Fire/Apotheosis#739]
This effect seems to be way to strong, I cant be killed when I have a armor piece with it, and I cant kill bosses that have it.

Is there a way to disable or make it less powerful in the configs?

**Comment by Shadows-of-Fire** [comment]
All affixes are defined in json - this particular one is defined here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/resources/data/apotheosis/affixes/revitalizing.json
It can be overrided with a datapack.
