### ISSUE TITLE
Disable enchant combining in the anvil when quark is enabled.

### ISSUE THREAD

**Issue by SpGilbert** [Shadows-of-Fire/Apotheosis#74]
Can you make it so you cannot combine enchants to a higher level like 2 unbreaking 3 into 1 unbreaking 4 though an anvil when quark is enabled or add a config option that allows you to enable or disable this feature of the mod in 1.12.2

**Comment by Shadows-of-Fire** [comment]
apotheosis raises max levels of enchantments, and the maxes are configurable, if you dont want maxes above normal, scale them back down.

**Comment by SpGilbert** [comment]
not that I mean you can combine unbreaking 3 with unbreaking 3 to get unbreaking 4 but quark has ancient tombs that do that as well.
