### ISSUE TITLE
[1.18.2] Alex's Mobs and Affixes

### ISSUE THREAD

**Issue by INooBTooMuch** [Shadows-of-Fire/Apotheosis#740]
The skelewag sword from [Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs) can block like a shield and the affixes it gets are only on the shield part and not the sword part. Is there a way to make it get affixes on both parts of the weapon or maybe just the attack?

Apotheosis : 5.7.7
Forge : 40.1.85

**Comment by Shadows-of-Fire** [comment]
You can force the type of an item via the adventure module config, but an item cannot have two types.

So you can make the game treat it like a sword, but then it will not receive shield affixes.
