### ISSUE TITLE
Straight-up broken

### ISSUE THREAD

**Issue by TrikiNya** [Shadows-of-Fire/Apotheosis#741]
- Gems don't appear in JEI
- As a matter of fact, most Apotheosis items don't show up
- The Chronicle of Shadows is essentially broken, having no entries
- I can't turn gems into dust with an anvil

This is a multiplayer server that I do not own nor have control over.

https://user-images.githubusercontent.com/52202914/206793027-be889e64-7a3a-4456-957f-abab0c057afe.mp4

**Comment by Shadows-of-Fire** [comment]
You are likely on an old version before dust was implemented.

As for everything else, most of apoth can be disabled, so you will want to take it up with the authors of the modpack you are using.

**Comment by TrikiNya** [comment]
> You are likely on an old version before dust was implemented.

No, this is 5.7.6, unless this mod is somehow backward compatible and the server is running an older version...

**Comment by TrikiNya** [comment]
Nope, version of the server is the same as the one in the modpack from what I'm told
