### ISSUE TITLE
[1.18.2] Server freeze during startup while replacing calls (COREMODLOG)

### ISSUE THREAD

**Issue by Numilani** [Shadows-of-Fire/Apotheosis#743]
This may be an incompatibility with other mods (I can provide a full list upon request, it's rather long) but the behavior around the problem seems strange. When starting a modded server, the console frequently freezes on these lines:

```
[Server] [modloading-worker-0/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[Server] [modloading-worker-0/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTreasureOnly() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[Server] [modloading-worker-0/INFO] [ne.mi.co.Co.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTradeable() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
```

The server never actually *crashes*, but startup comes to a halt and requires the process to be killed.

Now, here's the weird part: this doesn't *always* happen. About one in every 4 attempts to start the server, it boots without issue; if I just keep killing and restarting the server, eventually it boots and runs normally.

I can provide a full modlist and any additional log files needed upon request.

**Comment by Shadows-of-Fire** [comment]
So the thing is those lines appear after the transformer is finished, meaning your problem lies with whatever is running after it.  Unfortunately the log provides no clues as to what it might be, but it's not this transformer.

You'll just need to remove mods until the issue halts, which is difficult if its a classloading race condition.
