### ISSUE TITLE
Player Mobs mod entities spawn with no Username when given Affixed gear

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Shadows-of-Fire/Apotheosis#745]
I've come to notice that when a player mob from the Player Mobs mod spawns with affix items, something happens that prevents it from loading any of the users set within its configs, perhaps caused by the name system. I'm not sure what could be doing this, but perhaps an easy workaround would be a config to blacklist mobs from being spawned w affix gear or being renamed when given said gear

**Comment by Shadows-of-Fire** [comment]
Only boss mobs are renamed, and bosses are generated on a whitelist basis, as they require a boss json to be present.  If you have done something to enable player mobs spawning as bosses, then you should just... not be doing that, I guess.

Realistically I would consider this a flaw in player mobs if they are relying on the username for _anything at all_.  But in general there won't be anything to do about this from my end.
