### ISSUE TITLE
[1.18.2 Request] - Max Gem Slot Config

### ISSUE THREAD

**Issue by iron431** [Shadows-of-Fire/Apotheosis#746]
Can we get a config for the maximum amount of gem slots an item can roll? Would help with modpack balancing tremendously

**Comment by Shadows-of-Fire** [comment]
Nothing new will be added to 1.18.2 at the current moment.  Could potentially look at something like this for 1.19

**Comment by Shadows-of-Fire** [comment]
Deferring to #780
