### ISSUE TITLE
Interaction with Corail Tombstone, also reported to ATM 8 team

### ISSUE THREAD

**Issue by shrad1994** [Shadows-of-Fire/Apotheosis#748]
https://github.com/AllTheMods/ATM-8/issues/484

I'm aware of how terrible the ATM team is with communicating issues outward so I'm also reporting it here in case you need to know to fix it inb4 they just outright disable blocks from your mod :P - The library of alexandria will not allow me to take out a book with only tombstone soulbound (Corail tombstone mod) on it, but will allow me to take it in ADDITION to a second enchant.

![image](https://user-images.githubusercontent.com/96917010/208844832-8f9a58ed-6125-4805-99bb-07dacceddb18.png)

![image](https://user-images.githubusercontent.com/96917010/208844854-64a868b7-ec05-4a9b-a670-5a4c7cb5884a.png)

**Comment by Shadows-of-Fire** [comment]
Corail Tombstone is a closed-source all rights reserved mod.  No support is provided for these types of mods due to inability to debug anything.  You'll have to ask them to fix it.  And given that it's only their enchantment out of "all enchantments in the universe", it's probably their problem.

**Comment by shrad1994** [comment]
![image](https://user-images.githubusercontent.com/96917010/208845849-a255ed19-dde0-4860-8788-fe2f8003665f.png)
I will figure out how to report it to them as your explanation makes sense, but to correct you it does seem to be open source as of now.

**Comment by Shadows-of-Fire** [comment]
The project license on CF is set to ARR and there is no source visible on the github.  Plus that screenshot is two years old.
