### ISSUE TITLE
Rarity Material Crafting.

### ISSUE THREAD

**Issue by HeavyDeception** [Shadows-of-Fire/Apotheosis#750]
A way to combine the Materials to make better ones would be great because as of right now you tend to gather a lot of the lower-level ones and they just end up sitting in your chests.

Maybe something that uses Gem dust with them as you get a lot of that also.

**Comment by bbarry** [comment]
yes please, even:

1. storage blocks for rarity materials and gem dust (9x recipe)
2.  4 block rarity + 4 block gem dust + nether star or something  like that => 1 next level material

Once you have half decent affixes of say a rare reforge, there seems to be absolutely no point to pick up uncommons... yet uncommons appear everywhere you look.

**Comment by SiverDX** [comment]
You can do this yourself using https://www.curseforge.com/minecraft/mc-mods/crafttweaker

Example:
``` zs
craftingTable.addShaped("apotheosis_uncommon_material", <item:apotheosis:uncommon_material>, [
    [<item:minecraft:copper_ingot>, <item:minecraft:copper_ingot>, <item:minecraft:copper_ingot>], 
    [<item:minecraft:copper_ingot>, <item:apotheosis:common_material>, <item:minecraft:copper_ingot>], 
    [<item:minecraft:copper_ingot>, <item:minecraft:copper_ingot>, <item:minecraft:copper_ingot>]]
);
```

**Comment by Shadows-of-Fire** [comment]
No plans to add tiering up recipes for the rarity materials.
