### ISSUE TITLE
Apotheosis effects flickering

### ISSUE THREAD

**Issue by hyenaheartbeats** [Shadows-of-Fire/Apotheosis#752]
I'm running a 1.18.2 server and experiencing some odd flickering with effects, where they will run out and reapply themselves shortly after. Gear that gives you extra health tends to not give as much as advertised and any gear with speed has the FOV flickering in and out making the game nearly unplayable. I'm unsure what could be causing this, as the server has adequate RAM and CPU available, and the TPS consistently remains 20.

The server is running Oracle Linux Server release 8.6, 2x Ampere Altra 80C OCPUs through Oracle Cloud, with 12GB of memory.
The full list of mods on the server: https://pastebin.com/L3FwveXg

**Comment by Shadows-of-Fire** [comment]
This has been determined to be a bug with the mod `Forgery`

**Comment by hyenaheartbeats** [comment]
Forgery lets you toggle mixins on and off, is there any specific module that's messing it up?
