### ISSUE TITLE
Shulker shell with affix

### ISSUE THREAD

**Issue by shrad1994** [Shadows-of-Fire/Apotheosis#753]
![image](https://user-images.githubusercontent.com/96917010/210167786-398fe747-4274-446c-aca7-2fc94fd68249.png)

really not sure how this happened 

![image](https://user-images.githubusercontent.com/96917010/210167801-57412448-5ef9-4f93-aa28-a81f4a97d60f.png)

**Comment by shrad1994** [comment]
It happened naturally, I'm not really sure if it generated in a box or dropped from a mob though

**Comment by Shadows-of-Fire** [comment]
This happens because convert rules are active and a mod (supplementaries i think?) makes shulker shells into wearable helmets.

You can blacklist either the shulker loot table or remove the equipment type from shells via config.  I may look into making that a default config option.

**Comment by Shadows-of-Fire** [comment]
Shulker shells are now set to type `NONE` by default.
