### ISSUE TITLE
Library of Alexandria not showing sharpness enchant for axes

### ISSUE THREAD

**Issue by shrad1994** [Shadows-of-Fire/Apotheosis#755]
![image](https://user-images.githubusercontent.com/96917010/210191716-0a35df97-987b-4b8a-937e-39aa91d3b471.png)
The sharpness enchant doesn't show up with the "item filter" with axes

![image](https://user-images.githubusercontent.com/96917010/210191706-f036fde7-4aa1-4e42-9737-38f72b3beca0.png)
See here it is applicable

I haven't tested with anything else yet as no other enchants stand out in my mind in the same way.

**Comment by shrad1994** [comment]
Just to note*** sharpness DOES show up with swords so it seems to be isolated to axes perhaps?

**Comment by Shadows-of-Fire** [comment]
That check is here https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/ench/library/EnchLibraryScreen.java#L238

Seems it may need to be loosened to `canApply` or whatever it is the anvil checks instead.
