### ISSUE TITLE
Multiple Suffixes don't work for 1.19.2

### ISSUE THREAD

**Issue by DaddyP1G** [Shadows-of-Fire/Apotheosis#758]
Certain items don't have the corresponding Language data. 
![2023-01-07_16 23 43](https://user-images.githubusercontent.com/37815251/211170916-4e49ab55-9fee-4358-a6e3-937806100414.png)

**Comment by Shadows-of-Fire** [comment]
There is no affix with id `apotheosis:stalwart` in 1.19.
How did you obtain this item?

**Comment by DaddyP1G** [comment]
It was in a Dungeon Crawl Dungeon.

**Comment by Shadows-of-Fire** [comment]
Was your world previously on 1.18?

**Comment by DaddyP1G** [comment]
This is my 1.19 test bench for my mod upgrade, i did copy some things over.

**Comment by Shadows-of-Fire** [comment]
Affix nbt is locked in at generation time, so old data becomes stale when renames happen. This isn't really a bug, and there's no way to migrate them, just that there was a breaking rename in the 18->19 change.

You won't see this on new items, so this is safe to close
