### ISSUE TITLE
[1.19.2] Crash when entering certain modded dimensions. (No value present)

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apotheosis#759]
Title ^

Currently running a server and it seems the server crashes with something related to Apotheosis when entering certain modded dimensions.

**Versions:**
Minecraft: 1.19.2
Forge: 43.2.3
Apotheosis: 6.0.2
Placebo: 7.1.1
Patchouli: 77

**Crash Report**: https://gist.githubusercontent.com/Gbergz/d92dba3db1b4f0574a49c802d2affde9/raw/91c655969b3ca532a182ad0b6c12a896ba5f9596/gistfile1.txt

**Edit: Crash Report 2**:
https://gist.githubusercontent.com/Gbergz/8a9a1edf4581a46c844992f87db580ae/raw/905422be54bb24906d88c6fb086e6afeff8f48f2/gistfile1.txt

**Comment by Cicopath** [comment]
I'm experiencing the same issue. Entering dimensions from The Lost Cities, Ad Astra!, and Deeper and Darker all seem to trigger the Apotheosis crash.

Here's my crash log:

[crash-2023-01-14_18.22.43-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10419129/crash-2023-01-14_18.22.43-server.txt)

**Comment by Cicopath** [comment]
Update: The issue is known, and I was told to downgrade to the second latest version of Apotheosis and Placebo, and now my game is no longer crashing. Do this in the meantime.

Edit: Apotheosis 6.0.1 and Placebo 7.0.1.

**Comment by Gbergz** [comment]
@Cicopath Thanks for mentioning that, but a real fix would be nice aswell :)

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Placebo/commit/aa2c5a0935fe555960a519e7e1dcb4fe485e1bc4
