### ISSUE TITLE
My game just crashes. 

### ISSUE THREAD

**Issue by MrBlackhole618** [Shadows-of-Fire/Apotheosis#764]
It crashes opon startup for no apparent reason. 
Is there anything I can try?

**Comment by Shadows-of-Fire** [comment]
Not unless you provide a crash report

**Comment by MrBlackhole618** [comment]
[crash-2023-01-15_22.52.12-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10427094/crash-2023-01-15_22.52.12-client.txt)

**Comment by Shadows-of-Fire** [comment]
How did you end up on this repo?  You have none of my projects installed.  Your crash report is coming from jei.

**Comment by MrBlackhole618** [comment]
whoops wrong crash report then 
[crash-2023-01-09_16.10.10-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428549/crash-2023-01-09_16.10.10-fml.txt)
[crash-2023-01-09_23.59.53-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428550/crash-2023-01-09_23.59.53-fml.txt)
[crash-2023-01-15_15.57.19-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428551/crash-2023-01-15_15.57.19-fml.txt)
[crash-2023-01-15_17.06.12-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428552/crash-2023-01-15_17.06.12-client.txt)
[crash-2023-01-15_17.45.15-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428553/crash-2023-01-15_17.45.15-fml.txt)
[crash-2023-01-15_22.50.00-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428554/crash-2023-01-15_22.50.00-fml.txt)
[crash-2023-01-15_22.52.12-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428555/crash-2023-01-15_22.52.12-client.txt)
[crash-2023-01-16_12.05.10-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10428556/crash-2023-01-16_12.05.10-client.txt)
Its one of these reports.
