### ISSUE TITLE
Apotheosis Boss Drops cause my game to crash with the enhanced armaments reloaded mod.

### ISSUE THREAD

**Issue by FruitW0rld** [Shadows-of-Fire/Apotheosis#765]
When I get a drop from an apotheosis boss, the item crashes my game and in the crash report it seems to be a conflict with the enhanced armaments reloaded mod.

**Comment by Shadows-of-Fire** [comment]
at minimum a crash report is required

**Comment by FruitW0rld** [comment]
At the moment I can't do it. I'll do it tomorrow. Sorry I couldn't add it now.

**Comment by FruitW0rld** [comment]
Here's the crash report:

[crash-2023-01-14_12.46.51-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10469284/crash-2023-01-14_12.46.51-client.txt)

**Comment by RoyalReject** [comment]
Issues is caused by this mod looks like https://www.curseforge.com/minecraft/mc-mods/enhanced-armaments

**Comment by Shadows-of-Fire** [comment]
yeah that's entirely on the other mod
