### ISSUE TITLE
A problem about affix identifying weapons

### ISSUE THREAD

**Issue by 48004800** [Shadows-of-Fire/Apotheosis#768]
I use the reforge table to add affix to the weapon. But a lightsaber was identified as a shield

The details are in this issue, and someone has given the code problem

https://github.com/coolsimulations/SurvivalPlus-Lightsabers/issues/14

**Comment by Shadows-of-Fire** [comment]
This is just an unfortunate side effect of how autodetection worke.  If you want them to be picked up as swords, use the config to override the type.

**Comment by 48004800** [comment]
> This is just an unfortunate side effect of how autodetection worke. If you want them to be picked up as swords, use the config to override the type.

I see. The problem is solved

I also have a question whether the rarity of affixes of items can be specified in the loot table
I noticed that the rarity is set in the loot table of the chest
However, the item will be obtained randomly and the item ID cannot be specified. Whether the item ID can be determined by modifying the loot table
I mean a function to determine the rarity

**Comment by Shadows-of-Fire** [comment]
If you are using the affix loot pool entry, you can specify a rarity.  I don't have docs so you'll have to read the serializer https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/loot/AffixLootPoolEntry.java#L78
