### ISSUE TITLE
[Feature Request] Stats sheet

### ISSUE THREAD

**Issue by JWTHDYTWA** [Shadows-of-Fire/Apotheosis#769]
Please add a way to see your current attributes.

**Comment by Shadows-of-Fire** [comment]
This is planned (and has been for a while) but other things are taking priority recently.

**Comment by rtxyd** [comment]
I recently try a mod with the this feature and it has a affix system like apotheosis, this mod's stats sheet is able to show the stats modifier of other mod and the final number of particular attribute. But personally, too op for most time.
https://github.com/Minecraft-LightLand/L2Artifacts
https://www.curseforge.com/minecraft/mc-mods/l2-artifacts

**Comment by Shadows-of-Fire** [comment]
This is slated for 6.3.0
