### ISSUE TITLE
Can't use shears in dispensers

### ISSUE THREAD

**Issue by Elsker99** [Shadows-of-Fire/Apotheosis#77]
So i use automatic wool farms in my worlds to get different colors while im doing other things. After getting this mod I have found that because of the separate classification of the shears causes them to not work with dispensers anymore. Instead of being used they just get spit out like how droppers do to everything. I know it got changed to be able to enchant it so i hope that function can be brought back and still be able to use enchantments.

**Comment by Shadows-of-Fire** [comment]
Vanilla is probably keeping a hard reference to the old shears item (which I've replaced in the game registry).  I'll need to find it and make it point to the new one.
