### ISSUE TITLE
Apotheosis not remembering HP on armor when logging in

### ISSUE THREAD

**Issue by MrAek546** [Shadows-of-Fire/Apotheosis#770]
Hello, I just updated my server from 6.0.1 to 6.0.3, ever since then when logging on/off on my server (all the mods 8) I lose all my stacked HP bars, upon some research it looks like Apotheosis is not recalling the HP on gear, so it's loading me in without all the HP on gear.

We've decided to roll back to server until this issue is fixed.

**Comment by Shadows-of-Fire** [comment]
Do you have AttributeFix installed?

**Comment by MrAek546** [comment]
Yes. When rolling back it still had the same issue. It's remembering hp from other mods (heart containers, croptopia unique foods) but not apotheosis gear stats. So it may be something with the profile?  Super weird cause there was no problem till we attempted to upgrade.

But when rolling back we just launched the unchanged old server version and the issue persisted.

**Comment by FrozenDragon0** [comment]
Seems both AttributeFix and Max Health Fix don't fix this issue at all, it's quite annoying logging back into a world or going through the End exit portal to have your health completely just reset.

**Comment by Shadows-of-Fire** [comment]
This is the bug that max health fix is supposed to fix.  If it doesn't fix it, you should bring up an issue with them
