### ISSUE TITLE
Crash with astikor carts 1.18.2

### ISSUE THREAD

**Issue by Blugori** [Shadows-of-Fire/Apotheosis#772]
Hi, when apotheosis and astikor carts are installed, the game crash on launch.

Astikor carts : 1.1.2
Apotheosis : 5.7.7
Placebo : 6.6.6
Patchouli : 71.1
Forge : 40.2.0
Minecraft : 1.18.2

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10527382/latest.log)
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10527384/debug.log)

**Comment by RConTRS** [comment]
i have encountered the same issue recently according to your log, i can say there are many mods crashing with astikor carts maybe cause it's early on 1.18.2 i don't really know

**Comment by Shadows-of-Fire** [comment]
Closing as an issue on the other mod's end
