### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#773]
https://paste.gg/p/anonymous/a2bedfa507ab42baa71442a936f841ca

**Comment by Shadows-of-Fire** [comment]
This is not an apoth issue, as this is a cme and apoth is on the main thread here.  You have another mod modifying the entity list off-thread, which is causing the crash.  Unfortunately that mod is not named in the stacktrace, so you will have a hard time finding it.

**Comment by ghost** [comment]
https://paste.gg/p/anonymous/a765f6e5f52f4a04b822f7c801a4cd98
This one too?

**Comment by Shadows-of-Fire** [comment]
That one is different - still not apoth, and still a concurrency issue.  This time between a mod and vanilla, but the mod is not known.
