### ISSUE TITLE
Crash with cavespider-spawner with no ai

### ISSUE THREAD

**Issue by kolhed** [Shadows-of-Fire/Apotheosis#775]
I converted a spawner to cavespiders (using egg from dna from mobgrinder-mod) and added the fruit to remove ai. I also had added a comparator to redstone control it.
The moment the first spider spawned the server crashed.
I have a few other spawners with no ai and no crash.

I tried doing the same in a creative world and my client crashed as soon as the first spider spawned.
Before removing the ai I spawned a few spiders without any crash.

DW20 1.19 v1.1.1 modpack
Apotheosis 6.0.3

**Comment by RoyalReject** [comment]
Please share the crash log, Use a site lite pastebin or a github gist please

**Comment by kolhed** [comment]
https://pastebin.com/LAKqS8Y9

I noticed that in this pack spiders move differently (more "natural") might be a 1.19, but more likely a mod...

**Comment by kolhed** [comment]
yeah, this is the crashlog when I changed my creative spawner to normal spiders and it crashed the same
https://pastebin.com/UA17bmNy

**Comment by kolhed** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2449

they seem to have some kind of clue how to fix it in the modpack :) 
sorry if it wasn't apoteosis fault <3

**Comment by RoyalReject** [comment]
It caused by a bad interaction with a mixin from https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders, I tested this with a profile with just apotheosis and was able to get cave spiders to spawn fine with no ai, added this mod and crashed when attempting the same

**Comment by NoPro17** [comment]
Its more than just cave spiders

3 crashes with the cave spiders one with the wither skeletons on an airship

[crash-2023-02-07_13.40.58-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10679640/crash-2023-02-07_13.40.58-server.txt)

[crash-2023-02-07_13.19.09-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10679643/crash-2023-02-07_13.19.09-server.txt)

[crash-2023-02-06_18.50.33-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10679648/crash-2023-02-06_18.50.33-server.txt)


[crash-2023-02-04_22.39.49-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10679655/crash-2023-02-04_22.39.49-server.txt)

**Comment by Shadows-of-Fire** [comment]
The other linked crash is an unrelated CME.  The spider crashes are the fault of the other mod's mixin and I cannot fix them, you'll need to report it to them.
