### ISSUE TITLE
Conflict with Harder Spawners mod

### ISSUE THREAD

**Issue by Willem07** [Shadows-of-Fire/Apotheosis#776]
On its own server with a lot of mods, the items blaze rod, ghast tear, prismarine crystals, and fermented spider eye do not work on the spawner, and quartz does not work in the second hand either. In a single world, everything works. Do you think it could be related to other mods or do I need to enable rules in server.properties?

**Comment by Willem07** [comment]
Apotheosis-1.19.2-6.0.3

**Comment by RoyalReject** [comment]
Sounds like another mod is causing an issue, do you have logs? Or if it works in single in not multiplayer make sure the server and client have same mods and versions

**Comment by Willem07** [comment]
How can I provide my actions with a spawner in the logs if there are no actions there?

Here there are mods that work separately, do they have a conflict with apotheosis?

Server mods
![1](https://user-images.githubusercontent.com/51959206/216056190-958813ef-a0d4-475f-80ad-4bc6ee477246.png)
Server datapack
![3](https://user-images.githubusercontent.com/51959206/216056244-e7b86eb7-6fd2-40dd-920a-e112988afc72.png)
Client mods
![2](https://user-images.githubusercontent.com/51959206/216056213-4f25b5c0-743a-4686-9ffe-204cb52424bb.png)

**Comment by Willem07** [comment]
I found a conflict with the Harder Spawners mod. In the config according to the standard there are these values to which the spawner is reset

#Hostile Spawners: Player Range when hostile mobs start spawning
	#Range: 7 ~ 256
	requiredPlayerRange = 10
	#Hostile Spawners: Maximum Spawned Hostile Entities
	#Range: 3 ~ 256
	maxNearbyEntities = 9
	#Hostile Spawners: How far from spawner hostile mobs can spawn
	#Range: 4 ~ 256
	spawnRange = 9

**Comment by Willem07** [comment]
I also noticed another conflict with the Harder Spawners mod. There is a slow breaking spawner mechanic in mod, which does not work due to modified spawners in Apotheosis
