### ISSUE TITLE
Cannot Add Gems to Enchanted Items

### ISSUE THREAD

**Issue by ridaztor** [Shadows-of-Fire/Apotheosis#777]
I cannot add a Gem to Armor Pieces if their enchanted

i also have Polymorph in my Modlist, it shows me a working recipe, but i cannot select it

Happens on Version 1.19.2-6.0.3

**Comment by ridaztor** [comment]
Does not have anything to do with being entchanted... i can only add a gam once then it wont work anymore... also happens on 6.0.2

Leaving the Modpack i use here so you can investigate, if you need the world or anything else, just message me

[RiloCommunity.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/10550908/RiloCommunity.zip)

**Comment by Shadows-of-Fire** [comment]
https://github.com/illusivesoulworks/polymorph/issues/181
