### ISSUE TITLE
[Suggestion] More Affix Config Options

### ISSUE THREAD

**Issue by zinx10** [Shadows-of-Fire/Apotheosis#780]
So, the implementation of affix items is a really neat idea, and this is amplified with the existence of gems that you can socket into certain affixed items. However, when messing around the config options (whether for fun or for developing a modpack), some customization options are missing for these items. The changes/additions I'm about to suggest would tremendously help for balancing and further customization of affixed items. The changes are as follows:

Every quality type for affixed items (Common, Uncommon, Rare, Epic, Mythic) would have an option to set the minimum and maximum amount of empty socket slots available. On top of this, every quality type for affixed items would also have an option to set the minimum and maximum of affixed traits (i.e. +30% Crit Damage). That way, the person setting up the mod can decide how powerful each quality of affixed item can be in the game.

This would also allow for some more interesting changes modpack developers could do, such as making every affixed item have 0 affixed traits, but more empty socket slots for higher quality items. For example, I could make it where the empty socket counts for each quality of affix items be:

_Common - 1 Slot
Uncommon - 2 Slots
Rare - 3 Slots
Epic - 4 Slots
Mythic - 5 Slots_

That way, the power of the affix items comes from gem stones rather than their inherit nature. Higher quality items just have a larger potential for customization.

**Comment by Shadows-of-Fire** [comment]
This comes with the json-definition of the rarities, though it is not yet completed, it may arrive in 6.1.0.
