### ISSUE TITLE
Bosses not generating correctly

### ISSUE THREAD

**Issue by zookeper** [Shadows-of-Fire/Apotheosis#782]
We are using dw20 1.19.2 v 1.2.1 and it appears that items will generate but bosses refuse to spawn, no lightning, no color bars above head, the only boss Ive found is a Hoglin in the nether. The bosses refuse to spawn in the end and in the overworld

**Comment by Shadows-of-Fire** [comment]
Boss generation settings are very configurable.  Consult with the modpack author, as you have not described anything that could not be achieved through configuration.
