### ISSUE TITLE
Crash when loading world when Apotheosis and the Unique Enchantments are both present

### ISSUE THREAD

**Issue by Knight1night** [Shadows-of-Fire/Apotheosis#783]
The combination Apotheosis and any mod from the Unique Enchantments Series crashes the game when trying to load a new world. Below is a crash log
[crash-2023-02-12_00.17.24-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10714324/crash-2023-02-12_00.17.24-client.txt)

**Comment by Shadows-of-Fire** [comment]
Unique enchantments is known to be incompatible until they make some mixin changes on their end
