### ISSUE TITLE
[Suggestion] Option to disable Charms while in Inventory

### ISSUE THREAD

**Issue by slave2midna** [Shadows-of-Fire/Apotheosis#784]
Not sure it exists, couldn't seem to figure out a means of making it work. But I love the Potion Charms and effects, but I think it would be cool if they could be enabled only while set in a charm slot for curios. Or if there was a config option to disable their functionality while in the base inventory. To avoid charms stacking an such from a balance perspective.

**Comment by slave2midna** [comment]
Is this fix available in 1.18.2?

**Comment by Shadows-of-Fire** [comment]
don't believe so

**Comment by slave2midna** [comment]
Dang. No worries! Thank you for the response! We'll update one day for sure! Can't wait.
