### ISSUE TITLE
[1.18.2] Server Thread Error: Tried to load unrecognized recipe 

### ISSUE THREAD

**Issue by Lxazl5770** [Shadows-of-Fire/Apotheosis#785]
Version: 1.18.2-Forge_40.2.0 with Apotheosis 5.7.7

Everytime I enter my world, a popup shows that new recipes unlocked with some apotheosis items.

Although this problem won't make the game unplayable, I think this bug should be fixed.

For example, line 7638 in the log below reads:
`[132��2023 16:15:35.868] [Server thread/ERROR] [net.minecraft.stats.ServerRecipeBook/]: Tried to load unrecognized recipe: apotheosis:crystal_seashelf removed now.`
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10720126/latest.log)

**Comment by Shadows-of-Fire** [comment]
Various things have been attempted to fix that.  If it's still happening, it means none of them have worked.  Since it doesn't cause any issues, I've elected to ignore it.
