### ISSUE TITLE
[Bug] Speed boost on armor twitching

### ISSUE THREAD

**Issue by yeeterwa** [Shadows-of-Fire/Apotheosis#788]
So when I put armor on that has some kind of speed boost the character keeps twitching like going on and off constantly with the effect. Same thing happens with health boost, it keeps adding and removing hearts every milisecond. Everyone on the server keeps experiencing this.

**Comment by Shadows-of-Fire** [comment]
To my understanding this is a bug with another mod causing attribute modifiers to not apply correctly.  If you add a modifier to item nbt via /apoth attribute, does it also flicker?

None of this happens in isolation

**Comment by yeeterwa** [comment]
> To my understanding this is a bug with another mod causing attribute modifiers to not apply correctly. If you add a modifier to item nbt via /apoth attribute, does it also flicker?
> 
> None of this happens in isolation

I will try it tomorrow and see if it fixes it.

**Comment by yeeterwa** [comment]
> To my understanding this is a bug with another mod causing attribute modifiers to not apply correctly. If you add a modifier to item nbt via /apoth attribute, does it also flicker?
It seems to work when using it like that, so thank you

**Comment by yeeterwa** [comment]
> To my understanding this is a bug with another mod causing attribute modifiers to not apply correctly. If you add a modifier to item nbt via /apoth attribute, does it also flicker?
> 
> None of this happens in isolation

It only happens when I have items dropped from the bosses, is there a way to remove the modifier and put my own
