### ISSUE TITLE
[Suggestion] server friendly spawner modification

### ISSUE THREAD

**Issue by Teriderol** [Shadows-of-Fire/Apotheosis#789]
Apotheosis has been quite a staple of modded minecraft for years now. Very grateful for what it does. 
However, the spawner mechanics are known to be bad offenders on multiplayer servers were people can't handle responsibility. This usually results in a broad discard of the whole mechanic.
As is the case on a certain ATM gravitas server, should be fine though... 
However, somehow the combination of mods and this server modification leads to spawners ignoring light levels, ignoring spawn cap and hard to break.
Thus my suggestion: 
Is it possible to make a boolean for servers which would combine the comparator modification with the no AI modification and disable the worst offenders like spawn delay and ignore_players?

**Comment by RoyalReject** [comment]
This is already possible, you would need to create a datapack to override the default recipes for spawner modification, https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/recipes/spawner, you can change max/min values or disable it all together

**Comment by Shadows-of-Fire** [comment]
Yeah this can all be done with a datapack (or other recipe editor).  You can remove the recipes for the modifiers you wish disabled, and add a recipe that applies both redstone and noai at once.

**Comment by Teriderol** [comment]
So, you want every server which runs your spawner mod in a pack and does not want their server to die an early death to make a data pack or trust a random guy to make a datapack. Sir, I say this is ill advise.

**Comment by RoyalReject** [comment]
Datapacks are a vanilla feature, they are actually very useful at allowing things to be highly customized, but if you want to get upset about it gotta take it up with mojang as they themselves are moving to more data driven things.

**Comment by Teriderol** [comment]
not upset, at you at least. just dealing with some upstuck people who rather broad swipe remove then to think 2 seconds
