### ISSUE TITLE
Certus Quartz

### ISSUE THREAD

**Issue by OverWims** [Shadows-of-Fire/Apotheosis#790]
Certuz Quartz when mined with fortune 8 is dropping certus quartz dust not certus quartz crystals. This is kind of useless when it can only become silicon.

You seem to get both crystals and dust. But a lot more dust. It's like the first 3 levels of fortune are giving the crystals like normal then the next 5 are giving the dust.

**Comment by RoyalReject** [comment]
Seems like some mod is changing the loot table for certuz quartz. It might just be how fortune interacts with it. What mod is the dust from or what modpack are you playing?

**Comment by OverWims** [comment]
It's from applied energistics 2. It is definitely this mod causing it as it only started doing it when I upgraded my fortune to a higher level.

**Comment by RoyalReject** [comment]
What version of minecraft are you on?

**Comment by Shadows-of-Fire** [comment]
How blocks react to higher fortune levels is out of my control.  You'll have to take it up with ae
