### ISSUE TITLE
Cannot disenchant Apotheosis items in PneumaticCraft Pressure Chamber

### ISSUE THREAD

**Issue by FrederikRasmussen** [Shadows-of-Fire/Apotheosis#793]
When using the PneumaticCraft pressure chamber in a vacuum (-0.75 to -1.0 bar pressure) you can disenchant items by putting the item and a book inside. When trying to do this with an Apotheosis item, nothing happens, even if the Apotheosis item has a vanilla enchant.

![image](https://user-images.githubusercontent.com/3720563/221205266-16dcb320-3458-4e9c-8987-fb71febc2e0d.png)

Attempted disenchant was done on the above item, where I wanted the Looting II enchant off.

Minecraft version 1.19.2, Apotheosis version 6.03, PneumaticCraft version 4.3.2.

**Comment by Shadows-of-Fire** [comment]
@desht any idea?  My extra nbt shouldn't be impacting your code

**Comment by desht** [comment]
Offhand, no, but I'll see if I can get a chance to test something this weekend.

**Comment by Shadows-of-Fire** [comment]
This should probably be offloaded to PNC, as this is ultimately their disenchanter and not something I can debug or fix.

**Comment by desht** [comment]
Oh yeah, I was going to test this.  What's the easiest way to get a random Apotheosis item (i.e. with prefixes & suffixes) for testing purposes?

**Comment by Shadows-of-Fire** [comment]
`/apoth lootify <rarity>` while holding the item

**Comment by desht** [comment]
Just tested it, and it worked fine.  The Pressure Chamber removed Looting II (and other enchants) from an Apotheosis weapon without any problems, and spat out a Looting II book and the sword without the enchant, but still with the Apotheosis augmentation.

@FrederikRasmussen I don't know why it didn't work for you, maybe some other mod in your pack is interfering? But this definitely works as expected with just PNC:R and Apotheosis.

**Comment by FrederikRasmussen** [comment]
@desht Late response, but I'm unsure. I was testing an early build of E9E with Kanz at the time. During the next test session I'll make sure to create an issue on the PNC:R GitHub, assuming I can replicate the bug at all - so we can track it down properly.
