### ISSUE TITLE
The changes to configs are not being applied

### ISSUE THREAD

**Issue by villaxd123** [Shadows-of-Fire/Apotheosis#794]
I added the mod (Apotheosis) to my modpack, i disabled some modules and changed the max level of some enchantments, then i tried to make another change but this new change is not being applying.

As an example, i had before the "capturing 5" as max level, now i set to 3 as the max level and put only true to obtain by loot sources (treasureable=true, discovereable=false, lootable=false, tradeable=false), then i started Minecraft but the changes are not working.

All the changes was made with the game was closed and before re open de game i saved the new configuration.

I'm not on a server, is just my singleplayer survival world that i host localy to play in my LAN.

I'm playing on Minecraft 1.19.2 with Apotheosis v6.0.3

**Comment by Shadows-of-Fire** [comment]
Are the changes being reverted in the file or is the file staying unchanged, and the changes just not propagating into the game?

**Comment by villaxd123** [comment]
The file still have my new config, didn't get reverted, just the changes are not getting applied into the game.

**Comment by Shadows-of-Fire** [comment]
How are you testing if they are being applied or not?

**Comment by Shadows-of-Fire** [comment]
I can verify that the changes work properly on my end.

**Comment by villaxd123** [comment]
Yes, as my example, capturing still with max lvl 5 and other enchantments like knowledge of the ages was disabled before, but now I make it available again with max lvl 1 and nothing happens, protection is the same example, I set 4 before and now I want the 5 lvl but nothing happens.

**Comment by RoyalReject** [comment]
Changes in the config do not apply to items that have already been created/enchanted IIRC it only applies to items enchanted and such after the config change

**Comment by villaxd123** [comment]
> How are you testing if they are being applied or not?

I have JEI installed, and does show my changes.
The guide book didn't show the new available enchantments.
On the anvil the max lvl of some enchantments is not like the config file when I combine.

**Comment by Shadows-of-Fire** [comment]
If JEI shows the changes then the changes are being applied.  Other mods may interfere with this, but unless you can pinpoint exactly what mod is breaking what interaction, no changes will be made.

**Comment by villaxd123** [comment]
> Changes in the config do not apply to items that have already been created/enchanted IIRC it only applies to items enchanted and such after the config change

I know that, that's why I'm testing with new diamond tools, I have the books to test if my changes are working, I'm combining on the anvil, that's how I noticed that isn't working any single change.

**Comment by Shadows-of-Fire** [comment]
If you are in creative, there are no restrictions on what you may apply in an anvil, so if you are holding books of a higher-than-max level, they will apply successfully

**Comment by villaxd123** [comment]
> If JEI shows the changes then the changes are being applied.

But JEI isn't showing any chance applied.

**Comment by Shadows-of-Fire** [comment]
> I have JEI installed, and does show my changes.
then you really aren't making any sense.

In any case, the configs work as expected, and I have verified it manually.  You are responsible for resolving any mod conflicts you may have.
