### ISSUE TITLE
[1.16.5 bug]

### ISSUE THREAD

**Issue by Teddymancam** [Shadows-of-Fire/Apotheosis#795]
When using an enchantment table I am unable to view all available enchantments. 
I can click the button but the GUI does not load have to press esc to get out.

![ezgif-4-19254a8749](https://user-images.githubusercontent.com/78605885/222279391-51252788-f9e3-4cd2-ba39-40c0598b6f2e.gif)

**Comment by Shadows-of-Fire** [comment]
Other mods that render things can break the Forge GUI Stacking feature, which that menu relies on.  You'll have to isolate the mod and remove it from your instance.

**Comment by derellrtb** [comment]
Have you figured out which mod was clashing? Because i’m getting the same issue.
