### ISSUE TITLE
Spawner Soul Lantern modification broken for Blaze spawner

### ISSUE THREAD

**Issue by MajikalExplosions** [Shadows-of-Fire/Apotheosis#796]
The soul lantern modification is broken for Blaze spawners. I'm unsure if this is a Blaze-specific problem. I tested a single blaze spawner in a redstone-only world during daytime on the surface (so light 15 everywhere). Even with the soul lantern modification, no blazes spawn. Then, I moved the same spawner underground (including the soul lantern modification), and it started spawning.

Spawner settings were:
- Min/Max Delay: 20 (for faster spawning)
- Ignore Light

I also had a command block setup to kill all blazes every 2 seconds, to allow the spawner to continue spawning.

**Comment by Shadows-of-Fire** [comment]
Blazes already ignore light, so the modifier wouldn't actually produce any change.  Likely something else was blocking the spawn.
