### ISSUE TITLE
Log Spam Causing World Tick

### ISSUE THREAD

**Issue by DOOMDUDE643** [Shadows-of-Fire/Apotheosis#797]
[New Paste 1.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10877484/New.Paste.1.txt)

**Comment by Shadows-of-Fire** [comment]
The log error you're showing implies that a spawner is without it's block entity.  This isn't something I can fix, so you probably have some sort of mod conflict.

**Comment by DOOMDUDE643** [comment]
@Shadows-of-Fire Thanks for the assist at least i have some general direction now and can check my mods.
