### ISSUE TITLE
[1.19.2 bug] pre-enchanted items glitching

### ISSUE THREAD

**Issue by yeeterwa** [Shadows-of-Fire/Apotheosis#798]
I recently made a post about speed bug happening but its not only the speed. Its also happening with defence and max health. This only happens with items dropped from bosses that have some special effects and come pre-enchanted or enchanted using lootify command
Edit: link to video example
https://imgur.com/a/ArZuiut

**Comment by Shadows-of-Fire** [comment]
This is, as far as I can tell, caused by another mod breaking the attribute system.  It does not reproduce with just apotheosis in a dedicated environment or otherwise, so all I can tell you to do is remove mods until it stops.

**Comment by yeeterwa** [comment]
> This is, as far as I can tell, caused by another mod breaking the attribute system. It does not reproduce with just apotheosis in a dedicated environment or otherwise, so all I can tell you to do is remove mods until it stops.

Ok then, thank you
