### ISSUE TITLE
1.19.3 Game crashes with only apotheosis and it dependencys

### ISSUE THREAD

**Issue by Wafaloma** [Shadows-of-Fire/Apotheosis#799]
forge-44.1.21

My mod folder:
Apotheosis-1.19.2-6.0.3.jar
Bookshelf-Forge-1.19.3-17.0.3.jar
EnchantmentDescriptions-Forge-1.19.3-14.0.4.jar
Patchouli-1.19.3-78.jar
Placebo-1.19.2-7.1.2.jar

[crash-2023-03-06_21.17.30-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/10902051/crash-2023-03-06_21.17.30-fml.txt)
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10902055/latest.log)
![photo_2023-03-06_21-23-54](https://user-images.githubusercontent.com/127144250/223210278-fb70e7ec-98b3-4e70-9460-11e23344a039.jpg)

**Comment by RoyalReject** [comment]
Well apotheosis is only 1.19.2 not 1.19.3

**Comment by Shadows-of-Fire** [comment]
1.19.3 is not supported
