### ISSUE TITLE
Player or mob having NaN HP

### ISSUE THREAD

**Issue by Modrichsch** [Shadows-of-Fire/Apotheosis#800]
It probably has something to do with this:
[ne.mi.co.Co.apotheosis/COREMODLOG]: Patching CombatRules#getDamageAfterMagicAbsorb

When it happens to your character it goes as follows:
You take damage from a certain mob (while on full HP) and all your hearts go away as if you were dead, but you do not die and your health bar stays emty, the screen shakes and hostile mobs do not 'see' you
interaction with blocks is impossible

It is in a modpack with like 60 mods in 1.16.5 Forge 36.2.39

**Comment by Shadows-of-Fire** [comment]
1.16 is not supported, though this isn't caused by that coremod, as it is caused by a weird client/server desync.
