### ISSUE TITLE
apotheosis 6.0.1 crash (forge 43.2.3) 

### ISSUE THREAD

**Issue by arhp777** [Shadows-of-Fire/Apotheosis#802]
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/10933595/latest.log)

**Comment by Shadows-of-Fire** [comment]
Your log looks truncated.  It mentions a mixin conflict but the other mod's mixin is skipped, and a crash does not happen.

In any case, this is not an apoth bug, and it is on you to not install conflicting mods.
