### ISSUE TITLE
Hello, when will it be released on version 1.19.3

### ISSUE THREAD

**Issue by hxndler** [Shadows-of-Fire/Apotheosis#807]
:D

**Comment by Shadows-of-Fire** [comment]
it won't be

**Comment by hxndler** [comment]
I respect you very much as a mod maker

> :D

**Comment by hxndler** [comment]
> it won't be

why?((

**Comment by Shadows-of-Fire** [comment]
Because 1.19.3 has no player-facing changes and is essentially a snapshot.  There is a very large port overhead for what is effectively zero gain from a player (or developer) perspective.
