### ISSUE TITLE
1.19.2 Crash with latest apotheosis and REI

### ISSUE THREAD

**Issue by Saereth** [Shadows-of-Fire/Apotheosis#808]
Crashes when you try to search in REI
https://gist.github.com/Saereth/a2f58ffa1257336dcebb484a978893d2

**Comment by Shadows-of-Fire** [comment]
Why is REI adding a gem item to the tab page?  Those are not added by me for this exact reason

**Comment by Saereth** [comment]
I have no idea, want me to open an issue with them as well?

**Comment by Shadows-of-Fire** [comment]
Perhaps.  Arguably apoth shouldn't be crashing if an invalid item is looked at, but rei also shouldn't be adding it to the display

**Comment by HalsekiRaika** [comment]
In terms of the game ending abnormally, I get a similar error when I mouse hover LegacyGem on REI when I install LegendaryTooltips and the game is forced to end. (This one did not output a crash log)
I hope this is of some help...

Error Log
https://gist.github.com/HalsekiRaika/957b52bb39eb001c71f9befedcbb6630

Mod List
https://gist.github.com/HalsekiRaika/6c98b56c0e594fb6e58a78be51b83868

**Comment by Shadows-of-Fire** [comment]
fixed for 6.1.2 - though REI shouldn't be adding this item to the creative tab.
