### ISSUE TITLE
Spawner mob cap

### ISSUE THREAD

**Issue by AntoRod** [Shadows-of-Fire/Apotheosis#81]
Forge 1.12.2-14.23.5.2838
Apotheosis-1.12.2-1.10.5
i'm on a custom modpack, but i don't know if it changes anything, i'll test with only apotheosis later and edit.

When i use a nether star on a spawner, if i update the spawner (restart server, break it etc..), it also apply the "ignore spawn cap" in addition to the "ignore player", if i remove it with chorus fruit, it removes it until next update of the block, only way to remove it completely is with the nether star....

**Comment by MissPotato** [comment]
I'm getting this same issue with a spawner in version 1.10.5. We're on a dedicated server and the spawner is spawning infinite villagers unless we remove the nether star upgrade, we can temporary disable it by inverting a chorus fruit but as OP said reloading chunks/server causes it to regain the spawn camp. A great way to test this is silk touching the spawner as even breaking the spawner casuses it to reappear.
