### ISSUE TITLE
Game crash when trying to upgrade socketed diamond pickaxe to netherite (version 1.19.2-6.1.2)

### ISSUE THREAD

**Issue by GothCartel** [Shadows-of-Fire/Apotheosis#813]
Hi, 

I got the following error and complete game crash when trying to upgrade a diamond pickaxe to a netherite one. The pick was enchanted and had two gems in sockets (1 extra free socket). When reloading the world the pick and netherite ingot are sitting on the ground next to smithing table. 

Included is full crash log.

Error: java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.tuple.Pair.getValue()" because the return value of "shadows.apotheosis.adventure.affix.socket.gem.LegacyGem.getStoredBonus(net.minecraft.world.item.ItemStack)" is null

[crash-2023-03-18_20.54.52-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11009585/crash-2023-03-18_20.54.52-client.txt)

**Comment by Shadows-of-Fire** [comment]
Interesting.  The error would claim you have a broken legacy gem in the item (presumably the resulting item), but that should be impossible if the source item was valid.

**Comment by GothCartel** [comment]
Indeed so, it was certainly a valid gem, I believe I located it in a born in chaos dungeon chest. The pick works as it should, bonuses work from the socketed gems, the only error occurs when trying to upgrade it to netherite .

**Comment by rtxyd** [comment]
@Shadows-of-Fire I also get the same crash, when I put sword with free socket and "vial_of_extraction" into smithing table. See conclusion below.

**Comment by rtxyd** [comment]
Just before, I test more situations with "vial_of_extraction". 
Make a conclusion,
1,  0 socket, not crash.
2,  1, 2, 3 sockets(all free sockets), crash.
3,  No free sockets, not crash.
4,  At least 1 free sockets, crash.

[crash-2023-03-19_21.28.13-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11011157/crash-2023-03-19_21.28.13-client.txt)
