### ISSUE TITLE
Behavior about critical mechanic

### ISSUE THREAD

**Issue by rtxyd** [Shadows-of-Fire/Apotheosis#815]
MC version:1.19.2
placebo: 7.1.5
apotheosis: 6.1.2
I test the critical damage with dummmmy, jei, and apotheosis. It seems critical mechanic is not as what I recognized. 
Conclusion, 
0, Base critical damage is 0.
1, There is a not low base critical chance for weapon with only critical damage, and if the critical chance enough, base damage will always be multiplied.
2, Critical chance above like 30% seems a trigger to another critical mechanic, deal (1+ "critical damage +%") * 150% damage.
Because of the key words of weapons and gems are basically the same descriptions for same affixes, I just wonder if the mechanic is working as intended.

**Comment by Shadows-of-Fire** [comment]
Critical hits interact as you would expect unless you are jumping (invoking a vanilla crit)

i.e. you have X% chance to deal +Y% damage, unless you are doing a jump crit, in which case you deal the formula you described above (X% chance to deal 150% * Y% damage)

**Comment by rtxyd** [comment]
@Shadows-of-Fire I didn't jump, but I get 70% critical chance and +0% critical damage, it behaved the same with jump hit. Deal 150% damage. You can try with sword like this, 
here is the result
![KS5TZAT)DB19`4(A)Z$LVHQ](https://user-images.githubusercontent.com/65117312/226159443-29dac408-70e8-4cf0-a932-3bc96e63e86c.png)

![ICOI~YR}U}VEIZS`PI80`QL](https://user-images.githubusercontent.com/65117312/226159476-007a7207-6eb5-4984-9f33-2a51918cf7e0.png)

**Comment by Shadows-of-Fire** [comment]
Yes, you have a base critical damage of 150% (representing the jump crit damage)

**Comment by rtxyd** [comment]
If I don't have +crit chance affix, it can still be mutipilied . Test with this sword.

![)@C4EAVP XJBLFL19B7IN@L](https://user-images.githubusercontent.com/65117312/226160071-08ff3b2e-ba5e-4197-8b2e-16a20d87abb9.png)

![O(O_VLMOP`1H40FEPO49JQR](https://user-images.githubusercontent.com/65117312/226160064-bcb3c8ee-a2b3-49a4-a9b6-799581277611.png)

**Comment by rtxyd** [comment]
And if my critical chance is low, like 25%, I can't deal 150% damage.

**Comment by rtxyd** [comment]
@Shadows-of-Fire And the formula I described above is the behavior from my test, not as you told me. 
There are two condition,
1, If I have low critical chance or 0 chance, I may deal X * (1+Y% critical damage) damage. 
2, If I have high critical chance, like 70%, I may deal normal X * (1+Y% critical damage) or critical  X * (1+Y% critical damage) * 150% damage.

**Comment by Shadows-of-Fire** [comment]
Is your base critical chance value set to 1.5?  You can check it with /attribute
Old versions of the mod would incorrectly set the base value.

**Comment by rtxyd** [comment]
@Shadows-of-Fire That's it, it's 1.0, I don't know this until now. Thanks. But if there's a wiki, I may solve it myself and not bother you.
![image](https://user-images.githubusercontent.com/65117312/226160755-cdde82ab-87d0-4e69-9b08-14318b85ec25.png)

**Comment by rtxyd** [comment]
Wait this is crit damage, and this is chance,
![image](https://user-images.githubusercontent.com/65117312/226161019-3a194de8-0df1-457b-9da5-50efb2ae50bf.png)

**Comment by Shadows-of-Fire** [comment]
Yes, old versions had them swapped.  You can fix them with the command by changing the base values.

**Comment by rtxyd** [comment]
And what should I do next, the crit chance is 1.5, set to 1.0?

**Comment by rtxyd** [comment]
OK this works, thanks.
