### ISSUE TITLE
Crash after updating placebo

### ISSUE THREAD

**Issue by KostromDan** [Shadows-of-Fire/Apotheosis#823]
Crash on server when first player joining it.
[crash-2023-03-23_07.29.22-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11046978/crash-2023-03-23_07.29.22-server.txt)
[2023-03-23-2.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11046981/2023-03-23-2.log)

**Comment by Shadows-of-Fire** [comment]
Placebo 7.1.6 is for Apotheosis 6.1.3, 6.1.2 will not work.
