### ISSUE TITLE
Update placebo and apotheosis cause multiplayer nullpoint exception on my friend entering the world.

### ISSUE THREAD

**Issue by rtxyd** [Shadows-of-Fire/Apotheosis#824]
MCversion: 1.19.2
Apotheosis: 6.1.3
placebo: 7.1.6

Test with lanserverproperties 1.9.1, Apotheosis, placebo .
Single player OK, but my friends can't enter our save  on multiplayer after update the apotheosis, so I made another test with only these mod. And previous version of these two mods also no problem.

ps. lanserverproperties is a mod to chose the net port that my friend can access.
here the debug file.

**Comment by rtxyd** [comment]
waite a minute, I upload a wrong file.

**Comment by rtxyd** [comment]
![I6XD2_JBM}IVQY2_GLT%3BJ](https://user-images.githubusercontent.com/65117312/227133669-a5704e76-b6d9-4ca3-b416-9b598d8806f9.png)

[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11048075/debug.log)

**Comment by Shadows-of-Fire** [comment]
fixed in 6.1.4
