### ISSUE TITLE
Apotheosis boss dropped item always includes "misc.apotheosis.affix_name.three"

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [Shadows-of-Fire/Apotheosis#826]
Mod version: 6.1.5
About #818, I found Apotheosis boss dropped item always includes `misc.apotheosis.affix_name.three` suffix, and this item cannot be renamed by anvil. Even changing the language to English, this bug doesn't be fixed.
![2023-03-24_08 56 55](https://user-images.githubusercontent.com/37864486/227397831-6da45530-76ba-4b8f-8edb-10aebc84fc10.png)

**Comment by mc-kaishixiaxue** [comment]
6.1.5
Fixed an issue where boss names were failing to translate.

**Comment by Shadows-of-Fire** [comment]
This issue was present in 6.1.4, but does not persist in 6.1.5 - However, the fix is not retroactive.  Reforging the item can fix the name though.
