### ISSUE TITLE
Tooltip mistake when Jade shows droped item entity with socket.

### ISSUE THREAD

**Issue by rtxyd** [Shadows-of-Fire/Apotheosis#827]
MC version: 1.19.2
placebo: 7.1.7
Apotheosis: 6.1.5
Jade: 8.8.1

This will not influence gameplay. But may provide some message.

![image](https://user-images.githubusercontent.com/65117312/227402318-2094cf6c-1e20-48fc-9de7-a41470ef1fae.png)

![4AR~W{KK6N~M%{$G}0N486Q](https://user-images.githubusercontent.com/65117312/227402357-de85b0f9-6d42-41d7-aac2-b44c935dc635.png)

**Comment by Shadows-of-Fire** [comment]
This is not something apoth can fix - it means Jade is not properly supporting forge tooltip components.

**Comment by rtxyd** [comment]
OK, I will post this on Jade and see.
