### ISSUE TITLE
KoTA III is broken (OP)

### ISSUE THREAD

**Issue by mikaba-eu** [Shadows-of-Fire/Apotheosis#829]
The ratio from Scavenger III is to broken.
I kill with my sword 1 cow and reach level 30 from level 15.
You can reduce that to even *5 instant of *25 and it should be fine too:

https://github.com/Shadows-of-Fire/Apotheosis/blob/0e54ea61e183650598cf53a7cda650d572c3f23c/src/main/java/shadows/apotheosis/ench/enchantments/masterwork/KnowledgeEnchant.java#L48

![grafik](https://user-images.githubusercontent.com/117845495/227720074-e07e9102-c059-4135-8cd9-dbb19f916bd2.png)

**Comment by Shadows-of-Fire** [comment]
1. This is Knowledge o the Ages, not Scavenger
2. This enchantment is designed for this exact purpose, since apoth demands high xp levels later in the game.

Anyhow, if you don't like it, you can decrease the max level.  I could probably make the `25` a configurable value though.
