### ISSUE TITLE
'apotheosis:superior_sigil_of_enhancement' crashes mc

### ISSUE THREAD

**Issue by arhp777** [Shadows-of-Fire/Apotheosis#830]
[crash-2023-03-28_15.08.22-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11089875/crash-2023-03-28_15.08.22-client.txt)

**Comment by rtxyd** [comment]
update your mod version,pls

**Comment by Shadows-of-Fire** [comment]
duplicate of #813
