### ISSUE TITLE
on hit wont work with Tinkers Construct

### ISSUE THREAD

**Issue by qwearchangel** [Shadows-of-Fire/Apotheosis#831]
![image](https://user-images.githubusercontent.com/11604316/228290468-262cdc16-56fd-4c00-9ef1-0ddc96f961da.png)

Got this sword with the on hit weakness and ancient knowledge, but when i hit mobs i wont get the buff nor wont the surviving mobs get weakness.

Apotheosis-1.18.2-5.7.7.jar
TConstruct-1.18.2-3.6.3.111.jar
Forge -40.2.0

**Comment by Shadows-of-Fire** [comment]
mc 1.18 is no longer supported
