### ISSUE TITLE
Arrow bugs.

### ISSUE THREAD

**Issue by KostromDan** [Shadows-of-Fire/Apotheosis#832]
1. Achivement take aim will not work with apotheosis arrows.
2. Arrow rendering is absolutely incorrect with this affixes.
![image](https://user-images.githubusercontent.com/90044015/229207240-9f0945cc-7644-43e9-acfd-295225772820.png)
The trajectory can vary up to 30 degrees.

**Comment by KostromDan** [comment]
3. Dragon can be cheated with obsisian arrows. When he landed, you can shot very many arrows on top of him, and then he start fly, all arrows fall and kill him. Not reproducable with vanilla arrows.

**Comment by Shadows-of-Fire** [comment]
Arrow rendering simply isn't build to handle very fast arrows.  I'm not inclined to rewrite it entirely to make it work properly, so I'm going to leave it as-is.

As for the obsidian arrows, their code is the same as vanilla arrows, so nothing to fix there either.

**Comment by KostromDan** [comment]
@Shadows-of-Fire 
You can fix obsidian arrows glith.
I fixed it for my modpack with this kubejs script.
```js
EntityEvents.hurt(event => {
    if (event.entity.type == "minecraft:ender_dragon") {
        let center_bedrock = 60
        for (let i = 80; i > 40; i--) {
            if (event.level.getBlock(0, i, 0).getId() == 'minecraft:bedrock') {
                center_bedrock = i
                break
            }
        }
        if (event.source.type == "arrow" && Math.sqrt(event.entity.blockPosition().distSqr(new $BlockPos(0, center_bedrock, 0))) <= 5) {
            event.cancel()
            return;
        }
        ...
        ```
