### ISSUE TITLE
White Candle crash Game (Include ATM8)

### ISSUE THREAD

**Issue by JCSweetHeart2022** [Shadows-of-Fire/Apotheosis#834]
The white Candle from Apotheosis make follow Issues:

`Apotheosis : Enchantment/]: Failed parsing enchanting_stats file apotheosis:white_candle.`

This Issues was few times and special as we was in the World "The Other" but im not sure was that a Building and/or down from the Ground into a Cave or whatever.

We using follow Version of the Modpack "ALL THE MODS 8" : **1.0.15**

I and my Players hope that the Mod-Devs or anywho from here can help to fix it.

Thanks

PuppyBosko.

PS: When you need more Information, can you answer me here and i can write it back so fast as possible

**Comment by Shadows-of-Fire** [comment]
This doesn't crash the game, it just results in a file failing to load.  The file should be fixed now.
