### ISSUE TITLE
[1.19.2] Crash: "Weight should be >= 0".

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apotheosis#836]
Title^

Not sure what triggers this as this happens on a public server I run.

**Versions:**
MC: 1.19.2
Forge: 43.2.6
Placebo: 7.1.7
Apotheosis: 6.1.5

**Crash-report**: https://gist.githubusercontent.com/Gbergz/7f2e3ecd9204a19987affc4460ea8854/raw/2e08d549ba192ba5a19863b9d9a79d665c92f57c/gistfile1.txt

**Comment by Shadows-of-Fire** [comment]
Hm, what probably happened here is a user with sufficiently negative luck triggered an item to have a negative weight (which causes this crash).  I may need to guard against negative luck values.

**Comment by complicitsalami** [comment]
I'm also running into this issue in single player, this is the crash report I get:

https://pastebin.com/Ks5FnhrX

Versions:
MC: 1.19.2
Forge: 43.2.8
Placebo: 7.1.7
Apotheosis: 6.1.5

**Comment by Shadows-of-Fire** [comment]
Fixed in placebo 7.2.0
