### ISSUE TITLE
Reintroduced Gem Dupe Glitch #686

### ISSUE THREAD

**Issue by jondood** [Shadows-of-Fire/Apotheosis#839]
Exact same method - using the smithing table and vial of extraction, inserting multiple vials alongside the item, and shift-clicking the gem causes as many duplicates as you have vials. Tested in 6.1.5 (Current newest ATM8 pack, haven't confirmed if works in the newest version)

**Comment by Shadows-of-Fire** [comment]
fixed in 6.2.0
