### ISSUE TITLE
[Feature Request] Hide item enchantments

### ISSUE THREAD

**Issue by JWTHDYTWA** [Shadows-of-Fire/Apotheosis#842]
I suggest to add a vial that hides enchantments in the tooltip. There is a minecraft native NBT tag `HideFlags: 1` which does exactly what is needed. I want this because it's usually too many lines in item tooltips on modpacks.

![изображение](https://user-images.githubusercontent.com/30724185/230481683-3c194278-a973-427f-8911-1d3446a2bdd3.png)

**Comment by JWTHDYTWA** [comment]
UPD:
Actually it would be better if enchantment list is shown only when some key is being held. Something like [Shift].

**Comment by Arceus-77** [comment]
That is an OP axe Sharpness 40, Unbreaking 8, looting 20!

**Comment by Shadows-of-Fire** [comment]
I think this is best left to mods which try to manage tooltip rendering.
