### ISSUE TITLE
java.lang.NullPointerException: null key in entry: null=shadows.apotheosis.village.fletching.arrows.MiningArrowRenderer@36acfcff

### ISSUE THREAD

**Issue by LordM4x** [Shadows-of-Fire/Apotheosis#844]
No clue what causes this but I'll attach the logs
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11183539/latest.log)

**Comment by rtxyd** [comment]
check your resource pack, try unloading it and see if it's solved.

**Comment by Shadows-of-Fire** [comment]
This is caused by Astikor Carts.  A random mod gets blamed because they are registering entity renderers improperly and breaking other mods.

**Comment by LordM4x** [comment]
It seems to be an issue with geckolib since it does not crash if geckolib isn't there
