### ISSUE TITLE
Crash to Windows Blue Screen

### ISSUE THREAD

**Issue by TronWoWGamer** [Shadows-of-Fire/Apotheosis#845]
I have had this happen several times now in more than 1 modpack - currently playing TNP Limitless 6 but also had this in ATM 8

Sometimes when mousing over a weapon/tool/armor with the new affixes, the game freezes and eventually crashes out to a blue screen, and I have to reboot my computer.  I am using the Curseforge Launcher for both modpacks.  

The error is "Unexpected Store Exception" (yeah, I know, it's a lame brain windows error that really doesn't explain anything except I think it has to do with a hard drive write process failing or getting corrupted_

ATM8 is on Forge 43.2.6 and Apotheosis is version 1.19.2-6.1.5

Limitless 6 is on Forge 43.2.6 and Apotheosis is version 1.19.2-6.1.5

Every time this has happened I have been mousing over affixed items in my backpack.

**Comment by Shadows-of-Fire** [comment]
So, nothing a mod can do can cause a BSOD to happen.  You have other problems (probably hardware failures), and something that is happening at that time is triggering it.  It is very likely to be a RAM failure or a hard disk failure (though more likely a ram failure).
