### ISSUE TITLE
Crit Rate / Crit Damage - 1.19.2 forge

### ISSUE THREAD

**Issue by Qualthalas** [Shadows-of-Fire/Apotheosis#847]
Crit rate and Crit damage added through weapon affixes do not work at all (crit rate doesnt add and crit dmg is x1.50 regardless)
Gems do work though, with gemmed weapons multicrits also work while jumping (falling)

Crit damage gems add flat dmg% instead of a crit dmg multiplier and the dmg % is also incorrect

**Comment by rtxyd** [comment]
check the version of your Apotheosis, if it's 6.1.2 or below. See #815

**Comment by rtxyd** [comment]
And simplely speaking, there is an in-game command: /attribute , you can check your base value about Apotheosis attributes. Just follow the index of this command to find attributes about critical hit.

**Comment by Qualthalas** [comment]
> And simplely speaking, there is an in-game command: /attribute , you can check your base value about Apotheosis attributes. Just follow the index of this command to find attributes about critical hit.

seems to have fixed the base issue, thank you
but i can't figure out the multicrits now, jump crits just do the regular crit dmg
(crit rate and crit dmg sword)
normal hit 25.5
normal crit 61.9
jump crit 61.9
jump multicrit - doesn't happen
![image](https://user-images.githubusercontent.com/36307669/230785090-e87989f0-b065-4fbd-938f-bae17f5f95fc.png)

**Comment by rtxyd** [comment]
@Qualthalas The overflowed crit chance will be caculated for next crit hit, so normally you need to increase your critical chance to over 100% to trigger that, and the jump crit seems a independent condition, and I haven't tested that deeply, so I think it's the mechanic that there should be.

**Comment by Shadows-of-Fire** [comment]
You cannot overcrit on a jump crit unless your critical strike chance exceeds 50%, for balance reasons.  Everything works as intended, it's just a little bit convoluted.

I might just decouple the apoth crits from jump crits entirely at some point.
