### ISSUE TITLE
2.2.3 For 1.14.4 Server Not working 

### ISSUE THREAD

**Issue by Squabbit** [Shadows-of-Fire/Apotheosis#85]
When i go to join my server with your mod on it come up with 
Internal Exception:io.netty.Handler.Codec.EncoderException:java.lang.nosuchFiedError: INGREDIENT_VANILLA 

I did updated my Forge. (28.0.75)
I have other mods it was working with before. (it's not them because I try going back to an older update where it did work)
i add 2 more thinking it was them, but i remove them and still get the same Error.
Also i tried going back to 2.2.1 Still doesn't work.

![MInes](https://user-images.githubusercontent.com/19509702/64057456-4e670d00-cbe0-11e9-9e48-e649bc11a3e6.PNG)

edit: 
I know it's this mod because i remove it and i could join my server.

Also sorry if spelling is bad not my strong suit.

**Comment by Shadows-of-Fire** [comment]
Apotheosis has not been upeated to forge 75 yet.  Use 45 for now.
