### ISSUE TITLE
Anvil mishandles renaming items with affixes/bosses mentioned in their item names

### ISSUE THREAD

**Issue by Twisted-Code** [Shadows-of-Fire/Apotheosis#852]
Lesson learned: the anvil does not know how to handle affixed item names. At one point I had Mark's Weakening Weakening Scimitar of Critical Thinking of Critical Thinking. I think it might've kept going if the anvil didn't have a relatively short text buffer for renaming.

![image](https://user-images.githubusercontent.com/7110033/231765327-c386dd15-6afc-47b6-afa5-4a3b41d3fcf6.png)
![image](https://user-images.githubusercontent.com/7110033/231765672-306f1d64-8a9e-429e-942d-04bfcd69be3f.png)
![image](https://user-images.githubusercontent.com/7110033/231766560-94ab077a-1244-4dab-ae9b-eff7f78d86a4.png)
![image](https://user-images.githubusercontent.com/7110033/231766712-3f93d15b-ec31-4706-8b9d-3427d1966096.png)

I suspect this may be a vanilla issue with translated text components, but if that's the case I would prefer to just be able to remove the translated components completely. If you can't patch the anvil, maybe you can add a way to strip them off through the reforging table. The way it's behaving currently, I have to pay an extra level when using the anvil on any loot from the adventure module (unless I can get the output to exactly match the previous item name)...

**Comment by Twisted-Code** [comment]
actually it occurs to me this doesn't happen with all loot, it might've been something about that specific item. Unfortunately I neglected to save the data, so... Hopefully it's about boss drops, not EXCLUSIVELY that item. I have to play around with it I guess

**Comment by rtxyd** [comment]
@macks2008 Boss drops have a translatable tooltip, that's defined in the item nbt, and it's different from another nbt tag "Name", so if you change the name in anvil, it's actually change the certain nbt tag named "Name" rather than the boss's name in another nbt tag.

**Comment by Twisted-Code** [comment]
okay so the part that reads like "Jon's Lacerating... of bloodletting" Is part of a different NBT node from the name node? Because apparently, as you can see in the screenshots, the anvil doesn't make a distinction, concatenating and writing the whole thing to the rename buffer, then writing that buffer back to the name NBT node when the anvil crafting is finalized.

**Comment by Shadows-of-Fire** [comment]
The prefix and suffix are not part of the standard name data, no.

The anvil won't update the name unless you type something in the box though.

**Comment by Twisted-Code** [comment]
@Shadows-of-Fire 
> The anvil won't update the name unless you type something in the box though.

Weird, then something's not right because I didn't type anything when I put the above-shown item into an anvil, and nonetheless it acted as if I was trying to rename the item. I even pulled the sword out and put it back in (TWSS...) just to be sure I didn't accidentally hit a key (easier than it sounds with me). That's what I mean by "I think it might've kept going". 
Sorry I wasn't more clear about the actual problematic behavior. My test case was kind of limited since I've yet to reproduce the issue (because I'm too lazy to dedicate time to test. Hoping it will come up again organically through gameplay so I have a better idea where to start)

**Comment by Twisted-Code** [comment]
Cannot reproduce.
