### ISSUE TITLE
Easy Anvil crash

### ISSUE THREAD

**Issue by PatrickPichler98** [Shadows-of-Fire/Apotheosis#853]
Hello when i disable the enchantments module on Apotheosis, the Anvil crash with the mod "Easy Anvil"

https://github.com/Fuzss/easyanvils/issues/23

**Comment by Shadows-of-Fire** [comment]
Easy anvils is, to my knowledge, incompatible with apoth.

From the looks of the crash report in the linked issue, they added some sort of compat which doesnt work when the ench module is disabled.
