### ISSUE TITLE
[1.19.2] Crash: "mouseClicked event handler"

### ISSUE THREAD

**Issue by itspaiva** [Shadows-of-Fire/Apotheosis#854]
The bug occurs when I press the single player button on the main menu, when I create a new world.
I came to the conclusion that it is the apotheosis, because when I disabled it, there was no more crash.
Maybe it's some incompatibility with another mod, but idk...

Versions:
MC: 1.19.2
Forge: 43.2.8
Apotheosis: 6.1.5
Placebo: 7.1.7

Crash-report:
https://mclo.gs/IqqVVbt
https://pastebin.com/0CvQFShf

**Comment by Shadows-of-Fire** [comment]
Unique enchantments is incompatible with apoth.
