### ISSUE TITLE
Rouge spawner generation causing java.lang.NullPointerException

### ISSUE THREAD

**Issue by DOOMDUDE643** [Shadows-of-Fire/Apotheosis#858]
[Spawner Issue Log.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11242103/Spawner.Issue.Log.txt)
 
not sure if user error but seems most likely the case since no one else seems to be having this problem, any help would be much appreciated.

**Comment by rtxyd** [comment]
DistantHorizons is currently a buggy mod, not sure exactly your problem is, but I suggest deleting it if it's not vanilla.

**Comment by Shadows-of-Fire** [comment]
The code responsible for getting that block entity immediately sets it in to the world the line prior
```java
		world.setBlock(pos, Blocks.SPAWNER.defaultBlockState(), 2);
		SpawnerBlockEntity entity = (SpawnerBlockEntity) world.getBlockEntity(pos);
		this.stats.apply(entity);
```

I suspect another mod is making this contractually invalid.
