### ISSUE TITLE
[1.14.4] Forge Version Incompatability

### ISSUE THREAD

**Issue by Morpheus1101** [Shadows-of-Fire/Apotheosis#86]
Mod sais it requires 28.0.74 to run when im using 28.0.9

**Comment by Shadows-of-Fire** [comment]
74 is a much larger number than 9

**Comment by Morpheus1101** [comment]
Arg, apologies, stupid Curse client...i though 28.0.9 was 28.0.90 .. i will remedy this which will solve all my issues
