### ISSUE TITLE
[Request] NameHelper for translation

### ISSUE THREAD

**Issue by t0piy** [Shadows-of-Fire/Apotheosis#860]
I was translating the mod into my language and I noticed that the translations were weird. I think it would be interesting to adapt the [util/NameHelper.java](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/util/NameHelper.java) code for possible translations

**Comment by Shadows-of-Fire** [comment]
That sounds like a nightmare, lol.  That file is one of the oldest pieces of legacy code in the codebase (it's originally from Deadly World).

**Comment by t0piy** [comment]
> That sounds like a nightmare, lol. That file is one of the oldest pieces of legacy code in the codebase (it's originally from Deadly World).

I thought it was relatively simpler lol. So no expectations to update this code for now?

**Comment by Shadows-of-Fire** [comment]
Probably not, no.

It relies on a lot of string concatenation and is user-editable, so the best thing you can do is translate the config file and provide that to servers running in your localization.

**Comment by t0piy** [comment]
> Probably not, no.
> 
> It relies on a lot of string concatenation and is user-editable, so the best thing you can do is translate the config file and provide that to servers running in your localization.

Sorry for the inconvenience, but can you tell me what is the simple step by step to do this (I talk about updating the NameHelper code for translation)? I have little experience with Java, so I don't know if it would be easy to do this on my own
