### ISSUE TITLE
Server Freezing at certain point

### ISSUE THREAD

**Issue by Xephiro9999** [Shadows-of-Fire/Apotheosis#861]
This issue occurs every so often, but it happens enough that I find it to be an issue... at these lines -- it freezes.
`[19Apr2023 05:01:24.200] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[19Apr2023 05:01:24.201] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTreasureOnly() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[19Apr2023 05:01:24.201] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTradeable() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
`

and the server usually takes 5 minutes to load, due to the size of the modpack, but with this it freezes and is stuck loading indefinitely. When I caught the issue this time, it was 6 hours since the server was supposed to load back up. I've include the latest log file to try and narrow down the issue. But I'm not entirely sure why this is happening.
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11274825/latest.log)

**Comment by rtxyd** [comment]
I've played a homemade multiplayer 1.19.2 server with 220 mods and with apotheosis for a time, and have some suggestions: 
Did you change the default enchantment.cfg config? You can try resetting it and see if the problem solved. 
Or is there another mod also change enchantment levels and other properties? 
If not their problem, 
as I know,  firstly this may be caused by optimization mods, which might operate the threads. But it's just a guesswork, if delete all the optimazation mods didn't solve the problem, you may need a binary search to locate which mod caused this.

**Comment by Xephiro9999** [comment]
I've no clue how to do a binary search. But I've not changed the default, and none of the mods change anything involving enchantments except for Apotheosis.

**Comment by Xephiro9999** [comment]
I've no clue how to do a binary search. But I've not changed the default, and none of the mods change anything involving enchantments except for Apotheosis. 

(Accidentally closed, I never use this site.)

**Comment by RoyalReject** [comment]
I suggest trying with a normal forge server, hybrid servers like arclight tend to break things and are not supported.

**Comment by Xephiro9999** [comment]
> I suggest trying with a normal forge server, hybrid servers like arclight tend to break things and are not supported.

Sadly, I don't have a choice as far as hybrid servers are concerned. And this wasn't really an issue before. This only recently started and I don't know why or how.

**Comment by Shadows-of-Fire** [comment]
That log message shows up at the end of my transformer's application, which means the error/stall lies in whatever runs after my transformer.  The problem is, you can't determine what is running _after_ my transformer, so you'll just have to remove mods until it stops.

**Comment by Xephiro9999** [comment]
Well, when it doesn't stall/error, this is what's next...
`[21Apr2023 15:59:59.851] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[21Apr2023 15:59:59.851] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTreasureOnly() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[21Apr2023 15:59:59.851] [modloading-worker-0/INFO] [net.minecraftforge.coremod.CoreMod.apotheosis/COREMODLOG]: Replaced 1 calls to Enchantment#isTradeable() in net/minecraft/world/entity/npc/VillagerTrades$EnchantBookForEmeralds
[21Apr2023 16:00:00.268] [main/INFO] [quark/]: Dispatching Module Step REGISTER
[21Apr2023 16:00:01.126] [main/INFO] [quark/]: Dispatching Module Step POST_REGISTER`

So I'm to assume Quark is doing it?

**Comment by Shadows-of-Fire** [comment]
It's a possibility, but the early startup stage is asynchronous, and not everything running may emit a log message.

**Comment by Xephiro9999** [comment]
Update: Tried loading without Arclight -- still stalling. but this time it's not showing Apotheosis messages.
