### ISSUE TITLE
Attributes showing up wrong/weird.

### ISSUE THREAD

**Issue by Shaedah** [Shadows-of-Fire/Apotheosis#862]
Item attributes, such as base crit & life steal, aren't displayed correctly.
Example: My vampiric sword has "31% Base Life Steal", but it shows me "31% Base Hit  Enemies per Swing". The sword DOES actually apply lifesteal on hit though.
Every item shows something weird like this, even newly acquired/reforged ones.

If I socket gems they show what they're supposed to be correctly.

I am playing on a server that I host, and my friend doesn't have this issue. The mod's version is matched between client/server.

Let me know if I can provide further information.

---

Here's the list of mods I have:
[modlist.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11277100/modlist.txt)
Here's a couple of examples:
![2023-04-19_19 46 08](https://user-images.githubusercontent.com/131302834/233186505-7b0d1cf4-4a1e-4045-94df-99416001752b.png)
![2023-04-19_19 46 49](https://user-images.githubusercontent.com/131302834/233186651-286e8753-b993-4849-b927-cb615e6a296c.png)

**Comment by Shadows-of-Fire** [comment]
Couldn't really tell you what's wrong.  Sounds like either your registry is corrupted beyond belief (which would cause other issues) or you have a resource pack mangling the translations.

**Comment by Shaedah** [comment]
> Couldn't really tell you what's wrong. Sounds like either your registry is corrupted beyond belief (which would cause other issues) or you have a resource pack mangling the translations.

I have disabled all the resource packs I got, which only leaves "Default", "Mod Resources", and a "Supplementaries Generated..." (I can't see the full name).
I have tried every order and that didn't seem to be the issue.

As for the corrupted registry, I have no idea what that is and how to go about it, and I am not experiencing any other issues whatsoever. Would making a new instance and reinstalling all the mods again fix it? If not I'd appreciate a quick guide on how to go about this registry issue so I can test this theory.
Edit: Looking this up online and I can't seem to find anything useful.

Thanks.

**Comment by Shadows-of-Fire** [comment]
I'm not necessarily certain how you can inspect registry corruption, as it is typically hidden from the user.

**Comment by Shaedah** [comment]
> I'm not necessarily certain how you can inspect registry corruption, as it is typically hidden from the user.

What registry are we talking about here?
Windows reg? If so I could figure out something on my own.
Does Minecraft have a reg? If so, where is it? Can I get my friend to just send me their game folder and it'll work?

Thanks.

**Comment by Shadows-of-Fire** [comment]
We would.be talking about the internal minecraft attribute registry.

You could try cloning your friend's instance, that may resolve it

**Comment by Shaedah** [comment]
Thank you, I will try that.
I'll post the results once we do, if you're interested.

**Comment by Shaedah** [comment]
It appears the cause was multiple mods.

I could only single out Reblurred in the new instance, but removing it in my original instance doesn't change anything.
Most of them were aesthetic mods anyway so I just stopped trying to add any, as I really don't feel like it's worth my time hunting down the ones causing it.
