### ISSUE TITLE
Can't blacklist boss mob types

### ISSUE THREAD

**Issue by CariJac** [Shadows-of-Fire/Apotheosis#863]
I'm struggling with the vindicator bosses, since on my modpack i have MCA, these bosses basically decimate the entire population and in my opinion is just too much of a hassle to deal with. I don't see any option to blacklist any vindicator type bosses- in fact I don't see any options to blacklist mob bosses or add new ones. I checked all the config files and found nothing.

I think that sound be an option- to be able to blacklist OR whitelist mob types to make into bosses, so even modded creatures could spawn in with the apotheosis perks and loot.

If there's any way you can already do this, I'd love to know. Thank you for reading.

**Comment by Shadows-of-Fire** [comment]
All bosses are defined by json, if you want one to stop spawning, override that json with one that doesn't load https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/bosses
