### ISSUE TITLE
[Feature Request] Hide affixes in name

### ISSUE THREAD

**Issue by robertmaxton42** [Shadows-of-Fire/Apotheosis#864]
It would be cool to have a way to hide affixes when renaming -- maybe as a smithing table upgrade or the like. Some of us like to have melodramatic names for our endgame gear, and "Lacerating Sigh of the Critical Thinking" doesn't really have the same impact. :p

**Comment by Shadows-of-Fire** [comment]
closed - 6.2.0 - vial of unnaming
