### ISSUE TITLE
No Apotheosis Mobs/Bosses spawning

### ISSUE THREAD

**Issue by Grizzy08** [Shadows-of-Fire/Apotheosis#865]
I'm playing Direwolf 20 w/ Apotheosis 6.1.1 and I've been playing for about a week and I have never had an apotheosis mini boss spawn. I used to play on All The Mods 8 so Im familiar with how they sound/look, but I have yet to encounter one - any tips to get them to spawn?

**Comment by Shadows-of-Fire** [comment]
boss spawn rates are heavily turned down in that modpack, you'll have to ask the pack authors for more information.
