### ISSUE TITLE
Gem Affixing for Industrial Foregoing resets item and removes gem

### ISSUE THREAD

**Issue by jmac460** [Shadows-of-Fire/Apotheosis#867]
When attempting to affix gems to the Industrial Foregoing weapons or tools, the Gem affix resets the tool back to base state. Particularly the Infinity Hammer and Infinity Drill. It can be upgraded to obtain sockets, but you cannot use those sockets.

**Comment by Shadows-of-Fire** [comment]
This has been reported before with no root cause discovered.  Given this process works for "every other item in the universe except that one" I don't think there's anything for me to do about it, and suggest not affixing infinity items.
