### ISSUE TITLE
1.18.2 Apotheosis + Astikor Carts = Startup Crash

### ISSUE THREAD

**Issue by xFirefalconx** [Shadows-of-Fire/Apotheosis#869]
Hi, I'm reporting this bug in hope you can do something on your end so I might be able to implement Apotheosis into my Modpack update. 
There is an issue when starting the game with both these mods installed. It says "Failed to create entity Minecraft:pig". 

It basically loads til it is almost done loading and then crash. 

I singled out these mods, but I should also inform you that there is a cross mod issue going on with Astikor Carts - whereas it might have to do with how items are registered in your mod, as the **CherryBlossomGrotto mod dev successfully (!) fixed a crash cause** together with Astikor Carts on their end (same error message and behaviour), so it might be possible to mend. Tumbleweed dev however stated they couldn't do anything regarding the bug. So it's a 50/50 chance. 
Apparently some code in AstikorCarts deletes something and causes the fallback entity not to be able to load? 
I reported the bug on their side MONTHS ago but it seems their development is stalled, postponed or deprecated. 
I wish I could just go and fix the bug myself on Astikor side with a fork or the sort but I have almost no knowledge about Java and I already struggle with C# a lot and do dumb and unfeasible things so I doubt I would be doing it any justice. 

Tech data:
Forge 40.2.0
Minecraft 1.18.2

Mods:
EnchantmentDescriptions-Forge-1.18.2-10.0.12
Patchouli-1.18.2-71.1
Placebo-1.18.2-6.6.7
Apotheosis-1.18.2-5.7.7
astikorcarts-1.18.2-1.1.2
Bookshelf-Forge-1.18.2-13.2.53

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11359714/latest.log)
[crash-2023-04-29_17.10.03-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11359715/crash-2023-04-29_17.10.03-client.txt)

Thank you for taking the time.

**Comment by Shadows-of-Fire** [comment]
That mod is breaking a ton of other mods as far as I'm aware.  The crash report is nondescript and I have other things to do than spend hours trying to debug someone else's poor code.

I will not be trying to solve this on my end, sorry

**Comment by xFirefalconx** [comment]
Thanks for your reply.
Just wanted to add some info - **the issue has been resolved.** 
AstikorCarts TFC fork author Verph figured out how to fix the issue, I applied their changes to a new fork yesterday. It's compatible so you can mark it as properly resolved. 
I will also update the other bug reports I made in the past.
