### ISSUE TITLE
[1.14.4] Crash loading spawners

### ISSUE THREAD

**Issue by HellWhyNot** [Shadows-of-Fire/Apotheosis#87]
In my survival world, presumably the first time I loaded a spawner though I didn't actually see it, game ctds, this happened on a creative test as well.
[crash-2019-09-04_03.28.40-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/3573359/crash-2019-09-04_03.28.40-server.txt)

**Comment by HellWhyNot** [comment]
Removing apotheosis made world accessible again.

**Comment by Shadows-of-Fire** [comment]
Seems like forge made another breaking change.  Will update soon

**Comment by Shadows-of-Fire** [comment]
aaf6383aa2cec9cfc7828eb62ce4b0d989679bb5
