### ISSUE TITLE
Apotheosis bosses healing upon being hit

### ISSUE THREAD

**Issue by Traehgniw** [Shadows-of-Fire/Apotheosis#870]
Every so often an Apotheosis boss spawns that has both a very high armour value and an effect where they gain Instant Health or Instant Health 2 upon being hit, making it so that they take less damage even to a heavily enchanted netherite weapon than they heal up upon being hit.

(This is in 1.18.2)

**Comment by rtxyd** [comment]
because their equipment affixed with ability to get instant healing on hit.

**Comment by Traehgniw** [comment]
yeah but it still sucks, it'd be nice if i dunno instant health equipment didnt spawn on boss mobs and was crafted-only or something

**Comment by Shadows-of-Fire** [comment]
This is working as intended but I'll leave this open as the cooldown is still bugged in 1.18.2, and I may have to update that version for some other bugfixes, so this may make it back.

**Comment by Shadows-of-Fire** [comment]
5.8.0
