### ISSUE TITLE
Apotheosis - Bosses rarity will not change in the Overworld.

### ISSUE THREAD

**Issue by Engry1960** [Shadows-of-Fire/Apotheosis#871]
Hello!

I am running a private server and I am hoping you all can help! Currently in the Overworld, only uncommon, rare, and epic mob bosses are spawning. I went into the config file and changed the odds for Mythic to spawn(deadly config), and included Mythic as able to spawn in the overworld.

Any idea what I can do to get mythic to spawn?

I am including a screenshot of the relevant adventure config and deadly config.
![issue adventure config](https://user-images.githubusercontent.com/132216449/235362823-27f60b7b-ef7f-46c4-8eb9-7ec7c2e4506a.JPG)
![issue deadly config](https://user-images.githubusercontent.com/132216449/235362824-95da579c-a9df-4d99-b32f-be5b6f2bba2c.JPG)

**Comment by Engry1960** [comment]
Just to be clear, I am running 1.19.2 and forge 43.2.8

**Comment by Shadows-of-Fire** [comment]
The config does not control boss rarities.  For those, you need to make a datapack which overrides the existing overworld boss entries to be able to spawn as epic+, and also provide stats for those rarities.
