### ISSUE TITLE
Apotheosis Anvils can't go beyond vanilla limits

### ISSUE THREAD

**Issue by Kit1112** [Shadows-of-Fire/Apotheosis#874]
I discovered this wonderful mod. Everything was fine until the moment when I decided to try using the anvil to apply enchantments from a book to an item. Enchantment is applied, but not above vanilla limits, that is, if I combine a book sharpness 7 with a sword, then I get only sharpness 5.

Game version 1.19.2, apotheosis 6.1.5
P.S Apotheosis installed on the server

**Comment by Shadows-of-Fire** [comment]
duplicate of #873
