### ISSUE TITLE
[1.19.2] Confliction Crash on Launch

### ISSUE THREAD

**Issue by itsdinkd** [Shadows-of-Fire/Apotheosis#875]
Botania + Apothesis + aquamirae + Unique Enchantments Conflict.

https://gist.github.com/itsdinkd/80070021f6204c40709b8d837d515123 (Conflicting w/o Botania, but with Unique Enchantments and Apothesis while Enchantment Module is on). This crash occurs when trying to create a single player world. 

https://gist.github.com/itsdinkd/939ef9bc5eb54a243b0140e29a94e192 (Crashes on launch, added botania, disabled enchantment module on Apothesis)

**Comment by Shadows-of-Fire** [comment]
unique enchantments is incompatible with apoth, regardless of if the module is enabled or not.  Supposedly they're working on a fix on their end.

**Comment by itsdinkd** [comment]
Ah dang :( thanks for the info though!

**Comment by itsdinkd** [comment]
also thank you for the super quick response!
