### ISSUE TITLE
Commit 873

### ISSUE THREAD

**Issue by Kit1112** [Shadows-of-Fire/Apotheosis#876]
The problem is not in modifications, everything works in singleplayer, the problem is on the server side. Perhaps you could help me?
I managed to find out that the problem is not in the world files, not in the mods and not in the plugins. I'm honestly running out of ideas for this.

(Anvils work incorrectly)
https://github.com/Shadows-of-Fire/Apotheosis/issues/873

**Comment by unhack12** [comment]
#873

**Comment by SiverDX** [comment]
Should probably list the mods the server is using
Is it your server?

https://www.curseforge.com/minecraft/bukkit-plugins/enhancedenchants
Stuff like this could limit what a normal player is allowed to do

**Comment by Kit1112** [comment]
> Should probably list the mods the server is using Is it your server?
> 
> https://www.curseforge.com/minecraft/bukkit-plugins/enhancedenchants Stuff like this could limit what a normal player is allowed to do

no, I don't have this plugin on the server. I don't think a mod list is necessary, because I've found out for sure that the problem is NOT mods or plugins. I think I have problem with anything alse

**Comment by SiverDX** [comment]
Yeah, no way is anyone able to help you if you can't even be bothered to provide any basic information
Thousands of mods available, different server providers with their own custom setup etc. and you give no context

Good luck

**Comment by Shadows-of-Fire** [comment]
Opening three issues constitutes spam.
