### ISSUE TITLE
[Support] [1.18.2] Removing Affixes

### ISSUE THREAD

**Issue by slave2midna** [Shadows-of-Fire/Apotheosis#877]
Some what of a question on datapack and adjustments for 1.18.2 I have been able to create a working datapack that has worked smoothly for allowing me to add weapons to affix_loot, but I was curious if there was a method of using datapacks to REMOVE specific affixes from populating on weapons and armor?

In this case, I'd like to remove base "Speed" bonus from weapons and armors, but still keep them on gems. I just wasnt' sure where to find the structure for removing just this one affix, or if it was even possible to do so. Ideally I don't mind having the affix that procs a short speed boost after a hit, just the flat speed stat boost that can be rolled on items.

Or at the very least, reduce the % alloted.

**Comment by Shadows-of-Fire** [comment]
To remove an affix you use a datapack to replace the affix json with a file that will not load.  Typically this is done by using the `forge:false` loading condition.
