### ISSUE TITLE
[Suggestion] Smithing Anvil Can't Rename Affix Items

### ISSUE THREAD

**Issue by slave2midna** [Shadows-of-Fire/Apotheosis#878]
Not sure if this was intentional, or fixed post 1.18.2 - but I noticed you cannot rename an item in the anvil with affixes. IF you attempt to rename it, it will only rename 1 part of the name, and keep the rest of the information. Like: Quickening `Sword` of Savagery ( example), could be renamed Quickening `Affliction` of Savagery - the sword part is all that changes. Would be cool to name the entire weapon once you've got the stats you want and the gems you want, having a cool name would be fancy.

**Comment by Shadows-of-Fire** [comment]
The prefix and suffix staying are intentional, you can only rename the item's actual name (and the prefix/suffix will stay unchanged).

There is a todo list item for a "Vial of unnaming", an item to remove the extra name components.
