### ISSUE TITLE
Is it possible to extract the attributes to Library mod?

### ISSUE THREAD

**Issue by ferriarnus** [Shadows-of-Fire/Apotheosis#879]
I have been working on a mod of mine own that adds attributes like "life steal", "piercing" and other RPG like effects and stats. Today I noticed that you have already made attributes like that for [Apotheosis](https://github.com/Shadows-of-Fire/Apotheosis/blob/9912e4f05c6a430fbeee5dc8f545e7ff897438b1/src/main/java/shadows/apotheosis/Apoth.java#L222). My question now is if you would be interested in splitting these effects (and possible add more/others) into a separate library mod so other mods could also use it? I would also be up for helping with this if you're fine with it.

**Comment by Shadows-of-Fire** [comment]
I *could*, though nothing prevents mods from using them with apoth (except well, needing apoth installed)

**Comment by ferriarnus** [comment]
Yeah that was the point I meant. For addons it would be fine to have apoth as a required dep, but there are mods that would benefit solely from the attributes. If it became part of a library mod, that would not be needed.

**Comment by Shadows-of-Fire** [comment]
Marking this as TODO but not high priority right now.

**Comment by Shadows-of-Fire** [comment]
Code has been isolated to <https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/java/shadows/apotheosis/core/attributeslib> but not yet fully extracted.

**Comment by Shadows-of-Fire** [comment]
https://www.curseforge.com/minecraft/mc-mods/apothic-attributes
