### ISSUE TITLE
config tweaks

### ISSUE THREAD

**Issue by itsdeadfrosty** [Shadows-of-Fire/Apotheosis#880]
Can you guys add config options to tweak the multiplier for loot pinata? It's just a little bit too strong or at least like Restrict it to certain drops. Because I'm getting Like 20 loot bags on random occasions. And it's kind of overpowered.

and could we possibly see some sort of compressed tool tip For affix items? because once you throw on a couple enchantments it gets a little ridiculous and you can no longer. See the entire tooltip. It gets even worse if you try to make tweaks with /apoth modifier, Not only is the command a little confusing, with addition, vs total multiplier, but the Gear keeps track of the history. So if you apply something twice, it's going to list it twice, and it makes the tool type ridiculously long rather than just condense it all into one stat

Also more precise affix control with the lootify command would be great. pls n thx

**Comment by Shadows-of-Fire** [comment]
Are you looking for a config to change the 20x multiplier to something less?  The percentage values are already configurable.

**Comment by itsdeadfrosty** [comment]
Had no idea I’ll look into it
