### ISSUE TITLE
Crashing Forge 1.19.2

### ISSUE THREAD

**Issue by HoodBlah** [Shadows-of-Fire/Apotheosis#881]
With this mod, whenever I open my inventory or right click the game crashes.
[2023-05-06-7.log](https://github.com/Shadows-of-Fire/Apotheosis/files/11413768/2023-05-06-7.log)
[latest.zip](https://github.com/Shadows-of-Fire/Apotheosis/files/11413779/latest.zip)

**Comment by Shadows-of-Fire** [comment]
You have something in your instance which is irreparably breaking apoth. No clue what it is. Probably optifine though.
