### ISSUE TITLE
Bug: Bonus Max health armor doesn't maintain full health when logging..

### ISSUE THREAD

**Issue by Twisted-Code** [Shadows-of-Fire/Apotheosis#882]
That is, if I have max health bonuses on my armor, log out with full health, and log back in, I'm at whatever help I would've been if the max health bonus wasn't applied. It's as if it's recalculating my health without the bonus.
Some facts:

- I know that I logged out with full health. If I had taken damage after healing up with food, I wouldn't have any absorption hearts from Overheal
- I have not repeated the issue, yet, though I think it's happened a few times and I wondered where my health had gone. I just haven't gone out of my way to be sure of it, as it's a bit tedious logging in and out and in and out, especially with this pack...
- I've not conclusively eliminated other health-bonus sources, but the amount of health I'm currently missing is exactly the amount of "+ Max health" on my armor. 

Apotheosis version: 6.1.5

**Comment by RoyalReject** [comment]
This is actually a bug with vanilla itself, you need to use a mod like https://www.curseforge.com/minecraft/mc-mods/max-health-fix, to fix it

**Comment by Twisted-Code** [comment]
In that case, why are my other max health bonuses not affected? I have bonuses from Baubly Heart Canisters and Spice of Life Carrot Edition. Is it just because they are not armor? Is there nothing that can be done in the affix implementation to get around this?

**Comment by Shadows-of-Fire** [comment]
The solution is to install MHF.  Fixing it natively basically requires copying MHF into apoth, so /shrug

**Comment by Twisted-Code** [comment]
ok, fair enough. I mean I have to update my mod list either way, so same amount of work for me just to install the fix I guess.
