### ISSUE TITLE
Apotheosis and unique enchantments

### ISSUE THREAD

**Issue by DragonMaster14545** [Shadows-of-Fire/Apotheosis#883]
When I use just apotheosis and unique enchantmants and all its addons(And their dependencies) the game crashes while loading
[crash-2023-05-11_17.15.13-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11453765/crash-2023-05-11_17.15.13-fml.txt)

**Comment by Shadows-of-Fire** [comment]
UE is incompatible with apoth.
