### ISSUE TITLE
[Support] Compatibility with Tetra [1.19.2]

### ISSUE THREAD

**Issue by erathia65** [Shadows-of-Fire/Apotheosis#884]
Apotheosis ver. : 1.19.2-6.1.5
Tetra ver. : 1.19.2-5.2.1

I'm trying to get gems sockets working for custom weapons from tetra, and i realized the work is already half done, the melee weapons are recognized by the mod but the bows and crossbows arent, here are some examples with screenshots:

<details><summary>Details</summary>
<p>

Sword socketed and then customized:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/6e150cc1-311f-436f-821b-f60ad14d4e50)

Sword customized and then socketed
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/c0dddcd4-9a7b-4409-9000-7e23825aaac1)

Bow Socketed and then customized (bow no longer recognized as a bow for socketing):
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/a04a91b1-8456-47c3-b2b5-09e808adc283)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/d69fe139-edd5-4f8e-9ab0-d8a7347f266c)

Custom Crossbow, not recognized for socketing:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/c05b9d25-5ace-4aa3-ba50-ca95997e60bc)

Custom Bow, not Recognized for socketing:
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/3441742/52a34208-5b28-4dc9-9918-41d6db39291f)

</p>
</details>

**Comment by Shadows-of-Fire** [comment]
Unfortunately if those aren't picked up there's not much I can do (I don't want to mixin hooks into tetra) - the builtin compat relies on bows and crossbows extending the vanilla classes, but it seems like these two don't
