### ISSUE TITLE
Wizard tower doesn't generate

### ISSUE THREAD

**Issue by ClementM0512** [Shadows-of-Fire/Apotheosis#885]
Hello i'm in 1.19.2 version.

I searched through the configs and couldn't find any trace of the wizard towers being generated.
Is this a bug or has it not been implemented?

![apoth](https://github.com/Shadows-of-Fire/Apotheosis/assets/34575889/d1de7e2b-d3cb-4df0-8244-5b58088282db)

**Comment by Shadows-of-Fire** [comment]
The tower was removed in 1.18.  It may be readded at a later date, but it is currently not enabled.
