### ISSUE TITLE
How to properly remove data entries?

### ISSUE THREAD

**Issue by Treeways** [Shadows-of-Fire/Apotheosis#887]
Hi, I'm trying to remove wandering trader trades with KubeJS data.

I've just been overriding data with blank files, like so:

```
{}
```

Technically, this "works", but I'm getting errors like this in the console:

```
[Render thread/ERROR] [Apotheosis : Village/]:
Ignoring wanderer_trades item with id apotheosis:eye_of_ender as it is empty. 
Please switch to a condition-false json instead of an empty one.
```

What is a condition-false json? Does this apply to all data files, such as chest loot or affixes, or just trades?

Thanks!

**Comment by Shadows-of-Fire** [comment]
That would be the following
```
{
    "conditions": [
        { "type": "forge:false" }
    ]
}
```

It will apply to most things.  Loot tables are not one of those things currently (but it doesnt make sense to null out a loot table, as that would crash things which try to generate it)
