### ISSUE TITLE
Remove movement speed from armor

### ISSUE THREAD

**Issue by Treeways** [Shadows-of-Fire/Apotheosis#888]
In my modpack, there are armors that provide base movement speed increase. I would like to nerf this because it is particularly gamebreaking, with various transportation methods becoming irrelevant when these armor sets are stacked.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/56928485/eba46248-e827-4a0d-b26d-7032b4d80b1a)

I had a look at the [affix list](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/Affixes.txt), and interestingly, there were not any speed related buffs for armor:

> Armor:
+Max Health
+Armor
+Armor Toughness
Magic Resistant
Reduces duration of negative effects

I also had a look through the data, and I couldn't find any configurable speed related upgrades besides the stuff on gems, and this one affix for the bow:

```
./data/apotheosis/gems/core/lightning.json:			"attribute": "minecraft:generic.movement_speed",
./data/apotheosis/gems/core/samurai.json:			"attribute": "minecraft:generic.movement_speed",
./data/apotheosis/gems/core/splendor.json:			"attribute": "minecraft:generic.movement_speed",
./data/apotheosis/affixes/ranged/attribute/windswept.json:	"attribute": "minecraft:generic.movement_speed",
```

Is there anything I can do to disable this additional armor speed? Did I miss something?

**Comment by Shadows-of-Fire** [comment]
That affixes.txt file is worthless, it was a staging document for 1.16 - basically any .txt file in the root is internal / misc.

The affix is the one you listed, which is not just for the bow (despite it being in that folder) https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/affixes/ranged/attribute/windswept.json#L41

**Comment by Treeways** [comment]
Ahh okay, thanks a bunch!
