### ISSUE TITLE
Dupliation

### ISSUE THREAD

**Issue by OKthen333** [Shadows-of-Fire/Apotheosis#89]
So the new fletching module is great. 1 problem happens when you shift click while making broadhead arrows. It makes like 9000000 sticks and iron

**Comment by Shadows-of-Fire** [comment]
What version of the mod are you using?  This was patched already, but I know FTB Unstable is using an old version.

**Comment by OKthen333** [comment]
1.14.4-2.3.1

**Comment by Shadows-of-Fire** [comment]
Was this on a dedicated server?

**Comment by Shadows-of-Fire** [comment]
I cannot reproduce this issue in any environment, dedicated or integrated.
