### ISSUE TITLE
Crescendo of Bolts & SilentGear Crossbows

### ISSUE THREAD

**Issue by SargeRyong** [Shadows-of-Fire/Apotheosis#890]
Crescendo fails to trigger when using silentgear crossbows - I've been trying to investigate why, but I'm not 100% sure.

Silent's crossbows DO extend vanilla CrossbowItem

(see: https://github.com/SilentChaos512/Silent-Gear/blob/1.18.x/src/main/java/net/silentchaos512/gear/item/gear/GearCrossbowItem.java)

Is it failing to work because Silent overrides use(...) and calls its own fireProjectiles(...)?  I'd like to troubleshoot the issue myself but I have a poor understanding of mixins.

**Comment by Shadows-of-Fire** [comment]
Overriding use would make the mixin fail, yes. Fixing it would require mixing into the extension, and the hooks will likely need to be different.

This is how ars spell crossbow is supported - with a custom mixin

**Comment by SargeRyong** [comment]
Thanks for the info!

I spent a bit of time today implementing a mixin to support SilentGear crossbows with this enchant.  Learned quite a bit about mixins, lol.

Made a PR if you want it: https://github.com/Shadows-of-Fire/Apotheosis/pull/891

**Comment by Shadows-of-Fire** [comment]
at the current moment I don't want to sink time into supporting this further, so I'm just going to close this.
