### ISSUE TITLE
Ticking entity crash from arrows when ranged mob effect config is changed

### ISSUE THREAD

**Issue by Treeways** [Shadows-of-Fire/Apotheosis#893]
When updating files in `kubejs/data/apotheosis/affixes/ranged/mob_effect/*`, any arrows shot after the change will eventually cause a null entity ticking error.

Changing this config on a previously generated world is extremely dangerous, and causes world corruption. The server crashes on boot once this crash happens the first time.

[crash-2023-05-18_19.03.32-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11510940/crash-2023-05-18_19.03.32-server.txt)

**Comment by Shadows-of-Fire** [comment]
At first glance that looks like user error.  You would need to show the files you have changed and how they differ from the originals.

**Comment by Treeways** [comment]
I modified the caps on some effects, and removed others. Here's the full diff: https://github.com/Shadows-of-Fire/Apotheosis/compare/1.19...Treeway7:Apotheosis:1.19

(There are no JSON errors in these files.)

**Comment by Treeways** [comment]
I also pushed the other data I've modified so far here on a different branch: https://github.com/Shadows-of-Fire/Apotheosis/compare/1.19...Treeway7:Apotheosis:full-changes

Removing the arrow mob effect files fixes the bug.
My best guess is that the condition-false statements are messing with the already summoned arrows, but I haven't done any testing to confirm this.

**Comment by Shadows-of-Fire** [comment]
Based on the diffs the error comes from in-flight arrows retaining affixes where you reduced the rarity scope, which then crashes.

The condition-false ones aren't crashing.

You can just perform your changes, enable RemoveErroringEntities in the forge config, and then all "broken" arrows will be cleared (no new ones may be introduced).
