### ISSUE TITLE
Crash during boss spawning

### ISSUE THREAD

**Issue by FearAK** [Shadows-of-Fire/Apotheosis#896]
Updated to the latest apotheosis version for 1.19.2 and now when I go into the table to disassemble tools and armor I crash with this crash report.

https://hastebin.com/share/rofapoteto.php

**Comment by Shadows-of-Fire** [comment]
Interesting correlation, crash report has absolutely nothing to do with the salvaging table, but rather an issue with boss spawns.

**Comment by FearAK** [comment]
Oh, it happened just as I entered the table so I thought that was the cause. Sorry, I'm not good at understanding crash reports :/

**Comment by Shadows-of-Fire** [comment]
Ah, this particularly happens when a mounted boss spawns, as it fails to find the name of the boss for the announcement.  Will be fixed in 6.2.1
