### ISSUE TITLE
Crash when Reforging Mythic Botania Mjolnir

### ISSUE THREAD

**Issue by k8thekat** [Shadows-of-Fire/Apotheosis#899]
The issue is when attempting to mouse over the choices from the Reforging Table my game crashes.

This is on *ATM8 v1.0.18*

Apotheosis Version - Apotheosis-1.19.2-6.1.5.jar

Simply take the hammer and place into the table; attempt to mouse over a selection and the game crashes instantly.

I have attached my crash log.

[crash-2023-05-22_18.07.27-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11538183/crash-2023-05-22_18.07.27-client.txt)

**Comment by Shadows-of-Fire** [comment]
Update to 6.2.0
