### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mxnmnm** [Shadows-of-Fire/Apotheosis#902]
Mc 1.18.2
mod 5.8.0

crash report: https://gist.github.com/mxnmnm/e7680587f69f5f9cebc2ef06d37f79bc

happens on boot, if you need more info let me know
also version 5.7.7 works just fine

**Comment by Shadows-of-Fire** [comment]
Not really any way that can be an apoth bug - looks like it would be the fault of some rendering mod or AT's failing to apply

Can you pull the entire debug.log file instead of the crash report?

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/55c74eafcad8f7d4ad8bfa8ea4165c2f

looks like I had an older jei version because my profile was set to release only. There should probably be a more obvious way to let the player know they need a newer jei version lol

**Comment by Shadows-of-Fire** [comment]
Properly displaying dependency errors is forge's domain, all I can do is declare them.
