### ISSUE TITLE
Tooltip Config

### ISSUE THREAD

**Issue by SiverDX** [Shadows-of-Fire/Apotheosis#903]
Would it be possible to allow for a config to disable the summarization of tooltips?

https://github.com/Shadows-of-Fire/Apotheosis/blob/0ec325b924b8867a723bec3b8c2c0a32e6140c8f/src/main/java/shadows/apotheosis/adventure/client/AdventureModuleClient.java#L328

it would make it easier to customize the tooltip (since it would be a lot more effort to calculate and format the values yourself in the same way to add them when `Shift` is not pressed)

On another note - there could also be a potential compatibility for `Better Combat` and its `Attack Range` tooltip
(Adding the Attack Range modifiers to that tooltip - though the current `priority` would not support that since `Better Combat` is using `NORMAL`)

There is also a problem where `Attack Speed` attributes get added to that `Attack Range` tooltip:
![grafik](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/a7ab7a0f-4779-4206-9923-aabfb53bb24e)

Seems due to the way `Better Combat` adds its tooltip:
https://github.com/ZsoltMolnarrr/BetterCombat/blob/f218f68547266e6918d29a0d07cb8d46a3c25a53/common/src/main/java/net/bettercombat/client/WeaponAttributeTooltip.java#L51

There is a config to disable that tool tip - could maybe do something similar that you already do for Quark?

**Comment by Shadows-of-Fire** [comment]
Due to BC's unwillingness to support the Forge Attack Range attribute, I have elected to not provide any support for BC-related issues. See https://github.com/ZsoltMolnarrr/BetterCombat/issues/244 and https://github.com/ZsoltMolnarrr/BetterCombat/issues/266
