### ISSUE TITLE
Boss spawn causes crashing.

### ISSUE THREAD

**Issue by DracxTar** [Shadows-of-Fire/Apotheosis#904]
So I have Apotheosis in a custom modpack I made for a few friends and myself, we have noticed that multiple times when certain bosses spawn in the game crashes. I'm not sure if this is a result of a recent update or not but I figure I'd bring this issue to light.

**Comment by Shadows-of-Fire** [comment]
It was an issue in 6.2.0 but fixed in 6.2.1 - you would need to provide a crash report for reference.

**Comment by DracxTar** [comment]
Gotcha, I'll make sure to update it. I appreciate the info
