### ISSUE TITLE
NBT issue?

### ISSUE THREAD

**Issue by Kn0wnG1itch** [Shadows-of-Fire/Apotheosis#905]
I know that the affix nbt tag issue was fixed, but when I updated to the 5.8 release for 1.18.2 I seem to have gotten a new issue. It's possible that it isn't Apotheosis doing it because the tag is completely empty, but it happened when I updated so it might be connected. 
![Screenshot 2023-05-26 165315](https://github.com/Shadows-of-Fire/Apotheosis/assets/119559352/24efa863-91e9-44a5-9c43-2cac3a2d97a6)
![Screenshot 2023-05-26 165310](https://github.com/Shadows-of-Fire/Apotheosis/assets/119559352/327b577e-bce3-4ce0-95a4-6e2e02c614df)
I haven't found a reliable situation that causes it but it does happen very much. My instance has a LOT of mods so it could be just an unfortunate interaction too. 

(I don't post on Github often so if there are any issues or standards that I missed, just lmk.)

**Comment by Shadows-of-Fire** [comment]
5.8 is officially the end of 1.18 for apoth, unless there are major gamebreaking bugs (Dupes, world corruption, etc).

**Comment by violetkitty87** [comment]
Im also having this same issue on 1.19.2 version of mod is 6.2.1 not just with torches it has happened with other things such as bread

**Comment by ewsmith** [comment]
i'm also getting this issue on 1.19.2 with version 6.2.1. i've also figured out that the issue doesn't happen if you shift click the results out of the crafting table. it only happens when you craft items one at a time.
