### ISSUE TITLE
Crashes trying to spawn boss in The Other

### ISSUE THREAD

**Issue by static-dream** [Shadows-of-Fire/Apotheosis#906]
Playing ATM7 and wanted to enable apotheosis bosses in allthemodiums The Other

I looked at the config for ATM8 and aw there was only one line i needed to add it seemed like so I did as such

   # Dimensions where bosses can spawn naturally, spawn chance, and spawn rules.
    # Format is dimname|chance|rule, chance is a float from 0..1.
    # Valid rules are NEEDS_SKY, NEEDS_SURFACE, and ANY [default: [minecraft:overworld|0.02|NEEDS_SKY], [minecraft:the_nether|0.03|ANY], [minecraft:the_end|0.02|NEEDS_SURFACE], [allthemodium:the_other|0.09|NEEDS_SURFACE], [twilightforest:twilight_forest|0.05|NEEDS_SURFACE]]
    S:"Boss Spawn Dimensions" <
        minecraft:overworld|0.01|NEEDS_SKY
        minecraft:the_nether|0.02|ANY
        minecraft:the_end|0.02|NEEDS_SURFACE
        twilightforest:twilight_forest|0.05|NEEDS_SURFACE
	allthemodium:the_other|0.09|NEEDS_SURFACE
     >

C
[crash-2023-05-26_21.22.49-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11580780/crash-2023-05-26_21.22.49-server.txt)

**Comment by Shadows-of-Fire** [comment]
You must add valid boss jsons for any dimension you add to that list.

**Comment by static-dream** [comment]
> You must add valid boss jsons for any dimension you add to that list.

Thank you for the speedy reply, How would I go about that?

**Comment by Shadows-of-Fire** [comment]
You use a datapack.  The existing files, for reference, live here https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/bosses
