### ISSUE TITLE
all spawners not working in a specific chunk

### ISSUE THREAD

**Issue by domshi** [Shadows-of-Fire/Apotheosis#908]
i wrote to the server management team and they are attempting to shift blame of this issue onto the mod, what information do you need to verify that it is not the mod that is causing the issue?

this picture is the spawner area that is not working
![2023-05-30_17 29 36](https://github.com/Shadows-of-Fire/Apotheosis/assets/90562421/3b2b2ce0-a933-4915-a5ef-7584b3686a72)

followed by the stats of all my spawners
<img width="259" alt="Capture 2" src="https://github.com/Shadows-of-Fire/Apotheosis/assets/90562421/162f26d9-b551-4121-9f5a-48774fd0a58a">

this last picture is the spawner working correctly in other chunks
<img width="960" alt="Capture" src="https://github.com/Shadows-of-Fire/Apotheosis/assets/90562421/7d867631-f329-44e1-8a41-9d8a00818da6">

**Comment by Shadows-of-Fire** [comment]
The spawner performs no checks that are sensitive to a specific chunk.
The easiest check is to see if it fails to work with no modifiers, as an unmodified spawner is just a vanilla spawner."

The only way it could even be potentially an apoth issue is if it only reproduces in that chunk when a specific modifier is present.

**Comment by domshi** [comment]
i discovered that it was a separate mod that caused the conflict, i ejected the other mod. thank you for clearing that up
