### ISSUE TITLE
[Feature Request] Disabling Random Boss Spawns

### ISSUE THREAD

**Issue by CKY-** [Shadows-of-Fire/Apotheosis#909]
I understand that the adventure module can be disabled as a whole. 
This would remove boss dungeons, and I for one like this part of the module. The random boss;s are a bit overbearing. 

It would be amazing to be able to disable in the adventure module the random boss that can spawn. 
Independent of the boss dungeons. There are some great confings that can be done but no way to turn off the bosses.

**Comment by SiverDX** [comment]
I'm not sure but could you not set this to 0?
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/82340b60-e6a8-4d1d-8c37-1ed5570ee237)

Seems like it is used to spawn the bosses:
https://github.com/Shadows-of-Fire/Apotheosis/blob/0ad17e2c2b47eb94967e29019c987ddc0d9d240d/src/main/java/shadows/apotheosis/adventure/boss/BossEvents.java#LL64C16-L64C16

The boss spawners seem to have a different logic so they should still work I think
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/boss/BossSpawnerBlock.java

**Comment by CKY-** [comment]
I will try this, and report back. I was looking at that but was unsure if that would cause other issues.

**Comment by Shadows-of-Fire** [comment]
This can be accomplished through the adventure module config file as shown above.
