### ISSUE TITLE
Problem at generating bamboo

### ISSUE THREAD

**Issue by Gnis97** [Shadows-of-Fire/Apotheosis#91]
Minecraft 1.14.4
Forge 28.1.0
Apotheosis 2.3.3
No other mods installed

When te bamboo is generated naturaly it collapses and fall to the ground. Reducing the max heigth of bamboo dont affect and deactivating the garden module fixes it.
![2019-09-23_22 25 42](https://user-images.githubusercontent.com/49316776/65460439-2cb11c80-de52-11e9-97c8-34dd8ec52986.png)
![2019-09-23_22 26 12](https://user-images.githubusercontent.com/49316776/65460468-3d619280-de52-11e9-9a3f-e55b4a1fbf1b.png)
![2019-09-23_22 26 26](https://user-images.githubusercontent.com/49316776/65460573-84e81e80-de52-11e9-811a-09695429b6d8.png)

**Comment by Shadows-of-Fire** [comment]
Hm, looks like somewhere is capturing the old bamboo state.
