### ISSUE TITLE
Broken Affixes 

### ISSUE THREAD

**Issue by Madaawg** [Shadows-of-Fire/Apotheosis#910]
Affixes in my server have suddenly started to become more broken with random affix stats. At the start of the world they were normal but then progressively became more random. Armor seems to be fine though. 
![2023-06-02_13 23 29](https://github.com/Shadows-of-Fire/Apotheosis/assets/135383272/5069f613-babe-4734-9cc3-7a5f3e29e5f1)
![2023-06-02_13 23 24](https://github.com/Shadows-of-Fire/Apotheosis/assets/135383272/bf29c069-24f7-48e1-bb82-f2a5571db7b5)
![2023-06-02_13 38 14](https://github.com/Shadows-of-Fire/Apotheosis/assets/135383272/077fe958-dabd-4661-aa76-9e5a69925dd3)

**Comment by Shadows-of-Fire** [comment]
I have no clue what that is.  It looks like registry corruption. I don't think it's on my end or something I can fix.
