### ISSUE TITLE
Jade Compatible Feature Request

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadows-of-Fire/Apotheosis#911]
Can you add a function to Jade's Boss Modifiers to show them by holding shift?
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47446553/89c416c9-c077-4aee-9d34-0ffd50ff2ee2)
It's so long it takes up part of the center of the screen
I asked the author of Jade and he said he had to tell you

**Comment by Shadows-of-Fire** [comment]
in 6.3.0+ individual boss modifiers will be hidden in production environments.
