### ISSUE TITLE
Full-upgraded spawners not spawnin sheeps from energetic sheep's mod 

### ISSUE THREAD

**Issue by caiofelipetz** [Shadows-of-Fire/Apotheosis#912]
i asked the devs of energetic sheeps mod, they told me it should be a problem with apotheosis side 

ISSUE: the spawner just no not spawn any sheeps from the mod even with full upgrade to ignore spawn conditions

**Comment by Shadows-of-Fire** [comment]
Unmodified spawners operate the exact same as a vanilla spawner - and with ignore conditions, no checks are performed at all. If a mob doesn't spawn with ignore conditions, something is preventing it from being spawned, but it isn't the spawner.
