### ISSUE TITLE
[Feature Request] Allow SalvagingTableBlock to have inventory 

### ISSUE THREAD

**Issue by klugemonkey** [Shadows-of-Fire/Apotheosis#916]
Request that the SalvagingTableBlock/SalvagingTableTile act as an inventory for purposes of input and output, as well as having functionality to automatically salvage items in the inventory (check box). 

Currently the Salvage Table only allows a player to place items into and pull items from the input and output when the block interface gui is open.  If the player closes the GUI, items do not remain in the block that are placed in the input or generated in the output.   This makes it impossible to integrate the SalvageTableBlock with any other automation mods that using pipes for transport or that access a item slot.

Understanding that it might be the intent of the author to nerf the functionality to hand salvaging, this functionality could still be implemented and set in a configuration file whether to accept input from the sides or disable globally.

Salvage of items with affix data is a nice feature, and with some modpacks, players will setup mob grinders and generate significant amounts of drops that have affix data.  In order to help process all these drops, allowing for automated salvaging in the mod would be a very helpful.

**Comment by Shadows-of-Fire** [comment]
Automated salvaging is part of the upcoming 6.3.0 update

**Comment by DjeyMute** [comment]
Pls we all wait 1.20 support for Auction House !
