### ISSUE TITLE
Method of disabling the undead knight

### ISSUE THREAD

**Issue by DraTrav** [Shadows-of-Fire/Apotheosis#917]
The undead knight spawns a little too often and is rather annoying, there doesn't appear to be a way to disable it in its entirety.

**Comment by Shadows-of-Fire** [comment]
The undead knight is a datapack object and can be disabled using the appropriate methods (or have the spawn rate reduced, or any other manner of changes) - https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/minibosses/overworld/undead_knight.json

**Comment by DraTrav** [comment]
Hi, I understand you are supposed to be able to disable them threw a datapack, but I have no clue where to even begin to do something like that. Do you happen to have any way to lead me down the right path? Changing a "true" to "false" is much easier than making a data pack for one of the very few non configurable options so I'm a little lost.
