### ISSUE TITLE
[Suggestion] Portable storage for gems-- maybe bundle

### ISSUE THREAD

**Issue by Xetaxheb** [Shadows-of-Fire/Apotheosis#919]
Some kind of portable storage to stash a bunch of gems in, like a bundle-derivative item that only holds gems but holds 64 of them, would be a very welcome change. Having a bunch of random gems from chest loot makes it difficult logistically but outright discarding them feels bad.

**Comment by willsike1** [comment]
Right Now, the best, semi-portable solution is armoury cabinets. You do need a external viewer to view the contents though.

**Comment by Xetaxheb** [comment]
I don't think some third party mod makes it a "best solution". A few AE2 1k portable item cells would likely be far more convenient at 63 items per slot and can be opened individually for 16+ minutes from full charge. Or RS's equivalent portable grid and a 1k storage disk (1000 items/slot?). And more likely to be in a modpack than functional storage (which, amusingly, recommends AE2/RS to access the cabinet since there's no good built in way to do so).

But this issue is about apotheosis features so these comments are neither here nor there..

**Comment by Msanical** [comment]
Have You Tried Vanilla Bundles? They Do Just That

**Comment by Xetaxheb** [comment]
> Have You Tried Vanilla Bundles? They Do Just That

...a vanilla bundle works on stack sizes holding at most 1 total stack of items.... 
when you have a non-stacking item like a gem, it takes up all 64 slots by itself...
so you can fit at most 1 singular gem inside a vanilla bundle

hence why i was recommending... a vanilla bundle inspired item.... except for gems

**Comment by Msanical** [comment]
> ...a vanilla bundle works on stack sizes holding at most 1 total stack of items.... when you have a non-stacking item like a gem, it takes up all 64 slots by itself... so you can fit at most 1 singular gem inside a vanilla bundle

Mate, I'm On 1.19.2 And I Can Fit 64 Gems In A Single Bundle. And I Don't Have Any Mod That Changes Bundles In Any Way

**Comment by Msanical** [comment]
Just Confirmed, It's Working With Only Apotheosis And Placebo Installed.

Bundles _Can_ Hold Multiple Gems, And Gems Of The Same Type _Do_ Stack In Player Inventory

![2024-01-03_19 49 23](https://github.com/Shadows-of-Fire/Apotheosis/assets/44846599/eed907e8-d86f-4a99-8be2-1eff8ef42229)

**Comment by Xetaxheb** [comment]
👍 looks like the 6.3.0 overhaul changed gems to stack 64, making this addition unnecessary.

With that said, I think it would be hilarious for a gem bag that holds a large number and auto collects gems when it's in your inventory but not in active hand (see: botania flower pouch), and you right click to toss a random gem from the bag to the floor as an item.
