### ISSUE TITLE
[1.19] Massive lag caused by bamboo item

### ISSUE THREAD

**Issue by AndreAugustoDev** [Shadows-of-Fire/Apotheosis#921]
If I pick up a bamboo in inventory with Apotheosis installed, I will experience massive lag and become unplayable.
No crash occurs, just lag
Apparently the dropped item does not cause lag

**Comment by Shadows-of-Fire** [comment]
You will need to provide a spark profile. Apotheosis does not add any code to the bamboo that runs in the inventory.

**Comment by AndreAugustoDev** [comment]
I made these two messing with the inventory, taking and putting items in a barrel and walking around

`/sparkc profiler start --thread * --timeout 60`
https://spark.lucko.me/Xi0BhEZpWj
`/sparkc profiler start --thread * --combine-all --timeout 60`
https://spark.lucko.me/C5I8Z4NLr5

**Comment by Shadows-of-Fire** [comment]
Nothing in the profiler reports anything of apoth, and it doesn't reproduce locally. Unfortunately this appears to be instance-specific to you.
