### ISSUE TITLE
Rabbit Foot

### ISSUE THREAD

**Issue by gcaury** [Shadows-of-Fire/Apotheosis#922]
Is there any place to change the Lucky Rabbit's Foot drop percentage to be able to get Normal Rabbit's Foot sometimes? I need it in another mod.

**Comment by Shadows-of-Fire** [comment]
The Lucky Foot does not change the drop chance of the normal rabbit's foot, it is added as an extra item.

**Comment by gcaury** [comment]
strange then, the only thing I get from the rabbit is this loot, not even meat and leather is dropping, but, thanks!
