### ISSUE TITLE
REIPC support jei 9.9999 apotheosis wants 10 or above 

### ISSUE THREAD

**Issue by Enkvaros** [Shadows-of-Fire/Apotheosis#924]
i wrote this one first REIPC github they said "I will not support JEI 10 since it is impossible to support both at the same time, and more mods are on JEI 9." it can be possible to do anything about this like support both 9 and 10? i want to keep apotheosis on my pack

my report on REIPC github: https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/44

here is REIPC page about similar issue: https://github.com/shedaniel/REIPluginCompatibilities-Issues/issues/21

![](https://user-images.githubusercontent.com/119643840/247133844-8dfa2a8e-f444-4be8-8255-8891cf69a084.jpeg)

**Comment by Shadows-of-Fire** [comment]
Well, unfortunately Apoth was updated to JEI 10, and 1.18 is not receiving any further changes. You can either use the old version of apoth, or use JEI instead of REI.

**Comment by Enkvaros** [comment]
Okey i can use old version, which version we talk about and its 1.18 right? if i understand correctly

**Comment by Shadows-of-Fire** [comment]
5.7.7

**Comment by Enkvaros** [comment]
Thanks! have nice day mate
