### ISSUE TITLE
[1.19.2] Modular Tetra items are only recognized as tools, including swords. 

### ISSUE THREAD

**Issue by ambientNexus** [Shadows-of-Fire/Apotheosis#927]
Reforges in the table do not allow for sword rolls, and you cannot socket gems for weapon effects. Any weapons converted into a tetra weapon will have gem effects swapped to tool effects.

**Comment by ambientNexus** [comment]
Seems like the issue only applies if the weapon has "Good Quality" on it.
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2994

**Comment by Shadows-of-Fire** [comment]
There's not really much I can do there - the automated logic only picks up items as tools if they report being able to perform tool actions (`PICKAXE_DIG` or `SHOVEL_DIG`). 
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/loot/LootCategory.java#L49

If Tetra is marking their swords as pickaxes... idk, but I can't fix that.
