### ISSUE TITLE
Recipes from the Enchanting Module missing when i disable the Adventure Module

### ISSUE THREAD

**Issue by Handzz1** [Shadows-of-Fire/Apotheosis#928]
I made a custom modpack in 1.16.2 and when I disable the adventure module some recipes from the enchanting module disappear, the ones that i have noticed are:

- Tome of Superior Scrapping
- Tome of Extraction
There might be more, but this are the ones I noticed.

Those Items appear on JEI but I just can't craft them, unlike the items from the adventure module that just are not in the game.

**Comment by Shadows-of-Fire** [comment]
Those recipes had the wrong conditions in their json files - fixed for 6.3
