### ISSUE TITLE
Mixin issue causing crash with MythicBotany's Mjölnir and Apotheosis' Reforging Table (Forge 1.18.2)

### ISSUE THREAD

**Issue by StAlexandre** [Shadows-of-Fire/Apotheosis#929]
Technically a [repost from MythicBotany's side](https://github.com/noeppi-noeppi/MythicBotany/issues/122)

Here's my log: https://gist.github.com/StAlexandre/025f7bfd75c685fabe7fe0e112d7a938

Reproduction Steps:
1. Install Botania, MythicBotany, and Apotheosis
2. Get/craft Mjölnir and Reforging Table
3. Place Mjölnir in Reforging Table GUI and scroll over the affix descriptions

**Comment by Shadows-of-Fire** [comment]
1.18 is no longer supported, this has already been fixed in 1.19
