### ISSUE TITLE
You can put things into the output slot of the Gem Cutting Table

### ISSUE THREAD

**Issue by SiverDX** [Shadows-of-Fire/Apotheosis#932]
Fresh install (+ JEI) for latest 1.19.2 version

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/c806c9e8-aae1-46cd-b382-2961af5a547c)

If you place a gem or gem dust into their slots the item in the output slot gets deleted

**Comment by Shadows-of-Fire** [comment]
6.3.0
