### ISSUE TITLE
[Forge 1.19.2] Crashes alongside Goblin Traders 

### ISSUE THREAD

**Issue by RiftSpatial** [Shadows-of-Fire/Apotheosis#933]
I found that Apotheosis was causing a crash with Goblin Traders installed.

**Comment by Shadows-of-Fire** [comment]
Provide a crash report

**Comment by RiftSpatial** [comment]
[crash-2023-06-30_22.27.25-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11924194/crash-2023-06-30_22.27.25-client.txt)

**Comment by RiftSpatial** [comment]
I removed Apotheosis after this and it worked.

**Comment by RiftSpatial** [comment]
I just tested with only the two mods and it worked, must be a combination with another mod.

**Comment by SiverDX** [comment]
Apotheosis is not compatible with this 

https://www.curseforge.com/minecraft/mc-mods/unique-enchantments

**Comment by RiftSpatial** [comment]
Alright, thank you for pointing that out. Not Enough Crashes was pinning it on Goblin Traders solely, and not on any other mods, but it may just be an error on NECs part, which I've seen plenty.

**Comment by RiftSpatial** [comment]
I also had trouble getting the world to actually load spawn, and Apotheosis was the only mod I removed, so it must have been the cause of both.
