### ISSUE TITLE
[Forge 1.19.2] Crash when creating random loot

### ISSUE THREAD

**Issue by mistermacflurry** [Shadows-of-Fire/Apotheosis#934]
Hi, I have Apotheosis 6.2.1 in a modded server with friends and the server has already crashed various times when Apotheosis (i think) tries to create a random rarity for an item.

The crash file: https://gist.github.com/mistermacflurry/f03bc0d45db31100515888d4662cbb96

And the crash part of the log file: https://gist.github.com/mistermacflurry/79ed14383f86f716a7ef28bdac7b7c9e

**Comment by Shadows-of-Fire** [comment]
Haev you made any modifications to the apotheosis via datapack? It looks like something, somewhere, has invalid rarity bounds.

**Comment by mistermacflurry** [comment]
Yes, i have change some affix values and added items from other mods to the items pool. I will look where is the error. Thanks!

Edit: I think it could be the festive affix. I wanted to override it so it doesnt appear and let the "type" in blank.

{
	"type": "",
	"values": {
		"epic": {
			"min": 0.0,
			"steps": 1,
			"step": 0.0
		},
		"mythic": {
			"min": 0.00,
			"steps": 5,
			"step": 0.0
		},
		"ancient": {
			"min": 0.0,
			"steps": 8,
			"step": 0.0
		}
	},
	"types": [
		"NOTHING"
	]
}

**Comment by SiverDX** [comment]
Instead of
``` json
{
    "type": "",
    "values": {
        "epic": {
            "min": 0.0,
            "steps": 1,
            "step": 0.0
        },
        "mythic": {
            "min": 0.00,
            "steps": 5,
            "step": 0.0
        },
        "ancient": {
            "min": 0.0,
            "steps": 8,
            "step": 0.0
        }
    },
    "types": [
        "NOTHING"
    ]
}
```

do this
``` json
{
    "conditions": [
        { "type": "forge:false" }
    ]
}
```

**Comment by Shadows-of-Fire** [comment]
This is likely the result of a bad datapack. I'm adding some additional validation to catch it, but yeah
