### ISSUE TITLE
can't modify boss tiers in any dimensions

### ISSUE THREAD

**Issue by StarWalker1** [Shadows-of-Fire/Apotheosis#935]
I can't change what tier of boss spawns in any dimension, including the overworld, nether and end. changing the config doesn't do anything. Also can't add boss spawns into other mod dimensions. The rest of the config seems to work.
on forge 1.19.2 version 6.2.1
my adventure config file:
[adventure upload.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/11943752/adventure.upload.txt)

**Comment by SiverDX** [comment]
I think you need to add new bosses as a datapack
https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/bosses

or add your custom dimensions to their `dimensions` list

**Comment by StarWalker1** [comment]
I mean, I can't even prevent mythics from spawning in the end

**Comment by SiverDX** [comment]
you should look at the definitions in the link I posted since the min and max rarity is defined there

**Comment by Shadows-of-Fire** [comment]
Everything relating to bosses is in the individual boss json files, which require modification via datapack.
