### ISSUE TITLE
Gem placement in smithing table causes crash

### ISSUE THREAD

**Issue by postal291** [Shadows-of-Fire/Apotheosis#936]
When placing any gem (tried several types of various effects / qualities) alongside a fluxsaw, the client crashes.

6.2.1 for 1.19.2 (FTB Skies modpack)

**Comment by SiverDX** [comment]
what is a fluxsaw and what are you trying to achieve by using it on an item from another mod?
does it have mod compatibility?

if its recipe based you might want to ask the modpack authors instead

also nothing anyone can do without any logs

(im not the dev btw)

**Comment by Shadows-of-Fire** [comment]
If you are posting an issue without a crash you must provide a crash report.
