### ISSUE TITLE
Issue with socketing gems.

### ISSUE THREAD

**Issue by tyHubbard** [Shadows-of-Fire/Apotheosis#937]
I'm playing on 1.19.2, playing with notable mods like tetra and create, but I have an item which is straight out of the crafting table, into the infuser, and trying to socket a gem into it. However it isn't doing anything, I've gone into a creative world to try and test other combos and none of them are working.

is there something I'm doing wrong? is it possibly a mod conflict I'm unaware of?
Weirder yet is I can modify the tools/weapons with apotheosis modifications and still keep all the benefits.

![Capture](https://github.com/Shadows-of-Fire/Apotheosis/assets/74334910/cf24a653-6588-4933-ab81-eb8f256f6c6c)
![Capture1](https://github.com/Shadows-of-Fire/Apotheosis/assets/74334910/0214088b-fbb8-432a-bd40-8d5c19be5b64)

**Comment by Shadows-of-Fire** [comment]
Socketing is done in a smithing table, not the anvil.

**Comment by tyHubbard** [comment]
oof okay thank you, I guess I can't read, much appreciated.
