### ISSUE TITLE
Not compatible with [Epic Knights: Shields, Armor nd Weapons] weapons in 1.19.2

### ISSUE THREAD

**Issue by liceis114** [Shadows-of-Fire/Apotheosis#938]
[Epic Knights: Shields, Armor and Weapons]'s weapons cannot use the Empty Socket function

**Comment by Shadows-of-Fire** [comment]
Apoth uses a heuristic to determine if items are valid for affixing.  It doesn't always work, so for those cases you can manually set the category in `/config/apotheosis/adventure,cfg` via `"Equipment Type Overrides"`
