### ISSUE TITLE
Invalid player data after server restart

### ISSUE THREAD

**Issue by benurecarmin** [Shadows-of-Fire/Apotheosis#943]
Hi,
I have a problem with my modded server that seems to come from Apotheosis or at least a conflict with another mod, the players are instantly disconnect with, most of the time, "Invalid Player Data" when they try to join the server. No crash-report.
I'm not able to understand exactly what is the conflict, but there is the log.
[debug (14).log](https://github.com/Shadows-of-Fire/Apotheosis/files/12003153/debug.14.log)
[mod list.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12003197/mod.list.txt)

**Comment by SiverDX** [comment]
should ask 

https://github.com/MerchantPug/apugli/blob/309be11a618f9db0979c84e47a1417d9f165300e/Forge/src/main/java/net/merchantpug/apugli/mixin/forge/common/EnchantmentHelperMixin.java#L29

to add a `null` check in their code

**Comment by Shadows-of-Fire** [comment]
That mixin is extra yikes.  Modification of the tag levels of enchantments is how you get dupe glitches all over the place.

But yeah, ultimately that's their problem.  Placebo even has [an event](https://github.com/Shadows-of-Fire/Placebo/blob/1.19/src/main/java/shadows/placebo/events/GetEnchantmentLevelEvent.java) for doing exactly what it is they are failing to do.
