### ISSUE TITLE
1.20.1 support!

### ISSUE THREAD

**Issue by cjldonovan** [Shadows-of-Fire/Apotheosis#945]
Just putting this here so I can get notified if you ever make the mod pack for 1.20.1! 
I love your work and all you've done with it! If their is a better way to be notified as well lmk and then feel free to remove this or lmk to remove it!

**Comment by SiverDX** [comment]
this is really not the place to do this

follow the curseforge page or join the discord and set notifications for the announcement channel

**Comment by Shadows-of-Fire** [comment]
duplicate of #915
