### ISSUE TITLE
Loot affix mistake?

### ISSUE THREAD

**Issue by Rostas** [Shadows-of-Fire/Apotheosis#946]
Apotheosis-1.19.2-6.3.0

I'm not sure if this makes a difference but all of the Fiery equipment have the wrong types in the json files. Other items just say "ARMOR", "BREAKER" etc

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/2160335/1e42acfc-fba4-48a3-af8e-8b818a1bf4f1)

**Comment by Shadows-of-Fire** [comment]
The `type` field is unused in affix loot entries, I just haven't removed it from any of them.

The actual type is inferred from the item being used.
