### ISSUE TITLE
The Boss Spawner block is not set to be transparent, so it lets you see through blocks

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Apotheosis#947]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/f12f37a4-7c68-427d-bf78-f6f9d9145659)

Also note the name isn't localized

**Comment by Shadows-of-Fire** [comment]
Hm

Well the name isn't localized because it has no item form, usually jade/top didn't display those.

I'll fix the transparency thing though, its a minor issue because survival players can't actually see one, but it shouldn't be broken

**Comment by aaronhowser1** [comment]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/0f957af7-638a-4408-b4fd-2d7252dd1f59)
This was the screenshot that was reported to me by a survival player

**Comment by aaronhowser1** [comment]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/07a17c78-4dcf-4093-950b-5638200cebb5)
And TOP does show itself for blocks that don't have items, in my experience

**Comment by Shadows-of-Fire** [comment]
A boss spawner near a survival player *should* delete itself immediately in all cases, so that might be the real bug here...
