### ISSUE TITLE
[Question] Way to remove affix drops from endermen

### ISSUE THREAD

**Issue by felbeatha** [Shadows-of-Fire/Apotheosis#948]
I'm currently setting up a modpack for a small server. We have disabled epic and mythic gear by turning their weight to 0, and don't want things to be too op. While testing, we have found that the end trivializes rare affix gear and also netherite. Is there a way we could make affix gear not generate in the end or just blacklist endermen?

**Comment by Shadows-of-Fire** [comment]
I don't think you could blacklist endermen in general without reducing the configurable Random Affix Chance to zero since that's a global system for all mob spawns.

You could, however, just remove netherite from the gear pools, or buff endermen so they aren't trivial to kill.

**Comment by felbeatha** [comment]
How would I go about removing netherite from loot tables? Sorry, I have no prior experience with modding.

**Comment by Shadows-of-Fire** [comment]
You would need to use a datapack to disable the netherite affix loot entries https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/affix_loot_entries/the_end
