### ISSUE TITLE
Deadly Boss Module Unsafely Modifies Attributes

### ISSUE THREAD

**Issue by Jackiecrazy** [Shadows-of-Fire/Apotheosis#95]
The deadly bosses don't check for null attributes when they spawn. For certain mobs that may miss certain values, e.g. sheep that don't have attack damage, or AoA mobs that don't have armor values (I think), the following crash occurs:
https://pastebin.com/dvUj6DcZ

**Comment by Shadows-of-Fire** [comment]
Mobs that are not instance MobEntity (like sheep) are not supported for the boss system.
Looks like the error detection could use some work though.

**Comment by Jackiecrazy** [comment]
The issue was generated with AoA. I'm not sure why it happens, actually.

**Comment by Shadows-of-Fire** [comment]
If you could source what entity causes the issue, I can try to figure out why it causes it.  Chances are it's not an EntityMob, because those attributes are part of that base class

**Comment by Jackiecrazy** [comment]
Hmm. I believe my entire config was EntityMob... but I see now, ranged mobs aren't assigned an attack damage in AoA. Side note, is there a way to disable the enchantment tweaks, but keep the enchantability tweaks? Specifically, I want the enchantment table to cap at level 30, but it only gives me low level enchants if I do so. Also, Quark's ancient tomes cease working with enchanted books, I'm not sure why.

**Comment by Shadows-of-Fire** [comment]
You could achieve it by doing a bit of config work, there's no simple "enable half of the ench module" system, so you'd need to adjust all the levels and max powers back down to original.
As for the quark tomes, i'm not sure why they're broken, I'd have to look into quark's anvil update handler.

**Comment by Shadows-of-Fire** [comment]
Closed via https://github.com/Shadows-of-Fire/Placebo/commit/4cbbd564c29932d2cbf401a85a977e107f05a250
