### ISSUE TITLE
Crash when using Apoth 6.3.0 with irons spells mod

### ISSUE THREAD

**Issue by Faith6001** [Shadows-of-Fire/Apotheosis#951]
Version 6.2.1 of Apoth works with Iron's Spells 'n Spellbooks, but once you update to 6.3.0 you get a crash report on startup (reproducable)

crash report:
[crash-2023-07-17_19.20.08-fml.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12072236/crash-2023-07-17_19.20.08-fml.txt)

**Comment by SiverDX** [comment]
https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/104
