### ISSUE TITLE
Disabling Adventure Module Results in "Data pack validation failed!"

### ISSUE THREAD

**Issue by purplepumpkin09182** [Shadows-of-Fire/Apotheosis#955]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/139901190/d8fcf806-38fc-461a-ad78-88f80e3b86aa)

Whenever I try to create or load a world with the adventure module disabled via the apotheosis.cfg file, it results in a message saying "Data pack validation failed!" This issue only seems to be affecting the latest version of the mod (6.3.0) and it only happens with the adventure module. I disabled each module individually and did not get any error message. 

To be extra thorough, I created an entirely new modpack with just apotheosis in it (and the mods it tells the curseforge launcher to get too) so that I knew it wasn't some other mod I installed messing things up.

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/139901190/f0aa2405-13f8-4f45-b169-5b91be2bc5e3)

To be extra _extra_ thorough, I tried to see if this happened with every version of forge the current apotheosis mod is compatible with (43.2.14-43.2.21) and I got the same error across all versions tested.

I don't know if this information helps, but I figured I should include it anyway to be safe.
If I click "reset to default" it allows me to create a world as if nothing were wrong. However, when I quit out of that world and attempt to load back into it, I get this:

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/139901190/b787298a-b187-44b7-bed9-89b7386c2654)

Clicking "Safe Mode" does literally nothing. I hear the click sound but nothing happens. However, I found that this issue gets resolved completely simply by reactivating the adventure module.

That's all I could think of to include in this. Apologies in advance if it's too long or I left out some critical detail. This is my first time bug reporting lol.

**Comment by ScoutTheSaneless** [comment]
Just about to mention that this bug had shown it's ugly mug again. Is something up w Forge again or what?

**Comment by Shadows-of-Fire** [comment]
It is partially a result of https://github.com/MinecraftForge/MinecraftForge/pull/9293 not being merged. I'm working on implementing the relevant parts of it locally.

**Comment by SiverDX** [comment]
it's because of the structure 
as a workaround you could try creating a datapack which overrides the processor (I think that was the problematic part) when  you want to disable the adventure module

**Comment by Shadows-of-Fire** [comment]
Fixed in 6.3.1
