### ISSUE TITLE
[Apoth 6.3] Attack range description bug

### ISSUE THREAD

**Issue by mistermacflurry** [Shadows-of-Fire/Apotheosis#958]
With the new 6.3 update, every weapon tootltip (including modded weapons) shows 2 Attack Range descriptions. One with a base value of 3 and another (i suppose from the Better Combat mod) that changes between weapons types. This didnt happened in 6.2.1, where only the second one was shown.

### **6.2.1**
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/134368988/616ca716-644f-45eb-b751-377da00cc062)

### **6.3**
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/134368988/81a604ad-743d-4fc8-a3be-ebe81615c4c0)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/134368988/520bc0b8-a2e2-4cfd-af4c-4a4027d87a0d)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/134368988/1a09e589-ba32-4241-a2c7-75af78cddd3b)

**Comment by SiverDX** [comment]
> Due to BC's unwillingness to support the Forge Attack Range attribute, I have elected to not provide any support for BC-related issues. See [ZsoltMolnarrr/BetterCombat#244](https://github.com/ZsoltMolnarrr/BetterCombat/issues/244) and [ZsoltMolnarrr/BetterCombat#266](https://github.com/ZsoltMolnarrr/BetterCombat/issues/266)

To give more explanation:
You are seeing the attack range attribute from forge itself which every mod uses (if they use attack range)
And a new attack range attribute solely from Better Combat which breaks the forge attack range attribute (and therefor every mod which uses it)
