### ISSUE TITLE
[Bug] [Apoth 6.3] Anvils crash with Easy Anvils and Apoth while the Enchantment Module disabled

### ISSUE THREAD

**Issue by SoulRacer65** [Shadows-of-Fire/Apotheosis#961]
While trying to open or place an anvil with the mods Easy Anvils & Apotheosis with the Enchantment Module is disabled it causes the game to crash, I have tested this multiple times in both old and new worlds and re-enabling the Enchant Module.

[crash-2023-07-23_13.11.51-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12139659/crash-2023-07-23_13.11.51-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is an issue with whatever compat code easy anvils has for apoth, as it seems like they are unconditionally reaching into ench module code even if it is disabled.
