### ISSUE TITLE
The gems in towers are always identical

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Apotheosis#962]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/7cb1eaa3-847f-42a5-817e-5fcadc463c14)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/a14817cd-d9cf-4616-855e-e53b28c1a16c)

Reported to me by players on my server, using Apotheosis-1.19.2-6.3.1. This problem wasn't in previous versions, according to them.

**Comment by Shadows-of-Fire** [comment]
That's uh, weird.  The random that generates them is seeded based on the tower's position

**Comment by aaronhowser1** [comment]
There's multiple Item Frames per tower, each has the same gem inside. 4 per tower

**Comment by aaronhowser1** [comment]
> seed: -2439561773624327919
> /tp @s 432 ~ 880
> generated 2 worlds with same seed but one with 6.3.0 version and other with 6.3.1
the one with 6.3.0 (prev version) has diffirent gems and the 6.3.1 (new version) has identical gems 

to quote the player

**Comment by aaronhowser1** [comment]
Sorry, let me clarify. Gems are identical *within towers*. They're different per tower, but each tower only has the same gem 4 times.

**Comment by Marius-jj** [comment]
Yeah same for me, different per tower, but each tower always contains 4 identical gems.
