### ISSUE TITLE
Crashing While Socketing Mjolnir

### ISSUE THREAD

**Issue by SerPedr** [Shadows-of-Fire/Apotheosis#963]
Mjolnir from Mythic Botany CAN be given affixes with no issue however once you try to add a gem into the sockets via the smithing table all seems fine until and only until you go to take the new socketed mjolnir out of the table. Game crashes and takes you to the launcher with an error code. Just thought I would mention this since I hadn't seen any search results about this issue.
[crash-2023-07-25_03.54.56-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12159185/crash-2023-07-25_03.54.56-client.txt)

**Comment by Shadows-of-Fire** [comment]
You're using an outdated version of apoth - this was fixed in 6.3.0

**Comment by SerPedr** [comment]
> 

Well thank you very much for the info and a rapid response. Will let our server host know too.
