### ISSUE TITLE
Can't stack gems in containers.

### ISSUE THREAD

**Issue by Marius-jj** [Shadows-of-Fire/Apotheosis#964]
I am not able to stack gems when they are inside chest and barrels, I have to take them out and in to my player inventory and stack them there, then move them to the chest again.

Using Apotheosis-1.19.2-6.3.1 and forge version 43.2.21.

**Comment by Shadows-of-Fire** [comment]
Unfortunately the only mechanism to remove nbt data from gems requires them being in the player inventory, so any old gems (from pre-6.3) will require being placed in a player inventory first.
