### ISSUE TITLE
When a Seagull from Alex's Mobs picks up items, the tag apoth.equipment=1 is added

### ISSUE THREAD

**Issue by aaronhowser1** [Shadows-of-Fire/Apotheosis#965]
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/4a0f1708-e882-4181-92c1-240c8379b0ba)

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/d1026f14-a955-4c34-a848-742e02092e66)
This makes it so it doesn't stack. It's held in `HandItems` so maybe it think's its like a naturally spawned weapon or something?

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/15698722/f7721ff4-a621-4aed-87ed-b0b1baab188c)

This is using Apotheosis-1.19.2-6.3.1

**Comment by Shadows-of-Fire** [comment]
The marker is only added on entity death (and is then removed in the drops event) - you're saying it gains the nbt as soon as it picks up the item?

<https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/adventure/affix/effect/FestiveAffix.java#L71>

**Comment by aaronhowser1** [comment]
I threw down a normal stack of steak, summoned a seagull, waited for it to pick the item up, then took the first screenshot (and the third, after repeating that).

Then I killed it, picked up the steak it dropped, looked at its NBT, and took the second screenshot that has the wonky NBT. It didn't have the NBT while the Seagull was holding it. Ideally, the NBT would not be added to the steak whatsoever.

**Comment by Shadows-of-Fire** [comment]
The nbt should be removed unconditionally, not being removed means the drops event isn't firing (or for some reason the seagull is coded in a way that hides the item from the drops event).

I see nothing to indicate that the seagull is doing this natively, was this in a larger modpack or isolation?

**Comment by aaronhowser1** [comment]
Yes, there's like 250 mods. The pack is unreleased unfortunately, but here's a mod list

<details>

- accelerated-decay-forge-1.0.0+mc1.19.2.jar
- AdvancedPeripherals-1.19.2-0.7.29r.jar
- AEInfinityBooster-1.19.2-1.2.0+11.jar
- AI-Improvements-1.19.2-0.5.2.jar
- AkashicTome-1.6-23.jar
- alexsmobs-1.21.1.jar
- almostunified-forge-1.19.2-0.5.0.jar
- alternate-current-mc1.19-1.7.0.jar
- AmbientEnvironment-forge-1.19.2-8.0+3.jar
- Amplified_Nether_1.19.3_v1.2.1.jar
- Apotheosis-1.19.2-6.3.1.jar
- appleskin-forge-mc1.19-2.4.2.jar
- Applied-Botanics-1.4.2.jar
- Applied-Mekanistics-1.3.4.jar
- appliedenergistics2-forge-12.9.5.jar
- architectury-6.5.85-forge.jar
- arsarmiger-1.19.2-1.4.0.jar
- ars_creo-1.19.2-3.2.1.jar
- ars_elemental-1.19.2-0.5.9.1.2b.jar
- ars_nouveau-1.19.2-3.17.9.jar
- artifacts-1.19.2-5.0.3.jar
- art_of_forging-1.6.7-1.19.2.jar
- AttributeFix-Forge-1.19.2-17.2.7.jar
- AutoRegLib-1.8.2-55.jar
- auudio_forge_1.0.3_MC_1.19.jar
- balm-forge-1.19.2-4.5.7.jar
- BetterAdvancements-1.19.2-0.3.0.148.jar
- BetterCompatibilityChecker-1.0.10-build.50+mc1.19.2.jar
- betterfpsdist-1.19.2-2.9.jar
- Bookshelf-Forge-1.19.2-16.3.20.jar
- Botania-1.19.2-440-FORGE.jar
- botarium-forge-1.19.2-1.8.2.jar
- buildinggadgets-3.16.2-build.22+mc1.19.2.jar
- canary-mc1.19.2-0.2.7.jar
- catalogue-1.7.0-1.19.2.jar
- cc-tweaked-1.19.2-1.101.3.jar
- cccbridge-mc1.19.2-forge-v1.5.1.jar
- chipped-forge-1.19.2-2.1.5.jar
- chisels-and-bits-forge-1.3.135.jar
- citadel-2.1.4-1.19.jar
- ClickMachine-1.19.2-7.0.0.jar
- clienttweaks-forge-1.19.2-8.1.2.jar
- cloth-config-8.3.103-forge.jar
- Clumps-forge-1.19.2-9.0.0+14.jar
- CNB-1.19-1.5.4.jar
- CobbleForDays-1.6.0.jar
- CodeChickenLib-1.19.2-4.3.1.481-universal.jar
- CommonCapabilities-1.19.2-2.9.0.jar
- compactmachines-5.1.0.jar
- compressedcreativity-1.19.2-0.1.7.jar
- Compressium-2.1.1-build.8+mc1.19.jar
- configured-2.1.1-1.19.2.jar
- Controlling-forge-1.19.2-10.0+7.jar
- CosmeticArmorReworked-1.19.2-v1a.jar
- craftingstation-1.19.2-6.0.1.jar
- craftingtweaks-forge-1.19.2-15.1.7.jar
- create-1.19.2-0.5.1.c.jar
- create-confectionery1.19.2_v1.0.9.jar
- createchunkloading-1.5.0-forge.jar
- create_misc_and_things_  1.19.2_3.0.jar
- creeperoverhaul-2.0.9-forge.jar
- crittersandcompanions-1.19.2-2.0.2.jar
- CTM-1.19.2-1.1.6+8.jar
- curios-forge-1.19.2-5.1.4.1.jar
- CyclopsCore-1.19.2-1.18.6.jar
- dankstorage-1.19.2-5.1.6.jar
- DarkUtilities-Forge-1.19.2-13.1.9.jar
- default-server-properties-forge-77.1.0.jar
- defaultoptions-forge-1.19-15.0.1.jar
- dummmmmmy-1.19.2-1.7.1.jar
- dynview-1.19.1-2.9.jar
- effective_fg-1.3.4.jar
- effortlessbuilding-1.19.2-3.3.jar
- elevatorid-1.19.2-1.8.9.jar
- Emojiful-Forge-1.19.2-4.0.4-all.jar
- EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
- engineersdecor-1.19.2-forge-1.3.28.jar
- EnhancedBlockEntities-Reforged-1.19.2-0.8.0.jar
- entangled-1.3.14-forge-mc1.19.2.jar
- entityculling-forge-1.6.1-mc1.19.2.jar
- Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
- EverlastingAbilities-1.19.2-2.1.1.jar
- EvilCraft-1.19.2-1.2.24.jar
- ExplorersCompass-1.19.2-1.3.0-forge.jar
- extremesoundmuffler-3.37-forge-1.19.2.jar
- farsight-1.19.2-2.1.jar
- FastFurnace-1.19.2-7.0.0.jar
- FastSuite-1.19.2-4.1.0.jar
- FastWorkbench-1.19.2-7.1.4.jar
- ferritecore-5.0.3-forge.jar
- findme-3.1.0-forge.jar
- FluxNetworks-1.19.2-7.1.4.13.jar
- FramedBlocks-6.8.4.jar
- ftb-banners-1.0.0-build.31-20230427.152744-1.jar
- ftb-chunks-forge-1902.4.1-build.290.jar
- ftb-essentials-forge-1902.3.3-build.100.jar
- ftb-library-forge-1902.4.1-build.236.jar
- ftb-pack-companion-2.0.3-build.8+mc1.19.2.jar
- ftb-quests-forge-1902.5.1-build.250.jar
- ftb-ranks-forge-1902.1.15-build.77.jar
- ftb-schools-1.0.1-20230724.150537-1.jar
- ftb-teams-forge-1902.2.14-build.123.jar
- ftb-ultimine-forge-1902.4.1-build.90.jar
- ftb-xmod-compat-forge-1.2.0.jar
- ftbauxilium-forge-1902.1.10-build.42-forge.jar
- ftbbackups2-forge-1.19.2-1.0.20.jar
- fullstackwatchdog-1.0.1+1.19.2-forge.jar
- functionalstorage-1.19.2-1.1.4.jar
- gag-forge-2.0.0-build.8.jar
- GameStages-Forge-1.19.2-11.1.4.jar
- geckolib-forge-1.19-3.1.40.jar
- glassential-forge-1.19-1.2.4.jar
- hexal-forge-1.19.2-0.2.18.jar
- hexcasting-forge-1.19.2-0.10.3.jar
- HostileNeuralNetworks-1.19.2-4.1.1.jar
- Iceberg-1.19.2-forge-1.1.4.jar
- idas_forge-1.7.6+1.19.2.jar
- ImmediatelyFastReforged-1.19.2-1.1.12.jar
- ImmersiveEngineering-1.19.2-9.2.2-165.jar
- immersive_weathering-1.19.2-1.2.9-forge.jar
- Incendium_1.19.3_v5.1.6.jar
- IntegratedCrafting-1.19.2-1.1.2.jar
- IntegratedDynamics-1.19.2-1.16.9.jar
- integratednbt-1.19.2-1.6.0.jar
- IntegratedTerminals-1.19.2-1.4.8.jar
- IntegratedTunnels-1.19.2-1.8.20.jar
- integrated_api_forge-1.2.7+1.19.2.jar
- inventoryessentials-forge-1.19-5.0.2.jar
- inventorysorter-22.0.0.jar
- ironchest-1.19.2-14.2.7.jar
- item-filters-forge-1902.2.9-build.51.jar
- JAMD-Forge-2.1.2+mc1.19.2.jar
- JAOPCA-1.19.2-4.2.7.14.jar
- jecalculation-forge-1.19.2-4.0.2.jar
- jeed-1.19.2-2.1.4.jar
- jei-1.19.2-forge-11.6.0.1016.jar
- jeimultiblocks-1.19.2-0.0.3.jar
- JustEnoughProfessions-forge-1.19.2-2.0.2.jar
- JustEnoughResources-1.19.2-1.2.2.200.jar
- kleeslabs-forge-1.19.2-12.3.0.jar
- konkrete_forge_1.6.1_MC_1.19-1.19.2.jar
- kotlinforforge-3.12.0-all.jar
- kubejs-forge-1902.6.1-build.327.jar
- kubejs-mekanism-1902.1.5-build.15.jar
- laserio-1.5.2.jar
- lazydfu-1.19-1.0.2.jar
- light-overlay-7.0.1-forge.jar
- lightspeed-1.19.2-1.0.5.jar
- littlebotanics-1.00-1.19.2.jar
- littlecontraptions-forge-1.19.2.2.jar
- littlelogistics-mc1.19.2-v1.4.0.jar
- lofirecordstomineto-1.19.2-1.1.1.jar
- lootjs-forge-1.19.2-2.9.0.jar
- lootr-1.19-0.4.24.62.jar
- MaxHealthFix-Forge-1.19.2-8.0.2.jar
- mcjtylib-1.19-7.2.5.jar
- megacells-forge-2.0.1-1.19.2.jar
- Mekanism-1.19.2-10.3.9.13.jar
- Mekanism-Evolution-1.19.2-1.3.4.jar
- Mekanism-MoreSolarPanels-1.19.2-1.5.2.jar
- MekanismAdditions-1.19.2-10.3.9.13.jar
- MekanismGenerators-1.19.2-10.3.9.13.jar
- MekanismTools-1.19.2-10.3.9.13.jar
- merequester-1.19.2-1.1.2.jar
- mininggadgets-1.13.0.jar
- mob_grinding_utils-1.19.2-0.4.50.jar
- modernfix-forge-5.3.2+mc1.19.2.jar
- modnametooltip-1.20.1-1.20.0.jar
- modular-routers-1.19.2-10.2.0-3.jar
- moonlight-1.19.2-2.2.43-forge.jar
- moredragoneggs-3.2.jar
- MouseTweaks-forge-mc1.19-2.23.jar
- MultiMine-1.19.2.3.jar
- mutil-1.19.2-5.1.0.jar
- NaturesAura-38.2.jar
- NaturesCompass-1.19.2-1.10.0-forge.jar
- NekosEnchantedBooks-1.19-1.8.0.jar
- notenoughcrashes-4.2.1+1.19.2-forge.jar
- Nullscape_1.19.3_v1.2.1a.jar
- observable-3.3.1.jar
- oculus-flywheel-compat-1.19.2-0.2.1.jar
- oculus-mc1.19.2-1.6.4.jar
- overloadedarmorbar-1.19.3-7.2.jar
- ParCool-1.19.2-3.0.1.0-R.jar
- Patchouli-1.19.2-77.jar
- paucal-forge-1.19.2-0.5.0.jar
- PigPen-Forge-1.19.2-11.1.2.jar
- pitchperfect-1.19.2-1.3.1.jar
- Placebo-1.19.2-7.3.1.jar
- pluto-mc1.19.2-0.0.9.jar
- pneumaticcraft-repressurized-1.19.2-4.3.6-27.jar
- polylib-forge-1900.0.2-build.73.jar
- polymorph-forge-0.46.4+1.19.2.jar
- ponderjs-1.19.2-1.2.0.jar
- prefab-1.9.2.5.jar
- PrettyPipes-1.13.6.jar
- Prism-1.19.1-1.0.2.jar
- probejs-5.3.0-forge-hotfix.jar
- Quark-3.4-405.jar
- QuarkOddities-1.18.jar
- radon-0.8.2.jar
- RecipeStages-4.0.0.7.jar
- reforgium-1.0.12a.jar
- repurposed_structures_forge-6.3.24+1.19.2.jar
- resourcefulconfig-forge-1.19.2-1.0.20.jar
- resourcefullib-forge-1.19.2-1.1.24.jar
- rftoolsbase-1.19-4.1.7.jar
- rftoolsbuilder-1.19-5.2.8.jar
- rftoolscontrol-1.19-6.1.4.jar
- rftoolsdim-1.19.2-9.1.7.jar
- rftoolspower-1.19-5.1.2.jar
- rftoolsstorage-1.19-4.1.2.jar
- rftoolsutility-1.19-5.1.7.jar
- rhino-forge-1902.2.2-build.268.jar
- rubidium-0.6.2b.jar
- rubidium_extras-1.19.2_v1.4.3.jar
- Runelic-Forge-1.19.2-14.1.4.jar
- saturn-mc1.19.2-0.0.4.jar
- scannable-MC1.19.2-forge-1.7.7+dc5ea09.jar
- serverconfigupdater-3.2.jar
- Shrink-1.19-1.3.5.jar
- SimpleDiscordRichPresence-forge-3.0.4-build.27+mc1.19.2.jar
- simplygraves-1.19.2-1.0.5-build.5.jar
- simplylight-1.19.2-1.4.5-build.42.jar
- SlimyBoyos-forge-1.19.2-5.0.0.5.jar
- SmartBrainLib-forge-1.19.2-1.9.jar
- smoothboot(reloaded)-mc1.19.2-0.0.2.jar
- smoothchunk-1.19.1-2.0.jar
- sophisticatedbackpacks-1.19.2-3.18.55.889.jar
- sophisticatedcore-1.19.2-0.5.81.377.jar
- soulshards-1.19-1.3.4.jar
- spark-1.10.37-forge.jar
- spiderstpo-1.19.2-2.0.4.jar
- squatgrow-3.0.0-build.33+mc1.19.2.jar
- starlight-1.1.1+forge.cf5b10b.jar
- Statues-1.19.2-0.3.2.9.jar
- Steam_Rails-1.4.3+forge-mc1.19.2.jar
- SuperFactoryManager-1.19.2-4.12.0.jar
- supermartijn642configlib-1.1.7-forge-mc1.19.jar
- supermartijn642corelib-1.1.12-forge-mc1.19.2.jar
- supplementaries-1.19.2-2.3.20.jar
- tetra-1.19.2-5.3.1.jar
- tetranomicon-1.4.2-1.19.2.jar
- theoneprobe-1.19-6.2.2.jar
- tinygates-1.19.2-3.1.2.jar
- tinypipes-1.19.2-3.1.4.jar
- tinyredstone-1.19.2-4.1.5.jar
- Tips-Forge-1.19.2-8.0.27.jar
- TipTheScales-forge-1.19.2-6.0.10.jar
- titanium-1.19.2-3.7.3-27.jar
- trashcans-1.0.18-forge-mc1.19.jar
- xnet-1.19-5.1.4.jar
- xnetgases-1.19.2-4.0.1.jar
- yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
- YungsApi-1.19.2-Forge-3.8.9.jar
- YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
- YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
- YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
- YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar

</details>

**Comment by Shadows-of-Fire** [comment]
I'm going to change the marker removal event handler to be a lowest-prio that receives cancelled events, so hopefully that fixes it.  If not it means the event isn't getting posted and idk what to do about that.
