### ISSUE TITLE
Game Crash  Failed to create player model for default

### ISSUE THREAD

**Issue by KaiHaruki** [Shadows-of-Fire/Apotheosis#966]
I ran to trouble of recent 2 updates

https://paste.ee/p/a67vx

Regard

**Comment by SiverDX** [comment]
can you post your latest.log file?

**Comment by KaiHaruki** [comment]
Here the latest log 
https://paste.ee/p/58T3w

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/passive-skill-tree is not compatible with the latest version of apotheosis
