### ISSUE TITLE
Max Health Gems not adding correctly.

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#969]
Hey, posting here to bring a max health gem issue to your attention. For reference, I've applied this to the Dragon Armor from Gobber 2 on Direwolf20 v1.11.1 (MC 1.19). Each armor piece has +15 Max Health on it (attribute boost, not gem boost). Upon applying the max tier flawless Gem of the Warlord and Brawler's Gem, I noticed that instead of the 145 Max Health I should have had, I only had 112.5 Health. After messing around with this, I found that the issue seemed to be as follows.

When putting on both pieces of core armor, the health boost from the gems on whichever core armor piece is applied second does not apply. For instance, I put on the chestplate, which has +15 from stats, +20 (warlord) and +12.5 (brawler), my health goes from 20 to 67.5, as expected. Same result when putting on the leggings. When I slot the second core piece on, which has the same stat boost and gem boosts, (+15, warlord, brawler), my health goes from 67.5 to 82.5, i.e. +15.

So I'm curious if I've somehow messed up my armor, or if this is a mod issue. Anybody else seen this?

**Comment by Shadows-of-Fire** [comment]
The only thing that could cause what you're experiencing is gem UUID duplication - this was fixed for new gems in Apotheosis 6.3.0, but still impacts all older versions.

This problem occurs when you socket two exact duplicate gems (those from loot pinata, the creative menu, or JEI), as these gems have the same NBT-encoded UUID and you may only have one attribute modifier per UUID at any time.

**Comment by ghost** [comment]
Ahh that makes sense, thank you for the clarification.
