### ISSUE TITLE
Apotheosis & Passive Skill Tree

### ISSUE THREAD

**Issue by OxiiGiin1** [Shadows-of-Fire/Apotheosis#971]
[crash-2023-08-03_15.29.06-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12254913/crash-2023-08-03_15.29.06-client.txt)

I keep getting this crash. I've talk with the owner of PST and he wanted me to reach out to you.

**Comment by Shadows-of-Fire** [comment]
Passive skill tree is invoking `setSockets` before the socket affix is loaded via datapack registry (on world start), which crashes.
