### ISSUE TITLE
Failed to locate any affixes for air{null} with category LootCategory{ring} and rarity LootRarity{uncommon}

### ISSUE THREAD

**Issue by Tokohiko** [Shadows-of-Fire/Apotheosis#972]
Hello.
This is my first time reporting an issue with a mod, so if I'm missing any information or formatted something wrong, let me know.

I've been encountering this issue since updating my server to Apotheosis 6.3.0. This issue has also been replicated in singleplayer.

At the same time, I updated Passive Skill Tree mod to BETA-0.5 and Iron's Spells n' Spellbooks v1.19.2-1.2.0.
I am playing on the Medieval Minecraft modpack, so these three mods were updated manually.

Attached is the crash log.

[crash-2023-08-04_02.42.32-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12259469/crash-2023-08-04_02.42.32-server.txt)

**Comment by SiverDX** [comment]
ring and necklace are two loot categories added by the passive skill trees mod
the error might be due to their implementation of said categories - you're better off askin them about it

**Comment by Tokohiko** [comment]
Got it; I figured it would have been an issue with either of the two mods, but it's curious because both mods say they've updated for 6.3.0 support.

Thanks for the reply.
I will keep the thread open for any potential updates from the Passive Skill Tree dev.

**Comment by SiverDX** [comment]
well im assuming this problem also stems from some other mods (or configurations) of your modpack
e.g. some weird things ending up in the curios ring tag (which seems to be what passive skill tree is checking for valid items)

https://github.com/Daripher/Passive-Skill-Tree/blob/8f65fd8434a6c16ad7e0e19e3b670df83e9528bf/src/main/java/daripher/skilltree/compat/apotheosis/ApotheosisCompatibility.java#L52

meaning it probably works with apotheosis and lots of other mods, just not your modpack

**Comment by Tokohiko** [comment]
_That's what I was also thinking.

Is there any way to brute force the config/coding to remedy this particular instance?
I'm not well-versed in code language, but I was assuming the game was crashing because it was trying to generate an affix for the ring loot category.

Is it possible via Apotheosis config, for example, to disable an item generating with prefixes?_

Edit:
Scratch that, skills tree dev pushed out an update.
Testing to see if that fixed the errors.
