### ISSUE TITLE
[Bug] 1.19.2 Cannot invoke "shadows.apotheosis.util.FloatReferenceHolder.set(float)" because "this.eterna" is null

### ISSUE THREAD

**Issue by CKY-** [Shadows-of-Fire/Apotheosis#973]
```[05Aug2023 01:16:49.691] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5c743c88, suppressing error
java.lang.NullPointerException: Cannot invoke "shadows.apotheosis.util.FloatReferenceHolder.set(float)" because "this.eterna" is null
```
The enchanter menu will not open

here is the full log 
https://gist.github.com/CKY-/ee7de8153734996501b960d7e6d3f5ea

Apotheosis: 1.19.2-6.3.2
Forge: 43.2.21

**Comment by Shadows-of-Fire** [comment]
Do you have other mods installed that mess with the enchanting table?  Lapis Reserve in particular is known to cause this crash.

**Comment by CKY-** [comment]
> Do you have other mods installed that mess with the enchanting table? Lapis Reserve in particular is known to cause this crash.

quark is the only other one that I can think of but that table is supposed to be disabled in the config.

**Comment by CKY-** [comment]
Lapis Reserve was installed, Sorry I missed that part of your Question. 

I try not to have 2 mods that do the same thing due to conflicts. 

thank you for your time and looking into this.. I will notate this for next time.
