### ISSUE TITLE
Missing particle textrue

### ISSUE THREAD

**Issue by Karashok-Leo** [Shadows-of-Fire/Apotheosis#975]
id: apotheosis:enchant_water
screenshot: https://sm.ms/image/t9oEuOLq3M1dTDN

**Comment by Shadows-of-Fire** [comment]
What version?  I can observe it working correctly in 6.3.2

**Comment by Karashok-Leo** [comment]
Sorry for replying so late. I was using 6.3.2 at the moment. Today I update the mod to 6.3.5 but the issue still exists. I am not sure if it is caused by mods conflicts or sth else..

**Comment by Karashok-Leo** [comment]
I find it. It's "sga_i_water". You mistakenly entered the lowercase " i " into uppercase (so similar to lowercase “ L ”)
