### ISSUE TITLE
Better Compatibility with Epic Fight/Epic Knights

### ISSUE THREAD

**Issue by Elldar112** [Shadows-of-Fire/Apotheosis#978]
It seems like most weapons in Epic Fight/Epic Knights mod have max block statistic and because of that Apotheosis considers them shields instead of weapons and rolls defensive affixes instead of offensive and reqire item to be put in offhand to even take place.

**Comment by Shadows-of-Fire** [comment]
Unfortunately due to the way the order of precedence works, shields are checked first, because there is no definitive check for "sword-class" items so that check is "does this item have attack damage".

You can use the adventure module config file to override the types for specific items.
