### ISSUE TITLE
1.19.2 crash bug: Apotheosis (apparently) improperly missing a null check before tryign to spawn in blue skies dimension

### ISSUE THREAD

**Issue by mberlin1** [Shadows-of-Fire/Apotheosis#980]
please see attached issue at:  https://gitlab.com/modding-legacy/blue-skies/-/issues/175

**Comment by Shadows-of-Fire** [comment]
This is the result of user error, you cannot configure bosses to spawn for a dimension without providing any bosses for that dimension.

**Comment by mberlin1** [comment]
I'm not sure what you're stating here -- the adventure file had a boss statement for both skies dimensions as the other dimensions did (which worked fine), in this case the blue skies folks block such spawns. It seems like you forgot to check for a null instantiation before assuming the object would in fact be non-null.

**Comment by Shadows-of-Fire** [comment]
Apotheosis does not ship a spawn rule for any dimension other than the overworld, nether, end, and twilight forest.  Any other modifications are done by the user (or pack developer), and it is their responsibility to provide adequate boss jsons.

**Comment by mberlin1** [comment]
Alright ,and if they mimic the existing spawn lines exactly, shouldn't they be expected to function just like the others? And if they don't function just like the others, whose responsibility is that?

**Comment by Shadows-of-Fire** [comment]
No, boss json files must be provided by a datapack
https://github.com/Shadows-of-Fire/Apotheosis/tree/1.19/src/main/resources/data/apotheosis/bosses

**Comment by mberlin1** [comment]
Thank you, i'll take a look.
