### ISSUE TITLE
[1.19.2] New Update Crash

### ISSUE THREAD

**Issue by Loufoque09** [Shadows-of-Fire/Apotheosis#983]
MC: 1.19.2
Mod Ver: Apotheosis-1.19.2-6.3.5

Here's the crashlog thru pastebin: https://pastebin.com/jCdeNErQ

Last know working version of mod without crashes is Apotheosis-1.19.2-6.3.0

**Comment by Loufoque09** [comment]
this is a custom modpack for a server btw. It should be up on curseforge if they'd want to test it with other versions of apotheosis.

https://www.curseforge.com/minecraft/modpacks/craft-down-under/files/4691644

**Comment by SiverDX** [comment]
update passive skill tree mod

**Comment by Loufoque09** [comment]
Worked now. Thanks!
