### ISSUE TITLE
Old Gem (removed? / changed?) occupying "Empty Socket" stopping new gem from filling it

### ISSUE THREAD

**Issue by Ashe-Void** [Shadows-of-Fire/Apotheosis#985]
Noticed this on a set of leggings, images below show the context
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/98918267/65a549c3-c587-4ccf-9f0e-76e9e6dbb057)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/98918267/973d9e18-b4db-4335-b771-f0dbf5c9c039)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/98918267/d73b663d-e186-4f46-bba0-4f5d24b47109)

Anyway to fix this without destroying the other gems (Vial of Searing Explusion)

**Comment by Ashe-Void** [comment]
As you can see, a "fake" gem is occupying the Empty socket but on other tools it still shows as blank (These do work with gems)
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/98918267/6c2ff238-c026-45f2-856d-be3ec02548df)

**Comment by Shadows-of-Fire** [comment]
Fixed via side effect of the fix for #984
