### ISSUE TITLE
ConcurrentModificationException via shadows.apotheosis.adventure.affix.AffixHelper.getAffixes

### ISSUE THREAD

**Issue by peter-ahe** [Shadows-of-Fire/Apotheosis#986]
Sorry if this isn't the right place for this bug report.

As far as I can tell, Apotheosis is the mod calling a hashCode method that leads to ConcurrentModificationException.

[crash-2023-08-19_15.59.46-server.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12386072/crash-2023-08-19_15.59.46-server.txt)
 
I'm not exactly sure what I was doing at the time, I was moving loot around.

I'm playing ATM8 version 8-1.0.22 in single player mode, using Minecraft version 1.19.2, and Forge version 43.2.14.

**Comment by erazare** [comment]
for me this started with the update, the first release for 1.20 worked just peachy so far as i could see but the second one kills the server cold

**Comment by Shadows-of-Fire** [comment]
This is a CME, which means something else is accessing and modifying item nbt off-thread.  Unless you can reliably reproduce it and get a thread dump from when the crash happens, this cannot be pursued further.

**Comment by peter-ahe** [comment]
It doesn't have to be a different thread. It also can happen if you're iterating a collection and removes something from it. Concurrent doesn't mean another thread in this case, it just means "at the same time".

I agree that you should close this issue. I've seen a number of crashes like this by now, never again from apotheosis, so I agree that it's like to be a multi-thread issue.

Sorry for the noise.

**Comment by erazare** [comment]
Odd because your latest update resolved all issues. Coincidence?
