### ISSUE TITLE
Ice and fire compatibility issue.

### ISSUE THREAD

**Issue by haltalt** [Shadows-of-Fire/Apotheosis#987]
MC version: 1.18.2
Forge version: 40.2.10
Apotheosis version: 5.8.1
Ice and fire version: 2.1.12

Endless quiver doesn't seem to work with dragon bone bow and arrows. The solution would be to either make the enchantment unapplicable on dragon bone bow or make it function.

**Comment by Shadows-of-Fire** [comment]
1.18 is not supported
