### ISSUE TITLE
Rubidium compatibility issue

### ISSUE THREAD

**Issue by WildTamara** [Shadows-of-Fire/Apotheosis#988]
I haven't found this one in the list of incompatibilities, so posting it here just to be sure. With Rubidium installed there is some trouble rendering the salvage table window - when placing any item inside game crashes. Works fine once Rubidium is gone. Attached is the crash log.
[crash-2023-08-20_19.45.02-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/12388819/crash-2023-08-20_19.45.02-client.txt)

**Comment by Shadows-of-Fire** [comment]
This is purely a rubidium bug, I cannot fix it.

It seems rubidium for 1.20.1 is breaking far more things than it did in 1.19.2 as HNN had a similar issue.

**Comment by SiverDX** [comment]
rubidium 0.7 is the broken version

https://github.com/Asek3/rubidium-upstream/pull/2
merging prs seems to be too big of a task
