### ISSUE TITLE
[1.20] Pulled Attributes Showing Registry Name

### ISSUE THREAD

**Issue by slave2midna** [Shadows-of-Fire/Apotheosis#990]
Not sure if this is normal, or something that can be fixed. But I'm running Apotheosis 1.20.1 with Apotheosis Attributes, and I LOVE it. It's such a good addition and feels really nice. 

However, I noticed that it seems to automatically pull newly added attributes from other mods, and list them as their Registry names. 

I was curious if it was possible to either remove these attributes? Or rename them so they don't show up with strange registry names inside?

Would this be something that would have to be changed in the mod?

**Comment by SiverDX** [comment]
If I understand you correctly you can add language entries for those mods with a resource pack

see https://github.com/Shadows-of-Fire/Apothic-Attributes/blob/1.20/src/main/resources/assets/attributeslib/lang/en_us.json as reference

**Comment by slave2midna** [comment]
OH! Nice! That might work! Thank you - I'm going to try that!

**Comment by Shadows-of-Fire** [comment]
If you can you should tell those mods to add the appropriate language keys for their name (vanilla spec) and the description (AA spec).  Futher issues for attributes should go to https://github.com/Shadows-of-Fire/Apothic-Attributes
