### ISSUE TITLE
custom configuration

### ISSUE THREAD

**Issue by wsxiya** [Shadows-of-Fire/Apotheosis#991]
When used with quark, some tooltips will be displayed. It seems that this is not the case before 1.18.2. I personally like quark's tooltips. Is it supported to turn off the tooltips in the picture? Or support in future updates
![{UM(VQU%4(C(M9MS_0K1ATE](https://github.com/Shadows-of-Fire/Apotheosis/assets/114494454/82fd4cdf-9e82-4481-88a0-220fca31e7f5)
![O5S`_HLD`KO@NE33L% {XJL](https://github.com/Shadows-of-Fire/Apotheosis/assets/114494454/70f652ee-f761-4817-929c-ecce62379301)

**Comment by Shadows-of-Fire** [comment]
This is controlled by `Disable Quark Tooltips for Affix Items` in adventure.cfg

**Comment by wsxiya** [comment]
> 这是由冒险控制的.cfg`Disable Quark Tooltips for Affix Items`

I mean can you just display the "Quark" tooltip
