### ISSUE TITLE
Gem of royal family bug

### ISSUE THREAD

**Issue by ZerausDG** [Shadows-of-Fire/Apotheosis#992]
hi, sorry for my bad english, I use a translator, when you add the royal family gem in the helmet, it does not increase the 10%, it happens is that it is multiplied. i don't know if it's a bug or if it's designed that way.

MC 1.20.1
Forge 47.1.3
Apotheosis  7.0.4
ApothicAttributes 1.0.4

![2023-08-22_15 28 14](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/518d1204-b7b6-41ba-ae88-05db98186f9f)
![2023-08-22_15 28 38](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/5be38c54-f9fe-4497-bff8-325579e34652)
![2023-08-22_15 28 57](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/c3e8391e-9754-46fd-b8e4-1ea07b56b154)
![2023-08-22_15 35 01](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/6f7269a7-330a-4294-915f-51e974d6b4db)
![2023-08-22_15 35 16](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/e9f7cf2c-3096-4c30-8b22-ffc6a996e218)
![2023-08-22_15 35 23](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/91308aba-d539-442e-b091-db36e4128810)
![2023-08-22_15 35 31](https://github.com/Shadows-of-Fire/Apotheosis/assets/106796155/0fbdcd7d-d58c-4ab7-af8c-a1af413bde3a)

**Comment by Shadows-of-Fire** [comment]
The royal family gem is a +20% MULTIPLY_TOTAL to all attributes, which is a `value * 1.2` operation.
