### ISSUE TITLE
Version 7.0.5 Spectator mode not flying

### ISSUE THREAD

**Issue by Dr-WeiAL** [Shadows-of-Fire/Apotheosis#995]
Switching to Spectator mode drops you and prevents you from flying.
Must have Flying effect to achieve normal effect

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce.  I can launch the game with just Apothic Attributes and flight works just fine in spectator mode.  Are you using a version prior to Apothic Attributes - 1.1.3?

**Comment by BiakCeu** [comment]
I also am dealing with this issue. I'm on the latest versions of both apotheosis and apothic attribute. Minecraft version 1.20.1. Maybe it's conflicting with one of my other 300 mods lol. I don't plan to find out though, as I don't really mind it since I don't really use that mode. I thought I'd just say the OP isn't the only one dealing with this issue.

**Comment by Dr-WeiAL** [comment]
> Cannot reproduce. I can launch the game with just Apothic Attributes and flight works just fine in spectator mode. Are you using a version prior to Apothic Attributes - 1.1.3?

[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/12475752/latest.log)
Apotheosis-1.20.1-7.0.5
ApothicAttributes-1.20.1-1.1.3
AttributeFix-Forge-1.20.1-21.0.2
MaxHealthFix-Forge-1.20.1-12.0.2
Placebo-1.20.1-8.3.7

**Comment by Shadows-of-Fire** [comment]
Does removing attributefix produce any change?

**Comment by Dr-WeiAL** [comment]
> Does removing attributefix produce any change?

No, this problem occurs even when using only Apotheosis, ApothicAttributes, Placebo

**Comment by Shadows-of-Fire** [comment]
Can you check your player's value of `attributeslib:creative_flight` while in spectator mode?  It should be 1

**Comment by BiakCeu** [comment]
![2023-08-31_00 39 27](https://github.com/Shadows-of-Fire/Apotheosis/assets/88417452/8c1ae75b-a510-4807-92e3-a23d2e71c51b)
For me it shows 0.0

**Comment by BiakCeu** [comment]
![2023-08-31_01 07 19](https://github.com/Shadows-of-Fire/Apotheosis/assets/88417452/55546cc1-9dd7-4a93-bc64-3b433c96c3b5)
After leaving and rejoining the world, I could fly in spectator mode but when switching back to creative, I am once again unable to fly.

**Comment by Dr-WeiAL** [comment]
> Can you check your player's value of `attributeslib:creative_flight` while in spectator mode? It should be 1

No, even in creative mode this value is 0
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/47446553/88160784-971d-4f68-b7e1-f1e20c9501ad)

**Comment by Dr-WeiAL** [comment]
Incidentally, I found that switching from survival mode to spectator mode is flyable, but switching from creative mode to spectator mode is not.

**Comment by Shadows-of-Fire** [comment]
https://github.com/Shadows-of-Fire/Apothic-Attributes/commit/09a08507a6b72f8f4a466902ec21b2d6ca27c56e
