### ISSUE TITLE
Shield bash is able to be used with other damage boosting enchantments.

### ISSUE THREAD

**Issue by Garwinium** [Shadows-of-Fire/Apotheosis#997]
Some mods have weapons that count as both swords and shields (such as the skelewag skull from Alex's Mobs), due to this sharpness and one other specific damage boosting enchantment (such as smite) can be used with shield bash, allowing for a ridiculously broken weapon.
![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/92835818/77d96e11-36cc-4662-bbe5-2b0162318ebd)

Minecraft version: 1.19.2
Forge version: 43.2.20
Apotheosis version: 6.3.5

**Comment by Shadows-of-Fire** [comment]
There's no way to differentiate between "real" shields and swords, but I could probably make it exclusive with sharpness.
